LibreELEC/LibreELEC.tv

config/functions
config/optimize
packages/lang/Python/package.mk
packages/mediacenter/kodi/package.mk
packages/network/openssh/package.mk
packages/sysutils/systemd/package.mk
scripts/build

see the discussion at https://github.com/OpenELEC/OpenELEC.tv/pull/4661
@MilhouseVH is this ok with you?

stripping changes

---

packages/devel/cmake/package.mk
packages/devel/ncurses/package.mk
packages/lang/llvm/package.mk
packages/network/openssh/package.mk
packages/sysutils/dbus/package.mk
packages/textproc/expat/package.mk
packages/x11/proto/videoproto/package.mk
packages/x11/xserver/xorg-server/package.mk

llvm bump is just the final version, we were using a git version that was close to final before
[xorg-server 1.18.2](https://lists.x.org/archives/xorg-announce/2016-March/002681.html)
[openssh 7.2p2](http://www.openssh.com/txt/release-7.2p2)
[dbus 1.10.8](https://cgit.freedesktop.org/dbus/dbus/tree/NEWS?id=dc8f8c52941f4ecb8e903ed30330f805999d4c08)
[expat 2.1.1](http://expat.sourceforge.net/)
[videoproto 2.3.3](http://permalink.gmane.org/gmane.comp.freedesktop.xorg.announce/2408)
[cmake 3.5.0](https://cmake.org/cmake/help/v3.5/release/3.5.html)
[ncurses 6.0](https://www.gnu.org/software/ncurses/)

llvm, xorg-server, openssh, dbus package updates

---

CONTRIBUTING.md

Incorrect URL mentioned in the instruction for adding an upstream remote.

CONTRIBUTING.md: fix trivial typo

---

packages/linux/patches/4.4.5/linux-231-fix-cx23885-ci-devices.patch

In Linux kernels 4.0-4.5 there is a bug that breaks the common interface of certain DVBSky and TechnoTrend devices. This patch fixes it and can be discarded after fixed upstream kernel (currently it seems 4.6-rc1 is the first working one) is in use.

linux: fix cx23885 bug affecting DVBSky/TechnoTrend cards with CI

---

packages/lang/Python/package.mk

This reverts commit 70ee30ebf92754e333eee3fd72a79c239b7ec4fd.

Revert "Python: don't include _sysconfigdata.py"

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

This includes support for dynamic device tree overlays ([details](https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=139732)) and adds `dtoverlay` userland binary to dynamically load/unload/query device tree overlays.

bcm2835-driver: update to version c230b2b and install dtoverlay userland

---

packages/multimedia/libdvbcsa/package.mk

Needed to build vdr.
```
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-8.0-devel/toolchain/lib/gcc/armv7ve-openelec-linux-gnueabi/5.3.0/../../../../armv7ve-openelec-linux-gnueabi/bin/ld.gold: error: /home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-8.0-devel/toolchain/armv7ve-openelec-linux-gnueabi/sysroot/usr/lib/libdvbcsa.a(dvbcsa_bs_algo.o): requires unsupported dynamic reloc R_ARM_MOVW_ABS_NC; recompile with -fPIC
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-8.0-devel/toolchain/lib/gcc/armv7ve-openelec-linux-gnueabi/5.3.0/../../../../armv7ve-openelec-linux-gnueabi/bin/ld.gold: error: /home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-8.0-devel/toolchain/armv7ve-openelec-linux-gnueabi/sysroot/usr/lib/libdvbcsa.a(dvbcsa_bs_block.o): requires unsupported …
```

libdvbcsa: build with -fPIC

---

packages/mediacenter/kodi/config/os.openelec.tv/addon.xml
packages/mediacenter/kodi/package.mk

This is needed for people moving from OE so their add-ons aren't marked as broken.
This can probable removed for LE 8.0

kodi: readd os.openelec.tv for backwards compatibility

---

scripts/image

This is needed for add-ons that currently check for OPENELEC_ARCH and if not found, default to an arch that may result in unexpected behaviour.
This can be removed for LE 8.0

libreelec: Re-add OPENELEC_ARCH for temporary backwards compatability

---

packages/sysutils/busybox/package.mk
packages/sysutils/busybox/scripts/fs-resize
packages/sysutils/busybox/scripts/functions
packages/sysutils/busybox/scripts/init

Merge this AFTER #27!
This adds various progress indicators during long running update steps:
* a simple spinner `|`, `/`, `-`, etc. for any indeterminately long process (ie. gunzip as we don't know the uncompressed file size)
* a percentage complete indicator during file copies when the file size is known `Updating KERNEL... 28%`
* a countdown indicator, `rebooting in 10 seconds... 10`, `rebooting in 10 seconds... 9` ... `rebooting in 10 seconds... NOW`.
Also improve quality of some error messages, taking the opportunity to explain what options the user has when failing "Check size", and correcting some code indentation issues.

init: Add progress indicators during long running updates

---

scripts/unpack

If the package unpacks correctly, and `PKG_SOURCE_DIR` is being set, we can ignore the `PKG_SOURCE_DIR`.

build: ignore PKG_SOURCE_DIR when not required

---

config/noobs/partitions.json
distributions/LibreELEC/options
packages/tools/installer/config/installer.conf
packages/tools/installer/package.mk
packages/tools/installer/scripts/installer
scripts/image
scripts/mkimage

This is an enhanced version of #49. ping @zalaare .
The default system partition size and offset will be 512MB and 2048 respectively, However this can be overridden by adding `SYSTEM_SIZE` and/or `SYSTEM_PART_START` to `$DISTRO/options` or `$PROJECT/options`.
Since I don't have any x86 systems I'm willing to trash, I've only been able to run a simulated test of the installer, but it seems to work as expected.
Testing with an 8GB SD card, the following partitions were created:
In sectors:
```
Model: Generic- USB3.0 CRW -SD (scsi)
Disk /dev/sde: 15523840s
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:
Number  Start     End        Size       Type     File system  Flags
1      2048s     1050624s   1048577s   primary  ext4         boot
2      1052672s  15522816s …
```

Allow for a custom system partition start sector + custom system size

---

packages/mediacenter/LibreELEC-settings/package.mk

[3924775](https://github.com/LibreELEC/service.libreelec.settings/commit/3924775301338b4e57218a207ee51ebcb40ae20f) This adds the migration function for those moving from OpenELEC.
[f60ceed](https://github.com/LibreELEC/service.libreelec.settings/commit/f60ceed9157a0cfaea04c9a8652ceab1a408ce13) This allows the auto updater to use .img.gz files

LibreELEC-settings: update to 6e3f5df

---

packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml

This removes the OE blue/grey text colouring and multiple mentions of 'official' naming from the LE repo addon.xml

addons: remove OE colours and 'official' text from LE repo

---

packages/mediacenter/LibreELEC-settings/package.mk

fixes the last OE logo and adds text for wait-for-network

settings: bump to v0.7.1

---

projects/RPi/options
projects/RPi2/options

Enabling `console=ttyAMA0,115200` as a default for devel images will result in no framebuffer console, which is frankly more useful to 99% of image users than a serial console.
Anyone that requires a serial console can add `EXTRA_CMDLINE=console=ttyAMA0,115200` to `$HOME/.libreelec/options`.
Although with recent firmware (since RPi3) the console device should now be `ttyS0`, as `ttyAMA0` is used for Bluetooth Serial on RPi3. Not sure if this also applies to RPi1 and RPi2, but could be handled by a project-specific `options` setting.

RPi: Stop enabling serial console in devel images

---

packages/sysutils/busybox/system.d/shell.service
projects/RPi/filesystem/usr/lib/systemd/system/serial-console.service
projects/RPi2/filesystem/usr/lib/systemd/system/serial-console.service

The console cursor is left disabled by `init` after #44.
I've tested `textmode` and that now has a working cursor. I'm assuming the RPi/RPi2 serial console works similarly to imx6 (see #83), but I'm unable to test this.

console: enable cursor for textmode and RPi serial consoles

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Currently we have a new kernel but old firmware from Mar 15, which lacks support for https://github.com/raspberrypi/firmware/commit/1c4f14521087dc557468c2454d0a11e76930ace2 and is [breaking Bluetooth](http://forum.libreelec.tv/thread-64-post-428.html#pid428).
This needs to go into 6.90.005, and adding to the distro server.

RBP: Update firmware to be in sync with kernel

---

scripts/image

Requested by @chewitt to further differentiate community builds from official builds.
Builds from forked repositories will now point to their own issues page ie. https://github.com/chewitt/LibreELEC.tv/issues instead of https://github.com/LibreELEC/LibreELEC.tv/issues.
Builds from the upstream repository will continue to point to https://github.com/LibreELEC/LibreELEC.tv/issues.
Expressions where `official`/`community` is used have been simplified.

image: BUG_REPORT_URL should reflect origin repo used for build

---

packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk

This takes the fixes from `screensaver.shadertoy`
This supercedes #62

visualization.shadertoy: fix build for OpenGLES

---

packages/addons/addon-depends/libiconv/package.mk
packages/addons/addon-depends/libiconv/patches/libiconv-glibc-fix-2.16.patch
packages/addons/addon-depends/vdr/package.mk

- vdr add dependencies
- libiconv is needed for Tvheadend (without this the character conversion won't work)

libiconv: add libiconv package

---

packages/addons/addon-depends/libiconv/package.mk
packages/addons/service/tvheadend/package.mk

libiconv will overwrite glibc iconv.h and cause havoc to the build system. This installs relevent files from libiconv into it's own directory.

tvheadend fix libiconv and cleanup

---

config/arch.aarch64
config/arch.arm

Allows building code with big.LITTLE [optimization](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html).
I use this on one of my community builds (Odroid_XU3).
I removed the aarch32 cpu's from the comments (cosmetic) of the aarch64 file and fixed a seemingly extra sed call with a bash substitution in both aarch32 and aarch64.

Add big.LITTLE support to buildsystem.

---

packages/graphics/mesa/package.mk

I'd like to get this in before beta.
for intel dri3 is broken and disabled at compile time.
nvidia doesn't use the dri system
for radeon dri3 is built in but must be manually enabled via xorg.conf like so
```
Section "Device"
Identifier  "Radeon"
Driver      "radeon"
Option      "DRI3"   "on"
EndSection
```
So this shouldn't harm anything and we can have people test DRI3 on radeon to see if we want to enable this by default in the future.

mesa: enable-dri3

---

projects/RPi2/patches/linux/README.md

@MilhouseVH go over this and let me know if it needs any expansion or clarification
see here for the markdown formatted version
https://github.com/lrusak/LibreELEC.tv/tree/rpi-linux-instructions/projects/RPi2/patches/linux

RPi/RPi2: add linux kernel patch creation instructions

---

packages/network/samba/config/smb.conf

I have no idea why two times root preexec doesn't work here (it works for the log dir).

samba: fix directory creation

---

packages/mediacenter/kodi/scripts/kodi-config

An OE Kodi 16 installation will, naturally enough, have an Addons*.db that is populated with OE addons linked to the `repository.openelec.tv` repo.
However, following the migration to LE, Kodi 16 adds the same addons to Addons*.db, but now for the `repository.libreelec.tv` repo - the old OE addons are still present in the database, even though the `repository.openelec.tv` repo no longer exists.
So now, for example, there will be two `pvr.demo` addons in the `addon` table, one linked to the OE repo (usually with a low id, ie. 8) and again for the LE repo, but now with a much higher id, eg. 980.
When the user attempts to install the `pvr.demo` addon from the LE repository, Kodi seems to use the first addon it comes across, which is typically the addon with the lowest id and thus the legacy …

kodi-config: Hack to work around repo issue following OE-to-LE migration

---

scripts/image

With this patch **make amlpkg** for WeTek creates both SD card and NAND packages. This saves time : one less build run, one less squashfs to create. Another benefit is that KERNEL and SYSTEM images are bit-to-bit equal in all packages.

scripts/image: create SD card image wtih amlpkg

---

packages/devel/ncurses/package.mk
packages/graphics/mesa/package.mk
packages/network/samba/package.mk
packages/virtual/mediacenter/package.mk

On x86, qt5 build uses x11.
Although it's also requiring eglfs to build the associated plugin, which is why we need mesa to support it.
Lastly the mediacenter virtual package assumes that the mediacenter uses skins and themes, which is valid for Kodi, but not necessarilly for other platforms.

Qt5 x86 build modifications 

---

packages/mediacenter/kodi-binary-addons/visualization.wavforhue/package.mk
packages/mediacenter/kodi-binary-addons/visualization.wavforhue/patches/visualization.wavforhue-0001-undo-p8-platform.patch

Included a patch that reverts p8-platform. This patch can be dropped after #98

visualization.waveforhue: initial add-on

---

projects/WeTek_Core/install/updater-script
projects/WeTek_Play/install/updater-script
scripts/image

This allows updating LibreELEC via recovery without wiping userdata while keeping toothpick method work when a clean flash is needed. Without this patch _update_ in ZIP name can be confusing as it does user data wipe.
Ping @codesnake - are you OK with this?

projects/WeTek_*: Move userdata wipe to factory_update_param script

---

scripts/image

In our case we use an alternate image name in order to comply with our client apps updater setup, eg. PlexMediaPlayer-1.0.6.236-1ce41570.RPi2-arm.img
And to allow for custom image naming via the distributions options file we would like to have this added.'
An example of how to add this to the distro file would be for instance to add:
```
CUSTOM_IMAGE_NAME="$DISTRONAME-1.0.6.236-12345678.$PROJECT-$TARGET_ARCH"
```
This would result in: `LibreELEC-1.0.6.236-12345678.Generic-x86_64`
Other uses could be to feed the build with variables during build time:
eg. `CUSTOM_IMAGE_NAME="$DISTRONAME-$MYVARIABLE-$PROJECT-$TARGET_ARCH"`
Which by adding `MYVARIABLE=1.0.6.236-12345678` will result in `LibreELEC-1.0.6.236-12345678-Generic-x86_64`

Add option for CUSTOM_IMAGE_NAME to allow for alternate image naming

---

packages/tools/installer/config/installer.conf
packages/tools/installer/package.mk

This patch allows to define a per distro EXTLINUX_PARAMETERS.
The main goal of this is that you ssh isn't enabled on default distro, and it will only be anbled with thru kodi addon, which we don't have.
defining `EXTLINUX_PARAMETERS` in `$DISTRO/options` allows then to have default ssh

installer : allow to have per distro EXTLINUX_PARAMETERS

---

packages/tools/bcm2835-bootloader/package.mk

This allows another distro to use a different config.txt.
Typically we use alsa for which we need `dtparam=audio=on` to be added to the config.txt.
This would not be a good idea for Kodi, but mandatory for us.

bcm2835-bootloader : allow to have a per distro config.txt

---

config/functions

This PR will allow each distribution to have it's own set of functions that a custom package could use.
It also enables to override some default functions so that they behave slightly differently.
Typically, for each build we release, we dump symbols for a few packages so that we can use minidumps. that requires to override the debug_strip() default function so that we dump the symbols before stripping the binaries.

config/functions : allow to have a per distro functions script

---

scripts/image

Quite often users experience a crash and the crash log is useless without `gdb`. We could offer `gdb` as an addon, but it's too late to capture the crash and users can't be expected to install the addon (assuming they're even able to install addons) and reproduce the crash.
This change will install `gdb` by default. There will be no way to __not__ install `gdb` - it's useful, why would you not want it? Though this could be made optional if required.
The size of `/usr/bin/gdb` is 3.5MB (RPi/RPi2) and 5.2MB (x86), so it will have a small impact on the overall size of SYSTEM.
I think the advantages of having `gdb` installed by default (more useful problem reports) outweigh any disadvantages (mainly, increased image size).
Any concerns, questions, issues? Happy to close if we're unable to …

build: Install gdb for release builds (RFC)

---

packages/network/samba/package.mk
packages/tools/bcm2835-bootloader/package.mk

The distro specific paths for which samba & RPi bootloader are looking are incorrect.
`$DISTRO_DIR`actually points to `LibreELEC.tv/distributions` so we need to add `$DISTRO` there.
Didn't see that before because of build tree remains :(

distros : config files paths fixups

---

packages/tools/bcm2835-bootloader/release

Distro can use a differnt config.txt which is deployed to usr/share/bootloader.
therefore we need to keep the consistency.
This is a follow up of the last PR : https://github.com/LibreELEC/LibreELEC.tv/pull/145

bcm2835-bootloader : make sure we deploy the proper config.txt

---

packages/sysutils/busybox/package.mk
packages/sysutils/busybox/scripts/fs-resize
packages/sysutils/busybox/scripts/init
packages/tools/installer/package.mk
packages/tools/installer/scripts/installer

Allows a distro to have it's name appear in installer and busybox scripts

scripts : remove some hardcoded LibreELEC distro name

---

packages/tools/bcm2835-bootloader/package.mk
packages/tools/bcm2835-bootloader/release
packages/tools/bcm2835-bootloader/scripts/update.sh

dt-blob.bin is used by the Raspberry Pi compute module to move a
number of pins around and possibly change the clock configuration
at boot time.
This isn't used by the Raspberry Pi because a default is build in, but for compute module designs where the default pins are moved this file is used to tell the firmware where those pins are.

Add dt-blob.bin compilation and installation to the system.

---

packages/sysutils/udevil/udev.d/95-udevil-mount.rules

to prevent the RECOVERY partition being mounted at boot

added RECOVERY to partitions not to be mounted

---

tools/repo-tool

This allows you to build add-ons for all projects or a specific project
eg.
to build all add-ons (LibreELEC and kodi binary) for Generic project 
```
./tools/repo-tool -b all Generic
```
to build official add-ons for all projects
```
./tools/repo-tool -b official
```

tools/repo-tool: make it actually usable

---

packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk

Should fix build.
Needs `libwidevinecdm.so` in `/storage/.kodi/cdm`.
When including the addon as a built-in, `libwvdecrypt.so` will be found in `/usr/lib`, but this also needs to be in `/storage/.kodi/cdm` - adding a symbolic link `ln -fs /usr/lib/libssd_wv.so ~/.kodi/cdm/libssd_wv.so` does the trick.
```
curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh -o /tmp/getwidevine.sh && sh /tmp/getwidevine.sh
```
can be used to install `libewidevinecdm.so` (and create the link for `libssd_wv.so`, if available).
Perhaps longer term `wvdecrypt` could/should be built and installed separately from `inputstream.mpd`

inputstream.mpd: fix build

---

packages/x11/xserver/xorg-server/config/xorg-modesetting.conf
packages/x11/xserver/xorg-server/package.mk
packages/x11/xserver/xorg-server/udev.d/97-xorg.rules

Thanks for the tip @fritsch 
apparently,
1. the intel devs suggest using the modesetting driver + glamor
2. Ubuntu 16.04 may ship with the modesetting driver + glamor
I *think* I have done this correctly, but I don't have any intel graphics to test with.
see, https://www.reddit.com/r/archlinux/comments/4cojj9/it_is_probably_time_to_ditch_xf86videointel/

Drop xf86-video-intel, use modesetting driver instead

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

From @popcornmix on slack:
> I think https://github.com/raspberrypi/linux/commit/db8d4644d36ea40d0ff359fa9400f2421f20d00a fixes some omxplayer related hangs on seeking/trickplay. Worth getting into next stable build. 
> Have a play with omxplayer enabled and do some seeking and trickplay. Setting a script to just seek backward every second typically hangs after less than a minute for me. The linked commit fixes that.
Mirror updated.

RBP: Update RPi kernel and firmware

---

tools/distro-tool

This is preventing the updated `mesa` package from downloading successfully.

distro-tool: treat 350 status as valid for ftp

---

packages/mediacenter/LibreELEC-settings/package.mk

settings: bump to v0.7.2

---

packages/security/libressl/patches/libressl-trusted-first.patch

partial backport of #204
This should fix the certificate issue with pandora and any other services that has a certificate that is trusted earlier in the certificate chain sent by the server
Will require recompile of curl and python, they check for `X509_V_FLAG_TRUSTED_FIRST` at compile time

partial backport of #204

---

config/version

The githash of this PR will be the hash visible in Kodi GUI and /etc/os-release. The 7.0.0 tag will point to a different githash once branding changes are merged post release.

set version to 7.0.0

---

packages/tools/procps-ng/package.mk

While I'm grateful for the more functional `top` provided by procps-ng (thanks, @lrusak) I've no idea what the procps-ng developers are smoking but I don't want any of it - the new "modern" default UI scheme for `top` is awful (it's practically unusable) and quite a few other distributions - Arch, OpenEmbedded, Ubuntu 16.04 - would all seem to agree, as they're disabling it by default too.

procps-ng: Default to old top colour scheme

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk

- fixes the problem that DVBC sticks won't work

tvheadend42: update to 4.1.1933

---

packages/mediacenter/kodi/config/appliance.xml

The default number of steps when changing volume is currently 100, which is painful to use with a remote that doesn't support auto-repeat.
@stefansaraev added a GUI option in Kodi 17 that allows the default number of steps to be changed.
I'm proposing we choose a sane system default for LibreELEC. I find 20 (as in this PR) to be quite usable, but 25 or 30 could also work. The existing 100 default is not sane.
An (internal - sorry) poll on the Kodi forum revealed the following preferences:
Steps   | Votes | %
---------|-------|------
10|0|0%
10 < x <= 20*|6|33.33%
20 < x <= 30|2|11.11%
40 < x <= 50|2|11.11%
50 < x <= 60|3|16.67%
60 < x <= 70|0|0%
70 < x <= 80|0|0%
80 < x <= 90|0|0%
90 < x <= 100|5|27.78%
So the majority favoured change, with a bias towards the lower end (20-30).
The object …

kodi: configure volume steps to 20 by default

---

packages/mediacenter/kodi/package.mk

In Kodi 17, if a user drops their Addons*.db there's a risk that `os.openelec.tv` will remain disabled (as this is the new default state for all non-system addons). There's no way to enable the `os.openelec.tv` addon in the GUI, `sqlite3` would have to be used. So we must add this addon to the manifest.

kodi: add os.openelec.tv to manifest while we still ship it

---

packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml

- saves 75% of size/bandwidth
this is untested (@chewitt knows what to do)
I'm unsure what `<hashes>` does - Kodi wiki didn't tell the story (Kodi addon repo has this value).

LibreELEC addon repository: change to xml.gz

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk

- fixes the problem that DVBC sticks won't work

tvheadend42: update to 4.1.1945

---

tools/distro-tool

This fixes a few minors.
`iperf` is returning a unicode-encoded header, that isn't being handled (decode exception).
`lshw` has version `B.02.17` which trips up the major/minor/patch regex: `.02.17` is extracted, which resulted in an exception when converting the blank major component to an `int`.
Drop startup delay.
Reduce number of retries and add a `--max-time` timeout to avoid excessive hanging on really slow servers. Worst case query time should now be about 300 seconds per package (60 seconds for current version, plus 60 seconds for each of the 4 potential version checks). The Gnome ftp servers are particularly bad today...
When querying AWS (Amazon WS, eg. `irrssi` or `jq`, which both redirect to AWS), curl `HEAD` requests return a 403 response (Forbidden). In this case switch to a …

distro-tool: Fixes

---

tools/distro-tool

`u-boot` package.mk is triggering an error due to it calling `exit 0`. Other packages could do something similar, so implement a fix.
`opengl-meson` resolves to version `0.0invalid` - handle this.

distro-tool: Workaround packages that call exit

---

packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml

This backports #175 to the libreelec-7.0 branch. I am publishing addons.xml and addons.xml.gz to the 7.0 repo to ensure we support users on builds before/after this change.

repository: use xml.gz

---

packages/addons/addon-depends/system-tools-depends/depends/efivar/patches/efivar-makeguids-allocate-fix.patch

Without execution (sometimes) fail:
./makeguids guids.txt guids.bin names.bin guid-symbols.S efivar-guids.h
makeguids: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

efivar: allocate enough memory in makeguids tool

---

packages/security/libressl/package.mk

Addons such as Quasar have a dependency on `/etc/pki/tls/cacert.pem`.
http://forum.kodi.tv/showthread.php?tid=269814&pid=2328868#pid2328868

libressl: Add /etc/pki/tls link for backwards compat

---

packages/security/libressl/package.mk

libressl: Add /etc/pki/tls link for backwards compat (backport)

---

packages/mediacenter/kodi/config/advancedsettings.xml
packages/mediacenter/kodi/config/appliance.xml
packages/mediacenter/kodi/scripts/kodi-config
projects/RPi/kodi/advancedsettings.xml
projects/RPi2/kodi/advancedsettings.xml
projects/WeTek_Core/kodi/advancedsettings.xml
projects/WeTek_Play/kodi/advancedsettings.xml
projects/imx6/kodi/advancedsettings.xml

This updates our Kodi 17 configuration following recent updates.
Double buffered is the recommended default for RPi and x86. If WeTek/imx6 prefer the default triple buffered this can become a project default.

kodi: Fixes for various settings

---

packages/addons/addon-depends/system-tools-depends/depends/efivar/patches/efivar-makeguids-allocate-fix.patch

Without execution (sometimes) fail:
./makeguids guids.txt guids.bin names.bin guid-symbols.S efivar-guids.h
makeguids: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

efivar: allocate enough memory in makeguids tool (backport)

---

packages/addons/addon-depends/libmad/package.mk

```packages/addons/addon-depends/libmad/package.mk: line 37: [: ==: unary operator expected```

libmad: fix 'unary operator expected' error

---

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-05-fix-AP-timeout.patch
packages/linux-drivers/RTL8812AU/patches/RTL8812AU-06-disable-power-saving.patch

RTL8812AU: Fix AP timeout and disable power saving (backport)

---

packages/sysutils/busybox/package.mk
packages/sysutils/systemd/scripts/systemd-machine-id-setup

In @kszaq builds (and likely others) multiple hosts report `68b329da9893e34099c7d8ad5cb9c940` as the machine-id hash is being derived from the "/sys/class/net/eth0/address: No such file or directory" error message due to delayed driver loading and no MAC being present. This change sets BLANK as a default value then backgrounds a task that tries at 250ms intervals for 15 seconds until the ethernet or wireless interfaces appear. Once eth0 or wlan0 appear the correct MAC hash overwrites BLANK and is used in all future update queries so that project stats show correctly.

systemd: fix machine-id uniqueness

---

packages/mediacenter/kodi/config/appliance.xml

Moves `pvrpowermanagement.setwakeupcmd` from group 2 to 1.
--
Untested.

kodi: update appliance.xml after settings reshuffle.

---

packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk

the last bump caused a problem where the version was from the wrong upstream repo.

inputstream.mpd: update to latest master

---

projects/imx6/options

to use kernel 3.14 from solidrun use extra build parameter LINUX_VERSION="sr-3.14"

projects/imx6: use Linux kernel 4.4 by default

---

projects/imx6/options

to use kernel 3.14 from solidrun use extra build parameter LINUX_VERSION="sr-3.14"

projects/imx6: use Linux kernel 4.4 by default (backport)

---

packages/mediacenter/kodi/patches/kodi-999.16-PVR-fix-EPG-search.patch

Lets try this again shall we.
This affects all Platforms, blank screen when using the PVR search function.
Krypton backport.

Kodi: fix EPG search bug for all projects

---

packages/addons/driver/sundtek-mediatv/package.mk

This now builds properly for the aarch64 platform like the S905 C2.

Sundtek-mediatv: use ARM64 installer for aarch64

---

tools/distro-tool

Some packages respond with an html error page (and 200 response) when querying package version. Ignore responses with content type `text/html`.
Make sure we only process github results when content type is `application/json`.

distro-tool: Ignore text/html responses

---

packages/addons/service/mpd/package.mk

Apparently the current mpd is using a shared libogg, which no longer exists. The addon needs to static link libogg.
@chewitt can you make sure this addon gets a clean build, please? Thanks.

mpd: Bump rev, needs a clean build (static link libogg)

---

packages/tools/mtools/patches/mtools-05-fix-install.patch

I just was hit by the info/dir: empty file issue again during an RPi build of 7.0.1 - the fix didn't seem to have made it into the 7.0 branch

backport of #257

---

packages/addons/addon-depends/rpi-tools-depends/Adafruit_Python_GPIO/package.mk
packages/addons/addon-depends/rpi-tools-depends/Adafruit_Python_LED_Backpack/package.mk
packages/addons/addon-depends/rpi-tools-depends/Adafruit_Python_PureIO/package.mk
packages/addons/tools/rpi-tools/package.mk

add support for LED-backpacks like HT16K33 into the rpi-tools addon

RPi-Tools: add same Adafruit library for LED backpacks

---

packages/addons/addon-depends/faad2/package.mk
packages/addons/addon-depends/faad2/patches/faad2-2.7-automake_1.13.patch
packages/addons/addon-depends/faad2/patches/faad2-2.7-mp4ff_shared.patch
packages/addons/addon-depends/libmad/package.mk
packages/addons/addon-depends/libmad/patches/libmad-0.15.1b-automake_1.13.patch
packages/addons/addon-depends/libmad/patches/libmad-0.15.1b-cflags-O2.patch
packages/addons/addon-depends/libmad/patches/libmad-0.15.1b-cflags.patch

backported from 8.0, these are required for mpg123 and sqeezelite in #373

addons: add libmad and faad2 to addon-depends

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/dtc/package.mk

Backport of #371.
`dtparam` should be included as a RPi userland binary (complimentary to `dtoverlay`, added some time ago).. However without `dtc`, `dtparam` won't work.
@chewitt: This is not essential for 7.0.2 so if not required then by all means close, but equally shouldn't cause any problems.

dtc: add package (backport)

---

packages/mediacenter/kodi/system.d/kodi.service

See forum thread: http://forum.kodi.tv/showthread.php?tid=276075
From nvidia driver README.txt:
```
11F. OPENGL YIELD BEHAVIOR
There are several cases where the NVIDIA OpenGL driver needs to wait for
external state to change before continuing. To avoid consuming too much CPU
time in these cases, the driver will sometimes yield so the kernel can
schedule other processes to run while the driver waits. For example, when
waiting for free space in a command buffer, if the free space has not become
available after a certain number of iterations, the driver will yield before
it continues to loop.
By default, the driver calls sched_yield() to do this. However, this can cause
the calling process to be scheduled out for a relatively long period of time
if there are other, same-priority processes …
```

nvidia: Enable USLEEP to reduce CPU load while rendering

---

packages/x11/other/fluxbox/config/keys

When running Spotify in a container, I found that there is actually no way to exit Spotify in the application itself. Having a keybinding to close the window in Fluxbox can be handy.

fluxbox: add key binding alt + escape to close window

---

packages/addons/service/oscam/changelog.txt
packages/addons/service/oscam/package.mk

updates OSCam and fixes (WeTek_Play) - OSCam did not work
>[WARNING] parser: The timediff for TELETEXT is big (3249104422), using current dts
[  ERROR] descrambler: ECM late (18 seconds) for service "abcdefgh"

oscam: update to 11233

---

packages/addons/service/oscam/changelog.txt
packages/addons/service/oscam/package.mk

updates OSCam and fixes (WeTek_Play) - OSCam did not work
>[WARNING] parser: The timediff for TELETEXT is big (3249104422), using current dts
[  ERROR] descrambler: ECM late (18 seconds) for service "abcdefgh"

backport of #399

---

packages/lang/gcc/package.mk

Compiling gcc 5.3.0 with gcc 6 fails. Using -std=gnu++98 remedies this.

gcc: compile with -std=gnu++98 to fix build with gcc6

---

packages/lang/Python/package.mk

#301 broke compilation of the curses module for some. We need netbsd-curses:host and a patch to fix this:
`/root/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/Python-2.7.11/Modules/_cursesmodule.c: In function 'PyCursesWindow_EchoChar':
/root/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/Python-2.7.11/Modules/_cursesmodule.c:808:18: error: dereferencing pointer to incomplete type 'WINDOW {aka struct __window}'
if (self->win->_flags & _ISPAD)`

Python: don't build curses and readline modules for host

---

config/noobs/partition_setup.sh
distributions/LibreELEC/options
packages/tools/bcm2835-bootloader/files/3rdparty/bootloader/config.txt

For comment: I'm generally against swapping the (c) marking we inherited but in this case the files end up being user-visible on the noobs SD card and we've had a couple of cases where people are unsure whether they're using LE or OE due to the headers. For config.txt I added a URL link to the OE original following the existing form in the file.

cosmetic changes for noobs

---

packages/sysutils/busybox/scripts/init

https://github.com/LibreELEC/LibreELEC.tv/pull/353#issuecomment-223090789

init: Parse resolution after splash.conf

---

packages/addons/addon-depends/libid3tag/package.mk

This dependency was missed in the 7.0 backport .. fully tested (mpd is already in the repo)

mpd: add libid3tag package to addon-depends

---

scripts/checkdeps

``This allows to build OpenELEC on OpenSUSE 42.1 and most probably earlier.``
tx at @kad

scripts/checkdeps: add support for OpenSUSE

---

packages/sysutils/systemd/scripts/systemd-machine-id-setup

machine-id.service can fail on first boot (noticed in noobs installs) if /storage/.cache hasn't been created by systemd-tmpfiles-setup.service before machine-id.service runs. Adding a dependency breaks stuff so this is simpler.

systemd: ensure /storage/.cache exists before writing machine-id

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

backport of #429 (docker: update to 1.11.2)

---

packages/tools/mtools/patches/mtools-01-fix-creation-of-dot-directories.patch

See: https://lists.gnu.org/archive/html/info-mtools/2014-08/msg00000.html
Without this patch we sometimes experience corrupted MSDOS directories in the image.
```
fsck from util-linux 2.27.1
fsck.fat 3.0.28 (2015-05-16)
/OVERLAYS/.
Bad short file name (.).
Auto-renaming it.
Renamed to FSCK0000.000
/OVERLAYS/..
Bad short file name (..).
Auto-renaming it.
Renamed to FSCK0000.001
/OVERLAYS/FSCK0000.000
File size is 0 bytes, cluster chain length is > 0 bytes.
Truncating file to 0 bytes.
Performing changes.
```

mtools: Fix creation of dot directories (. and ..)

---

packages/tools/bcm2835-bootloader/scripts/update.sh

This should help clean up any systems with trashed /flash/overlays folder.
I'd also suggest this as a backport to 7.0.2

RPi: Add a cleanup step

---

packages/network/samba/system.d.opt/nmbd.service
packages/network/samba/system.d.opt/smbd.service

This was removed in the samba refactor, it's needed to actually disable samba via our settings add-on

samba: actually allow it to be disabled

---

packages/tools/bcm2835-bootloader/files/3rdparty/bootloader/config.txt
packages/tools/bcm2835-bootloader/package.mk
packages/tools/bcm2835-bootloader/scripts/update.sh

We noticed that our custom config.txt isn't being copied from the system image to the bootloader on updates.
This should allow for a string in the config.txt file to be matched and version checked. So if custom version on system image is higher than on the bootloader it will update it.
Thoughts are welcome.

Add Custom config.txt copy to boot loader during update and version check

---

packages/audio/alsa-utils/scripts/soundconfig

To avoid audio crackling on digital audio on the RPi we need to change the Master/PCM audio volumes to 0db instead of 100%. 100% results in 104db, so a 4db amplification on the RPi and causes a bad experience with audio crackling when playing music.

Fix digital audio crackling when playing music on non Kodi based setups.

---

packages/linux-firmware/wlan-firmware/package.mk

This is in anticipation of https://github.com/LibreELEC/wlan-firmware/pull/1 - if it doesn't merge I'll update the version of this PR back to 0.0.31 and then it's just a package URL change.

wlan-firmware: bump to 0.0.32

---

packages/x11/xserver/xorg-server/config/xorg-modesetting.conf
packages/x11/xserver/xorg-server/package.mk
packages/x11/xserver/xorg-server/udev.d/97-xorg.rules

This reverts commit fee76beb720901d4ae7f754f0ff8bf611e0ede1a.
the modesetting driver is only good for newer intel chipsets. Maybe we can find a way to differentiate intel chipsets in the future and decide the xorg driver based on that but for now this is better.

Revert "Merge pull request #136 from lrusak/modesetting"

---

packages/sysutils/systemd/package.mk

See https://forum.libreelec.tv/thread-560.html for background info
Please review if the change is correct, I'm not 100% sure why MaxRetentionSec had been set to 1day.
For a quick test if it works just set the date into the future (eg date -s 2020-01-01) and see if the journal is still there.

fix journal truncation on time jumps

---

packages/multimedia/ffmpeg/package.mk

Discussing the proposed ffmpeg changes (#477) on slack brought up an issue with the current ffmpeg versioning.
If a builder downloads the 3.0-xbmc ffmpeg source tarball (as I did at the end of March) to their `sources` cache they won't ever download the 3.0-xbmc ffmpeg source tarball again even if is updated with new commits (unless they delete their existing tarball).
The current 3.0-xbmc ffmpeg version is now 3.0.2, which is 33 commits ahead of the 3.0.1 version I downloaded in March.
Someone building master who has never downloaded the ffmpeg tarball will build with the latest 3.0-xbmc (ie. 3.0.2, plus a few more commits) while I will continue building with 3.0.1, blissfully ignorant of any new fixes (or new bugs).
This clearly isn't a good situation, as we should all be building the …

ffmpeg: Switch to revision based versioning, not release

---

packages/multimedia/libva-intel-driver/package.mk
packages/multimedia/libva-intel-driver/patches/libva-intel-driver-01-update-pci-ids.patch
packages/multimedia/libva/package.mk

This bumped version of `libva-intel-driver` includes the custom patch I've had in my Generic builds for the last few weeks (thanks @fritsch): http://nmacleod.com/public/oebuild/patches/00_intel_CSC_average_logic.txt

libva/libva-intel-driver: update to 1.7.1

---

packages/audio/pulseaudio/package.mk

This should be pretty safe to merge as it's only used for bluetooth audio.

pulseaudio: update to 9.0

---

scripts/clean
scripts/skip_unpack
scripts/unpack

NOTE: This will require a clean build! Best to include next time we bump something which requires a clean build, such as gcc or similar.

build: start using .libreelec-unpack

---

.gitignore
Makefile
config/options
config/path

Saw this communicated elsewhere, and thought I'd take a dig at it.
Moved ccache for given project to its build.project directory.
`make clean` will blow it up along with the project.
No changes to current CCACHE_CACHE_SIZE="30G"

libreelec: use build project directory for ccache

---

packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.upse/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.wsr/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk
packages/mediacenter/kodi-binary-addons/visualization.pictureit/patches/visualization.pictureit-01-rename_find_package_to_Kodi.patch
packages/mediacenter/kodi-binary-addons/visualization.wavforhue/package.mk
tools/mkpkg/update_binary-addons

Bump those addons not officially supported by https://github.com/xbmc/repo-binary-addons
Unlike officially supported Kodi binary addons, these "unofficial" binary addons will be blindly bumped - they may or may not be compatible with latest Kodi, as is the case with `visualization.pictureit` which requires a slight modification to build against latest Kodi (which might suggest there is and will be ongoing maintenance/support issues with this add-on - consider dropping?)

kodi-binary-addons: Update unofficial addons

---

packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
packages/addons/tools/multimedia-tools/changelog.txt
packages/addons/tools/multimedia-tools/package.mk

Remove IR support from squeezelite, which is unlikely to ever be used on LE

squeezelite: remove ir

---

packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
tools/mkpkg/update_binary-addons

Certain binary addons are configured in Kodi to use a different repo to the repo our package will ultimately build.
For example:
`inputstream.mpd` (Kodi: mapfau, LE: libertydeveloper)
`screensaver.shadertoy` (Kodi: afedchin; LE: popcornmix)
This means we will pull a rev (version) based on the Kodi repo, then build our repo using this wrong rev. Often this works, as the repo we are using is a fork of the Kodi repo, but it does mean the version of the code we use is not necessarily the latest for the repo we ultimately build.
This change to `update_binary-addons` will detect when the Kodi repo does not match our package repo, and will defer processing of the repository treating it as an "unofficial" addon.

kodi-binary-addons: Fix update_binary-addons

---

config/options

If `LIBREELEC_VERSION` is ever set in `$HOME/.libreelec/options` or `$HOME/.libreelec/projects/$PROJECT/options` (eg. `7.0.2`) the `DEVTOOLS` option would always be set to `yes` whenever the tree value for `LIBREELEC_VERSION` is `devel`. This corrects that error.

build: evaluate DEVTOOLS after $HOME options

---

packages/mediacenter/kodi-theme-Estuary/package.mk
packages/mediacenter/kodi/package.mk

The package on the mirror is `f3ca4ea`, which I could change/regenerate, but our standard is 7-chars so fixing that instead.

kodi: Fix package version

---

scripts/image

This file is not needed as it's included in "full" ZIP already. Keeping this file confuses some people.

scripts/image: don't copy *-update.zip to target directory

---

packages/multimedia/libamcodec/package.mk

Let libamcodec build properly for other aarch64 Amlogic targets.

libamcodec: make source arch-specific, not project-specific

---

packages/sysutils/busybox/package.mk
packages/sysutils/busybox/scripts/init

This fixes updating LE from img.gz when installed on WeTek internal memory.

init: Fix updating from img.gz when kernel resides on block device

---

packages/multimedia/ffmpeg/package.mk

I wanted to know how building FFmpeg for LibreELEC compared to a vanilla FFmpeg cross compilation. I think this is it.
~~The only update is that --enable-pic was added for aarch64.~~
The ~~other~~ changes should be cosmetic:
- removed the default and autodetected build options
- removed superfluous variables (FFMPEG_CPU, FFMPEG_FPU and FFMPEG_PIC)
- split the code into logic for dependencies and logic for pre_configure_target.
The output of the configure step is the same as with the previous version of ffmpeg for Generic and RPi2. We could maybe use Jenkins to check the other builds

ffmpeg: rework

---

packages/multimedia/libbluray/package.mk
packages/multimedia/libbluray/patches/libbluray-01-bump_to_Nevcairie_v0.9.2.patch

The Nevcairie commit is from: http://git.1f0.de/gitweb?p=libbluray.git;a=summary;js=1
This adds improved 3D ISO support for RPi. Probably not much use for anything else.
Once merged should fix `clpi_parse.h` build issue.

libbluray: update to 0.9.3

---

packages/virtual/corefonts/package.mk
packages/x11/other/fontconfig/package.mk

So we use our own fonts on Plex Media Player and Liberation fonts break our fonts as fontconfig is hardcoded to /usr/share/fonts/liberation.
This PR should address that with an option to put an alternate font using distro option file.

Enable custom fonts to be installed in place of liberation fonts

---

packages/mediacenter/kodi/patches/kodi-999.23-PR9696.patch

backport https://github.com/xbmc/xbmc/pull/9696 to Jarvis
this should fix a known issue after kodi moved skin settings out of guisettings.xml (fixed in krypton) but I am unable to build / runtime test it, so please do a quick test before merging
ref: https://forum.libreelec.tv/thread-53.html

kodi: fix for saving sking settings on shutdown

---

scripts/image

Update script image to expose build filename so that it can be accessed by external scripts; i.e. copying builds from Jenkins to web03.

Update image script to expose build filename

---

packages/x11/driver/xf86-video-nvidia/package.mk

http://www.nvidia.com/download/driverResults.aspx/105343/en-us
Not tested (will include in my build tonight).
No change to supported models, so no change to udev rules.

xf86-video-nvidia: update to 367.35

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

This updates Syncthing to the latest stable release.
Builds and runs for RPi2.
Should also be backported to LE7.

syncthing: update

---

packages/mediacenter/kodi/patches/kodi-100.17-dbupgrade-dynamic-splash-message.patch

This is based on the work of @MrMC: https://github.com/MrMC/mrmc/commit/dcf671d09393eede19255f448d86d5d054ddd843
Details of each database to be upgraded will be overlayed on the Kodi splash image. If the user has disabled the Kodi splash image, the Kodi splash image will be displayed anyway during database migrations.
Tested with MySQL migration of Videos and Music. Should work when migrating SQLite databases, and also when migrating other databases eg. Addons etc.
This is just a temporary solution until the issue of database migrations is solved upstream in Kodi (this fix will not be accepted upstream due to the Splash dependency being added to Database). However as there is no timeframe on such a solution, this is better than nothing.

kodi: database migration splash text

---

projects/WeTek_Core/initramfs/platform_init
projects/WeTek_Play/initramfs/platform_init

This commit checks the resolution capabilities of the hdmi device and sets the framebuffer resolution depending on the max resolution of the device and the selected resolution by hdmimode boot parameter.
Tested with WeTek Core and Beelink MXIII (S802) connected to a 4K Hisense tv.
**Edit**: Nothing. :D

WeTek: Set the resolution more precisely at boot

---

packages/sysutils/lcdproc/package.mk

With enabled LCD_DRIVER  `glcd`  lcdproc fails to build, because freetype from my host was used ```-I/usr/include/freetype2```
```
...
checking if freetype support has been enabled... yes
checking for armv7a-libreelec-linux-gnueabi-freetype-config... no
checking for freetype-config... /usr/bin/freetype-config
configure: WARNING: using cross tools not prefixed with host triplet
checking for FreeType -- version >= 7.0.1... cross compiling; assuming OK... yes
...
/home/michael/workspace/LibreELEC.tv/build.LibreELEC-imx6.arm-8.0-devel/toolchain/bin/armv7a-libreelec-linux-gnueabi-gcc -DHAVE_CONFIG_H -I. -I/home/michael/workspace/LibreELEC.tv/build.LibreELEC-imx6.arm-8.0-devel/lcdproc-0.5.7-cvs20140217/server/drivers -I../..  -I/home/michael/workspace/LibreELEC.tv/build.LibreELEC-imx6.arm-8.0-de …
```

lcdproc: do not use freetype from host

---

projects/WeTek_Core/initramfs/platform_init
projects/WeTek_Play/initramfs/platform_init

It's the licence update in the files, which was discussed after the PR was already merged: https://github.com/LibreELEC/LibreELEC.tv/pull/541#discussion-diff-71088815

Licence updated

---

packages/sysutils/lcdproc/package.mk

from: http://lcdproc.sourceforge.net/docs/lcdproc-0-5-7-user.html#glcd-howto
>  The glcd driver (graphic lcd) driver is a "meta driver" that renders text for display on graphic displays. It uses either a built-in 5x8 font (the same as used in elsewhere in LCDproc) or Freetype 2 to draw the characters and icons into an internal frame buffer. That frame buffer is then copied to the display by a small sub-driver called connection type driver (CT-driver).

lcdproc: LCD_DRIVER glcd should depend on freetype

---

packages/sysutils/systemd/patches/systemd-09_ignore-storage-flash-mount-points.patch

The default [`systemd-halt.service`](https://github.com/systemd/systemd/blob/master/units/systemd-halt.service.in) will unmount all mounted file systems prior to shutting down the system.
Unfortunately, this means that systemd attempts to unmount `/storage` early in the shutdown process when `/storage` is still in use (for various purposes, most notably the system journal, plus `/storage/.config` as we haven't executed any shutdown scripts yet...), and consequently the unmount of `/storage` always fails.
Here is the shutdown log based on current master when booting Generic on i5 NUC - note that I have two additional mount points `/storage/freenas` and `/storage/data` that are being correctly unmounted:
```
Jul 17 21:03:43 NUC systemd[1]: Stopping Udevil mount service...
Jul 17 21:03:43 …
```

systemd: Do not unmount /storage and /flash at shutdown as this always fails

---

packages/network/connman/package.mk

Minor bump to 1.33 .. and it's time to loose the warning message; it's mature code.

connman: bump to 1.33

---

config/functions

If some packages want to use strip_lto and use the TARGET_FLAGS, those still have the lto flags.

functions : Make sure sure we also remove lto flags from TARGET_FLAGS.

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/go/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch
packages/addons/service/docker/source/config/docker.conf
packages/addons/service/docker/source/systemd/service.system.docker.service

This is a pretty big change, I've tested it quite thoroughly on my RPi and RPi2
I changed to the storage driver overlay2 as this uses the updated overlayfs in kernel 4.0+.
People can manually change to the overlay2 driver by editing or removing the file
`/storage/.kodi/userdata/addon_data/service.system.docker/config/docker.conf`
then restarting docker (or rebooting)
I'll update this to 1.12 final when it is released (which should be soon)

docker: update to 1.12.0

---

packages/tools/u-boot/scripts/update.sh

Check if imx6-system-type exist has wrong path. It seems that error happened at renaming openelec to libreelec.

u-boot: Fix update.sh script for imx6

---

packages/devel/glib/package.mk
packages/tools/qemu/package.mk
packages/virtual/virtual/package.mk
projects/Virtual/config/ovf.template
scripts/image
scripts/mkimage

This is a placeholder PR until this is cleaned up and finalized.
We are trying to make VMware and Virtualbox images during the regular `make image` process.  They should be generic enough to "just work" for use and be sane enough to handle both older versions of VB, or VMware.
Current status:
*VMware*
- Import .ova file works as expected.
- vmdk needs to be physically expanded by the user prior to booting for the first time or the storage partition will continue to stay the 32MB (which may be fine for the user).
- If [PR#205](https://github.com/LibreELEC/LibreELEC.tv/pull/205) is used in conjunction, then user can resize disk at any point, then use the Reset LE to defaults option.
- sound is working now
*Virtualbox*
- Import .ova file works as expected.
- image uses vmdk, so if the user …

Virtual Project Staging

---

packages/mediacenter/kodi/patches/kodi-999.99-PR10211-videoplayer-fix-handling-of-progressive-content-in-rendermanager.patch

17.0alpha3 video playback is rendered as a green screen on Generic and therefore unwatchable without this Beta1 fixer-upper.

kodi: Fix green screen on Generic

---

packages/addons/service/spotify-connect-web/changelog.txt
packages/addons/service/spotify-connect-web/package.mk
packages/addons/service/spotify-connect-web/source/bin/spotify-connect-web.start
packages/addons/service/spotify-connect-web/source/default.py
packages/addons/service/spotify-connect-web/source/resources/language/English/strings.po
packages/addons/service/spotify-connect-web/source/resources/settings.xml
packages/addons/service/spotify-connect-web/source/settings-default.xml
packages/addons/service/spotify-connect-web/source/system.d/service.spotify-connect-web.service

This turns a RPi2/3 into a Spotify Connect device.
To try it out:
1. Install the addon
2. Get your spotify_appkey.key from [here](https://devaccount.spotify.com/my-account/keys/)
3. Place the spotify_appkey.key in the addon home folder
4. Configure Spotify username and password via the addon settings
5. Redirect Spotify streams from your device to LibreELEC
6. Enjoy!
Other implementations (native, docker) proved rather impractical,

spotify-connect-web: initial addon

---

packages/graphics/bcm2835-driver/package.mk

Pushing this as an alternative to #605.
On RPi the `libEGL`/`libGLESv2` libraries are now called  `libbrcmEGL`/`libbrcmGLESv2`. This breaks addons that expect to link against `libEGL`/`libGLESv2`.
The background for the renaming is in this change: https://github.com/raspberrypi/firmware/issues/625#issuecomment-230356111.
This PR will create sym links in the toolchain that will allow RPi builds to appear "normal" as far as `libEGL`/`libGLESv2` are concerned, allowing untouched addons to build against these libraries (that are just symbolic links to the real things - `libbrcm*`).
We already include sym links in the image for `libEGL`/`libGLESv2`, to `libbrcm*`, these are intended for backward compatibility but while we ourselves continue to link against `libEGL`/`libGLESv2` they will always …

RBP: Add GL symlinks to toolchain

---

packages/graphics/bcm2835-driver/package.mk

Apologies for this. This is an update for #606. We need to use `-f` when creating symbolic links in the toolchain as the symbolic link may already exist from a previous build (and without `-f` the attempt to create the symbolic link will fail).

RBP: Use force when creating symbolic links in toolchain

---

projects/WeTek_Core/install/updater-script

This PR revises the updater-script for WeTek Core. The script checks now if the previous installation is android. If this is the case, the (user) data partition will be wiped. Otherwise the (user) data will be untouched by the update. I also restructured it a tiny bit.
Something similar would also make sense in the updater-script for WeTek Play imho. I don't have one, that's why I can't test it.
Can someone recheck the script? @codesnake @stefansaraev @kszaq 
PS: Heavily tested it on my WC.

WeTek_Core:Revised install/update procedure

---

packages/addons/driver/sapphire/changelog.txt
packages/addons/driver/sapphire/package.mk

According to https://forum.libreelec.tv/thread-634-post-8597.html#pid8597 the driver is not working in v7.90.004 and dmesg reports:
```# dmesg | grep sapphire
[    6.825862] sapphire: version magic '4.6.3 SMP mod_unload ' should be '4.7.0 SMP mod_unload '```
So this is just a plain version bump to rebuild against 4.7 kernel and ensure update. 
NB: It concerns me to discover this add-on is kernel version sensitive as we cannot assume that all users will be on latest LE version (with latest LE kernel). If any users are still using 001-003 builds this will break it for them, which is fine while we're in alpha, but is not acceptable once we move to beta and beyond.

saphire: rebuild against 4.7 kernel

---

scripts/image

The $RELEASE_DIR will be removed now after building a WeTek Core/Play image. I also revised the line indention for better reading.

WeTek: RELEASE_DIR removing fix

---

packages/mediacenter/kodi/config/appliance.xml
packages/mediacenter/kodi/patches/kodi-999.99-detect-intel-gpus.patch
projects/Generic/filesystem/etc/X11/xorg-i915.conf
projects/Generic/filesystem/usr/bin/intel-fullrange.sh
projects/Generic/filesystem/usr/lib/systemd/system/intel-fullrange-resume.service
projects/Generic/filesystem/usr/lib/systemd/system/intel-fullrange.service

@fritsch I've had these three commits in my Generic builds for quite a while now, originally from your OE repo. Are they all still needed? If not please let me know which (if any) should be dropped. Thanks.

kodi/Intel: Various improvements from fritsch

---

scripts/mkimage

for all projects, useful when disk is mounted showing nice label LIBREELEC instead of numbers or NO NAME (like with our USB-SD creator tool)
label is all upper case but this could be changed with fatlabel from dosfstools
tested with imx6 and Generic without visible side effects

scripts/mkimage: set real volume label on system partition

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk
packages/addons/addon-depends/emby-depends/imagemagick/package.mk
packages/addons/addon-depends/emby-depends/x264/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk
packages/addons/service/emby/source/bin/emby.start
packages/addons/service/emby/source/resources/language/English/strings.po
packages/addons/service/emby/source/resources/settings.xml

This enables optional platform specific hardware transcoding to Emby. h264_omx transcodes a 1080p stream faster than it is be played, but still displays the stream on the screen. Basis for testing and further improvement.

emby: update and enable optional platform specific hardware transcoding

---

packages/addons/addon-depends/emby-depends/imagemagick/package.mk

needed for emby; 6.9.5-4 is not on the upstream server so use 6.9.5-5 instead

imagemagic: udpate to 6.9.5-5

---

tools/distro-tool

1) Fix error when specifying `--all` - packages that should have been downloaded were ignored
2) Generate package workload using multiple threads, resulting in significantly improved startup performance on ARM quad-core server. Maximum number of threads can be configured with `WORKER_MAX` environment variable (default: number of available cores).

distro-tool: Fix error, improve performance

---

packages/linux-drivers/brcmap6xxx-aml/config/config.txt

This disables WiFi power saving by default, most visible in delays when typing over SSH. Power saving can be turned back on by user on demand.

packages/linux-drivers/brcmap6xxx-aml: disable power saving by default

---

packages/devel/netbsd-curses/package.mk

This was missed when backporting multimedia-tools add-on changes

netbsd-curses: backport package to support #640

---

packages/linux-drivers/brcmap6xxx-aml/config/config.txt

This enables 150Mbps using 2.4Ghz band. 5Ghz unaffected (at least with 802.11n).

packages/linux-drivers/brcmap6xxx-aml: enable 40MHz channels for 2.4G

---

projects/Odroid_C2/patches/kodi/kodi-0001-enable-OMX_PTS64.patch

just a note on this: omx_pts_interval_lower is NOT set by the amvideo driver if using hardkernels 3.14 linux kernel. Therefore kodis AMLCodec assumes that omx_pts is 32 bit wich is not true.
On Wetek Hub omx_pts_interval_lower is set, because of this it runs well on Wetek devices.

odroidc2_64_bit_omx_pts

---

packages/sysutils/busybox/scripts/init

Now that the RPi3 can boot entirely from the network without an SD card\[1] (once the updated RPi firmware makes it into master), it's possible to configure multiple devices to boot from a single networked boot (System) partition/folder\[2]. However in this situation each client still needs to use a unique disk (Storage) partition/folder, which is tricky when there is only a single static `cmdline.txt` configuration file for all clients (retrieved from the shared boot partition).
In order to automatically match the booting client with the matching network Storage share, I've added the concept of a `@UID@` token which, in the case of the RPi[1-3], will be replaced by the serial number of the booting device (eg. `ff449f90`, `3b952c03` etc.).
There is no support at the moment for other …

init: mount per-client boot/disk if available & configured

---

scripts/image

I automatically increment the build code in my builds, which (after a long day) resulted in a build code of "160826|" (having blown past `a`-`z` and `{` - yes I know it's lame, but that's not the point).
Anyway, once we had an image filename of the form `LibreELEC-RPi2.arm-8.0-devel-20160826202024-#0826|-ga0e3207.system` the fakeroot script choked as follows:
```
Version: Linux version 4.7.2 (email@address.com) (gcc version 5.4.0 (GCC) ) #1 Fri Aug 26 19:48:52 BST 2016
DT: y
DDT: y
270x: y
283x: n
...done
/home/neil/projects/LibreELEC.tv/.fakeroot.build.LibreELEC-RPi.arm-8.0-devel: line 6: -ga0e3207.system: command not found
/home/neil/projects/LibreELEC.tv/.fakeroot.build.LibreELEC-RPi.arm-8.0-devel: line 7: -ga0e3207.system: command not found
Makefile:9: recipe for target 'release' …
```

image: fakeroot chokes on image names with meta chars

---

packages/sysutils/busybox/scripts/createlog

This PR will add governor (cpufreq) details to the 03_Hardware.log.
Modern Intel CPUs will use Intel P-States, while non-Intel (or older Intel) hardware will use one of the in-kernel CPUFreq governors.
Not all hardware will use the same CPUFreq governor, eg. RPi/RPi2 will use `ondemand` (default in the kernel, and then forced in `platform_init`), while WeTek_Hub will use `hotplug` (even though the kernel default is `performance`), and other hardware/platforms may use `performance` or `ondemand` (eg. the Revo 3700 - Intel Atom D525 - will use `performance` even though the default governor for Generic is `ondemand`).
So, having this information written to the logfiles might be useful...
Not all hardware will have accessible governor details (eg. Xstreamer Ultra2) in which case less …

logfiles: Add CPU governor details to 03_Hardware.log

---

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-05-fix-AP-timeout.patch

This corrects the patch in #654 with an increased timeout value instead of deleting it.

rtl8812au: fix AP timeout value patch

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk

Wow!
The latest xbmc/ffmpeg release significantly improves h264 omx transcoding performance on RPi.
CPU usage is reduced from ~400% to ~200% on a RPi 3.
Transcoded stream is however still displayed on the screen.

emby: update and rebuild ffmpegx

---

packages/mediacenter/kodi/patches/kodi-999.99-Revert-PR10247.patch

See https://github.com/xbmc/xbmc/pull/10247
@FernetMenta is on holiday and with the imminent release of 7.90.005 it would be better to revert PR10247. There is a partial fix, https://github.com/xbmc/xbmc/pull/10367, however seeking remains a bit off in which case from the user experience point of view reverting the entire change is best.
The OOM issue will no doubt be fixed (in Kodi 17 Beta2) once fernet returns from holiday in which case this can be dropped from 7.90.006/LE8b1.
Close if not wanted.

kodi: Temporarily revert PR10247 for Kodi 17 beta1 due to OOM

---

packages/sysutils/busybox/scripts/init

This is a first stab/RFC/WIP at adding a degree of protection to the upgrade process, so that users can't so easily upgrade using incompatible `.tar`/`.img`/`.img.gz` files.
Note that this will NOT prevent users installing the wrong LibreELEC upgrade file when upgrading from any OpenELEC build, or any current LibreELEC build (to date) for that matter - this ship has already sailed, and there's nothing we can do to prevent users from installing anything of their choice on such  systems. The change proposed in this PR will only protect users once they are already booting a version of LibreELEC that includes this PR.
Essentially, this PR uses the `LIBREELEC_ARCH` (from `/etc/os-release`) of the currently running system and also the upgrade system, and determines if the Project/Arch of the …

init: Add upgrade check to avoid incompatible upgrades [RFC,WIP]

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk

- update to Tvheadend 4.1.2236
- fixes picons download from Tvh server
- fixes empty/incomplete frequency scan-tables

tvheadend42: update to 4.1.2236

---

packages/linux/package.mk

imx6 project has multiple device trees defined with KERNEL_UBOOT_EXTRA_TARGET

packages/linux: Correctly copy Amlogic device tree binary

---

packages/addons/addon-depends/system-tools-depends/mrxvt/package.mk
packages/addons/addon-depends/system-tools-depends/mrxvt/patches/mrxvt-01_xterm.patch

The default "rxvt" terminal type is not available in LE

system-tools: mrxvt: set terminal type to "xterm"

---

packages/addons/tools/system-tools/package.mk

install hddtemp database to get rid of:
htpc:~ # hddtemp /dev/sda
hddtemp: can't open /storage/.kodi/addons/virtual.system-tools/data/hddtemp.db: No such file or directory

system-tools: fix hddtemp

---

config/arch.aarch64
projects/Odroid_C2/options
projects/WeTek_Hub/options

S905 does not support crypto extensions, while other aarch64 CPUs may implement them.
Solution: define CPU extensions project-wise.

aarch64: define CPU extensions project-wise

---

packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk
packages/addons/tools/system-tools/source/default.py

Have the ability to open a mrxvt terminal window from kodi when selecting addon

system-tools: optional start mrxvt from kodi

---

packages/addons/addon-depends/vdr/patches/vdr-30_fix-dvbname-segfault.patch

VDR segfaults when initializing a DVB-C2 capable device.
The patch limits access to available DeliverySystemNames[] elements.

vdr: fix NULL pointer segfault

---

packages/addons/addon-depends/system-tools-depends/inotify-tools/package.mk
packages/addons/addon-depends/system-tools-depends/mc/package.mk
packages/addons/addon-depends/system-tools-depends/mc/patches/mc-01-netbsd-curses.patch
packages/addons/addon-depends/system-tools-depends/mc/patches/mc-02-netbsd-curses.patch
packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk

mc builds, I have not tested it, though

system-tools: add inotify-tools, mc

---

config/optimize
distributions/LibreELEC/options
projects/Generic/options
projects/Odroid_C2/options
projects/RPi/options
projects/RPi2/options
projects/Virtual/options
projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play/options
projects/imx6/options

As discussed in #644 This removes OPTIMIZATION=normal (02)
also this moves some default options from projects to the distro options.
This should be tested as it will default all projects to use lzo compression instead of gzip, not sure how big of an impact this will make.

build system cleanup

---

projects/RPi/patches/linux/linux-03-hifiberry_digi_pro.patch
projects/RPi2/patches/linux/linux-03-hifiberry_digi_pro.patch

Add RPi 4.4.y kernel commit https://github.com/raspberrypi/linux/commit/d614a77fbce891283e9f38f2e42ab4ce761d6a22 to support the HiFiBerry Digi+ Pro soundcard.

RPi/RPi2: add support for HiFiBerry Digi+ Pro

---

scripts/unpack

This fixes an unpack annoyance after patches has failed to apply.
With this the unpack script will clean a package the second time build/unpack is run after a patch has failed to apply instead of trying to apply patches a second time.

scripts/unpack: clean unpatched packages

---

projects/WeTek_Hub/patches/kodi/0004-powermanagement-disable-suspend.patch

This changes to use poweroff instead of suspend when selecting 'Power off system' in Kodi, the wifi driver causes a kernel crash on suspend.
The device can be powered back on using the power button on the remote.

projects/WeTek_Hub/patches/kodi: use poweroff instead of suspend

---

projects/WeTek_Hub/filesystem/etc/amremote/remote.conf

Map Home button on WeTek Hub's IR remote to KEY_HOME and add button labels to the IR remote config file.

projects/WeTek_Hub: Map Home button on IR remote to KEY_HOME

---

packages/devel/libcec/patches/libcec-PR208.patch

Shouldn't have dropped this. I had it marked as "merged upstream" but only because I'm already building with latest libcec unreleased master - LibreELEC still needs this.

libcec: shouldn't have dropped PR208

---

projects/WeTek_Core/kodi/advancedsettings.xml
projects/WeTek_Hub/kodi/advancedsettings.xml
projects/WeTek_Play/kodi/advancedsettings.xml

Remove settings that are not needed anymore from default advancedsettings.xml in WeTek projects.

Cleanup advanced settings in WeTek projects

---

packages/graphics/bcm2835-driver/package.mk

Since https://github.com/raspberrypi/firmware/commit/83dc067c60fd3f66eda1114eab23e45f57be387d we now need this support library, otherwise...:
```
rpi22:~ # vcdbg log msg 2>&1
vcdbg: error while loading shared libraries: libelftoolchain.so: cannot open shared object file: No such file or directory
```
@chewitt: Only `vcdbg` seems to be affected. No brainer for 7.90.006, but not exactly essential either.

RBP: include missing libelftoolchain.so

---

packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk

https://github.com/kodi-game/peripheral.joystick/pull/53 fixes weird stack-smashing crashes on RPi2.
Might be useful to have in 7.90.006.

peripheral-joystick: bump to abff316

---

packages/graphics/bcm2835-driver/package.mk

Discussing this with popcornmix, we currently copy/install 16 of the available 20 libraries (not including the two sym linked libraries).
To avoid being caught out next time a required library is added to the firmware, it is better that we simply copy/install everything.
The remaining/additional 4 (stripped) libraries add only 296KB:
```
-rw-rw-r-- 1 neil neil 84612 Sep 23 15:53 libbrcmOpenVG.so
-rw-rw-r-- 1 neil neil 63620 Sep 23 15:53 libbrcmWFC.so
-rw-rw-r-- 1 neil neil 84604 Sep 23 15:53 libOpenVG.so
-rw-rw-r-- 1 neil neil 63620 Sep 23 15:53 libWFC.so
```

bcm2835: simplify

---

packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk

No rebuild of v7.90.006 is required for perhipheral.joystick as the second PKG_VERSION value overwrote the first and built images contain the correct version. Thanks to @MartijnKaijser for spotting :)
pvr.stalker avoids some crash reports reported in Kodi forums.

kodi-binary-addons: bump pvr.stalker and fix peripheral.joystick pkg

---

packages/sysutils/busybox/scripts/init

Legacy boots with `/flash/syslinux.cfg`
UEFI boots with `/flash/EFI/BOOT/syslinux.cfg`
This change keeps the two in sync.

init: synchronise UEFI and legacy syslinux.cfg updates

---

config/path
scripts/build
scripts/image

Calling `setup_toolchain target` from `path` results in `$ROOT/$TOOLCHAIN/etc/cmake-$TARGET_NAME.conf` being the first time `options` is sourced, which may happen when a build isn't taking place, or before all build variables are defined (eg. `BUILD_SUFFIX`, which causes the conf to be written into the wrong build directory).
With this change we only call `setup_toolchain target` when actually building, by which time all variables needed should be correctly setup.
Also, this should be more efficient, as `options` is sourced thousands of times during a build.

toolchain: only setup_toolchain target when building

---

config/path
scripts/image

Every time `config/options` is sourced for a specific package, the entire repository (ie. disk) is scanned for various matching directories. This happens almost 1500 times during a build (typically, each package will source `config/options` at least 3 times - more if it actually requires building). On systems with slow or contended IO, this can add up to significant overhead.
With this change we build a cache of package directories that we can refer to without incurring any additional IO overhead.
On a dedicated system with an SSD and fast processor this change saves ~45 seconds of processing time. It may not sound a lot, but this is on a system with plenty of IO. On a system with contended spinning rust (ie. limited IO) and/or slower processor, it will hopefully result in a much greater …

path: optimize package processing

---

packages/security/libressl/package.mk

just some security updates.
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.6-relnotes.txt
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.7-relnotes.txt
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.8-relnotes.txt

bump libressl to 2.3.8

---

packages/graphics/mesa/package.mk
packages/lang/llvm/package.mk

Makes for a smaller overall system size. Should probably go in a @MilhouseVH build or two first.
plus mesa complains that using a static llvm is dangerous.

llvm: build shared library

---

packages/sysutils/busybox/tmpfiles.d/z_01_busybox.conf

Comments in LE settings guide users to restore from /storage/backup which doesn't exist unless you already created a backup or visited the samba shares. This ensures it is created on boot.

busybox: create /storage/backup by default

---

projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play_2/options

Some leftover options from the days of old.
The add-on urls are handled on the webserver, so they don't need to be changed here.

Wetek_* cleanup

---

packages/addons/addon-depends/moonlight-embedded/patches/moonlight-embedded-0002-revert-upstreamm-commit-6fcc63e.patch

this reverts upstream commit https://github.com/irtimmer/moonlight-embedded/commit/6fcc63ee9ea7660080de985ef07931418b6e2183
this allows it to build again for amlogic projects

moonlight-embedded: add patch to revert upstream commit

---

packages/addons/addon-depends/dvb-tools-depends/dvblast/patches/dvblast-0001-fe-caps-t.patch

I'm unable to figure out this error
```
dvb.c:639:30: error: unknown type name 'fe_caps_t'
static fe_code_rate_t GetFEC(fe_caps_t fe_caps, int i_fec_value)
```

dvblast: fix build with aml-3.14

---

projects/Odroid_C2/options
projects/RPi/options
projects/RPi2/options
projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play/options
projects/WeTek_Play_2/options
projects/imx6/options

It's not needed on any systems other than Generic as far as I know.
Please pipe up if you disagree.

projects/*/options: disable lcdproc for all projects except Generic/Virtual

---

packages/x11/driver/xf86-video-ati/config/xorg-radeon.conf
packages/x11/driver/xf86-video-ati/package.mk

@MilhouseVH would you be able to include this in some builds to see if there are any negative side effects for pre-GCN users?
/var/log/Xorg.0.log
```
[2085616.061] (**) RADEON(0): DRI3 enabled
[2085616.116] (II) RADEON(0): Use GLAMOR acceleration.
```

xf86-video-ati: add xorg-radeon.conf to enable dri3 and glamor

---

packages/addons/service/tvheadend42/source/defaults/config
packages/addons/service/tvheadend42/source/defaults/dvr/config/8d0f5b7ae354d956d7fe5db25f5d0d24
packages/addons/service/tvheadend42/source/defaults/epggrab/config

@CvH I'm pinging you as you seems to be the maintainer ;-)
It seems that the default configs are a bit outdated and can cause issues with non advanced users and SMB shares. Also the wizard on the first setup isn't working because of the predefined config. A big complain about tvheadend is that's it's hard to configure. My aim is to keep things simple, the user should be able to watch TV after running the wizard and enabling pvr.hts. 
General config:
* Use "basic" interface level, this is the default when installing tvheadend on other systems and it should be comparable to what regular STB's offer.
* Disable the switch interface level button to avoid user confusion. 
* Enable the wizard on the first start. This is the default when installing tvheadend on other systems.
-> it will guide the …

tvheadend42: wizard fix + general config updates

---

packages/x11/driver/xf86-video-intel/package.mk

From extended community build by @escalade 
Should improve VNC

xf86-video-intel: enable dri3 and make it default

---

packages/network/samba/config/smb.conf
packages/sysutils/udevil/config/udevil.conf

AML S905 ODROID C2 users were complaining about slow transfers over SMB and slow speeds writing to connected USB2.0 -  NTFS formatted HDD's,  so a C2 user **@infinity85** suggested some config tweaking might help:
The conversation and test results start from this post onwards:
http://forum.odroid.com/viewtopic.php?f=144&t=23405#p161855 
This may benefit other LE platforms.

Network: smb & ntfs config mods

---

config/path

This fixes the issue with `gtk+` reported [here](https://github.com/LibreELEC/LibreELEC.tv/commit/01eff6af7c34c1325614f1dec3c850c04b35cd0d#commitcomment-19318709).
It's a bit hackish, but I can't think of a better way that allows us to eliminate the regex and match only the package name at the end of the string (because if we're processing `linux` we want to match `/linux` but not `/linux-drivers` etc.)
The `_ANCHOR` string is just something extremely unlikely to appear in a filename...

path: remove regex dependency when processing packages

---

packages/audio/taglib/package.mk
packages/lang/llvm/package.mk
scripts/build

This builds with -Os instead of -O3/-O2

scripts/build: use MinSizeRel cmake build type

---

packages/linux/package.mk

The reference to hardkernel is not need after 73b406c4563da03326f375f858f13b4eee79dfaf

hardkernel reference no longer need

---

packages/lang/llvm/package.mk

this should fix building on Debian
llvm-tblgen build for target should not be used on build system

llvm: build llvm-tblgen for host and use it for target

---

packages/sysutils/lirc/patches/lirc-0007-disable-python-yaml-mod.patch

It's not used by LibreELEC and it trigger a build failure on recent
GNU/Linux distribution like Fedora 24.

LIRC: Disable YAML python module autodetection

---

packages/network/connman/package.mk

This PR removes full path to build dir in connman logs and replaces it with `../`
Before: `connmand[338]: /jenkins/workspace/LibreELEC/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/connman-1.33/src/ntp.c:decode_msg() adjusting time 0 seconds, 23399 msecs`
Now: `connmand[313]: ../src/ntp.c:decode_msg() adjusting time 0 seconds, 23837 msecs`

connman: remove full path in log

---

projects/imx6/patches/linux/4.4-xbian/linux-002-add-avermedia-td110-id.patch

Backport Avermedia TD110 support to i.MX6 4.4 kernel.

---

packages/tools/installer/config/installer.conf
packages/tools/installer/scripts/installer

Revert back to the default colours (blue background like Anaconda etc.). Also make sure that the "backtitle" is visible during the whole installation process.

installer: cosmetic touches

---

packages/multimedia/libamcodec/package.mk

this should fix building hyperion on Jenkins.
```
audio_out/alsa-out.c:18:28: fatal error: alsa/asoundlib.h: No such file or directory
```

libamcodec: requires alsa-lib

---

projects/imx6/linux/4.4-xbian/linux.arm.conf

and lines in dmesg
[ 2226.525427] evbug: Event. Dev: input5, Type: 0, Code: 0, Value: 0
[ 2226.697409] evbug: Event. Dev: input5, Type: 1, Code: 304, Value: 0
[ 2226.697423] evbug: Event. Dev: input5, Type: 0, Code: 0, Value: 0

imx6/linux 4.4: remove evbug option

---

packages/mediacenter/kodi/patches/kodi-999.99-aml-Drop-frames-if-requested-by-VideoPlayer.patch

When playing a video with HW-acceleration on an Amlogic-based device, video may become off-sync with audio. The issue is most notable when GUI is displayed on top of the video being played - video goes off-sync with audio more and more.
This PR fixes the problem.

Fix A/V sync issues in Kodi on Amlogic-based devices

---

packages/linux/patches/4.8.4/linux-053-spinelplus-remote-0.2.patch

patch is renamed for 4.8.4, supersedes #776

linux: add support for ZOTAC IR reciver

---

packages/linux/patches/4.8.4/linux-999-i915-chris-wilson-limit-depth-of-display-pipeline.patch

https://bugs.freedesktop.org/show_bug.cgi?id=97442#c15
Helps avoid blank screens on some Intel systems.

drm/i915: Limit the depth of the display pipeline to the framebuffer

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk

Yay! No more artefacts on RPi3 when transcoding from 1080o to 720p/4MBps.

emby: upgrade to 3.0.8300

---

packages/debug/valgrind/package.mk
packages/virtual/debug/package.mk

valgrind is only useful when the programs are compiled with debug symbols.
maybe @MilhouseVH can include this in his next debug build?
also @kszaq can test this for his oom research

add valgrind to debug builds

---

config/functions

@chewitt this should fix you issues building the *-tools add-ons.

config/functions: change debug_strip syntax

---

packages/multimedia/ffmpeg/patches/ffmpeg-99.1010-tls-1.2.patch

ffmpeg couldnt open streams on tls 1.2 servers. @vpeter4 made this patch and its tested and works.
Also sent to ffmpeg, so this can be removed later when its merge, ill try to keep on an eye open for it.

patch to make ffmpeg work with tls 1.2 servers

---

packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-theme-Estuary/package.mk
packages/mediacenter/kodi/package.mk

It's a minor bump with few changes since 17b4; files are uploaded.

kodi: bump to 17.0-beta5-e92818a

---

projects/RPi/patches/kodi/kodi-002-backport.patch
projects/RPi2/patches/kodi/kodi-002-backport.patch

Detail here:  https://github.com/Pulse-Eight/libcec/issues/252#issuecomment-256473002
From @popcornmix:
"I've spotted a bug where "pll adjust" may be active when "sync display" is disabled which wasn't the intention. At the very least it generates log spam, but may actually be harmful. Would be good to get in the next LE alpha (assuming no complaints from next nightly)."

RBP: Add PLL backport patch for Kodi 17 Beta 4

---

packages/web/curl/package.mk

Numerous security fixes.
https://curl.haxx.se/docs/security.html

curl: bump to curl-7.51.0

---

packages/linux-firmware/iwlwifi-firmware/package.mk

Need this before https://github.com/LibreELEC/iwlwifi-firmware/pull/2, or at least before we can pull in that update. I'll update this PR if #2 is merged before this PR.

iwlwifi-firmware: use github for package, bump to cb23d96

---

config/functions

OPTIMIZATIONS variable removed in 4df4ea789c44137f90c8c804888649cd35ae5e7c

buildsys: no more extra optimizations

---

packages/security/libressl/package.mk

This update cover issues with weak ciphering and digesting algorithm that are now disabled by default. 
Signed-off-by: Jérôme Benoit jerome.benoit@piment-noir.org

LibreSSL: update to 2.4.3

---

config/functions

HOST_CC/CXX (and follow ups) is only set for :target.
But :host need a correct set HOST_CC/CXX, too.
for example a clean ./scripts/install bzip2:host will create an unusable host bzip2.
clean build for RPi2 was fine

build: fix host build enviroment

---

packages/security/libressl/package.mk

Instead of reverting all changes in #875 this drops back to the last version before the ABI change. Pick this or #919 - whichever is better.

libressl: drop back to 2.3.9 to avoid soname changes

---

packages/multimedia/libass/package.mk

From @popcornmix: "if you test the SSA memory leak fix, note that current libssa has a cache size of 1G which is not very useful for most arm platforms. Latest 0.13.4 release limits caches to 192M (still a lot, but more reasonable). It also appears to fix some minor leaks and has improvements to caching, so I think it's worth testing in nightly and probably bumping in Kodi."
I'll include this in test builds, might want to wait a couple of days for positive feedback.

libass: update to 0.13.4

---

packages/addons/service/hyperion/patches/hyperion-0003-fix-protobuf-cmake.patch

This should fix the build issue.
The stock FindProtobuf.cmake file was update upstream to use camelcase libraries.
@chewitt please test

hyperion: add patch to remove protobuf cmake function

---

packages/sysutils/busybox/patches/busybox-05-tar.patch

Busybox tar fails to untar some files with "bad tar magic"/"short read".
This problem also occurs on other Busybox distributions, eg Alpine, OpenWrt, etc.
I could not find a bug report/fix, only a a workaround: install tar.
There are probably other things to do, ie disable Busybox tar and install tar, but I would not know what.

busybox: fix tar

---

packages/multimedia/libva-intel-driver/package.mk
packages/multimedia/libva/package.mk

libva: https://lists.freedesktop.org/archives/libva/2016-November/004730.html
* Bump VA API version to 0.39.4
* API: add support for bitrate control per temporal layer
* API: update the usage for framerate in VAEncMiscParameterFrameRate to
support non-integer frame-rate
* Add has_prime_sharing flag in VADriverVTableWayland to indicate if  
buffer sharing with prime fd can be used in the backend driver
libva-intel-driver: https://lists.freedesktop.org/archives/libva/2016-November/004731.html
* Add support for HEVC 10bit encoding on KBL
* Integrate the Google Test Framework for unit testing
* Add support for bitrate control per temporal layer for SVC-T
* Fix VA_STATUS_ERROR_UNIMPLEMENTED when sharpening with I420 surface (https://bugs.freedesktop.org/show_bug.cgi?id=96987)
* Fix crop issue …

libva: bump to libva-1.7.3 and libva-intel-driver-1.7.3

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-live/patches/vdr-plugin-live-gcc6.patch
packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/patches/vdr-plugin-xmltv2vdr-gcc6.patch
packages/addons/depends/audio/libopenmpt/patches/libopenmpt-bug-769.patch
packages/addons/service/tvheadend42/patches/tvheadend42-03_gcc6.patch
packages/audio/espeak/patches/espeak-1.48-gcc-6-fix.patch
packages/audio/sidplay-libs/package.mk
packages/devel/glibc/package.mk
packages/graphics/libprojectM/patches/libprojectM-c++14.patch
packages/lang/gcc/package.mk
packages/lang/gcc/patches/gcc-reduce-genautomata-memory-footprint-for-arm-bug-70473.patch
packages/mediacenter/kodi-binary-addons/adsp.biquad.filters/patches/adsp.biquad.filters-gcc-6.patch
packages/security/libgcrypt/package.mk
packages/security/libgcrypt/patches/libgcrypt-ac_cv_sys_symbol_underscore.patch
packages/tools/u-boot/package.mk
projects/Odroid_C2/patches/linux/linux-compiler-gcc.h.patch
projects/WeTek_Core/patches/linux/linux-compiler-gcc.h.patch
projects/WeTek_Hub/patches/linux/linux-compiler-gcc.h.patch
projects/WeTek_Play/patches/linux/linux-compiler-gcc.h.patch
projects/imx6/patches/linux/3.14-mx6-sr/linux-compiler-gcc.h.patch

Build and run-time tested on RPi, RPi2 and Generic with 4.7.0 kernel. I've built the main system plus PVR and inputstream addons without any issues. Obviously a clean build is required.
Needs testing on all other platforms. Addons need building too. I've added stack-protection config options to the Wetek and imx6 kernels as they support this feature - the 3.10 kernels do not.
No rush to merge, but would be nice to nail any build issues before merging once master is open for LE9 (i.e after we branch for LE8 beta).

gcc: Bump to gcc-6.2.0

---

packages/security/libressl/package.mk

This update bump the shared object version of the LibreSSL libraries.
LibreSSL in this version disable by default all weaks ciphering
or digesting algorithms and protocols like MD5, SHA1, SSLv2, SSLv3, etc.

LibreSSL: update to 2.4.4

---

packages/addons/service/oscam/changelog.txt
packages/addons/service/oscam/package.mk
packages/addons/service/oscam/source/settings-default.xml

Because of those $s `eval` in `oe_setup_addon` fails (see `packages/mediacenter/kodi/profile.d/00-addons.conf`).

oscam: fix settings-default.xml

---

packages/addons/service/boblightd/package.mk

This reverts commit b8d54c996d2b9f7814265b3fd9428f6be7f79c3b.
This is needed to build boblight-aml

Revert "boblightd: disable autoreconf"

---

projects/WeTek_Play_2/patches/linux/linux-compiler-gcc.h.patch

WP2 was missed when this was added recently

linux: add missing gcc compiler patch to WP2

---

config/version

We need this to bump all the add-ons without pissing people off because suddenly all their add-ons broke with the next alpha bump.
I'd sit on this till we have everything in a stable state again, then we can rebuild and push add-ons

config/version: set ADDON_VERSION to 8.1

---

packages/audio/libopenmpt/package.mk

libopenmpt: update to 0.2.7386-beta20.3

---

packages/mediacenter/kodi-binary-addons/pvr.filmon/patches/pvr.filmon-00.user_agent.patch

This patch should not interfere with upstream commits, as upstream version (0.7.8) is ahead of the patched version (0.7.7)

pvr.filmon: change user agent

---

packages/devel/binutils/patches/binutils-01-warn-for-uses-of-system-directories-when-link.patch

linker output in case of using /usr/lib path:
/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/6.2.0/../../../../x86_64-libreelec-linux-gnu/bin/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation, ignore it

binutils: warn for uses of system directories when cross linking

---

scripts/create_addon

copy the fanart.png to the `target/addons/8.1/arch/addon_name/resources/` folder, without the fanart is missing at the repo

scripts/create_addon: copy fanart to buildfolder too

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

backport of #981 
no ctop because the python isn't build with curses support.

backport of #981 (docker: update to 1.12.3)

---

packages/linux-drivers/wetekdvb/package.mk

Update WeTek proprietary DVB modules to wetekdvb-20161127.

packages/linux-drivers/wetekdvb: Update to wetekdvb-20161127

---

packages/network/samba/config/smb.conf

See: https://forum.libreelec.tv/thread-2485.html, which should be fixed by adding `allocation roundup size = 0`.
I've also added `strict allocate = yes` as this may improve performance (https://wiki.samba.org/index.php/Linux_Performance).
I'd like about a week of test builds without any incident before merging this, so keep open.

samba: fix allocation/size on disk issues reported by Windows 8.x+

---

scripts/create_addon

- the pvr addons ship the addon.xml in the old format, icon.png is at the old path (not in the resources sub folder) and at the addon.xml the entries for news, icon and fanart are missing
- what **is** working: icon and fanart is at the right folder that it gets picked up and properly recognised at the repo addon.xml (icon and fanart gets shown if addon is not installed), icon is in the right place to match the addon.xml from the addon (if the addon is installed)
- what is **not** working: fanart.png is at the resources sub folder of the addon but not recognised in the addon.xml from the addon (if the addon is installed), the news entry is also missing
A real fix is to support the new format by kodi-pvr instead of maintain the old version.

scripts/create_addon: workaround for pvr addons

---

packages/lang/gcc/patches/gcc-crosscompile-badness.patch

This reverts commit 00a7211dc6687da308ce0a95d13b8da1b43822a6 and fixes #805.
Don't understand why Python would fail with this. Will check once in the future.

Revert "gcc: do not abort when including host headers"

---

projects/RPi/filesystem/usr/share/alsa/cards/HifiberryDigi.conf
projects/RPi2/filesystem/usr/share/alsa/cards/HifiberryDigi.conf

From poppcornmix:
> Can you add a file /usr/share/alsa/cards/snd_rpi_hifiber.conf containing http://paste.ubuntu.com/23554758/ for Pi builds? I've tested it and it allows passthrough to be enabled on hifiberry dac without this kodi hack: https://github.com/popcornmix/xbmc/commit/ec36920251aa06c98856db52c162345fe0d41e5d

alsa-lib: add HiFiBerry config

---

packages/graphics/mesa/patches/mesa-01-i965-add-APL-and-KBL-SKU-strings.patch

I know this hardware is already supported by mesa 13.0.2 (#1006), but backporting to mesa 13.0.0 for 7.90.009 would be useful (tested in my builds).
ping @chewitt
@lrusak: Drop this in #1006...

mesa: add Apollo and Kaby Lake support to 7.90.009

---

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk

Reverts LibreELEC/LibreELEC.tv#1029
wvdecrypter is not included upstream yet. I made an mistake, thanks to @stefansaraev for pointing it out.

Revert "Inputstream.adaptive: include decrypter lib"

---

packages/virtual/x11/package.mk
packages/x11/driver/xf86-input-synaptics/package.mk

Add Synaptics x11 input driver (if using evdev instead of libinput), to handle some touchpad models.

xf86-input-synaptics: add package

---

packages/graphics/bcm2835-driver/package.mk

Backport of #768, required by latest firmware which itself is required to support RPi2B+...

bcm2835-driver: create symlinks for new firmware [backport]

---

packages/network/samba/config/smb.conf

This resolves an issue reported by users when transferring large files from the network to an external HDD:
http://forum.kodi.tv/showthread.php?tid=298461&pid=2476327#pid2476327
http://forum.kodi.tv/showthread.php?tid=298462&pid=2476329#pid2476329
As `strict allocate` may be enabled by default in future versions of Samba ([ref](https://wiki.samba.org/index.php/Linux_Performance#How_do_I_get_the_patch_.3F)), this PR will always force `strict allocate` to be disabled even though with 3.6.25 it is not currently necessary. That way if it is enabled by default in future we shouldn't see broken behaviour again.

samba: disable strict allocate

---

packages/virtual/initramfs/package.mk
scripts/image

After #805 (merge /usr), we need a `/usr/lib64` sym link.
```
NUC:~ # lsb_release
LibreELEC (Milhouse) - Version: devel-20161214021654-#1213x-g4b0e759 [Build #1213x]
NUC:~ # ls -la /usr/bin/Xorg
-rwxr-xr-x    1 root     root       1893088 Dec 14 02:18 /usr/bin/Xorg
NUC:~ # ldd /usr/bin/Xorg
$       not a dynamic executable
```
```
@escalade
9:41 AM you'll get not a dynamic executable
9:41strace shows ldd looking for /usr/lib/ld-linux.so.2, which isn't there then /usr/lib64/ld-linux-x86-64.so.2 which isn't there either
9:41there's /usr/lib/ld-linux-x86-64.so.2
9:42 in my build i symlinked /usr/lib to /usr/lib64 and it works
```
/usr/bin/ldd before /usr:
```
RTLDLIST="/lib/ld-linux.so.2 /lib64/ld-linux-x86-64.so.2 /libx32/ld-linux-x32.so.2"
```
/usr/bin/ldd AFTER /usr:
``` …
```

Fixup post-/usr: need /usr/lib64

---

packages/x11/driver/xf86-video-nvidia-legacy/package.mk
packages/x11/driver/xf86-video-nvidia/package.mk

nvidia 375.26: [changelog](https://devtalk.nvidia.com/default/topic/981831)
nvidia-legacy 340.101: [changelog](https://devtalk.nvidia.com/default/topic/981835)
Builds fine with kernel 4.8 and also 4.9 (no nvidia-legacy-linux-4.9 patch required - #1017 updated).
nvidia-legacy successfully tested on ION2 (both 4.8.13 and 4.9.0)

Package updates: nvidia 375.26 and nvidia-legacy 340.101

---

packages/x11/driver/xf86-video-nvidia-legacy/patches/xf86-video-nvidia-legacy-kernel-4.9.patch

Thanks to ejmarkow on the [NVIDIA Developer forum](https://devtalk.nvidia.com/default/topic/982052/linux/latest-nvidia-driver-340-101-builds-compiles-properly-but-fails-to-load-has-errors-with-linux-kernel-4-9-resolved-with-patch-/post/5039355/#5039355).
Build and run-time tested, 340.101 now loads normally wth 4.9.0.

xf86-video-nvidia-legacy: linux 4.9 fix

---

packages/addons/addon-depends/system-tools-depends/file/package.mk
packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk

fixes
```
LibreELEC:~ # file /bin/busybox
Aborted (core dumped)
```

system-tools: bump file package

---

packages/linux/patches/default/linux-999-i915-fix-setting-of-boost-freq-tunable.patch

This might prove beneficial to anyone hoping to tune their Intel system.
There haven't yet been any reports of this being an issue, but that could happen in future.

linux: drm/i915: Fix setting of boost freq tunable

---

packages/sysutils/busybox/package.mk
packages/sysutils/busybox/scripts/getedid

This is a newer version for the getedid script which contains the changes @MilhouseVH mentioned in the previous PR

Added getedid script

---

packages/addons/addon-depends/moonlight-common-c/package.mk
packages/addons/script/moonlight/changelog.txt
packages/addons/script/moonlight/package.mk

fixes a bug with the new gamestream client

moonlight: bump depends and rebuild

---

tools/distro-tool

This change allows the "new package" checking to be restricted to main packages (`--check-main`) or add-on packages (`--check-addons`), and/or version-based packages (`--check-ver`) or rev-based packages (`--check-rev`).
Also distinguish between version and revision based packages when reporting new version:
```
New Ver Pkg available: wpa_supplicant (2.5 => 2.6) http://hostap.epitest.fi/releases/wpa_supplicant-2.6.tar.gz
New Rev Pkg available: vdr-plugin-dvbapi (897c50e => 7a42b22) https://github.com/manio/vdr-plugin-dvbapi/archive/7a42b22.tar.gz
```

distro-tool: Add main/addon and rev/ver filters

---

packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml

I'm not entirely sure whether this is supposed to be 8.0.0 repo to match 8.0.0 release or 8.1.0 repo to match 8.1 repo version. Merge or close as appropriate.

kodi: bump repository.libreelec.tv to 8.1 for consistency

---

packages/devel/dbus-glib/package.mk
packages/python/system/dbus-python/package.mk
packages/sysutils/dbus/package.mk

This PR updates dbus packages to latest versions
- `dbus` is downgraded to stable 1.10.14 release (https://lists.freedesktop.org/archives/dbus/2016-November/017063.html)
- `dbus-glib` and `dbus-python` is upgraded to latest versions and mostly contains changes to docs, test and build scripts
This was tested together with https://github.com/LibreELEC/service.libreelec.settings/pull/45 on a WeTek Hub

Update dbus packages

---

packages/addons/addon-depends/libconfig/package.mk

This reverts commit 2642b4f4cb74206f915aac96f2b042b56df7265e.
Doesn't build (apologies - couple of add-on related packages crept in to #1075).

Revert "libconfig: update to libconfig-1.6"

---

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
projects/WeTek_Play_2/filesystem/etc/amremote/remote.conf

I noticed that on WP2 some keys weren't working. For instance Chan-Up and Chan-Down.
aml_keypad was not handled with eventlircd.
Please test this.

eventlircd: Fix missing buttons with WP2 remote

---

packages/virtual/network/package.mk

For now the samba package is built only when KODI_SAMBA_SUPPORT is set to yes, whatever the setting of SAMBA_SERVER and/or SAMBA_SUPPORT in distributions/LibreELEC/options.
So if one doesn't want/need Kodi samba support he cannot have OS samba server/client.
This PR fixes it.

Virtual network package: Fix samba and openvpn build options

---

packages/addons/addon-depends/protobuf/package.mk

Without this protobuf fail on imx6 because protoc is used from target folder.
Before merging I will build on Jenkins Generic and RPi2 project to not brake something.

protobuf: set protoc path

---

packages/devel/ccache/package.mk

This PR fixes clean build when `CCACHE_DISABLE=1` is defined
ccache 3.1.10 included a bug fix for:
ccache no longer tries to create the cache directory when `CCACHE_DISABLE` is set. 
when max cache size is configured it stops with:
`ccache: error: could not set cache size limit: /path/to/.ccache/Generic.x86_64-8.0/ccache.conf: No such file or directory`

ccache: fix build with CCACHE_DISABLE

---

packages/addons/addon-depends/libdvbcsa/package.mk

libdvbcsa: AArch64 support

---

config/path

This is an alternative to #938 
In this version, the build-specific ccache is now the default, as this is the most complicated ccache folder name to determine, while being potentially the "safest" ccache variant.
Anyone wanting the old project-specific ccache can add the following to `$HOME/.libreelec/options`:
```
if [ -n "$DEVICE" ]; then
export CCACHE_DIR=$ROOT/.ccache/$PROJECT.$DEVICE.$TARGET_ARCH-$OS_VERSION
else
export CCACHE_DIR=$ROOT/.ccache/$PROJECT.$TARGET_ARCH-$OS_VERSION
fi
```
If `$DEVICE` is not a concern, then it's a one line addition to `$HOME/.librelec/options` to re-instate a project-specific ccache, or whatever/whereve type of ccache you desire.

build: switch to build-specific ccache by default

---

config/functions
packages/mediacenter/kodi/package.mk

This PR makes `enable_service` behave more like `systemctl enable`, symbolic links is now created for aliases defined by `Alias=` in addition to current `WantedBy=` symbolic links
`kodi.target` is the only systemd unit using `Alias=` in LibreELEC

Create symbolic links for systemd unit aliases

---

packages/addons/service/vdr-addon/changelog.txt
packages/addons/service/vdr-addon/package.mk
packages/addons/service/vdr-addon/source/bin/vdr.start

Otherwise they may not be accesible from Windows via smb

encode special characters in directory names as hex values

---

config/version

This concludes the libreelec-7.0 release branch. Add-on maintenance will be accepted if users and maintainers continue to submit changes but no further LibreELEC 7.0.x/Jarvis releases are planned. Krypton beckons :)

config: set version to devel

---

packages/devel/libcec/package.mk
projects/WeTek_Core/patches/libcec/libcec-00-amlogic-support.patch
projects/WeTek_Play/patches/libcec/libcec-00-amlogic-support.patch
projects/imx6/patches/libcec/libcec-100-from-xbian.patch

Bump to 4.0.1.
Should fix https://github.com/Pulse-Eight/libcec/issues/276 and https://github.com/Pulse-Eight/libcec/issues/272 and fixes missing [HAVE_AOCEC_API](https://github.com/Pulse-Eight/libcec/pull/274) (project patches updated, but untested).

libcec: update to libcec-4.0.1

---

packages/addons/repository/repository.linuxserver.docker/sources/addon.xml

This sets the minimum Kodi version to 16.1 (Jarvis) which corresponds to LE 7.0. PKG_REV does not need to be bumped as nobody can install the current zip. I'll clean things up before pushing the updated version.

repo: correct minimum add-on version for ls.io repo

---

packages/x11/other/fluxbox/config/apps
packages/x11/other/fluxbox/package.mk

This brings back the behavior of Ratpoison, where any new window is started maximized. This makes sense when launching applications outside of Kodi, if they are not maximized and you move the mouse then focus might be lost and you need to alt+tab to find the window.

fluxbox: start applications maximized by default

---

packages/x11/driver/xf86-video-ati/config/xorg-radeon.conf
packages/x11/driver/xf86-video-intel/package.mk

I didn't want to revert the previous commits as I want to leave DRI3 enabled but make it possible for users to opt in.
I would like others to comment as I consider this a bug fix as some people were reporting problems flickering, etc.

move back to DRI2

---

scripts/create_addon

This should have always been the case. I have been using this with retroplayer add-ons as often the emulator package would get updated but the binary add-on would stay the same, so the addon version would stay the same but the PKG_REV can allow the new add-on to exist.
This isn't the case for all binary add-ons but many use third party libraries that can be bumped independently from the binary add-on.
all PKG_REV should be reset to `1` or `100` for binary add-ons. I can include that in this PR if all agree.

scripts/create_addon: use PKG_REV as part of the binary addon version

---

packages/sysutils/lirc/system.d/lircd-uinput@.service

If the lircd service is enabled in LE settings but there isn't a lircd.conf then lircd-uinput will fail to start because lircd doesn't output to the socket. This makes the socket a condition to start.

lirc: check for socket in lircd-uinput.service

---

packages/sysutils/systemd/profile.d/90-systemd.conf

This is the best solution I have found.
busybox less cannot interpret the color ANSI codes produced by systemd, so lets disable them.
~~I tried settings `SYSTEMD_COLORS=0` in the profile, but this didn't work, so it probably has to be set before systemd is invoked in the init, however, this solution works just as well.~~
Edit: I needed to export it.
This is the issue I am talking about
```
[[0;1;31m●[[0m LibreELEC
State: [[0;1;31mdegraded[[0m
Jobs: 0 queued
Failed: 1 units
Since: Thu 2017-01-12 10:42:38 PST; 13min ago
CGroup: /
```
and
```
[[0;1;32m●[[0m kodi.service - Kodi Media Center
Loaded: loaded (/usr/lib/systemd/system/kodi.service; disabled; vendor preset: disabled)
Active: [[0;1;32mactive (running)[[0m since Thu 2017-01-12 10:42:44 PST; 14min ago
Process: 584 …
```

systemd: add patch to disable colors

---

scripts/checkdeps

lsdiff is needed to build media_build (included in patchutils)
lsdiff it the program we need, patchutils the package that include it

scripts/checkdeps: add patchutils as dependency

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/patches/linux/linux-01-RPi_support.patch

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.3
This updated RPi firmware includes usb/net booting support.
The RPi patches include the JustBoom driver name fix.

linux: update to linux-4.9.3

---

packages/mediacenter/kodi/patches/kodi-999.16-amlogic_timing.patch

Recent @peak3d's patch for Kodi Krypton for smooth 24p playback. Fixes various playback issue.
This is still WIP, please do not merge.
It only works with the linux patch: 
https://github.com/LibreELEC/linux-amlogic/pull/34
https://github.com/LibreELEC/linux-amlogic/pull/35
Original work: https://github.com/peak3d/xbmc/pull/2

kodi: Add peak3d's amltiming patch

---

packages/graphics/mesa/package.mk

cleanup
configure: WARNING: unrecognized options: --disable-xlib-glx, --disable-r600-llvm-compiler, --enable-sysfs

mesa: update 13.0.3 and cleanup

---

packages/addons/driver/steamcontroller/changelog.txt
packages/addons/driver/steamcontroller/package.mk
packages/addons/driver/steamcontroller/patches/steamcontroller-0001-fix-include-dir.patch
packages/addons/driver/steamcontroller/patches/steamcontroller-0002-append-python-path.patch
packages/addons/driver/steamcontroller/patches/steamcontroller-0003-wait-for-controller-connection.patch
packages/addons/driver/steamcontroller/patches/steamcontroller-0004-use-run-for-pid-directory.patch
packages/addons/driver/steamcontroller/patches/steamcontroller-0005-steam-client-will-never-be-running.patch
packages/addons/driver/steamcontroller/source/system.d/driver.steamcontroller.service

There was high cpu usage before when no controller was plugged in because python was looping constantly. Now systemd will just restart the service every 10 seconds.

steamcontroller: update to 60499dc

---

packages/sysutils/e2fsprogs/package.mk

`e2fsprogs:host` will create files in the `.install` directory that are read-only:
```
neil@nm-linux:~/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel$ ls -la e2fsprogs-1.43.3/.x86_64-linux-gnu/.install/usr/lib/
total 580
drwxrwxr-x 3 neil neil   4096 Jan 17 23:11 .
drwxrwxr-x 4 neil neil   4096 Jan 17 23:11 ..
-r--r--r-- 1 neil neil  19016 Jan 17 23:11 libcom_err.a
-r--r--r-- 1 neil neil 557982 Jan 17 23:11 libext2fs.a
drwxrwxr-x 2 neil neil   4096 Jan 17 23:11 pkgconfig
```
These files are then copied to `toolchain/lib` with the same read-only file attributes.
When the package is subsequently bumped and new toolchain files are created, the new files cannot be copied if the destination folder already contains read-only files from a previous build. The build fails.

e2fsprogs: make e2fsprogs bumpable

---

packages/mediacenter/kodi/scripts/kodi.sh

Create `/storage/.kodi/temp/kodi_crash.log` sym link to latest Kodi crash log.
Main reason for adding this is to simplify instructions to users, as there can be up to 10 crashlogs and we usually only ever want the latest.
Will backport this.

kodi: create sym link for latest crashlog

---

packages/linux/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/patches/linux/linux-01-RPi_support.patch
tools/RPi/rpi-linux-rebase.sh

Supercedes #1182.
4.9.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.4
4.9.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.5
I haven't included the RPi firmware bump as this will be updated soon (branch=master) with a deinterlace fix. Leave this open and wait (I'll add it to this PR), or merge now and I'll bump the firmware in a separate PR (I vote for the latter).
Note I haven't build tested this PR yet, maybe tomorrow.

linux: update to linux-4.9.5

---

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
projects/WeTek_Play_2/filesystem/etc/amremote/remote.conf

This reverts my PR #1081 and fixes the missing buttons for the original WP2 remote.
Using eventlircd has the disadvantage that long press is no longer working also there are some problems with other Amlogic remotes as reported by @kszaq.
Most of the buttons work out of the box with Kodi as they should. Everything else can be remapped with Keymap Editor Addon.
EDIT:
sms style input works too: http://kodi.wiki/view/HOW-TO:Use_SMS-style_text_entry_for_remotes
Please test before merge.

Rework WP2 amremote keymapping

---

packages/audio/alsa-lib/package.mk
packages/audio/alsa-utils/package.mk
packages/audio/flac/package.mk
packages/audio/taglib/package.mk
packages/compress/xz/package.mk
packages/compress/zlib/package.mk
packages/graphics/libjpeg-turbo/package.mk
packages/graphics/libpng/package.mk
packages/multimedia/libass/package.mk
packages/network/openssh/package.mk
packages/web/curl/package.mk
packages/web/libmicrohttpd/package.mk

Sync with recent kodi package bumps.
https://github.com/xbmc/xbmc/pull/11100 - [depends] libmicrohttpd 0.9.52
https://github.com/xbmc/xbmc/pull/11101 - [depends] taglib 1.11.1
https://github.com/xbmc/xbmc/pull/11102 - [depends] libpng 1.6.26
https://github.com/xbmc/xbmc/pull/11103 - [depends] libjpg-turbo 1.5.1

Package updates

---

packages/audio/taglib/patches/taglib-01-efficient_lookup_for_an_ID3v2_tag_in_MPEG_files_with_garbage.patch

See https://github.com/xbmc/xbmc/pull/11543

taglib: Efficient lookup for an ID3v2 tag in MPEG files with garbage

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk
packages/addons/service/tvheadend42/source/bin/tvheadend42.start
packages/addons/service/tvheadend42/source/resources/language/English/strings.xml
packages/addons/service/tvheadend42/source/resources/settings.xml

- added custom start options to addon
- added FRITZ!Box Sat>IP server support to addon
- update to Tvheadend 4.1.2415
- fix debug if activated but nothing selected

tvheadend42: update to 4.1.2415

---

packages/compress/zlib/package.mk

For reference: https://forum.libreelec.tv/thread-4254-post-30631.html#pid30631
Please test.

zlib: Fix dead link by bumping to 1.2.11

---

packages/tools/dtc/package.mk

currenly dtc package install everything in $HOME when build for the
:host target. 
It's not the intended behavior, so override the path PREFIX in the Makefile and 
define a makeinstall_host function that will set the PREFIX variable to the proper 
:host path for dtc.

dtc: fix host install path

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

(As mentioned in #1207)
firmware: di_adv: Fix for green artefacts regression
See: http://forum.kodi.tv/showthread.php?tid=304573
firmware: di_adv: Avoid artefacts at bottom of video for YUV420
See: http://forum.kodi.tv/showthread.php?tid=304814
firmware: raspistill: Added SIGUSR2 signal to capture and exit immediately
See: raspberrypi/userland#368
firmware: dispmanx: Protect a null element access
firmware: leds: Provide a way of changing LED assignments for CM3
firmware: leds: Prevent re-initialisation

RBP: update to firmware debe2d2

---

scripts/unpack

from
`APPLY PATCH (common)   /data/LibreELEC.tv/packages/audio/alsa-lib/patches/alsa-lib-USB_Soundblaster_HD.patch
`
to
`APPLY PATCH (common)   packages/audio/alsa-lib/patches/alsa-lib-USB_Soundblaster_HD.patch`

scripts/unpack: use relative path for showing a patch file

---

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
packages/linux-drivers/media_build/sources/backports/linux-240-pctv452e_kernel_oops_in_4.9.patch

TT-S2-3600 is broken in 4.9.x but it is already fixed for 4.10.x
```
dvb-usb: found a 'Technotrend TT Connect S2-3600' in warm state.
pctv452e: pctv452e_power_ctrl: 1
Unable to handle kernel NULL pointer dereference at virtual address 00000000
pgd = adb60000
[00000000] *pgd=00000000
Internal error: Oops: 805 [#1] SMP ARM
```
patch was reported working (tx uatschitchun)
cc @kszaq @wrxtasy (it is a usb device)

media_build: fix TT-S2-3600

---

packages/devel/glibc/package.mk

This prevents having 2 copies of libm.so, saves space.

glibc: preserve symlinks when copying libs to initramfs

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/patches/linux/linux-01-RPi_support.patch

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.7
Firmware:
```
firmware: Fixup CEC code cleanup 8: fixed hdmi state machine clk
See: #732 (https://github.com/raspberrypi/firmware/issues/732)
firmware: CEC code cleanup 11: cec_release_logical_addr
firmware: CEC code cleanup 12: CEC init @ HPD
```

linux: update to linux-4.9.7

---

packages/graphics/mesa/package.mk

Mesa 13.0.4 is a bug fix release which fixes bugs found since the 13.0.3 release.
changelog: https://lists.freedesktop.org/archives/mesa-announce/2017-February/000294.html
tested

mesa: update to 13.0.4

---

packages/security/libressl/package.mk

libressl: update to 2.4.5 for security

libressl: update to 2.4.5 for security reasons

---

packages/audio/alsa-utils/package.mk

new alsa-utils failed to build, when python-docutils is installed.
With this patch, the problematic man files are not build (there are not needed)

alsa-utils: fix man build in same enviroments

---

packages/databases/mysql/package.mk

Debug builds, at least for WH, failing at mysql. This quick fix works for me, ofc it only workaround the real problem. Someone with proper knowledge pls decide if this can be merged or not.

mysql: fixes debug build for aarch64

---

packages/network/bluez/package.mk

Initial discussion: https://forum.libreelec.tv/thread-372-post-31335.html#pid31335
Bluetooth device is not powered up on the Asrock Beebox N3xxx machines. Maybe on some other machines too...
I then found that the fix has been added in OE: https://github.com/OpenELEC/OpenELEC.tv/commit/f887de1fc6e316629d770b83f773657fdf74c245
So this is the same fix here.

bluez: set AutoEnable policy

---

packages/sysutils/busybox/scripts/getedid

I removed the "default" option and therefore the "restore" function. I would say it's not really needed as "create" and "delete" should be enough for that script. 
Further I corrected some typos and some other minor changes like exit codes.

busybox: cleanup getedid script

---

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules

It's almost impossible to do a single button press if buttons are set to repeat after 200ms.
gpio-ir-recv is working fine on RPi2 with the default settings (500ms kernel default or 1000ms as setup by the eventlircd udev rule), so no need to treat gpio-ir-recv differently than all other IR receivers.

eventlircd: use default initial-repeat delay for gpio-rc-recv

---

packages/mediacenter/kodi/scripts/kodi-config

This fixes the "memleak" (not actually a memleak) issue on 64bit systems. It's actually a memory fragmentation issue.
see, https://github.com/xbmc/xbmc/pull/11620
and, https://bugzilla.redhat.com/show_bug.cgi?id=843478

kodi: set MALLOC_MMAP_THRESHOLD_=524288 for 64bit cpus

---

packages/mediacenter/kodi/scripts/kodi-config

backport of #1286 (kodi: set MALLOC_MMAP_THRESHOLD_=524288 for 64bit cpus)

---

packages/sysutils/eventlircd/system.d/eventlircd.service
packages/sysutils/lirc/package.mk
packages/sysutils/lirc/scripts/lircd_helper
packages/sysutils/lirc/system.d/lircd-uinput@.service

don't merge yet, please review and test
Since diagonal key support was added in kernel 4.7 via commit https://github.com/torvalds/linux/commit/488326947cd1f038da8d2c9068a0d07b913b7983 using the default release suffix of _UP for transporting key-up events from lircd to lircd.-uinput is broken.
KEY_LEFT_UP and KEY_RIGHT_UP are now valid keycodes and lircd-uinput will interpret them differently (diagonal-key-down instead of left/right key up) leading to non-working left/right keys. See for example this irw output: https://forum.libreelec.tv/thread-4413-post-31915.html#pid31915
This problem went unnoticed so far because of another issue: during cross-compilation the lirc build picked up the linux include with valid keycodes from the build host instead of the target. So when compiling on a …

fix lirc cross-compilation and non-working left/right keys

---

.gitignore
tools/mkpkg/update_binary-addons-retroplayer
tools/mkpkg/update_emulation
tools/mkpkg/update_retroplayer-addons

I've added a new script that will automatically bump the PKG_REV when either the add-on or its emulator package is bumped. This makes it much easier to track once we get the repo going.
I've reworked the old scripts so they can still be used to update individual add-ons or emulators
```
../../tools/mkpkg/update_binary-addons-retroplayer game.libretro.2048
../../tools/mkpkg/update_emulation libretro-2048
```

add reworked retroplayer add-ons script

---

packages/addons/addon-depends/bash/package.mk
packages/addons/addon-depends/moonlight-embedded/patches/moonlight-embedded-0002-Revert-Update-libCEC-compatibility-to-version-4.0.patch
packages/addons/driver/sapphire/package.mk

This PR fixes building of **moonlight-embedded** after a recent bump, enables **sapphire** addon for 7.0 and fixes **bash** building without netbsd-curses.

LibreELEC 7.0 addon fixes

---

packages/mediacenter/kodi/patches/kodi-999.01-create-archive-cache.patch

`Add-on caching doesn't work without that directory so playback stopping and list repopulating will be slow.`
it builds (no runtime test because no idea how to reproduce)
@popcornmix could tell more

kodi: add backport to fix addon cache

---

packages/linux/package.mk

backport of #1321 (linux-amlogic: update to 83803a1)

---

projects/WeTek_Play_2/filesystem/etc/amremote/remote.conf

work by @Raybuntu this was already in master:
https://github.com/LibreELEC/LibreELEC.tv/commit/5df86b714d26f832675c8f0b08f21ff87a468228

Backport for LE8: WeTek_Play_2: Remap buttons in remote.conf

---

packages/mediacenter/kodi/config/advancedsettings.xml
packages/mediacenter/kodi/patches/kodi-999.99-PR11663.patch
packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
packages/sysutils/v4l-utils/udev.d/70-input-repeat.rules
projects/RPi/kodi/advancedsettings.xml
projects/RPi2/kodi/advancedsettings.xml
projects/WeTek_Core/kodi/advancedsettings.xml
projects/WeTek_Hub/kodi/advancedsettings.xml
projects/WeTek_Play/kodi/advancedsettings.xml
projects/WeTek_Play_2/kodi/advancedsettings.xml
projects/imx6/kodi/advancedsettings.xml

This PR changes the repeat delay and period for all LIRC remotes to match what Kodi sets for keyboards.
Currently `98-eventlircd.rules` sets the delay to 1000ms and the kernel sets the period to 33ms.
This is a too long delay and a too short period in my opinion.
~Copy the file to `/storage/.config/udev.rules.d/99-lircd-uinput.rules` and modify it to try with different delay/periods (after a reboot)~

input: change input repeat config

---

packages/audio/rpi-cirrus-config/config/rpi-cirrus-config.sh.sample
packages/audio/rpi-cirrus-config/modprobe.d/rpi-cirrus.conf
packages/audio/rpi-cirrus-config/package.mk
packages/audio/rpi-cirrus-config/scripts/rpi-cirrus-config
packages/audio/rpi-cirrus-config/udev.d/90-alsa-restore.rules
projects/RPi/options
projects/RPi2/options

don't merge yet, needs RPi kernel bump.
The driver for the Wolfson/Cirrus card has recently been included in the rpi kernel, this PR adds the necessary ALSA config (ALSA card conf and mixer settings) so that it is set up correctly and can work out-of-the-box.
The kernel config change is idendical to https://github.com/MilhouseVH/LibreELEC.tv/commit/88bb3e69aeebf9bf187910169d8a844d1365b35f "RBP: Sync options with upstream", so add either of these.
@MilhouseVH could you add this PR to your builds instead of "RBP: Sync options with upstream"?

add config scripts for RPi Wolfson/Cirrus Logic audio card

---

packages/sysutils/v4l-utils/package.mk
packages/sysutils/v4l-utils/patches/v4l-utils-24-fix-streamzap-keymap.patch

This should hopefully fix the streamzap issue reported here:
https://forum.libreelec.tv/thread-4873-post-34116.html
@MilhouseVH could you include that in your x86 build?

v4l-utils: update to 1.12.2 and fix streamzap keytable

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

backport of #1350 (docker: enable journald buildtag)

---

packages/mediacenter/kodi/config/advancedsettings.xml
projects/RPi/kodi/advancedsettings.xml
projects/RPi2/kodi/advancedsettings.xml
projects/WeTek_Core/kodi/advancedsettings.xml
projects/WeTek_Hub/kodi/advancedsettings.xml
projects/WeTek_Play/kodi/advancedsettings.xml
projects/WeTek_Play_2/kodi/advancedsettings.xml
projects/imx6/kodi/advancedsettings.xml

This PR fixes an edge case for Harmony remotes configured to send 3 command repeats (sync to the current state of #1327)

kodi: skip one lirc repeat event

---

packages/linux/package.mk

Update Amlogic kernel to 3.10-de626d8.
The updated kernel contains an important fix to improve playback of the videos with fractional FPS.

packages/linux: Update Amlogic kernel to 3.10-de626d8

---

packages/linux/package.mk

Backport of #1362 (Update Amlogic kernel to 3.10-de626d8)

---

packages/linux-drivers/wetekdvb/package.mk

Updates WeTek proprietary DVB modules to wetekdvb-20170116.
The update fixes a VDR scan issue on WeTek Play 2.

Update WeTek proprietary DVB modules to wetekdvb-20170116

---

projects/WeTek_Hub/linux/linux.aarch64.conf
projects/WeTek_Play_2/linux/linux.aarch64.conf

This PR fixes building LE8 without prompting for linux meson pwm config on WeTek_Hub and WeTek_Play_2.
@wrxtasy please add similar to your #1339 for master

WeTek_Hub/WeTek_Play_2: disable meson PWM support

---

packages/linux-drivers/wetekdvb/package.mk

Backport of #1372 (Update WeTek proprietary DVB modules to wetekdvb-20170116)

---

packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk

revert to krypton release instead of master (Leia)

peripheral.joystick: revert package bump

---

packages/lang/Python/package.mk

While building `Python:host` on a heavily loaded system (ie. a system concurrently building several builds - FX-8350, 8 cores) I will occasionally experience one of two errors during Python `makeinstall_host`:
1) `file too short`
```
changing mode of build/scripts-2.7/2to3 from 664 to 775
changing mode of build/scripts-2.7/smtpd.py from 664 to 775
/usr/bin/install -c python /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel-next/toolchain/bin/python2.7
if test -f libpython2.7.so; then \
if test -n "" ; then \
/usr/bin/install -c -m 555  /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel-next/toolchain/bin; \
else \
/usr/bin/install -c -m 555 libpython2.7.so /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreE …
```

Python: use -j1 for makeinstall_host

---

config/functions
scripts/create_addon

This PR makes build system strip all executables in addons we create to shave off some unnecessary MBs from binaries. This removes the need to add `debug_strip` in each addon's `package.mk`.
I also added a fix for stripping addon if we want to re-create a ZIP without rebuilding.
These changes are included in my community 8.0 builds and so far no issues reported.

Addon stripping improvements

---

scripts/image

Print depmod errors so that we can see unresolved symbols when building. This is handy when including out-of-tree drivers, e.g. `media_build`. If a symbol cannot be resolved, the module is non-functional and we should fix it, not ship it.

scripts/image: print depmod errors

---

packages/linux-drivers/gpu-aml/patches/gpu-aml-0001-dont-use-mali-utilization.patch

This settings turns off any scaling for Mali cores/frequency. The effect of this is smooth Kodi GUI operation without a need to set turbo mode in driver parameter or device tree.
Users reported smoother GUI with UTILIZATION = 0 and Mali operating at 500MHz than with UTILIZATION = 1 and Mali at 666MHz.
It's also worth to note that `USING_GPU_UTILIZATION ?= 0` is default setting in Mali driver source code from ARM.

gpu-aml: Do not use Mali Utilization

---

packages/linux-drivers/gpu-aml/patches/gpu-aml-0001-dont-use-mali-utilization.patch

Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/1390
This settings turns off any scaling for Mali cores/frequency.
The effect of this is smooth Kodi GUI operation without a need
to set turbo mode in driver parameter or device tree.
Users reported smoother GUI with UTILIZATION = 0 and Mali operating at 500MHz
than with UTILIZATION = 1 and Mali at 666MHz.

gpu-aml: Do not use Mali Utilization [backport]

---

packages/graphics/mesa/package.mk
packages/lang/llvm/package.mk

This is currently in my Generic test builds (starting with #0225).

mesa: update to mesa-17.0.0 with llvm-3.9.1 bump

---

packages/mediacenter/kodi/config/appliance.xml
packages/mediacenter/kodi/patches/kodi-999.99-ADSP-hack.patch
tools/RPi/rpi-kodi-rebase.sh

See thread: https://forum.libreelec.tv/thread-4606-post-37112.html#pid37112
This will hide the entire ADSP settings group in LE 8.0.1.
Instead of this:
there will be this:
If "audio DSP processing" has already been enabled in an earlier release, users will have to go back to a previous release that allowed the ADSP setting to be enabled/disabled (ie. 8.0.0, 7.95.x beta or 7.90.xxx alpha) in order to disable the now hidden setting.
Or they can edit `guisettings.xml` and set `<dspaddonsenabled>false</dspaddonsenabled>`.
About the only other option that comes to mind is to force `dspaddonsenabled` disabled via a `sed` in `kodi-config.sh`, which isn't great. Any better options, preferably that don't involve patching Kodi?

kodi: hide ADSP settings

---

packages/graphics/libprojectM/patches/libprojectM-hacky-removal-of-glew-spiff.patch
packages/mediacenter/kodi-binary-addons/visualization.projectm/patches/visualization.projectm-03-remove-glew-spiff.patch

These patches are from @notspiff and allow projectM to build without glew.
I'm submitting this PR as a quick fix for 8.0.0 (assuming it works - I've not tested this on 8.0, but it should work).
I've only tested these patches on LE9 and Kodi 18a1, and they work. I can submit this PR to master as well, but we may instead want to bump libprojectM to 2.1.0 which requires a lot more work that @lrusak indicates he has already done. If you want a PR for master as well, let me know.

projectM: remove glew

---

packages/graphics/libprojectM/patches/libprojectM-hacky-removal-of-glew-spiff.patch
packages/mediacenter/kodi-binary-addons/visualization.projectm/patches/visualization.projectm-03-remove-glew-spiff.patch

Same as #1378, but for master.
This allows us to build projectM again (many thanks @notspiff!)
We can update to libprojectM 2.1.0 in future (there's currently a problem loading the 2.1.0-based add-on) but having this PR at least fixes the current build issue.

projectM: remove glew [LE9]

---

projects/RPi/linux/linux.arm.conf
projects/RPi2/linux/linux.arm.conf

driver was (accidentally?) disabled when upgrading from kernel 4.4 to 4.6 in commit 012fd9bca0864ec8b88e80facab7b244f6ae2216

LE8: RPi/RPi2: re-enable lirc_xbox driver

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk
packages/addons/addon-depends/emby-depends/imagemagick/package.mk
packages/addons/addon-depends/emby-depends/x264/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk
packages/addons/tools/mono/changelog.txt
packages/addons/tools/mono/package.mk

Emby 3.2.5 requires Mono >= 4.6
Mono 4.8.0.495 builds for and runs on RPi2 (Emby, WebGrabPlus and other addons run)
Updated ffmpegx, imagemagick and x264

emby: update to 3.2.5

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/system.d/brcmfmac_sdio-firmware.service
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/udev.d/90-rpi-add-serial.rules

As mentioned by @popcornmix:
> @pelwell suggested using the /usr/bin/btuart from latest raspbian. It looks like this: http://paste.debian.net/917481/
> Basically Pi0W now has flow  control on BT uart, so can run a bit faster. But there are two uarts and they can be swapped in config.txt if you need the "better" one for other purposes, so this also handles that case.
>
> The raspbian btuart should work for Pi0w and Pi3, and also when uarts have been swapped in config.txt.
The udev.d rule adds the correct /dev/serial1 device, which is then used by `rpi-btuart` to bring up Bluetooth.
Thanks @popcornmix & @pelwell.

brcmfmac_sdio-firmware-rpi: Implement Raspbian udev rules and btuart

---

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
packages/linux-drivers/media_build/sources/backports/linux-063-fix-rc-raw-decoder-loading.patch
packages/linux/patches/default/linux-063-fix-rc-raw-decoder-loading.patch

The fix was just added to the media/fixes tree and should land in stable kernels in the near future.

[LE8] Fix IR decoder modules not loading automatically

---

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
packages/linux-drivers/media_build/sources/backports/linux-063-fix-rc-raw-decoder-loading.patch
packages/linux/patches/default/linux-063-fix-rc-raw-decoder-loading.patch

The fix was just added to the media/fixes tree and should land in stable kernels in the near future.

Fix IR decoder modules not loading automatically

---

projects/RPi/options

RPi: build brcmfmac_sdio-firmware-rpi for Pi0W

---

projects/RPi/options

RPi: build brcmfmac_sdio-firmware-rpi for Pi0W [backport]

---

projects/imx6/patches/linux/3.14-sr/linux-020-gpio-ir-recv-add-timeout-on-idle.patch
projects/imx6/patches/linux/4.4-xbian/linux-020-gpio-ir-recv-add-timeout-on-idle.patch

fixes Logitech Harmony One and probably others
https://forum.libreelec.tv/thread-4813.html

imx6/linux: add timeout on idle for gpio-ir-recv [backport]

---

projects/imx6/patches/linux/3.14-sr/linux-020-gpio-ir-recv-add-timeout-on-idle.patch
projects/imx6/patches/linux/4.4-xbian/linux-020-gpio-ir-recv-add-timeout-on-idle.patch

fixes Logitech Harmony One and probably others
https://forum.libreelec.tv/thread-4813.html

imx6/linux: add timeout on idle for gpio-ir-recv

---

packages/addons/addon-depends/libdvbcsa/package.mk

I've made some performance improvements since 4ce8be8.
To run tests, copy `.../build.LibreELEC-.../libdvbcsa-XXXXXXX/test` directory to the target device and run
```
./testenc && ./testdec && ./testbsops && ./testbitslice && seq 10 | xargs -n1 ./benchbitslice
```
It would be nice if someone could run benchmarks on AArch64 to make sure `--enable-uint64` is still faster than `--enable-neon` (see the comment in `package.mk`).

libdvbcsa: update to aae3d0c

---

packages/mediacenter/LibreELEC-settings/package.mk

this moves update checks to https

settings: bump to v0.8.10

---

packages/mediacenter/kodi/package.mk
packages/mediacenter/kodi/scripts/xml_merge.py

Cleanup some remaining build issues.
I've amended `xml_merge.py` to...
- Use any number of inputs
- Any input file that doesn't exist won't be read, so no need to silently handle `IOError`s
- Any input file that cannot be parsed will print the name of the file to `stderr` before re-raising the exception
- Raise exception when there are no input files instead of assert (which can be disabled at compile time)

buildystem: Cleanup fixes

---

packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
packages/addons/tools/multimedia-tools/changelog.txt
packages/addons/tools/multimedia-tools/package.mk

To fix https://forum.libreelec.tv/thread-5887.html

multimedia-tools: update squeezelite to a3d95ec

---

packages/graphics/bcm2835-driver/package.mk
packages/multimedia/ffmpeg/patches/ffmpeg-99.1003-pfcd_hevc_optimisations.patch
packages/tools/bcm2835-bootloader/package.mk

@chewitt - couple of extra RPi commits that would be good to get into the next 8.x.
From @popcornmix:
>FYI I've added https://github.com/popcornmix/xbmc/commit/20c7b371e3337a983276193226ef61f9356edf66 to backports. That solves an issue on newclock5 with half second pauses when playing iplayer dash streams. While I'm not certain those streams occur on Krypton, the bug in general an could be triggered by any stream that happens to cause video decode frames to be a little bursty. 
I've rebased the support patch and removed the two CEC commits.

RPi/RPi2: Update kodi support patches

---

packages/graphics/mesa/package.mk

Only critial issue/bug fixes here
https://www.mesa3d.org/relnotes/13.0.4.html
https://www.mesa3d.org/relnotes/13.0.5.html
https://www.mesa3d.org/relnotes/13.0.6.html
All changes described:
New features
"None" !
some fixes related with kodi
Bug 99158 - vdpau segfaults and gpu locks with kodi on R9285
label please: LE8
for LE9 we using mesa 17.0.x

mesa: bump to 13.0.6

---

scripts/clean
scripts/unpack

When a package version is bumped this change allowed the old package to remain in the build directory.
Although undesirable (and unintended), normally this wouldn't be a huge problem unless performing a wildcard copy as in the case of [bcm2835-bootloader/release](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/tools/bcm2835-bootloader/release#L24).
Reverting this change restores the original behaviour which is correct (now that I fully understand why it's doing what it is/was doing!)
Thanks and apologies to @HiassofT and [indri](https://forum.libreelec.tv/thread-6541-post-41055.html) :)
(No need for a backport, these changes are LE9 only)

scripts: revert changes that led to accumulation of old packages

---

config/path

Automatically add $MEDIACENTER (ie. `kodi`) to PKG_NEED_UNPACK for addons so that whenever `kodi` is bumped the add-ons will be automatically cleaned prior to building.
Could be backported if required.

config/path: addons need kodi

---

packages/addons/addon-depends/libdvbcsa/package.mk

I have performed tests on Aarch64, WeTek Hub:
* `--enable-uint64` gives ~200 Mbits/s
* `--enable-neon` gives ~215 Mbits/s
Ping @glenvt18

libdvbcsa: use enable-neon for Aarch64

---

packages/sysutils/systemd/package.mk
packages/sysutils/systemd/scripts/userconfig-setup
packages/sysutils/systemd/system.d/userconfig.service

If we change our sample config files (for example, see samba4 bump) then we don't overwrite any existing conf.sample file. This results in upgrading users having out of date (and possibly erroneous or problem causing) sample config files.
This change will remove those sample config files we maintain, before updating `/storage/.config` with new files.

userconfig: overwrite our sample files

---

distributions/LibreELEC/options
packages/tools/installer/scripts/installer
scripts/mkimage

This PR changes partition alignments from 1MiB to 4MiB that is the recommended alignment for sd-cards.
The following changes have been made:
- Start of system partition is moved to 4MiB instead of 1MiB
- Size of system/storage partition is reduced by 1 sector to make them perfectly aligned
- The ~1MiB between system and storage partition is removed
- Calculation of the disk image size now depend on the start position of the system partition
Before:
```
Disk LibreELEC-RPi2.arm-8.0.0.img: 1122304s
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:
Number  Start     End       Size      Type     File system  Flags
1      2048s     1050624s  1048577s  primary  fat16        boot, lba
2      1052672s  1118208s  65537s    primary  ext4
```
```
Disk …
```

scripts/mkimage: align partitions to 4MiB

---

packages/mediacenter/kodi/patches/aarch64/kodi-0006-aml-Scale-video-axis-correctly-when-1080p-to-2160p-switching.patch

Fixes only a part video visible when switching from 720p to 1080p/4K during frame rate automation process.
Upstream PR: https://github.com/xbmc/xbmc/pull/11935

kodi/aarch64: fix 720p -> 1080p switch

---

packages/sysutils/lirc/udev.d/98-lircd.rules

see https://forum.libreelec.tv/thread-6724.html

LE8 backport of #1489 lirc: also support lirc devices from the rc subsystem

---

packages/linux/package.mk

This gets rid of the following errors when building the kernel:
```
cp: cannot stat 'projects/Generic/devices//config/*-overlay.dts': No such file or directory
cp: cannot stat 'projects/Generic/devices//config/dt-blob.dts': No such file or directory
```
Currently the only projects or devices with dts files are Slice and Slice3:
```
projects/RPi/devices/Slice/config/dt-blob.dts
projects/RPi/devices/Slice/config/ws2812-overlay.dts
projects/RPi/devices/Slice/config/slice-overlay.dts
projects/RPi/devices/Slice3/config/dt-blob.dts
projects/RPi/devices/Slice3/config/ws2812-overlay.dts
projects/RPi/devices/Slice3/config/slice-overlay.dts
```
With this PR we:
1. Silence the errors when no dts files are present
2. Add support for "common" project-level dts files
3. Avoid accessing the devices …

linux: cp project and device device tree, silence errors

---

projects/imx6/patches/linux/3.14-sr/linux-020-gpio-ir-recv-add-timeout-on-idle.patch

imx6/linux: export symbol used by gpio-ir-recv (forward port of #1494)

---

packages/addons/addon-depends/vdr/patches/vdr-40_caid-buffer-v3.patch

This patch solves a problem with a scrambled german news channel ("N-TV HD") and maybe some others too. Without this patch it is impossible to descramble this channel using oscam.
This patch is part of some major VDR distributions for over a year now and there are no known side effects.

VDR: dynamically resize buffer for caids

---

packages/linux-drivers/wetekdvb/package.mk

Update DVB drivers for WeTek Play and WeTek Play 2 to wetekdvb-20170404.

Update WeTek proprietary DVB modules to wetekdvb-20170404

---

packages/linux-drivers/wetekdvb/package.mk

Update DVB drivers for WeTek Play and WeTek Play 2 to wetekdvb-20170404.
Backport of #1522.

Backport of #1522 (Update WeTek proprietary DVB modules to wetekdvb-20170404)

---

packages/linux-firmware/misc-firmware/package.mk

This corrects various missing BT firmware issues for users switching to LE 8.0.x. Other changes are planned for master (and misc-firmware repo) so no forward-port required.

misc-firmware: change repo and update to 0ed3d22

---

packages/mediacenter/kodi/patches/kodi-999.99-ae-settings-samplerate.patch

workaround to define a minimum sample Rate for broken AVRs
Confirmed by user from forum that patch helped them and again got sound on AVR
Tested on LE8

re-add patch for AE minimal sample rate

---

packages/addons/service/net-snmp/package.mk

This corrects things being staged in the wrong location during build. Thanks @MilhouseVH

net-snmp: correct errant $ROOT usage

---

packages/mediacenter/LibreELEC-settings/package.mk

Use updated methods of starting/stopping lircd after #1320 lirc changes

settings: bump LE settings add-on to 9.0.0

---

packages/devel/rapidjson/package.mk
packages/devel/rapidjson/patches/rapidjson-0001-remove_custom_cxx_flags.patch
packages/mediacenter/kodi-binary-addons/imagedecoder.raw/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.biogenesis/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.greynetic/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.pyro/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.stars/package.mk
packages/mediacenter/kodi/package.mk
packages/mediacenter/p8-platform/package.mk

This PR bumps Kodi and associated platform/addon bits to current versions as it's been a while since we updated them and people are starting to create testing builds. 
NB: The update_binary-addons script still captures the game.retroplayer items so I've included those changes - i'm not sure if that is still intended as there's also a separate update-binary-addons-retroplayer script in tools/mkpkg?

kodi: bump kodi and binary add-ons to current

---

packages/tools/dtc/package.mk

even if tar.xz is requested it is redirected to tar.gz
fixes as described https://forum.libreelec.tv/thread-7906-post-47449.html

dtc: change url and use correct file type

---

packages/sysutils/busybox/scripts/createlog

This is something that's annoyed me for quite some time.
The log files included in `Logfiles/01_KODI.log` (zip) are in a pretty much random order, and as it contains all of the log files from the `.kodi/temp` directory it makes locating the latest `kodi.log` and/or latest `kodi_crashlog_*.log` a somewhat frustrating experience (to the point where I'd rather not deal with `01_KODI.log` at all).
This change brings order to the log files present in the zip:
`01_KODI.log`: `kodi.log` (first) followed by `kodi.old.log`
`01_KODI_CRASH.log`: `kodi_crashlog_*.log` (descending filename, ie. latest first)
`01_KODI_OTHER.log`: any other log files that may be present in `.kodi/temp` (ascending filename)
@chewitt: I can backport this if needed.

createlog: bring sanity to kodi log order

---

packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk

See comment: https://github.com/kodi-pvr/pvr.mythtv/issues/105#issuecomment-275841712
This PR gets us on the correct upstream report - the kodi-pvr/pvr.mythtv repo is dead.

pvr.mythtv: change url, bump to 8db66ca (5.10.0)

---

packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk

See comment: https://github.com/kodi-pvr/pvr.mythtv/issues/105#issuecomment-275841712
This PR gets us on the correct upstream report - the kodi-pvr/pvr.mythtv repo is dead.

pvr.mythtv: change url, bump to c4259bf (4.15.0) [LE8]

---

packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk

See: https://github.com/xbmc/repo-binary-addons/blob/master/pvr.vdr.vnsi/pvr.vdr.vnsi.txt
This repo has moved from `kodi-pvr` to a personal repo, but only for master - the `Krypton` branch continues to use `kodi-pvr` so there is no need to backport this.
I haven't used the tip of tree from the new repo as it includes recent changes not compatible with the current Kodi master in this LE repo. We'll pick those commits next time we bump Kodi.
I've been including this add-on from the new repo for some time in my test builds so it should build with this PR.

pvr.vdr.vnsi: change url, bump version

---

projects/imx6/filesystem/usr/lib/systemd/system/serial-console.service

sometimes terminal is not initialized properly (no cursor visible)

projects/imx6: init terminal with reset command in console service

---

tools/mkpkg/update_binary-addons

Just a quick hack to ignore `game.*` addons when updating binary addons.

tools/update_binary-addons: ignore game.* addons

---

projects/Odroid_C2/patches/u-boot/u-boot-0003-update_cec_simplink_wakeup.patch

Using this Patch a LG TV can wake up an Odroid C2 using Simplink Vendor CEC commands. 
I wasn't able to test it myself but thanks to odroid forum user "Jacobo" for providing Logs and doing tests on actual LG hardware I'm sure it's working.
I can create a LE8 backport if necessary.

Odroid_C2/u-boot: Make LG CEC (Simplink) wakeup work

---

projects/imx6/bootloader/uEnv-matrix.txt
projects/imx6/bootloader/uEnv-udoo.txt
projects/imx6/bootloader/uEnv.txt
projects/imx6/patches/linux/3.14-sr/linux-410-limit-eth-speed-100mbits.patch
projects/imx6/patches/linux/4.4-xbian/linux-410-limit-eth-speed-100mbits.patch

to enable gigabit speed module parameter via kernel command line
must be set in form fec.disable_giga=0

imx6/linux: limit ethernet speed to 100mbits which works reliable

---

packages/audio/pulseaudio/package.mk
packages/multimedia/ffmpeg/package.mk

ffmpeg-3.3 includes new support that depends on NEON which isn't being enabled on aarch64, so the ffmpeg build fails:
```
LD      ffmpeg_g
libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy64_aarch64'
libavcodec/libavcodec.so: undefined reference to `ff_idctdsp_init_aarch64'
libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy32_aarch64'
libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy128_aarch64'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:136: ffmpeg_g] Error 1
make[1]: Leaving directory '/home/neil/projects/LibreELEC.tv/build.LibreELEC-WeTek_Play_2.aarch64-9.0-devel/ffmpeg-eb0819c'
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 2
```
PulseAudio-10.0 will fail to build with NEON enabled on aarch64:
``` …
```

aarch64/neon: update neon checks in ffmpeg and pulseaudio

---

packages/audio/alsa-lib/patches/alsa-lib_HdmiLpeAudio.patch

It's a playback-only device with a single PCM dedicated for HDMI/DP
output.  The dmix is working with the latest driver code, so enable it
for default, while providing the hdmi PCM dev for the accesses with
AES bits.
dont merge - until kernel 4.11

Intel HDMI/DP LPE audio config

---

config/path
scripts/get
tools/distro-tool

As discussed with @vpeter4 on #irc.
This PR adds optional checksum verification for downloaded packages.
Package verification is entirely optional, and the behaviour of `scripts/get` is unchanged when a package does not specify a value for `PKG_SHA256`.
The value for `PKG_SHA256` is the value that is written to `*.sha256` once a file is successfully downloaded.
When bumping packages, one option to obtain the new checksum would be to comment out `PKG_SHA256` so that the new tarball is downloaded (and not verified), and then the new checksum value from `*.sha256`  is added to the bumped `package.mk`.

build system: verify package downloads using sha256 checksum

---

projects/imx6/patches/kodi/kodi-200-handle-SIGTERM-after-vivante.patch

seems imx-gpu-viv-5.0.11.p7.4-hfp overwrites signal handler
thats why we set it again after GUI is already created
without this patch kodi exits immediately on any received signal
and settings are not saved
this pr is send only to libreelec-8.0 branch
for master I will investigate for some other solutions (like
downgrading or upgrading galcore for a few versions)

imx6/kodi: reinstall SIGTERM signal handler after GUI is created

---

packages/debug/libva-utils/package.mk
packages/virtual/debug/package.mk

ping @MilhouseVH and @piotrasd 
The change to intel-vaapi-driver moved vainfo to libva-utils

libva-utils: initial package

---

packages/devel/libcec/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk

bcm2835: fix missed renames from bcm2835-firmware -> bcm2835-driver

---

projects/RPi/patches/linux/linux-02-RPi_clk_fix.patch
projects/RPi2/patches/linux/linux-02-RPi_clk_fix.patch

This fixes 48kHz samplerate not working on HifiBerry Amp+.
See https://github.com/raspberrypi/linux/issues/2016
This patch can be dropped on the next RPi kernel bump, it comes from the rpi-4.9.y tree
https://github.com/raspberrypi/linux/commit/76527b4e6a5dbe55e0b2d8ab533c2388b36c86be
Master will get the fix on the next RPi kernel bump, the fix is included in the 4.11 and 4.12 trees as well

[LE8] RPi/RPi2: add kernel patch to fix I2S clock

---

packages/linux/sysctl.d/qdisc.conf
projects/Generic/linux/linux.x86_64.conf
projects/Odroid_C2/linux/linux.aarch64.conf
projects/RPi/devices/RPi/linux/linux.arm.conf
projects/RPi/devices/RPi2/linux/linux.arm.conf
projects/WeTek_Core/linux/linux.arm.conf
projects/WeTek_Hub/linux/linux.aarch64.conf
projects/WeTek_Play/linux/linux.arm.conf
projects/WeTek_Play_2/linux/linux.aarch64.conf

This qdisc aims to eliminate bufferbloat and as a side effect improves
latency during heavy network load. The most notable effect will be a
slightly more responsive ssh session during large downloads.
Systemd will autoselect fq_codel when it's available:
m8s:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 4096 qdisc noqueue
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP8000> mtu 1500 qdisc fq_codel
qlen 1000
link/ether 82:cd:fa:1b:03:1d brd ff:ff:ff:ff:ff:ff
inet 172.20.0.166/24 brd 172.20.0.255 scope global eth0
valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP8000> …

linux: enable fq_codel for all projects

---

packages/linux-drivers/wetekdvb/package.mk

Rebase of 34de01dfa552ac391485044a169a81c2511ad194 - use older wetekdvb for WP1 project

wetekdvb: Use older WeTek proprietary DVB modules if building for WP1

---

packages/devel/libcec/package.mk
packages/graphics/imx-gpu-viv/package.mk
packages/linux/package.mk
projects/imx6/linux/4.4-xbian/linux.arm.conf
projects/imx6/options

Variable LINUX_VERSION now took value '3.14-sr' to build imx6 project with 3.14 kernel from solidrun.

imx6/options: unify linux version strings and simplify it's usage

---

packages/mediacenter/kodi/package.mk
packages/virtual/mediacenter/package.mk

Fix for joystick support option. It currently does nothing. Also removed kodi joystick build option. As far as I can tell $KODI_JOYSTICK goes unset and I can't see any joystick support build options in kodi's cmakelist anyway.

peripheral.joystick: fix JOYSTICK_SUPPORT build option

---

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk

current githash results in a build error ~ this is the one advised by peak3d

addons: fix githash for inputstream.adaptive

---

packages/addons/addon-depends/rpi-tools-depends/lan951x-led-ctl/package.mk
packages/addons/tools/rpi-tools/package.mk

adds the ability to turn off the rpi lan leds
test build here, http://lrusak.libreelec.tv/public/lan951x-led-ctl

add lan951x-led-ctl

---

packages/addons/addon-depends/system-tools-depends/screen/package.mk
packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk

This PR fixes the issue when only eight basic colors (0-7) are displayed regardless of TERM setting. It's netbsd-curses specific and is caused by a wrong configure decision made while cross-compiling. This PR also enables 256 color support and updates to the recent stable version.

GNU screen color fixes

---

packages/devel/glibc/package.mk

This restores `ldd`, `getent` and `locale` after they were dropped by #1616, as they're kinda useful...
I've used a simple nested loop, for simplicity. I could have used something more fancy such as:
```
findignore=
for gib in $GLIBC_INCLUDE_BIN; do
findignore+=" -not -name ${gib}"
done
find $INSTALL/usr/bin -type f ${findignore} -delete
```
but from a scalability point of view I didn't want to get into a situation where we might be calling `find` with a large number of `-not foo` arguments (even if that is unlikely) and maybe hit some sort of limit.
So, simple is best.
The combined uncompressed size of these 3 binaries is: 55KB (RPi/RPi2) and 69KB (Generic)

glibc: re-enable programs, remove those we don't want

---

packages/sysutils/e2fsprogs/package.mk

As requested: https://github.com/LibreELEC/LibreELEC.tv/pull/1685#issuecomment-308092350
I don't consider this strictly necessary, but shouldn't do any harm.

e2fsprogs: avoid installing read-only files into the toolchain

---

packages/sysutils/e2fsprogs/package.mk

As mentioned on Slack, clean builds do not build and install the `fuse2fs` binary.
However, if `e2fsprogs` is ever rebuilt then `fuse2fs` will be automatically enabled by `configure` whenever `fuse.h` is detected, and then `fuse2fs` will be built and installed.
`fuse.h` is installed by the `fuse` package which is built near the end of the build long after `e2fsprogs` (it's needed by `fuse-exfat` in order to create the image).
So a clean build will not include `fuse2fs`, but a later incremental build that rebuilds `e2fsprogs` will contain `fuse2fs`.
In order to remove this uncertainty from the build, this PR explicitly disables `fuse2fs`.

e2fsprogs: do not build fuse2fs

---

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-01-add_new_cards.patch

As discussed in https://forum.libreelec.tv/thread/7057-tplink-archer-t4u-v2-ac1300-issue/?postID=46614, this change was once tested with the correct VendorID, but two codes were mixed up while creating the pull request. The correct USB ID for the TP-Link T4U is 2357:010d.

Correcting VendorID for TP-Link T4U v2

---

packages/linux-firmware/firmware-imx/package.mk

This makes it so we don't have to host the source anymore.

firmware-imx: use upstream url

---

packages/addons/service/tvheadend42/package.mk

"reopen" pr (see #1672) @lrusak

tvheadend42: fix build with empty ARCH variable

---

packages/sysutils/fuse/patches/fuse-0002-dont-run-update-rc.d.patch

Cross compiling should never call scripts that could change the host system.
When building on Debian Stretch as unprivileged user this causes the build to pause and ask for the root password which will eventually time out and continue.
```
/usr/sbin/update-rc.d fuse start 34 S . start 41 0 6 . || true
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: stop runlevel arguments (0 6) do not match fuse Default-Stop values (none)
insserv: warning: current stop runlevel(s) (0 6) of script `fuse' overrides LSB defaults (empty).
insserv: fopen(.depend.stop): Permission denied
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: root
Password: …
```

fuse: don't run /usr/sbin/update-rc.d on install

---

packages/sysutils/fuse/patches/fuse-0002-dont-run-update-rc.d.patch

[8.2] backport fuse: don't run /usr/sbin/update-rc.d on install

---

distributions/LibreELEC/options
projects/Odroid_C2/options
projects/RPi/options
projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play/options
projects/WeTek_Play_2/options
projects/imx6/options

Currently we only build RPiX with swap support and all other platforms not.
This PR removes from the projects the swap options and activate swap for all devices at distribution options.
opinions ?
@codesnake @MilhouseVH @lrusak @vpeter4

activate swap for all projects

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk

to be in sync with 8.2 (no rev bump because master addons wasn't build at all)

tvheadend42: update to 4.2.2-75

---

packages/audio/libsndfile/package.mk
packages/audio/sbc/package.mk
packages/audio/soxr/package.mk
packages/databases/sqlite/package.mk
packages/devel/netbsd-curses/package.mk
packages/devel/readline/package.mk
packages/multimedia/rtmpdump/package.mk
packages/security/libgpg-error/package.mk
packages/sysutils/systemd/package.mk
packages/textproc/tinyxml/package.mk

I needed this when building without lto support. I don't think it should harm anything but would be work including in a @MilhouseVH build

Enable -fPIC for some packages

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch

Merge this at 4.11.8 (perhaps in a week or two, depending on when .7 and .8 appear).
4.11.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.5
4.11.6 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.6
4.11.7 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.7
4.11.8 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.8

linux: update to linux-4.11.8

---

packages/addons/service/bluetooth-audio/changelog.txt
packages/addons/service/bluetooth-audio/package.mk
packages/addons/service/bluetooth-audio/source/default.py
packages/addons/service/bluetooth-audio/source/resources/language/English/strings.po

On LE8:
```
ERROR: POParser: unable to read PO file header from file: /storage/.kodi/addons/service.bluetooth-audio/resources/language/English/strings.po
```
and
``` 
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.RuntimeError'>
Error Contents: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
File "/storage/.kodi/addons/service.bluetooth-audio/default.py", line 185, in <module>
client = BluetoothAudioClient()
File …
```

bluetooth-audio: fix log errors

---

packages/mediacenter/kodi/package.mk

debug fission uses -gsplit-dwarf which creates separate .dwo debug files that live in the build directory. We don't want this. We want to include all the debug symbols in the build when we do a debug build.

kodi: disable using debug fission

---

distributions/LibreELEC/options
packages/tools/installer/scripts/installer
scripts/mkimage

This PR is a backport of #1431 scripts/mkimage: align partitions to 4MiB

LE8.2: backport of scripts/mkimage: align partitions to 4MiB

---

packages/sysutils/busybox/scripts/init

Do not use dd option conv=fsync when updating kernel on a block device.
Makes updates much faster for NAND installations on Amlogic-based devices.

aml: Make updates faster

---

packages/sysutils/busybox/scripts/init

Do not use dd option conv=fsync when updating kernel on a block device.
Makes updates much faster for NAND installations on Amlogic-based devices.
Backport of #1768.

LE 8.2: aml: Make updates faster

---

packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk

@popcornmix advises this githash (as used in 8.0) should be used

addons: fix screensaver.shadertoy githash

---

scripts/create_addon

fixes
```
PROJECT=Odroid_C2 ARCH=aarch64 ./scripts/create_addon imon-mce
CREATE ADDON  (Odroid_C2/aarch64) imon-mce
find: '/builddir/addons/imon-mce/driver.remote.imon-mce': No such file or directory
*** WARNING: driver.remote.imon-mce-8.2.100.zip already exists. not overwriting it ***
```
and
```
PROJECT=Generic ARCH=x86_64 ./scripts/create_addon screensavers.rsxs
CREATE ADDON  (Generic/x86_64) screensavers.rsxs
find: '/builddir/addons/screensavers.rsxs/screensavers.rsxs': No such file or directory
```

scripts/create_addon: fix debug_strip

---

scripts/create_addon

fixes
```
PROJECT=Odroid_C2 ARCH=aarch64 ./scripts/create_addon imon-mce
CREATE ADDON  (Odroid_C2/aarch64) imon-mce
find: '/builddir/addons/imon-mce/driver.remote.imon-mce': No such file or directory
*** WARNING: driver.remote.imon-mce-8.2.100.zip already exists. not overwriting it ***
```
and
```
PROJECT=Generic ARCH=x86_64 ./scripts/create_addon screensavers.rsxs
CREATE ADDON  (Generic/x86_64) screensavers.rsxs
find: '/builddir/addons/screensavers.rsxs/screensavers.rsxs': No such file or directory
```

backport of #1794

---

packages/devel/heimdal/package.mk
packages/network/samba/package.mk

Update Samba and Heimdal with fix for the latest security vulnerability.
https://www.h5l.org/advisories.html?show=2017-07-11
CVE-2017-11103 ([Orpheus' Lyre](https://www.orpheus-lyre.info/) mutual authentication validation bypass)

samba/heimdal: update to samba-4.6.6 and heimdal-7.4.0

---

packages/linux-firmware/intel-ucode/package.mk
packages/linux/package.mk

When booting HSW/BDW/SKL/SKX/KBL Intel CPUs and 4.13-rc1 with current Intel ucode the following message may be displayed:
```
[    0.000000] [Firmware Bug]: TSC_DEADLINE disabled due to Errata; please update microcode to version: 0xb2 (or later)
```
The ucode in this package bump should be applied to older kernels as it's just that [as of 4.13.y](https://lkml.org/lkml/2017/5/31/599) the firmware bug message is being displayed whenever out of date ucode is detected.
See also: https://bugs.launchpad.net/ubuntu/+source/intel-microcode/+bug/1700373
From https://downloadcenter.intel.com/download/26925/Linux-Processor-Microcode-Data-File
> Detailed Description
> The microcode data file contains the latest Linux* microcode definitions for all Intel® Processors. Intel periodically releases these …

intel-ucode: update to intel-ucode-20170707

---

packages/network/ethtool/udev.d/99-wakeup-eth.rules
packages/sysutils/systemd/package.mk
packages/sysutils/udevil/udev.d/95-udevil-mount.rules
packages/tools/hdparm/udev.d/61-cdrom.rules

This is largely cosmetic, removing some annoyances, but might have a slight performance benefit - I don't think there will be any drawbacks.
This change avoids mounting the `/flash` and `/storage` partitions through `udevil` when they have already been mounted by `init`. 
The following is the boot sequence on an RPi system with `/flash` and `/storage` on `/dev/mmcblk0p[1,2]`, and a third `Images` parition on `/dev/sda1` that is to be auto-shared by Samba.
```
Jul 07 20:23:55 rpi22 systemd[1]: Starting Udevil mount service...
Jul 07 20:23:55 rpi22 systemd[1]: Starting Udevil mount service...
Jul 07 20:23:55 rpi22 systemd[1]: Starting Samba SMB Daemon...
Jul 07 20:23:55 rpi22 systemd[1]: Starting Samba NMB Daemon...
Jul 07 20:23:55 rpi22 udevil[538]: udevil: denied 92: device /dev/mmcblk0p2 …
```

udev: cleanup

---

scripts/checkdeps
scripts/create_addon

This will fix `scripts/checkdeps` for `libjson-perl` as the test for this perl module wasn't working post installation - it was checking a file which would never exist. This change now makes the check for `libjson-perl` more robust by adding a test function facility that will be automatically used if it exists, otherwise fall back on the existing file name check.
The change also eliminates the repetition of the yes/no question, while accepting both `y` and `yes` (case insensitive) - prior to this change, `yes` would abort the update...

scripts/checkdeps: fix library test

---

projects/imx6/patches/RTL8812AU/RTL8812AU-010-compile-3.14.patch

Fixes imx6 patch for v5.1.5 driver.
Backport is in #1823

imx6: update RTL8812AU patch

---

packages/linux-firmware/kernel-firmware/firmwares/any.dat
packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat

This adds a few firmwares that are referenced by kernel modules we build.
In particular it adds the two htc firmwares found in the root needed by WeTek hardware (thanks @hiassoft), and the rt2870.bin firmware needed by various Ralink chipsets [[1](https://forum.kodi.tv/showthread.php?pid=2625135#pid2625135)][[2](https://forum.kodi.tv/showthread.php?tid=298461&pid=2625272#pid2625272)]
This is an interim solution to a more thorough LE9 cleanup in #1848.

kernel-firmware: band aid additions for libreelec-8.2

---

packages/mediacenter/kodi/config/appliance.xml
packages/network/samba/patches/samba-951-backport-SMB3_11-default.patch

Drop the Samba patch when Samba 4.7 arrives.
The `appliance.xml` change depends on https://github.com/xbmc/xbmc/pull/12110 so don't merge this PR until we've bumped to a version of Kodi that includes PR12110.

samba: make SMB3_11 the default protocol, don't force in kodi

---

packages/linux-firmware/kernel-firmware/firmwares/any.dat
packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat
packages/linux/package.mk
projects/imx6/kernel-firmware/firmwares/any.dat

This is another attempt at only installing the firmware we actually need/use.
The changes in this PR are based on an analysis of kernel modules (all projects) and the information reported by `modinfo`. While not 100% reliable, it's a start and did identify some firmwares we need but were not including.
Firmwares that are now dropped - ie. `mwl8k`, `mwlwifi`, `ath6k`, `ath10k`, `libertas` - do not appear to be used by any kernel modules.
The `e100` firmwares should be in `initrd`, as they're used mostly by PRO/100 PCI adapters (this only adds 1.5KB).
`rtl_nic` is already included in `initrd`, and doesn't need to be included a second time in the image (at least, I don't think it does...)
`mrvl`, `ti-connectivity` and a handful of other firmwares are only used by the `imx6` 4.4-xbian kernel. …

kernel-firmware: cleanup pt2

---

packages/sysutils/busybox/scripts/init

This is a minor bug fix.
If `mount` fails during `get_project_arch()` (eg. the new image is corrupt or using an unsupported compression format) then the `error()` function will be called which calls `debug_shell()`, which in turn calls `showcursor()` - this sends the escape sequence to enable the cursor to `stdout`.
Unfortunately, `get_project_arch()` is consuming `stdout`, so the user is left without a cursor.
This change forces the output from `error()` to be sent to `stderr`.
In addition, it ensures that `mount_common()` (via `mount_part()`) returns a usable exit code, which can be detected by the caller allowing appropriate action to be taken, rather than (for example) subsequently attempting to `umount` a partition that was never mounted.
@chewitt: This could be backported if needed.

init: fix error handling during get_project_arch

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk

Runtime tested OK on RPi1 and RPi3.
I pinged @popcornmix to check if it would be worth bumping the "stable" firmware branch, so I'd suggest waiting until he's able to reply.

linux: update to linux-4.9.41 [le82, RPi/RPi2]

---

packages/multimedia/ffmpeg/package.mk

Successfully tested on generic.

Bump ffmpeg to 3.1.9-Krypton-17.4 [le82]

---

config/functions
config/path
scripts/autoreconf
scripts/build
scripts/clean
scripts/get
scripts/install
scripts/unpack

This change is inspired by #1869 (which can be closed).
1. Add your custom colour options to `$HOME/.libreelec/options`
2. Default colours are:
```
CLR_ERROR=boldred
CLR_WARNING=boldred
CLR_WARNING_DIM=red
CLR_APPLY_PATCH=boldgreen
CLR_AUTORECONF=boldmagenta
CLR_BUILD=boldyellow
CLR_CLEAN=boldred
CLR_FIXCONFIG=boldyellow
CLR_GET=boldcyan
CLR_INFO=boldgreen
CLR_INSTALL=boldgreen
CLR_PATCH_DESC=boldwhite
CLR_TARGET=boldwhite
CLR_UNPACK=boldcyan
```
3. Change any colour by associating with an existing colour or a direct escape sequence:
```
CLR_INSTALL=boldblue
CLR_TARGET=boldyellow
```
```
yellowonred="\e[33;41m"
CLR_INSTALL=yellowonred
CLR_TARGET="\e[7;32m" #reverse green
```
4. Disable all colours by adding `DISABLE_COLORS=yes`
I'll submit a backport if this is accepted.

buildsystem: enable custom colours (or none at all)

---

projects/Generic/config/ovf.template
scripts/mkimage

Fix VMware CapacitySize mismatch error upon import of OVA into VMware Player/Workstation/Fusion.
I've tested with Player 12.
Can someone verify with Fusion?

build system: use DISK_SIZE in bytes for ovf template

---

packages/sysutils/busybox/patches/busybox-04-revert-dd-fsync-change.patch

This [change](https://git.busybox.net/busybox/commit/?id=dba0dc1999bb1e8bfe64607e2a9385cda361fcb7) (introduced in 1.27.0) makes no sense - if anyone wanted to perform a single sync they would do that with `dd && sync` without changing the entire behaviour of `conv=fsync`.
Following this change in `busybox`, the upgrade progress indicators are useless as `dd bs=1M conv=fsync` no longer performs a sync every 1MB - there are now long delays where there is no progress, and then the progress jumps to 50% and finally 100% as the entire transfer is synced at the end (rather than at regular intervals **during** the transfer prior to `busybox` 1.27.0).
I've opened a bug: https://bugs.busybox.net/show_bug.cgi?id=10191
Apologies for not catching this sooner, I had assumed my SD card was on the …

busybox: revert dd fsync change which makes no sense

---

config/functions

This addresses two issues:
1. Fixes the issue raised by @InuSasha https://github.com/LibreELEC/LibreELEC.tv/pull/1871#issuecomment-322473439
Apparently bash-4.4 behaves differently to bash-4.3. Splitting the conditions into two tests resolves the issue.
2. If `print_colour CLR_INSTALL ""` is ever used then the `${endcolor}` wouldn't be output which may not be intended. Therefore, change the test to the number of arguments (there's probably other ways of skinning this cat).
@InuSasha can you confirm this is good for you?

config/functions: fix bash-4.4 issue, and empty 2nd param behaviour

---

scripts/mkimage

* drop .img extension for the open virtual appliance (cosmetic)
* change the default syslinux entry from installer to run for the open virtual appliance
Tested with VMware Player 12
Images
Branches
* master: [LibreELEC-Generic.x86_64-9.0-devel-20170816083248-r26711-g6a2d35ac4.ova](https://zalaare.freeddns.org/junkbin/LibreELEC-Generic.x86_64-9.0-devel-20170816083248-r26711-g6a2d35ac4.ova)
* libreelec-8.2 [LibreELEC-Generic.x86_64-8.2-devel-20170816085022-r25993-g8366a8f51.ova](https://zalaare.freeddns.org/junkbin/LibreELEC-Generic.x86_64-8.2-devel-20170816085022-r25993-g8366a8f51.ova)

build system: drop .img extension for the open virtual appliance [backport]

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart
packages/linux-firmware/kernel-firmware/package.mk
packages/linux-firmware/wlan-firmware/package.mk

Currently we install:
`BCM43430A1.hcd` from `brcmfmac_sdio-firmware-rpi`
`brcmfmac43430-sdio.bin` from `kernel-firmware`
`brcmfmac43430-sdio.txt` from `wlan-firmware`
This is crazy, particularly as we need to install updated brcmfmac43430-sdio.{bin,txt} (see [here](https://github.com/raspberrypi/linux/issues/1342#issuecomment-321221748)) but pulling the files from `kernel-firmware` (a repo not under our control) means that is more difficult to do - yes, we could binary patch it...
Now, all three files will be installed from `brcmfmac_sdio-firmware-rpi`.
This PR depends on https://github.com/LibreELEC/wlan-firmware/pull/4 (I'll update this once it is merged).
The change to `kernel-firmware` is a hack, but the best I could think of right now.
If any non-RPi0/RPi3 platforms require …

brcmfmac_sdio-firmware-rpi: Consolidate firmware files

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart
packages/linux-firmware/kernel-firmware/package.mk
packages/linux-firmware/wlan-firmware/package.mk

Backport of #1922 
Dependent on https://github.com/LibreELEC/wlan-firmware/pull/4

brcmfmac_sdio-firmware-rpi: Consolidate firmware files [Backport]

---

packages/debug/libva-utils/package.mk
packages/multimedia/intel-vaapi-driver/package.mk
packages/multimedia/libva/package.mk

FYI the current dev version of intel-vaapi-driver includes a crash when resuming VC-1 content - could be a Kodi bug though: https://forum.kodi.tv/showthread.php?tid=307033&pid=2636351#pid2636351
Bug is not present in 1.8.3, so lets get on to this version and deal with the crash later.

Package Updates: intel-vaapi-driver, libva and libva-utils to 1.8.3

---

scripts/unpack

Renaming (moving) a file is something that `git` supports when patching, but GNU `patch` does not, consequently complex git-based patches that move/rename (but don't otherwise change) files cannot be applied by the LibreELEC patching process. This addresses that issue.

scripts/unpack: use git apply whenever patch includes a renamed file

---

packages/linux/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch

Merge target: 4.12.14 (or when 4.13.0 is released, whichever is first?)
Edit: As 4.13 is now available, this can go in as-is.
4.12.10 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.12.10

linux: update to linux-4.12.10

---

packages/addons/addon-depends/dvb-tools-depends/dvb-apps/package.mk

Newer versions of perl no longer include the current directory
in the default include path which causes dvb-apps compilation to fail.
Fix this by setting the PERL_USE_UNSAFE_INC environment variable
to restore the previous behavior.
See https://perldoc.perl.org/perldelta.html#Removal-of-the-current-directory-(%22.%22)-from-%40INC
for details about the perl change

[8.2] dvb-apps: fix compilation with current perl versions

---

packages/addons/addon-depends/dvb-tools-depends/dvb-apps/package.mk

Newer versions of perl no longer include the current directory
in the default include path which causes dvb-apps compilation to fail.
Fix this by setting the PERL_USE_UNSAFE_INC environment variable
to restore the previous behavior.
See https://perldoc.perl.org/perldelta.html#Removal-of-the-current-directory-(%22.%22)-from-%40INC
for details about the perl change

dvb-apps: fix compilation with current perl versions

---

packages/addons/driver/sundtek-mediatv/changelog.txt
packages/addons/driver/sundtek-mediatv/config/sundtek.conf
packages/addons/driver/sundtek-mediatv/package.mk
packages/addons/driver/sundtek-mediatv/source/bin/sundtek-mediatv.start

once a serial number is in config file then ir_disabled parameter needs to be localized below it (it is not global parameter anymore)

sundtek-mediatv: localize ir_disabled parameter

---

packages/mediacenter/kodi/patches/kodi-999.18-PR12783-spdif-rates.patch

adding patch to extend the rates usable with S/PDIF as per https://forum.libreelec.tv/thread/9823-solved-audio-output-device-192khz-to-384khz-sampling-rates

kodi: make it possible to use 352 khz and 384 khz with S/PDIF

---

packages/sysutils/busybox/scripts/getedid

Seen a user at IRC and he has shown his xorg.conf where the specific line looks like:
Option         "CustomEDID" ""DFP-1":/storage/.config/edid.bin"
So there's a `"` too much in front of the "DFP-1" which should now be fixed.

updated getedid script because of an issue

---

packages/linux/patches/linux-020_default_SMB211_for_CIFS.patch

This is a temporary libreelec-8.2-only fix that rounds out the recent Samba changes and brings CIFS up to par with the Samba server (min protocol=SMB2).
The patch applies cleanly on all kernels (v4 and v3), but I've only built and tested v4.x (RPi/RPi2/Generic) so other platform maintainers **please test**.
Kernel 4.14 may  have [protocol auto-negotiation](https://patchwork.kernel.org/patch/9932955/), but that's unlikely to be supported by v3.x kernels in which case this patch may have to be adapted for v3.x kernels in LE9. Maybe one of the v3.x platform maintainers would like to contribute that fix.

linux: enable SMB211 as default for CIFS

---

packages/addons/service/bluetooth-audio/changelog.txt
packages/addons/service/bluetooth-audio/package.mk
packages/addons/service/bluetooth-audio/source/resources/language/English/strings.po

Kodi refuses to load strings.po without it:
```
ERROR: POParser: unable to read PO file header from file: /storage/.kodi/addons/service.bluetooth-audio/resources/language/English/strings.po
```
Completes #1942

bluetooth-audio: add needed strings.po header, version 102

---

packages/sysutils/busybox/scripts/init

Just a small change to the `init` "break after" procedure.
Whenever `debugging break=$step` is configured, the `init` process will drop into a debug shell _after_ $step, eg. after `load_splash`.
However, once you exit from $step, the boot procedure will continue to completion even if you wanted to debug a subsequent step.
This change now means that once you have reached $step and dropped into the debug shell, all subsequent steps will also break and drop into the debug shell. This gives more control over the `init` boot process once $step is reached.
Note that if the debug shell is entered because of an error, the existing boot-to-completion behaviour is unchanged.
In addition, the current boot step has been added to the debug shell message so that users will know where they are in the …

init: make break after behaviour really break after

---

packages/network/samba/config/smb.conf
packages/network/samba/scripts/samba-config

OK, so this should help us avoid the repeated "samba doesn't work" issues when upgrading to 8.2.
Now, we'll ignore the current custom `/storage/.config/samba.conf` (and log a warning in the system log) if either of the following is true:
1) we find `This file is part of OpenELEC` in the second line
2) the embedded version number is missing, invalid, or not what we require
In future if we need to go through this again, then we simply bump `SMB_CONFIG_VERSION` to a new higher value and set the same version in `packages/network/samba/config/smb.conf`, and job done. Users with older/incompatible custom configs will start using the stock config - ie. will have a working Samba server - until they update their config again.
The downside of  this change does mean that users that have already gone …

samba: validate samba user config and don't use if legacy or incompatible

---

packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat

Reported here: https://forum.kodi.tv/showthread.php?tid=298462&pid=2645455#pid2645455
```
[    3.672332] usb 1-4: Direct firmware load for ar3k/AthrBT_0x11020000.dfu failed with error -2
[    3.672338] Bluetooth: Patch file not found ar3k/AthrBT_0x11020000.dfu
[    3.672339] Bluetooth: Loading patch file failed
[    3.672349] ath3k: probe of 1-4:1.0 failed with error -2
[    3.672392] usbcore: registered new interface driver ath3k
[    3.675236] usbcore: registered new interface driver btusb
```
Confirmed fixed here: https://forum.kodi.tv/showthread.php?tid=298462&pid=2646777#pid2646777
~~Will backport.~~ Backport not necessary, ar3k [already included](https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-8.2/packages/linux-firmware/kernel-firmware/firmwares/any.dat#L1).

kernel-firmware: add ar3k firmware for Asus Chromebook M004U

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Latest "stable" RPi firmware for libreelec-8.2. This includes the CEC button fix tested [here](https://forum.kodi.tv/showthread.php?tid=280408&pid=2646517#pid2646517).

RPi: update firmware to 756dd85 (stable)

---

projects/RPi/filesystem/usr/share/alsa/cards/IQAudIODigi.conf
projects/RPi2/filesystem/usr/share/alsa/cards/IQAudIODigi.conf

This should fix this: https://forum.libreelec.tv/thread/9889-iqaudio-pi-digi-passthrough-not-available/
Wait for confirmation if fix is correct before merging

RPi,RPi2: add alsa card conf for IQAudIODigi to enable passthrough

---

projects/RPi/filesystem/usr/share/alsa/cards/IQAudIODigi.conf

This should fix this: https://forum.libreelec.tv/thread/9889-iqaudio-pi-digi-passthrough-not-available/
Wait for confirmation if fix is correct before merging

RPi: add alsa card conf for IQAudIODigi to enable passthrough

---

packages/network/samba/scripts/samba-autoshare

The samba-autoshare script that takes care of sharing mounted drives restarts smbd every time udevil mounts a disk. This can lead to a Samba restart frenzy on boot with several connected disks. This is unnecessary as Samba does not need to be restarted to pick up changes to shares in smb.conf.
This PR modifies samba-autoshare to simply regenerate the configuration (samba-config) and then extend the configuration according to LE settings (smbd-config).

samba: don't restart smbd in samba-autoshare

---

packages/sysutils/busybox/scripts/init

In the event of a failed upgrade, the user will be dumped into the debug shell. If they have a keyboard and know what they're doing, they can manage their way out of the situation, but most users will power cycle the machine. And when the machine boots, it will find the upgrade files, and repeat the upgrade (and fail, etc.)
This change will use the `/storage/update/.tmp` folder as a marker that an upgrade is already in progress, and if found it will clean the files and continue with a normal boot. So in the case where the user power cycles their machine, on the next boot LibreELEC will start more or less cleanly.

init: recover from a failed upgrade

---

packages/linux-drivers/RTL8192EU/patches/RTL8192EU-0101-gcc-5.patch

Fix error caused by #1973 on S905 builds like WeTek_Play_2
If the patch is related to one especific kernel mabye made sense move it to 
projects/[device]/patches/RTL8192EU/*.patch

RTL8192EU: Revert delete to maintain compatibility with AmLogic Kernel

---

scripts/extract
scripts/unpack

Each time `scripts/extract` is called it sources `config/options` which is an expensive operation.
We call `scripts/extract` 8 times for each possible tarball pattern, and for 7 of those 8 calls `scripts/extract` does nothing but source `config/options` and then exit.
This change is more efficient, while functionally equivalent.

scripts/unpack: avoid calling scripts/extract for each tarball pattern

---

packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_SSD1306/package.mk
packages/addons/libraries/adafruit-libraries/changelog.txt
packages/addons/libraries/adafruit-libraries/package.mk

@InuSasha I can't test this nor did I have any clue about it, so pls have a look (it compiles at least)
as "requested" at the forum https://forum.libreelec.tv/thread/9576-compile-libreelec-with-adafruit-python-ssd1306/

adafruit-libraries: include SSD1306 library

---

packages/linux/package.mk

This provides the fix for the bluebourne kernel vulnerability and fixes the IR remote on Hub/C2 after recent RC core changes.

linux: bump Amlogic 3.14 kernel to c8c32b4

---

packages/linux-drivers/RTL8192EU/package.mk

Update from v4.3.1.1_11320.20140505 to v4.4.1
Backport of #1973 & #1984

RTL8192EU: Update to new branch

---

packages/network/samba/package.mk

*  [CVE-2017-12150](https://www.samba.org/samba/security/CVE-2017-12150.html) (SMB1/2/3 connections may not require signing where they should)
*  [CVE-2017-12151](https://www.samba.org/samba/security/CVE-2017-12151.html) (SMB3 connections don't keep encryption across DFS redirects)
*  [CVE-2017-12163](https://www.samba.org/samba/security/CVE-2017-12163.html) (Server memory information leak over SMB1)
Release Notes: https://www.samba.org/samba/history/samba-4.6.8.html

samba: update to samba-4.6.8

---

packages/network/bluez/package.mk
packages/network/bluez/patches/bluez-12_sixaxis-add-support-for-setting-SDP-record.patch

Fixes BlueBorne/CVE-2017-1000250
5.46 [announcement](http://www.bluez.org/release-of-bluez-5-46) / [changelog](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/ChangeLog?id=46f47fc8a1683100c7d08200f420fbb41a3a6754)
5.47 [announcement](http://www.bluez.org/release-of-bluez-5-47) / [changelog](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/ChangeLog?id=d139fd866241fe0d99b5e430f937c8d6160cc7dd)
Not really sure about the `BROWSE_SDP` change - the only other browse type is `BROWSE_GATT`, in which case `BROWSE_SDP` seemed the logical choice...
`BROWSE_SDP`/`BROWSE_GATT` parameters added [here](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/src/device.c?id=5252296b725ef159992be5372f60721bd9adca48), as a fix for this …

bluez: update to bluez-5.47

---

packages/mediacenter/kodi/patches/kodi-999.99-aml_fix_bookmark_thumbnails.patch

Backport of https://github.com/xbmc/xbmc/pull/12056.

[LE 8.2] kodi: backport a patch to fix bookmark thumbnails when using amcodec

---

packages/compress/zstd/package.mk
packages/sysutils/squashfs/package.mk
packages/sysutils/squashfs/patches/squashfs-001-add-zstd-support.patch
scripts/image

This switches to the upstream source for `squashfs` as the sourceforge repository is no longer maintained, and bumps to the latest version which has seen several updates over the last 3 years.
It also adds support for `zstd` v1.3.1 compression for use when creating squashfs images.
`zstd` compression depends on #1991 as it requires a kernel with `zstd` decompression in order for the squashfs image to used.
For this reason, the `zstd` decompression must be supported in the users kernel _before_ they try to upgrade to a system with zstd squashfs image.  This will make upgrading to a `zstd` compressed image tricky, but I'm putting this here so that we can upgrade `squashfs` and test with `zstd`.
This PR can be merged before #1991, but `zstd` compression must not be used until kernels …

squashfs: change upstream, update to squashfs-1a6ffc7, add zstd support

---

scripts/checkdeps

openjdk should be added to deps_pkg:
https://www.archlinux.org/packages/extra/x86_64/jdk8-openjdk/
libjson-perl does not exist on ArchLinux, but perl-json does:
https://www.archlinux.org/packages/community/any/perl-json/

ArchLinux openjdk and libjson-perl

---

packages/mediacenter/kodi/scripts/kodi.sh

Reported in forum: https://forum.libreelec.tv/thread/9995-libreelec-8-1-1-black-screen-with-mouse-pointer/?postID=63793#post63793
From `journalctl`:
```
Sep 23 10:30:58 LibreELEC kodi.sh[619]: /usr/lib/kodi/kodi.sh: line 94: rm: Argument list too long
```
Problem is due to 34694 core files:
```
-rw-------    1 root     root       8654848 Aug  7 14:35 core.!storage!.kodi!addons!plugin.audio.spotify!resources!lib!spotty!x86-linux!spotty-x86_64.1502130943.727
-rw-------    1 root     root       8654848 Aug  7 14:36 core.!storage!.kodi!addons!plugin.audio.spotify!resources!lib!spotty!x86-linux!spotty-x86_64.1502130974.823
-rw-------    1 root     root      10752000 Aug  7 14:37 core.!storage!.kodi!addons!plugin.audio.spotify!resources!lib!spotty!x86-linux!spotty-x86_64.1502131044.900 …
```

kodi: switch to using find to avoid argument limit

---

packages/linux-firmware/dvb-firmware/package.mk

- this fixes major stream problems at Pinnacle 460e sticks (aka not working before)
- added a missing fw

dvb-firmware: update to 1.2.2

---

tools/repo-tool

The test for the device directory was wrong and Slice, Slice3 weren't handled as devices

repo tool: fixes for DEVICE support

---

packages/mediacenter/LibreELEC-settings/package.mk

This resolves an issue with the free space calculation for backups

settings: bump to fix backup free-space calc

---

packages/linux/patches/default-rpi/linux-053-spinelplus-remote-0.2.patch

This should fix spinelplus driver being broken on RPi after commit 3fd44b70ea8
See https://forum.libreelec.tv/thread/10097-mce-ir-driver-not-loading/

[8.2] linux (rpi): sync spinelplus patch with default

---

packages/sysutils/lirc/patches/lirc-0100-disable-python.patch

Lirc python scripts need python 3 or newer (ideally 3.5) so won't work in LE.
Don't install them in the target image and sysroot to avoid build conflicts. See #2040

lirc: don't install python scripts

---

projects/WeTek_Hub/install/updater-script
projects/WeTek_Play_2/install/updater-script

Fix an issue on WeTek Hub and WeTek Play 2 when LE cannot boot after installing on top of Android Marshmallow.
This is already merged to LE 8.2: https://github.com/LibreELEC/LibreELEC.tv/pull/1875.

Fix installation to internal storage on top of Android Marshmallow on WeTek Hub and WeTek Play 2

---

scripts/checkdeps

In OpenSuSE and CentOS perl/JSON.pm provided by package perl-JSON

Fix perl/JSON.pm dependency on OpenSUSE and CentOS

---

projects/Allwinner/linux/linux.arm.conf
projects/Allwinner/patches/linux/07-1-add-H3-H5-DE2-DT-nodes.patch
projects/Allwinner/patches/linux/07-2-add-H3-DE2-DT-nodes.patch
projects/Allwinner/patches/linux/13-dw-hdmi-add-DT-nodes.patch
projects/Allwinner/patches/linux/16-H3-add-HDMI-sound-nodes.patch
projects/Allwinner/patches/linux/24-sun4i-gpadc-iio-add-H3-CPU-thermal-zone.patch
projects/Allwinner/patches/linux/39-rename-s_twi-pinctrl-functions.patch
projects/Allwinner/patches/linux/40-add-SY8106A-regulator-driver.patch
projects/Allwinner/patches/linux/41-h3-h5-Add-r_i2c-controller.patch
projects/Allwinner/patches/linux/42-h3-h5-Add-r_i2c-pins.patch
projects/Allwinner/patches/linux/43-H3-cpux-allow-set-parent.patch
projects/Allwinner/patches/linux/44-H3-clk-cpu-use-pll-notifier.patch
projects/Allwinner/patches/linux/45-add-h3-cpu-OPP-table.patch
projects/Allwinner/patches/linux/46-H3-add-opp-table-to-cpu.patch
projects/Allwinner/patches/linux/47-01-enable-dvfs-opi-zero.patch
projects/Allwinner/patches/linux/47-02-enable-dvfs-opi-one.patch
projects/Allwinner/patches/linux/47-03-enable-dvfs-opi-pc.patch
projects/Allwinner/patches/linux/47-04-enable-dvfs-opi-2.patch
projects/Allwinner/patches/linux/47-05-enable-dvfs-opi-lite.patch
projects/Allwinner/patches/linux/48-cpufreq-dt-auto-create-platdev.patch
projects/Allwinner/patches/linux/49-h3-add-mali-gpu-node.patch

This PR allows H3 SoC to achieve full performance since it can throttle based on SoC temperature. Till now it worked at fixed frequency which was set at 1 GHz instead of 1.296 GHz for safety reasons.
Unfortunately, I had to update some unrelated patches due to DT merge conflicts.

Allwinner: Enable thermal driver and  DVFS

---

projects/Odroid_C2/filesystem/usr/share/bootloader/canupdate.sh
projects/WeTek_Hub/filesystem/usr/share/bootloader/canupdate.sh
projects/WeTek_Play_2/filesystem/usr/share/bootloader/canupdate.sh

Adding a canupdate scripts so we can switch between aarch64 and arm on Odroid_C2, WeTek_Hub, WP2. This will be required once the decision is made to switch to 32bit userspace.

OC2,WH,WP2: Allow updates between aarch64 and arm

---

config/addon/xbmc.broken.xml
packages/addons/service/tvheadend/package.mk
scripts/install_addon

- adds the possibility to mark an addon as broken
it is required to fill in some reason
`PKG_ADDON_BROKEN="some description why it is broken"`
and change the `PKG_ADDON_TYPE` to
`PKG_ADDON_TYPE="xbmc.broken"`
tried to add this without disturbing the other addons (as the usage is a corner case)
- added Tvh 4.0 "stub" package that marks Tvh 4.0 as broken at our repo
- support for kodi binary addons is not included yet

add addon broken support to addon building

---

packages/addons/addon-depends/go/package.mk
tools/docker/Dockerfile
tools/docker/README.md

This PR adds a minimal ubuntu xenial docker container that can be used to build LibreELEC images, very useful together with Jenkins and CloudBees Docker Custom Build Environment Plugin.

 tools/docker: add build container 

---

scripts/image
scripts/mkimage

This PR renames the gpt partitions both named `primary` to `system` and `storage` (cosmetic change).
It also changes to use the pre-generated serial number for the system partition for all bootloaders (not just `syslinux`) and drops the unused `UUID_SYSTEM` variable.

scripts/mkimage: rename gpt partitions and use generated serial number

---

packages/mediacenter/kodi/scripts/service-addon-wrapper

change from https://www.libreelec.tv to https://libreelec.tv

kodi: correct URL in service addon wrapper header

---

packages/linux-drivers/RTL8188EU/package.mk

RTL8188EU: update to c5113ff
Add TP-Link TL-WN722N v2
Fix buffer overrun warning
See changes at [lwfinger repository](https://github.com/lwfinger/rtl8188eu/compare/18a5f33b60e25bee0b4eea05bc91ba48611505c5...c5113ffec0e7081b1facc1f809e4d03e5d60e9d4)

RTL8188EU: update to c5113ff

---

packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.upse/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.wsr/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.octonet/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk

We didn't bump Kodi binary add-ons for 8.0 branch for a while. This should be considered a final bump before the switch to 8.2.

kodi: binary add-on updates for 8.0

---

packages/addons/service/hyperion/patches/hyperion-0003-fix-protobuf-cmake.patch

On a clean build I can't seem to build hyperion for Odroid_C2 (I haven't tested others).
> 
> [ 72%] Building CXX object libsrc/protoserver/CMakeFiles/protoserver.dir/home/ray/tmp_LE/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/hyperion-1c21232/libsrc/protoserver/message.pb.cc.o
> armv8a-libreelec-linux-gnueabi-g++-7.2.0: error: /home/ray/tmp_LE/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/hyperion-1c21232/.armv8a-libreelec-linux-gnueabi/libsrc/protoserver/home/ray/tmp_LE/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/hyperion-1c21232/libsrc/protoserver/message.pb.cc: No such file or directory
> armv8a-libreelec-linux-gnueabi-g++-7.2.0: fatal error: no input files
> compilation terminated.
> make[2]: *** [libsrc/protoserver/CMakeFiles/protoserver.dir/build.make:279: …

hyperion: fix protobuf cmake patch

---

config/functions
distributions/LibreELEC/options
packages/devel/libcec/package.mk
packages/devel/libcec/patches/cec-framework/libcec-0001-PR380.patch
packages/sysutils/v4l-utils/package.mk

This PR adds optional support for cec framework to libcec using Pulse-Eight/libcec#380.
Also builds and installs `cec-ctl` when `CEC_FRAMEWORK_SUPPORT` is enabled.
Tested on Rockchip / ROCK64.

libcec: add cec framework support

---

config/functions

This PR adds a call to a `show_distro_config` function for showing distribution specific configuration when running `make image`.
Example of usage:
https://github.com/Kwiboo/LibreELEC.tv/blob/openpht-2.0-rockchip/distributions/OpenPHT/config/functions#L11-L28
```
...
OpenPHT configuration:
======================================================
- OpenPHT branch:                       openpht-2.0
- OpenPHT repository:                   git@github.com:Kwiboo/OpenPHTv2.git
- OpenPHT-Settings repository:          https://github.com/RasPlex/service.openelec.settings.git
- OpenPHT gitrev:                       5f956509fbb2d1fe1f81db9962022dc4ac391d74
- OpenPHT version:                      2.0.0.0-5f956509
Image configuration:
======================================================
- Image …
```

config/functions: call show_distro_config

---

scripts/unpack

This PR changes the unpack script to apply `*.patch` instead of `$PKG_NAME-*.patch` inside the package specific `patches` folder (same as all other patch locations).
Allows for OpenPHT to reuse kodi patches by using a symlink to `kodi`, see https://github.com/Kwiboo/LibreELEC.tv/commit/0d4455dc4f5d208b76715ffb30d9cdde0fc61bc5.
It also adds support for having device specific `PKG_PATCH_DIRS` patches, useful for a project that supports multiple `LINUX` versions (rockchip-4.4 and rockchip-4.14).

 scripts/unpack: apply more patches

---

config/arch.x86_64
config/functions
config/optimize
config/options
config/path
packages/virtual/virtual/package.mk
scripts/build
scripts/install
scripts/uninstall

Another small round of buildsystem optimisations, this time eliminating about 22 sub-process/forks per call to `config/options <packagename>` (which is executed at least 3 times per package).
Using the same test script from [#2072](https://github.com/LibreELEC/LibreELEC.tv/pull/2072#issuecomment-334957175), the following results were obtained (AMD FX-8350).
Before:
```
ELAPSED: 142 seconds, 557 packages x3 (LOOP #1)
ELAPSED: 144 seconds, 557 packages x3 (LOOP #2)
ELAPSED: 145 seconds, 557 packages x3 (LOOP #3)
ELAPSED: 146 seconds, 557 packages x3 (LOOP #4)
ELAPSED: 145 seconds, 557 packages x3 (LOOP #5)
```
After:
```
ELAPSED: 76 seconds, 557 packages x3 (LOOP #1)
ELAPSED: 78 seconds, 557 packages x3 (LOOP #2)
ELAPSED: 77 seconds, 557 packages x3 (LOOP #3)
ELAPSED: 78 seconds, 557 …
```

buildsystem: more optimisations

---

packages/mediacenter/kodi/config/appliance.xml
packages/mediacenter/kodi/config/guisettings.xml
packages/mediacenter/kodi/scripts/xml_merge.py
projects/imx6/kodi/guisettings.xml

This PR fixes merging of `appliance.xml` using the `xml_merge.py` script by including attributes when finding a matching element.
Also moves default `debug.screenshotpath` from `guisettings.xml` to `appliance.xml`, makes the value reset correctly when you select `Reset above settings to default`.
Finally removes inconsistent default `settinglevel` use by the imx6 project compared to all other projects.

kodi: fix appliance.xml merge and more

---

packages/multimedia/ffmpeg/patches/ffmpeg-99.1001-pfcd_hevc_optimisations.patch

Dirty fix to get rid of a linker error when building for aarch64:
`libavutil/libavutil.so: undefined reference to 'rpi_sand128b_stripe_to_8_10'`

ffmpeg: fix undefined reference to rpi_sand128b_stripe_to_8_10 error when building for aarch64

---

config/functions
packages/addons/addon-depends/libdvbcsa/package.mk
packages/audio/flac/package.mk
packages/audio/pulseaudio/package.mk
packages/emulation/libretro-dinothawr/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk
packages/mediacenter/kodi/package.mk
packages/multimedia/ffmpeg/package.mk
projects/Generic/options
projects/Odroid_C2/options
projects/RPi/options
projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play/options
projects/WeTek_Play_2/options
projects/imx6/options

This implements a generic, reliable and extensible solution when testing for specific hardware features.
`arm` (but not `RPi`/`Slice`) and `aarch64` all now have `neon` support.
`Generic` has `mmx`, `sse2` and `sse3`.
I've added `32bit` and `64bit` as a "feature" in case this ever needs to be determined.
In future we could add endian (little/big) if this is ever needed.

buildsystem: add TARGET_FEATURES

---

packages/linux-firmware/brcmfmac_sdio-firmware-imx/package.mk

brcm_patchram_plus needs to be installed in the normal place

brcmfmac_sdio-firmware-imx: fix install path

---

tools/distro-tool

Some packages, such as [game.libretro.pcsx-rearmed](https://github.com/LibreELEC/LibreELEC.tv/blob/c863ecc017a06f314af5d21c95059f45d91b1d28/packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk#L38), may output text when the package is sourced which corrupts the json data structure being generated by `distro-tool`. Ignore all such text.

distro-tool: ignore package output

---

packages/addons/addon-depends/ffmpegx/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.upse/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.wsr/package.mk
packages/network/samba/scripts/smbd-config

These add-ons have not been correctly forked with a Krypton branch so the update script finds HEAD which pulls in updates for Leia that break compile. I doubt there will be many updates for these going forwards, but we need to be careful - vis.shadertoy also fails for the same reason.

misc: cleanup items for 8.2.0

---

tools/docker/Dockerfile

This PR adds python to the docker container to fix building of images with the recent `meson` change, see #2153 for details

tools/docker: add python

---

scripts/checkdeps

With the `meson` change we now have a dependency on `python` before any packages (including our own `Python2`) are built: https://github.com/LibreELEC/LibreELEC.tv/blob/2a530ac2ce455d19351fa5bfb03b0cce8f521208/config/functions#L60
Consequently on a system without `python` (eg. an Ubuntu Xenial Docker), the build will fail with an error.
```
config/functions: line 60: python: command not found
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 127
```
Adding `python` to `scripts/checkdeps` will avoid this issue.

scripts/checkdeps: add python

---

config/version

The plan is to release a simple 8.2.0.1 respin for RPi and Slice images once a fix for the HEVC issue has been figured out.

config: bump version to 8.2.0.1 for RPi HEVC respin

---

packages/debug/libva-utils/package.mk
packages/graphics/libdrm/package.mk
packages/graphics/mesa/package.mk
packages/multimedia/intel-vaapi-driver/package.mk
packages/multimedia/libva/package.mk
packages/web/curl/package.mk
packages/x11/data/xkeyboard-config/package.mk
packages/x11/driver/xf86-input-libinput/package.mk
packages/x11/lib/libXfont2/package.mk
packages/x11/lib/libpciaccess/package.mk
packages/x11/other/fontconfig/package.mk

Release notes:
| Package | Version | Announce |
| ---- | ---- | ---- |
| intel-vaapi-driver | 2.0.0 | [2.0.0](https://github.com/01org/intel-vaapi-driver/releases/tag/2.0.0) |
| libva | 2.0.0 | [2.0.0](https://github.com/01org/libva/releases/tag/2.0.0) |
| libva-utils | 2.0.0 | [2.0.0](https://github.com/01org/libva-utils/releases/tag/2.0.0) |
| mesa | 17.2.3 | [17.2.3](https://www.mesa3d.org/relnotes/17.2.3.html) |
| libdrm | 2.4.85 | [2.4.84](https://lists.x.org/archives/xorg-announce/2017-October/002815.html), [2.4.83](https://lists.x.org/archives/xorg-announce/2017-August/002804.html) |
| libXfont2 | 2.0.2 | [2.0.2](https://lists.x.org/archives/xorg-announce/2017-October/002813.html) |
| libpciaccess | 0.14 | [0.14](https://lists.x.org/archives/xorg-announce/2017-October/002817.html) …

Package Updates: Various x86-related packages

---

config/graphic

Misc small fixes through config/graphics. Inspired by, yet to be posted Mesa VAAPI support ;-)

Misc config graphcs fixes

---

packages/addons/addon-depends/nss/package.mk
packages/addons/addon-depends/nss/patches/nss-04-skip_shlibsign.patch
packages/addons/addon-depends/nss/patches/nss-05-disable_host_cflags.patch
packages/addons/browser/chromium/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/virtual/network/package.mk

This builds nss and nspr as part of the main image, for x86. The packages are based on the existing add versions (which are now removed), but bumped to latest versions (thanks @InuSasha).
The libraries created by `nss` and `nspr` are required by `chromium` and `inputstream.adaptive` addons (in the case of the latter, they're required by `libwidevinecdm.so`).
This PR adds `nss` as a dependency of kodi, when building for x86_64. It also builds `nss` using the system Sqlite3 library which avoids `nss` installing a version of `libsqlite3.so` that can't be linked by kodi (and thus causing Kodi to fail).
The additional libraries add about 4MB to the final SYSTEM size.
There may be better ways of doing this, perhaps a dedicated `nss`/`nspr` addon, if anyone wants to have a go at that.

nss/nspr: include in main image [rfc]

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk

This just moves us to a repo rather than a manually maintained tarball. Firmware files are unchanged.

brcmfmac_sdio-firmware-rpi: update to brcmfmac_sdio-firmware-rpi-13edcc7

---

packages/linux-firmware/brcmfmac_sdio-firmware-aml/package.mk
packages/linux-firmware/brcmfmac_sdio-firmware-aml/patches/brcmfmac_sdio-firmware-aml-0001-install-firmware-to-FWDIR.patch

brcm_patchram_plus was installed under /usr/lib/kernel-overlays/base/usr/bin which breaks BT on WP2.

brcmfmac_sdio-firmware-aml: Fix install of binaries

---

packages/network/samba/patches/samba-953-backport-misleading-file-exists-fix.patch

[LE8.2] samba: fix misleading "file exists" message on login error

---

packages/network/samba/patches/samba-953-backport-misleading-file-exists-fix.patch

[LE9] samba: fix misleading "file exists" message on login error

---

packages/lang/llvm/package.mk

Unfortunately we have to add this in order to fix the output of llvm-config to properly report a shared library.
This problem came apparent when I updated mesa.

llvm: fix output of llvm-config

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch

This should be the last 4.13.y bump before the switch to 4.14.0.
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.12

 linux: update to linux-4.13.12 

---

packages/sysutils/systemd/udev.d/60-not-joysticks.rules

Fix for usb airmouse remote+, not all buttons work without this
https://forum.libreelec.tv/thread/2722-8-0-2c-libreelec-8-0-builds-for-ki-plus-kii-pro-ki-pro/?postID=69043#post69043

systemd: remote+ is not a joystick

---

packages/mediacenter/kodi/profile.d/00-addons.conf

When running linuxserver.io docker addons in Kodi 18 you can change the settings in Kodi but the script is ignoring it because that awk/sed hack is failing on with settings version 2.
Uses xmlstarlet. I copied it from @vpeter4 https://github.com/LibreELEC/LibreELEC.tv/pull/2147
Tested on Odroid C2 LE9.

Fix parsing settings.xml in oe_setup_addon

---

packages/graphics/giflib/patches/giflib-01-fix-reallocarray-exception.patch

See https://github.com/xbmc/xbmc/pull/13015 for details.

giflib: don't export reallocarray function

---

packages/tools/dtc/patches/dtc-0002-fix-format-errors.patch

Already fixed upstream, can be dropped at next bump.

dtc: fix format conversion errors

---

packages/addons/service/slice/package.mk
scripts/create_addon

With the old code, any addon that is for RPi2 but not RPi, would not build as the PROJECT=RPi, eg. [audiodecoder.usf](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk#L35) which has:
```
PKG_ADDON_PROJECTS="Generic Nvidia_Legacy RPi2 imx6 WeTek_Play"
```
and scripts/create_addon would then claim that RPi2 is not supported.
Similarly, [service/slice](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/slice/package.mk#L34) has:
```
PKG_ADDON_PROJECTS="RPi"
```
which will work with the old code, building for all RPi-based devices, but I don't know if this is intended. Consequently I've updated this package with the correct device codes, which will now mean it won't build for RPi and RPi2.

scripts/create_addon: simplify PROJECT selection, support DEVICE

---

packages/multimedia/ffmpeg/package.mk
packages/multimedia/rkmpp/package.mk
packages/multimedia/rkmpp/patches/rkmpp-0001-osal-add-rk3036-platform.patch
packages/multimedia/rkmpp/patches/rkmpp-0002-mpp-retrieve-available-input-packet-free-slots.patch
packages/multimedia/rkmpp/patches/rkmpp-0003-fix-32-bit-mmap-issue-on-64-bit-kernels.patch
projects/Rockchip/patches/kodi/kodi-PR13044.patch

This PR enables hw video decoding support by adding xbmc/xbmc#13044 as a patch (can be dropped when master have updated to latest kodi).
This may have some minor issues on rk3288 that will be addressed when atomic drm support is added to kodi and the drm prime renderer.

Rockchip: enable hw video decoding

---

packages/addons/addon-depends/dvb-tools-depends/dvb-fe-tool/package.mk

reopened pr from https://github.com/LibreELEC/LibreELEC.tv/pull/2152
> When using repo-tool, build fails due to missing reference to pthread

dvb-fe-tool: fixed compile error issue

---

packages/devel/heimdal/package.mk

Building OTP is broken on ArchLinux and it seems it is not needed
anyway.
@MilhouseVH is it safe to disable OTP?

heimdal: Disable OTP

---

scripts/mkimage

not sure why this wasn't ever converted before.

scripts/mkimage: use uuid for partitions on RPi

---

projects/RPi/devices/Slice/patches/linux/linux-999.99-slice-mmc-aliases.patch
projects/RPi/devices/Slice3/patches/linux/linux-999.99-slice-mmc-aliases.patch

This ensures the emmc storage on the CM3 uses /dev/mmcblk0 else it becomes /dev/mmcblk1 in recent kernels which causes boot failure after updating to LE9.0 due to cmdline.txt containing hard references to /dev/mmcblk0. I'm still asking questions to Pi kernel people to see if there's a way to change the aliases through the Slice dts file so we can avoid the patch, but for now, this works.

slice: patch bcm2708-rpi.dtsi so emmc uses /dev/mmcblk0

---

packages/sysutils/util-linux/patches/util-linux-blkid_swapon_mkfs_uuidgen.patch

While building `util-linux` I noticed the following error is being silently ignored:
```
checking for ncursesw5-config... no
checking for ncursesw... no
checking for initscr in -lncursesw... no
/home/neil/projects/scratch/alternates/xLibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/util-linux-2.31/configure: line 23338: build_uuidgen]=yes: command not found
checking for unshare... yes
checking for setns... yes
```
The typo in the patch results in the following being written to `configure`, which is obviously garbage:
```
23335   if test "x$enable_uuidgen]" = xno; then
23336    build_uuidgen]=no
23337 else
23338    build_uuidgen]=yes
23339 fi
```
@CvH can you update #2186 with this fix. Unfortunately it's not the cause of our 8.2/17.10 woes. :(

util-linux: fix typo in blkid patch

---

packages/devel/glibc/package.mk

I noticed the following error in the build logs:
```
/home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/glibc-2.26/configure: line 5542: -V:apiversion: command not found
```
The relevant code in `configure` is:
```
5541 if test "$PERL" != no &&
5542    (eval `$PERL -V:apiversion`; test `expr "$apiversion" \< 5` -ne 0); then
5543   PERL=no
5544 fi
```
The value of `$PERL` is being set from:
https://github.com/LibreELEC/LibreELEC.tv/blob/298a1c251059c24c8a4732312b896e5f17841f4c/packages/devel/glibc/package.mk#L34
which results in `$PERL` being initially blank, which is != `no`, and consequently `configure` tries to execute `-V:apiversion` as a command, before setting `PERL=no`.
@CvH: needed by libreelec-8.2 too.

glibc: fix perl

---

packages/sysutils/util-linux/package.mk

On our main build server I see failures with util-linux 2.31 related to it finding some ncurses libs and maybe not respecting the `--without-ncurses` switch. Looking at the commits between 2.30 which works fine and 2.31 which does not; reverting [https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/commit/?id=87c26ce5b689abe1b52181f98ef3c9eb1b1a5165](url) "fixes" the issue, e.g. with the patch:
```
checking for armv7ve-libreelec-linux-gnueabi-ncursesw6-config... no
checking for ncursesw6-config... no
checking for armv7ve-libreelec-linux-gnueabi-ncursesw5-config... no
checking for ncursesw5-config... ncursesw5-config
checking ncursesw/ncurses.h usability... no
checking ncursesw/ncurses.h presence... no
checking for ncursesw/ncurses.h... no
checking ncursesw/term.h usability... no …
```

util-linux: add --without-ncursesw to config

---

packages/virtual/virtual/package.mk

When `vmware` is not enabled, the build system will bail out because the package finishes with exit code == 1, which is interpreted by `set -e` in `config/path` as an error condition.
Ping @LongChair

virtual: avoid exiting with failure code

---

packages/network/samba/package.mk

Changelog: https://www.samba.org/samba/history/samba-4.7.3.html
This is a security release, fixing:
*  CVE-2017-14746:
All versions of Samba from 4.0.0 onwards are vulnerable to a use after
free vulnerability, where a malicious SMB1 request can be used to
control the contents of heap memory via a deallocated heap pointer. It
is possible this may be used to compromise the SMB server.
*  CVE-2017-15275:
All versions of Samba from 3.6.0 onwards are vulnerable to a heap
memory information leak, where server allocated heap memory may be
returned to the client without being cleared.

samba: update to samba-4.7.3

---

packages/devel/libcec/package.mk

disable git depends to fix Jenkins
before
```
-- git found: fatal: No tags can describe 'b1073d3db040416a7a099b16174cff1a4e77061a'.
Try --always, or create some tags.
...
-- lib info: git revision: fatal: No tags can describe 'b1073d3db040416a7a099b16174cff1a4e77061a'.
Try --always, or create some tags., compiled on Wed Nov 22 by jenkins@buildbox on Linux 4.4.0-81-generic (x86_64)
```
after
```
-- lib info:  compiled on Wed Nov 22 by jenkins@buildbox on Linux 4.4.0-81-generic (x86_64)
```

libcec: disable git depends

---

packages/linux/package.mk

Update amlogic-3.10 kernel to to amlogic-3.10-f016bb1.
The update includes a fix for building systemd-235 for WeTek Play and WeTek Core projects.

[LE 9.0] linux: Update amlogic-3.10 kernel to amlogic-3.10-f016bb1

---

config/options

This prevents anyone building as `root`, which runs the risk of trashing a system given that a cross-compiling build system wants to overwrite the host files at every opportunity (and will, if being run as `root`).

config/options: check if the effective uid is root (and bail if so)

---

packages/addons/addon-depends/system-tools-depends/diffutils/patches/diffutils-002-explicitly-disable-replacing-getopt.patch

fix building of diffutils
> xstrtol-error.c:84:26: error: invalid use of undefined type 'struct rpl_option'
that `scripts/create_addon system-tools` works
@mglae fyi

diffutils: fix compiling

---

scripts/get

This addresses an issue with package downloads when building different versions of LibreELEC from a single repository, or using a shared `sources` folder maintained outside of the LibreELEC repository (in order to save space and/or due to limited internet bandwidth).
This mainly affects packages downloaded from `$DISTRO_SRC` as this will evaluate to a different url for `devel` than it will for `8.2.1` or `9.0` etc., even though the downloaded packages may be identical. However it can also affect packages that have been updated to use an alternative `PKG_URL` in master (but not a different version) which hasn't been backported to an older branch - although the packages may be identical they will be repeatedly downloaded each time the "other" branch is built due to the different url. This …

scripts/get: avoid flip-flopping downloads

---

packages/sysutils/v4l-utils/patches/v4l-utils-02-irctl-fix-multiple-scancodes.patch
packages/sysutils/v4l-utils/patches/v4l-utils-03-irctl-fix-rc6-on-32bit.patch

- fix sending multiple scancodes with configurable gap
- fix sending rc6 scancodes on 32bit platforms
Patches are backported from v4l-utils master branch
Signed-off-by: Matthias Reichl <hias@horus.com>

v4l-utils: fix sending scancodes with ir-ctl

---

packages/sysutils/v4l-utils/patches/v4l-utils-02-irctl-fix-multiple-scancodes.patch
packages/sysutils/v4l-utils/patches/v4l-utils-03-irctl-fix-rc6-on-32bit.patch

- fix sending multiple scancodes with configurable gap
- fix sending rc6 scancodes on 32bit platforms
Patches are backported from v4l-utils master branch
Signed-off-by: Matthias Reichl <hias@horus.com>

[8.2] v4l-utils: fix sending scancodes with ir-ctl

---

packages/sysutils/busybox/scripts/init

After https://github.com/mirror/busybox/commit/607f2b404e992174d7c5956d11e8f35f78d2701f in busybox 1.26.0 the output of `fdisk -u -l` for MBR-based partitions is changed with 2 extra columns causing the OFFSET calculation to be incorrect, resulting in partitions that fail to mount (`Invalid argument`, see https://github.com/Raybuntu/LibreELEC.tv/issues/39).
Before (MBR partitions):
```
Disk /dev/loop0: 575 MB, 575668224 bytes
4 heads, 32 sectors/track, 8784 cylinders, total 1124352 sectors
Units = sectors of 1 * 512 = 512 bytes
Device Boot      Start         End      Blocks  Id System
/dev/loop0p1   *        8192     1056767      524288   c Win95 FAT32 (LBA)
/dev/loop0p2         1056768     1122303       32768  83 Linux
```
After: (MBR partitions)
```
Disk /dev/loop0: 549 MB, 575668224 …
```

init: fix offset calculation after busybox fdisk change

---

packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
packages/addons/tools/multimedia-tools/changelog.txt
packages/addons/tools/multimedia-tools/package.mk

Link libraries to squeezelite instead of using dlopen() to support static build ones.
See [https://forum.libreelec.tv/thread/5887-multimedia-tools-squeezelite-missing-libraries/](https://forum.libreelec.tv/thread/5887-multimedia-tools-squeezelite-missing-libraries)

multimedia-tools: squeezelite: support all possible media formats

---

packages/addons/service/librespot/changelog.txt
packages/addons/service/librespot/package.mk
packages/addons/service/librespot/source/bin/librespot.start
packages/addons/service/librespot/source/default.py

This addresses issues reported by users in the forum:
- unable to disable addon from Kodi
- unable to complete backup

librespot: fix default.py, move fifo to /var/run/librespot

---

packages/linux-firmware/kernel-firmware/package.mk

It turns out the Intel Bluetooth 9260/9560/8260/8265 firmwares in the last bump [are corrupt](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=e4252cf670f33410a35d1bf604ac5f35dc211c4d) and missing the binary firmware files.
The original commits have been reverted and binary files re-applied.
This bump also adds support for the the CYW4373 SDIO and USB firmware files (brcmfmac4373-sdio.bin and brcmfmac4373.bin).

kernel-firmware: update to kernel-firmware-7f93c9d

---

packages/network/connman/patches/connman-06-ntp-startup.patch

This patch was sent to the connman mailing list after a conversation Lukas and I had with Daniel Wagner at ELC Europe about persistent issues with initial NTP sync on pi hardware where slow-loading USB wireless drivers can cause the first sync attempt to fail and then it's a 7200 second wait before connman makes the next attempt.
Upstream merge is pending on feedback that this approach solves or improves the situation. This PR can either be merged to enable broader testing as we move towards LE 9.0 alpha releases, or left open as a team reminder that we need to find candidate users with the problem, and get them test images so we can provide feedback.

connman: add NTP startup patch for wider testing

---

config/functions
packages/sysutils/busybox/package.mk
packages/sysutils/systemd/package.mk
packages/sysutils/systemd/scripts/usercache-setup
packages/sysutils/systemd/scripts/userconfig-setup
packages/sysutils/systemd/system.d/usercache.service

1) Now that `/etc/shadow` is a symbolic link to `/storage/.config/shadow` the correct file to `chmod 000` in the image is `/usr/config/shadow`. This also avoids the following warning when running `fakeroot`:
```
chmod: cannot operate on dangling symlink '/home/neil/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/image/system/etc/shadow'
```
2) Ensure that `/storage/.config/shadow` always has the correct `000` file permission.

/etc/shadow: fix file permissions

---

packages/sysutils/busybox/patches/busybox-06-prevent-root-weak-passwd.patch

Busybox allows root to have a null password but our default (and correct) ssh config does not allow null passwords. This means users can set a null password and lock themselves out of the console requiring /storage/.cache/shadow to be deleted (via Kodi file manager) and the box rebooted to regain access. In poking this we discovered busybox 'weak password' checking is not applied to the root user; a warning is shown but it can be ignored. This patch removes the exemption so root (our only user) is treated the same as a normal non-root user.
Original source: http://lists.infradead.org/pipermail/lede-dev/2017-February/006032.html

busybox: prevent weak root passwords

---

packages/devel/heimdal/package.mk
packages/security/openssl/package.mk

openssl 1.0.2n: https://www.openssl.org/news/secadv/20171207.txt
heimdal 7.5.0: https://github.com/heimdal/heimdal/issues/353 ([CVE-2017-17439](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17439))

openssl/heimdal: Security fixes

---

packages/network/nss-mdns/package.mk

Avahi isn't loading libnss_mdns_minimal.so.
Also, nss-mdns is using `/var/run/avahi-daemon/socket` as the path for the Avahi socket - it should be `/run/avahi-daemon/socket`. In the end I had to resort to a patch, as setting build variables got me nowhere.

nss-mdns: install all libraries, correct avahi socket path

---

packages/sysutils/busybox/tmpfiles.d/z_01_busybox.conf
packages/sysutils/tz/system.d/tz-data.service

See #2303 for background.
`tz-data` is creating `/var/run` before `systemd-tmpfiles-setup` is executed, which prevents the symbolic link `/var/run` (to `../run`, in the file `var.conf` from `systemd`) from being created. Chaos ensues, breaking `avahi`/`nss-mdns` communication, and possibly others.
The `busybox` config creates `/var/lock` which is already created by `legacy.conf` (from the `systemd` package), and consequently a warning message is being logged. Drop the second `/var/lock`, lose the warning message.

systemd: fix systemd-tmpfiles-setup

---

scripts/mkimage

This patch adds `LIBREELEC_DISK` label to user data partition. This is required to allow Amlogic devices boot from USB drives. Possibly useful for other devices as well.

scripts/mkimage: add label to disk partition as well

---

packages/tools/u-boot/package.mk
packages/tools/u-boot/sources/configs/dummy_x86_defconfig

This is for kszaq's PR #2261 as mkimage is missing from the toolchain directory
A suitable location for invoking the install of the package will need to be decided

u-boot: added option to compile mkimage for host

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/libnetwork/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/package.mk
packages/addons/service/syncthing/package.mk

This PR will change to set `GOARM=7` on all arm builds except for the only armv6 cpu known to LE build system
Also removes the current mix of `cortex-a7` and `cortex-a7|cortex-a9` check for setting `GOARM=7`
https://github.com/golang/go/wiki/GoArm recommends to always set an appropriate `GOARM` when cross compiling

addons: use GOARM=7 for more arm cpus

---

config/options

This PR changes `LINUX_DEPENDS` to include entire `$PROJECT/linux` and `$PROJECT/devices/$DEVICE/linux` path instead of just `linux/linux.${TARGET_PATCH_ARCH:-$TARGET_ARCH}.conf`, linux package supports lots of different config file paths, see https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux/package.mk#L75-L94
This is originating from `rockchip` branch where linux configs is located in a subfolder at `projects/Rockchip/linux/rockchip-4.4/linux.*.conf`
A small negative side effect of this change is that changing any file in the config file path will trigger linux and modules rebuild.

linux: rebuild when config or patches changes

---

packages/sysutils/tz/system.d/tz-data.service

Just in case, this is a partial backport of #2308: only the `/var/run` change is needed, as the `/var/lock` issue doesn't affect libreelec-8.2.

tz-data: adjust dependency so that it doesn't create /var/run [backport]

---

packages/multimedia/libamcodec/package.mk

This PR bumps libamcodec to its latest revision, there is only 1 minor change to a Makefile since the last revision.

libamcodec: update to latest revision

---

packages/linux/package.mk
packages/tools/aml-dtbtools/package.mk
projects/WeTek_Core/options
projects/WeTek_Hub/options
projects/WeTek_Play_2/options

This is useful if a few devices need to be supported by one project. 
If there is only one device tree created from `KERNEL_UBOOT_EXTRA_TARGET` it is appended as-is, e.g. without multidtb tool header.

Add a possibility to create multi-image device tree blobs for Amlogic

---

packages/sysutils/systemd/scripts/usercache-setup

If the `/storage/.cache/shadow` file contains garbage (ie. is missing the entry for `root`), then it will not be overwritten with default details.
Now it will.

shadow: detect corrupt content

---

packages/devel/libcec/patches/libcec-002-PR390.patch

This patch fixes the 2012 (and apparently newer) LG tv's changing input to libreelec whenever the TV is switched on.
see https://github.com/Pulse-Eight/libcec/pull/390 for more info

Libcec: Fix LG tv always changing input

---

packages/mediacenter/LibreELEC-settings/package.mk
packages/mediacenter/kodi/package.mk
packages/mediacenter/kodi/scripts/kodi-config
packages/mediacenter/kodi/scripts/kodi-safe-mode
packages/mediacenter/kodi/scripts/kodi.sh
packages/mediacenter/kodi/system.d/kodi.service
packages/network/samba/scripts/smbd-config

As nobody wanted to discuss this on Slack...
With the move to automatic updates enabled by default, I have a sneaking suspicion this may lead to an increase in the number of systems that enter a Kodi crash loop due to duff addons after the upgrade, particularly after a major upgrade.
To mitigate this, I present to you... safe mode.
By default after 5 crashes within 15 minutes (both configurable in `options`: `KODI_MAX_RESTARTS` and `KODI_MAX_SECONDS`) "safe mode" will restart LibreELEC with a temporary _clean_ `.kodi` folder.
The original (and crash-causing) `.kodi` folder will be renamed `.kodi.FAILED`. In the `Logfiles` Samba folder an extra archive with `-FAILED` suffix will be created with the logs from the failed Kodi folder.
"Safe mode" (identifiable as it uses the red background …

kodi: safe mode [RFC]

---

packages/x11/driver/xf86-video-amdgpu/package.mk

... for devices managed by the amdgpu kernel driver
Without the configuration the X radeon or modesettings driver may be loaded resulting in errors up to freezing system.

xf86-video-amdgpu: instruct xorg to load the amdgpu driver

---

scripts/mkimage

Fix an issue when device tree image is not included into SD card images for WeTek devices.
The issue was introduced by 5da14cfce52adb1113977d8945b2923c91c8b8f1.

[LE 9.0] mkimage: Fix an issue when device tree image is not included into SD card images for WeTek devices

---

packages/network/samba/package.mk

Add `--without-libarchive` otherwise `samba` auto detects `archive.h` (added by `libarchive` when building `vfs.archive`) and, when rebuilding `samba`, it then builds `libarchive` support which pulls in `openssl` and `bzip2` dependencies, which fail during linking as the libraries are not found (missing `-lcrypto -lbz2`). 
A clean build of `samba` succeeds because `archive.h` doesn't exist at the time `samba` is first built, but a rebuild will fail after `libarchive` is built.
With this PR, `samba` will rebuild without failing.

samba: fix link issues when rebuilding

---

packages/addons/browser/chromium/changelog.txt
packages/addons/browser/chromium/package.mk

CVE-2017-15429
builds fine,
no runtime tests, yet.

chromium: security fix to 63.0.3239.108

---

packages/multimedia/ffmpeg/patches/ffmpeg-99.1003-pfcd_hevc_optimisations.patch

This amends commit b27b2a9 with omitted MVC parser code for ffmpeg-99.1003-pfcd_hevc_optimisations.patch

Fixes: Libreelec 8.2.0.1 Rpi3 3D iso not playing properly

---

packages/graphics/bcm2835-driver/package.mk

This adds the creation of the versioned links to the RPi Graphics driver similar to what mesa does.
Actually some Qt plugins seems to dynamically load some libraries and they refer to the versioned links which are also standard.

bcm2835-driver : make versionned symlinks for EGL / GLES

---

packages/multimedia/rkmpp/package.mk
packages/multimedia/rkmpp/patches/rkmpp-0001-mpp-retrieve-available-input-packet-free-slots.patch
packages/multimedia/rkmpp/patches/rkmpp-0002-fix-32-bit-mmap-issue-on-64-bit-kernels.patch
projects/Rockchip/README.md
projects/Rockchip/bootloader/install
projects/Rockchip/packages/u-boot/package.mk

This PR updates `u-boot` to latest vendor version fixing a boot issue with rk3328 in my last PR.
The u-boot install-script also adds support for more SoCs using a default `PKG_DATAFILE` and `PKG_LOADER`.
`rkmpp` was also updated to latest version, it contains some changes/fixes to the h264 decoder.
Finally a short notice about what type of devices is more likely to work was added to the Rockchip project `README.md`.

Rockchip: u-boot and rkmpp update

---

packages/sysutils/systemd/package.mk
packages/sysutils/systemd/patches/systemd-0100-backport-systemd-analyze-plot-fix.patch

Since systemd 235 systemd-analyze plot stopped working, it needs systemd-hostnamed and an upstream patch (which can be dropped on 237 systemd bump).
Running systemd-analyze plot on systemd 235 and 236 gives the following error:
```
Failed to get host information from systemd: Unknown object '/org/freedesktop/hostname1'.
```
Enabling systemd-hostnamed is not enough, it still results in the same error - see https://github.com/systemd/systemd/issues/7667
With systemd-hostnamed enabled plus upstream commit https://github.com/systemd/systemd/commit/bf0e0a4df2d41a5631811f7db6b6c1c866c3ed80 systemd-analyze plot works fine.
Using the commit without enabling hostnamed doesn't work, then we get this error
```
Failed to get host information from systemd: The name org.freedesktop.hostname1 was not …
```

systemd: enable hostnamed and add patch to fix systemd-analyze plot

---

tools/distro-tool

Just a small tweak that includes the `projects/$PROJECT` folder when generating the list of packages to process, otherwise packages that exist only in the project folder (and have no global equivalent) would never be processed. Example:
```
projects/Odroid_C2/gcc-linaro-arm-eabi
projects/Odroid_C2/packages/gcc-linaro-aarch64-elf`
```
----
We should probably cron a `distro-tool` run at least once a week. Running it against different branches (eg. `libreelec-8.2`) is also possible - just switch branch on the source LibreELEC.tv repository before running the script.
In order to process all project packages, and also any global packages with project-specific logic (ie. `PKG_URL`/`PKG_VERSION` selection, as in `packages/linux`), it will require running for all project/arch that we support. …

distro-tool: add project package support

---

scripts/build

fixed meson build system usage while cross compiling
on behave of @Kwiboo 
@lrusak pls have a look, fixed it for me
Without meson is not able to cross compile packages for different archs and creates errors like
```
File "/builddir/toolchain/lib/python3.6/site-packages/meson-0.42.1-py3.6.egg/mesonbuild/mesonmain.py", line 353, in run
app.generate()
File "/builddir/toolchain/lib/python3.6/site-packages/meson-0.42.1-py3.6.egg/mesonbuild/mesonmain.py", line 148, in generate
self._generate(env)
File "/builddir/toolchain/lib/python3.6/site-packages/meson-0.42.1-py3.6.egg/mesonbuild/mesonmain.py", line 188, in _generate
intr = interpreter.Interpreter(b, g)
File "/builddir/toolchain/lib/python3.6/site-packages/meson-0.42.1-py3.6.egg/mesonbuild/interpreter.py", …
```

scripts/build: fix meson cross-compiling

---

packages/tools/u-boot/package.mk

This PR adds support for installing a `canupdate.sh` script, rebuilds package if `bootloader` content changes and adds support for project specific u-boot version and depends.
See https://github.com/Kwiboo/LibreELEC.tv/commit/becdb06540774441d41c5a275e5869f27c8b9212 for an example of how project specific version can be used instead of the project specific u-boot package on Rockchip.
(Rockchip is still not fully ready to use mainline u-boot+spl on rk3328/rk3399 in u-boot 2018.01)
This should not change anything for current projects beside using `http` instead of `ftp` to get the default u-boot version.

u-boot: add support for project specific version and more

---

packages/addons/addon-depends/libmpdclient/package.mk
packages/addons/service/mpd/changelog.txt
packages/addons/service/mpd/package.mk

this reworks and updates mpd
- due the mpd build system a lot options are "auto" and the actually addon build was **heavily** differing between clean build and "normal" build -> changed to static values to allow reproduce able builds
- activated every feature we have already at the toolchain
- update to 0.20.13

mpd: update to 0.20.13

---

packages/sysutils/systemd/patches/systemd-0101-backport-sysctl-use-raw-file_descriptor-in-sysctl_write.patch

Backport a patch to fix a failure in systemd-sysctl during a startup of systemd-236.
On WeTek Hub and WeTek Play 2 systemd-sysctl fails to start with the following errors:
```
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't write '1' to 'fs/protected_hardlinks': Input/output error
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't write '1' to 'fs/protected_symlinks': Input/output error
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't write '0' to 'dev/cdrom/lock': Input/output error
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't write '0' to 'dev/cdrom/autoclose': Input/output error
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't write '16384' to 'vm/min_free_kbytes': Input/output error
Jan 01 02:00:22 LibreELEC systemd-sysctl[2665]: Couldn't …
```

systemd: Fix a failure in systemd-sysctl during a startup of systemd-236

---

packages/sysutils/busybox/scripts/pastebinit

The author of sprunge.us [recommends](https://github.com/rupa/sprunge/issues/35#issuecomment-169486002) moving to ix.io.
The sprunge.us developer appears to have no interest in resolving the ongoing availability issues, and is not showing any interest in addressing the bugs in the code which mean [only 50% of the id space](https://github.com/rupa/sprunge/issues/29) will ever be used, and sprunge.us will become slower as the [id space is filled](https://github.com/rupa/sprunge/issues/38) eventually spinning forever (note that due to the reduced id space it's actually 36^4 not 62^4).
Switching to ix.io may not be a long term solution, but using something other than sprunge.us is necessary at least in the short term until we decide on a more suitable long term replacement.
This may be too …

pastebinit: switch to ix.io

---

packages/network/iptables/config/README
packages/network/iptables/config/home.v4
packages/network/iptables/config/home.v6
packages/network/iptables/config/public.v4
packages/network/iptables/config/public.v6
packages/network/iptables/package.mk
packages/network/iptables/scripts/iptables_helper
packages/network/iptables/system.d/iptables.service

Default: Only allow private subnets
Don't overwrite rules from docker or connman wifi tether
An example how to turn on/off through LE Settings addon is available here: 
https://github.com/Raybuntu/service.libreelec.settings/commit/d3e19e7a902ecda4f6060a4abb3f016337461640
I can PR that too if we decide to this get's accepted. Filters are disabled by default and need to be enabled through LE settings addon.
Docker is restarted when the rules are reloaded or flushed otherwise it would break network connectivity in docker. Same for wifi tethering.
I have been using these rules in my community builds for a few months (enabled by default) without hearing any complaints about broken networks. I've just reworked the scripts a little bit the last few days so it will require some testing before it …

[RFC] iptables: Add default net filters

---

packages/devel/boost/package.mk

This fixes building boost for me on fedora. The problem is that boost picks up the system `/usr/include/python` path.
This was introduced in https://github.com/LibreELEC/LibreELEC.tv/commit/195aef26928306978beee19ce4c2710a1a981f69

boost: fix python config

---

packages/linux-firmware/intel-ucode/package.mk

Latest microcode firmware update from the peddler of insecure microprocessors.
From the release notes it's mostly fixes for new processors:
```
Intel Processor Microcode Package for Linux
20171117 Release
-- New Platforms --
CFL U0 (06-9e-0a:22) 70
CFL B0 (06-9e-0b:2) 72
SKX H0 (06-55-04:b7) 2000035
GLK B0 (06-7a-01:1) 1e
APL Bx (06-5c-09:3) 2c
-- Updates --
KBL Y0 (06-8e-0a:c0) 66->70
-- Removed files --
SKX H0 (06-55-04:97) 2000022
```
No specific bug fixes are mentioned in the changelog, so one can only guess...
https://downloadcenter.intel.com/download/27337/Linux-Processor-Microcode-Data-File

intel-ucode: update to intel-ucode-20171117

---

packages/linux-firmware/amlogic/brcmfmac_sdio-firmware-all-aml/package.mk

This PR bumps brcmfmac_sdio-firmware-all-aml to the latest revision

brcmfmac_sdio-firmware-all-aml: update to latest revision

---

packages/linux-drivers/amlogic/ssv6xxx-aml/patches/ssv6xxx-aml-001-fix-build-and-firmware-path.patch

This PR fixes the firmware paths for people with ssv6* WiFi chips

ssv6xxx-aml: fix firmware paths

---

packages/sysutils/busybox/patches/busybox-01-umount-ignore-c.patch

This fixes the shutdown bug for unmounting `/tmp` at shutdown
a bug report was filled upstream https://github.com/systemd/systemd/issues/7786
I'd like to wait to hear back to see what to do.

busybox: add upstream patch to fix umount from systemd

---

config/show_config
distributions/LibreELEC/options
packages/virtual/misc-packages/package.mk
projects/Amlogic/devices/S905/options
scripts/image

As the title says, we have a couple of packages in projects/Amlogic (only 1 listed at present) that are required to be built.
As can be seen this has been added to the end of packages/virtual/debug/package.mk as this is the very last point in the build system that packages are compiled before an image is created.
I'm open to suggestions if anybody thinks this could or should be placed elsewhere.

 buildsystem: add support for building extra packages specified in project or device options

---

packages/mediacenter/LibreELEC-settings/package.mk

Update to recent version. Also fix for PKG_LICENSE. According to https://github.com/LibreELEC/service.libreelec.settings/blob/master/COPYING the package is GPL not proprietary.

LibreELEC-settings: update to b13dbf3

---

packages/databases/mysql/package.mk

5.7.18 is no longer available for download (although we have it on our mirror).

mysql: update to mysql-5.7.20

---

projects/Amlogic/filesystem/usr/lib/systemd/system/fstrim.service

With fstrim from util-linux we can use one command to trim all trimmable mounts. Use it and simplify the service.

projects/Amlogic: fstrim all trimmable mounts

---

packages/sysutils/systemd/patches/systemd-0200-persist-persistent-timer-stamps.patch

The need for this change became evident when testing #2399.
Each time a persistent timer is run it updates it's stamp file in `/var/lib/systemd/timers` so that when the system is rebooted it can correctly recalculate the next trigger time relative to the last time the timer triggered.
Since `/var` is not persistent in LibreELEC, the persistent timers will have no stamp from previous runs so when rebooting, the trigger for a weekly timer will always be calculated as +1 week from "now", rather than +1 week from when it last ran (which may have been 6 days ago, so the timer should run tomorrow, not next week).
Without this change, some timers may never trigger unless the system is left up for weeks/months.
This does cause an issue with systems without real time clocks, as by default …

systemd: persist persistent timer stamps

---

packages/network/samba/config/smb.conf
packages/network/samba/scripts/smbd-config

Not entirely sure if this is worthwhile, but it came up in [the forum](https://forum.libreelec.tv/thread/10667-cannot-connect-to-smb-after-updating-to-8-2-1-how-do-i-roll-back/?postID=77279#post77279).
We use `browseable` and `writeable` (with `e` - British English?) in the `[global]` section, but the version without `e` (`browsable`/`writable`) in the share sections. Fortunately both are valid, with or without the `e`, so this is just a cosmetic issue.
I see no good reason not to be consistent, so I'm adding the missing `e` since the properties with `e` are the documented properties in smb.conf man pages (see forum link - the properties without `e` are just synonyms, so maybe added later due to this being a common misspelling?)
The second commit replaces the synonyms with the documented …

samba: use documented browseable/writeable properties not synonyms

---

packages/graphics/mesa/package.mk
packages/x11/driver/xf86-video-intel/package.mk

xf86-video-intel adds Coffeelake support, various sna fixes.

mesa/xf86-video-intel: bump to 17.3.2/028c946

---

packages/addons/service/tvheadend42/source/bin/tv_grab_file

Kodi 18 settings.xml changes break the current Tvheadend tv_grab_file function - this updates the tv_grab_file grep to match the changes.

update for Kodi 18 settings.xml changes

---

packages/linux-firmware/amlogic/qca9377-firmware-aml/package.mk

Firmware tar.gz available on linode always includes the latest version without changing the file name. This means that actual firmware version is 1.0.0-4, which is known to degrade performance, at least on Amlogic devices. To fix this regression and make sure that we always get the same firmware version, repack the 1.0.0-3 firmware and provide it from our server.

qca9377-firmware-aml: change firmware version to 1.0.0-3

---

projects/Amlogic/initramfs/platform_init
projects/WeTek_Hub/initramfs/platform_init
projects/WeTek_Play_2/initramfs/platform_init

Amlogic devices with the latest "Nougat" kernel will output no HDMI signal if incorrect mode/attr combination is provided. Since Kodi doesn't support setting attr, set it to the most universal value that would allow Kodi to set any output resolution.

amlogic: Set colorspace to avoid no HDMI signal with non-4K output modes

---

packages/linux-drivers/intel_nuc_led/package.mk
packages/linux-firmware/kernel-firmware/package.mk
packages/linux-firmware/wlan-firmware/package.mk
packages/linux/patches/default-rpi/linux-999-revert-softirq-let-ksoftirqd-do-its-job.patch
packages/linux/patches/default/linux-999-revert-softirq-let-ksoftirqd-do-its-job.patch
packages/linux/patches/default/linux-999.20-i915-pm-Be-less-agressive-with-clockfreq-changes-on-Bay-Trail.patch
packages/linux/patches/default/linux-999.21-intel_idle:-Disable-C6N-and-C6S-on-Bay-Trail.patch
packages/mediacenter/LibreELEC-settings/package.mk
packages/network/samba/config/smb.conf
packages/network/samba/scripts/smbd-config
packages/sysutils/busybox/scripts/pastebinit
projects/Generic/options

I wasn't planning to make another LE 8.2 release but the Leia Alpha milestone has moved to April and the demise of sprunge.us is complicating support in the forums. As we're doing a release we can cherry-pick some other low-risk changes that solve problems, e.g. the kernel softirq change revert to resolve USB/DVB issues since 4.9 kernel, and recent Intel Baytrail fixes.
NB: I have no plan to look at the mess of spectre/meltdown changes because the patches require proper testing and the issue is moot on LE where the console access needed to exploit means you are already the root user.
I'll leave the PR open for a few days in case other staff have changes to pick/include.

release: initial backports and updates for LE 8.2.3

---

packages/linux-drivers/media_build/sources/backports/linux-265-fix-for-kernel-4.11-cinergy-s2-dual-support.patch

This restores support for Cinergy S2 USB Rev.4 DVB-S2 tuner. Now Cinergy S2 USB Rev.4 is working, and the new tuners added by this patch should be working as well. The modification only reverts the removal of the lines needed to support my tuner.
This is the first time I submit a pull request, so maybe I made something wrong in the process. I hope it can be reviewed and merged, so I and anyone using this tuner can return to official builds again.

Fix Cinergy S2 USB Rev.4

---

scripts/create_addon

`PROJECT=Generic ARCH=x86_64 ADDON_OVERWRITE=yes scripts/create_addon abc`
overwrites addon.zip instead of abort with a warning

scripts/create_addon: add-on overwrite support

---

packages/sysutils/busybox/package.mk

We've been restricted to building projects with low concurrency make level due to race conditions when building busybox. This forces busy box to build with concurrency make level of 1 while the rest of the project can be built with a different level.

add -J flag to limit race condition during build step

---

packages/mediacenter/LibreELEC-settings/package.mk

This removes lirc enable/disable switch in LE settings which is no longer needed since #2341

LibreELEC-settings: update to c8ec6f6

---

packages/linux-driver-addons/dvb/crazycat/package.mk

This patch disables IR_NUVOTON options which doesn't compile with 3.10 kernel. In return we can enable crazycat for WeTek Core and Play (when cc-compatible module is ready).
Ping @codesnake - can you check with WeTek Core, please?

crazycat: fix building for amlogic-3.10

---

packages/linux/package.mk

Use most recent version of Amlogic kernel 3.10 from LibreELEC/linux-amlogic.

linux: update amlogic-3.10 kernel to amlogic-3.10-02fdb27

---

packages/linux-drivers/amlogic/fd628-aml/package.mk

This PR is to update the source URL for the FD628 VFD driver, one of the forum users has modified the original Tanix source to make the driver compatible with multiple devices via changes to the device tree sources.
Tested and confirmed working on 3 devices so far.
Tanix TX3 Mini S905W
Sunvell T95M S905X
Vorke Z6 S912
@kszaq @Raybuntu @arthur-liberman

fd628-aml: update driver source to support multiple devices

---

packages/multimedia/ffmpeg/package.mk

`--enable-indev=x11grab_xcb` is not available at ffmpeg >3.3
it is useless to have this option build in, ffmpegx supports it and adds encoders to the build to make it usable at all

ffmpeg: remove x11grab

---

config/functions
packages/network/samba/package.mk
packages/sysutils/busybox/package.mk
packages/tools/bcm2835-bootloader/package.mk
packages/tools/installer/package.mk
packages/tools/plymouth-lite/package.mk
packages/tools/u-boot/package.mk
packages/x11/xserver/xorg-server/package.mk
projects/Amlogic/devices/LePotato/packages/u-boot/package.mk
scripts/image
scripts/mkimage

This is something that's been bugging me for a while.
Currently we use this pattern which is repeated (with minor changes) in several places:
```
if [ -n "$DEVICE" -a -f $PROJECT_DIR/$PROJECT/devices/$DEVICE/config/blah.conf ]; then
cp $PROJECT_DIR/$PROJECT/devices/$DEVICE/config/blah.conf $INSTALL/etc
elif [ -f $PROJECT_DIR/$PROJECT/config/blah.conf ]; then
cp $PROJECT_DIR/$PROJECT/config/blah.conf $INSTALL/etc
elif [ -f $DISTRO_DIR/$DISTRO/config/blah.conf ]; then
cp $DISTRO_DIR/$DISTRO/config/blah.conf $INSTALL/etc
else
cp $PKG_DIR/config/blah.conf $INSTALL/etc
fi
```
I think it would be better to use a helper function that takes care of locating the file or directory within the standard repo hierarchy (ie. project/device -> project -> distribution -> pkg etc.) so that the package …

buildsystem: avoid if/then/else boiler plate when accessing hierarchy [RFC]

---

packages/addons/addon-depends/dvb-tools-depends/depends/bitstream/package.mk
packages/addons/addon-depends/dvb-tools-depends/dvblast/package.mk
packages/addons/addon-depends/dvb-tools-depends/mumudvb/package.mk
packages/addons/addon-depends/dvb-tools-depends/w_scan/package.mk
packages/addons/tools/dvb-tools/changelog.txt
packages/addons/tools/dvb-tools/package.mk
packages/addons/tools/dvb-tools/source/default.py

follow up pr for https://github.com/LibreELEC/LibreELEC.tv/pull/2460
- dvblast includes current upstream version and fixes HEVC, pkg url was switched to git mirror as the upstream url won't allow download with wget (https://code.videolan.org/videolan/dvblast)
- w_scan was changed to refelect changes at our build system (@Raybuntu should work I guess?)

dvb-tools addon bump

---

scripts/mkimage

This reverts commit 7793bea2e9d47d979bf830c15c657c456aead2bb.
`scripts/mkimage` doesn't actually source `config/options` so doesn't have access to any helper functions and now fails with:
```
scripts/mkimage: line 252: find_file_path: command not found
```
Sourcing `config/options` may overwrite one or more of the environment variables used by `scripts/mkimage`, making it a risky proposition.
Reverting this change is the simplest/safest option.
Thanks/apologies @kszaq!

Revert "scripts/mkimage: use helper function"

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
packages/mediacenter/LibreELEC-settings/package.mk

`service.libreelec.settings`:
* Corrects use of sprunge.us with ix.io in Help messages (reported on Team Kodi slack).
`brcmfmac_sdio-firmware-rpi`:
* Update with latest RPi3/ZeroWH WiFi firmware after [successful testing](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=203508)

LibreELEC Repo bumps: service.libreelec.settings and brcmfmac_sdio-firmware-rpi
