packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk, packages/mediacenter/LibreELEC-settings/package.mk
Backport of #2482.
Switches brcmfmac_sdio-firmware-rpi to use our repo.
=> LibreELEC Repo bumps: service.libreelec.settings and brcmfmac_sdio-firmware-rpi [Backport]

packages/emulation/libretro-beetle-pcfx/package.mk, packages/emulation/libretro-craft/package.mk, packages/emulation/libretro-desmume/package.mk, packages/emulation/libretro-mame2010/package.mk, packages/emulation/libretro-mame2014/package.mk, packages/emulation/libretro-mupen64plus/package.mk, packages/emulation/libretro-pcsx-rearmed/package.mk, packages/emulation/libretro-ppsspp/package.mk, packages/emulation/libretro-ppsspp/patches/libretro-ppsspp-0004-ffmeg-build.patch, packages/emulation/libretro-reicast/package.mk
This PR change the DEVICE and PROJECT case with and equivalent code using TARGET_CPU
The idea is maintain the same functionality, only **cortex-a17** has been added.
~~Please DON'T MERGE, I'm trying to understand why on my environment~~ the following packages not compile:
- ~~libretro-mupen64plus~~
- ~~libretro-desmume~~
- ~~libretro-ppsspp~~
- libretro-reicast
~~I have reverted my changes on libretro-mupen64plus and still failing, I'm not sure if is a error on my environment or a real issue with the packages.~~ libretro-mupen64plus fixed.
~~libretro-ppsspp gives me a 404 downloading the code from github, maybe is a temporal issue.~~
This PR supersede the commit 92f993cce5b0d82d2c31113cd3994791c0c962e4 from #2116 
I have added a few lines of code to avoid the nested PROJECT and DEVICE …
=> emulation: Replace DEVICE and PROJECT variables with TARGET_CPU

config/functions, packages/linux/package.mk
As per title.
@HiassofT I realised while updating the linux package for this change (sorry for not noticing before!) that the $PKG_VERSION is needed to correctly determine the config path, and so `$(kernel_config_path)` must be called after we have set PKG_VERSION in the `case` statement.
This isn't a problem with #2480 as we don't currently have any PKG_VERSION-specific config paths, but could be in future, hence moving to after the `case` statement which sets PKG_VERSION.
=> functions: add helper function to locate linux config

packages/lang/gcc-linaro-aarch64-linux-gnu/package.mk
I need to test this new toolchain first on AML on RK.
=> gcc-linaro-aarch64-linux-gnu: update to 7.2-2017.11

packages/linux/package.mk
This PR skips building `perf` on 64-bit kernel + 32-bit userspace builds, fixes building `ARCH=arm` on Rockchip.
=> linux: do not build perf on 64/32-bit

packages/debug/valgrind/package.mk, packages/devel/arm-mem/package.mk
new arm-mem library contains a fix so that it can be used with valgrind on RPi2/3. It also contains optimized memset for armv7 which can be beneficial for RPi2/3
valgrind 3.13.0 fixes unhandled instructions on RPi2/3, it's now runs on RPi2/3 fine (it won't compile on RPi1, but so didn't 3.12.0)
=> bump arm-mem and valgrind

projects/Amlogic/bootloader/update.sh
If there is no file matching `/flash/*.dtb` wildcard, the loop will proceed with `all_dtb="/flash/*.dtb"`, causing erratic behaviour in next script steps. Fix this by checking if  exists before proceeding.
=> projects/Amlogic: update.sh fix and cleanup

packages/sysutils/busybox/package.mk
I hit this issue when building `busybox` (host)
```
gcc -Wp,-MD,libpwdgrp/.uidgid_get.o.d   -std=gnu99 -Iinclude -Ilibbb  -include include/autoconf.h -D_GNU_SOURCE -DNDEBUG -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D"BB_VER=KBUILD_STR(1.28.1)" -O2 -Wall -pipe -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Play.arm-9.0-devel-systemd-glibc226/toolchain/include -Wno-format-security -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability …
```
=> busybox: don't build parallel

config/functions, config/optimize, config/options, config/path, config/show_config, distributions/LibreELEC/options, packages/audio/alsa-lib/package.mk, packages/databases/mysql/package.mk, packages/devel/attr/package.mk, packages/devel/glibc/package.mk, packages/lang/gcc/package.mk, packages/multimedia/ffmpeg/package.mk, packages/network/bluez/package.mk, packages/virtual/debug/package.mk, scripts/build, scripts/image
This is proposed as an alternative to #2493 
Selectively building LibreELEC packages with debug significantly reduces the size of SYSTEM+KERNEL making it unnecessary to increase partition size at this time.
Most of the time we only need Kodi and supporting libraries to be built with debug, this can be accomplished with `DEBUG=yes`.
If all packages need to be built with debug, then `DEBUG=all` can be used.
`yes` maps to a "group", which is currently defined as `kodi !mesa` - this builds `kodi` (and all immediate dependent packages as defined by `PKG_DEPENDS_TARGET`) while excluding `mesa` as the graphics drivers with symbols are very large and rarely require debugging.
When building `kodi` with debug, all addons will be built with debug. Similarly, if building `linux` with debug, all …
=> buildsystem: selectively build packages with debug

packages/debug/gdb/package.mk, packages/debug/libunwind/package.mk, packages/devel/binutils/package.mk, packages/linux/package.mk, packages/linux/patches/default/linux-999-no-lzma-in-x86-perf-build.patch
perf crosscompilation should be performed like for linux kernel, i.e. by specifying ARCH and CROSS_COMPILE. The initial version accidentally dropped LDFLAGS, add these back in.
On x86_64 the upstream Makefile adds -llzma to the libunwind libs, patch this out as we don't build lzma in LE.
Also cleanup libunwind package.mk so that headers and static libs are only installed to sysroot
=> fix perf build

packages/linux-driver-addons/dvb/crazycat/config/usb.config, packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-01-add-AML-specific-to-backports.patch, packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-04-AML-hacks.patch, packages/linux-driver-addons/dvb/crazycat/sources/backports/linux-304-AML-wetekplay.patch, packages/linux-driver-addons/dvb/depends/media_tree/package.mk, packages/linux-driver-addons/dvb/hauppauge/patches/amlogic/driver.dvb.hauppauge-01-add-AML-specific-to-backports.patch, packages/linux-driver-addons/dvb/hauppauge/sources/backports/linux-304-AML-wetekplay.patch, packages/linux-drivers/wetekdvb/package.mk, projects/Amlogic/devices/WeTek_Play_2/options
Add wetekdvb modules for WeTek Play 2 built with crazycat and hauppauge headers.
Enable support for crazycat and hauppauge in WeTek Play 2 project.
=> WeTek Play 2: Add support for crazycat and hauppauge driver addons

config/path, packages/linux-drivers/RTL8188EU/package.mk, packages/linux-drivers/RTL8192CU/package.mk, packages/linux-drivers/RTL8192DU/package.mk, packages/linux-drivers/RTL8192EU/package.mk, packages/linux-drivers/RTL8812AU/package.mk, packages/linux-drivers/amlogic/RTL8188EU-aml/package.mk, packages/linux-drivers/amlogic/RTL8189ES-aml/package.mk, packages/linux-drivers/amlogic/RTL8189FS-aml/package.mk, packages/linux-drivers/amlogic/RTL8723BS-aml/package.mk, packages/linux-drivers/amlogic/RTL8723DS-aml/package.mk, packages/linux-drivers/amlogic/RTL8822BU-aml/package.mk, packages/linux-drivers/amlogic/ap6xxx-aml/package.mk, packages/linux-drivers/amlogic/mt7601u-aml/package.mk, packages/linux-drivers/amlogic/mt7603u-aml/package.mk, packages/linux-drivers/amlogic/qca9377-aml/package.mk, packages/linux-drivers/amlogic/ssv6xxx-aml/package.mk, packages/linux-drivers/brcmap6xxx-aml/package.mk, packages/linux/package.mk, packages/tools/u-boot/package.mk, scripts/build, scripts/image
Cross compiling the linux kernel and u-boot is normally done via setting appropriate ARCH and CROSS_COMPILE options (which the LE buildsystem already does).
It's therefore not necessary to redefine TARGET_PREFIX in scripts/build
Just add TARGET_KERNEL_PREFIX (defaulting to TARGET_PREFIX on non-split arch builds) in addition to the already existing TARGET_KERNEL_ARCH and use that for compiling kernel, kernel-modules and u-boot
Note: with these changes PKG_IS_KERNEL_PKG becomes an unused marker and can probably be dropped, but I left it intact for now
=> Compile kernel on 64/32 split archs without redefining TARGET_PREFIX

projects/Amlogic/packages/device-trees-amlogic/package.mk
Bump package to latest revision and also include wetek device trees in S905 image
=> device-trees-amlogic updates

packages/linux-drivers/wetekdvb/package.mk, projects/Amlogic/devices/S905/options
This PR adds the driver & firmware for wetek dvb into the generic S905 builds.
=> projects/Amlogic: include wetekdvb with S905 builds

config/functions, scripts/build, scripts/clean, scripts/image
Following on from #2516, this is an attempt to save some "state" within each build directory so that it doesn't have to be parsed from the build directory name which isn't going to be reliable/easy in every case.
Have I missed anything (any variables, reasons why this won't work)?
It's not perfect, I realise it's possible to rebuild with different DEBUG values each time, so the presence of DEBUG is somewhat informational and probably shouldn't be relied upon, but would represent the last value used.
The config is only saved when executing `scripts/image` - not sure if this is going to be a problem with addons. I can't imagine anyone builds the main image exclusively using `scripts/build`.
=> buildsystem: save/load build config, simplify clean and build --all

tools/mkpkg/update_binary-addons, tools/mkpkg/update_retroplayer-addons
As mentioned in #2141, `package.mk` should only ever be sourced with `config/options`.
I haven't updated `tools/repo-tool` as I'm not sure if it's still used/how it's used.
=> tools: source packages reliably

packages/devel/binutils/patches/binutils-02-PR22764.patch, projects/Rockchip/README.md, projects/Rockchip/patches/linux/rockchip-4.4/linux-0001-rockchip.patch
This PR includes fixups for building aarch64, fixup commits to be squashed on next rebase.
Also includes binutils patch from #2525, to be dropped on next rebase.
=> Rockchip: fix building aarch64

packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-01-add-AML-specific-to-backports.patch, packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-04-AML-hacks.patch, packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-05-compat_h-fix.patch, packages/linux-driver-addons/dvb/crazycat/sources/backports/linux-305-AML-dmx_h.patch, packages/linux-driver-addons/dvb/crazycat/sources/backports/linux-306-AML-build-dvb-avl.patch, packages/linux-driver-addons/dvb/depends/media_tree/package.mk, packages/linux-driver-addons/dvb/hauppauge/patches/amlogic/driver.dvb.hauppauge-01-add-AML-specific-to-backports.patch, packages/linux-driver-addons/dvb/hauppauge/patches/amlogic/driver.dvb.hauppauge-05-compat_h-fix.patch, packages/linux-driver-addons/dvb/hauppauge/sources/backports/linux-305-AML-dmx_h.patch, packages/linux-driver-addons/dvb/hauppauge/sources/backports/linux-306-AML-build-dvb-avl.patch, packages/linux-drivers/amlogic/avl6862-aml/package.mk, packages/linux-drivers/amlogic/avl6862-aml/system.d/amlogic-dvb.service, projects/Amlogic/devices/S905/options, projects/Amlogic/devices/S912/options
This PR introduces support for internal dvb in WP2 and Mecool K-series boxes.
=> Amlogic: support  for AVL6862 DVB driver

packages/devel/binutils/patches/binutils-02-PR22764.patch
This PR adds a patch to fix a ld regression on aarch64, fixes building aarch64 `u-boot` on `rockchip` branch.
Patch is taken from `binutils-2_30-branch` with the changes to `ChangeLog`-files removed to make it apply.
Bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=22764
Fix commit: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commitdiff;h=b01452b1d44a586f4ecf5cf02ffc0643e4962324
=> binutils: add patch to fix aarch64 ld regression

packages/linux-driver-addons/dvb/crazycat/sources/backports/linux-302-AML-amlogic-video-dev.patch
fixes broken patch after https://github.com/LibreELEC/LibreELEC.tv/pull/2451
patch didn't apply at all
```
patch -s -f -N -p1 -i ../backports/linux-302-AML-amlogic-video-dev.patch
1 out of 1 hunk FAILED
```
=> crazycat: fix broken patch

packages/linux-driver-addons/dvb/hauppauge/sources/backports/linux-302-AML-amlogic-video-dev.patch
fixes broken patch after #2451
patch didn't apply at all
```
patch -s -f -N -p1 -i ../backports/linux-302-AML-amlogic-video-dev.patch
1 out of 1 hunk FAILED
```
I had forgotten to add this to https://github.com/LibreELEC/LibreELEC.tv/pull/2532
=> hauppauge: fix broken patch

packages/tools/dtc/package.mk
I cherry-picked the change from Raybuntu's LE fork. It adds building `fdtget` and `fdtput` tools useful to modify device trees in-place.
=> dtc: build fdtput and fdtget

scripts/uboot_helper
The dtb name for Odroid-C2 was wrong in the uboot_helper script, this fixes the mkimage.
=> uboot_helper: fix dtb name for odroid-c2

packages/linux-drivers/wetekdvb/package.mk
Fix an issue when the device variable always evaluates to WeTek_Play_2 causing drivers for WeTek Play 2 to be copied for WeTek Play 1.
=> wetekdvb: fix an issue when the device variable always evaluates to WeTek_Play_2

packages/mediacenter/LibreELEC-settings/package.mk
=> LibreELEC-settings: update to a70ec1c

projects/Amlogic_GX/patches/linux/0050-ath10k-add-inlined-wrappers-for-htt-tx-ops.patch, projects/Amlogic_GX/patches/linux/0051-ath10k-add-inlined-wrappers-for-htt-rx-ops.patch, projects/Amlogic_GX/patches/linux/0052-ath10k-add-struct-ath10k_bus_params.patch, projects/Amlogic_GX/patches/linux/0053-ath10k-high-latency-detection.patch, projects/Amlogic_GX/patches/linux/0054-ath10k-add-bus-type-check-in-ath10k_init_hw_params.patch, projects/Amlogic_GX/patches/linux/0055-ath10k-per-target-config-of-max_num_peers.patch, projects/Amlogic_GX/patches/linux/0056-ath10k-DMA-related-fixes-for-high-latency-devices.patch, projects/Amlogic_GX/patches/linux/0057-ath10k-various-fixes-for-high-latency-devices.patch, projects/Amlogic_GX/patches/linux/0058-ath10k-add-start_once-support.patch, projects/Amlogic_GX/patches/linux/0059-ath10k-add-HTT-TX-HL-ops.patch, projects/Amlogic_GX/patches/linux/0060-ath10k-add-HTT-RX-HL-ops.patch, projects/Amlogic_GX/patches/linux/0061-ath10k-htt-RX-ring-config-HL-support.patch, projects/Amlogic_GX/patches/linux/0062-ath10k-htt-High-latency-TX-support.patch, projects/Amlogic_GX/patches/linux/0063-ath10k-htt-High-latency-RX-support.patch, projects/Amlogic_GX/patches/linux/0064-ath10k-wmi-disable-softirqs-while-calling-ieee80211_rx.patch, projects/Amlogic_GX/patches/linux/0065-ath10k-remove-htt-pending-TX-count-for-high-latency.patch, projects/Amlogic_GX/patches/linux/0066-ath10k-add-QCA9377-usb-hw_param-item.patch, projects/Amlogic_GX/patches/linux/0067-ath10k-add-QCA9377-sdio-hw_param-item.patch, projects/Amlogic_GX/patches/linux/0068-ath10k-sdio-htt-data-transfer-fixes.patch, projects/Amlogic_GX/patches/linux/0069-ath10k-wb396-reference-card-fix.patch, projects/Amlogic_GX/patches/linux/0070-ath10k-DMA-bounce-buffers-for-read-write.patch, projects/Amlogic_GX/patches/linux/0071-ath10k-reduce-transmit-msdu-count.patch, projects/Amlogic_GX/patches/linux/0072-ath10k-use-clean-packet-headers.patch, projects/Amlogic_GX/patches/linux/0073-ath10k-high-latency-fixes-for-beacon-buffer.patch, projects/Amlogic_GX/patches/linux/0074-ath10k-fix-rssi-indication.patch, projects/Amlogic_GX/patches/linux/0075-ath10k-common-read-write.patch, projects/Amlogic_GX/patches/linux/0076-ath10k-virtual-scatter-gather-for-receive.patch, projects/Amlogic_GX/patches/linux/0077-ath10k-hif-start-once-addition.patch, projects/Amlogic_GX/patches/linux/0078-ath10k-fix-type-mismatch-in-func-prototype.patch, projects/Amlogic_GX/patches/linux/0079-ath10k-add-sparklan-usb-support.patch
This patch series adds ath10k sdio support to the mainline kernel - patches are still being tweaked for upstreaming in 4.17 or 4.18. Not fully tested yet, so merge blocked.
=> linux: add ath10k sdio patches

packages/mediacenter/kodi/scripts/cputemp
On a mainline kernel `scpi_sensors` is required in the cputemp script for the Kodi System Information screen to show Amlogic SoC temperatures.
=> kodi: add scpi_sensors to cputemp script

scripts/mkimage
This tweaks the uboot message wording to align (literally) with the other messages that run before and after it when making the image. OCD at its finest :)
=> mkimage: tweak uboot wording to match other messages

packages/linux-driver-addons/dvb/crazycat/sources/backports/linux-303-AML-meson-ir.patch, packages/linux-driver-addons/dvb/hauppauge/sources/backports/linux-303-AML-meson-ir.patch
This patch is following @danielkucera #98 PR 'fix flush_timer'  in linux-amlogic.
=> linux-driver-addons: fix flush_timer for meson-ir and consolidate patch

packages/addons/addon-depends/ffmpegx/package.mk
fixes a missing dependency when building for generic at jenkins
=> ffmpegx: reorder dependencies

projects/Amlogic_GX/patches/linux/0002-dw-hdmi-Fix-overflow-workaround-for-Amlogic-Meson-GX-SoCs.patch
adding https://patchwork.freedesktop.org/patch/206458/ until 4.17 kernel
=> linux: add dw-hdmi overflow patch from 4.17-rc1

projects/Amlogic/packages/u-boot/package.mk
in case `PKG_VERSION` is set **after** `PKG_URL`, `PKG_VERSION="0.0invalid"` at the time of setting `PKG_URL`.
From IRC:
```
09:10 < jazz> hi there
09:11 < jazz> is LE git head building fine ? i get a problem with u-boot sources (0.0invalid.tar.gz)
09:13 < vpeter> jazz: Which project?
09:20 < jazz> odroid c2
09:20 < jazz> vpeter:
09:28 < jazz> project amlogic, device odroid_c2
09:30 < jazz> vpeter: wget https://github.com/hardkernel/u-boot/archive/0.0invalid.tar.gz returns a 404
09:37 < vudiq> jazz: could it be because PKG_VERSION is set AFTER PKG_URL?
09:37 < vudiq> https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Amlogic/packages/u-boot/package.mk#L29
09:37 < vudiq> the order of PKG_URL and PKG_VERSION should be swapped, imho
09:39 < vudiq> try to change it locally …
```
=> Amlogic u-boot: fix order of PKG_URL and PKG_VERSION

projects/RPi/patches/kodi/kodi-0100-temp-add-pr13594.patch
This PR has been in included in Milhouse builds for a while, without it Netflix is unusable on RPi.
So temporarily add it until it's either merged upstream or a proper fix for the playback issues is found
see kodi PR for details https://github.com/xbmc/xbmc/pull/13594
=> RPi: temporarily add kodi PR13594

tools/distro-tool
Default to $HOME/sources sym link which points to wherever tarballs are stored.
No `python` sym link on sources server, only `python3`.
=> distro-tool: fixup after server migration

packages/linux/package.mk
Since 64/32 split arch compilation problems have been resolved and rockchip-4.4 kernel received the required perf patch it's now safe to enable perf on 4.4 and newer kernels.
None of the current AML projects with 3.x kernels have CONFIG_PERF_EVENTS set so perf won't be built there. But since this may change in the future and perf compilation hasn't been tested with these old kernels (and quite certainly will fail), disable perf for these kernel trees.
I've compile+runtime tested this on Rock64
=> linux: build perf on all kernels except amlogic-3.x

config/noobs/partitions.json, scripts/image
Limited backport of #2243.
Once implemented, create duplicates of the new tarfiles using the old tar filenames until the [upstream json](https://downloads.raspberrypi.org/os_list_v3.json) file is updated.
=> NOOBS: shorten partition labels, change tar filename [backport]

packages/network/bluez/patches/bluez-21-hciattach-add-QCA9377-Tuffello-support.patch, packages/network/bluez/patches/bluez-22-hciattach_rome-simplify-baudrate-setting.patch, packages/network/bluez/patches/bluez-23-hciattach_rome-do-not-override-module-MAC.patch, packages/network/bluez/patches/bluez-24-hciattach_rome-force-IBS-to-disabled-in-NVM.patch, packages/network/bluez/patches/bluez-25-hciattach_rome-display-ROM-and-TLV-info.patch
The QCA9377 module on the SML-5442TW box requires a large patch to bluez that has been refused upstream as it uses hciattach; the patch author is still working up the enthusiasm to rework it around a new/preferred method. The module also requires ath10k-sdio firmware that doesn't currently exist in the mainline kernel-firmware repo so we add a temporary package to source it, along with a package for the BT firmware. In the long-term I expect to drop or roll both packages into others, but it's been a good way to experiment with different approaches for being more explicit with what gets included, or in this case excluded to avoid bloat and select only what's actually needed for the device.
=> amlogic: changes for qca9377 sdio module

packages/network/samba/package.mk
https://www.samba.org/samba/security/CVE-2018-1057.html
=> samba: update to samba-4.7.6

packages/x11/driver/xf86-video-nvidia/package.mk
Announcement: [driver](http://www.nvidia.com/Download/driverResults.aspx/131853/en-us)
Fixes a regression.
=> xf86-video-nvidia: update to xf86-video-nvidia-390.42

packages/linux-drivers/amlogic/fd628-aml/package.mk, packages/linux-drivers/amlogic/fd628-aml/system.d/fd628.service
There was a typo (missing closing ') in the service file and without this PR the service won't start.
In addition there was a bug in the driver that would cause an exception during modprobe, which is now fixed, and therefore I bumped it up.
=> Fix fd628.service syntax error + Fix small bug in fd628-aml driver.

packages/linux/package.mk, projects/Amlogic/packages/device-trees-amlogic/package.mk
As the title says
amlogic-3.10 bump contains wetek play 1 dtb update
amlogic-3.14 bump contains dtb updates for latest vfd driver
device-trees-amlogic contains dtb updates for latest vfd driver
=> Amlogic related package bumps

config/arch.aarch64, config/arch.arm, config/arch.x86_64, config/show_config, packages/graphics/libjpeg-turbo/package.mk, projects/Amlogic/options, projects/Generic/options, projects/RPi/options, projects/Rockchip/devices/MiQi/options, projects/Rockchip/devices/RK3328/options, projects/Rockchip/devices/RK3399/options, projects/Rockchip/devices/TinkerBoard/options, projects/WeTek_Core/options, projects/WeTek_Play/options
`neon` and `mmx/sse/sse2` should be defined by the CPU, not the project or device.
This also drops the variable `SIMD_SUPPORT`.
=> buildsystem: simplify SIMD support (neon/mmx/sse/sse2)

packages/linux-drivers/wetekdvb/modules-load.d/wetekdvb.conf, packages/linux-drivers/wetekdvb/package.mk, packages/linux-drivers/wetekdvb/system.d/wetekdvb.service
This PR is to fix the issue identified in #2575, as wetekdvb is included in the S905 image it should only be loaded conditionally.
=> wetekdvb: load the module conditionally

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk, packages/linux-firmware/wlan-firmware/package.mk
Backport of #2587 and #2599, after I got #2588 into a mess which can't be re-opened.
=> brcmfmac_sdio-firmware-rpi: cleanup wlan-firmware [backport]

packages/emulation/libretro-beetle-pcfx/package.mk, packages/emulation/libretro-craft/package.mk, packages/emulation/libretro-mame2010/package.mk, packages/emulation/libretro-mame2014/package.mk, packages/emulation/libretro-mupen64plus/package.mk
This is necessary to build emulation packages for RK3399 devices.
=> Emulation support for cortex-a72.cortex-a53

packages/addons/service/fd628/sources/resources/lib/fd628dev.py, packages/addons/service/fd628/sources/resources/lib/service.py
Sorry for the mess and the consecutive PRs on something that should've been just one.
This PR fixes the Kodi FD628 Service add-on to work with the new driver.
=> Update fd628 kodi add-on to support new driver device name.

packages/addons/addon-depends/moonlight-common-c/package.mk, packages/addons/addon-depends/moonlight-embedded/package.mk, packages/addons/script/moonlight/changelog.txt, packages/addons/script/moonlight/package.mk
Update moonlight addon.
Fixes build error of moonlight-embedded for WeTek Core and WeTek Play 1 projects:
```
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CURL: /var/lib/jenkins/LE/build2/workspace/Addons/Category/script/moonlight/build.LibreELEC-WeTek_Core.arm-9.0-devel/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/lib/libcurl.so (found version "7.58.0") 
-- Found OpenSSL: /var/lib/jenkins/LE/build2/workspace/Addons/Category/script/moonlight/build.LibreELEC-WeTek_Core.arm-9.0-devel/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/lib/libcrypto.so (found suitable version "1.0.2n", minimum required is "1.0.2") 
-- Found EXPAT: /var/lib/jenkins/LE/build2/workspace/Addons/Category/script/moonlight/build.LibreELEC-WeTek_Core.arm-9.0-devel/toolch …
```
=> moonlight: update addon

config/functions, packages/python/devel/meson/package.mk, packages/sysutils/systemd/package.mk, scripts/build
- generate cross-file per package, needed since https://github.com/mesonbuild/meson/pull/1807 was merged. build-flags can used like in cmake and configure, now.
=> meson: update to 0.45

packages/security/openssl/package.mk
1.0.2m: https://www.openssl.org/news/secadv/20171102.txt
1.0.2n: https://www.openssl.org/news/secadv/20171207.txt
1.0.2o: https://mta.openssl.org/pipermail/openssl-announce/2018-March/000119.html
No must-have fixes, but brings us up to date and should be low-risk, but close if not wanted.
=> openssl: update to openssl-1.0.2o [backport]

config/path, distributions/LibreELEC/options, scripts/extract, scripts/get, scripts/get_archive, scripts/get_file, scripts/get_git, scripts/unpack
This is a feature that came out of #2517.
It adds support for packages file formats that may be of more use to developers (file/directory), and other distributions (git).
The `get_archive` handler implements current tar archive download functionality.
The `get_file` handler supports files and directories using `file://<path>` urls. If the file is a tar archive then it will be unpacked directly into the build directory (if not a tar archive it will be copied, but the build will most likely fail). Directories will be copied directly into the build directory.
The `get_git` handler supports git repositories using either `git://` urls, or urls that end in `.git`. Repositories will be cloned into a directory in $SOURCES, and from there copied into the build directory.
The distro option …
=> buildsystem: support get handlers (archive, file, git)

packages/security/openssl/package.mk
https://mta.openssl.org/pipermail/openssl-announce/2018-March/000119.html
=> openssl: update to openssl-1.0.2o

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Update Broadcom BCM43455 (Pi0W/Pi3+) firmware from v7.45.112 to v7.45.154.
=> brcmfmac_sdio-firmware-rpi: update to brcmfmac_sdio-firmware-rpi-18d7c93

config/functions, packages/lang/Python2/package.mk, packages/lang/Python3/package.mk, scripts/build, scripts/checkdeps, scripts/unpack
Clean builds required (as this will change all the stamps).
The Python changes remove junk left in the build directories.
Stamp generation is ripe for a function, and using a better hashing function is now trivial.
`==` works fine, but we use `=`.
=> buildsystem: cleanups, use sha256sum for stamp function

packages/sysutils/amremote/scripts/remote-config, projects/WeTek_Core/filesystem/etc/amremote/remote1.conf, projects/WeTek_Hub/patches/linux/wetek_pro_remote.patch, projects/WeTek_Play/filesystem/etc/amremote/remote1.conf, projects/WeTek_Play_2/filesystem/etc/amremote/remote1.conf
Add support for WeTek Pro Remote (https://wetek.com/ww/en/product/pro-remote) to WeTek Play, WeTek Core, WeTek Hub , and WeTek Play 2 projects.
=> [LE 8.2] WeTek Play, WeTek Core, WeTek Hub, WeTek Play 2: add support for WeTek Pro Remote

packages/mediacenter/kodi/scripts/kodi-config
No idea about the porpouse of that hack but this looks rather dead code. 
Also `http://libreelec.tv/news?format=feed&type=rss` or `http://feeds.libreelec.tv/news` were never a valid source of rss in the past.
=> kodi: remove rss hack

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch, packages/linux-drivers/media_build/sources/backports/linux-999-fix-mce-kbd-stuck-keys.patch, packages/linux/patches/default-rpi/linux-999-fix-mce-kbd-stuck-keys.patch, packages/linux/patches/default/linux-999-fix-mce-kbd-stuck-keys.patch
Backport of https://patchwork.linuxtv.org/patch/48519/
This fixes the issue reported here: https://forum.libreelec.tv/thread/12095-no-driver-for-ehome-ir-transceiver/?postID=87588#post87588
=> [8.2] fix stuck keys with MCE keyboard

scripts/image
This PR adds support for using periodic naming of nightly/daily/weekly/monthly `devel` images.
It also drops the revision count from the image name of `devel` images for consistent naming.
`CUSTOM_GIT_HASH` will be used instead for `git rev-parse HEAD` in image name if supplied.
The `$BUILD/BUILD_FILENAME` file now contains the full `$IMAGE_NAME` instead of just `$LIBREELEC_VERSION`.
Use `BUILD_PERIODIC=nightly/daily/weekly/monthly` to use the periodic naming.
Example
```
LibreELEC-RK3328.arm-9.0-devel-20180422165943-a80c9bb.tar
LibreELEC-RK3328.arm-9.0-nightly-20180422-a80c9bb.tar
LibreELEC-RK3328.arm-9.0-daily-2018112-a80c9bb.tar
LibreELEC-RK3328.arm-9.0-weekly-201816-a80c9bb.tar
LibreELEC-RK3328.arm-9.0-monthly-201804-a80c9bb.tar
```
`UBOOT_SYSTEM` images
``` …
```
=> scripts/image: support periodic image names

packages/network/samba/package.mk, packages/network/samba/scripts/samba-autoshare, packages/network/samba/scripts/samba-config, packages/network/samba/system.d.opt/nmbd.service, packages/network/samba/system.d.opt/smbd.service
When booting with external storage already attached, there's a race condition caused by `samba-autoshare` which is started by `udevil-mount`.
`samba-config` is executed as soon as `sysinit.target` is reached - this will create `/run/samba/smb.conf`.
`udevil-mount` will subsequently execute `samba-autoshare` which unconditionally executes `samba-config` overwriting `/run/samba/smb.conf`, followed by `smbd-config` that adds `workgroup`. `server min protocol`, `server max protocol` and the auto shares, to `/run/samba/smb.conf`.
Samba is then started (starting `nmbd` and `smbd`) and both these units require `samba-config`, however `samba-config` has already been started after reaching `sysinit-target` so systemd does not start this unit again. Consequently when `smbd-config` is executed by …
=> samba: fix interleaved config generation/modification

config/options, packages/linux/package.mk, packages/network/bluez/package.mk, packages/network/samba/package.mk, packages/sysutils/busybox/package.mk, packages/x11/xserver/xorg-server/package.mk
The idea behind DEVTOOLS was that builds which had LIBREELEC_VERSION set to "devel" include an additional set of programs that are only relevant to development which don't need to be included in release versions to save space.
In reality the space saving is rather small (less than 2MB on a ~140MB RPi build) and the additional programs are actually rather useful ones like smbclient and btmon which are helpful on release builds as well - so users can test for issues or we can instruct them to do certain tests.
Another problem with this approach is that we developers will be testing different things than what's released. We might not notice during development that some script or addon depends on functionality that's not available in release builds - which is really bad as we'd probably not …
=> retire DEVTOOLS

packages/sysutils/systemd/config/logind.conf.d/README, packages/sysutils/systemd/package.mk
Kodi is already handling KEY_POWER and as it's currently grabbing input devices it prevents systemd-logind from receiving power button events.
If kodi and eventlircd are stopped though, eg when testing IR remote configurations, systemd-logind receives KEY_POWER events and immediately inits a shutdown - which is rather annoying.
So change the HandlePowerKey setting in /etc/systemd/logind.conf from the default (poweroff) to ignore and add the possibility to override systemd-logind settings via /storage/.config/logind.conf.d/*.conf files by users.
@lrusak with this change it should be safe to disable input grabbing in libinput
=> systemd: don't power off when power button is pressed

packages/network/connman/package.mk, packages/network/connman/patches/connman-01-build-add-disable-stats-option.patch, packages/sysutils/busybox/scripts/init
I ran into another problem while net-booting LibreELEC: with `/storage` mounted via NFS, halting or rebooting causes the system to hang. This is due to ConnMan exiting (and therefore bringing down the network) while processes still have open handles to files under `/storage` (including ConnMan itself: this can be verified with `lsof | grep /storage`, which shows that `connmand` has an open state file at `/storage/.cache/connman/*/data`).
This can be solved by lazy-unmounting `/storage` when LibreELEC is being net-booted (along with `/flash`, if that's also mounted remotely, since there's no reason not to) before ConnMan is stopped. This means that ConnMan doesn't have a chance to update its state file before it exits, but from a brief look at the ConnMan source code, it appears not to do …
=> Don't cause system to hang on halt/reboot when net-booting

packages/linux/patches/default/linux-999-improve-ir-timeout-handling.patch, packages/linux/patches/raspberrypi/linux-999-improve-ir-timeout-handling.patch
See https://www.spinics.net/lists/linux-media/msg131010.html
The current IR decoding is much too slow. Many IR protocols rely on
a trailing space for decoding (e.g. rc-6 needs to know when the bits
end). The trailing space is generated by the IR timeout, and if this
is longer than required, keys can be perceived as sticky and slugish.
The other issue the keyup timer. IR has no concept of a keyup message,
this is implied by the absence of IR. So, minimising the timeout for
this further improves the handling.
With these patches in place, using IR with the builtin decoders is much
improved and feels very snappy.
=> RPi, Generic: backport proposed patch to reduce IR latency

scripts/create_addon
@islipfd19 @chewitt works for LE addons + binary addons from my tests, not sure if something is missing or do not work if used under real conditions
usage `PROJECT=Generic ARCH=x86_64 ADDON_JENKINS=yes scripts/create_addon abc`
=> create_addon: jenkins specific quirks

packages/devel/make/patches/make-do-not-assume-glob-internals.patch, packages/devel/make/patches/support-glob-interface-v2.patch
Latest Arch Linux has trouble building make. To fix that, two commits were cherry picked from make git.
=> Make: Fix building on arch linux 

packages/tools/qemu/package.mk
- updates qemu to 2.12.0
- builds now for Ubuntu 18.04 (likely Debian Buster too)
=> qemu: update to 2.12.0

config/functions, config/optimize, packages/mediacenter/kodi/package.mk
else gcc/binultis can reenable it, automatically
Build tested with Generic, RPi2 and LePotato
=> buildsystem: use no-lto, when lto is disabled

packages/linux/patches/default/linux-999-improve-ir-timeout-handling.patch, packages/linux/patches/raspberrypi/linux-999-improve-ir-timeout-handling.patch
This should fix the issues with the Topseed mceusb receiver 1784:0011 reported
here https://forum.kodi.tv/showthread.php?tid=298461&pid=2727866#pid2727866
and here https://forum.kodi.tv/showthread.php?tid=298461&pid=2732458#pid2732458
@MilhouseVH could you please add this to your builds?
=> RPi, Generic: fix erratic IR timeout behaviour on Topseed mceusb receiver 1784:0011

packages/linux/patches/default/linux-999-improve-ir-timeout-handling-of-ite-cir.patch
Tests on my PC (with ITE8713 receiver) worked fine, if testing on other PCs is fine, too I'll send the patch upstream
=> Generic: allow lower IR timeouts on ITE CIR devices

packages/addons/addon-depends/librespot-depends/rust/package.mk, packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk
This fixes librespot, which was broken due to changes at Spotify.
This also introduces versioned rustup.
=> rust: rework

config/options, packages/devel/glibc/package.mk, packages/sysutils/busybox/scripts/getedid, packages/sysutils/busybox/scripts/init, packages/tools/installer/config/installer.conf, packages/tools/installer/package.mk, packages/tools/installer/scripts/installer, packages/tools/syslinux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/Rockchip/devices/MiQi/linux/rockchip-4.4/linux.arm.conf, projects/Rockchip/devices/RK3328/linux/rockchip-4.4/linux.aarch64.conf, projects/Rockchip/devices/RK3399/linux/rockchip-4.4/linux.aarch64.conf, projects/Rockchip/devices/TinkerBoard/linux/rockchip-4.4/linux.arm.conf, scripts/image, scripts/mkimage
As discussed on the forum:
1) Upgrade from img.gz fails when using a custom kernel filename ([thread](https://forum.libreelec.tv/thread/12400-update-with-new-le-img-gz-failes-when-boot-image-kern-82))
2) /flash/EFI/BOOT/syslinux.cfg is redundant ([thread](https://forum.libreelec.tv/thread/12411-just-one-syslinux-cfg-to-edit-for-bios-uefi))
3) Boot hooks (for encryption, other things) and configurable system to ram limit ([thread](https://forum.libreelec.tv/thread/12413-2-init-boot-hooks-and-kernel-argument-to-configure-system-toram-limit-patch-incl))
Thanks sky42.
=> init: add sky42 enhancements/bug fixes

projects/Rockchip/devices/MiQi/linux/rockchip-4.4/linux.arm.conf, projects/Rockchip/devices/MiQi/options, projects/Rockchip/devices/RK3328/linux/rockchip-4.4/linux.aarch64.conf, projects/Rockchip/devices/RK3328/options, projects/Rockchip/devices/RK3399/linux/rockchip-4.4/linux.aarch64.conf, projects/Rockchip/devices/RK3399/options, projects/Rockchip/devices/TinkerBoard/linux/rockchip-4.4/linux.arm.conf, projects/Rockchip/devices/TinkerBoard/options
I'm not sure why this was done this way, but let's fix it now :+1:
=> Rockchip: use default kernel name

packages/graphics/bcm2835-driver/package.mk, packages/linux-firmware/intel-ucode/package.mk, packages/linux-firmware/iwlwifi-firmware/package.mk, packages/linux-firmware/kernel-firmware/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.38 (skipped)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.39
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.40 (skipped)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.41
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.42
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.43
=> linux: update to 4.14.43

packages/addons/addon-depends/emby-depends/imagemagick/package.mk, packages/addons/addon-depends/ffmpegx-depends/fdk-aac/package.mk, packages/addons/addon-depends/ffmpegx-depends/x264/package.mk, packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/addon-depends/tvh-dtv-scan-tables/package.mk, packages/addons/service/emby/changelog.txt, packages/addons/service/emby/package.mk, packages/addons/service/emby/source/bin/emby-update, packages/addons/service/tvheadend42/changelog.txt, packages/addons/service/tvheadend42/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk, packages/audio/speex/package.mk, packages/multimedia/aom/package.mk, packages/multimedia/libhdhomerun/package.mk
This updates 3 add-ons, as they have dependencies at each other I bump them all together in one pr.
- adds AOM -> AV1 codec @lrusak might have a look if this is okay`ish for the moment (also the location of the package)
- adds Emby script for easy manual upgrade from SSH @awiouy -> this is could kill an emby install if emby changes something significantly at their code so this is NOT save for an gui button !
- updated packages
=> update: Tvh, Emby and ffmpeg-tools

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
By routing the x86, Wetek Play and Wetek Core power buttons through eventlircd it's impossible to configure systemd-logind to use them as eventlircd is grabbing the input.
OTOH routing the power button through eventlircd is not needed as Kodi will happily use the power button's input event device.
I've successfully tested this on Generic/x86_64 but can't test on WP or WC. Would be great if someone could verify if this works - ping @codesnake 
I also tested with the gpio-shutdown overlay on RPi, which creates a power button input device that's not run through eventlircd, and Kodi picked it up nicely as well so I'm rather confident the change should work on WP/WC.
Note: In my tests I also had the Kodi bump PR #2654 with the switch to libinput applied, could be that this PR depends on it
=> eventlircd: don't grab power buttons

scripts/image
Found this small typo when I realized that the noobs tarballs are failing to create:
```
Creating "noobs" release tarball...
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
Makefile:15: recipe for target 'noobs' failed
make: *** [noobs] Error 2
```
=> scripts/image: fix noobs tarball

packages/security/openssl/package.mk
If host has `libssl-dev` installed openssl includes wrong files.
Problem should exist for a long time already and only came up recently because Ubuntu 18.04 (other distros likely too) includes openssl 1.1.x and we are still at 1.0.x (1.1 and 1.0 are incompatible to each other).
This needs an complete rebuild.
fix was found by @ksooo , tx !
=> openssl: do not include from host

packages/security/openssl/package.mk
use absolute toolchain path for the prefix, in the host build.
The actual solution is installed under completely wrong path, and the local openssl environment is used. 
@ksooo is this working for you?
@CvH ping
build tested for Generic on Debian Stretch with and without libssl-dev.
=> openssl: fix host build

scripts/image
This PR fixes missing partition labels after #2730
=> scripts/image: pass BOOTLABEL and DISKLABEL to mkimage

packages/network/libnl/package.mk
fixes network-tools add-on
libnl: update to 3.4.0
fixes
```
BUILD    iw (target)
TOOLCHAIN    make (auto-detect)
Executing (target): make 
CC   iw.o
...
CC   iw
/builddir/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/lib/libnl-3.a(utils.o):utils.c:function nl_prob2int: error: undefined reference to 'rint'
```
=> network-tools add-on buildfix

packages/audio/soxr/package.mk
This prevents soxr getting a dependency on libavutil/libavcodec
and fixes pulseaudio build failures on ARM.
=> soxr: don't create libavutil dependency on ARM

packages/security/nss/package.mk
- warnings added with gcc8 and not needed, after last update of nss
build test on RPi2
=> nss: drop supression of warnings

packages/graphics/bcm2835-driver/package.mk, packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk, packages/linux/package.mk, packages/network/wireless-regdb/package.mk, packages/tools/bcm2835-bootloader/package.mk
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.44
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.45 (skipped)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.46 (skipped)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.47 (skipped)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.48
=> linux: update to linux-4.14.48

packages/x11/driver/xf86-video-nvidia-legacy/package.mk
Announcement: http://www.nvidia.com/Download/driverResults.aspx/135161/en-us
* Added support for X.Org xserver ABI 24 (xorg-server 1.20).
=> xf86-video-nvidia-legacy: update to xf86-video-nvidia-legacy-340.107

projects/Amlogic/packages/device-trees-amlogic/package.mk
solves the problem to build `linux:target` for LePotato
clean build for LePotato was ok.
=> device-tree-amlogic: add LePotato dts files to EXTRA_TREE

packages/graphics/kmscube/package.mk
A nice test utility used often by the drm/kms people.
not currently dependent on anything so you either have to add
ADDITIONAL_PACKAGES="kmscube" to your build options or scp the binary over to you install.
=> kmscube: add package

config/functions, packages/graphics/mesa/package.mk, packages/graphics/mesa/patches/mesa-0001-only-build-vl-winsys-dri-with-x11.patch, packages/lang/llvm/package.mk, packages/python/devel/Mako/package.mk, packages/python/devel/MarkupSafe/package.mk
This should be tested on all mesa platforms before merging. I only build tested for a couple platforms that I test with.
@evelikov would you mind having a look over?
I was forced to update to 18.1.0 because I couldn't enable EGL with only gallium drivers present in 18.0.x
=> mesa: change to use meson and update

packages/sysutils/busybox/scripts/init
This fixes updating on amlogic (Wetek) android bootloader devices.
the android bootloader hardcodes BOOT_IMAGE=kernel.img so we cannot add a leading `/` to it.
This change was really ugly anyways :smile:
=> fix updating on android bootloader devices

packages/network/iptables/config/README
iptables-save and ip6tables-save dumps rules to stdout and not in file directly.
=> iptables: fix README for saving rules

config/optimize, packages/lang/gcc/package.mk
Builds are currently creating both styles of hash table in the ELF
header. Only one style of table is necessary, and the GNU one is
more performant for lookups. Eliminating the SysV style hash table
trims ~450kb.
Note that if MIPS is ever added as a supported architecture, it
does not support hash-style=gnu at this time.
Compiled & tested for RPi3.
Signed-off-by: Ian Leonard <antonlacon@gmail.com>
=> build: only use gnu-style hash table in binaries

packages/sysutils/busybox/scripts/init
Better fix for #2767 
Some systems, eg. Amlogic, use BOOT_IMAGE=kernel.img, while others (eg. Generic,
Rockchip, RPi) will use (or have used) BOOT_IMAGE=/KERNEL or BOOT_IMAGE=/kernel.img. We could change this in new installations but we still have to support legacy installations that are upgrading, so we'll always have a mixture of with-slash and without-slash regardless of what we do with BOOT_IMAGE from here onwards.
With this change we no longer care whether the leading / is specified - both forms should now work reliably.
Since the original change (https://github.com/LibreELEC/LibreELEC.tv/pull/2689/commits/01a87ad78870f81c41c876959e803e970cb014a1) broke Amlogic, upgrades, can an Amlogic builder confirm this PR now restores normal upgrade functionality before we merge this.
=> init: strip leading / from BOOT_IMAGE & DISK_IMAGE, normalising for all projects

packages/sysutils/ntfs-3g_ntfsprogs/patches/ntfs-3g_ntfsprogs-001-fix-mounting-after-Win10-Creators-Update.patch
See forum: https://forum.libreelec.tv/thread/10888-external-hard-drives-no-longer-mount/?postID=94104#post94104
=> ntfs-3g_ntfsprogs: fix mount problem caused by Windows 10 Creators Update

packages/compress/zstd/package.mk
https://github.com/facebook/zstd/releases/tag/v1.3.4 - faster everything.
I'm not sure anyone is using LibreELEC with `zstd` yet, but no harm in keeping up to date.
=> zstd: update to zstd-1.3.4

packages/mediacenter/kodi/scripts/kodi.sh
When stopping kodi the kodi.service always enters failed state even on successful exit.
Filter the [powerdown/restartapp/reboot exit codes](https://github.com/xbmc/xbmc/blob/195491e14f4dfafed2dc1b11a851dcf5b66ff9b3/xbmc/XBApplicationEx.h#L30-L32) to reduce log spam.
=> kodi.sh: return zero on succesful exit

packages/multimedia/libbluray/package.mk, packages/multimedia/libbluray/patches/libbluray-01-bump_to_Nevcairiel_vL20170904.patch, packages/multimedia/libbluray/patches/libbluray-02-install-extra-MVC-headers.patch
Similar to #2417 (which I suggest this replaces), this PR fixes the licence, bumps the version and rebases the `L20170904` 3D MVC patch from http://git.1f0.de/gitweb?p=libbluray.git;a=summary;js=1
From the forum, confirmation that UHD support is now working with this PR:
https://forum.kodi.tv/showthread.php?tid=298462&pid=2744919#pid2744919
https://forum.kodi.tv/showthread.php?tid=298462&pid=2745004#pid2745004
However resuming UHD playback may be a problem, which is under investigation.
This needs further testing on RPi with 3D playback - my own testing didn't reveal any issues.
=> libbluray: bump to 1.0.2

config/path, config/show_config, packages/lang/dash/package.mk
This has been discussed on Slack, so I did some investigating (prompted by @cvh) to see what the actual benefit is using `dash`, this PR is mainly to document those results assuming this isn't accepted/merged.
----
This PR adds the `dash` package to the toolchain, and uses it during `configure` by adding `CONFIG_SHELL=$TOOLCHAIN/bin/dash` (unless another shell is already set).
I ran some test builds on an 8-core 4GHz Intel machine, Ubuntu 16.04.
The default system shell for Ubuntu is `/bin/dash` 0.58.2, but the default user shell is `/bin/bash`, so by default `configure` will use `/bin/bash` not `/bin/dash`.
@cvh determined there is a performance improvement in `dash` 0.5.10.2 compared with 0.5.8-2, so I've included timings for the stock `/bin/dash` and `/bin/bash`.
Build times …
=> dash: add package, configure as default CONFIG_SHELL [RFC]

config/functions
Storing the cache in an exported environment variable can
result in build failures if the cache exceeds the MAX_ARG_STRLEN
limit (128k on linux) which can be triggered by building in a
rather deeply nested directory.
See also https://github.com/LibreELEC/LibreELEC.tv/pull/2808#issuecomment-401564613
=> config/functions: store package caches in build dir

packages/graphics/mesa/package.mk
see: https://cgit.freedesktop.org/mesa/mesa/tree/meson.build#n553
when doing an intel only build you will come across this issue.
=> mesa: only build va tracker if using a gallium driver that uses it

packages/debug/valgrind/patches/valgrind-0001-enable-armv8.patch
otherwise when building a 64/32 split build you see
```
checking host system type... armv8a-libreelec-linux-gnueabi
checking for a supported CPU... no (armv8a)
configure: error: Unsupported host architecture. Sorry
```
=> valgrind: add patch to enable armv8

packages/addons/driver/sapphire/package.mk
The kernel module needs to be built with kernel_make
Build-tested for RPi2 (kernel 4.14) and Generic (kernel 4.18-rc2)
=> sapphire: fix build

packages/mediacenter/LibreELEC-settings/package.mk
This bumps the settings add-on to include support for opting out of stats collection after #2708 and drops the CPU (64/32 bit) detection flag which is obsolete since we dropped Generic i386 images in OE 5.0. The idea of sending useful flags back has been adapted to detect GPU type (Generic) or board revision (RPi) which will be used to support upcoming project decisions to continue or discontinue support for some older hardware in LE 10.0. Collecting those stats is essential as it allows the team to make support decisions based on hard facts not personal hunches/opinions.
=> settings: bump LibreELEC-settings to pick-up changes

scripts/image
Part of https://github.com/LibreELEC/service.libreelec.settings/pull/100 depends on this.
Updated: 
If `BUILDER_NAME` is present in `/etc/os-release`, eg. `BUILDER_NAME="Milhouse"`, this value will be included in the url when performing the update check, allowing stats to be aggregated by author.
If `BUILDER_VERSION` is present in `/etc/os-release`, eg. `BUILDER_VERSION=#0601`, this value will be included in the url instead of the normal `devel-20180601153228-g89fe123` version that would otherwise be used. This allows stats for the builder to be grouped by a version identifier they are more familiar with (or prefer to use). When using a custom `BUILDER_VERSION` it's important to include a unique `BUILDER_NAME` in order to differentiate build statistics with the same version identifier but …
=> scripts/image: add BUILDER_NAME, BUILDER_VERSION support

packages/network/bluez/package.mk
Tested in mainline branches I've been using recently with no obvious ill effects, but it would be good to pick into @MilhouseVH releases for a few days to prove on a larger audience before merging.
=> bluez: bump version to 5.50

packages/security/openssl/package.mk, packages/security/openssl/scripts/openssl-config, packages/security/openssl/system.d/openssl-config.service, packages/web/curl/package.mk
This should allow users to append their own self-signed CA.
https://forum.libreelec.tv/thread/12789-adding-own-certs-to-connect-via-webdavs-sftp-again
=> openssl: generate cacert.pem from system and user CA

packages/mediacenter/kodi/config/appliance.xml
We want to get more visibility for retroplayer so let's enable games by default.
The only reason kodi doesn't do this is because it doesn't have the sense of a
binary add-on repo. LibreELEC is special in that we have had this ability forever.
We also want to disable rewind by default because it makes low powered devices
suffer in performance. It also isn't exposed in a manner that makes it easy to use yet.
=> kodi: enable games and disable rewind by default

packages/linux/package.mk
@lrusak that's the same version as in your #2828 PR
I've been using that version the last couple of days and it's been working fine.
Would be nice to get the fixes in soonish
=> Linux (RPi) update to 4.14.54+ with lan78xx and vc4 fixes

packages/mediacenter/kodi-binary-addons/game.libretro.vram-test/package.mk
fixes the `game.libretro.vram.test` -> `game.libretro.vram-test`
=> game.libretro.vram-test: update to 92e1146

packages/lang/gcc-linaro-aarch64-elf/package.mk, packages/lang/gcc-linaro-aarch64-linux-gnu/package.mk, packages/lang/gcc-linaro-arm-eabi/package.mk, packages/lang/gcc-linaro-arm-linux-gnueabihf/package.mk
This PR updates gcc-linaro toolchains to latest `4.9.4-2017.01` and `7.3.1-2018.05`.
I have tested this on Rock64 (`gcc-linaro-aarch64-linux-gnu`) and Tinker Board S (`gcc-linaro-arm-linux-gnueabihf`) without any issues.
This needs testing on Amlogic before going in.
=>  gcc-linaro: update to latest version

packages/emulation/libretro-mame/package.mk
Resolves issue with incorrect PKG_SHA256.
=> libretro-mame: update to libretro-mame-c816514

packages/devel/glibc/package.mk
partial revert of #2763 
`busybox:init` has problems with the drop of `obsolete-rpc`. The result was, no nfs mounts was possible from the initramfs.
Actual, i hadn't any idea, why it happens and howto fix it.
So rollback, for now.
ping @MilhouseVH 
PS: `busybox:target` is working fine, with nfs...
=> busybox: temporary fix for nfs based boot

scripts/create_addon
from 
```
$ cat 9.0-Generic-x86_64-driver.dvb.hdhomerun-9.0.101.zip.sha256
617e636517c149e67ddaee4bdef0883f17aa7de36eb96d65b653f08d26ebfe6d
```
to 
```
$ cat 9.0-Generic-x86_64-driver.dvb.hdhomerun-9.0.101.zip.sha256
617e636517c149e67ddaee4bdef0883f17aa7de36eb96d65b653f08d26ebfe6d  9.0-Generic-x86_64-driver.dvb.hdhomerun-9.0.101.zip
```
creates proper sha256 file instead just the hash
=> create_addon: change jenkins sha256 files

scripts/create_addon
1) Use POSIX compliant operators (ie. `=` not `==`, consistent with existing code), and numeric operators when comparing numeric values
2) Ignore `$SHELL` as it can't be trusted - for example when `SHELL=/bin/sh` is set in `/etc/crontab` (as is the default on Ubuntu), and an add-on is built using a cron job, `scripts/create_addon` will fail:
```
Building addon: tvheadend42 for pi1...
Cleaning tvheadend42                         RPi/arm/devel
/bin/sh: 1: [: unexpected operator
/bin/sh: 2: ./config/options: [[: not found
/bin/sh: 372: config/functions: Syntax error: "(" unexpected (expecting "fi")
ERROR: 'tvheadend42' matches nothing...
for more informations type: ./scripts/create_addon --help
```
Ping @InuSasha
=> scripts/create_addon: minor cleanup

packages/network/bluez/patches/bluez-12-fix-obexd-after-5_50.patch
Bluez 5.50 includes https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=bff0c2ae9f0ba93efe387bbec603b4ddbc7ce4ce so obxed is now (correctly) missing from the image. If we build bluez with `--enable-obexd` we incur a whole pile of obxed dependencies for obex use-cases on a mobile device (iCal and message sync etc.) that are not relevant to LibreELEC. It's not possible to revert due to subsequent and ongoing changes that conflict, but this restores the previous loophole that allows obexd to build without the dependencies.
=> bluez: fix obexd inclusion after 5.50 bump

packages/network/samba/system.d.opt/nmbd.service, packages/network/samba/system.d.opt/smbd.service
Also cleanup interdependencies, ensuring:
```
samba-config.service
|
+-- nmbd.service
|
+-- smbd.service
```
=> samba: make services depend on network-online.target

packages/audio/pulseaudio/system.d/pulseaudio.service
This change gets rid of the `Running in system mode, ...` flannel.
@lrusak, @5schatten - any concerns?
Before:
```
NUC:~ # journalctl -a  _SYSTEMD_UNIT=pulseaudio.service
-- Logs begin at Fri 2018-08-03 21:20:15 BST, end at Fri 2018-08-03 21:49:46 BST. --
Aug 03 21:20:16 NUC pulseaudio[289]: W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set.
Aug 03 21:20:16 NUC pulseaudio[289]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Aug 03 21:20:16 NUC pulseaudio[289]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
Aug 03 21:20:16 NUC pulseaudio[289]: N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time.
Aug 03 21:20:16 NUC pulseaudio[289]: W: [pulseaudio] main.c: Home …
```
=> pulseaudio: silence some warnings

packages/addons/service/net-snmp/changelog.txt, packages/addons/service/net-snmp/package.mk, packages/addons/service/proftpd/changelog.txt, packages/addons/service/proftpd/package.mk, packages/network/openvpn/package.mk
proftpd to 1.3.6
net-snmp to 5.8
openvpn to 2.4.6
all build tested Generic & RPi2
proftpd and net-snmp functional tested on Generic
=> proftpd, net-snmp, openvpn: updates to recent version

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.8.4.html
```
o  CVE-2018-1139  (Weak authentication protocol allowed.)
o  CVE-2018-1140  (Denial of Service Attack on DNS and LDAP server.)
o  CVE-2018-10858 (Insufficient input validation on client directory
listing in libsmbclient.)
o  CVE-2018-10918 (Denial of Service Attack on AD DC DRSUAPI server.)
o  CVE-2018-10919 (Confidential attribute disclosure from the AD LDAP
server.)
```
=> samba: update to samba-4.8.4

packages/graphics/bcm2835-driver/package.mk, packages/linux-drivers/RTL8812AU/package.mk, packages/linux/package.mk, packages/linux/patches/raspberrypi/linux-999-improve-ir-timeout-handling.patch, packages/tools/bcm2835-bootloader/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.55
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.56
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.57
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.58
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.59
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.60
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.61
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.62
Includes POE HAT fan suppport.
=> linux (RPi): update to linux-4.14.62

packages/mediacenter/kodi/scripts/cputemp
- Support amdgpu devices.
- Remove coretemp from GPU case statement. Avoids showing CPU temperature on systems with Intel CPU and dedicated (i.e. AMD) GPU.
=> cputemp: add amdgpu, prefer dedicated gpu

distributions/LibreELEC/options, packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml
K18 logs `WARNING: Repository LibreELEC Add-ons uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!` unless the addon repo supports either HTTPS or uses SHA256 verification instead of MD5. This change implements both. To avoid path issues in existing addon databases we also need to increment the repo addon version. Next time around we should avoid bumping the repo addon version until we move from beta to release (as with the build-system repo version).
=> kodi: use HTTPS and SHA256 for LibreELEC repo addons

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/pull/9
=> brcmfmac_sdio-firmware-rpi: update to brcmfmac_sdio-firmware-rpi-8c1e2bff

distributions/LibreELEC/options, packages/mediacenter/kodi/package.mk, projects/RPi/options
Now we only build RPi patches in branches, never master.
Anyone wanting to build with RPi patches in master can add the `raspberrypi` tag/sha and switch to using the `raspberrypi` repo.
Switch to `raspberrypi` after we branch for `libreelec-9.0`.
=> kodi: add option to use RPi vendor repo

packages/compress/zstd/package.mk, packages/graphics/libpng/package.mk, packages/security/libgcrypt/package.mk
This updates zstd to 1.3.5, libgcrypt to 1.8.3, and libpng to 1.6.35. All are built test for raspi3. zstd and libpng have been tested in deployment. Libgcrypt, looking at what depends on it, I don't have appropriate media to test it beyond building.
=> zstd, libgcrypt, libpng: package updates

scripts/mkimage
This enables the local console (CTRL+ALT+F3) in run mode. For some unknown to the mists of time reason it's enabled for all the other modes, but not run.
=> mkimage: support tty in run mode

packages/mediacenter/LibreELEC-settings/package.mk
This bumps settings after https://github.com/LibreELEC/service.libreelec.settings/pull/102 and cleans up some cruft that's been commented out for aeons.
=> settings: update to 080f0dc

packages/devel/bison/package.mk, packages/devel/m4/patches/fix-compilation-with-glibc-2.28.patch, packages/sysutils/squashfs/patches/fix-compilation-issue.patch, packages/tools/populatefs/patches/fix-compilation-issue.patch
There are 2 issues:
- gnulib included in m4 and bison doesn't compile
- missing definition of some macros like minor, major, etc. (https://sourceware.org/bugzilla/show_bug.cgi?id=19239)
Changes shouldn't affect building with older glibc, but I would like someone to confirm that.
=> Fix compilation issues with glibc 2.28 on host

scripts/create_addon
on special wish of @cvh
`addon-summary.log`
```
success: audioencoder.flac
failed: audioencoder.lame
success: audioencoder.vorbis
success: audioencoder.wav
```
=> create_addon now also writes a summary when log writing is used.

packages/linux/package.mk
Building the kernel separately, after the modules have been built, has
the side-effect that modpost (called from scripts/link-vmlinux.sh in
the kernel tree) generates a Module.symvers files containing only the
in-kernel symbols.
${MAKE} -f "${srctree}/scripts/Makefile.modpost" vmlinux.o
This causes undefined symbol warnings when building external
modules/drivers and these drivers reference symbols from modules.
eg when building RTL8812AU for RPi2:
WARNING: "cfg80211_put_bss" [.../RTL8812AU-ff2f1dd/8812au.ko] undefined!
...
When building the kernel in the usual way (by just running "make")
this problem does not occur because the default kernel build target
includes "modules", which is built after the kernel. So Modules.symvers
generated from link-kernel.sh will later be replaced by the …
=> linux: fix Module.symvers generation

projects/RPi/devices/Slice/config/slice-overlay.dts, projects/RPi/devices/Slice/config/ws2812-overlay.dts, projects/RPi/devices/Slice3/config/slice-overlay.dts, projects/RPi/devices/Slice3/config/ws2812-overlay.dts
Note: this is mostly untested as I don't have any Slice hardware. Do not merge until we get some positive runtime test results.
I only tested building LE for the Slice3 device and applying the slice and ws2812 overlays with fdtoverlay to the bcm2708-rpi-cm.dtb and bcm2710-rpi-cm3.dtb DTBs.
I removed the ws2812 specific bits from the slice-overlay as they are also in the ws2812-overlay
@chewitt could you test please?
=> Slice/Slice3: fix device tree overlays

scripts/extract
GNU tar can automatically detect the compression format based on
the file name since at least 2006. So just use "tar xf" to extract
all tarballs and drop the redundant cases.
GNU tar can also strip the top level directory from the archive
which allows us to extract it to the directory wanted by the
build system ($PKG_NAME-$PKG_VERSION), so packages don't need to
specify PKG_SOURCE_DIR if the top level dir from that and scripts/unpack
doesn't need to rename the directory.
If PKG_SOURCE_DIR is not set the top level dir is automatically
stripped from the archive and extracted to $BUILD/$PKG_NAME-$PKG_VERSION
If PKG_SOURCE_DIR is set, scripts/extract behaviour is unchanged.
=> scripts/extract: improve tar file handling

scripts/image
The compression methods used by mksquashfs take compression levels, which are trade offs between time spent compression and size of the compressed file. This makes use of them for lzo and zstd. For lzo, it's a ~40kb size savings, and for zstd it's about 500kb size savings.
I also tested gzip, where the size reduction was 4kb, and xz where size reduction was 8kb. If those reductions should be included, let me know. gzip is a simple -o squashfs_compression == gzip to the lzo test, while xz requires exporting a variable.
=> scripts/image: use maximum lzo and zstd compression level for images

packages/linux/package.mk, packages/mediacenter/kodi/package.mk
PKG_SOURCE_DIR is no longer required since commit 1c5d050bc026ae387abf4c367c071601979f4842
Add PKG_SOURCE_NAME so that the kernel and kodi source files stored
in sources include the kernel/kodi variant in their file name (eg linux-amlogic-3.10, linux-raspberrypi, ...).
Currently a lot of files are named linux-GITHASH.tar.gz / kodi-GITHASH.tar.gz.
When PKG_SOURCE_NAME is set this will change to eg
linux-raspberrypi-GITHASH.tar.gz, linux-amlogic-3.10-GITHASH.tar.gz
etc and it's easer for humans to detect older versions and clean
up the sources dir.
=> linux, kodi: remove PKG_SOURCE_DIR, add PKG_SOURCE_NAME

config/functions, packages/lang/gcc/package.mk, packages/mediacenter/kodi/patches/kodi-995.01-pr14354_wrapper_toolchain_nm.patch
When building LibreELEC on a Ubuntu 16.04 build host, playing DVDs from VIDEO_TS folders with Kodi ​fails. This is caused by an empty wrapper.def file generated during and libdvdnav-x86_64-linux.so not linked correctly. 
When executing the wrapper.def custom target nm fails with
```
[17/1519] cd /home/m/tools/libreelec/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/kodi-f08d8686e96edcfbe065d4e5094ab6221da057b9/.x86_64-libreelec-linux-gnu/build/cores/dll-loader/exports && nm /home/m/tools/libreelec/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/kodi-f08d8686e96edcfbe065d4e5094ab6221da057b9/.x86_64-libreelec-linux-gnu/build/cores/dll-loader/exports/CMakeFiles/wrapper.dir/wrapper.c.o | grep __wrap | awk '{ printf ( "%s ", $3 ) }' | sed "s/___wrap_/__wrap_/g" | sed …
```
=> Kodi: use toolchain nm for generating wrapper.def

packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/patches/vdr-plugin-xmltv2vdr-02_gcc721_fixes.patch
fixes
```
event.cpp:531:5: error: 'string' was not declared in this scope
string si=sql_insert;
^~~~~~
event.cpp:531:5: note: suggested alternatives:
In file included from /builddir/toolchain/armv7ve-libreelec-linux-gnueabi/include/c++/8.2.0/string:39,
from /builddir/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/pcrecpp.h:333,
from event.cpp:12:
/builddir/toolchain/armv7ve-libreelec-linux-gnueabi/include/c++/8.2.0/bits/stringfwd.h:74:33: note:   'std::string'
typedef basic_string<char>    string;
^~~~~~
/builddir/toolchain/armv7ve-libreelec-linux-gnueabi/include/c++/8.2.0/bits/stringfwd.h:74:33: note:   'std::string'
event.cpp:533:48: error: 'si' was not declared in this scope
ireps=pcrecpp::RE("'").GlobalReplace("''",&si);
^~
event.cpp:533:48: note: suggested alternative: …
```
=> vdr-plugin-xmltv2vdr: add buildfix patch

packages/addons/service/inadyn/changelog.txt, packages/addons/service/inadyn/package.mk, packages/addons/service/inadyn/source/resources/settings.xml
- Update to 2.4
- Add custom option for defining DDNS services which
are not natively supported by inadyn
Signed-off-by: Miikka Tuppurainen <miikka75@gmail.com>
=> Inadyn: Update to 2.4

distributions/LibreELEC/options, packages/sysutils/v4l-utils/package.mk, projects/Amlogic/devices/Odroid_C2/options, projects/Amlogic/devices/WeTek_Hub/options, projects/Amlogic/devices/WeTek_Play_2/options
This has been on my TODO list for quite a long time:
I've cleaned up the list of IR remotes that are supported in LibreELEC out-of-the-box and removed broken tables (hp_mce and zotac_ad10 won't work as is with current kernel) and rarely used ones (like cubox-i) from the default config.
I still kept the (semi-)broken tables, we can clean them up later.
The default setup is now very simple: LE supports (Microsoft) MCE remotes, the Xbox one and Xbox 360 remotes out of the box on all devices.
Projects/devices can extend or override the list of OOTB remotes as they wish, for simplicity I suggest to just add the remote that comes with the device to the list of default remotes.
Then people can use an MCE (compatible) remote on any device if they prefer. Or they can use the remote that came eg …
=> Cleanup OOTB IR remote support and make it configurable

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
This fixes issues with latest libwidevine (API version 10)
=> inputstream.adaptive: update to 2.2.27

packages/multimedia/ffmpeg/package.mk
This cleans up some of ffmpeg's package.mk. 
disable-{ffprobe,ffplay} and enable-ffmpeg get ignored because of disable-programs later on.
disable-{w32threads,dxva2} get ignored because of target-os=linux.
Hardcoded tables are a start up speed optimization in exchange for an increased sizeon disk  of libavcodec. Its impact is negligible due to the encode/decode cycle. Libavcodec reduces in size by 1.5MB with the tables disabled.
Also noticed, but not addressed here, is the usage of --enable-gpl and --enable-nonfree. Mixing these has ffmpeg's configure script finish with: `License: nonfree and unredistributable` Enable-nonfree appears to be due to the use of mixing enable-gpl and enable-openssl. Options seem to be using gnutls, using libressl (libtls) or dropping enable-openssl (and losing …
=> ffmpeg: cleanup

packages/multimedia/SDL2/package.mk
Bumb SDL2 version to 2.0.8 and added CMAKE toolchain. Someone should look over it in case I missed an option while updating the toolchain opts. The CMAKE opts are a 1:1 conversion according to the configure opts.
I build it as shared lib for my fork but static libs (-DSDL_STATIC=ON & -DSDL_SHARED=OFF) should be suitable for LE upstream.
=> SDL2: update to v2.0.8 / added cmake toolchain opts

scripts/get_archive, tools/distro-tool
Issue discussed [here](https://savannah.gnu.org/bugs/?51181), although doesn't actually resolve it as latest 1.19.5 still has the same issue, in which case I'm not sure if this is a regression/bug in `wget` or new/expected behaviour.
To reproduce:
1. Create `/tmp/test.sh`
```
#!/bin/bash
wget --timeout=30 --tries=3 --passive-ftp --no-check-certificate -c -O /tmp/aom.tar.gz "http://repo.or.cz/aom.git/snapshot/1b0e7dc4ac4b50f245dacc1e2362e50b7b2d1860.tar.gz"
```
2.  Run `/tmp/test.sh` as a "background" process
```
bash /tmp/test.sh &
```
Result: instead of the output from `wget` being sent to the console, it is sent instead to `wget-log` in the current directory. And if `wget-log` exists, then `wget-log.1` is created, then `wget-log.2` etc. etc.
Adding `--output-file=-` overrides the …
=> scripts/get_archive, tools-distro-tool: fix wget redirection issue when wget running in background

config/options, scripts/install
We automatically install config files from the global package but completely ignore project and device specific equivalents.
These files also need to be considered when determining the LINUX_DEPENDS - any change to a conf file should rebuild linux.
Inspired by #2963.
I've quickly build tested this on RPi/RPi2/Generic and don't see any difference in the before/after images.
=> buildsystem: better support for project and device config files

packages/sysutils/busybox/scripts/fs-resize
In Amlogic mainline images (and probably others) the `fs-resize` script attempts to fix GPT headers with sgdisk even though the SD card uses an MBR scheme. This creates a ~2 min delay until sgdisk fails/time-out and the script continues. The error can be see if you uncomment the command output redirect to /dev/null:
I'm not sure why long delay isn't seen with other MBR images (older kernel codebase etc.) but this change detects the partition scheme (MBR or GPT) and skips sgdisk fixup unless a GPT scheme is being used. Initial boot and resize now takes ~20 seconds again.
=> busybox: don't fix GPT tables when partition scheme is MBR

packages/lang/Python2/package.mk, packages/lang/Python3/package.mk
Thanks [@vpeter](https://github.com/LibreELEC/LibreELEC.tv/commit/1821a2078db4e950ca63cc2d2c2c3765cc81cecc#commitcomment-30460104).
The reminder for Python2 is unlikely to be required, but doesn't do any harm.
The only consequence of this snafu is that reindent.py is installed incorrectly in $TOOLCHAIN/lib - no big deal, as nothing uses it.
=> Pythons: bump internal Python3 version, add reminders

packages/python/devel/meson/package.mk
After updating Python to 3.7.0 we need to update Meson too.
https://docs.python.org/3.8/library/exceptions.html#StopIteration
https://github.com/mesonbuild/meson/issues/3821
=> meson: update to 0.47.2

scripts/get_archive
really just an minor change to make copying of the hash easier
click at the gifs for big (fantasy hash values !)
before the change you also copy the `,` at double click at the hash
fixed
=> scripts/get: make hash output easier to copy

scripts/get_archive
=> scripts/get: wget uses bar indicators

config/options, scripts/get_archive
fixes https://github.com/LibreELEC/LibreELEC.tv/pull/2979#issuecomment-423802948 (accidentally dropped the verbose variable) and added the possibility to use VERBOSE=yes/no from the commandline
`PROJECT=RPi DEVICE=RPi2 ARCH=arm VERBOSE=no scripts/abc def`
=> fixes $VERBOSE usage

scripts/checkdeps
Tested on a branch not containing #2970 and there heimdal is configured properly, so it seems that the host libncurses package is properly detected. Thanks @MilhouseVH for pointing to this approach in the other PR.
=> supporting sabayon host distro, quite straightforward, as a flavour of gentoo

packages/emulation/libretro-genplus/package.mk
Fixes a bus error, the makefile already sets this flag for RPi based systems but not for other arm platforms like the AML S905 chips.
See https://github.com/ekeeke/Genesis-Plus-GX/issues/158 for further details.
=> libretro-genplus: bus error fix for non RPi arm based systems

packages/addons/addon-depends/comskip/package.mk
fixes 
```
libavcodec/omx.c:185: error: undefined reference to 'dlclose'
libavcodec/omx.c:93: error: undefined reference to 'dlsym'
libavcodec/omx.c:101: error: undefined reference to 'dlopen'
libavcodec/omx.c:106: error: undefined reference to 'dlsym'
libavcodec/omx.c:109: error: undefined reference to 'dlclose'
libavcodec/omx.c:114: error: undefined reference to 'dlopen'
libavcodec/omx.c:130: error: undefined reference to 'dlclose'
libavcodec/omx.c:133: error: undefined reference to 'dlclose'
```
=> comskip: fix build

packages/network/samba/scripts/smbd-config, packages/network/samba/system.d/samba-config.service, packages/sysutils/systemd/scripts/usercache-setup
samba-config.service runs before systemd-tmpfiles-setup.service:
On first boot the samba-config script creates a file /storage/.cache/services.  systemd-tmpfiles-setup.service is not able any more to create the same directory name. With the directory missing no LE service can be configured. More worse the avahi and cron services do not even start.
Journal: http://ix.io/1neo
The first commit delays the samba-config after basic.target to avoid the fault at new installations and extends usercache-setup to detect and fix a damaged system.
The second commit removes in place modification of smb.conf because I'm afraid of races.
=>  samba-config.service: fix destroying .cache structure 

scripts/image
Squashfs allows configuring a blocksize between 4KB and 1MB. The default is
128KB. Increasing blocksize, in general, increases compression efficiency
at a cost of increased access time. Using 256KB for a blocksize appears to be
a sweet spot balancing the two.
Gzip decreases image by ~700KB.
Lzo decreases image by ~850KB.
Zstd decreaes image by ~2.5MB.
Benchmarking device is an RPi3 running an AArch32 build of LE-9 git from 9/19/18. Test data is a LE9 git filesystem (the /etc and /usr directories - 303MB) from the end of August; the same used for compression level testing. Filename is squashfs-compression method-compression level-blocksize. UTIME is access time to decompress and dump the image to /dev/null.
Filename| Size| Ratio| UTIME
:-----:|:-----:|:-----:|:-----: …
=> scripts/image: use 256kb blocksize for squashfs images

packages/linux-drivers/slice-drivers/package.mk
This fixes build issues on kernel 4.17 and newer
=> slice-drivers: update to 8a2bdcd

scripts/image
This change simplifies SBC image filenames by only appending the board-type suffix when the image file is one of multiple u-boot variants, e.g. `LibreELEC-RK3399.arm-8.90.006-rockpro64.img.gz` will remain the same. If the device has its own u-boot variant and entry in `scripts/uboot-helper` the name is shortened, e.g. `LibreELEC-TinkerBoard.arm-8.90.006-rk3288.img.gz` becomes shortened to `LibreELEC-TinkerBoard.arm-8.90.006.img.gz`. To work the scripts/uboot-helper entries just need to match the buildsystem `$DEVICE` name.
=> u-boot: only append suffix when creating multiple u-boot variants

packages/emulation/libretro-pcsx-rearmed/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk
on lowend generic systems better than beetle-psx / added correct GIT version
If you have a well performing generic system beetle-psx is the PSX emulator of choice but if you struggle to run games at full speed PCSX_reARMed could be a better choice and at least an option. It has less features but is less demanding too.
=> libretro-pcsx-rearmed: set PKG_ARCH to any since PCSX_reARMed performs

packages/emulation/libretro-pcsx-rearmed/package.mk
make_target() uses $TARGET_ARCH which should be x86_64 for generic builds
=> libretro-pcsx-rearmed: target ARCH is x86_64 not x86-64

packages/debug/libva-utils/package.mk, packages/multimedia/libva/package.mk
As suggested by fritsch, we should bump libva/libva-utils to 2.3.0
It adds tone mapping support via libva
First time bumping a package.mk, so please bear with me ;)
The SHA seems to be correct and the packages build fine. That's what I've tested so far
=> graphics: update libva/libva-utils to 2.3.0

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/scripts/kodi-remote
This script could easily extended, not sure if something important/useful is missing. 
It works ootb with default Kodi settings (ssh enabled ofc).
Its partly an alternative to https://github.com/LibreELEC/LibreELEC.tv/pull/3017
=> kodi: add kodi-remote script

packages/sysutils/busybox/scripts/functions
There are two wait timers in the fs-resize script. The first shows when you shouldn't be trying to resize a full-size partition and this remains at 15s so it can be noticed. The second simply kills time after the resize and this is reduced from 15s to 5s which is long enough to be noticed but short enough to be less annoying for developers frequently testing installs :)
=> busybox: quit countdown timers on keyboard input

packages/sysutils/busybox/scripts/getedid
"getedid delete" did not work because of the use of the wrong $gpu variable output "intel" which should read "intel/amd"
=> getedid: Fixed typo in order to make "getedid delete" work again

packages/debug/valgrind/package.mk
Changes see http://valgrind.org/docs/manual/dist.news.html
build and runtime tested on RPi2
=> valgrind: update to 3.14.0

packages/x11/driver/xf86-video-nvidia/package.mk
Announcement: [410.73](https://devtalk.nvidia.com/default/topic/1043354)
No new PCI IDs this time - the "new" cards supported with this driver were already supported by 410.66.
=> xf86-video-nvidia: update to xf86-video-nvidia-410.73

packages/mediacenter/kodi/scripts/kodi-config
This allows the user to more easily configure the Kodi service without having to add entries to /storage/.config/autostart.sh which append environment variables to /run/libreelec/debug/kodi.conf etc.
This also ensures that the users settings are loaded after the standard system kodi config.
Every now and again it's sometimes necessary for users to force a specific version of GL/GLX, or some other behaviour, and this change should simplify the steps needed to achieve that.
Obviously this could result in users configuring an environment variable that results in breakage or sub-optimal performance of the Kodi service in the future, but that's something they can do today, just with more faffing about.
=> kodi: more easily support user configuration

packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk, packages/addons/addon-depends/multimedia-tools-depends/squeezelite/patches/squeezelite-01-makefile.patch, packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk
Linking (#2289) got lost on update.
There is a bug report on [forum](https://forum.libreelec.tv/thread/5887-multimedia-tools-squeezelite-missing-libraries-solved/?postID=101027#post101027).
Needs testing, I'm not using Logitech Media Server.
=> squeezelite: link instead dlopen again and update

packages/network/bluez/package.mk, packages/network/bluez/system.d/bluetooth-defaults.service, packages/network/bluez/system.d/bluetooth.service
I've had this in my Amlogic image for some time. It defaults the BT service to enabled so that users do not have to search/find and enable it manually before trying to pair devices. If there is no BT hardware present the Bluetooth connections page shows "no hardware" instead of "service disabled" so IMHO there is no real-world impact.
=> bluez: default enable bluetooth services

packages/sysutils/busybox/scripts/fs-resize, packages/sysutils/gptfdisk/package.mk, packages/sysutils/util-linux/package.mk
fs-resize running at early boot time may need minutes to complete because the kernel RNG is not initialized. 
When parted and sgdisk call uuid_generate(), util-linux libuuid implementation use a blocking getrandom() syscall. It waits until the kernel crng has collected enough entropy. Having a SSD, no network, no user input and no HW RNG this can take a long time. The behavior explains the delay seen in #2957. 
This is fixed in util-linux 2.32:
```
commit a9cf659e0508c1f56813a7d74c64f67bbc962538
Author: Carlo Caione <carlo@endlessm.com>
Date:   Mon Mar 19 10:31:07 2018 +0000
lib/randutils: Do not block on getrandom()
In Endless we have hit a problem when using 'sfdisk' on the really first
boot to automatically expand the rootfs partition. On this platform
'sfdisk' is blocking on …
```
=> Improve fs-resize, fix delay and simplify

packages/tools/u-boot/package.mk, projects/Amlogic/bootloader/mkimage, projects/Amlogic/bootloader/update.sh, projects/Amlogic/devices/KVIM/bootloader/boot.ini, projects/Amlogic/devices/KVIM2/bootloader/boot.ini, projects/Amlogic/devices/LePotato/bootloader/boot.ini, projects/Amlogic/devices/Odroid_C2/bootloader/boot.ini, projects/Amlogic/packages/u-boot/package.mk
Cross-grading (aarch64 to arm, and vice versa) is [broken](https://forum.libreelec.tv/thread/13542-how-to-integrate-driver-for-geniatech-dvb-t2-stick-into-libreelec).
Use UUIDs to avoid overriding the users choice of partition label (which may have been made to avoid a LABEL clash) or adding missing partition labels, using binaries that can't be executed.
I've not changed [platform_init](https://github.com/LibreELEC/LibreELEC.tv/blob/76ed87318661962a72cb61f3dd55efbaba709d10/projects/Amlogic/initramfs/platform_init#L32), because I'm not sure if we need it, or who uses it.
=> Amlogic/update.sh: fix issues with binary compatability using UUIDs

packages/textproc/expat/package.mk
See https://github.com/libexpat/libexpat/releases
This also allows us to drop PKG_SOURCE_DIR and the post-unpack hack
=> expat: use official release download URL

packages/mediacenter/kodi/package.mk, packages/multimedia/ffmpeg/patches/ffmpeg-99.1006-rkmppdec-continue-on-errinfo-frame.patch, packages/multimedia/ffmpeg/patches/ffmpeg-99.1007-rkmppdec-enable-mpeg2.patch, packages/multimedia/rkmpp/package.mk, packages/tools/u-boot/patches/rockchip/u-boot-0010-rk3288-tinker-enable-emmc.patch, packages/tools/u-boot/patches/rockchip/u-boot-0011-Revert-rockchip-dts-rk3328-evb-Enable-gmac2io-for-rk.patch, projects/Rockchip/README.md, projects/Rockchip/devices/MiQi/kodi/appliance.xml, projects/Rockchip/devices/TinkerBoard/README.md, projects/Rockchip/devices/TinkerBoard/kodi/appliance.xml, projects/Rockchip/patches/linux/rockchip-4.4/linux-0001-rockchip.patch, projects/Rockchip/patches/linux/rockchip-4.4/linux-0005-dts.patch
This PR updates some rockchip patches, ~~bootloader blobs,~~ rkmpp to latest version and kodi to beta 4.
Changes:
- Fix for emmc boot issue on Tinker Board S
- Possible to select YCbCr 4:2:2 or 4:4:4 output in Kodi
- YUV framebuffers is no longer clipped to 16-235/240 by Video Output Processor
- rkmppdec should now stop after 100 consecutive error frames
- Display Port disabled on RockPro64 to workaround 4K issue
- Add some dmt resolution clocks on RK3288 (2560x1440@60Hz and more)
- Fix inverted led on box-z28
Currently only runtime tested on Rock64 and Tinker Board S
=> Rockchip: package updates

config/functions, scripts/build, scripts/create_addon, scripts/extract, scripts/install, scripts/unpack
I was looking at adjusting PKG_BUILD and came across these cleanups. There shouldn't be anything exciting in here. This replaces a few places that should be using PKG_BUILD too. To ease looking it up, PKG_BUILD is defined in config/path: https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/path#L132
Tested with an RPi build.
=> buildsystem: unpacking / extracting cleanup

config/functions, config/path, packages/addons/addon-depends/cxxtools/package.mk, packages/addons/addon-depends/tntnet/package.mk, packages/addons/repository/repository.kodinerds/package.mk, packages/addons/repository/repository.linuxserver.docker/package.mk, packages/addons/script/script.config.vdr/package.mk, packages/addons/service/fd628/package.mk, packages/addons/service/touchscreen/package.mk, packages/addons/service/tvheadend42/package.mk, packages/audio/taglib/package.mk, packages/devel/ncurses/package.mk, packages/mediacenter/kodi/package.mk, packages/multimedia/SDL2/package.mk, packages/print/freetype/package.mk, packages/textproc/libxml2/package.mk, packages/textproc/libxslt/package.mk
`$SED` is generally ignored, or used incorrectly. Retire it.
Relies on PR3078.
=> treewide: retire $SED

packages/mediacenter/kodi/package.mk
This PR fixes SHA of force updated `rockchip_18.0b5-Leia` tag, old tag included `master` commits merged after `18.0b5-Leia` was taged
=> kodi: update SHA for corrected rockchip_18.0b5-Leia tag

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Currently both eventlircd and kodi try to grab input devices
which leads to a nasty race. If kodi wins the race eventlircd
can't do the keycode to lirc translation and users are left
with non-working buttons like OK.
Setting the LIBINPUT_IGNORE_DEVICE udev property for input
devices handled by eventlircd prevents the race as libinput
will then ignore these devices and kodi won't try to grab them.
Note: several users have been using `systemctl mask eventlircd` and setup custom IR keytables (changing eg KEY_OK to KEY_ENTER) to get longpress support in kodi.
This hack (which was never officiially supported) won't work any longer, instead of masking the eventlircd service people now have to override the eventlircd udev rule file, eg via
`: > /storage/.config/udev.rules.d/98-eventlircd.rules` …
=> eventlircd: prevent race with libinput / kodi

packages/devel/libcec/package.mk
@opdenkamp doesn't believe the wrapper is likely to work, see discussion: https://github.com/Pulse-Eight/libcec/issues/356#issuecomment-435987465
I'd suggest this is included in 8.90.007 due to the (potential) loss of functionality - hopefully nobody is using the Python wrapper.
=> libcec: drop python wrapper

projects/WeTek_Core/patches/kodi/kodi-100.26-hack-fix-audio.patch, projects/WeTek_Play/patches/kodi/kodi-100.26-hack-fix-audio.patch
We have a lot reports that WP1 audio is broken, this HACK makes it work again. 
This is no proper fix but there is currently nothing else available to have working audio at WP1.
It is an adapted version of https://github.com/LibreELEC/xbmc/commit/dd2255d77e5c3a819a92543de9f3ce276a522947
from https://www.kodinerds.net/index.php/Thread/62885-LE-9-auf-Wetek-Play-Ton-seltsam/?postID=483736#post483736
I have no WP1 so I can't test it at all (I ship an testimage to the forum).
=> HACK: fix audio for WP1

packages/mediacenter/kodi/config/advancedsettings.xml, packages/mediacenter/kodi/package.mk, projects/Amlogic/filesystem/usr/bin/cputemp, projects/Amlogic/filesystem/usr/bin/gputemp, projects/Amlogic/kodi/advancedsettings.xml, projects/Generic/filesystem/usr/bin/cputemp, projects/Generic/filesystem/usr/bin/gputemp, projects/Generic/kodi/advancedsettings.xml, projects/RPi/filesystem/usr/bin/cputemp, projects/RPi/filesystem/usr/bin/gputemp, projects/Rockchip/filesystem/usr/bin/cputemp, projects/Rockchip/filesystem/usr/bin/gputemp, projects/WeTek_Core/filesystem/usr/bin/cputemp, projects/WeTek_Core/filesystem/usr/bin/gputemp, projects/WeTek_Core/kodi/advancedsettings.xml, projects/WeTek_Play/filesystem/usr/bin/cputemp, projects/WeTek_Play/filesystem/usr/bin/gputemp, projects/WeTek_Play/kodi/advancedsettings.xml
1) All projects other than RPi and Rockchip use the `cputemp`/`gputemp` setting in Kodi `advancedsettings.xml`. This means that RPi (and potentially Rockchip) are at the mercy of Kodi to get it right (which doesn't always happen: see #3073)
With this PR, all projects now use the `cputemp` and `gputemp` scripts.
2) The current `cputemp` script includes logic for all platforms, even old kernels. This is unnecessary when most platforms and kernels use only a single path for the CPU temp.
With this PR, all projects now use only the path(s) necessary to return the CPU temp for the current kernel.
This means that Amlogic (and possibly others) will need to amend this script when using the mainline kernel. Allwinner - which apparently has a gpu temp sensor - may need to differentiate between …
=> kodi: use project specific cputemp scripts for all projects

projects/WeTek_Core/filesystem/usr/lib/modules-load.d/amlvideodri.conf
Load amlvideodri module on WeTek Core at startup, otherwise HW video decoding won't work.
=> projects/WeTek_Core: Load amlvideodri module at startup

Makefile, scripts/get, scripts/get_archive, scripts/get_file, scripts/get_git, scripts/mkimage
These are general cleanups for `mkimage` and the `get*` scripts. They cover:
Line indent
Backticks to $()
Quoting and braces/brackets/{}s for variables
Using build variables for path settings
Convert to die()
Testing by fetching/building an RPi2 `make image`. More testing probably needed as I don't think that it uses all the code paths here. For the Makefile change, the change is correct, but I'm not sure `make src-pkg` works, as I have no `.stamps` directory after building an image so it fails. Thus, I'm not sure how it is used currently.
=> Buildsystem: mkimage / get cleanup

packages/addons/addon-depends/vdr-plugins/vdr-plugin-restfulapi/package.mk, packages/addons/addon-depends/vdr-plugins/vdr-plugin-restfulapi/patches/vdr-plugin-restfulapi-02-webapp-path.patch, packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk, packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/patches/vdr-plugin-wirbelscan-001-fix_segv.patch, packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/patches/vdr-plugin-wirbelscan-002-channel_count.patch, packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/patches/vdr-plugin-wirbelscan-003-detect.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-01-svdrp-modt-recflag.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-02-invalid-locking-sequence.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-03-locking-channel-display.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-04-locking-channel-display-2.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-05-shutdown.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-06-channel-switch.patch, packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-07-disabling-mtd.patch, packages/addons/script/script.config.vdr/changelog.txt, packages/addons/script/script.config.vdr/package.mk, packages/addons/script/script.config.vdr/sources/addon.xml, packages/addons/service/vdr-addon/changelog.txt, packages/addons/service/vdr-addon/package.mk, packages/addons/service/vdr-addon/source/system.d/service.multimedia.vdr-addon.service
- update VNSI to 1.8.0
- add VDR 2.4.0 upstream patches from ftp://ftp.tvdr.de/vdr/Developer/Patches/vdr-2.4
- Fix script.config.vdr scan: 
- reststfulapi: use header from current wirbelscan
- wirbelscan: fix segv, interface channel counts and device detection
- When LibreELEC/script.config.vdr#7 is merged, addon script.config.vdr can be updated.
=> vdr-addon 109 / script.config.vdr 103

scripts/mkimage
If temporary folder is full error message can't be saved and shown to the user which doesn't know what the problem actually is. In this case show some message.
old behaviour
```
image: extracting part1 from image...
image: error happen...
image: cleanup...
```
new behaviour
```
image: extracting part1 from image...
image: error happen...
folder /tmp.inTRp2QM1b might be out of free space...
image: cleanup...
```
=> scripts/mkimage: show message when temp folder is full

config/functions, config/path, scripts/autoreconf, scripts/build, scripts/clean, scripts/create_addon, scripts/get_archive, scripts/get_file, scripts/get_git, scripts/install, scripts/unpack
WIP demonstration of adding a printf helper function to config/functions to output build messages. Currently two functions, but easily combined to one (simply insert build_msg_indent's content into the if test where it's called). Since not every status message causes indent to shift further, this is controlled through the 4th parameter being "indent" or not (and erroring out on other content in $4)
get_archive conversion provided as sample. Tested by fetching a variety of packages.
=> buildsystem: printf conversion to function

packages/network/iptables/package.mk, packages/network/libnftnl/package.mk
`iptables` 1.8.1 now requires `libnftnl` >= 1.1.1:
```
checking for libnftnl >= 1.1.1... no
*** Error: no suitable libnftnl found. ***
Please install the 'libnftnl' package
Or consider --disable-nftables to skip
iptables-compat over nftables support.
````
=> iptables: update to iptables-1.8.2

packages/x11/driver/xf86-video-nvidia/package.mk
Because Nvidia updated the name scheme from libglx.so.390.87 to libglx**server**_nvidia.so.410.66 a wrong libGLX file was installed. 
https://download.nvidia.com/XFree86/Linux-x86_64/390.87/README/installedcomponents.html
https://download.nvidia.com/XFree86/Linux-x86_64/410.66/README/installedcomponents.html
=> xf86-video-nvidia: fix libglx_nvidia.so

packages/graphics/opengl-meson/package.mk
Since https://github.com/xbmc/xbmc/pull/14772 Kodi doesn't supports the old AML 3.14 buildroot EGL headers anymore. So we need some kind of HACK/workaround/backport to fix it.
- this fixes S905 compiling of Kodi
updated headers from https://github.com/khadas/buildroot_buildroot/tree/buildroot/package/meson-mali/include and added to `EGL/eglext.h` 
```
#ifndef EGL_KHR_debug
#define EGL_KHR_debug 1
typedef void *EGLLabelKHR;
typedef void *EGLObjectKHR;
typedef void (EGLAPIENTRY  *EGLDEBUGPROCKHR)(EGLenum error,const char *command,EGLint messageType,EGLLabelKHR threadLabel,EGLLabelKHR objectLabel,const char* message);
#define EGL_OBJECT_THREAD_KHR             0x33B0
#define EGL_OBJECT_DISPLAY_KHR            0x33B1
#define EGL_OBJECT_CONTEXT_KHR            0x33B2
#define …
```
=> egl fix for amlogic

packages/multimedia/aom/package.mk
AV1 builds with NEON. Which isn't a good idea when NEON isn't supported (ie. RPi).
=> aom: disable NEON when not supported

scripts/create_addon
`scripts/create_addon official` was not working
=> scripts/create_addon: fix typo of official

packages/multimedia/rkmpp/package.mk, projects/Rockchip/patches/linux/rockchip-4.4/linux-0001-rockchip.patch, projects/Rockchip/patches/linux/rockchip-4.4/linux-0006-rtl8211f.patch
This PR fixes a rockchip-4.4 kernel crash when Kodi 18.0rc1 is started and tries to open a drm render node. Also includes a rkmpp version bump with some [fixes](https://github.com/rockchip-linux/mpp/compare/b9dda0fb95674651673cbab0b846d29ab9b0e96c...1babbc9cc277692d02fc4727daef2e91f91ce8b0).
Tested on Rock64 and RockPro64
=> Rockchip: fix kernel crash when kodi 18.0rc1 starts

config/functions, config/path, scripts/build, scripts/create_addon, scripts/install, scripts/unpack
This adds a helper function that is used to call into package functions if they exist, handle errors when the call fails, and return a suitable exit code to indicate when the function does not exist.
If the package function does not exist, the proxy does nothing and returns with exit code 1, which would normally be an error so when the exit code isn't relevant to the caller then `|| true` must be used to prevent the calling script from bailing out due to `set -e`.
This change eliminates repeated code, and makes the calls to package functions more robust - if the call to the package function fails we will now output a (hopefully) helpful error message, rather than failing silently which normally leads to a lot of head scratching/confusion.
I've called the proxy function `pkg_function`, but …
=> buildsystem: proxy calls to package functions

config/functions
After #3109 custom color names are printed, not used.
I.e. with `CLR_TARGET="yellow"`
```
BUILD      vdr-plugin-dvbapi yellow(target)
```
=> buildsystem: fix custom colors

packages/network/samba/package.mk
Security release, but most issues affecting AD: https://www.samba.org/samba/history/samba-4.9.3.html
=> samba: update to samba-4.9.3

packages/emulation/libretro-fbalpha/package.mk
If a target device has ARM NEON support enabled you have to set `HAVE_NEON=1` otherwise the build will fail.
https://forum.kodi.tv/showthread.php?tid=298461&pid=2795624#pid2795624
- updated to latest version
- cleaned up lto stuff
- added check for NEON
- added RPi device specific platforms
- build with proper 7char hash git version
=> libretro-fbalpha: updated to git bfededf / updated build flags

packages/sysutils/busybox/scripts/getedid
This change fixes the problem that we delete the "/storage/.config/firmware"-folder at the `getedid delete`-section. This was talked about at #3141
Now we only delete the "edid"-subfolder.
=> [busybox] Fixed 'getedid delete' section

packages/network/iptables/package.mk, packages/network/iptables/patches/iptables-0001-fix-build-with-pre-4.2-kernels.patch
This upstream commit fixes the build issue with 3,10.y kernels, and can be removed with iptables-1.8.3.
=> iptables: fix build with 3.10.y, remove hack

packages/devel/heimdal/package.mk
Building OTP is broken on ArchLinux and it seems it is not needed
anyway.
Signed-off-by: Jernej Skrabec <jernej.skrabec@siol.net>
Also see https://github.com/heimdal/heimdal/issues/396
=> heimdal: Disable OTP [backport]

packages/linux/package.mk, packages/network/bluez/package.mk, packages/sysutils/systemd/scripts/kernel-overlays-setup
Creating an updates symlink to /storage/.config/firmware in the kernel firmware directory makes it impossible to add firmware overlays with an updates folder.
Furthermore bluez/hciattach only looks for firmware files directly in the /lib/firmware directory and ignores the /lib/firmware/updates directory. So adding BT firmware via .config/firmware didn't work.
Solve this by adding files from /storage/.config/firmware as the last step in kernel overlays setup so firmware files from there will show up directly under /lib/firmware and override other firmware files installed by the system and kernel overlays.
Also fix the /etc/firmware symlink for bluez, it pointed to the kernel firmware so hciattach would never pick up firmwares installed by kernel overlays or .config/firmware
=> fix .config/firmware handling

packages/devel/heimdal/package.mk
@jernejsk in light of [this question](https://github.com/heimdal/heimdal/issues/396#issuecomment-447479814) (which is in relation to #2218), can you test if `heimdal` with this PR continues to build correctly on Arch? I've tested on Ubuntu 17.10 without issue.
=> heimdal: remove unrequired setting

packages/multimedia/intel-vaapi-driver/package.mk
https://github.com/intel/intel-vaapi-driver/releases/tag/2.3.0
=> intel-vaapi-driver: update to intel-vaapi-driver-2.3.0

packages/linux-driver-addons/dvb/depends/media_tree/package.mk, packages/linux-driver-addons/dvb/dvb-latest/package.mk
- updates media_tree a bit further
- RK workaround is now fixed upstream
=> dvb-latest: update to 2018-12-07

packages/addons/addon-depends/tini/package.mk
I'm not 100% sure, but the existing variable names look like they are typos - @lrusak can you confirm as you committed this originally (86be339d0df5b438ca6eb2f6ecae296aa28a22c9).
=> tini: fix typos

config/functions, packages/lang/llvm/package.mk
I know everyone would like to build system as fast as possible. But when you don't have much cpu cores and you need to share them between different things it is good if build system respects CONCURRENCY_MAKE_LEVEL parameter. Currently llvm builds on all cores which this PR fixes.
=> config/functions: respect CONCURRENCY_MAKE_LEVEL for ninja

packages/addons/addon-depends/system-tools-depends/depends/libssh2/package.mk, packages/textproc/libxslt/package.mk
Compiling a shared library requires -fPIC. But this two libs are build without.
=> libxslt, libssh2: build with -fPIC

config/functions, config/optimize, packages/graphics/libjpeg-turbo/package.mk
Strictly speaking `nasm` is only required when SSE support is required, but building it always for x86_64 may be the least troublesome option.
=> libjpeg-turbo: bump version/switch to cmake; fix host cmake

packages/devel/glib/package.mk
`glib` includes a redundant `post_makeinstall_target()` function.
Only the second (last) definition would be executed.
=> glib: remove function that could not possibly be used

packages/devel/cmake/package.mk
Successfully builds RPi/RPi2/Generic.
@5schatten reports an issue with `libretro-citra`, but no details so far, and this package isn't in LE master.
Could we get Jenkins to build addons with this PR?
=> cmake: update to cmake-3.13.2

packages/addons/addon-depends/chrome-depends/chrome-libXcomposite/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libXdamage/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libXfixes/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libXi/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libXrender/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libXtst/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libxcb/package.mk, packages/addons/addon-depends/chrome-depends/cups/package.mk, packages/addons/service/hyperion/package.mk, packages/addons/service/mpd/package.mk, packages/databases/mysql/package.mk, packages/emulation/libretro-ppsspp/package.mk, packages/readme.md, tools/pkgcheck
This adds a script `tools/pkgcheck` that can be used to sanity check package.mk files.
When called without an argument it will check all packages, otherwise it will check the specified packages, eg. `./tools/pkgcheck kodi linux mysql`.
It tries to spot various problems that are now addressed by #3171.
Issue | Level | Meaning |
| :--- | :----: | ---- |
| late&nbsp;binding&nbsp;violation | FAIL | Late binding variables referenced outside of a function - see [late binding](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/readme.md#late-binding-variable-assignment) |
| duplicate&nbsp;function&nbsp;def | FAIL | Function defined multiple times, only last definition will be used |
| bad&nbsp;func&nbsp;-&nbsp;missing&nbsp;brace | FAIL | Opening brace (`{`) for function definition …
=> pkgcheck: add new script

packages/sysutils/v4l-utils/udev.d/70-infrared.rules
Using $id to get the rcX device name from the SUBSYSTEMS match,
as used by the upstrem v4l-utils udev rule, is easier and more
stable than using IMPORT{parent}, which needs to transmit info across
two levels (rcX->inputY->eventZ) and breaks with kernel 4.20.
Instead of running a shell script to check for the existance of
/storage/.config/rc_maps.cfg we can use the builtin udev TEST
function.
Also it's better to use ENV variables prefixed with a dot as
they are used only locally in the udev rule file and don't need
to be persisted in the udev database or exported to external tools.
=> v4l-utils: simplify 70-infrared.rules and fix kernel 4.20 issues

config/functions
Use _uname -m_ instead of _uname -i_ for CMAKE_SYSTEM_PROCESSOR.
Both actually returns x86_64 on most 64-bit systems however on other machines I get:
```
host ~ # uname -i
GenuineIntel
host ~ # uname -m
i686
```
Another Debian system shows:
```
root@ns:~# uname -i
unknown
root@ns:~# uname -m
i686
```
I know building on 32-bit hosts is no longer supported but this actually fixes _libjpeg-turbo_ build on 32-bit systems.
=> Fix host platform for CMake

packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch, packages/mediacenter/kodi/scripts/service-addon-wrapper
Currently when addon is installed it's service is enabled and started.
But immediately service is stopped, disabled, enabled and started again.
This second part should be executed only on addon's update.
Discussion in PR #1835 https://github.com/LibreELEC/LibreELEC.tv/pull/1835#commitcomment-31787284
=> kodi: service addon wrapper call fix

packages/compress/zstd/package.mk
Of note is compression ratio improvements. Takes another ~370kb off an RPi image for me.
Updated URL to point to releases so the checksum matches what the zstd maintainers say the checksum should be.
=> zstd: update to 1.3.8

packages/x11/driver/xf86-video-nvidia/package.mk
Announcement: [forum](https://devtalk.nvidia.com/default/topic/1045858), [alt](https://www.nvidia.com/Download/driverResults.aspx/141700/en-us)
Fixes kernel 4.20 issues.
=> xf86-video-nvidia: update to xf86-video-nvidia-410.93

packages/addons/addon-depends/snapcast-depends/alsa-plugins/package.mk, packages/audio/alsa-lib/package.mk, packages/audio/alsa-utils/package.mk
Update alsa-lib, alsa-plugins and alsa-utils to 1.1.8
With the fixes in alsa-lib alsaucm is now working and we can ship it as well.
alsaucm is a ~10k binary needed to configure audio routing on Intel Baytrail and various other boards.
Build and runtime tested on RPi2
=> alsa: update 1.1.8

packages/addons/addon-depends/containerd/package.mk, packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/libnetwork/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/changelog.txt, packages/addons/service/docker/package.mk
Updated Docker & it's dependencies to the latest stable release [18.09.1](https://github.com/docker/docker-ce/releases/tag/v18.09.1)
Compiled & tested on Generic systems to run PCSX2.
=> docker: updated to 18.09.1

packages/python/devel/MarkupSafe/package.mk
MarkupSafe is a dependency of Mako which uses Python3
=> markupsafe: use python3

packages/linux-driver-addons/dvb/crazycat_aml/patches/driver.dvb.crazycat_aml-03-config_mycompat_h.patch
fixes `dvb_usb_v2: Unknown symbol smp_mb__after_atomic (err 0)` while using for example `Technotrend CT-4400`
=> crazycat_aml: fix crash

packages/tools/qemu/package.mk
It builds, that's all I can tell you. Will include it the next x86_64 nightly (`#0108`).
=> qemu: update to qemu-3.1.0

packages/linux/patches/default/linux-999.03-dvbskys960-fix.patch, packages/linux/patches/raspberrypi/linux-999.03-dvbskys960-fix.patch
That bug made the S960 (VERY popular device) basically useless for proper usage since Kernel 4.10. 
Tx to https://forum.libreelec.tv/thread/12452-problems-with-dvbsky-technotrend-usb-dvb-s2-tuners-since-le8/?postID=107702#post107702 who fixed it.
Patch goes upstream "soon" so we could expect an backport to the LTS kernel at some date.
=> Linux: fix DVBSky S960 bug

config/functions
Sourcing `config/options` is not safe during a build. This hasn't always been the case, and I would argue (hence this PR) that it should generally be safe to source `config/options` at pretty much any time.
The problem now exists because the pacakge cache files are always generated by each new process that sources `config/options`. If a build process is ongoing then another process may result in corrupted cache files if the build process queries the cache files at the precise moment they are being regenerated by the second process. A corrupted cache file will result in errors such as `initramfs/package.mk does not exist`.
This change introduces a little more caution and we will now only update the cache files if they have changed (which would mean a new package has been introduced, or an …
=> buildsystem: be more cautious when overwriting package cache files

packages/network/libssh/package.mk
Documentation build process tries to use doxygen installed on host,
which may fail to build docs.
In order to avoid that, just disable documentation building altogether.
=> libssh: Disable documentation building

packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk
For some reason, sed tried to fix Makefile before it existed. Even stranger, that even worked in some cases.
=> tcpdump: properly reorder build step

projects/Rockchip/bootloader/install
This PR makes RK3328 images boot again after #3239
=> Rockchip: use correct rk3328 bootloader bl31 filename

config/functions, packages/linux/package.mk, packages/network/samba/package.mk, packages/sysutils/e2fsprogs/package.mk, scripts/build, scripts/create_addon, scripts/install, scripts/unpack
This restores the `set -e` (exit on failure) behaviour that is broken by #3136. This should also make #3248 unnecessary.
The core issue with the change in #3136 is that it is testing the exit code of the called function - any attempt to test the exit code will disable `set -e` behaviour. The `set -e` behaviour kicks in whenever a command or function is executed *unconditionally*.
This also means we can't have a helpful ` ${1} for package ${PKG_NAME} did not succeed!` failure message. :(
Apologies for not catching this sooner.
=> buildsystem: restore set -e behaviour after #3136

tools/mkpkg/update_retroplayer-addons
Instead of bumping libretro cores to their current master version use the githash from depends file in kodi game addon.
This ensures we ship the same libretro core versions as Kodi.
When a kodi game addon is bumped the libretro package is automaticallybumped, too.
If the script is invoked with the "-f" option all libretro packages will be synced to the version specified in the kodi game addon.
Result of a forced update is here: https://github.com/HiassofT/LibreELEC.tv/commit/97a44d33c178e202105b0dafdf44608340c28ccb
=> update_retroplayer-addons: sync libretro core versions with kodi

packages/emulation/libretro-mame2003_plus/package.mk, packages/emulation/libretro-mame2016/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mame2003_plus/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mame2016/package.mk, packages/mediacenter/kodi-binary-addons/game.netplay/package.mk
- this is just buildtested (at generic) because I have nothing to runtime test it
- mame2016 is building, game.libretro.mame2016 fails - ideas welcome how to fix it
```
buildbot:~/LE$ PROJECT=Generic ARCH=x86_64 scripts/create_addon game.libretro.mame2016
CREATE ADDON game.libretro.mame2016 (Generic/x86_64)
BUILD      game.libretro.mame2016 (target)
TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/builddir/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel /builddir/game.libretro.mame2016-2581a76552da518cb82f8940e3dd1c37d07e640d
-- MAME2016_VERSION=0.174.0.1
-- Configuring done
-- Generating done
-- Build files have been written to: …
```
=> add missing libretro addons

packages/emulation/libretro-mame/package.mk
broken due upstream changes at `game.libretro.mame`
=> libretro-mame: change name of binary

packages/emulation/libretro-picodrive/package.mk
The environment variable "R" leaks into the Makefile,
if it is set the build will fail. eg
export R=12345
scripts/build libretro-picodrive
...
make: *** No rule to make target '12345pico/pico.o', needed by 'picodrive_libretro.so'.  Stop.
Unset the variable before calling make to fix this issue
=> libretro-picodrive: fix build error

packages/addons/addon-depends/libid3tag/package.mk, packages/addons/addon-depends/libid3tag/sources/id3tag.pc, packages/addons/service/mpd/package.mk
- libid3tag: install libid3tag.pc that mpd could find it via pkgconfig
- mpd: uses now meson instead of configure, this was overseen as mpd auto-detect, and use, everything from host system without explicit enable/disable what we have at toolchain
=> mpd: change to meson

packages/linux-firmware/rockchip-firmware/package.mk, packages/linux-firmware/rockchip-firmware/udev.d/80-rockchip-firmware.rules, packages/multimedia/rkmpp/package.mk, packages/tools/rkbin/package.mk, projects/Rockchip/README.md, projects/Rockchip/bootloader/install, projects/Rockchip/devices/RK3399/README.md, projects/Rockchip/devices/RK3399/options, projects/Rockchip/patches/linux/rockchip-4.4/linux-0001-rockchip.patch, projects/Rockchip/patches/linux/rockchip-4.4/linux-0005-dts.patch, scripts/uboot_helper
This PR updates to ~~latest RK 4.4 kernel~~, installs more and updates wifi/bt firmwares seen in devices (AP6255, AP6256, AP6356, AP6398) and adds initial support for Rock Pi 4.
~~The kernel update has been compile tested, runtime testing ongoing.~~
Edit: Kernel bump dropped, only a few tested patches and dts for rock-pi-4 is now included.
=> Rockchip: update wifi/bt firmware and add initial rock-pi-4 support

packages/mediacenter/LibreELEC-settings/package.mk
Fixes stale list of versions when clicking on "Available versions" button.
=> LibreELEC-settings: update to LibreELEC-settings-37e206b

packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux/patches/default/linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux/patches/raspberrypi/linux-902-extend-rc6-toggle-support-for-zotac.patch
Zotac remotes use the customer code 0x80340000 and need the same toggle
bit handling as MCE remotes.
This should fix the issue reported here: https://forum.libreelec.tv/thread/14388-ir-remote-malfunction-after-upgrade-to-le-9-0/
Note: this is completely untested so far
=> linux: add patch to fix Zotac IR remotes

config/functions
Allow usage of cross-compile properties eg.
```
PKG_MESON_PROPERTIES_TARGET="
have_c99_vsnprintf=true
have_c99_snprintf=true
growing_stack=false
va_val_copy=false"
```
=> config/functions: add cross-compile property support

packages/tools/nano/package.mk
Automatic line wrapping is dangerous when changing configuration files.
=> nano: disable line wrapping

config/functions, config/options
After #3171 we init the package cache too late for `set_debug_depends`, which then fails.
I'll push a backport for libreelec-9.0 after further testing.
=> buildsystem: fix debug broken by #3171

packages/network/libnfs/package.mk
Backport of #3304.
I include latest `libnfs` so let this be tested a day or two before merging, close if issues.
The delta is minor:
https://github.com/sahlberg/libnfs/compare/38b62bcf873c778ebde79707bb0409b6a09ee608...libnfs-4.0.0
=> libnfs: update to libnfs-4.0.0 [backport]

packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-03-linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux/patches/default/linux-902-extend-rc6-toggle-support-for-zotac.patch, packages/linux/patches/raspberrypi/linux-902-extend-rc6-toggle-support-for-zotac.patch
backport of #3289 - this time to the correct le9 branch
=> [le9.0] add patch to fix Zotac IR remotes

packages/mediacenter/kodi/package.mk
build tested for RPi2 only so far
=> [le92] kodi: update to 18.1

packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-04-fix-tbs5520se.patch, packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-04-fix-tbs5520se.patch
```
usb 1-1.3: DVB: adapter 0 frontend 1 frequency 386000000 out of range (470000000..862000000)
So basically I can scan UHF channels but not the VHF (out of range)
```
tx to crazycat
=> CrazyCat TBS 5520SE fix

packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch
Drop KEY_TITLE mapping, this is already mapped in kodi Lircmap.xml.
Drop mappings with invalid keycodes KEY_FFORWARD KEY_VOLUP KEY_VOLDOWN
KEY_CHUP KEY_CHDOWN KEY_STAR KEY_POUND, they don't exist in
linux/input-event-codes.h
This fixes the bug reported here: https://forum.libreelec.tv/thread/14500-9-0-0-key-title-mapped-twice-in-lircmap-xml/
=> kodi: cleanup Lircmap.xml patch

packages/mediacenter/kodi/scripts/kodi.sh
Write more information into kodi crash log.
Use full back trace. Add CPU register dump and disassembly of current function.
=> kodi.sh: upgrade crash log information

packages/tools/texturecache.py/package.mk
=> texturecache.py: update to texturecache.py-2.4.9 [backport]

packages/network/openssh/package.mk
OpenSSH 7.0 was released in August 2015 and removed default-config support for DSA keys which are 1024 bit and considered insecure. I presume we re-added support in https://github.com/LibreELEC/LibreELEC.tv/commit/6390ccb28a162d7882fb2c89b963048879db7b89 to address users reporting their keys not working, but [3.5 years later] it would be better to accept defaults and prefer RSA/ed25519 keys. You can always use /storage/.cache/ssh/sshd_config to keep using DSA keys if needed. No backport to 9.0 as this is a breaking change.
=> openssh: drop support for ssh-dss keys

packages/databases/sqlite/package.mk, packages/graphics/libjpeg-turbo/package.mk, packages/graphics/tiff/package.mk, packages/lang/nasm/package.mk, packages/security/libgcrypt/package.mk, packages/security/libgpg-error/package.mk, packages/security/openssl/package.mk, packages/sysutils/tz/package.mk, packages/testing/package.mk, packages/tools/nano/package.mk, packages/web/curl/package.mk
This has been tested to the extent these packages are used in a RPi build (nasm isn't).
=> Packages: Miscellaneous package bumps to new minor versions

config/functions, packages/sysutils/systemd/package.mk
I'm not sure if this is the best method to do this so I just wanted to PR this anyways to start some discussion.
The whole purpose of this is that some packages that we have we modify heavily. One part of this may be to remove default files. These files may change over time as the package gets bumped in version. When we use `rm -rf` the build system just blows over it and nothing happens if the path doesn't exist. If we use just `rm -r` then the build errors out and exits. This may not seem important but in terms of package maintenance I think it's important to know if we are doing something incorrectly.
I'm open to change the implementation and the warning message.
Example output when building systemd
```
path does not exist for removal: …
```
=> [RFC] add safe_remove to notify if a file doesn't exist

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/system.d/brcmfmac_sdio-firmware.service
I noticed that Bluetooth isn't always being enabled on a RPi3+ (and probably RPi3 too) - LibreELEC will sometimes try to configure the BT hardware before `/dev/serial1` is available:
Not working:
```
LibreELEC (official): 9.0.1 (RPi2.arm)
rpi22:~ # systemctl status brcmfmac_sdio-firmware.service
? brcmfmac_sdio-firmware.service - Broadcom sdio firmware update for BCM43430A1
Loaded: loaded (/usr/lib/systemd/system/brcmfmac_sdio-firmware.service; disabled; vendor preset: disabled)
Active: inactive (dead)
Condition: start condition failed at Fri 2018-06-22 12:11:51 BST; 8 months 11 days ago
+- ConditionPathExists=/dev/serial1 was not met
```
Reboot the RPi3+, and BT is now working:
```
LibreELEC (official): 9.0.1 (RPi2.arm)
rpi22:~ # systemctl status brcmfmac_sdio-firmware.service
? …
```
=> brcmfmac_sdio-firmware-rpi: fix race between service and /dev/serial1

packages/addons/service/lcdd/package.mk, packages/devel/elfutils/package.mk, packages/devel/glib/package.mk, packages/devel/mpfr/package.mk, packages/devel/pcre/package.mk, packages/print/freetype/package.mk, packages/x11/app/xkbcomp/package.mk, packages/x11/driver/xf86-input-evdev/package.mk, packages/x11/driver/xf86-input-libinput/package.mk, packages/x11/driver/xf86-input-synaptics/package.mk, packages/x11/lib/libSM/package.mk, packages/x11/lib/libX11/package.mk, packages/x11/lib/libXau/package.mk, packages/x11/lib/libXinerama/package.mk, packages/x11/lib/libfontenc/package.mk, packages/x11/other/fontconfig/package.mk, packages/x11/xserver/xorg-server/package.mk
Bumping packages in `x11`, `print` and `devel` sections.
`arm-mem` adds NEON `memcmp`: https://github.com/bavison/arm-mem/commit/ea0bde27d823bd27f2e38ea0913f124b540c5ecc
=> packages/{x11,print,devel}: bump packages

packages/x11/driver/xf86-video-nvidia/package.mk
Announcement: [forum](https://devtalk.nvidia.com/default/topic/1047709), [alt](https://www.nvidia.com/Download/driverResults.aspx/142569/en-us)
418.43 as a "long-lived branch" release (#3327) is increasingly looking to have been a mistake by Nvidia. I'll re-introduce this 410.xx driver (which I believe is the real "long lived branch") into test builds until the situation is resolved.
=> xf86-video-nvidia: update to xf86-video-nvidia-410.104

config/functions, config/multithread, packages/databases/mysql/package.mk, scripts/build, scripts/build_mt, tools/dashboard, tools/viewplan
~I don't know if anyone still builds `mysql` but this change is probably required when using the isolated sysroot.~
Edit 1: This PR was initially prompted by code in `mysql` which will create a broken sym link. I subsequently discovered that `open-vm-tools` does something similar, but during `make`, so we have to fix that sym link during the transfer to the shared sysroot. The fix for `open-vm-tools` also fixes `mysql` so that change is now dropped.
Edit 2: So looking at `mysql` again, it's creating the broken sym link in `$TOOLCHAIN/usr/bin` so that still needs to be fixed, as the change to `scripts/build` can only fix sym links where the link is within the isolated sysroot. Easiest solution is to just copy the `mysql` file rather than create a sym link.
=> scripts/build: fix broken sym link after #3328

config/options
We've been trying to support spaces in paths for quite a while, and it's not really working.
It's rarely - if ever - been a problem, as I can't really recall anyone ever complaining about the lack of spaces support so I'm not entirely sure why we have gone down this rabbit hole trying to fix what wasn't really an issue (but I will take responsibility for that, as it's something I've brought it up in reviews in the past).
This change takes the completely opposite approach, and now aborts the build if a space is detected in the path - it's brutally simple, and solves all the issues.
Over time we can even roll back some of the changes that attempted to add space-support as these changes often made the code more complicated, and/or ugly.
I'll be adding an entry to #3055 to say that it …
=> config/options: ban spaces in paths

packages/lang/Python3/package.mk, packages/lang/gcc/package.mk, packages/lang/llvm/package.mk, packages/multimedia/libhdhomerun/patches/libhdhomerun-pr19-fix-gcc-8.3.0-build.patch
This is a draft PR for discussion/consideration.
I'm not entirely convinced this is a useful change, as we don't have any issues with gcc-8.2.0, but I have built RPi1/RPi2/Generic (`image` + all addons) successfully with this PR, which may be useful for bleeding-edge self builders.
gcc-9.1.0 is expected April-ish, however extra testing time with LibreELEC 10 and gcc-8.3.0 between now and then might still be useful in case of any gcc-9.1.0 regressions.
If not, this PR can be closed and cherry-picked for gcc-9.x.0.
=> gcc: update to gcc-8.3.0

packages/addons/service/vdr-addon/changelog.txt, packages/addons/service/vdr-addon/package.mk, packages/addons/service/vdr-addon/source/bin/vdr.start
This fix costed me more time than I care to admit.
Unfortunately VDR's git history is a bit lacking, to say the least. Official git repo seems to be dead and, to add injury to insult, I decided to update all my boxes at once.
The rest is history and resulted in a lot of wasted time. Moving on.
The option `--chartab` was introduced in v2.1.10, with the following note:
> - The new command line option --chartab can be used to set the default character table to use for strings in the DVB data stream that don't begin with a proper character table indicator (suggested by Christopher Reimer). The old mechanism of using the environment variable VDR_CHARSET_OVERRIDE still works, but is now deprecated and may be removed in a future version. The value given in the --chartab option takes precedence …
=> [vdr-addon] Fix deprecated VDR_CHARSET_OVERRIDE

packages/sysutils/busybox/scripts/init
This is a cleanup of `busybox/scripts/init` done as part of my overlay experiment. No feature change is intended here. Commits are broken up into what they are doing, and to improve reviewability.
Big picture:
Remove leading indent: nearly every line has a 2-space indent
Reorder script: Changed script layout to look like
- bring up enough of the system to be able to set all variables
- set variables
- set functions (shared then local)
- bring up the system and hand it off to real init
Style changes: whitespace & line extension changes
Current names: `reset_oe` and `reset_xbmc` triggers to `reset_le` and `reset_kodi`. I'm not aware of any documentation related to these triggers.
This has been booting and updating my rpi for a couple of weeks. I don't have the environment to test all the …
=> busybox/init: cleanup

packages/network/samba/package.mk
Changelog: https://www.samba.org/samba/history/samba-4.9.5.html
No security fixes.
=> samba: update to samba-4.9.5

packages/lang/Python2/patches/Python2-2.7.11-017-dont-install-2to3.patch, scripts/build, scripts/install_addon
Noticed this `Python3` failure on Jenkins:
```
(cd /var/lib/jenkins/LE/build2/workspace/Addons/Category/service/snapserver/build.LibreELEC-RK3328.arm-9.1-devel/toolchain/bin; ln -s 2to3-3.7 2to3)
/usr/bin/install -c -m 644 /var/lib/jenkins/LE/build2/workspace/Addons/Category/service/snapserver/build.LibreELEC-RK3328.arm-9.1-devel/Python3-3.7.1/Include/fileutils.h /var/lib/jenkins/LE/build2/workspace/Addons/Category/service/snapserver/build.LibreELEC-RK3328.arm-9.1-devel/toolchain/include/python3.7
/usr/bin/install -c -m 644 /var/lib/jenkins/LE/build2/workspace/Addons/Category/service/snapserver/build.LibreELEC-RK3328.arm-9.1-devel/Python3-3.7.1/Include/floatobject.h /var/lib/jenkins/LE/build2/workspace/Addons/Category/service/snapserver/build.LibreELEC-RK3328.arm-9.1-devel/toolchain/includ …
```
=> Python2: don't install 2to3, clashes with Python3 equivalent

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/system.d/brcmfmac_sdio-firmware.service
#3354 introduces a startup delay of over 90 seconds on devices without built-in WiFi/Bluetooth (ie. RPi0, RPi1, RPi2) as services such as Kodi will wait for `network.target` to be reached, which is itself blocked while waiting for `brcmfmac_sdio-firmware-rpi` service which cannot start until device `dev-serial1` becomes available, or times out.
The [upstream](https://github.com/RPi-Distro/pi-bluetooth/blob/051881526027f38f0f031d7185bcd2152425d8db/debian/pi-bluetooth.hciuart.service) service includes a condition check which doesn't really work as the service still blocks while waiting for the `dev-serial1` job to start, which never happens on RPi0/1/2 so the service eventually times out, but I'll include it anyway as it shouldn't do any harm. Likely not an issue on upstream due to …
=> brcmfmac_sdio-firmware-rpi: fix delay on non-wifi enabled devices

packages/sysutils/util-linux/package.mk, packages/sysutils/util-linux/patches/util-linux-0100-enable-lscpu.patch
Installs `/usr/bin/lscpu`, 55KB on ARM.
=> util-linux: update to util-linux-2.33.1 + lscpu

packages/graphics/libmali/package.mk
This update adds libmali blobs for t620 (Exynos 5422), g52 (Amlogic S922) and updates EGL+GLES includes to latest version. 
https://github.com/LibreELEC/libmali/compare/3e06d6226c22d8d69cd5cb4935d040178b0737f6...74c27b4b401e3266c71ab3718ef9878bd36dbd34
=> libmali: update to 74c27b4

packages/mediacenter/kodi/scripts/kodi-config
Currently there are no targets that use aarch64 userspace - they run aarch64 kernel and arm userspace. Make them use MALLOC_MMAP_THRESHOLD_=8192 which greatly helps to lower memory fragmentation.
Tests for arm userspace (albeit with arm kernel) were done by @MilhouseVH and 512k is not a good choice: https://forum.kodi.tv/showthread.php?tid=298461&pid=2696616#pid2696616
I suspect that this would also be the case even if kernel is aarch64. My initial, completely non-scientific tests show lower Kodi memory usage after starting (83M vs 55M) and after playing a few videos (ca. 200M vs 85M).
=> kodi: set MALLOC_MMAP_THRESHOLD_=8192 for aarch64 kernels

packages/mediacenter/kodi/scripts/kodi-config
Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3382
=> kodi: set MALLOC_MMAP_THRESHOLD_=8192 for aarch64 kernels (backport)

tools/mkpkg/mkpkg_media_build
CrazyCat `linux_media` repository no longer exists on [Github](https://github.com/crazycat69/linux_media) and throws a 404 as per the link but CrazyCat seems to have migrated and be active on [bitbucket](https://bitbucket.org/CrazyCat/linux_media) so this just updates the repository location in the `mkpkg_media_build` file.
=> mkpkg_media_build wrong linux_media location.

packages/network/samba/package.mk
o  CVE-2019-3870 (World writable files in Samba AD DC private/ dir)
o  CVE-2019-3880 (Save registry file outside share as unprivileged user)
Details
----
o  CVE-2019-3870:
During the provision of a new Active Directory DC, some files in the private/
directory are created world-writable.
o  CVE-2019-3880:
Authenticated users with write permission can trigger a symlink traversal to
write or detect files outside the Samba share.
For more details and workarounds, please refer to the security advisories.
Changes since 4.9.5:
o  Andrew Bartlett <abartlet@samba.org>
* BUG 13834: CVE-2019-3870: pysmbd: Ensure a zero umask is set for
smbd.mkdir().
o  Jeremy Allison <jra@samba.org>
* BUG 13851: …
=> samba: update to samba-4.9.6

packages/devel/libtool/package.mk
`libtool`, `libtoolize` and source files in `/usr/share` are not required in target image. Removing them saves 1.6MB from (uncompressed) system image. `pulseaudio` compiles fine with this patch.
Note: after applying this patch you need to `rm -f build*/toolchain/bin/libtool*`. Thanks to @MilhouseVH for the tip.
=> libtool: don't install source files on target

packages/network/samba/config/smb.conf
Samba broadcasts `model = MacSamba` via bonjour but at some point the macOS Finder stopped showing a generic monitor icon (see the `msad` device) and instead displays a question mark (see the `N2` device). This PR sets `model = Xserve` (see the `X96` device) which is the least-worst of the Finder icons available that work. Options like `model = macmini` that would be more HTPC-like also display a question-mark so I'm not sure if this is a general macOS bug (in 10.13 which I use, so 10.14 is not tested) or a deliberate action from Apple. Either way the Xserve icon (also used by Synology and most NAS devices) looks better than a large `?` mark.
=> samba: set fruit:model = Xserve for macOS finder

packages/linux-drivers/RTL8192DU/patches/RTL8192DU-0004-revert-fix-for-old-kernels.patch
Fixes the build for Amlogic_Legacy devices but is not tested with a real RTL8192DU chipset base device.
=> RTL8192DU: fix build for Kernel 3.14.29 / Project Amlogic_Legacy

packages/tools/texturecache.py/package.mk
=> texturecache.py: update to texturecache.py-2.5.0 [backport]

packages/addons/addon-depends/containerd/package.mk, packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/go/patches/go-0001-add-ca-cert-location.patch, packages/addons/addon-depends/libnetwork/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/changelog.txt, packages/addons/service/docker/package.mk
Compiled & tested on Generic builds with my [PCSX2 Docker image](https://cloud.docker.com/repository/docker/5schatten/arch-pcsx2/general).
18.09.3 changelog: https://docs.docker.com/engine/release-notes/#18093
- Adresses https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736
18.09.4 changelog: https://docs.docker.com/engine/release-notes/#18094
18.09.5 changelog: https://docs.docker.com/engine/release-notes/#18095
=> docker: updated to 18.09.5

tools/docker/README.md, tools/docker/bionic/Dockerfile, tools/docker/stretch/Dockerfile, tools/docker/xenial/Dockerfile
This PR adds `python3` to docker build containers to fix build of `glibc` 2.29+.
Also changes the example in README to use `bionic` container instead of `xenial`
From [glibc 2.29 changelog](https://sourceware.org/ml/libc-announce/2019/msg00000.html):
* Python 3.4 or later is required to build the GNU C Library.
=> tools/docker: install python3

packages/tools/nano/config/nanorc, packages/tools/nano/package.mk, packages/tools/nano/patches/nano-999.01-initialize-a-variable-before-referencing-it.patch
- update to [Nano 4.0](https://www.phoronix.com/scan.php?page=news_item&px=GNU-Nano-4.0-Released)
- added patch to init vars before referencing them -> for ARM builds
- added some nanorc files to enable syntax highlighting for common file types -> adds about 8,8kB to the uncompressed size
Example:
https://i.imgur.com/XBJQ0j9.jpg
=> nano: updated to nano-4.0

packages/lang/llvm/package.mk
Tested with MESA 19.0.1 
https://releases.llvm.org/8.0.0/docs/ReleaseNotes.html
=> llvm: update to llvm-8.0.0

packages/multimedia/dav1d/package.mk, packages/multimedia/ffmpeg/patches/ffmpeg-99.1008-dav1d-enable-av1.patch, packages/multimedia/ffmpeg/patches/ffmpeg-99.1009-dav1d-fix-multithreaded-av1-sw-decoding.patch
Tested with:
- https://www.elecard.com/videos
- http://download.opencontent.netflix.com/?prefix=AV1/Chimera/
My [J3455-ITX](https://asrock.com/mb/Intel/J3455-ITX/) was able to handle this [1080p / 8bit video](http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-8bit-1920x1080-6736kbps.mp4) file at 24Hz which equals roughly performance wise an Intel® Core™2 Quad Processor Q6600 so I guess older cpus with SSSE3 support should be able to handle this video specs as well.
Additional updates:
- ffmpeg: updated AV1 support patch for dav1d 0.2.1 -> backported upstream [libdav1d.c](https://github.com/FFmpeg/FFmpeg/blob/9e62e1a1104bb0d64e604051ffc25004ad748eaf/libavcodec/libdav1d.c)
- ffmpeg: fixed multithreaded sw decoding for AV1 thx to @lrusak 
Release notes:
- …
=> dav1d: updated to 0.2.1 / added meson opts to disable tools & tests

packages/devel/arm-mem/package.mk, packages/virtual/libc/package.mk
This has been in my RPi/RPi2 test builds since 15 March 2019 without complaint.
I can drop the second commit which enables `arm-mem` for all `arm`-based projects if this is not wanted - I have not build/run-time tested this with any other projects.
=>  arm-mem: update to arm-mem-0100445, enable for all arm builds

packages/sysutils/busybox/package.mk, packages/sysutils/busybox/scripts/dtfile, packages/sysutils/busybox/scripts/dtname
The `dtname` helper script reads the mainline kernel `compatible` strings from Allwinner, Amlogic and Rockchip devices. It's primary use is for project stats reporting so we have some pretty strings like `khadas,vim` and `pine,rockpro64` instead of the current `unknown` but it can also be used from userspace to assist decisions on which firmware, driver, config, keymap to load/use. As ever more devices move to mainline kernels there's a clear benefit from sending device-trees upstream so that more device-specific compatible strings exist; so over time more userspace things can be auto-configured for a better out-of-box user experience. NB: The first `compatible` in the device-tree results in a short string with no spaces that is simple to reuse whereas the `model` string contains a much …
=> busybox: add dtname/dtfile helper scripts

packages/network/iptables/scripts/iptables_helper
This prepares for a pending feature change to add Ethernet tethering support to LE settings.
=> iptables: iptables_helper support for ethernet tethering

packages/sysutils/busybox/scripts/dtfile, packages/sysutils/busybox/scripts/dtname
Prevents errors on platforms where the device-tree values don't exist.
=> busybox: improvements to dtname/dtfile

packages/tools/texturecache.py/package.mk
=> texturecache.py: update to texturecache.py-2.5.1 [backport]

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk, packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk, packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk, packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.asteroids/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.biogenesis/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.greynetic/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.matrixtrails/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.pyro/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.stars/package.mk, packages/mediacenter/kodi-binary-addons/vfs.rar/package.mk, packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk, packages/mediacenter/kodi-binary-addons/visualization.spectrum/package.mk, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch, packages/multimedia/ffmpeg/package.mk, packages/textproc/nlohmann-json/package.mk
~Backport of #3424~
No longer a backport - we'll keep master on 18.2-rc1 for now.
=> kodi (Generic/RPi/RockChip): update to kodi-18.2-Leia

packages/sysutils/busybox/scripts/init
For multi-cluster CPUs (e.g. Amlogic S912) there is a separate policy for each CPU cluster. Add a case in init script to cover setting up_threshold for all clusters.
```
LibreELEC:~ # find /sys/devices/system/cpu/cpufreq -name up_threshold
/sys/devices/system/cpu/cpufreq/policy4/ondemand/up_threshold
/sys/devices/system/cpu/cpufreq/policy0/ondemand/up_threshold
```
=> init: set ondemand up_threshold for multi-cluster CPUs

config/graphic
This adds a combined if messy-named `limapanfrost` option for use with upstream mesa now that both are merged to mesa 19.1 and usable (with caveats). I thought about calling this `amlogic` but while use is currently limited to Amlogic 'GX' test images this would lead to duplication or renaming once other SoC platform take the plunge and go blob free. I toyed with the idea of also adding some separate `lima` and `panfrost` options, but building mesa with support for both does no harm so a single option will suffice. Suggestions for a prettier option name will be entertained :)
=> config/graphic: add lima/panfrost options and sort

packages/tools/qemu/package.mk
Builds, and creates OVA files - not personally run-time tested:
http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-9.1-devel-20190424062234-%230424c-g319be3b.ova
=> qemu: update to qemu-4.0.0

config/functions
We only update the dashboard after updating the history, and since we already have an exclusive lock on the history there's no need to take a lock on the status (dashboard) file too, so we can dispense with the `flock()` on `.status` entirely.
(Hiding the whitespace changes makes the relevant changes much easier to see!)
=> config/functions: eliminate unecessary dashboard flock()

packages/compress/zstd/package.mk
Release notes
- https://www.phoronix.com/scan.php?page=news_item&px=Zstd-1.4-Released
The CMake issue should be fixed by this commit 
- https://gitlab.kitware.com/cmake/cmake/commit/d4e551a90b6bf6ea4e18fa408f40f39df6ad6fb4
=> zstd: update to 1.4.0 / dropped CMake pthread workaround

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
cleanup to LE "standards" of https://github.com/LibreELEC/LibreELEC.tv/pull/3464
=> brcmfmac_sdio-firmware: cleanup package

packages/addons/addon-depends/ffmpegx/package.mk, packages/devel/libcec/package.mk, packages/graphics/bcm2835-driver/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk, packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk, packages/multimedia/ffmpeg/package.mk, projects/Allwinner/devices/H3/options, projects/RPi/options
The bcm2835-driver package contains several vendor headers & libs which were normally installed to `/opt/vc/include` & `/opt/vc/libs` but LE installs them to `/usr/...` so we need extra include flags to tell packages where they find these includes.
Also the pkgconfig files provided by the Raspberry project contain a `prefix=/opt/vc` var which leads to wrong include paths if pkg-config is used to compile packages.
So this PR changes the prefix to `prefix=/usr` & creates symlinks for `/opt/vc` to make sure hardcoded include paths were correct & pkg-config creates valid include paths.
- the PR also removes the CFLAGS in some projects
- reduces the TARGET_FPU options to hard or soft
- removes the softfp option for Allwinner H3 & RPi
Tests:
- RPi3 -> the usual stuff so video, tv & music works …
=> [RPi] fix vendor header & lib includes / remove project specific include CFLAGS WIP

packages/addons/service/lcdd/package.mk, packages/print/freetype/package.mk
`lcdd` currently fails to build if the build host has `libfreetype6-dev` installed as `-I/usr/include/freetype2` is then added during the `lcdd` build due to the incorrect prefix in `freetype2.pc` (from the `freertype` package).
=> lcdd: fix cross-compile breakage

scripts/image, scripts/image_st, scripts/mkimage, scripts/uboot_helper
This PR makes it possible to build multiple images based on the same `.kernel` and `.system` files.
**When is multiple images built?**
Building of multiple images is only activated when `BOOTLOADER` is `u-boot`, `UBOOT_SYSTEM` is empty, `DEVICE` is set and boards is defined in `scripts/uboot_helper`.
**How is images built?**
The `u-boot` package is built with empty `UBOOT_SYSTEM` and only `update.sh`, `canupdate.sh` and dtbs is installed into `.system` file at `/usr/share/bootloader`.
The device universal update `<IMAGE_NAME>.tar` file is created
For each uboot system returned by `scripts/uboot_helper <PROJECT> <DEVICE>`:
- `u-boot` package is re-built and re-installed with `UBOOT_SYSTEM` set
- `bootloader/release` is invoked to copy the `u-boot` files to `3rdparty/bootloader`
- …
=> scripts/image: build an image for each UBOOT_SYSTEM

packages/addons/addon-depends/network-tools-depends/lftp/package.mk
~~Backport of #3363~~ No longer a backport, but the alternative to #3373 that keeps libidn2 out of the image for LE9.
=> lftp: explicitly disable libidn2 to prevent linking [LE9]

packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.scummvm/package.mk
Fixes
https://forum.libreelec.tv/core/ticketsystem/ticket/64-lftp-not-working-in-libreelec-9-0-1/
https://forum.libreelec.tv/core/ticketsystem/ticket/67-scummvm-linker-error/
Would be probably nice to have them ready with next stable LibreELEC version.
=> addons: rebuild network-tools (lftp) and game.libretro.scummvm

config/graphic, packages/graphics/mesa/package.mk
Space delimited lists are generally easier to work with in shell code, and we only need to convert them to comma-delimited lists where they are ultimately "consumed".
=> config/graphic+mesa: simplify dedupe by using space-delimited lists

packages/multimedia/dav1d/package.mk
Release notes:
- https://code.videolan.org/videolan/dav1d/tags/0.2.2
- https://code.videolan.org/videolan/dav1d/tags/0.3.0
I testet it on my Generic i3-6100 & J3455 systems. The SSSE3 gave the Celeron a nice speed boost & lowered the average CPU usage from ~350% to under 300%
=> dav1d: updated to 0.3.0 / cleaned up

packages/web/curl/package.mk, packages/web/nghttp2/package.mk
Adds http2 support for curl. Tested on RPi2 without an issue. test results below.
curl --version
curl 7.62.0 (armv7ve-libreelec-linux-gnueabi) libcurl/7.62.0 OpenSSL/1.0.2q zlib/1.2.11 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2018-10-31
Protocols: file ftp ftps http https rtmp rtsp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
curl --http2 -I https://http2.akamai.com/
HTTP/2 200
server: Apache
etag: "9068c20f1c727825919f58f136cdfb91:1506554442"
last-modified: Wed, 27 Sep 2017 23:04:38 GMT
accept-ranges: bytes
content-length: 11710
push: true
rtt: 50
ghost_ip: 184.50.210.229
ghost_service_ip: 23.43.58.76
client_real_ip: X.X.X.X
client_ip: X.X.X.X
myproto: h2
protocol_negotiation: h2
cache-control: max-age=43200
expires: Sat, 23 Feb 2019 …
=> Add support for http2 in curl

packages/linux/package.mk, packages/tools/u-boot-tools/package.mk
If a host doesn't have `mkimage`, building `uImage` would fail. This PR adds support to build host `mkimage`.
Another way of solving this would be to add `uboot_tools` to `scripts/checkdeps`.
Third way to go is to add `u-boot-tools` host-only package, similar to `u-boot-tools-aml`.
=> u-boot: support host mkimage

packages/sysutils/busybox/scripts/init, scripts/image, scripts/image_st
For merger post-9.0(?)
This drops OPENELEC_ARCH from /etc/os-release, which may break out of date addons. As Kodi 19 is expected to break plenty of addons too, take the opportunity to drop this variable.
I reversed get_project_arch() in the busybox init because I don't like the idea of the variable falling back as default to what will be a known null value.
=> scripts/image: drop OPENELEC_ARCH

packages/linux/package.mk
When kernel image is compressed, it is first loaded to RAM at load address specified in command line, then unpacks to loadaddr provided by uImage.
For decompressed image not to overwrite compressed data, uncompressed image load address needs to be shifted by compressed image size + 64 kiB alignment.
=> linux: amend uimage load address for proper decompression

packages/addons/addon-depends/ffmpegx/package.mk, packages/emulation/libretro-mame/package.mk, packages/emulation/libretro-picodrive/package.mk, packages/linux/package.mk, scripts/genbuildplan.py
Small cosmetic cleanup to fix a few instances of `==` that have slipped in when the project standard is `=` (see #3055).
I've not bothered to fix 
https://github.com/LibreELEC/LibreELEC.tv/blob/6b93ae6ae0e0d5411256bdce14beea0393ce9eaf/projects/Amlogic_Legacy/packages/device-trees-amlogic/package.mk#L41-L46
as this file is due for the chop soon (#3458)
=> packages: use single = not == for string comparison

tools/pkginfo
Tool to dump fully evaluated package variables for a specific package. Additional parameters will be interpreted as variable names to be evaluated.
For example:
```
$ tools/pkginfo linux PKG_BUILD_PERF
PROJECT=Generic, DEVICE=, ARCH=x86_64
PKG_NAME="linux"
PKG_VERSION="5.0.7"
PKG_SITE="http://www.kernel.org"
PKG_URL="https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.0.7.tar.xz"
PKG_DIR="/home/neil/projects/pullrequest_repos/LibreELEC.tv/packages/linux"
PKG_NEED_UNPACK="/home/neil/projects/pullrequest_repos/LibreELEC.tv/projects/Generic/linux /home/neil/projects/pullrequest_repos/LibreELEC.tv/projects/Generic/patches/linux /home/neil/projects/pullrequest_repos/LibreELEC.tv/projects/Generic/packages/linux /home/neil/projects/pullrequest_repos/LibreELEC.tv/packages/linux …
```
=> tools/pkginfo: simple tool to dump a package.mk

config/functions
Due to missing cpp_args and cpp_link_args in meson.conf ninja builds
of projects with C++ code were performed without CPU optimization
flags (-march, -mcpu, -mtune etc). Add these args so C++ code is
built with proper flags.
=> config/functions: add C++ compiler and linker flags to meson.conf

packages/mediacenter/kodi/patches/kodi-999.99-PR16055.patch
As recommended by @fritsch on Team Kodi slack:
(:+1: from @lrusak)
=> kodi: fix 24fp refresh rate switching

packages/linux/package.mk
When building kernel image, suffixes are 'gz' and 'bz2'.
mkimage requires them to be 'gzip' and 'bzip2'.
=> linux: support creating gz/bz2 uImage for arm64

packages/sysutils/ethmactool/package.mk, packages/sysutils/ethmactool/scripts/ethmactool-config, packages/sysutils/ethmactool/system.d/ethmactool-config.service
Ethernet MAC address should be passed by u-boot in device tree. In many cases this address is not correct: `ethmactool` package allows userspace to take care of it.
Currently these are possible sources of "real" MAC:
- Amlogic: cmdline, eFuse, CPU SN
- default: CPU SN
For now the script is only triggered for `eth0` as we don't want to replace MAC on USB ethernet adapters or WiFi adapters.
=> ethmactool: new package for getting HW MAC address or generating from CPU SN

packages/debug/xorg-intel-gpu-tools/package.mk, packages/graphics/cairo/package.mk, packages/tools/procps-ng/package.mk
This add a new package [xorg-intel-gpu-tools](https://github.com/freedesktop/xorg-intel-gpu-tools).
> IGT GPU Tools is a collection of tools for development and testing of the DRM drivers. There are many macro-level test suites that get used against the drivers, including xtest, rendercheck, piglit, and oglconform, but failures from those can be difficult to track down to kernel changes, and many require complicated build procedures or specific testing environments to get useful results. Therefore, IGT GPU Tools includes low-level tools and tests specifically for development and testing of the DRM Drivers.
I ended up using for some intel stuff I'm working on so I figured I would PR it if anyone else wanted to use it. I didn't actually include it in the build as it is quite big so someone …
=>  xorg-intel-gpu-tools: add package

packages/multimedia/gmmlib/package.mk, packages/multimedia/media-driver/package.mk, packages/multimedia/media-driver/patches/media-driver-0001-remove-x11-dependency.patch
This adds a package for intels new media-driver which will eventually replace intel-vaapi-driver for newer intel platforms
>The Intel(R) Media Driver for VAAPI is a new VA-API (Video Acceleration API) user mode driver supporting hardware accelerated decoding, encoding, and video post processing for GEN based graphics hardware.
I did not include this by default as it is quite large and requires manual user interaction to use it anyways.
For example:
```
LIBVA_DRIVER_NAME="iHD" /usr/lib/kodi/kodi.bin
```
=> add Intel's new media-driver

config/functions
`x86_64` and ARM are both `little` endian architectures. Until such time as we need to support a big-endian architecture (unlikely) this can be hard-coded as `little`.
=> config/functions: endianness in meson cross is always little

packages/tools/u-boot/package.mk
u-boot defconfigs don't enable decompression routines required if we want to use compressed kernel image. Enable them to be able to compress kernel and run it.
=> u-boot: explicitly enable decompression

projects/Generic/options, projects/RPi/options, projects/Rockchip/options, scripts/image
For LE10.
Switch generic too? I'm not sure a user will notice but it should save bandwidth/storage on LE's end.
Benchmarks available here: https://github.com/LibreELEC/LibreELEC.tv/pull/3209
=> rpi: switch to zstd squashfs images

scripts/image_st
Applies https://github.com/LibreELEC/LibreELEC.tv/pull/3212 for single-threaded builds.
=> scripts/image_st: use a 1MB blocksize by default

packages/sysutils/systemd/package.mk
Without this option systemd 241 and newer builds will run git describe
and report the LibreELEC git tree info as version, eg in journal
systemd 8.95.002-927-gb1cdc76 running in system mode.
With version-tag set the version is reported like before
systemd 242 running in system mode.
=> systemd: add version-tag build option

packages/debug/libva-utils/patches/libva-utils-001-fix-build-withouth-x11.patch, packages/graphics/cairo/package.mk, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.14-use-alsa-and-pulse-together.patch, packages/multimedia/intel-vaapi-driver/patches/intel-vaapi-driver-999.01-check-the-interface-from-libva-first.patch, packages/textproc/pugixml/package.mk, packages/textproc/pugixml/patches/pugixml-100.01-always-install-the-pkg-config-file.patch, packages/wayland/libinput/package.mk, packages/wayland/wayland-protocols/package.mk, packages/wayland/wayland/package.mk, packages/wayland/waylandpp/package.mk, packages/wayland/weston/package.mk
- This PR should allow to build `Kodi 18.2` without `X11` and use instead `Wayland/Weston` & `OpenGL ES`
- it updates all packages to the latest versions, added dependencies as `pugixml` & added or updated patches for them
- Generic build tested on an Intel system with these project changes:
```
OPENGL="no"
OPENGLES="mesa"
UVESAFB_SUPPORT="yes"
DISPLAYSERVER="weston"
GRAPHIC_DRIVERS="r300 r600 radeonsi i915 i965 vmware virtio"
```
=> [Wayland] updated all Wayland packages, dependencies & patches

packages/network/samba/package.mk
Addictive Directory vuln: https://www.samba.org/samba/history/samba-4.9.8.html
=> samba: update to samba-4.9.8

scripts/build
Some packages install outside `/usr/*bin`, e.g. `/usr/lib/bluetooth` and executables remain unstripped. Try to strip everything executable except .ko and .so which are handled in separate cases.
All file size differences in an Amlogic-mainline build:
| | Before | After | Diff | Diff % |
| -- | -- | -- | -- | -- |
| /usr/lib/bluetooth/bluetoothd | 783956 | 572456 | -211500 | -26.98% |
| /usr/lib/bluetooth/obexd | 400816 | 305844 | -94972 | -23.69% |
| /usr/lib/dbus/dbus-daemon-launch-helper | 59216 | 39172 | -20044 | -33.85% |
| /usr/lib/libinput/libinput-debug-events | 105508 | 31584 | -73924 | -70.06% |
| /usr/lib/libinput/libinput-list-devices | 66836 | 18516 | -48320 | -72.30% |
| /usr/lib/libinput/libinput-measure | 48472 | 14280 | -34192 | -70.54% |
| /usr/lib/pulse/gsettings-helper …
=> scripts/build: strip all executables in /usr

packages/tools/u-boot-script/package.mk
Some targets require to have scripts for u-boot included in system image. Provide a package to compile them.
=> u-boot-script: add package to compile env scripts for u-boot

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/service/tvheadend42/changelog.txt, packages/addons/service/tvheadend42/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk, packages/multimedia/ffmpeg/package.mk, packages/security/gnutls/package.mk
Updates ffmpeg, ffmpegx, and gnutls to latest versions, and adjusts ffmpeg-tools and tvheadend42 to gnutls being built into image. Addons are tested to build, but I do not use them.
=> ffmpeg: shift to using gnutls

packages/web/curl/package.mk
[Changelog](https://curl.haxx.se/changes.html#7_65_0)
Security fixes:
* [Integer overflows in curl_url_set()](https://curl.haxx.se/docs/CVE-2019-5435.html)
* [TFTP receive buffer overflow](https://curl.haxx.se/docs/CVE-2019-5436.html)
=> curl: update to curl-7.65.0

packages/graphics/libmali/package.mk, packages/graphics/libmali/scripts/libmali-setup, packages/graphics/libmali/system.d/libmali-setup.service
This PR updates libmali to latest to add support for multiple so-files in an image.
`/usr/lib/libmali.so` will be linked to `/var/lib/libmali/libmali.so` when there is multiple .so-files installed.
`libmali-setup` script/service will create the `/var/lib/libmali/libmali.so` symlink based on gpu reported by kernel driver.
Example of `libmali-setup` output:
```
LibreELEC:~ # libmali-setup
GPUINFO: /sys/devices/platform/ffa30000.gpu/gpuinfo
GPU: Mali-T76x 4 cores r0p0 0x0750
LIB: libmali-midgard-t76x-*-r0p0-*.so
LIBMALI: /usr/lib/libmali-midgard-t76x-r14p0-r0p0-gbm.so
```
=> libmali: add support for multiple so-files

packages/linux-firmware/intel-ucode/package.mk, packages/linux-firmware/kernel-firmware/firmwares/any.dat, packages/linux-firmware/kernel-firmware/package.mk
* Latest Intel ucode with ZombieLoad fixes, switch to github repo
* Amlogic vdec firmwares
* Add support for installing project and/or device firmwares
* Add Mediatek mt7662[u] firmwares ([ref](https://forum.kodi.tv/showthread.php?tid=343068&pid=2854648#pid2854648))
=> kernel-firmware/intel-ucode: update to 20190514

packages/tools/u-boot/package.mk, scripts/uboot_helper
If board config is not present, appending project U-Boot settings will cause compilation problem and log would fill whole empty space on disk. Fix it by explicitly checking if config file really exist. If not, compilation will fail later, when makefile won't be able to find defconfig.
This PR also fixes U-Boot board config names for Allwinner project and adds new board, NanoPi M1.
=> Fix U-Boot compilation when board config is missing

packages/linux/modprobe.d/ati_remote.conf
Disabling mouse support in the driver not only makes the mouse
feature of the remote non-functional but also results in a kernel
crash when a pressing a mouse button on the remote.
See https://forum.libreelec.tv/thread/17562-le-9-0-2-freeze-when-ati-remote-is-used/
=> linux: drop ati_remote.conf modprobe file

config/functions
When building concurrently, if two or more processes execute `add_user()` concurrently there is a chance that `ln -sf` will fail with the following error:
```
ln: failed to create symbolic link '${INSTALL}/etc/shadow': File exists
```
This is because `ln -sf` (force create symbolic link) prior to [`coreutils-8.27`](https://github.com/coreutils/coreutils/commit/376967889ed7ed561e46ff6d88a66779db62737a) is NOT atomic.
This is a simple test script - run it concurrently in two different processes to reproduce the error when using `coreutils` prior to 8.27:
```
#!/bin/bash
INSTALL=/tmp/ln-sf-test
add_user() {
mkdir -p ${INSTALL}/etc
ln -sf /storage/.cache/shadow ${INSTALL}/etc/shadow
}
while [ : ]; do
add_user || break
done
echo FAIL
```
Ubuntu 17.10 provides `coreutils-8.26`, and the test …
=> config/functions: ln -sf is not always thread safe

packages/devel/glibc/package.mk
This is a micro-op for glibc's generic (non-SIMD) string and memory functions, removing support for kernels before 4.4. It's a revisit, and lower maintenance burden version, of #2756.
=> glibc: raise minimum kernel supported to 4.4.0

packages/graphics/libmali/package.mk, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H3/options, projects/Allwinner/devices/H6/options
This PR changes `libmali` to depend on kernel drivers for `mali-utgard/midgard/bifrost`. Removes the need to define `ADDITIONAL_DRIVERS` in project/device `options`-file. `rockchip-4.4` is excluded since it has mali driver bundled in kernel tree.
There is currently not a `mali-bifrost` package in master branch, it will be added once Amlogic mainline is merged into master branch.
Only Allwinner is affected by this change at the moment, mainline Amlogic and Rockchip will also benefit from this change once they land in master.
=> libmali: add depends on kernel driver

projects/Allwinner/devices/H6/patches/linux/07-opi3.patch, projects/Allwinner/devices/H6/patches/u-boot/002-orange-pi-3-support.patch
This change adds the "mmc2" definition for the device tree for Orange PI 3 on u-boot and linux. This definition enables the eMMC present on some Orange PI 3 models.
=> Alliwinner: Add eMMC definition to device tree of Orange PI 3

packages/debug/edid-decode/package.mk
The project moved from freedesktop.org to linuxtv.org in 2018.
See https://cgit.freedesktop.org/xorg/app/edid-decode/tree/README
=> edid-decode: switch to current URL and update to latest version

packages/debug/edid-decode/package.mk
The project moved from freedesktop.org to linuxtv.org in 2018.
See https://cgit.freedesktop.org/xorg/app/edid-decode/tree/README
Backport of #3575
=> [le92] edid-decode: switch to current URL and update to latest version

projects/RPi/devices/RPi2/options
dtc:host dependency was already dropped in e3c0a79024a, git rebase worked fine but unfortunately I had a local testing change in my commit so rebase left the commit with only the testing change.
=> fixup slice cleanup, revert accidentally added testing change

distributions/LibreELEC/version
final 9.2 release would have 9.2.0 addon version
x.x.900 is a workaround because we bumped to 9.1 already that was basically a mistake
for future bumps we can use x.x.0, x.x.1, x.x.2, ... x.x.9999,  - 3 digits saves us from trouble and allows maximal flexibility
=> distro: bump ADDON_VERSION to 9.1.900

packages/network/samba/package.mk
Security fixes.
https://www.samba.org/samba/history/samba-4.9.9.html
=> samba: update to samba-4.9.9

config/functions, packages/linux-firmware/kernel-firmware/package.mk, packages/linux/package.mk
If a kernel config is not available, sourcing the `linux` package will hang because we `grep` for content without providing a filename.
=> buildsystem: die if a kernel config is not available

packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/patches/mpv-drmprime-PR6461.patch, packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk, packages/python/devel/waf/package.mk
This PR adds a `mpv` package that is useful for debugging and testing ffmpeg drmprime decoding on mainline and rockchip projects.
Run `mpv --vo=gpu --gpu-context=drm --hwdec=drm/rkmpp/help <path>` when kodi has been stopped to start playback.
Tested on Allwinner (4.20) and Rockchip (4.4/4.20) projects.
Work-in-progress due to awaiting feedback on mpv patch/pull-request.
=> mpv-drmprime: new package

projects/Amlogic/patches/linux/a-meson-integ.patch
The commit "ASoC: hdmi-codec: unlock the device on startup errors"
landed in 5.1.6 and can be dropped in LE.
This fixes kernel patches not applying in current LE master
Note: only scripts/unpack tested so far yet, build is still running
=> Amlogic: fix backport kernel patches for 5.1.9

packages/mediacenter/kodi/package.mk
This PR updates the kodi rockchip tag with minor changes to the Rockchip HDR commit, sync more code with upstream HDR PR and adds support for setting full HDR metadata in the DRM infoframe.
Changes: https://github.com/Kwiboo/xbmc/compare/rockchip_18.3-Leia...rockchip_18.3-Leia-v2
Fixup commit: https://github.com/Kwiboo/xbmc/commit/6beb573e3de1a6db747687468cca7fdd6866e3a9
=> kodi (Rockchip): update to kodi-rockchip_18.3-Leia-v2

scripts/build, scripts/ccache_stats, scripts/checkdeps, scripts/clean, scripts/create_addon, scripts/create_docker_package, scripts/extract, scripts/image, scripts/install, scripts/install_addon, scripts/mkimage, scripts/unpack
Mostly cosmetic.
Adding braces to `scripts` where not used to be consistent, as we're at a point where the build system scripts are now a mixture of variables with and without braces. At some point in the future I'll probably do the same for `config`.
Tested fine here.
=> buildsystem: cleanup scripts, consistent brace usage

packages/sysutils/busybox/scripts/init, scripts/mkimage
I recently watched a [YouTube video](https://www.youtube.com/watch?v=QCdh0VZvBGs&t=381) of someone installing LibreELEC to run only from the USB flash drive. He entered `run` at the boot prompt:
```
Wait for installer to start or press <TAB> for more options (live, run)
```
but in the comments for the video there are several people asking how to install to the HDD, with some even saying it isn't possible...
When you look at the boot message, the confusion is perhaps obvious - we don't mention that `installer` is even an option!
This PR addresses the ommission by changing the boot message to:
```
Wait for installer mode to start or <TAB> for options (installer, live, run)
```
I've tried to fit the updated message within 80 chars to avoid wrapping on most displays (Generic/non-UEFI boot …
=> init: more informative syslinux boot message

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
mpg123 only checks for SDL, not SDL2, so we only built mpg123 with
alsa, oss and pulse support (which is enough) and we ca drop the SDL2
dependency.
=> mpg123: drop dependency on SDL2

packages/multimedia/ffmpeg/package.mk
The ffmpeg patches which add enable/disable-rpi options are now
RPi device specific, so using --disable-rpi breaks builds on non-RPi
projects.
=> ffmpeg: drop --disable-rpi option on non-RPi projects

scripts/unpack
The original change was half arsed. Now it's not.
=> buildsystem: fix scripts/unpack after #3570

scripts/mkimage
If doing unclean rebuild of a device that uses UBOOT_SYSTEM with a static version number, mkimage fails as the output image file already exists in the target/* folder. Adding -f allows gzip to overwrite the existing file allowing the UBOOT_SYSTEM loop to continue. The issue is not seen with Jenkins as we're always building clean, or devel images as the filenames change with each build run.
=> scripts/mkimage: force gzip to overwrite target/*.img.gz

config/noobs/os.json, projects/RPi/devices/RPi4/options, scripts/image
Noobs image build didn't take device specific (distro)config.txt files into account which lead to default (RPi/RPi2) files being installed for RPi4 - and a non-working installation.
The System and especially Storage tarballs were created without fakeroot which lead to the storage partition not being owned by root but by with whatever user/goup the image was built, instead of root, which caused lots of services (including ssh and kodi) fail to start.
The RPi4 options copied the (legacy) noobs supported hex revisions from RPi2/3 which was not correct. This option is only relevant to ancient noobs versions which don't support RPi4 anyway, so we can just drop it from os.json.
=> [le92] fix noobs image creation

packages/compress/pigz/package.mk, packages/devel/glibc/package.mk, packages/virtual/toolchain/package.mk, scripts/mkimage
gzip:
```
real    0m11.084s
user    0m10.731s
sys     0m0.352s
```
pigz:
```
real    0m1.891s
user    0m14.122s
sys     0m0.440s
```
The time to build `pigz` is an extra overhead but this is a small/simple C package (2-3 seconds to build) which should more than offset the time saved when creating the compressed image. U-boot-based projects will see the most benefit from this change.
=> buildsystem: use pigz when compressing images

packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
Package fails to build with undefined references to SSL_new, BN_free, TLS_server_method, and similar. openssl provides these functions in libssl and libcrypto, so add to depends and link them in.
Needs runtime testing still.
=> vdr-plugin-xmltv2vdr: link against openssl

packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml, packages/mediacenter/kodi/package.mk
This sets the cosmetic version for the embedded LE repo add-on to $ADDON_VERSION from distro version config - instead of requiring a manual bump that we inevitably forget.
=> kodi: set @ADDON_VERSION@ in repo addon.xml

packages/mediacenter/kodi/patches/kodi-995.01-revert-always-update-stream-detail.patch
This is a temporary fix for Kodi which is losing data in media libraries. See https://github.com/xbmc/xbmc/issues/16322
Thanks @5schatten
=> kodi: temp fix stream details are being lost once playback ends

packages/mediacenter/kodi/patches/kodi-995.01-revert-always-update-stream-detail.patch
=> kodi: temp fix stream details are being lost once playback ends [backport]

packages/sysutils/systemd/patches/systemd-0300-config-env-unhide-cursor.patch
/etc/98-busybox.conf configures the prompt and TERM.
PR #3326 stopped sourcing /etc/profile, which meant the
prompt no longer includes the HOSTNAME.
Additionally, #3326 removed code which unhides the cursor.
=> systemd: fix issues after #3326

scripts/build, scripts/unpack
Small improvement when unpacking packages with a `PKG_DEPENDS_UNPACK` property.
Currently, when running `scripts/unpack TexturePacker` which has `PKG_DEPENDS_UNPACK="kodi"`, only the `TexturePacker` package is unpacked. Ideally, we would want to unpack `kodi` first, then unpack `TexturePacker`. 
With this change, the package being unpacked will now recursively unpack all packages in `PKG_DEPENDS_UNPACK`, which is better.
I've also moved the `ACTIVE` announcement to occur _after_ cleaning and stamp checking, so that the unpack process doesn't become "active" if the package is already unpacked.
The download call (`scripts/get`) also doesn't need to happen if the package is already unpacked, so again move that until after we clean/check stamps.
=> buildsystem: small unpack improvements

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
mpg123 only checks for SDL, not SDL2, so we only built mpg123 with
alsa, oss and pulse support (which is enough) and we ca drop the SDL2
dependency.
Backport of #3593
=> [le92] mpg123: drop dependency on SDL2

packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
`mpv-drmprime` fails to build when built after `vfs.libarchive` because then `libarchive` is automagically enabled, and we don't build `libarchive` with `gnutls` or `bzip2` support so these symbols fail to be resolved when linking `mpv-drmprime`.
The fix is to disable all options that are determined automagically, resulting in a reproducible build.
=> mpv-drmprime: disable automagic options

packages/linux/package.mk
Linux 5.2 now contains Lima and Panfrost and Panfrost has rudimentary detection for Bifrost GPUs (5.1 patches only detect Midgard). Amlogic current uses a single kernel defconfig for both images and we'd like that to continue, so to use the Mali Bifrost blob/driver we now need to ensure in-kernel Panfrost is disabled. As people are also/still experimenting with the Mali Utgard blob in Amlogic images we also apply the same logic to Lima.
=> linux: disable lima/panfrost when using libmali

packages/tools/nano/package.mk
```
2019.06.18 - GNU nano 4.3 "Musa Kart"
â€¢ The ability to read from and write to a FIFO has been regained.
â€¢ Startup time is reduced by fully parsing a syntax only when needed.
â€¢ Asking for help (^G) when using --operatingdir does not crash.
â€¢ The reading of a huge or slow file can be stopped with ^C.
â€¢ Cut, zap, and copy operations are undone separately when intermixed.
â€¢ M-D reports the correct number of lines (zero for an empty buffer).
```
https://www.nano-editor.org/dist/v4/NEWS
=> nano: updated to v4.3

config/arch.aarch64, config/arch.arm
When compiling glibc for cortex-a9, the following errors appears:
`cc1: error: switch -mcpu=cortex-a9 conflicts with -march=armv7-a switch [-Werror]`
Using `mcpu` with `march` and `mtune` is not recommended and compiler emits warnings/errors when mismatched.
=> config: don't use mcpu switch for arm and aarch64

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.11.html
Not worth backporting to 9.2.
=> samba: update to samba-4.9.11

packages/x11/lib/libX11/patches/libX11-building-makekeys-build-tool-when-cross-compiling.patch
Needed for building on arm (and using with jre/bd-j menus).
=> libX11: remove makekeys dependency on X headers

packages/network/connman/package.mk
Whoops. Didn't cause any problems, but should have been removed.
=> connman: small fixup after 3525ffb

scripts/checkdeps
Uppercase P according to my local install and https://apps.fedoraproject.org/packages/perl-XML-Parser.
=> add a few missing dependencies for fedora, gentoo and arch

packages/tools/u-boot/package.mk, projects/Allwinner/bootloader/firmware, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H6/options, projects/Amlogic/options, projects/Rockchip/options
i.MX8 requires that firmware be copied into the u-boot root directory prior to building.
This PR allows us to do the following:
1) Specify if a package needs to be unpacked prior to building
2) Have a `firmware` script that copies the require files before building
I've done it this way to keep it platform agnostic. If a project/device doesn't need any firmware then leaving it blank/undefined will cause no harm. If someone has a better idea please advise.
The requirement for i.MX8 is laid out here https://github.com/u-boot/u-boot/blob/master/board/freescale/imx8mq_evk/README#L18-L24
=> u-boot: add support for installing firmware into the u-boot root directory

packages/addons/addon-depends/lcdd-depends/serdisplib/package.mk, packages/graphics/bcm2835-driver/package.mk, scripts/build
Inspired by #3639 
Packages should only modify the contents of `${SYSROOT_PREFIX}` during installation (including `pre_` and `post_`) which is when the package will be reading/writing to the _isolated_ sysroot. At all other times the package will be accessing the _shared_ sysroot when it is recommended that such access is read-only (ie. no writing).
This PR fixes two packages that were breaking this rule.
Since the `LINK_NAME` (`${i}`) in the isolated sysroot may already be a symbolic link (ie. `/opt/vc/lib` -> `/usr/lib`) we must always treat the `LINK_NAME` as a normal file and avoid dereferencing it, else we will create a new `TARGET` file within the dereferenced link (ie. `/usr/lib/lib`).
This PR fixes this issue.
Some packages are creating symbolic links that point to the build host …
=> buildsystem: fix symbolic link fixups

packages/sysutils/busybox/scripts/init
The current splash image selection logic is unnecessarily complicated, particularly with regard to OEM images. This PR simplifies it.
=> init: clean up splash image selection

packages/sysutils/systemd/patches/systemd-0400-eat-up-rrdrand-on-amd.patch
[Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Ryzen-3K-RdRand-Systemd-Maybe)
=> systemd: eat up RDRAND values seen on AMD cpus

tools/distro-tool
`distro-tool` tweaks, mainly improving package load performance, halving the time required - 30-40 seconds now about 15 seconds - on the storage server (and significantly quicker when using `--path-filter` etc.).
Kinda nice when having to run this thing a couple dozen or more times...
=> distro-tool: halve the time required to generate workload

config/functions, config/multithread, packages/linux-driver-addons/dvb/crazycat/package.mk, packages/linux-driver-addons/dvb/dvb-latest/package.mk, packages/linux/package.mk, scripts/get_archive, scripts/get_file, scripts/get_git, scripts/unpack, tools/mtstats.py
Add support for absolute paths to `PKG_PATCH_DIRS`, simplifying #3635 
Stop using a sub-process around the call to `unpack()` as this creates undesirable non-standard behaviour - any variables modified within the function call are "lost" as a result of being modified in the sub-process.
Fix misconfigured packages, and remove files that no longer serve any purpose since the introduction of `PKG_DEPENDS_UNPACK`.
=> buildsystem: add absolute patch dirs, remove unecessary sub-process, other cleanup

packages/sysutils/systemd/patches/systemd-0400-eat-up-rrdrand-on-amd.patch
=> systemd: eat up RDRAND values seen on AMD cpus [backport]

packages/addons/driver/steamcontroller/package.mk
adding a stub addon was missed at https://github.com/LibreELEC/LibreELEC.tv/pull/3674
=> steamcontroller: initial package (broken)

distributions/LibreELEC/version
This makes sure the RPi4 LE addons get rebuilt by Jenkins and distributed to users
=> bump ADDON_VERSION to 9.1.901

packages/wayland/wayland/package.mk
This should fix building H6 addons on jenkins.
=> wayland: Fix dependencies

packages/sysutils/udevil/udev.d/95-udevil-mount.rules
This patch includes /dev/nvme* block devices (for example, m.2 SSDs) in udevil's udev.d rules so they are auto-mounted along with SCSI disks, MMC, discs, etc.
=> Include /dev/nvme* for automounting m.2 devices

packages/mediacenter/kodi/package.mk
Kodi occasionally fails to build due to https://github.com/xbmc/xbmc/issues/16000.
It appears that `ninja` is more likely to cause this failure than `cmake-make` - I've tested 1,000 `cmake-make` Kodi builds with 0 (zero) failures, and 250 `ninja` builds with 4 failures (all due to issue xbmc/16000).
Team Kodi has seen this same failure when using `cmake` and their own Jenkins, so this PR may not eliminate the issue entirely (which could be a `kodi` and/or `cmake` issue, made worse by `ninja`) but should hopefully make it less of an issue for LibreELEC until it is fixed (if it is ever fixed).
=> kodi: building with ninja makes xbmc/1600 more likely - don't use ninja

packages/mediacenter/kodi/package.mk
Backport of #3698 
Leaving as draft until after 9.1.002 is tagged.
=> kodi: building with ninja makes xbmc/1600 more likely - don't use ninja [Backport]

tools/mkpkg/update_binary-addons, tools/mkpkg/update_common_functions, tools/mkpkg/update_retroplayer-addons
In addition to some general code refactoring a couple of features were added:
Operation mode is now controlled via command line options ("-b" = bump PKG_REV, "-d" = delete git dirs) instead of environment variables.
The previous mode of deleting cloned addon git dirs is now inverted, they are now kept by default. This speeds up addon bumping a lot as the addons gits don't need to be re-downloaded on subsequent runs.
To keep the LE git dir clean it's best to run the scripts in some out-of-tree directory. eg
```
cd addon-bump-tmp
../libreelec-master/tools/mkpkg/update_binary-addons Leia
```
PKG_REV is now automatically reset to 1 on version bumps (if we have version tags) or bumped (if we don't have version tags).
In addition to that PKG_REV can be force-bumped for all addons that weren't …
=> cleanup and improve addon update scripts

packages/graphics/glmark2/package.mk
glmark2 is an OpenGL 2.0 and ES 2.0 benchmark.
I've only build tested for OpenGLES. I don't know if OpenGL works.
This only builds the drm version. No x11 or wayland.
=> glmark2: add package

packages/sysutils/dosfstools/package.mk, packages/sysutils/e2fsprogs/package.mk, scripts/image, scripts/mkimage
We already build fsck.fat in dosfstools:host but didn't install it to toolchain. Add that (plus fatlabel which may be helpful, too) and use it in mkimage
Edit: by building e2fsck, mke2fs and tune2fs and installing to toolchain we can drop the dependency on build host tools completely and also remove /sbin from the PATH for mkimage
=> use e2fsprogs/dosfstools from toolchain for image creation

packages/mediacenter/kodi/patches/raspberrypi/kodi-100.14-use-alsa-and-pulse-together.patch
Commit f1ef2f099c5a9312f17508beb1a408d58f791071 missed to
add the "use-alsa-and-pulse-together" for kodi vendor raspberrypi.
Add it back so pulseaudio shows up in Kodi on RPi again.
See also https://forum.libreelec.tv/thread/13245-kodi-18-0-update-for-slice/?postID=123042#post123042
=> kodi (RPi): add missing alsa+pulseaudio patch

packages/debug/edid-decode/package.mk, packages/web/curl/package.mk
edid-decode: fix building when not using the gold linker
curl: 
Update for some changes in configure options
pre_configure_target() was not necessary on an RPi3 build. configure states it doesn't need an   external lib for clock_gettime.
Use libidn2 because it's present
Library paths not used/present because they're only supposed to be necessary if pkg-config isn't working correctly (building fine without here)
=> cleanup: curl, edid-decode

config/functions
if the target ($1) is a symbolic link to a removed file/folder, the
check will fail and the (broken) symbolic link will be not removed.
=> safe_remove: remove also broken symbolic links

packages/devel/parallel/package.mk
20190722 includes startup performance optimisations. I've been using a snapshot of this release since [Jun 25](https://git.savannah.gnu.org/cgit/parallel.git/commit/?id=7aa0394278b6abb439ba6e333f7a80120efa8762) without any issue.
https://lists.gnu.org/archive/html/bug-parallel/2019-07/msg00003.html
=> parallel: update to parallel-20190722

projects/NXP/devices/iMX6/patches/kodi/kodi-100.90-imx-quirk-plane-usage.patch
This patch is needed to allow kodi to run properly on some iMX6 platforms. I've added it as a patch for now as I would like to find a better solution for upstream Kodi.
=> iMX6: kodi: add patch to quirk the plane usage

projects/Allwinner/devices/H6/patches/linux/09-pineh64-enable-usb3.patch, projects/Allwinner/patches/linux/0002-backport-from-5.3.patch
USB3 doesn't work for H6 with kernel 5.2 currently. This PR adds a kernel patch which fixes that. Another patch enables USB3 support on PineH64 board.
=> Allwinner: Fix USB3 support

packages/mediacenter/kodi-binary-addons/audiodecoder.timidity/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.timidity/patches/audiodecoder.timidity-001-dynamic_lib.patch
Build and pack needed libtimidity.so.
See bug report on the [forum](https://forum.libreelec.tv/thread/17956-timidity-problem/?postID=123322#post123322).
Tested in my LE 9.0 Generic environment.
=> audiodecoder.timidity: add libtimidity.so

packages/sysutils/busybox/config/suspend-modules.conf
In some systems, `xpad` times out during suspend:
```
[ 4470.773651] xpad 2-1.5:1.6: timed out waiting for output URB to complete, killing
[ 4475.892774] xpad 2-1.5:1.4: timed out waiting for output URB to complete, killing
[ 4481.011717] xpad 2-1.5:1.2: timed out waiting for output URB to complete, killing
[ 4486.130707] xpad 2-1.5:1.0: timed out waiting for output URB to complete, killing
[ 4486.288630] PM: suspend devices took 20.880 seconds
```
This causes suspend to take a long time to complete. Unloading/reloading
the module during suspend/wakeup successfully works around this issue.
=> busybox: add 'xpad' to SUSPEND_MODULES

packages/devel/cmake/package.mk
A clean Generic & RPi image builds fine.
https://cmake.org/cmake/help/v3.15/release/3.15.html#cmake-3-15-release-notes
=> cmake: updated to v3.15.1 / clean up

projects/Allwinner/devices/H6/patches/u-boot/002-orange-pi-3-support.patch, projects/Allwinner/patches/u-boot/001-sun8i-h3-Add-support-for-the-Beelink-x2-STB.patch
This fixes OrangePi 3 and Beelink X2 image creation after https://github.com/LibreELEC/LibreELEC.tv/pull/3756
=> Allwinner: Fix errors in U-Boot patches

scripts/image, scripts/uboot_helper
Update `scripts/uboot_helper`:
1) Exit with error (1) when invalid arguments are specified
2) Reorganise to simplify/improve validation
3) Redirect errors (including `usage`) to stderr
4) Make `print()` statements more Pythonic
5) Improve `usage` usability by listing information only for the matching project and/or SOC (rather than listing everything)
Previously, calling `scripts/boot_helper` with invalid Project/Device would output no result (ie. no boards would be listed). Now, it will exit with an error (either invalid project or invalid soc), so it's important to not speculatively call `scripts/uboot_helper` with an invalid project/device in order to determine if any boards require processing (`scripts/image` has been updated to address this).
`scripts/image` will now abort if an …
=> buildsystem: validate UBOOT_SYSTEM at start of build

packages/mediacenter/p8-platform/package.mk, packages/mediacenter/p8-platform/patches/p8-platform-02-cmake_install_prefix_toolchain.patch
Aligns us with https://github.com/xbmc/xbmc/blob/master/cmake/addons/depends/common/p8-platform/p8-platform.txt rather than the upstream Pulse-Eight fork.
Bumps to latest commit in anticipation of https://github.com/xbmc/xbmc/pull/16417
Leaving as a draft to allow further testing.
=> p8-platform: switch to correct repo, update to p8-platform-cee64e9

packages/addons/addon-depends/dotnet-runtime-depends/lttng-ust/patches/lttng-ust-0001-namespace-gettid-wrapper.patch, packages/addons/addon-depends/system-tools-depends/lm_sensors/patches/lm_sensors-02-PR192.patch, packages/devel/glibc/package.mk, packages/x11/lib/libpciaccess/package.mk
Start using `safe_remove`.
Need to bump `libpciaccess` due to removal of [`sys/io.h`](https://sourceware.org/glibc/wiki/Release/2.30#A.3Csys.2BAC8-io.h.3E_removed_on_32-bit_Arm)
Add patch for `lttng-ust` (used by `dotnet-runtime`)
Issues:
* ~`lm_sensors` doesn't currently build (https://github.com/lm-sensors/lm-sensors/issues/190)~ fixed by https://github.com/lm-sensors/lm-sensors/pull/192
=> glibc: update to glibc-2.30

packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk
both these programs are only useful for testing outside of kodi
so they shouldn't be in the multimedia-tools package
This also fixes RPi and RPi2 builds of multimedia-tools where mpv-drmprime build fails.
mesa-demos and mpv should be handled like other additional test packages (eg kmscube), for example being pulled in via ADDITIONAL_PACKAGES. Or, as an alternative, grouped into some "devtest" or similar addon.
=> multimedia-tools: drop mesa-demos and mpv

scripts/uboot_helper
`matrix-q` doesn't build as it seems to generate `u-boot.imx` not `u-boot.img`.
```
COPY    u-boot.bin
CFGS    u-boot.cfgout
MKIMAGE u-boot.imx
===================== WARNING ======================
This board does not use CONFIG_DM_PCI Please update
the board to use CONFIG_DM_PCI before the v2019.07 release.
Failure to update by the deadline may result in board removal.
See doc/driver-model/MIGRATION.txt for more info.
====================================================
===================== WARNING ======================
This board does not use CONFIG_DM_VIDEO Please update
the board to use CONFIG_DM_VIDEO before the v2019.07 release.
Failure to update by the deadline may result in board removal.
See doc/driver-model/MIGRATION.txt for more info. …
```
=> NXP/iMX6: drop matrix-q board

packages/linux/patches/default/linux-001-backport-tools-build-check-if-gettid-is-available.patch, packages/linux/patches/raspberrypi/linux-001-backport-tools-build-check-if-gettid-is-available.patch
perf build fails because glibc 2.30 includes a gettid() function:
```
jvmti/jvmti_agent.c:48:21: error: static declaration of 'gettid' follows non-static declaration
48 | static inline pid_t gettid(void)
|                     ^~~~~~
In file included from /home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/unistd.h:1170,
from jvmti/jvmti_agent.c:33:
/home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
34 | extern __pid_t gettid (void) __THROW;
|                ^~~~~~
```
This has already been fixed in the 5.3 kernel tree. Add a backport
commit until the fix dribbles …
=> linux (default, RPi): fix perf build with glibc 2.30

packages/sysutils/busybox/scripts/getedid
Added the active HDMI/DP port to kernel parameters. 
Without it, fixed EDID does not work on Intel Haswell and possibly others.
=> getedid: added the active HDMI/DP port to new kernel parameters

packages/sysutils/util-linux/scripts/mount-swap
When multiple swap partition are present, `$SWAP` contains multiple lines.  A for loop already existed to handle this, but the original variable was still used in the command in the body of the loop.
=> systemd: fix swap partition handling when multiple present

packages/sysutils/busybox/config/busybox-init.conf, packages/sysutils/busybox/scripts/init, packages/sysutils/terminus-font/package.mk, packages/virtual/initramfs/package.mk
Console output (eg during an update or if a filesystem error occurred) is almost unreadable on 4k screens.
Use the terminus 16x32 font instead of the default built-in 8x16 font on display with more than 1080 lines. This is done very eary during init, after load_modules, so that errors from check_disks and subsequent init steps can be properly seen.
Runtime tested with RPi4 connected to 4k TV
=> [le10] use a larger console font on HiDPI displays

packages/network/samba/package.mk
Security fix.
https://www.samba.org/samba/history/samba-4.9.13.html
=> samba: update to samba-4.9.13

packages/mediacenter/kodi-binary-addons/audiodecoder.gme/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.gsf/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.vgmstream/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.wsr/package.mk, packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
inputstream.adaptive and pvr addon updates could be important.
haven't looked at changelogs, only build tested for RPi4
=> [le92] binary addons: update to latest Leia versions

packages/devel/binutils/package.mk, packages/graphics/bcm2835-driver/package.mk, packages/mediacenter/LibreELEC-settings/package.mk, packages/sysutils/busybox/package.mk, packages/sysutils/busybox/scripts/init, packages/sysutils/busybox/scripts/rpi-flash-firmware, packages/sysutils/busybox/system.d/rpi-flash-firmware.service, packages/sysutils/busybox/system.d/rpi-flash-firmware.target, packages/tools/flashrom/package.mk, packages/tools/rpi-eeprom/config/rpi-eeprom-update, packages/tools/rpi-eeprom/package.mk, packages/tools/rpi-eeprom/source/rpi-eeprom-update, projects/RPi/devices/RPi4/options
First stab at this, not yet ready to merge.
It uses the RPi supplied shell and Python scripts to update the bootloader, once these are hosted on an upstream repository (along with the SPI firmware) we can hopefully install from there (I'll adapt this PR as/when it becomes clear where the scripts and firmware will be hosted).
I'm currently patching changes to the scripts as required by LibreELEC, but it would be nice to avoid these changes in future.
I'm only planning on including one version of the SPI firmware (the latest) in the image - I'm not sure there's much point including older firmware versions.
As yet there is no GUI plumbing - this is command line only, using `rpi-eeprom-update`, with backups of existing SPI firmware being written to `/storage/.config/rpifw-backup`.
=> RPi4: add tools for updating SPI bootloader

packages/addons/service/hyperion/changelog.txt, packages/addons/service/hyperion/package.mk
Fix resuming from paused in kodi 18
Backport of #3808. Runtime tested on RPi4
=> [le92] hyperion: Update to version 2019-08-19

packages/graphics/libde265/package.mk, packages/graphics/libheif/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.heif/package.mk
libde265 and libheif using configure because I found no way to disable some stuff via cmake, looks like proper packaging is not intended :(
- libde265 is current git HEAD because last release would otherwise requires patches
- addon is build static otherwise it would require shipping libde265 and libheif libs
test pic (extract zip)
[testppic.zip](https://github.com/LibreELEC/LibreELEC.tv/files/3627569/testppic.zip)
=> imagedecoder.heif addon

packages/sysutils/busybox/scripts/init
Copying SYSTEM to RAM eats up precious memory that'd be better used
for kernel filesystem cache and other things and can takes quite some
time on slower storage devices like SD cards.
Instead of having two options to define a minimum RAM size (below
which SYSTEM won't be copied) and the "noram" option (which disables
copying completely) reverse the logic and use a single "toram" option
which users can set on kernel command line if they want SYSTEM copied
to RAM.
=> init: make copying SYSTEM to RAM opt-in

projects/Amlogic/linux/linux.aarch64.conf, projects/Amlogic/options
This reverts commit ef3d91d8a97e2843463a88a4bafb4cac05d59048, reversing
changes made to b6fff6cbed32a78efd237331db5c50a9113bfd33.
Apparently Amlogic isn't booting with #3841 so I'll revert it entirely as I made the changes blind, and leave Amlogic well alone from now on.
Good luck! :smile:
=> Revert "Merge pull request #3841 from MilhouseVH/le10_amlogic_cleanup"

packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0001-avutil-add-av_buffer_pool_flush.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0002-Add-common-V4L2-request-API-code.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0003-Add-V4L2-request-API-mpeg2-hwaccel.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0004-Add-V4L2-request-API-h264-hwaccel.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0005-Add-V4L2-request-API-hevc-hwaccel.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0006-Add-V4L2-request-API-vp8-hwaccel.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0007-Add-and-use-private-linux-headers-for-V4L2-request-A.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0008-hwcontext_drm-do-not-require-drm-device.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0009-avcodec-h264-parse-idr_pic_id.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0010-avcodec-h264-parse-ref_pic_marking_size_in_bits-and-.patch, packages/multimedia/ffmpeg/patches/v4l2-request-api/ffmpeg-95.0011-HACK-add-dpb-flags-for-reference-usage-and-field-pic.patch, projects/Allwinner/patches/linux/0001-backport-from-5.4.patch, projects/Allwinner/patches/linux/0005-cedrus-hevc.patch, projects/Allwinner/patches/linux/0010-WIP-HEVC-improvements.patch
This PR updates V4L2 request API related patches (FFmpeg and Allwinner Cedrus) to the latest version. Purpose of this is to align all patches with Rockchip driver included by https://github.com/LibreELEC/LibreELEC.tv/pull/3560
=> Allwinner: ffmpeg: Update v4l2 request api chain

projects/Allwinner/linux/linux.aarch64.conf, projects/Allwinner/linux/linux.arm.conf
Some kernel config options were left out during update to Linux 5.3. Add them now.
=> Allwinner: Update kernel configs

packages/readme.md
Documents the `speed` and `size` build flags for packages from #3524. Also proofreading edits to the paragraph after it.
=> Docs: add speed and size build flags to package.mk readme

packages/mediacenter/LibreELEC-settings/package.mk, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/scripts/pastekodi
Backport of #3817 
We need to backport the `pastekodi` script in case we bump the LibreELEC Settings add-on in `libreelec-9.2` in future.
=> kodi: add pastekodi script [backport]

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart
https://github.com/RPi-Distro/pi-bluetooth/commit/d596d06cce9b7cdee857d54b55004a427b6a6dfc
* Don't override the BT address on Pi 4
From @popcornmix:
> I think Pi4 has separate BT mac address in OTP. Earlier Pi's just used bits from serial number. Probably no huge effect, but it's more correct to include that patch.
=> RPi btuart: Sync with upstream 0.1.11

packages/mediacenter/LibreELEC-settings/package.mk, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/scripts/pastekodi
This adds a `pastekodi` script (and `pastecrash` sym link) that will be used by the LibreELEC Settings add-on (https://github.com/LibreELEC/service.libreelec.settings/pull/135).
The advantage is that we can also run this from the command line, obtaining more detailed logs even when Kodi isn't running.
Created as a draft, will add LE Settings add-on bump once it is merged.
=> kodi: add pastekodi script

packages/sysutils/busybox/scripts/init, packages/tools/rpi-eeprom/config/rpi-eeprom-update
RPi4 serial number: `1000000022bba2d2`
RPi3 serial number: `0000000023a4046f`
The top 32 bits are 0x10000000 for Pi4 and 0 for older Pi's.
This was purely added so people wouldn't be able to buy codec licences with a Pi4 serial number.
When network booting, the serial number used when communicating with the TFTP server is the bottom 32 bits, ie. `23a4046f`
Also include a fix for `rpi-eeprom-update` that allows installing firmware to a file system other than `/flash`.
=> init: add fix for RPi4 serial numbers

packages/sysutils/busybox/scripts/init
To have a full set of binaries in the init process as early as possible it now mounts the squashfs direct after mounting /flash.
There is also a hook /flash/post-sysroot.sh for custom scripting. I will use this e.g. for lvm2 and cryptsetup in the init process, because they are very big and i dont like them in initramfs.
build and tested for RPi4
build on top of https://github.com/LibreELEC/LibreELEC.tv/pull/3820
=> busybox: init: mount squashfs early

packages/sysutils/systemd/package.mk
With systemd-debug-generator installed we can use the standard
"systemd.debug_shell" kernel command line parameter to enable the debug
shell. Since systemd 243 the tty can also be changed by appending
"=ttyXYZ" to that parameter.
Use this method instead of enabling the debug shell on all systems
by default.
=> systemd: use upstream method to enable and configure debug shell

packages/sysutils/busybox/scripts/init
I was wondering why the file system corruption found in #3804 was not visible in the boot logs on my generic systems.
Recovery was done as part of the fsck operation but the output redirected to /dev/null. Make the messages visible in dmesg, i.e.:
```
[    6.322266] Checking disk(s):  UUID=0703-3126 UUID=7858ca35-a758-4559-8079-a51ce61415fc
[    8.353237] fsck: CP437: Invalid argument
[    8.353237] fsck: fsck.fat 3.0.28 (2015-05-16)
[    8.353237] fsck: /dev/sdb1: 49 files, 29041/65501 clusters
[    8.353237] fsck: /dev/sdb2: clean, 11586/3735552 files, 1395995/14935040 blocks
```
The `Invalid parameter` error is an issue with dosfstools and may be fixed by updating to [master](https://github.com/dosfstools/dosfstools/commits/master) HEAD with internal CP850 code page (not tested, just a …
=> init: fsck: wait for devices and unhide messages

packages/sysutils/busybox/scripts/init
To have a full set of binaries in the init process as early as possible it now mounts the squashfs direct after mounting /flash.
There is also a hook /flash/post-sysroot.sh for custom scripting. I will use this e.g. for lvm2 and cryptsetup in the init process, because they are very big and i dont like them in initramfs.
Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3825
=> [le92] busybox: init: mount squashfs early

packages/mediacenter/kodi/scripts/pastekodi
No brainer. :)
Old `LibreELEC-settings` code:
```
if os.path.exists('/sys/firmware/efi'):
```
New `pastekodi` code:
```
if [ -f "/sys/firmware/efi" ]; then
```
Bah, `/sys/firmware/efi` is a directory, so we always reported `BIOS` when booting with `UEFI`.
=> kodi: fix pastekodi efi check

packages/addons/addon-depends/rpi-tools-depends/RPi.GPIO/package.mk, packages/addons/tools/rpi-tools/changelog.txt, packages/addons/tools/rpi-tools/package.mk
This should fix issues with RPi4.
See https://forum.libreelec.tv/thread/20436-rpi-gpio-input-pin-pull-up-down-not-working-on-pi-4b/
Only build-tested so far, waiting for confirmation from user
=> update RPi.GPIO to 0.7.0

packages/mediacenter/kodi/scripts/pastekodi
`pastekodi -c` (and `pastecrash -c`) will now output to stdout, which is useful if `http://ix.io` is not available.
=> pastekodi: add option to allow output to stdout

packages/x11/driver/xf86-video-nvidia-legacy/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
Using the (older) host linker may cause errors.
=> xf86-video-nvidia/xf86-video-nvidia-legacy: use toolchain linker

packages/lang/llvm/package.mk
https://releases.llvm.org/9.0.0/docs/ReleaseNotes.html
=> llvm: update to llvm-9.0.0 / updated PKG_URL

packages/linux-drivers/RTL8192EU/package.mk, packages/linux-drivers/RTL8812AU/package.mk
- RTL8192EU: update to RTL8192EU-e7361e9 kernel 5.3 support.
- RTL8812AU: update to RTL8812AU-4aaf486 kernel 5.3 support
~~- RTL8812AU: Repository changed to use a newer version v5.1.5 vs v5.2.20.2.~~
~~RTL8812AU repository contains a newer version, and looks mantained and updated, is used at https://aur.archlinux.org/packages/rtl8812au-dkms-git/ looks a decent upstream for me.~~
=> linux-drivers: update RTL drivers with kernel 5.3 support.

config/functions
This PR sets OpenGL_GL_PREFERENCE to GLVND if either mesa or nvidia is used for the X11 displayserver.
https://cmake.org/cmake/help/v3.15/module/FindOpenGL.html#linux-specific
https://cmake.org/cmake/help/v3.15/policy/CMP0072.html#policy:CMP0072
=> setup_toolchain: add OpenGL_GL_PREFERENCE to target config

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
- enables eventlircd for Imon UltraBay (front panel buttons)
- this will fix the issue with some front panel buttons not being
detected by Kodi (if keycode value is higher than 255)
- no keycode remapping is necessary everything works just fine with default.evmap
=> eventlircd: adding new rule for iMON Panel, Knob and Mouse(15c2:ffdc)

packages/mediacenter/kodi/patches/kodi-999.99-PR16643-always-allow-black-screensaver.patch
This is important for OLED TV owner.
Kodi PR https://github.com/xbmc/xbmc/pull/16643
Build tested for Generic/RPi2/RPi4.
Run time tested for Generic and RPi4.
=> kodi: backport PR16643 always allow black screen saver

packages/compress/zstd/package.mk, packages/security/libgcrypt/package.mk, packages/security/openssl/package.mk, packages/web/curl/package.mk
This should be considered paired with #3880, only these are packages to be considered for 9.2 too. Tested to the extent they're used in an RPi project.
=> Package updates of interest for 9.2

packages/network/samba/package.mk
I noticed when starting a YouTube video with Kodi 18.4 (and also 19), the following error being logged:
```
Oct 15 03:32:58 NUC kodi.sh[1098]: sh: nmblookup: not found
```
[nmblookup](https://www.samba.org/samba/docs/current/man-html/nmblookup.1.html) is being used [by kodi](https://github.com/xbmc/xbmc/blob/05488ed68e4dc4c3cf9e1c4b2907e87bd8f0a26b/xbmc/network/DNSNameCache.cpp#L52) to resolve Samba hostnames, which might be useful and may even explain some issues...
It's a 104KB binary on RPi2/4.
=> samba: enable nmblookup, for kodi

projects/Allwinner/patches/linux/0005-cedrus-hevc.patch, projects/Allwinner/patches/linux/0010-WIP-HEVC-improvements.patch
If HEVC codec stream starts with something other than I-frame, it crashes Cedrus driver. That usually happens with DVB streams.
=> Allwinner: HEVC stability fixes

packages/compress/xz/package.mk, packages/lang/Python3/package.mk, packages/python/devel/meson/package.mk
build tested (incl. addons) for: Generic, RPi2
=> mesonbuild: udate to 0.52

packages/emulation/libretro-stella/package.mk
This is a cherry-pick of https://github.com/LibreELEC/LibreELEC.tv/commit/480fc09d5aa70697900b84594678fbf2e08af72c which is already in `libreelec-9.2`.
=> libretro-stella: fix PKG_LIBNAME

packages/sysutils/busybox/scripts/init
If updating an RPi4 with RPi2.img.gz, the following occurs:
```
UPDATE IN PROGRESS
Please do not reboot or turn off your LibreELEC device!
Found new compressed image file
Decompressing image file... OK
Mounting system partition...
Checking kernel.img.md5... OK
Checking SYSTEM.md5... OK
ERROR: LibreELEC-RPi2.arm-9.1.502.img.gz is not compatible with RPi4.arm hardware - update cancelled.
Current system: RPi4.arm
Update  system: RPi2.arm
Create /storage/.update/.nocompat to disable compatibility checks and risk a non-booting system.
Cleaning up... |umount: can't unmount /storage/.update/.tmp/mnt: Device or resource busy                                                                                                                    done
Normal startup in 60s... 53
```
The system will boot, …
=> init: unmount /update after a failed update

projects/Allwinner/devices/H6/patches/linux/07-opi3.patch, projects/Allwinner/patches/linux/0001-backport-from-5.4.patch, projects/Allwinner/patches/linux/0002-backport-from-5.5.patch
Apart from grouping merged patches, this PR also includes upstreamed patch for OrangePi Win analog audio and one DW-HDMI patch which fixes HDMI audio issue with certain monitors.
=> Allwinner: Pick upstreamed patches

config/functions
Also, remove leading `/` from unit_dir to avoid a double `//` when creating the full path.
=> config/functions: ensure enable_service tells us why it failed

packages/audio/pulseaudio/package.mk
This changes pulseaudio to use the meson build system. All options _should_ be the same other than the fact that there is no way to disable OSS audio with the meson build.
=> pulseaudio: switch to use meson

packages/audio/pulseaudio/package.mk, packages/audio/speexdsp/package.mk
This fixes the following warning:
```
You do not have speex support enabled. It is strongly recommended
that you enable speex support if your platform supports it as it is
the primary method used for audio resampling and is thus a critical
part of PulseAudio on that platform.
```
Note that this commit was done on top of the meson changes in #3928 thus the meson warning in the commit message. Ideally this can merge after the meson changes and I can update this to use meson instead.
=> pulseaudio: enable speex support 

packages/network/avahi/package.mk
This was originally added because SO_REUSEPORT was not available on older kernels
With this setting, avahi-daemon does not use either SO_REUSEADDR or SO_REUSEPORT, which means that other mDNS applications cannot access the multicast udp port 5353 at the same time. This includes mDNS clients which are simply trying to discover other services on the network. One such client exists in a PVR add-on I am writing for Kodi which currently fails in network discovery when run on LibreELEC.
See also https://github.com/grandcat/zeroconf/issues/63
=> avahi: remove disallow-other-stacks=yes

packages/print/freetype/package.mk
Stay in sync with Kodi: https://github.com/xbmc/xbmc/pull/16575
Changes: https://sourceforge.net/projects/freetype/files/freetype2/2.10.1/
Switch to xz as bz2 is not available.
Not yet build tested.
=> freetype: update to freetype-2.10.1

packages/multimedia/ffmpeg/package.mk
This is a fix for the issue with #3900 (plus extending to all other libraries on which `ffmpeg` has a dependency).
Also cleanup code: use braces for variables, and swith to using `+=`
=> ffmpeg: rebuild whenever libraries change

packages/devel/binutils/package.mk
https://www.phoronix.com/scan.php?page=news_item&px=GNU-Binutils-2.33.1-Released
=> binutils: update to binutils-2.33.1

tools/fixlecode.py
Hopefully this tool will be useful in helping automate the cleanup of build system code (`scripts/*`, `config/*`, and `package.mk`'s) so that it is more consistent, initially addressing the following common issues:
1) Updating variable concatenation (appends) to use the `+=` operator, from:
```
PKG_XYZ="${PKG_XYZ} blah"
```
to
```
PKG_XYZ+=" blah"`
```
2) Adding braces `{}` around variables, from:
```
echo "$PKG_XYZ"
```
to
```
echo "${PKG_XYZ}"
```
3) Replacing backticks (``) with dollar parens (`$()`), from:
```
lines=`cat file | wc -l`
```
to
```
lines=$(cat file | wc -l)
```
4. Remove whitespace before semicolon in `if` statements, and `for`/`while` loops, from
```
if [ test ] ; then
```
to
```
if [ test ]; then
```
All fixes are enabled by default, but can be optionally disabled (see …
=> tools/fixlecode.py: initial commit

packages/tools/u-boot/package.mk
i.MX8 requires specifying `make flash.bin` as the target to build. This PR adds the ability to specify the target via the project/device options. Leaving this blank will cause no harm to other platforms that don't need it.
```
UBOOT_TARGET="flash.bin"
```
the u-boot build instructions for i.MX8 can be found here https://github.com/u-boot/u-boot/blob/master/board/freescale/imx8mq_evk/README#L30
=> u-boot: add the ability to specify the u-boot target to build

projects/Amlogic/patches/kodi/kodi-guisize.patch
The Kodi bump from Leia > Matrix needs a rebased guisize patch for Amlogic images to build.
=> amlogic: update kodi-guisize patch after Matrix bump

projects/Allwinner/devices/H6/patches/linux/10-beelink-gs1.patch
Hi,
This add the support for the remote controller ships with Beelink GS1.
The TV section is leave unmapped.
Web is replaced by Subtitle
Mouse is replaced by EPG (Guide)
I'm open to different bindings, if it's more consistent with other remote controllers.
=> Allwinner: H6: Add RC keymap for Beelink GS1

packages/tools/texturecache.py/package.mk
=> texturecache.py: update to texturecache.py-2.5.2 [backport]

packages/linux/patches/default/linux-063-imon_ultrabay-id_0x98.patch
After applying this patch, display type will be set automatically to "LCD",
the front panel's key repeating will be suppresed and a working key table (for the front panel) will be loaded.
=> linux: Adding support for Imon UltraBay (id 0x98) ,which is another "15c2:ffdc" device

packages/graphics/libprojectM/package.mk
`visualization.projectm` doesn't build with the current `libprojectM` - the upstream add-on is using 3.1.1-rc4 for both Leia and Matrix.
https://github.com/xbmc/visualization.projectm/blob/Leia/depends/common/projectm/projectm.txt
I'll include this commit on #3908
=> libprojectM: update to libprojectM-3.1.1-rc4

config/functions, tools/checkunpack
Script to verify that all packages (or a filtered subset) for a given `PROJECT`/`DEVICE`/`ARCH` are capable of unpacking successfully. A summary of failed packages will be listed upon completion.
**NOTE**: This script is currently highly destructive and will remove the entire contents of `${BUILD_DIR}` during testing. In future, this could be avoided by implementing #3140 and updating the script to use a temporary build directory for the purposes of unpacking.
=> tools/checkunpack: mass unpack tester

packages/network/bluez/package.mk
* Fix issue with AVDTP session disconnect timeout handling.
* Mark media endpoint APIs as stable interfaces.
=> bluez: update to bluez-5.52

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.14.html
https://www.samba.org/samba/history/samba-4.9.15.html
4.9.15 is a security release:
*  CVE-2019-10218:
Malicious servers can cause Samba client code to return filenames containing path separators to calling code.
*  CVE-2019-14833:
When the password contains multi-byte (non-ASCII) characters, the check password script does not receive the full password string.
*  CVE-2019-14847:
Users with the "get changes" extended access right can crash the AD DC LDAP server by requesting an attribute using the range= syntax.
=> samba: update to samba-4.9.15

projects/Allwinner/devices/A64/patches/linux/01_a64_hdmi_audio.patch, projects/Allwinner/devices/H3/patches/linux/16-H3-add-HDMI-sound-nodes.patch, projects/Allwinner/devices/H6/patches/linux/05-sound-hack.patch, projects/Allwinner/patches/linux/0004-sun4i-i2s-improvements.patch
It was reported that high bitrate audio doesn't work anymore after I2S driver rework.
Thanks to @codekipper for fixing this.
=> Allwinner: Fix HDMI audio

packages/mediacenter/LibreELEC-settings/package.mk, packages/sysutils/busybox/scripts/init, packages/sysutils/busybox/scripts/rpi-flash-firmware, packages/tools/rpi-eeprom/package.mk
64-bit OS support (https://github.com/raspberrypi/rpi-eeprom/pull/6)
New beta firmware (https://github.com/raspberrypi/rpi-eeprom/pull/7)
help2man fixes (https://github.com/raspberrypi/rpi-eeprom/pull/8)
Cosmetics (https://github.com/raspberrypi/rpi-eeprom/pull/10)
Rpi eeprom config magic (https://github.com/raspberrypi/rpi-eeprom/pull/12)
Pieeprom 2019 09 10 (https://github.com/raspberrypi/rpi-eeprom/pull/15)
2019-09-23 - Beta test for network boot (https://github.com/raspberrypi/rpi-eeprom/pull/19)
Set unused data to zero if size of config is reduced (https://github.com/raspberrypi/rpi-eeprom/pull/20)
2019-09-25 - Beta test update for network boot (https://github.com/raspberrypi/rpi-eeprom/pull/22)
Rpi eeprom config 2 k (https://github.com/raspberrypi/rpi-eeprom/pull/29)
2019-10-08 - …
=> rpi-eeprom: update to latest rpi-eeprom

packages/mediacenter/LibreELEC-settings/package.mk
Once https://github.com/LibreELEC/service.libreelec.settings/pull/143 merges with Python3 fixes, it can be added to this PR.
=> LibreELEC-settings: re-enable bytecode compilation

config/functions, config/optimize, config/options, config/path
After #3524, we now build `kodi` with `-O3` (speed) rather than `-Os` (size). Consequently, when building with `DEBUG=yes` or `DEBUG=kodi` the size of the resulting `kod.bin` is massive (1.1GB up from 545MB on RPi2, 1.6GB up from 712MB for Generic).
This change ensures we only use `-Os` when building a package with debug. Not all packages are similarly bloated like `kodi` (when using `-O2` or `-Og` most packages show a small increase in size), but I don't think there's any benefit in optimising for anything but size whenever debug is enabled.
=> buildsystem: optimize for size when building with debug

packages/security/libgpg-error/patches/0001-gawk50.patch
This fixes 2 build error I ran into:
* u-boot builds a python module, which currently requires installed python2 headers
backport python3 patches and add a dependency for Python3:host, so it works everywhere
* libgpg-error wrt gawk and variable names of reserved keywords
=> build fixes

packages/mediacenter/kodi/scripts/kodi-config
If /storage/.config/kodi.conf doesn't exist (which it doesn't by default), then the failing "test -f" at the end of this script causes it to return a non-zero exit status, which it turn causes systemd to record it as failed when it runs it as a pre-start for the main kodi service  (and show it as such in "systemctl status kodi"), which is ugly. Instead force the exit status back to 0.
=> Make kodi-config return a zero exit status

projects/Allwinner/devices/H3/patches/linux/02-ARM-dts-sun8i-h3-Add-rc-map-for-Beelink-X2.patch, projects/Allwinner/devices/H6/patches/linux/13-Tanix-TX6.patch, projects/Allwinner/patches/linux/0001-backport-from-5.4.patch
This PR adds support for these two remotes.
=> Allwinner: Add support for Belink X2 and Tanix TX6 remotes

packages/mediacenter/LibreELEC-settings/package.mk, packages/sysutils/busybox/scripts/init, packages/sysutils/busybox/scripts/rpi-flash-firmware, packages/tools/rpi-eeprom/package.mk
Backport of #3807, this adds support for updating USB3 firmware, with corresponding firmware.
~Needs to be updated once https://github.com/LibreELEC/service.libreelec.settings/pull/141 is merged.~
=> rpi-eeprom: update with vl805 support [backport]

packages/addons/service/bluetooth-audio/changelog.txt, packages/addons/service/bluetooth-audio/package.mk, packages/addons/service/bluetooth-audio/source/bin/dbusservice.py, packages/addons/service/bluetooth-audio/source/default.py
Move dbus code into a single threaded python process to get rid of multi threaded problems.
The PR is intentionally for LE 9.2 only because of the current Python 3 activities on master where restricted mode was removed. 
Successfully tested on Generic.
After installing *Bluetooth Audio Device Changer* and restarting kodi *LibreELEC Settings Addon* is crashing with:
```
2019-10-08 19:39:12.603 T:139663176087296   ERROR: ## LibreELEC Addon ## oe::load_config ## ERROR: (IOError('file() constructor not accessible in restricted mode',))
2019-10-08 19:39:12.604 T:139663176087296   ERROR: Traceback (most recent call last):
File "/root/tools/libreelec/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel/LibreELEC-settings-f59dcc824fd8fe5b79c0a709a0c70676cc9ab3b1/.install_pkg/usr/share/kodi/addons …
```
=> bluetooth-audio: avoid LE Settings Addon crash

packages/mediacenter/kodi/scripts/kodi-config, packages/mediacenter/kodi/tmpfiles.d/kodi-userdirs.conf
`/storage/.kodi/userdata` is created by [tmpfiles.d](https://github.com/LibreELEC/LibreELEC.tv/blob/85150686feda583445ee7ad35e687eb935865cda/packages/mediacenter/kodi/tmpfiles.d/kodi-userdirs.conf#L4) when booting.
However, when testing a "clean" kodi installation using:
```
cd /storage
systemctl stop kodi
mv .kodi .kodi.bak
systemctl start kodi
```
then the following errors will be logged:
```
Nov 16 02:58:05 NUC systemd[1]: Starting Kodi Media Center...
Nov 16 02:58:05 NUC kodi-config[1789]: cp: can't create '/storage/.kodi/userdata': Path does not exist
Nov 16 02:58:05 NUC kodi-config[1789]: cp: can't create '/storage/.kodi/userdata': Path does not exist
Nov 16 02:58:05 NUC systemd[1]: Started Kodi Media Center.
```
and `sources.xml` and `guisettings.xml` will not be installed.
This PR …
=> kodi-config: create userdata when it doesn't exist

projects/Allwinner/devices/H6/patches/linux/07-opi3.patch, projects/Allwinner/devices/H6/patches/u-boot/008-sunxi-board-fixup-the-BT-address-for-Orange-Pi-3.patch
The driver refuses to use the shipped controller default address.
=> Allwinner: Fixup the bluetooth address on Orange Pi 3

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
update to 34aaf208f983cefc1d3188d43510c4dc4a35238b
fix for WiFi+BT issues in #3961
=> brcmfmac_sdio-firmware: add AP6255 NVRAM for Orange Pi Lite2

packages/graphics/bcm2835-driver/package.mk, packages/tools/bcm2835-bootloader/package.mk
Later firmware versions have a nasty bug that can lead to HDMI
lock-ups when the RPi is fully throttled (eg due to over-temperature).
Note: The bug is fixed in latest RPi firmware version but this contains the
rather experimental DVFS changes that we shouldn't use in LE9.2 stable yet.
=> RPi: revert to firmware 8e688a4

packages/devel/binutils/package.mk
By default binutils 2.33 will automatically build and use it's
bundled zlib version - which isn't obvious from package.mk as
we don't explicitly build the zlib folder.
binutils 2.32 uses the zlib include from it's bundled version but
won't build it and try to link with libz.a from sysroot - which
will either fail (if zlib wasn't built before) or result in a
possible version mix (which isn't nice as well).
Explicitly using the target zlib - like most linux distributions
do - solves these issues and makes the build consistent.
=> binutils: explicitly depend on target zlib

packages/multimedia/ffmpeg/package.mk
ffmpeg carries a patch to enable hevc playback on RPi3. From Slack, the patch is expected to be used with the raspberrypi branch for Kodi. Mixing the ffmpeg patch with upstream Kodi results in a black screen until playback aborts.
=> ffmpeg: rpi ffmpeg patch only for use with rpi kodi

packages/tools/amlogic-boot-fip/package.mk, packages/tools/amlogic-boot-fip/sources/acs_tool.py, projects/Amlogic/bootloader/install
Fix Python nonsense when building Amlogic because Python2 bytecode is being shipped.
Replace it with a decompiled source code version, that works with both Python2 and Python3.
=> amlogic-boot-fip: fix bytecode madness

packages/sysutils/systemd/patches/systemd-0900-backport-do-not-update-exec-deps-on-mountinfo-changes.patch, packages/sysutils/systemd/system.d/storage.mount.d/dependencies.conf
/storage will be unmounted by systemd-shutdown, like /flash.
As the squashfs root has several symlinks to /storage it
should not be unmounted during the normal shutdown process.
This prevents the symlinked files/directories vanishing too early
and also removes the "unmount /storage failed" messages when
netbooting.
Drop-ins for the storage mount unit didn't work before (due to a systemd bug in combination with the order in which we mount filesystems in initramfs), so include the proposed fix which should hopefully make it into the next systemd version.
=> systemd: prevent unmounting storage via umount.target

packages/sysutils/busybox/scripts/init
Using the soft timeout option for NFS mounts is a really bad idea
and the nfs(5) manpage explicitly warns about it's issues:
NB: A so-called "soft" timeout  can  cause  silent  data
corruption  in  certain cases. As such, use the soft op‐
tion only when client responsiveness is  more  important
than  data  integrity.  Using NFS over TCP or increasing
the value of the retrans option may mitigate some of the
risks of using the soft option.
So don't enable it by default, anyone who feels keen to take the
risk can specify it manually on kernel command line.
=> init: don't mount nfs shares with soft option by default

packages/network/avahi/package.mk
If root user not set on the avahi(on ssh server), most of the file explorers using default user(on ssh client) for sftp connections. If you have ssh connection without password setted on your libreelec, file explorers refuse to connect because they are trying to connect with their user.
With this change we can connect libreelec with avahi's published link without a problem.
=> avahi: set root user as default for published sftp

packages/compress/zstd/package.mk, packages/databases/sqlite/package.mk, packages/devel/parallel/package.mk, packages/multimedia/dav1d/package.mk, packages/textproc/libidn2/package.mk, packages/web/curl/package.mk
Nothing too notable here. Zstd image creation should be slightly faster. Dav1d should be faster on older x86 and armv7. The rest of the bumps looked like mostly bugfixes from the changelogs.
Built / tested for RPi.
=> Package Updates November 2019

packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb, projects/Amlogic/filesystem/usr/lib/udev/hwdb.d/70-local-keyboard.hwdb, scripts/install
This is a follow-up to #4019 
Instead of adding hwdb.d files to some selected projects add the configuration for all projects
Only build-tested, the hwdb file was properly added to /usr/lib/udev/hwdb.d but I don't have the specific remote - ping @chewitt can you please test this?
=> add hwdb.d installations from packages, make o2.cz BT remote config globally available

packages/devel/binutils/package.mk
=> [le92] binutils: explicitly depend on target zlib

packages/sysutils/systemd/scripts/userconfig-setup
Cosmetic, really. Not worth backporting.
BEFORE:
```
[ -f /usr/config//rc_maps.cfg.sample ] && rm -f /storage/.config/rc_maps.cfg.sample
[ -f /usr/config//rpi-cirrus-config.sh.sample ] && rm -f /storage/.config/rpi-cirrus-config.sh.sample
[ -f /usr/config//samba.conf.sample ] && rm -f /storage/.config/samba.conf.sample
[ -f /usr/config//sleep.conf.d/sleep.conf.sample ] && rm -f /storage/.config/sleep.conf.d/sleep.conf.sample
[ -f /usr/config//system.d/nfs.mount.sample ] && rm -f /storage/.config/system.d/nfs.mount.sample
[ -f /usr/config//system.d/cifs.mount.sample ] && rm -f /storage/.config/system.d/cifs.mount.sample
[ -f /usr/config//system.d/openvpn.service.sample ] && rm -f /storage/.config/system.d/openvpn.service.sample
```
AFTER:
```
[ -f /usr/config/rc_maps.cfg.sample ] && rm -f …
```
=> userconfig-setup: avoid // in test

distributions/LibreELEC/version
bump version after all 5.3 kernel are merged to properly rebuild and update all addons
=> ADDON_VERSION bump to 9.80.2

packages/addons/addon-depends/librespot-depends/rust/package.mk, packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk, packages/addons/service/librespot/changelog.txt, packages/addons/service/librespot/package.mk
This builds for and runs on RPi4, supports podcasts and does not anymore require avahi.
I will test build for other architectures and port to master in the coming days.
=> librespot: update to 0.1.0

packages/graphics/tiff/package.mk
Now that we include `--enable-xz` in `Python3:target`, when building `tiff` and `Pillow` we are automagically enabling `lzma` support (which comes from `xz`), but we aren't statically linking the `lzma` library when building `tiff`, so we end up with the following run-time error:
```
NUC:~ # python
Python 3.7.5 (default, Nov 30 2019, 00:35:30)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 90, in <module>
ImportError: /usr/lib/python3.7/site-packages/PIL/_imaging.so: undefined symbol: lzma_code
>>>
```
One solution is to add the missing dependency, and tell `tiff` where to find the codec …
=> tiff: fix automagic codec support resulting in undefined symbols

packages/sysutils/busybox/scripts/init
/dev/kmsg does only allow writes up to 976 bytes. Allow larger fsck output by writing line by line.
Bug was reported on [forum](https://forum.libreelec.tv/thread/20713-sed-write-error-during-boot-on-latest-generic-beta/?pageNo=1).
=> init: fsck: fix kmsg log writes

packages/security/nss/package.mk, packages/security/nss/patches/nss-08-tests-broken-since-3.47.patch
The tests added by https://github.com/nss-dev/nss/commit/47e35ec46e958b19c7176800708e1f7903a902e7 do not build when cross-compiling.
=> nss & nspr: update to nss-3.47.1 / nspr-4.23

packages/audio/pulseaudio/config/system.pa
From @fritsch:
```
Are you guys sure you want this: https://github.com/LibreELEC/LibreELEC.tv/blame/85150686feda583445ee7ad35e687eb935865cda/packages/audio/pulseaudio/config/system.pa#L68
having PA open via tcp to everyone
so that every network sink can output via pulse's default device, e.g. BT headset?
...
If it's not a use-case that LE should provide
remove it
makes no sense to announce LE as tcp streaming target
without authentication
```
This module is needed for [network audio](https://wiki.libreelec.tv/pulseaudio#network_audio_receiving), but probably shouldn't be enabled by default - anyone that needs network audio support can load this module themselves in autostart.sh, or via a systemd service.
I'll include this PR in nightly builds - let's see what (if anything) breaks.
=> pulseaudio: don't enable network audio support for everyone by default

packages/mediacenter/kodi/package.mk
Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3908/commits/72ef28e06385ac7e12aae56a13a0607271ea0108
=> kodi: build with ninja once again [backport]

packages/sysutils/systemd/package.mk
`systemd-v244` is no longer creating `/run/utmp`: https://github.com/systemd/systemd/pull/13483 when `utemp` is disabled, which is entirely correct.
Without `utmp`, the following error is logged when logging out of an ssh session as ssh is [unable to write](https://github.com/openssh/openssh-portable/blob/be02d7c/loginrec.c#L1435) to `/var/run/utmp`:
```
Dec 10 20:38:49 rpi22 sshd[855]: syslogin_perform_logout: logout() returned an error
```
According to https://linux.die.net/man/5/wtmp, `utmp` should always exist on Linux, so enable it:
```
Unlike various other systems, where utmp logging can be disabled by removing the file, utmp must always exist on Linux. If you want to disable who(1) then do not make utmp world readable. 
```
Thanks @lrusak
=> systemd: enable utmp support

config/functions, distributions/LibreELEC/options, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/default.py, packages/addons/service/docker/package.mk, packages/addons/service/docker/source/default.py, packages/mediacenter/kodi/package.mk, packages/readme.md, tools/pkgcheck
~Adds a helper to extract the addon id of the specified package (why OpenELEC chose to call the settings package `LibreELEC-settings` rather than use the addon id baffles me to this day).~
Only add the addon id of the configured package to the Kodi manifest if the add-on is enabled, otherwise Kodi will crash on startup.
=> LibreELEC-settings: make it easier to disable, or use alternative

config/functions
Reviewing the `flag_enabled()` code that sets the flag variable (ie. `PKG_SPEED_TARGET_ENABLED` etc.) I noticed the declared variables were not actually visible outside of the `flag_enabled()` function.
From `help declare`:
```
When used in a function, `declare' makes NAMEs local, as with the `local'
command.  The `-g' option suppresses this behavior.
```
Adding the `-g` option would allow the variables to become visible to the caller, meaning this code would work as intended.
However, as the variables are not currently used and I suspect will almost certainly never be used, I'd like to remove support for the declared variables as it complicates the function unnecessarily, could potentially result in a hard-to-debug variable name collision, and is just additional overhead.
=> flag_enabled(): declare is local by default - remove it

projects/RPi/devices/RPi4/options
This change was missed when adding RPi4 support to LE master.
While unsetting KODI_VENDOR works fine ATM it's not correct and
should be fixed.
=> RPi4: set KODI_VENDOR to default

.gitignore, config/options
I normally have several different build-system clones at different stages of "work in progress" so it's useful to support persistent options at $ROOT level in addition to $HOME.
e.g. I have `LIBREELEC_VERSION="9.2.0"` for RPi4 things, and `LIBREELEC_VERSION="9.8.0"` for Amlogic work. I hard-code the version so that scripts I use to automate the pull of update files to test devices have static paths on the build server.
=> options: support per-buildsystem options

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.11.3.html
o  CVE-2019-14861:
An authenticated user can crash the DCE/RPC DNS management server by creating
records with matching the zone name.
o  CVE-2019-14870:
The DelegationNotAllowed Kerberos feature restriction was not being applied
when processing protocol transition requests (S4U2Self), in the AD DC KDC.
=> samba: update to samba-4.11.3

packages/sysutils/lirc/package.mk
This fixes missing alsa_usb plugin.
See also https://forum.libreelec.tv/thread/20940-how-to-activate-ir-receiver-on-soundblaser-extigy/
=> lirc: add dependency on alsa-lib

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/scripts/pastekodi
Make kodi use user configurable /run/libreelec/cacert.pem instead of own copy in /usr/share/kodi/system/certs/cacert.pem.
Add cacert.pem logging to pastekodi in case of configuration errors.
System cacert.pem is usually the same as the kodi one (i.e. #3290).
A bug report can be found in the [forum](https://forum.libreelec.tv/thread/20806-http-s-proxy-how-to-add-my-ca-to-kodi/).
=> kodi: use system cacert.pem

packages/addons/addon-depends/system-tools-depends/vim/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
I'm sorry to push it again, but soon after #4033 was merged, the next Vim 8.x release is out.
So please let's bump it again.
It doesn't happen very often, the previous 8.1 release was out at May 2018.
Right now system-tools addon has following redundant Vim directory structure, where `vim81` is a runtime dir:
```
total 4
drwxr-xr-x 1 root root  476 Dec 24 01:58 vim81/
-rw-r--r-- 1 root root 1384 Dec 24 01:58 vimrc
```
It's needless for this addon.
So this PR also moves Vim runtime to the `vim` directory itself.
=> system-tools: Vim update and move redundant runtime dir

packages/mediacenter/kodi-binary-addons/audioencoder.flac/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.teleboy/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk, packages/mediacenter/kodi-binary-addons/screensaver.stars/package.mk, packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk, packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
pvr.teleboy bump should fix the issue reported here https://forum.libreelec.tv/thread/21010-pvr-teleboy-stream-addresses-has-changed-use-new-version/
RPi4 build of audioencoder.flac, pvr.iptvsimple, pvr.mythtv, pvr.teleboy and pvr.zattoo was fine. I kicked off a Generic build of all changed addons (including the x86_64/GL only addons screensaver.stars, visualization.pictureit and visualization.projectm) but that'll take a while to finish
=> [le92] kodi-binary-addons: update to latest Leia versions

config/functions, packages/graphics/mesa/package.mk, packages/lang/llvm/package.mk, packages/lang/llvm/patches/llvm-config.patch, packages/lang/llvm/patches/no-z3.patch
llvm-config is a compiled host binary used to get infos about the
target installation (sic). It currently lives in the target sysroot,
which may not be usable because now we're mixing build host and
target libraries:
toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/llvm-config-host:
relocation error: /lib/x86_64-linux-gnu/libpthread.so.0: symbol
__libc_vfork version GLIBC_PRIVATE not defined in file
libc.so.6 with link time reference
Move it to $TOOLCHAIN/bin where host binaries belong. But llvm-config
doesn't support spitting out a library path from a different prefix than
its own (which explains the placement in sysroot). Patch that in to
prevail sanity.
Then disable the z3 solver so the target doesn't use build host libraries.
But that's broken too, use debian's patch to fix it up. …
=> llvm: fix cross compilation issues

packages/devel/cmake/package.mk
Build tested all addons for RPi2 OK.
~Currently building all x86 addons.~
x86_64 builds fine.
=> cmake: update to cmake-3.16.0

packages/addons/tools/system-tools/package.mk, packages/compress/p7zip/package.mk, packages/compress/p7zip/patches/p7zip-0100-CVE-2016-9296.patch, packages/compress/p7zip/patches/p7zip-0200-CVE-2017-17969.patch, packages/compress/p7zip/patches/p7zip-0300-CVE-2018-5996.patch, packages/compress/p7zip/patches/p7zip-0400-CVE-2018-10115.patch
p7zip has a very basic build system, which has no support for building into a multi-arch directory.
Consequently it drops the host binaries into `$PKG_BUILD/bin`, and the target binaries are also dropped into the same `$PKG_BUILD/bin`. However if the host `7za` binary is already present when building the target (as it normally would) then `7za` is not created for the target and `system-tools` installs the host binary to the add-on.
This change is hack, based on what we [used to do for dosfstools-v3](https://github.com/LibreELEC/LibreELEC.tv/pull/3858#issuecomment-533950792), but allows `p7zip` to build host and target into arch-specific directories..
I've also added a number of security fixes that other distros have been carrying for some time (copied [from …
=> p7zip: needs helping hand with cross-compiling

packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
This remote revision adds support for long press (as eventlircd is not used); as well as a low battery indicator when the CR-2032 drops below 2.2V
=> Add support for OSMC RF rev 2.5

packages/textproc/expat/package.mk
This PR updates expat build options after the update to 2.2.9, build complains about:
```
-- Configuration
--   Prefix ..................... /usr
--   Build type ................. MinSizeRel
--   Shared libraries ........... ON
--   Character type ............. char (UTF-8)
--
--   Build documentation ........ OFF
--   Build examples ............. ON
--   Build fuzzers .............. OFF
--   Build tests ................ ON
--   Build tools (xmlwf) ........ ON
--   Install files .............. ON
CMake Warning:
Manually-specified variables were not used by the project:
BUILD_doc
BUILD_examples
BUILD_shared
BUILD_tests
BUILD_tools
```
With these changes expat now builds with:
```
-- Configuration
--   Prefix ..................... /usr
--   Build type ................. MinSizeRel
-- …
```
=> expat: update cmake build options

config/multithread, scripts/image, tools/mtstats.py
In order to further optimise the build system we should always output the build stats at the end of each build. This may also permit before/after comparisons when tuning the build system in future.
This is an example of the build stats for an 8-core system (FX-8350, with SSD) building all 688 addon steps (for Generic):
```
Total Build Time: 04:03:35.220 (wall clock)
Accum Build Time: 32:28:41.489 (8 slots)
Breakdown by status (all slots):
Status   Usage         ( Pct )  Count  State
ACTIVE   14:50:18.927  (45.7%)  1648   busy
FAILED     :  :00.000  (00.0%)  0
GETPKG     :  :01.297  (00.0%)  1      busy
IDLE       :09:27.274  (00.5%)  688
LOCKED     :12:27.079  (00.6%)  3781
MUTEX      :  :07.644  (00.0%)  6      busy
MUTEX/W    :  :00.000  (00.0%)  0      stall
STALLED  17:04:24.917 …
```
=> config/multithread: dump build stats

projects/Allwinner/devices/A64/patches/linux/04-Add-frame-inversion-to-correct-multi-channel-audio.patch, projects/Allwinner/devices/H3/patches/linux/17-Add-frame-inversion-to-correct-multi-channel-audio.patch, projects/Allwinner/devices/H6/patches/linux/16-Add-frame-inversion-to-correct-multi-channel-audio.patch
For some reason the mainline i2s driver inverts the frame clock
which in turn maps the audio channels incorrectly when not using
audio passthrough on multi-channel audio.
Adding frame-inversion to the device tree properties fixes the
issue but should be seen as a temporary fix whilst we investigate
the correct default setup of the i2s block.
Signed-off-by: Marcus Cooper <codekipper@gmail.com>
=> Allwinner: Add frame inversion to correct audio channels

packages/mediacenter/LibreELEC-settings/package.mk
```
Andre Heider (5):
Sync help text of the bluetooth toggle with the actual feature
Improve BT wtf codeflow
Only disconnect connected BT devices
Use the BT standby feature for DPMS as well
Add idle timeout feature for BT standby devices
Christian Hewitt (1):
Merge pull request #144 from MilhouseVH/le10_wiz-no-vis
MilhouseVH (4):
service.py: not every window may have a visible attribute
oeWindows.py: add visible attribute to wizard window
Merge pull request #145 from dhewg/pull/bt
Merge pull request #146 from chewitt/updates
chewitt (1):
improve update section titles
```
=> LibreELEC-settings: update to LibreELEC-settings-12ba57a

packages/devel/gettext/package.mk, packages/tools/grub/package.mk
This PR makes `gettext:host` install both runtime and tools in order to install `gettext` binary, fixes building of `grub` package when `gettext` is missing on host.
`grub` package fails with the following error if `gettext` is missing on host.
```
$ scripts/build grub
UNPACK      grub
BUILD      grub (target)
TOOLCHAIN      configure
./bootstrap: 470: ./bootstrap: gettext: not found
./bootstrap: Error: 'gettext' not found
./bootstrap: Please install the prerequisite programs
```
This PR will add extra build time, quick `time` test on my build host:
Only tools (before PR):
```
real    2m35.375s
user    6m1.630s
sys     1m22.207s
```
Both runtime and tools (after PR):
```
real    3m30.435s
user    6m58.925s
sys     1m45.584s
```
=> gettext: build runtime and tools

packages/tools/rpi-eeprom/package.mk
Stop installing `vl805.latest` after https://github.com/raspberrypi/rpi-eeprom/pull/67
=> rpi-eeprom: update to rpi-eeprom-e9290b3

config/arch.arm, packages/security/libgpg-error/package.mk
Following a discussion on https://github.com/zlib-ng/zlib-ng/issues/478 it became apparent that the TARGET_ABI used for arm doesn't reflect the presence of hard float.
I have successfully created images for RPi, RPi2 and Allwinner/A64 with this PR (RPi and RPi2 images also booted OK). Add-ons are yet to be build tested.
Creating as a draft for discussion, and in case any additions are required.
=> config/arm: use eabihf for hard float

packages/mediacenter/kodi/patches/kodi-100.30-addons-refresh-etc-environment.patch, packages/network/openssh/patches/openssh-source-etc-environment.patch, packages/sysutils/systemd/package.mk, packages/sysutils/systemd/scripts/environment-setup, packages/sysutils/systemd/system.d/envconfig.service
Executables (scripts, binaries) installed via add-ons are not accessible to `sshd` unless the full add-on path is specified because profiles are not sourced unless the user actually logs in to an interactive session.
This is a particular issue with `rsync`:
```
hias@lenny:~$ mkdir /tmp/videos
hias@lenny:~$ rsync -avn root@xbmc:~/videos/ /tmp/videos/
sh: rsync: not found
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [Receiver=3.1.3]
hias@lenny:~$ rsync -avn --rsync-path=/storage/.kodi/addons/virtual.network-tools/bin/rsync root@xbmc:~/videos/ /tmp/videos/
receiving incremental file list
```
In the case of `rsync`, the current workaround is to specify the full path of the remote LibreELEC …
=> image: add /etc/environment

tools/mkpkg/update_binary-addons
Extend the unofficial addon update logic to check if a kodi specific branch (Leia, Matrix, ...) is available and if yes bump to the HEAD of the branch. If no such branch exists bump to the HEAD of the default branch (origin/HEAD) as before.
As kodi Matrix is still developed in the master branch, but addons already created Matrix branches add the possibility to optionally specify the addon branch to use. eg:
```
./update_binary-addons master Matrix
```
This fixes visualization.pictureit bumps which incorrectly picked up the master branch instead of Leia/Matrix branches.
=> update_binary-addons: fix unofficial addon bumping

packages/sysutils/tz/package.mk
sync tz with master. This should fix the Brazil timezone issue reported here https://forum.libreelec.tv/thread/21161-wrong-time-on-some-brazilian-timezones-9-2-0/
Brazil DST cancellation was added in 2019b tz release https://github.com/eggert/tz/commit/8d1bcf9425ead6fd3447a658b20a8bb8a385228d
=> [le92] tz: update to 2019c

scripts/clean
This PR changes to use the same color on the newly added `Removing ...` messages as is used the `Removing ...` messages a few lines above.
=> scripts/clean: print build message with color

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.16.html
https://www.samba.org/samba/history/samba-4.9.17.html
Couple of (AD DC related) security fixes in 4.9.17.
=> samba: update to samba-4.9.17

packages/mediacenter/kodi-binary-addons/game.libretro.scummvm/package.mk
Using "-Wl,--as-needed" with ld causes undefined symbols.
This should fix the issue that was reported here:
https://forum.libreelec.tv/core/ticketsystem/ticket/67-scummvm-linker-error/
There was an earlier pull request that was supposed to fix it, but it didn't, see #3479
I am actually not able to test this fix myself, and as far as I understand comments from @vpeter4 it is only reproducible on the automatic build system. So if someone could trigger a build from this branch and make the resulting binary available, I could check if this change actually fixes it.
Also I guess that I would also have to increase PKG_REV, is that right?
=> game.libretro.scummvm: fix linker issue

packages/sysutils/busybox/scripts/init
Support for modules in initramfs was removed more than half a year
ago but I forgot to remove the now useless load_modules function in
init.
=> init: drop support for loading modules in initramfs

packages/sysutils/systemd/scripts/kernel-overlays-setup, packages/sysutils/systemd/system.d/kernel-overlays.service, scripts/image
Create the module and firmware symlink trees in /run/kernel-overlays
instead of /var/lib as recommended by FHS 3.0. This also allows us
to drop the After=var.mount ordering in the systemd service.
=> kernel-overlays: move volatile runtime data to /run

packages/sysutils/e2fsprogs/package.mk
`udev`, `systemd` and `crond` are being enabled automagically, installing `e2scrub` rules, services and cron scripts when detected. We don't need `e2scrub`, so explicitly disable all 3 dependencies to ensure predictable build behaviour.
=> e2fsprogs: disable automagic udev/systemd/crond detection

packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.18.html
Various security fixes.
=> samba: update to samba-4.9.18

config/multithread, scripts/pkgbuilder.py
Small change to improve searching within a combined log.
Now, the start of an individual package log in the combined log will be prefixed with:
```
<<< intel-ucode:host seq 4 <<<
```
and postfixed with:
```
>>> intel-ucode:host seq 4 >>>
```
so if you want to find the start of `intel-ucode:host`, search for `>>> intel-ucode:host`.
If you need to find the end of seq 4 (because it's been referenced as the root failure of another package) then search for `seq 4 <<<`.
=> scripts/pkgbuilder.py: bookend combined log with searchable tags

packages/sysutils/busybox/config/busybox-target.conf, packages/sysutils/dosfstools/package.mk, packages/sysutils/e2fsprogs/package.mk
Backport of #3858 and #4120 
* bumps `dosfstools` and `e2fsprogs` to the latest version used by `master`
* removes the hacky workaround when building `dos2fstools` v4
* remove the automagic randomness of `e2fsprogs` when detecting `udev`/`systemd`/`crond`
* always uses the full-fat `mkfs.vfat` from `dosfstools` (as we sometimes could end up using the more limited `busybox` version, depending on build order)
=> dosfstools/e2fsprogs: bump and fix [backport]

scripts/pkgbuilder.py
Would be nice to get this in sooner than later, although I've only hit this once (just now). Rather obvious now that I look at the code... :blush:
=> scripts/pkgbuilder.py: avoid returning negative timeout which is fatal

packages/devel/glibc/package.mk
Some users when building `glibc:target` have seen the following errors:
```
make[2]: Entering directory '/letv/10/master/build.LibreELEC-Generic.x86_64-9.80-devel/build/glibc-2.30/locale'
.././scripts/mkinstalldirs /letv/10/master/build.LibreELEC-Generic.x86_64-9.80-devel/build/glibc-2.30/.x86_64-libreelec-linux-gnu/locale
.././scripts/mkinstalldirs /letv/10/master/build.LibreELEC-Generic.x86_64-9.80-devel/build/glibc-2.30/.x86_64-libreelec-linux-gnu/locale
mkdir -p -- /letv/10/master/build.LibreELEC-Generic.x86_64-9.80-devel/build/glibc-2.30/.x86_64-libreelec-linux-gnu/locale
mkdir -p -- /letv/10/master/build.LibreELEC-Generic.x86_64-9.80-devel/build/glibc-2.30/.x86_64-libreelec-linux-gnu/locale
python3 -B gen-translit.py < C-translit.h.in > …
```
=> glibc: ensure it uses our $TOOLCHAIN/bin/python3

packages/sysutils/busybox/scripts/getedid
As discussed here: https://forum.kodi.tv/showthread.php?tid=343069&pid=2919267#pid2919267
we might need a copy of the edid.bin locally 
So, here it is ;)
Dropped the kernel check and the different modification for  syslinux/extlinux for intel as well, as we don't need that anymore. Not sure if we still need to check if `syslinux` or `extlinux` is in use. If that's not needed anymore as well, we might also consider dropping that check too
=> [busybox] getedid fixes

packages/debug/libva-utils/patches/libva-utils-001-fix-build-withouth-x11.patch
This is just a simple hack to remove the videoprocess subdir (which requires x11). We don't need the utilities that it provides.
=> libva-utils: fix non x11 build after e46c85e

packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/network/iw/package.mk, packages/network/iw/scripts/setregdomain, packages/network/iw/udev.d/60-iw-regdomain.rules, packages/virtual/network/package.mk
Include iw in image builds (this adds a 200k binary) and add support for configuring the regulatory domain (country) like on other linux distributions.
The regulatory domain is read from .cache/regdomain.conf (which should probably be managed by the LE settings addon), that file should set REGDOMAIN to a valid ISO country code. eg
```
LibreELEC:~ # cat .cache/regdomain.conf 
REGDOMAIN="AT"
```
=> add support for setting wireless regulatory domain

config/graphic, distributions/LibreELEC/options, packages/graphics/libdrm/package.mk, packages/virtual/mediacenter/package.mk
This driver will become the default in mesa 20, let's enable it now to do some pre-testing.
To test you need to use the env variable `MESA_LOADER_DRIVER_OVERRIDE=iris`. This won't be needed with mesa 20.
=> config/graphic: allow using the new intel gallium iris driver

packages/debug/libva-utils/package.mk, packages/multimedia/intel-vaapi-driver/package.mk, packages/multimedia/libva/package.mk
self explanatory.
libva-utils loses a couple utilities but nothing we care about.
=> convert libva related packages to use meson

packages/linux/package.mk, packages/network/wireless-regdb/package.mk, packages/virtual/network/package.mk
wireless-regdb is no longer needed to build current linux kernels so
drop it from linux depends and let wireless-regdb install the regdb
files to the firmware directory.
=> wireless-regdb: install via network instead of linux package

packages/linux-firmware/iwlwifi-firmware/package.mk
Resolve missing firmware issue with 5.1.y, reported on [forum](https://forum.libreelec.tv/thread/21281-support-of-intel-ax200-wifi-card).
=> iwlwifi-firmware: update to iwlwifi-firmware-19ce537 [libreelec-9.2]

packages/addons/addon-depends/system-tools-depends/vim/package.mk
Work around missing install directory error:
cp vimtutor build.LibreELEC-RPi.arm-9.80-devel/install_pkg/vim-8.2.0023/usr/bin/vimtutor
cp: cannot create regular file
'build.LibreELEC-RPi.arm-9.80-devel/install_pkg/vim-8.2.0023/usr/bin/vimtutor': No such file or directory
make[1]: *** [Makefile:2468: installtutorbin] Error 1
=> vim: work around broken make dependencies

packages/network/samba/scripts/smbd-config
Issue reported on the [forum](https://forum.kodi.tv/showthread.php?tid=343069&pid=2919489#pid2919489)
When setting the Samba username and password we're stripping out all non-alphanumeric characters which means we are potentially setting a username and password that is different to the username and/or password entered by the user. Worse still, we don't inform the user that this happened, so the configured and set (via `smbpasswd`) username/passwords don't match, and confusion reigns.
I'm not aware of any limitations relating to Samba usernames or passwords, so it's not at all obvious why we are doing this as the [original commit](https://github.com/OpenELEC/OpenELEC.tv/commit/9a0d1404d7f2df6cff074cf433c728fa2bb4b479) does not make this clear (but does suggest in the associated …
=> samba: stop mangling username and password

packages/addons/addon-depends/multimedia-tools-depends/mesa-demos/package.mk
#3749 removed `mesa-demos` as an add-on dependency, but when building `mesa-demos` via `ADDITIONAL_PACKAGES` nothing is being installed as we were still nopping out the install.
=> mesa-demos: doesn't install anything, fix that

packages/sysutils/busybox/scripts/init
When updating kernel.img and SYSTEM, we momentarily read the size of the existing file which means the percentage progress very briefly reads 100% and then starts incrementing from 0% as the file is overwritten by the new content.
Resolve this by removing the existing file before starting the progress meter thread.
=> init: remove file before overwriting

packages/lang/Python3/package.mk
As per [forum request](https://forum.libreelec.tv/thread/21239-lib2to3-pgen2-parse-missing), include the `lib2to3` module as this is included with "standard" distros such as Ubuntu. Contrary to the forum post, LibreELEC (or OpenELEC, for that matter) has never included `lib2to3` up to this point.
=> Python3: install lib2to3

config/multithread, scripts/pkgbuilder.py
This has been asked for previously, but is easy to implement now.
`image` builds by default will fail immediately after the first error. Normally this is desirable, but if you have several other (potentially large/slow package) jobs active that are almost finished (eg. `llvm`, `gcc:host` etc.) then it's rather annoying to have them all abort only to be restarted from scratch for what might be a trivial error in another package.
This PR adds the option to wait for all those other active jobs to finish before the entire build fails.
Enable this feature by adding `MTIMMEDIATE=no` on the command line. Only works with an `image` build - the `scripts/create_addons` build will ignore all errors and continue building until all packages have been processed.
The default is `MTIMMEDIATE=yes`.
=> scripts/pkgbuilder.py: allow active jobs to finish once an error occurs

projects/Allwinner/options, projects/Amlogic/bootloader/mkimage, projects/Generic/options, projects/NXP/options, projects/RPi/options, scripts/image, scripts/mkimage, scripts/uboot_helper
This PR changes `scripts/mkimage` to install `extlinux.conf` for `UBOOT_SYSTEM=box`, fixes an issue reported in [forum for Rockchip RK3328 box image](https://forum.libreelec.tv/thread/21142-why-no-dtb-for-generic-rockchip-box-with-mainline-kernel/) where dtb and `extlinux.conf` is not added to the image. `UBOOT_VERSION` leftovers is also removed.
For Amlogic `box` variants the uboot_helper dtb is changed to an empty value, the resulting `box` images is still generated without `extlinux.conf`.
~The Amlogic `mkimage` script is changed to not re-generate a custom `extlinux.conf`, this change still needs to be runtime tested on devices.~
=> scripts/mkimage: only configure extlinux for valid uboot_helper dtb

packages/mediacenter/LibreELEC-settings/package.mk
https://github.com/LibreELEC/service.libreelec.settings/pull/147: Add custom regdom option
https://github.com/LibreELEC/service.libreelec.settings/pull/148: improve download performance on fast connections
https://github.com/LibreELEC/service.libreelec.settings/pull/150: ssh password: switch to text mode, disable buffering
=> LibreELEC-settings: update to LibreELEC-settings-377cfa5

packages/network/connman/patches/connman-08-fix_for_building_with_old_headers.patch
This should fix compiling of connman for Rockchip devices on the libreelec-9.2 branch.
Problem:
The Rockchip build fails because some defines were missing from the older Rockchip headers.
Solution:
Add the needed defines if they are missing, the same as is done with wpa_supplicant.
=> [le92] connman: fix compile with older headers

packages/devel/ncurses/package.mk
This fixes "top -b" erroring out with "'dumb': unknown terminal type."
=> ncurses: also include dumb terminfo in fallbacks

config/options
Although `PROJECT` and `ARCH` have sane defaults when not passed on the command line, these 2 variables are not being (re-)exported so some packages (eg. `libretro-mame2010`) fail since `make` doesn't know the arch it's building for.
So, the following fails:
```
scripts/create_addon game.libretro.mame2010
```
with the following error:
```
src/emu/validity.c: At global scope:
src/emu/validity.c:35:57: warning: narrowing conversion of '-3' from 'int' to 'long unsigned int' is ill-formed in C++11 [-Wnarrowing]
35 | UINT8 your_ptr64_flag_is_wrong[(int)(5 - sizeof(void *))];
|                                                         ^
src/emu/validity.c:35:32: error: size '-3' of array 'your_ptr64_flag_is_wrong' is negative
35 | UINT8 your_ptr64_flag_is_wrong[(int)(5 - sizeof(void *))];
| …
```
=> config/otpions: export PROJECT and ARCH defaults

config/functions
Escaping the `/` is no logner necessary if we use a different field delimiter in `sed`. The escaping also resulted in cosmetic misalignment (in `%-105s`), as well as additional processing x3.
=> config/functions: drop unecessary / escaping

config/functions, packages/lang/Python3/package.mk, scripts/build
*.o files were silently removed in scripts/build (for no obvious reason) which prevents shipping *.o files in the LE image. Drop that so we can include IR BPF decoders in the image.
This drop revealed a bug in safe_remove, it's called with wildcards in several places but it only removed the first file so several *.o files from glibc ended up in /usr/lib.
Python3 installs a python.o file eg in /usr/lib/python3.7/config-3.7-x86_64-linux-gnu/python.o, delete this is post_makeinstall_target.
With these changes both RPi4 and Generic images built fine and didn't include any unwanted *.o files.
=> allow packages to install *.o files into the image

packages/addons/addon-depends/jre-depends/apache-ant/package.mk
If this package builds before the `${TOOLCHAIN}/bin` directory has been created then subsequent packages (ie. `make:host`) will fail as they are unable to create the `${TOOLCHAIN}/bin` directory (because it already exists, and is a file not a directory).
=> apache-ant: create TOOLCHAIN/bin before copying file

tools/mkpkg/update_retroplayer-addons
The kodi-game binary addon repo now contains Leia and Matrix,
like the kodi binary addon repo, so make the branch name a
mandatory option.
=> update_retroplayer-addons: stop defaulting to retroplayer branch

packages/emulation/libretro-4do/package.mk
The 4do libretro core was renamed to opera and the old repo now
redirects, leading to a different SHA256.
Correct the SHA256, eventually the core and kodi game addon should
be renamed to reflect the new name.
=> libretro-4do: fix PKG_SHA256

scripts/get_archive
Don't try 10 times to download a file if the hash was incorrect. 
With build_mt you won't see that the hash is wrong till it downloaded the file 10 times. If you need 10 tries to download a file that it fits the hash you should consider fixing the underlying problem instead of depending at those hacks.
This is basically annoying at dev stages if you forgot changing the hash etc.
=> scripts/get_archive: try two times to download file

packages/addons/addon-depends/ffmpegx/package.mk
Fixes compilation with GRAPHIC_DRIVERS="virtio"
=> ffmpegx: only depend on intel-vaapi-driver if intel drivers are build

config/multithread, scripts/pkgbuilder.py
When pkgbuilder.py is terminated with SIGINT (ie. ctrl-c), or exits
immediately due to a failed job, it is sometimes possible for child
subprocesses (ie. build tasks) to remain alive and continue running
in the background.
To fix this, assign each subprocess a new process group identifier,
and capture the pid of each child subprocess so that on shutdown we
can kill the entire child process group (ie. kill the child subprocess,
and all subprocesses the child subprocess may have created) for any
builder processes that are still running.
=> scripts/pkgbuilder.py: assign each subprocess a process group

config/functions, scripts/build, scripts/install, scripts/install_addon, scripts/unpack
This allows additional build failure information to be logged that should help more quickly narrow down the point of failure.
Example:
=> buildsystem: log pkg_call that failed

config/functions, tools/dashboard, tools/distro-tool
Stop logging a failed bash command when interrupting `PROJECT=RPi DEVICE=RPi2 ARCH=arm tools/dashboard`. Anywhere else we don't want/need to log the bash command, add `export NOONEXIT=yes` or use `NOONEXIT=yes . config/options ""`
=> buildsystem: allow onexit trap to be selectively ignored

packages/devel/binutils/patches/nodocs.patch
binutils-2.34/missing: 81: makeinfo: not found
WARNING: 'makeinfo' is missing on your system.
You should only need it if you modified a '.texi' file, or
any other file indirectly affecting the aspect of the manual.
You might want to install the Texinfo package:
<http://www.gnu.org/software/texinfo/>
The spurious makeinfo call might also be the consequence of
using a buggy 'make' (AIX, DU, IRIX), in which case you might
want to install GNU make:
<http://www.gnu.org/software/make/>
make[3]: *** [Makefile:474: binutils.info] Error 127
=> binutils: fix build without texinfo

packages/debug/gdb/package.mk
~~If /usr/lib/libexpat.so exists on host, it's picked instead of that from LE build system. From what I can tell, this issue was present before. However, in older configure logs only warning is issued but now error is returned.~~
Give search path for expat explicitly. This solves issue on some hosts where expat is present in system. Previously expat was set on auto and gdb configure only printed a warning. But now that it's set to "yes" configure script fails if expat isn't found.
=> gdb: fix expat search on some hosts

packages/linux/patches/linux-0000-nop-gcc-plugin.patch
Ping @jernejsk and @HiassofT 
As discussed on Slack with @jernejsk, when running `make oldconfig` the kernel executes `scripts/gcc-plugin.sh g++ g++ gcc`  which means it detects the host configuration and not the build host (ie. `host-g++ host-gcc`).
Some distros (eg. Arch, but not Ubuntu or Debian) include:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/plugin/include/bversion.h
```
The presence of this header results in `scripts/gcc-plugin.sh` enabling plugin support on Arch, but plugin support is not enabled on Ubuntu etc. since this header isn't installed by default.
We don't want different config options being enabled/disabled depending on the distribution, and as 
we don't need plugin support the easiest solution is to disable plugin support by having the script return nothing for …
=> linux: ignore gcc-plugin.sh

packages/mediacenter/kodi/package.mk
Only Generic for now,, RK, RPi, RPi4 are still missing. Build test was fine.
=> kodi: update to 18.6

packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
We have already this version, just to clean it up for the next bump/rebuild of the addons.
Main problem was that there was no release was tagged upstream, this is fixed now.
=> visualization.pictureit: update to 3.0.1

packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk, packages/multimedia/zvbi/package.mk, packages/multimedia/zvbi/patches/zvbi-0010-fix-static-linking.patch, packages/multimedia/zvbi/patches/zvbi-0020-ioctl.patch, packages/multimedia/zvbi/patches/zvbi-0030-ssize_max.patch, packages/multimedia/zvbi/patches/zvbi-0040-fix-clang-support.patch, packages/multimedia/zvbi/patches/zvbi-0050-prevent-test.patch
Merge after https://github.com/xbmc/repo-binary-addons/pull/128
=> inputstream.ffmpegdirect: new addon

packages/network/netbase/package.mk
Debian have retired their old "site" url.
Debian are no longer distributing the 6.0 tar file, but I've uploaded the copy of 6.0 I already had.
```
netbase (6.1) unstable; urgency=medium
* services: added isakmp (500/udp) which was removed by mistake in
6.0 instead of the UDP service. (Closes: #946138)
* services: removed some historical or not actually used ports:
isakmp (500/tcp), socks (1080/udp), ingreslock (1524/udp),
kermit (1649/udp), groupwise (1677/udp), l2f (1701/tcp), msnp (1863),
unix-status (1957/tcp), log-server (1958/tcp), remoteping (1959/tcp),
cisco-sccp (2000/udp), search (2010/tcp), pipe-server (2010/tcp),
gsigatekeeper (2119/udp), gris (2135/udp), cvspserver (2401/udp),
dict (2628/udp), f5-globalsite (2792/udp), gsiftp (2811/udp),
gpsd (2947/udp), gds-db (3050/udp), …
```
=> netbase: fix site url; update to netbase-6.1

packages/multimedia/libbluray/package.mk, packages/multimedia/libbluray/patches/libbluray-01-bump_to_Nevcairiel.patch, packages/multimedia/libbluray/patches/libbluray-02-install-extra-MVC-headers.patch
- changelog is pretty massive, it builds, I have no stuff that uses it
```
2019-06-07: Version 1.1.2
- Add libxml version to pkg-config Requires.private.
- Improve support for NetBSD operating system.
- Improve BD-J compability.
- Improve Java 8+ compability.
- Fix main playlist caching in Windows.
- Fix mark triggering when multiple marks are passed during single read().
- Fix seek bar pop-up at chapter boundary with some discs.
- Fix reading resources indirectly from mounted .jar file.
2019-04-05: Version 1.1.1
- Enable playback without menus when index.bdmv is missing.
- Improve error resilience and stability.
- Improve BD-J compability.
- Fix loading libraries on MacOS / hardened runtime.
- Fix resetting user-selected streams when playing without menus.
- Fix stack overflow when using …
```
=> libbluray: update to 1.1.2

config/options, distributions/LibreELEC/options, projects/Allwinner/devices/A20/options, projects/Allwinner/options, projects/Amlogic/devices/AMLGX/options, projects/Amlogic/options, projects/RPi/devices/Slice/options, projects/RPi/devices/Slice3/options, projects/Rockchip/options
Currently we symlinking/alias addon repos for several devices.
To avoid messing around with server/jenkins configs at every repo bump and the possibility to mess it up, just hard code it into the image what should be used.
With Repo 9.80.3 there is only a single addon build for RK and AW (AW H3). 
This is only a temporary solution till we have some kind of arm32 addon build that could be used by every arm device, a H3 build is what comes quite close to it.
AML could use it too but currently hold back till it has the same kernel version in use.
RPi4 basically the same, RPi 2-3 needs an more relaxed compiler options that should be included into a arm32 "project".
This is an intermediate step to find possible problems.
=> remove need of symlinks for the repository

packages/sysutils/systemd/package.mk
~Currently rc2.~ 245 released.
https://lists.freedesktop.org/archives/systemd-devel/2020-March/044099.html
> It's mostly bufixes, but still 146 commits since -rc1.
The plan is too release the final version at the end of the week.
Regressions and bugs are still being reported, so expect more patches
to go in.
Builds/boots RPi2, RPi4 and Generic without issue (also built `all` addons for same).
=> systemd: update to systemd-245

packages/network/samba/config/samba4-cache.txt, packages/network/samba/package.mk, scripts/checkdeps
https://www.samba.org/samba/history/samba-4.12.0.html
The Parse::Yapp::Driver module is no longer bundled with 4.12.0, so we need to add this as a new build dependency ([bug#14284](https://bugzilla.samba.org/show_bug.cgi?id=14284))
=> samba: update to samba-4.12.0

packages/lang/Python3/patches/Python3-0400-fix-bpo5537.patch
See: https://bugs.python.org/issue5537#msg361962
Forum: https://forum.libreelec.tv/thread/21369-exception-when-trying-to-save-lwpcookiejar-in-addon-on-milhouse-nightly/
Creating as a draft in case there's further discussion/changes in the issue before being marked as "fixed" in Python3.
This is also broken in Python2, and since the fix appears trivial it could be pushed as a backport.
=> Python3: fix year 2038 regression on 32-bit

tools/mkpkg/update_binary-addons
kodi-platform version is no longer managed in kodi's git tree and
needs to be updated manually, like p8-platform
=> update_binary-addons: drop kodi-platform bump

packages/addons/addon-depends/jre-depends/apache-ant/package.mk
Update to latest apache-ant, as Apache [no longer accept](https://support.sonatype.com/hc/en-us/articles/360041287334) http download requests, resulting in this failure:
```
[1;36mUNPACK[0m      jdk-x86_64-zulu
[1;36mUNPACK[0m      apache-ant
[1;33mBUILD[0m      apache-ant [1;37m(host)[0m
[1;35mTOOLCHAIN[0m      manual
... Bootstrapping Ant Distribution
... Compiling Ant Classes
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
... Copying Required Files
... Building Ant Distribution
Buildfile: /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.80-devel/build/apache-ant-1.10.6/build.xml
bootstrap:
check-optional-packages:
prepare:
build:
Created dir: /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9. …
```
=> apache-ant: update to apache-ant-1.10.7

packages/network/iwd/package.mk
systemd tries to create `/etc/iwd` but fails because of the r/o filesystem. iwd doesn't install anything to this directory so let's just disable it for now.
=> iwd: disable using ConfigurationDirectory

packages/audio/alsa-lib/modprobe.d/intel-audio.conf
Blacklist snd_soc_skl so that hda_intel gets used. This fixes audio
not working on NUCs which have a DSP on board.
Users needed snd_soc_skl can override this via an (empty)
/storage/.config/modprobe.d/intel-audio.conf file
Note: build-tested only (and verified that the intel-audio.conf file was included in image) but not runtime tested - I don't have any NUCs.
Also this is for LE9.2 only, for master we can (and probably should) use a different approach, see eg here https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=82d9d54a6c0ee8b12211fa4e59fd940a2da4e063
=> alsa-lib: add modprobe.d file to work around NUC audio issues

packages/network/bluez/package.mk
Changelog:
```
ver 5.54:
Fix issue with HOGP to accept data only from bonded devices.
Fix issue with A2DP sessions being connected at the same time.
Fix issue with class UUID matches before connecting profile.
Add support for handling MTU auto-tuning option for AVDTP.
Add support for new policy for Just-Works repairing.
Add support for Enhanced ATT bearer (EATT).
```
=> bluez: update to bluez-5.54

.gitignore
ignores the tools/mkpkg/*.git folders from update scripts (addons for example)
not 100% sure this syntax is correct, but works for me
=> gitignore: ignore tools/mkpkg/.git files

packages/graphics/libprojectM/package.mk, packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
Enable preset subdirs for libprojectM to make preset selection and visualization change in visualization.projectm work again.
Beside revision bump in visualization.projectm remove the "sed" line without effect.
Successful tested on my LE 9.2 Generic installation.
=> libprojectM: add --enable-preset-subdirs

packages/sysutils/dosfstools/patches/dosfstools-01-silence_backup_boot_sector_diff.patch, packages/tools/installer/scripts/installer
Since dosfstools bump to 4.1 (#3858) mkfs.fat used in installer automatically format the system partition FAT32 instead of FAT16.
One difference in the file system layout is the introduced FAT32 backup boot sector. On Generic build the Syslinux legacy installation is writing the boot sector and omitting the backup boot sector. Therefore fsck.fat complains about differences in boot and backup sector on every boot generating a long diff, i.e.:
```
[    3.451803] fsck: CP437: Invalid argument
[    3.451916] fsck: fsck.fat 4.1 (2017-01-24)
[    3.452089] fsck: There are differences between boot sector and its backup.
[    3.452270] fsck: This is mostly harmless. Differences: (offset:original/backup)
[    3.452476] fsck: 3:53/6d, 4:59/6b, 5:53/66, 6:4c/73, 7:49/2e, 8:4e/66, 9:55/61, 10:58/74
[ …
```
=> installer: use FAT16 for Generic system partition / dosfstools: reduce fsck.fat log spam

packages/linux-firmware/wlan-firmware/package.mk
Update package in order to support old ZyDAS WIFI dongles.
=> wlan-firmwate: Update package

packages/mediacenter/kodi-binary-addons/audiodecoder.timidity/package.mk, packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk, packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk, packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk, packages/mediacenter/kodi-binary-addons/vfs.libarchive/package.mk, packages/mediacenter/kodi-binary-addons/vfs.rar/package.mk, packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk
=> kodi-binary-addons: update to latest versions [LibreELEC-9.2]

packages/sysutils/lirc/patches/lirc-0001-fix-zotac-poll.patch
See https://sourceforge.net/p/lirc/tickets/327/
Fix is reported to work fine https://forum.libreelec.tv/thread/21597-remote-woes-after-updating-to-9-2-1/?postID=137644#post137644
=> lirc: add patch to fix zotac driver

projects/Allwinner/devices/H6/patches/linux/17-Add-GPU-operating-points-for-H6.patch
Panfrost driver doesn't adjust voltage yet, which makes GPU unstable. Fix that. Thanks to @clementperon for patch.
=> Allwinner: H6: Fix panfrost devfreq voltage adjustments

packages/linux-drivers/RTL8812AU/package.mk
Adds support for Tenda U12, see [forum](https://forum.libreelec.tv/thread/6133-rtl8812au-wifi-dongle-on-rpi-3/?postID=135256#post135256).
=> RTL8812AU: update to RTL8812AU-3ec2947

packages/network/iptables/scripts/iptables_helper
I'm pretty sure `check_tether()` has never worked correctly.
The commands:
```
$CONNMANCTL technologies | grep -e -A5 technology/wifi -e 'Tethering = True'`"
$CONNMANCTL technologies | grep -e -A5 technology/ethernet -e 'Tethering = True'`"
```
result in the following errors being logged:
```
Apr 15 04:13:04 NUC systemd[1]: Starting IPTABLES Packet Filtering...
Apr 15 04:13:04 NUC iptables_helper[669]: grep: technology/wifi: No such file or directory
Apr 15 04:13:04 NUC iptables_helper[767]: grep: technology/ethernet: No such file or directory
Apr 15 04:13:04 NUC iptables_helper[768]: Error 'tether': Invalid argument
Apr 15 04:13:05 NUC iptables_helper[836]: Error 'tether': Invalid argument
Apr 15 04:13:05 NUC systemd[1]: Finished IPTABLES Packet Filtering.
```
as `grep -e -A5 …
=> iptables: fix helper script

config/path
Fixes issue mentioned in #4326: we don't want Python adding the user site-packages directory to `sys.path` as the user site-packages may conflict/interfere with our `$TOOLCHAIN` packages, so disable this behaviour by setting `PYTHONNOUSERSITE` (value doesn't matter, just so long as it's set).
Belt & braces: also unset `PYTHONHOME` because bad things are likely to happen if that is ever set in a users profile, or whatever.
=> buildsystem: ignore custom host Python installations

packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat, packages/linux-firmware/kernel-firmware/package.mk
See https://forum.libreelec.tv/thread/21794-help-for-bluetooth-support/?postID=137978#post137978 for the original user report. This should pick the firmware.
=> kernel-firmware: pick BT firmware for USB/QCA9377 cards

packages/mediacenter/kodi-binary-addons/vfs.sacd/package.mk, packages/mediacenter/kodi-binary-addons/visualization.fishbmc/package.mk, packages/mediacenter/kodi-binary-addons/visualization.goom/package.mk, packages/mediacenter/kodi-binary-addons/visualization.starburst/package.mk, tools/mkpkg/update_binary-addons
=> [le92] kodi binary addons: add vfs.sacd and missing visualization addons

packages/mediacenter/kodi-binary-addons/vfs.sacd/package.mk, packages/mediacenter/kodi-binary-addons/visualization.fishbmc/package.mk, packages/mediacenter/kodi-binary-addons/visualization.goom/package.mk, packages/mediacenter/kodi-binary-addons/visualization.starburst/package.mk, tools/mkpkg/update_binary-addons
vfs.sacd is included in the kodi binary addon repo but was missing in LE.
Build-tested for RPi4
=> kodi binary addons: add vfs.sacd and missing visualization addons

projects/Qualcomm/devices/Dragonboard/options
This disables driver add-ons for the Dragonboard to workaround Jenkins build failures. I'm not sure what the root cause is, but current stats show Dragonboard has zero users (which is not unexpected) so the change does not impact anyone in the real world.
=> Dragonboard: temp disable driver-addons to prevent Jenkins failures

packages/mediacenter/LibreELEC-settings/package.mk
Changes:
* Custom WiFi regulatory domain support [(PR154)](https://github.com/LibreELEC/service.libreelec.settings/pull/154)
* Fix divide by zero during download [(PR157)](https://github.com/LibreELEC/service.libreelec.settings/pull/157)
=> LibreELEC-settings: update to LibreELEC-settings-42acf26
