- packages/mediacenter/kodi/package.mk
> [le90] kodi: update to 18.1

- packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch
> [le90] kodi: cleanup Lircmap.xml patch

- packages/tools/texturecache.py/package.mk
> texturecache.py: update to texturecache.py-2.4.9

- config/options
> config/options: ban spaces in paths [backport]

- packages/addons/service/vdr-addon/changelog.txt
- packages/addons/service/vdr-addon/package.mk
- packages/addons/service/vdr-addon/source/bin/vdr.start
backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3303
tx @hudokkow
> [vdr-addon] Fix deprecated VDR_CHARSET_OVERRIDE

- packages/graphics/libdrm/package.mk
- packages/graphics/mesa/package.mk
mesa-19.0.0 needs libdrm >= 2.4.97
> mesa: update to mesa-19.0.0

- packages/network/samba/package.mk
> samba: update to samba-4.9.5 [backport]

- packages/network/samba/package.mk
> samba: update to samba-4.9.6 [backport]

- packages/wayland/libxkbcommon/package.mk
Tested on Generic, RPi & Amlogic_Legacy
> libxkbcommon: updated to 0.8.4 / added meson opts

- packages/x11/data/xkeyboard-config/package.mk
- packages/x11/data/xkeyboard-config/patches/xkeyboard-config-0001-pt-layout.patch
- packages/x11/data/xkeyboard-config/patches/xkeyboard-config-0002-revert-commits-depending-on-unreleased-packages.patch
- added fix for broken pt layout
- updated build
> xkeyboard-config: updated to 2.26

- packages/network/samba/config/smb.conf
> samba: set fruit:model = Xserve for macOS finder

- projects/Allwinner/patches/linux/0002-fixes-from-5.1.patch
Fix linux 5.0.7 compilation error.
> fix Allwinner linux patch

- packages/graphics/libmali/package.mk
Just a bump to pick-up the symlink changes merged in the last couple of days.
> libmali: bump to include symlink changes

- packages/mediacenter/LibreELEC-settings/package.mk
Bumping to include recent feature changes and improvements.
> LibreELEC-settings: bump to include recent changes

- packages/linux/package.mk
arm64 target does not support creating uImage. Build Image first, then wrap it using u-boot's mkimage.
Requires defining UIMAGE_LOADADDR and UIMAGE_ENTRYADDR in project options. These variable names match what is kernel Makefiles.
On Amlogic devices, mainline kernel can be booted with vendor u-boot only if it's packaged into uImage or patched.
> linux: support creating uImage for arm64

- packages/sysutils/busybox/scripts/dtfile
I must have been Zzz when writing this script.
> busybox: fix dtfile path error

- projects/Allwinner/devices/A64/patches/linux/03-opi-win-bt.patch
- projects/Allwinner/options
> Allwinner: Fix BT/WIFI on OrangePi Win

- packages/web/curl/package.mk
- packages/web/nghttp2/package.mk
> Add nghttp2 support

- packages/network/samba/package.mk
Changelog: https://www.samba.org/samba/history/samba-4.9.7.html
> samba: update to samba-4.9.7

- packages/devel/libcec/package.mk
- packages/linux/package.mk
Fixup issues after merging #3458 
Not yet fully build tested.
> fixup build issues after removing amlogic

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
- projects/Allwinner/devices/H3/patches/linux/beelink_x2_wifi.patch
Latest package has firmwares for some modules used on Allwinner boards.
> Update Broadcom firmware package

- packages/mediacenter/LibreELEC-settings/package.mk
Bump for skin compatibility (breadcrumb) fixes.
> LibreELEC-settings: update to LibreELEC-settings-f59dcc8

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
Will cherry-pick into libreelec-9.2 once merged.
> binary-addons: bump to latest Leia

- distributions/LibreELEC/version
9.80/9.80.0 give us enough "space" for later bumps
first alpha is 9.90/9.90.0
> distro: bump OS_VERSION/ADDON_VERSION to 9.80/9.80.0

- config/functions
- packages/linux-firmware/kernel-firmware/package.mk
- packages/linux/package.mk
- scripts/build
- scripts/ccache_stats
- scripts/checkdeps
- scripts/clean
- scripts/create_addon
- scripts/create_docker_package
- scripts/extract
- scripts/image
- scripts/install
- scripts/install_addon
- scripts/mkimage
- scripts/unpack
Backport of #3570
Includes:
#3566 (buildsystem: die if a kernel config is not available)
> buildsystem: cleanup scripts, consistent brace usage [backport]

- scripts/unpack
> buildsystem: fix scripts/unpack after #3591 [backport]

- scripts/mkimage
> scripts/mkimage: force gzip to overwrite target/*.img.gz

- packages/compress/pigz/package.mk
- packages/devel/glibc/package.mk
- packages/virtual/toolchain/package.mk
- scripts/mkimage
> buildsystem: use pigz when compressing images [backport]

- config/graphic
Needed since https://lists.freedesktop.org/archives/mesa-dev/2019-January/214067.html
> config/graphic: build etnaviv and kmsro for imx devices

- packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml
- packages/mediacenter/kodi/package.mk
> kodi: set @ADDON_VERSION@ in repo addon.xml

- packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.10.html
> samba: update to samba-4.9.10

- packages/sysutils/busybox/scripts/init
- scripts/mkimage
> init: more informative syslinux boot message [backport]

- packages/addons/addon-depends/containerd/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/libnetwork/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
- packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch
Compiled & tested on Generic builds with my [PCSX2 Docker image](https://hub.docker.com/r/supervisedthinking/arch-pcsx2).
18.09.7 changelog: https://docs.docker.com/engine/release-notes/#180907
18.09.6 changelog: https://docs.docker.com/engine/release-notes/#18096
> docker: updated to 18.09.7

- packages/addons/addon-depends/containerd/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/libnetwork/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
- packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch
- packages/graphics/mesa/package.mk
- packages/network/samba/package.mk
- scripts/build
- scripts/unpack
Various backports:
#3577 (samba: update to samba-4.9.9)
#3637 (samba: update to samba-4.9.10)
#3621 (buildsystem: small unpack improvements)
#3604 (mesa: update to mesa-19.1.1)
#3625 (docker: updated to 18.09.7)
> backports: various

- packages/tools/nano/package.mk
> nano: updated to v4.3 [backport]

- distributions/LibreELEC/options
- packages/network/connman/package.mk
- packages/network/iwd/package.mk
This is very much a WIP. However it does work and it does work well.
The main caveat is that this relies on the kernel mac80211 framework, so out of tree drivers won't work (and some intree drivers that don't use the mac80211 framework).
I am just making this PR to get some visibility if people want to try and use it.
For those that don't know about it there was a great presentation at ELC about it.
https://youtu.be/yUxpm8ucQB8?list=PLbzoR-pLrL6pSlkQDW7RpnNLuxPq6WVUR
> iwd (inet wireless daemon) support

- packages/network/iwd/package.mk
self explanatory. Probably need to update kernel config options I'll have to figure out which ones.
> iwd: disable seccomp options for now as it breaks the service

- packages/graphics/libdrm/package.mk
https://www.phoronix.com/scan.php?page=news_item&px=libdrm-2.4.99-Released
> libdrm: update to libdrm-2.4.99

- packages/addons/addon-depends/lcdd-depends/serdisplib/package.mk
- packages/graphics/bcm2835-driver/package.mk
- scripts/build
> buildsystem: fix symbolic link fixups [backport]

- scripts/uboot_helper
This also does the following:
1) sort printed output
2) use dashes instead of underscores for board names
3) sort alphabetically
> scripts/uboot_helper: add formatting to the python object

- config/functions
- config/multithread
- packages/linux-driver-addons/dvb/crazycat/package.mk
- packages/linux-driver-addons/dvb/dvb-latest/package.mk
- packages/linux/package.mk
- scripts/get_archive
- scripts/get_file
- scripts/get_git
- scripts/unpack
- tools/mtstats.py
> buildsystem: add absolute patch dirs, remove unecessary sub-process, other cleanup [backport]

- projects/Qualcomm/devices/Dragonboard/options
Just a couple small things that were missed during the initial PR
> Dragonboard fixups

- packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.shadertoy/patches/visualization.shadertoy-0001-remove-unused-egl-headers.patch
> packages: fix shadertoys when building with RPi4 [backport]

- tools/mkpkg/update_binary-addons
- tools/mkpkg/update_common_functions
- tools/mkpkg/update_retroplayer-addons
> [le92] cleanup and improve addon update scripts

- projects/RPi/devices/RPi4/linux/linux.arm.conf
Should have been included with #3533, I ran out of time... last minute additions.
> linux (RPi4): config options for 5.1.18

- packages/compress/zstd/package.mk
https://github.com/facebook/zstd/releases/tag/v1.4.1
> zstd: update to 1.4.1

- packages/lang/llvm/package.mk
llvm & mesa build fine
https://github.com/llvm/llvm-project/releases/tag/llvmorg-8.0.1
> llvm: update to llvm-8.0.1 / updated PKG_URL

- config/functions
> safe_remove: remove also broken symbolic links

- packages/sysutils/dosfstools/package.mk
- packages/sysutils/e2fsprogs/package.mk
- scripts/image
- scripts/mkimage
> [le92] use e2fsprogs/dosfstools from toolchain for image creation

- distributions/LibreELEC/version
> distro: bump ADDON_VERSION to 9.80.1

- packages/sysutils/busybox/sleep.d.serial/99-suspend-modules.sh
Tangentially related to https://github.com/LibreELEC/LibreELEC.tv/pull/3738 (note that the purpose of this PR is to complement and not to replace that PR).
cc: @MilhouseVH
> busybox: allow customizing suspend-modules.conf

- projects/Allwinner/devices/H6/patches/u-boot/004-unreliable-dram.patch
> Allwinner: Add unreliable dram detection fix

- packages/web/curl/package.mk
> curl: update to curl-7.65.3

- packages/textproc/expat/package.mk
> expat: update to expat-2.2.7

- packages/compress/zstd/package.mk
https://github.com/facebook/zstd/releases/tag/v1.4.2
> zstd: update to zstd-1.4.2

- packages/devel/cmake/package.mk
3.15.1 -> 3.15.2 changes: https://cmake.org/cmake/help/v3.15/release/3.15.html#id2
Not yet build tested.
> cmake: update to cmake-3.15.2

- packages/multimedia/dav1d/package.mk
https://code.videolan.org/videolan/dav1d/-/tags/0.4.0
> dav1d: updated to 0.4.0 / updated meson opts

- packages/sysutils/busybox/config/busybox-init.conf
- packages/sysutils/busybox/scripts/init
- packages/sysutils/terminus-font/package.mk
- packages/virtual/initramfs/package.mk
> [le9.2] use a larger console font on HiDPI displays

- projects/Allwinner/devices/H6/patches/u-boot/002-orange-pi-3-support.patch
There is one-off bug in U-Boot patch
> Allwinner: Fix building OrangePi 3 image

- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/patches/rpi4-hevc/ffmpeg-001-pfcd_hevc_optimisations.patch
The update should fix issues with damaged HEVC files as reported here
https://forum.libreelec.tv/thread/17806-raspberry-pi-4-issue-with-damaged-hevc-file/
> Kodi (RPi4): update to latest leia_pi4 version

- packages/multimedia/ffmpeg/package.mk
sync with Kodi Leia branch - see https://github.com/xbmc/xbmc/commit/ec95b7c87362c4edd0586d4dfed535e9baba88a9
> [le92] ffmpeg: update to 4.0.4-Leia-18.4

- packages/mediacenter/kodi-binary-addons/audiodecoder.2sf/package.mk
- packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
- packages/mediacenter/kodi-binary-addons/audiodecoder.dumb/package.mk
- packages/mediacenter/kodi-binary-addons/audiodecoder.modplug/package.mk
- packages/mediacenter/kodi-binary-addons/audioencoder.vorbis/package.mk
- packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
> binary addons: update to latest Leia versions

- packages/multimedia/ffmpeg/package.mk
sync with Kodi master/Leia branch - see https://github.com/xbmc/xbmc/pull/16461
> [le10] ffmpeg: update to 4.0.4-Leia-18.4

- packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.9.12.html
> samba: update to samba-4.9.12

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to LibreELEC-settings-a8481d9

- packages/network/samba/package.mk
> samba: update to samba-4.9.13 [backport]

- packages/emulation/libretro-mame2016/package.mk
Signed-off-by: pretoriano80 <viusflag@libero.it>
> Fixed SHA265 checksum

- packages/linux-firmware/iwlwifi-firmware/package.mk
> iwlwifi-firmware: update to iwlwifi-firmware-8d85157

- packages/multimedia/libvdpau/package.mk
- switched repo to gitlab
- switched to meson toolchain
https://www.phoronix.com/scan.php?page=news_item&px=VDPAU-Library-1.3-Released
> libvdpau: updated to v1.3

- packages/addons/service/hyperion/changelog.txt
- packages/addons/service/hyperion/package.mk
Fix resuming from paused in kodi 18
> [le10] hyperion: Update to version 2019-08-19

- projects/Amlogic/options
- removed wrong addon url
- aligned to "default" options template
- added missing options
> Amlogic: cleanup options

- packages/graphics/mesa/package.mk
> mesa: update to mesa-19.1.6 [backport]

- packages/sysutils/busybox/scripts/init
> [le92] init: make copying SYSTEM to RAM opt-in

- packages/graphics/libde265/package.mk
- packages/graphics/libheif/package.mk
- packages/mediacenter/kodi-binary-addons/imagedecoder.heif/package.mk
backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3830
> imagedecoder.heif addon

- packages/devel/binutils/package.mk
- packages/graphics/bcm2835-driver/package.mk
- packages/mediacenter/LibreELEC-settings/package.mk
- packages/sysutils/busybox/package.mk
- packages/sysutils/busybox/scripts/init
- packages/sysutils/busybox/scripts/rpi-flash-firmware
- packages/sysutils/busybox/system.d/rpi-flash-firmware.service
- packages/sysutils/busybox/system.d/rpi-flash-firmware.target
- packages/tools/flashrom/package.mk
- packages/tools/rpi-eeprom/config/rpi-eeprom-update
- packages/tools/rpi-eeprom/package.mk
- packages/tools/rpi-eeprom/source/rpi-eeprom-update
- projects/RPi/devices/RPi4/options
Backport of #3729, #3802 and #3807
> RPi4: add tools for updating SPI bootloader [backport]

- packages/graphics/libepoxy/package.mk
- packages/x11/driver/xf86-video-nvidia/package.mk
- packages/x11/xserver/xorg-server/scripts/xorg-configure
> [GLVND] restore the mess in some graphic packages

- packages/addons/addon-depends/rpi-tools-depends/RPi.GPIO/package.mk
- packages/addons/tools/rpi-tools/changelog.txt
- packages/addons/tools/rpi-tools/package.mk
> [le92] update RPi.GPIO to 0.7.0

- packages/x11/proto/xorgproto/package.mk
https://lists.x.org/archives/xorg-announce/2019-June/003000.html
> xorgproto: updated to 2019.1

- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/patches/rpi4-hevc/ffmpeg-001-pfcd_hevc_optimisations.patch
this adds the "ffmpeg: Request max hevc clock while running" commit https://github.com/popcornmix/xbmc/commit/9e6b24cd39009855ea88815edcc20a72807e0dc6
> kodi: update RPi4 to latest leia_pi4 version

- projects/Amlogic/bootloader/install
https://forum.libreelec.tv/thread/12330-test-libreelec-images-with-kodi-18-for-s9xxx/?postID=128753#post128753
> fix start u-boot for nanopi-k2

- packages/sysutils/busybox/scripts/init
> init: fsck: wait for devices and unhide messages

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/addons/addon-depends/opus/package.mk
- packages/addons/tools/ffmpeg-tools/changelog.txt
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/security/gnutls/package.mk
> ffmpeg-tools: update ffmpegx, opus, gnutls [le9.2]

- packages/network/samba/package.mk
> samba: enable nmblookup, for kodi [backport]

- packages/compress/zstd/package.mk
- packages/security/libgcrypt/package.mk
- packages/security/openssl/package.mk
- packages/web/curl/package.mk
backport of https://github.com/LibreELEC/LibreELEC.tv/pull/3881
> Package updates backport

- projects/Amlogic/bootloader/mkimage
replace hardcoded values with variables
> Amlogic mkimage: use DISTRO labels

- packages/emulation/libretro-stella/package.mk
> libretro-stella: update to libretro-stella-6d74ad9

- packages/sysutils/busybox/scripts/init
> init: unmount /update after a failed update [backport]

- packages/sysutils/busybox/scripts/init
> init: make umount /update conditional [libreelec-9.2]

- packages/sysutils/open-vm-tools/package.mk
> open-vm-tools: update to open-vm-tools-stable-11.0.1

- packages/network/samba/package.mk
Changelog: https://www.samba.org/samba/history/samba-4.9.14.html
> samba: update to samba-4.9.14

- packages/compress/zstd/package.mk
trivial change to use meson instead of cmake.
> zstd: switch to use meson

- packages/devel/fribidi/package.mk
trivial change to use the meson build system
> fribidi: switch to use meson

- packages/graphics/libdrm/package.mk
- https://www.phoronix.com/scan.php?page=news_item&px=libdrm-2.4.100-Released
- https://lists.x.org/archives/xorg-announce/2019-October/003028.html
> libdrm: updated to 2.4.100 / cleaned up package

- packages/multimedia/dav1d/package.mk
- https://code.videolan.org/videolan/dav1d/-/tags/0.5.0
> dav1d: updated to 0.5.0

- packages/x11/driver/xf86-video-amdgpu/package.mk
- packages/x11/driver/xf86-video-ati/package.mk
xf86-video-amdgpu: https://www.phoronix.com/scan.php?page=news_item&px=xf86-video-amdgpu-19.1-Released
xf86-video-ati: https://www.phoronix.com/scan.php?page=news_item&px=xf86-video-ati-19.1-Released
> AMD driver updates 19.1.0

- projects/Allwinner/patches/kodi/0002-guisize.patch
> Allwinner/kodi: rebase guisize patch for kodi-19

- packages/network/avahi/package.mk
> [backport] avahi: remove disallow-other-stacks=yes

- projects/Allwinner/devices/H6/patches/linux/07-opi3.patch
This PR enables IR on OPi3 and fixes ethernet reboot issue.
> Allwinner: OrangePi 3 improvements

- packages/mediacenter/kodi/scripts/kodi-config
(cherry picked from commit e12e8cb7c41fd5bb6ee8849d574d49891fc928bc)
> Make kodi-config return a zero exit status

- packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
See https://github.com/kodi-game/game.libretro/releases/tag/2.0.0-Matrix
> game.libretro: update to 2.0.0-Matrix

- packages/mediacenter/kodi/scripts/kodi-config
- packages/mediacenter/kodi/tmpfiles.d/kodi-userdirs.conf
> kodi-config: create userdata when it doesn't exist [backport]

- packages/graphics/libmali/package.mk
This fixes several addons builds.
Should this be ported to 9.2?
cc: @InuSasha
> libmali: update to d4000def121b

- distributions/LibreELEC/version
> distro: bump OS_VERSION

- packages/addons/browser/chrome/source/default.py
- packages/addons/service/docker/source/default.py
Not build or run-time tested - there could be more lurking issues that need fixing.
> addons: Python3 changes

- packages/addons/service/mariadb/package.mk
- packages/addons/service/mariadb/patches/mariadb-0001-disable-plugin-auth-pam.patch
Build tested on Generic, but not run-time tested.
> mariadb: update to mariadb-10.4.10

- .gitignore
- config/options
> options: support per-buildsystem options

- packages/sysutils/lirc/package.mk
> [le92] lirc: add dependency on alsa-lib

- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/package.mk
Fixes https://forum.libreelec.tv/thread/21030-system-tools-no-vim-runtime/
> system-tools: add Vim runtime files

- packages/textproc/expat/package.mk
Includes security fixes in 2.2.8.
> expat: update to expat-2.2.9

- packages/addons/addon-depends/librespot-depends/rust/package.mk
- packages/addons/service/librespot/changelog.txt
- packages/addons/service/librespot/package.mk
- packages/addons/service/librespot/patches/librespot-01_notify_kodi.patch
- packages/addons/service/librespot/patches/librespot-02_use_own_pulseaudio_sink.patch
- packages/addons/service/librespot/source/default.py
- packages/addons/service/librespot/source/miscellaneous/service.librespot-alsa.service
- Fix rust compilation
- Update to f67a38d (2019-12-03)
- Use vorbis, which is more reactive than lewton
- Provide ALSA backend for custom installation
- Display some information about new audiotypes such as podcasts
- Python 3 compliant
> librespot: various improvements

- tools/docker/bionic/Dockerfile
- tools/docker/eoan/Dockerfile
- tools/docker/stretch/Dockerfile
- tools/docker/xenial/Dockerfile
This PR is only cosmetics and reorder the packages to install in the docker build containers to match `scripts/checkdeps` for easier comparison.
> tools/docker: reorder to match checkdeps

- packages/mediacenter/kodi/scripts/pastekodi
> pastekodi: avoid cmp this is installed by system-tools [backport]

- tools/mkpkg/update_binary-addons
> [le92] update_binary-addons: fix unofficial addon bumping 

- packages/mediacenter/kodi/patches/kodi-999.99-PR17081.patch
Temporary fix until next bump.
> kodi: fix caching issue accessing repositories

- packages/sysutils/util-linux/package.mk
> util-linux: update to util-linux-2.34

- packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.11.5.html
Various security fixes.
> samba: update to samba-4.11.5

- packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
- scripts/install
> add hwdb.d installations from packages, make o2.cz BT remote config globally available

- packages/linux-drivers/RTL8192EU/package.mk
See https://github.com/MilhouseVH/LibreELEC.tv/pull/7
> RTL8192EU: update to RTL8192EU-83b5aff

- packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.11.6.html
> samba: update to samba-4.11.6

- packages/lang/Python2/package.mk
> Python2: install lib2to3 [backport]

- packages/sysutils/busybox/scripts/getedid
> [busybox] getedid fixes

- packages/mediacenter/LibreELEC-settings/package.mk
Partial backport of #4167 
https://github.com/LibreELEC/service.libreelec.settings/pull/149: improve download performance on fast connections
> LibreELEC-settings: update to LibreELEC-settings-e775b97 [backport]

- packages/addons/addon-depends/jre-depends/apache-ant/package.mk
> apache-ant: create TOOLCHAIN/bin before copying file [backport]

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.17
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.18
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.19
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.20
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.21
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.22
> linux (RPi): update to linux-5.4.22

- tools/mkpkg/update_retroplayer-addons
> [le92] update_retroplayer-addons: stop defaulting to retroplayer branch

- packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
fix to don't rebuild an old version
> visualization.pictureit: rev fix

- packages/multimedia/dav1d/package.mk
Builds, but not yet run-time tested.
> dav1d: update to dav1d-0.6.0

- packages/network/iwd/package.mk
> iwd: fix build after 7eadda0

- distributions/LibreELEC/version
> distro: bump ADDON_VERSION to 9.80.3

- packages/x11/driver/xf86-video-nvidia/package.mk
https://devtalk.nvidia.com/default/topic/1072457
https://www.nvidia.com/Download/driverResults.aspx/157462/en-us
> xf86-video-nvidia: update to xf86-video-nvidia-440.64

- packages/graphics/libprojectM/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
sync version with https://github.com/xbmc/visualization.projectm/blob/3.0.1-Matrix/depends/common/projectm/projectm.txt
> libprojectM: update to 3.1.2

- packages/graphics/libprojectM/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
sync version with https://github.com/xbmc/visualization.projectm/blob/2.3.5-Leia/depends/common/projectm/projectm.txt
> [le92] libprojectM: update to 3.1.2

- packages/databases/sqlite/package.mk
- packages/security/openssl/package.mk
- packages/web/curl/package.mk
Just a couple of the frequently used.
> Package Updates March 2020

- packages/sysutils/lirc/patches/lirc-0001-fix-zotac-poll.patch
See https://sourceforge.net/p/lirc/tickets/327/
backport of #4312
> [le92] lirc: add patch to fix zotac driver

- packages/network/samba/package.mk
https://www.samba.org/samba/history/samba-4.12.1.html
> samba: update to samba-4.12.1

- packages/sysutils/dosfstools/patches/dosfstools-01-silence_backup_boot_sector_diff.patch
- packages/tools/installer/scripts/installer
> installer: use FAT16 for Generic system partition / dosfstools: reduce fsck.fat log spam

- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/patches/rpi4-hevc/ffmpeg-001-pfcd_hevc_optimisations.patch
> kodi: update to 18.7-Leia

- packages/devel/bison/package.mk
This should hopefully fix our jenkins heisenbuilds
> bison: build non-parallel

- .github/ISSUE_TEMPLATE/bug-report.md
I have not really an idea how it interacts with the repo settings.
Only one way to find out :)
> github: add issue template

- packages/compress/p7zip/patches/p7zip-0500-gcc10-build-fix.patch
- packages/sysutils/squashfs-tools/patches/squashfs-tools-4.4-fno-common.patch
With new GCC 10 on host (Arch Linux), two packages fail to build. Fix them.
> GCC 10 build fixes

- packages/multimedia/ffmpeg/patches/rpi-hevc/ffmpeg-99.1003-pfcd_hevc_optimisations.patch
This fixes the kernel oops and kodi locking up issue reported here https://forum.libreelec.tv/thread/13245-kodi-18-0-update-for-slice/?postID=140610#post140610
Not runtime tested yet
> ffmpeg: update RPi HEVC patch to latest version

- packages/linux-firmware/intel-ucode/package.mk
- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- projects/Allwinner/linux/linux.aarch64.conf
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.7
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.8
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.9
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.10
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.11
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.6.13
> linux (Generic/Allwinner): update to linux-5.6.13

- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
- packages/addons/browser/chrome/source/bin/chrome-start
- packages/addons/browser/chrome/source/default.py
- packages/addons/browser/chrome/source/resources/language/English/strings.po
- packages/addons/browser/chrome/source/resources/settings.xml
- packages/addons/browser/chrome/source/settings-default.xml
not build/runtime tested yet !
> chrome: add missing lib to addon

- distributions/LibreELEC/version
- projects/Allwinner/devices/A20/options
- projects/Allwinner/devices/A64/options
- projects/Allwinner/devices/H3/options
- projects/Allwinner/devices/H5/options
- projects/Allwinner/devices/H6/options
- projects/Allwinner/options
- projects/Amlogic/options
- projects/NXP/options
- projects/Qualcomm/devices/Dragonboard/options
- projects/Rockchip/devices/RK3288/options
- projects/Rockchip/devices/RK3328/options
- projects/Rockchip/devices/RK3399/options
- projects/Rockchip/options
@chewitt @jernejsk @Kwiboo @lrusak 
pls have a look if that changes for the addons are okay for your platforms
> LE repo version bump

- packages/network/wireguard-linux-compat/package.mk
- packages/network/wireguard-tools/config/system.d/wireguard.service.sample
- packages/network/wireguard-tools/package.mk
> wireguard: bump packages and use wait-time-sync

- packages/lang/gcc/patches/gcc-999-fix-host-gcc-final-when-ccache-is-used.patch
https://github.com/buildroot/buildroot/commit/58ecbbc3ef18c43ae1c02a5c4bf30aa7ef2d8092
Thanks to @MilhouseVH for spotting the fix!
> gcc: fix host-gcc-final when ccache is used

- packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
rebuild of the addon is necessary due  https://github.com/LibreELEC/LibreELEC.tv/pull/4438
> inputstream.rtmp rebuild

- packages/addons/addon-depends/libmpdclient/package.mk
- packages/addons/addon-depends/mpd-mpc/package.mk
- packages/addons/service/mpd/changelog.txt
- packages/addons/service/mpd/package.mk
> mpd: update to 0.21.24

- packages/addons/addon-depends/network-tools-depends/ngrep/package.mk
- packages/addons/addon-depends/system-tools-depends/unrar/package.mk
this should fix random build issues seen on jenkins
> disable parallel build of ngrep and unrar

- packages/linux-firmware/kernel-firmware/package.mk
- packages/linux/package.mk
- packages/mediacenter/LibreELEC-settings/package.mk
- packages/mediacenter/kodi/config/advancedsettings.xml
- packages/mediacenter/kodi/scripts/kodi-remote
- packages/sysutils/wait-time-sync/system.d/wait-time-sync.service
Just some minor bits to offload from my Amlogic branch before I send the Amlogic 5.7 bump.
> Linux Kernel, Settings and some minor bits

- packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.octonet/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.matrix/package.mk
- packages/mediacenter/kodi/package.mk
> Kodi update to 2020-07-19

- packages/emulation/libretro-pcsx-rearmed/package.mk
- packages/emulation/libretro-pcsx-rearmed/patches/libretro-pcsx-rearmed-0001-aarch64-support.patch
> libretro-pcsx-rearmed: fix PCSX ReARMed build (LE 9.2)

- packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk
bump for https://github.com/LibreELEC/LibreELEC.tv/pull/4496
> game.libretro.pcsx-rearmed: rebuild

- distributions/LibreELEC/version
- packages/mediacenter/kodi/package.mk
- works at generic
- added repo bump to cleanup old addons
> Kodi update to latest

- packages/linux/package.mk
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.1
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.2
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.3
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.4
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.5
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.6
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.7
> linux: update to 5.8.7

- projects/Allwinner/devices/H6/patches/linux/19-Beelink-GS1.patch
This may fix the issue that some users are encountering.
Waiting for some feedback : https://forum.libreelec.tv/thread/22703-beelink-gs1-doesn-t-boot-nightly-builds/
@jernejsk for the build :)
> Allwinner: Add patch to fix eMMC on some Beelink GS1

- packages/graphics/libglvnd/package.mk
- packages/graphics/mesa/package.mk
> mesa: update to 20.2.0

- packages/sysutils/systemd/package.mk
- packages/sysutils/systemd/patches/systemd-0001-move-etc-systemd-system-to-storage-.config-system.d.patch
- packages/sysutils/systemd/system.d/hwdb.service
also cleaned up safe_remove warnings and our hwdb service.
> systemd: update to v246

- packages/debug/libva-utils/package.mk
- packages/lang/llvm/package.mk
- packages/multimedia/gmmlib/package.mk
- packages/multimedia/libva/package.mk
- packages/multimedia/libvdpau/package.mk
- packages/multimedia/media-driver/package.mk
- packages/x11/driver/xf86-video-intel/package.mk
> Graphics related package updates

- packages/emulation/libretro-atari800/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
> [le92] add game.libretro.atari800

- packages/sysutils/busybox/scripts/getedid
> [getedid] remove kernel check

- projects/Generic/patches/linux/linux-100-temporary_i915_haswell_black_screen_fix.patch
Haswell black screen patch, see description in patch.
> linux: Haswell black screen fix for Generic

- packages/compress/zstd/package.mk
- packages/databases/sqlite/package.mk
- packages/network/openssh/package.mk
- packages/print/freetype/package.mk
- packages/security/gnutls/package.mk
- packages/security/libgpg-error/package.mk
- packages/security/openssl/package.mk
- packages/sysutils/tz/package.mk
- packages/web/curl/package.mk
Various updates. Noticed some a/v sync issues w/ RPi3 but I'm assuming that's prime time network congestion as nothing here should impact playback.
> October package updates

- packages/linux-firmware/kernel-firmware/package.mk
> kernel-firmware: Update to 20200918

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
> [le92] kodi binary addons: update to latest Leia versions

- projects/Allwinner/devices/H6/patches/linux/07-opi3.patch
- projects/Allwinner/patches/linux/0109-drm-shme-helpers-Fix-dma_buf_mmap-forwarding-bug.patch
> Allwinner: H6: Fix OrangePi 3 ethernet

- packages/addons/addon-depends/system-tools-depends/strace/package.mk
- packages/addons/addon-depends/system-tools-depends/strace/patches/strace-0001-autoreconf.patch
- packages/addons/addon-depends/system-tools-depends/strace/patches/strace-0002-fix-autoconf-archive.patch
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
update to strace 5.9, fixes building
> system-tools buildfix

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to 7414645

- packages/devel/boost/package.mk
- packages/devel/cmake/package.mk
I used these to build add-ons without noticeable issues
> Update boost and cmake

- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
- updated squeezelite to latest, it builds
> update multimedia-tools fixes #4644

- projects/RPi/devices/RPi2/options
- projects/RPi/devices/RPi4/options
tested with pvr.hts and inputstream.adaptive / youtube on RPi2 and RPi4
> RPi2/4: switch to ARMv7/8 addons

- packages/debug/xorg-intel-gpu-tools/package.mk
- packages/x11/driver/xf86-video-intel/package.mk
Updated to head of intel xf86 and paired with intel gpu package.
Split out from #4667
> Intel graphics updates - xf86 and gpu tools

- packages/x11/xserver/xorg-server/package.mk
Split out from #4667 - package has been updated. Setting as draft as it is just new.
> xorg-server: update to 1.20.10

- packages/devel/glib/package.mk
> glib: update to 2.67.1

- packages/sysutils/dbus/package.mk
Updating to latest dbus. Have been testing this for the last 4 weeks along with dbussy code.
@thoradia - FYI
https://gitlab.freedesktop.org/dbus/dbus/blob/master/NEWS
> dbus: update to 1.13.18

- packages/compress/zstd/package.mk
- packages/sysutils/tz/package.mk
Couple of bugfix updates I didn't see in the other PRs.
> December package updates

- packages/textproc/tinyxml/package.mk
revert to downstream modified version
> tinyxml: revert url change

- packages/web/curl/package.mk
- packages/web/nghttp2/package.mk
Minor bumps to current for the 2 web packages:
- curl: updated to 7.74.0
- nghttp2: updated to 1.42.0
> web package updates

- packages/devel/boost/package.mk
- packages/devel/cmake/package.mk
- packages/devel/elfutils/package.mk
- packages/devel/elfutils/patches/elfutils-001-make-executables-optional.patch
boost: update to 1.75.0 - single bump
elfutils: update to 0.182 - minor (12 months) 
cmake: update to 3.19.2 - minor bump
> packages/devel - next batch of bumps

- packages/readme.md
> packages: update readme.md to current version of python

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to e755969

- packages/multimedia/dav1d/package.mk
Not a big update, but for anybody software decoding AV1 content any little bit can help :grinning:
> dav1d: updated to 0.8.1

- packages/sysutils/tz/package.mk
Update from 2020e to 2020f of TZ data.
> tz: update to 2020f

- packages/devel/readline/package.mk
26 fixes
11 new features
https://tiswww.cwru.edu/php/chet/readline/CHANGES
readline-8.0.tar.gz | 2019-01-07 09:13 | 2.8M
readline-8.1.tar.gz | 2020-12-06 15:45 | 2.9M
> readline: update to 8.1

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
Update to latest version from jc which includes a fix for green blocks with a specific HEVC file - that could help with other files, too.
> ffmpeg: update rpi patch

- packages/addons/addon-depends/librespot-depends/rust/package.mk
- packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk
rust: update to 1.49 from 1.45
- https://github.com/rust-lang/rust/blob/master/RELEASES.md
rustup.rs: update to 1.23.1 from 1.22.1
- https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md
> rust and rustup.rs: update packages

- packages/python/devel/setuptools/package.mk
Update from 51.0.0 to 51.1.1
minor bug fixes
https://github.com/pypa/setuptools/blob/main/CHANGES.rst
> setuptools: update to 51.1.1

- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
Bug fixes
https://github.com/tsl0922/ttyd/releases
> ttyd: update to 1.6.3

- packages/addons/service/proftpd/changelog.txt
- packages/addons/service/proftpd/package.mk
Minor update.
see release notes.
http://www.proftpd.org/
http://www.proftpd.org/docs/RELEASE_NOTES-1.3.7a
http://www.proftpd.org/docs/NEWS-1.3.7a
> proftpd: update to 1.3.7a

- packages/web/libmicrohttpd/package.mk
Update from 0.9.71 to 0.9.72
Changelog below
- https://github.com/Karlson2k/libmicrohttpd/blob/master/ChangeLog#L91
> libmicrohttpd: update to 0.9.72

- packages/devel/libftdi1/package.mk
Update from libftdi1 - 1.4 to 1.5
release notes: https://www.intra2net.com/en/developer/libftdi/index.php
> libftdi1: update to 1.5

- packages/sysutils/usbutils/package.mk
This fixes reconfiguration issue for targets other than Generic.
> usbutils: Fix reconfifuration

- packages/tools/crust/package.mk
- projects/Allwinner/patches/linux/0008-media-sunxi-cir-allow-timeout-to-be-set-at-runtime.patch
- projects/Allwinner/patches/linux/crust/0032-media-sunxi-cir-Skip-register-writes-during-remove.patch
- projects/Allwinner/patches/linux/crust/0033-media-sunxi-cir-Remove-unnecessary-spinlock.patch
- projects/Allwinner/patches/linux/crust/0034-media-sunxi-cir-Factor-out-hardware-initialization.patch
- projects/Allwinner/patches/linux/crust/0035-media-sunxi-cir-Implement-suspend-resume-shutdown-ca.patch
- scripts/uboot_helper
This PR allows Tanix TX6 box to suspend/resume and power up via IR remote that comes with it.
> Allwinner: Support Tanix TX6 suspend/resume

- packages/addons/addon-depends/system-tools-depends/depends/efivar/package.mk
- packages/addons/addon-depends/system-tools-depends/dstat/package.mk
- packages/addons/addon-depends/system-tools-depends/efibootmgr/package.mk
- packages/addons/addon-depends/system-tools-depends/hddtemp/package.mk
- packages/addons/addon-depends/system-tools-depends/hddtemp/patches/hddtemp-nvme.patch
- packages/addons/addon-depends/system-tools-depends/nmon/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- dstat: update to 2020-06-19
- efibootmgr: update version details
- efivar: update to 2020-10-16
- hddtemp: add patch to support nvme drives
- nmon: update to 16m
> system-tools: update to (119)

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/addons/tools/ffmpeg-tools/changelog.txt
- packages/addons/tools/ffmpeg-tools/package.mk
FFmpeg-tools: update addon to 113
- FFmpeg updated to 4.3.1
- Changelog: https://github.com/FFmpeg/FFmpeg/blob/release/4.3/Changelog
> ffmpeg-tools: update addon (113)

- packages/multimedia/libhdhomerun/package.mk
update 20200303 to 20201023
minor changes
changelog: https://github.com/Silicondust/libhdhomerun/commit/7c54382fb681d03888b469033e50bebaf4ce6bce
> libhdhomerun: update to release 20201023 (7c54382)

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
update 1.21.0 to 1.21.1
changelog: https://github.com/syncthing/syncthing/releases/tag/v1.12.1
> syncthing: update to 1.21.1

- packages/addons/addon-depends/tini/package.mk
update 0.18.0 to 0.19.0
changelog: https://github.com/krallin/tini/releases/tag/v0.19.0
> tini: update to 0.19.0

- packages/python/devel/setuptools/package.mk
update 51.1.1 to 51.1.2
changelog: https://github.com/pypa/setuptools/blob/main/CHANGES.rst
resolves: https://github.com/pypa/setuptools/issues/2505
> setuptools: update 51.1.2

- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
squeezelite: update to 2021-01-03 (1.9.8.1315)
> multimedia-tools: update addon to 114

- packages/addons/addon-depends/game-tools/linuxconsoletools/package.mk
- packages/addons/tools/game-tools/changelog.txt
- packages/addons/tools/game-tools/package.mk
- linuxconsoletools: update to 1.7.1
> game-tools: update addon to 103

- packages/addons/addon-depends/dvb-tools-depends/dvblast/package.mk
- packages/addons/addon-depends/dvb-tools-depends/mumudvb/package.mk
- packages/addons/tools/dvb-tools/changelog.txt
- packages/addons/tools/dvb-tools/package.mk
- mumudvb: update to 2021-01-06
- dvblast: update to 2021-01-07
> dvb-tools: update addon to 107

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
runtime tested on RPi4 and RPi3B+
> linux (RPi): update to 5.10.7

- packages/addons/addon-depends/libdvbcsa/package.mk
update aae3d0c (2017-02-07) to 2a1e61e (2018-01-29)
changelog: https://github.com/glenvt18/libdvbcsa/commits/master
update package.mk
> libdvbcsa: update to 2018-01-29

- packages/addons/addon-depends/jre-depends/apache-ant/package.mk
> apache-ant: bump package to 1.10.9

- packages/tools/installer/scripts/installer
- Suppress "Error: /dev/sda: unrecognised disk label" on empty disk
- Support BOOT_IMAGE and SYSTEM_IMAGE boot options
> installer: minor fixes

- packages/addons/addon-depends/network-tools-depends/iftop/package.mk
- packages/addons/addon-depends/network-tools-depends/iftop/patches/iftop-variable-to-be-local-due-to-pcap-1-10-0.patch
- packages/addons/tools/network-tools/changelog.txt
iftop: update to 2018-10-03
- update 1.0pre4 (2014-01-19) to 77901c8c (2018-10-03)
- changelog: https://code.blinkace.com/pdw/iftop/commits/master
- fix compile with libpcap-1.10.0
- updated PKG_URL and PKG_SITE
network-tools: fix iftop compile failure (108)
> iftop: update to 2018-10-03

- packages/graphics/glew/package.mk
update 2.1.0 to 2.2.0
changelog: as below and https://github.com/nigels-com/glew/blob/glew-2.2.0/doc/log.html
Bug fixes:
- GL_EXT_semaphore constants
- Some const pointer fixups in OpenGL API
- Correction for GLEW_VERSION_4_5
- Windows build updates and fixes
New extensions:
- GL_AMD_framebuffer_multisample_advanced
- GL_AMD_gpu_shader_half_float_fetch
- GL_AMD_shader_image_load_store_lod
- GL_ARM_texture_unnormalized_coordinates
- GL_DMP_program_binary
- GL_DMP_shader_binary
- GL_EXT_EGL_image_external_wrap_modes
- GL_EXT_EGL_image_storage
- GL_EXT_EGL_sync
- GL_EXT_clip_control
- GL_EXT_depth_clamp
- GL_EXT_disjoint_timer_query
- GL_EXT_draw_transform_feedback
- GL_EXT_multiview_tessellation_geometry_shader
- GL_EXT_multiview_texture_multisample
- GL_EXT_multiview_timer_query
- …
> glew: update to 2.2.0 (2020-03-15)

- packages/graphics/libdrm/package.mk
update 2.4.103 to 2.4.104
changelog: https://cgit.freedesktop.org/drm/libdrm/log/
> libdrm: update to 2.4.104

- packages/tools/nano/package.mk
update 5.4 to 5.5
news: https://www.nano-editor.org/news.php
> nano: update to 5.5

- packages/addons/addon-depends/system-tools-depends/htop/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
htop: update to 3.0.5 …
- update 3.0.4 to 3.0.5
- changelog: https://raw.githubusercontent.com/htop-dev/htop/master/ChangeLog
> system-tools: update to 120

- packages/network/connman/package.mk
See https://github.com/LibreELEC/LibreELEC.tv/pull/4906#issuecomment-762960385
> connman: fix typo

- packages/sysutils/tz/package.mk
Latest Timezone file: https://www.iana.org/time-zones
> tz: update to 2021a

- packages/databases/sqlite/package.mk
updtate 3.34.0 to 3.34.1
changelog: https://www.sqlite.org/releaselog/3_34_1.html
> sqlite: update to 3.34.1

- packages/network/iptables/package.mk
- packages/network/libnftnl/package.mk
libnftnl: update to 1.1.9
- update 1.1.8 to 1.1.9
- changelog: https://git.netfilter.org/libnftnl/log/
iptables: update to 1.8.7
- update 1.8.6 to 1.8.7
- changelog: https://git.netfilter.org/iptables/log/
> Update netfilter packages

- config/functions
- scripts/image
Remove some hard coded variables what are defined anyway
> config|scripts: keep source more generic

- scripts/genbuildplan.py
This converts `scripts/genbuildplan.py` to use f-strings. This is a small performance increase for slower machines due to the amount of strings it generates (pretty much every line of the `plan` and `plan.json`).
Backslashes are illegal syntax within f-strings, so work around it with chr(). chr(10) is UTF-8 character 10, aka Line feed, aka LF, aka "\n".
`plan`, `plan.json` and `tools/viewplan` have the same content before and after. I've used it for about a month.
> genbuildplan: convert to fstrings

- packages/wayland/wayland/package.mk
update 1.18.0 (2020-02-12) to 1.19.0 (2021-01-27)
changelog:
https://lists.freedesktop.org/archives/wayland-devel/2021-January/041692.html
https://lists.freedesktop.org/archives/wayland-devel/2021-January/041691.html
https://lists.freedesktop.org/archives/wayland-devel/2021-January/041683.html
https://lists.freedesktop.org/archives/wayland-devel/2020-December/041668.html
> wayland: update to 1.19.0

- tools/packages-checker
I was asked to PR the script that generated #4994. Here it is.
> tools/packages-checker: initial commit

- packages/audio/openal-soft/package.mk
update 1.21.0 (2020-11-04) to 1.21.1 (2021-02-05)
changelog: https://raw.githubusercontent.com/kcat/openal-soft/master/ChangeLog
> openal-soft: update to 1.21.1

- packages/addons/service/inadyn/changelog.txt
- packages/addons/service/inadyn/package.mk
update 2.7 (2020-03-22) to 2.8.1 (2021-01-31)
changelog: https://github.com/troglobit/inadyn/blob/master/ChangeLog.md
> inadyn: update to 2.8.1

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
update 1.12.1 (2020-12-06) to 1.13.1 (2021-01-12)
changelog: https://github.com/syncthing/syncthing/releases
> syncthing: update to 1.13.1

- packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
- packages/mediacenter/kodi/package.mk
- build and runtime tested at generic
> kodi: update to latest master 

- packages/mediacenter/kodi/package.mk
> kodi: update to 19.0

- packages/emulation/libretro-fbneo/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.fbneo/package.mk
add the https://github.com/libretro/FBNeo libretro core which supersedes fba: https://www.libretro.com/index.php/goodbye-fbalpha-welcome-fbneo/
> [emulation] add game.libretro.fbneo

- packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
- packages/emulation/libretro-vecx/package.mk
- packages/tools/dt-overlays/package.mk
results of `./tools/packages-checker`
> minor code cleanup

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to cdb0406

- packages/addons/addon-depends/snapcast-depends/aixlog/package.mk
- packages/addons/addon-depends/snapcast-depends/snapcast/package.mk
- packages/addons/service/snapclient/changelog.txt
- packages/addons/service/snapclient/package.mk
- packages/addons/service/snapserver/changelog.txt
- packages/addons/service/snapserver/package.mk
- aixlog: update to 1.5.0
- snapcast: update to 0.24.0
- snapclient: update to 0.24.0 addon (105)
- snapserver: update to 0.24.0 addon (105)
> snapcast: update to 0.24.0 and addons to (105)

- packages/addons/service/mpd/changelog.txt
- packages/addons/service/mpd/package.mk
- update 0.22.3 (2020-11-06) to 0.22.6 (2021-02-16)
- changelog: https://raw.githubusercontent.com/MusicPlayerDaemon/MPD/v0.22.6/NEWS
> mpd: update to 0.22.6 (addon 110)

- packages/graphics/mesa/package.mk
- packages/graphics/mesa/patches/mesa-999.01-lima-always-set-stride-in-texture-descriptor.patch
Release notes:
- https://docs.mesa3d.org/relnotes/21.0.0.html
- https://docs.mesa3d.org/relnotes/21.0.1.html
- https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0-Released
- https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0.1-Released
> mesa: updated to 21.0.1

- packages/addons/service/librespot/changelog.txt
- packages/addons/service/librespot/package.mk
- packages/addons/service/librespot/patches/vorbis-rs.patch
- packages/audio/libogg/package.mk
Update to try and resolve #5038 
- release: https://github.com/librespot-org/librespot/releases/tag/v0.1.5
- release: https://github.com/librespot-org/librespot/releases/tag/v0.1.6
- diff: https://github.com/librespot-org/librespot/compare/v0.1.3...v0.1.5
- diff: https://github.com/librespot-org/librespot/compare/v0.1.5...v0.1.6
> librespot: update to 0.1.6 and addon (127)

- packages/multimedia/media-driver/package.mk
- packages/multimedia/media-driver/patches/media-driver-999.01-PR1162-use-forward_references-as-the-reference-for-ADI.patch
> media-driver: enable VAAPI deinterlacers at X11

- CONTRIBUTING.md
Updated the link to interactive rebase in the CONTRIBUTING.md file.
> Documentation fixes

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to d86a317

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
- packages/mediacenter/kodi/patches/kodi-100.30-addons-refresh-etc-environment.patch
- packages/mediacenter/kodi/patches/kodi-995.20-gbm-default-to-original-crtc-mode.patch
- packages/mediacenter/kodi/patches/kodi-995.30-CDVDVideoCodecDRMPRIME-skip-frames-when-requested.patch
build + runtime tested at generic
> kodi: update to 4471acb

- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/package.mk
- kodi updated to latest in matrix branch
- - ffmpeg bump included
compiles and works for generic
> Kodi: update to latest Matrix

- projects/Allwinner/patches/linux/0061-arm64-dts-allwinner-Fix-SD-card-CD-GPIO-for-SOPine-s.patch
- projects/Allwinner/patches/linux/0062-arm64-dts-allwinner-Revert-SD-card-CD-GPIO-for-Pine64-LTS.patch
- projects/Allwinner/patches/linux/0063-media-v4l2-ctrls.c-fix-race-condition-in-hdl-request.patch
- projects/Allwinner/patches/linux/0064-media-v4l2-ctrls-fix-reference-to-freed-memory.patch
Several fixes from upstream - two patches are for Pine64 LTS board which fix SD card detection and another two fix race conditions in v4l2 request api.
> Allwinner: linux: Add upstream fixes

- packages/network/wireless-regdb/package.mk
update 2020.11.20 to 2021.04.21
announcement: http://lists.infradead.org/pipermail/wireless-regdb/2021-April/001242.html
regular update to databas
> wireless-regdb: update to 2021.04.21

- packages/x11/xserver/xorg-server/package.mk
https://lists.freedesktop.org/archives/xorg/2021-April/060678.html
Clean build & run tested on Generic SKL/APL
> xorg-server: update to 1.20.11

- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
- pvr.iptvsimple
- pvr.mediaportal.tvserver
- pvr.waipu
>  kodi-binary-addons: update to latest versions

- packages/addons/addon-depends/system-tools-depends/bottom/package.mk
- packages/addons/addon-depends/system-tools-depends/depends/oniguruma/package.mk
- packages/addons/addon-depends/system-tools-depends/file/package.mk
- packages/addons/addon-depends/system-tools-depends/mc/package.mk
- packages/addons/addon-depends/system-tools-depends/mc/patches/mc-revert-wchar.patch
- packages/addons/addon-depends/system-tools-depends/mtpfs/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/patches/fix-parallel-build.patch
- packages/addons/addon-depends/system-tools-depends/unrar/package.mk
- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- Added bottom (btm) (successor to ytop) - all arch except Generic
- Update file to 5.40
- Update mc to 4.8.26
- Update mtpfs to 2021-05-14
- Update oniguruma to 6.9.7.1
- Update stress-ng to 0.12.09
- Update unrar to 6.0.6
- Update vim to 8.2.2879
> system-tools: update addon to 122

- packages/addons/service/net-snmp/changelog.txt
- packages/addons/service/net-snmp/package.mk
- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
- packages/addons/service/syncthing/package.mk
Update addons 
- net-snmp: update to 5.9.1 and addon (109)
- rsyslog: update to 8.2104.0 and addon to (108)  
- syncthing: update to 1.16.1 and addon (116)
> update addons - net-snmp, rsyslog, syncthing

- packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
**pvr.waipu:**
- 2.9.2-Matrix:
- Improve internal login handling
- 2.9.1-Matrix
- Fix internal Device ID generation
- Fix Android build
> bump binary addons

- packages/mediacenter/kodi/package.mk
> kodi: update to 6402a50

- packages/mediacenter/LibreELEC-settings/package.mk
> LibreELEC-settings: update to 6172183

- distributions/LibreELEC/version
> distro: bump ADDON_VERSION to 10.0.0

- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/chrome-depends/pango/package.mk
- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
- chrome: update to 92.0.4515.107
- at-spi2-core: update to 2.40.3
- gdk-pixbuf: update to 2.42.6
- gtk3: update to 3.24.30
- pango: update to 1.48.7
> chrome: update to 92.0.4515.107

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
- update minisatip 1.1.24 to 1.1.34
- compare: https://github.com/catalinii/minisatip/compare/v1.1.24...v1.1.34
- releases: https://github.com/catalinii/minisatip/releases
> minisatip: update to 1.1.34 (106)

- distributions/LibreELEC/version
not sure if we want to merge it now ?
> distro: bump ADDON_VERSION to 10.80.0, OS Version 11.0

- packages/multimedia/dav1d/package.mk
https://code.videolan.org/videolan/dav1d/-/releases/0.9.0
> dav1d: update to 0.9.1

- packages/x11/driver/xf86-input-libinput/package.mk
- https://lists.x.org/archives/xorg-announce/2021-April/003079.html
- https://www.phoronix.com/scan.php?page=news_item&px=xf86-input-libinput-1.0
> xf86-input-libinput: update to 1.0.1

- packages/audio/libsndfile/package.mk
- updated copyright notes
- updated license to SPDX short identifier
- switched to github repo
- enabled pic
- use CMake build
- updated build opts
> libsndfile: update to 1.0.31

- packages/graphics/mesa/package.mk
Update from 21.2.0 to 21.2.1
Ann: https://lists.freedesktop.org/archives/mesa-dev/2021-August/225464.html
> mesa: update to 21.2.1

- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- pvr.nextpvr: update 8.2.6-Matrix to 8.2.7-Matrix
> kodi-binary-addons: update to latest versions  (LE11)

- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- pvr.nextpvr: update 8.2.6-Matrix to 8.2.7-Matrix
refer #5564
> kodi-binary-addons: update to latest versions (LE10)

- packages/mediacenter/kodi-binary-addons/audiodecoder.organya/package.mk
- packages/mediacenter/kodi-binary-addons/imagedecoder.heif/package.mk
- packages/mediacenter/kodi-binary-addons/imagedecoder.mpo/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
- audiodecoder.organya: update 3.0.0-Matrix to 19.0.0-Matrix
- imagedecoder.heif: update 1.4.0-Matrix to 19.0.0-Matrix
- imagedecoder.mpo: update 2.0.1-Matrix to 19.0.0-Matrix
- pvr.filmon: update 6.1.2-Matrix to 6.1.3-Matrix
- pvr.iptvsimple: update 7.6.9-Matrix to 7.6.10-Matrix
- pvr.vuplus: update 7.4.9-Matrix to 7.4.11-Matrix
> [le10] kodi-binary-addons: update to latest versions

- packages/addons/service/jellyfin/package.mk
> jellyfin: update License and Description

- packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk
- packages/mediacenter/kodi-binary-addons/visualization.waveform/package.mk
- peripheral.joystick: update 1.7.2-Matrix to 19.0.0-Matrix
- visualization.shadertoy: update 19.0.0-Matrix to 19.0.1-Matrix
- visualization.waveform: update 19.0.0-Matrix to 19.0.1-Matrix
> [le11] kodi-binary-addons: update to latest versions

- projects/Generic/options
disable dvb addons till we are heading some release
> Generic: disable dvb add-ons

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Changes:-
https://github.com/catalinii/minisatip/compare/v1.1.34...v1.1.44
> minisatip: update to 1.1.44 (107)

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Changes:-
https://github.com/catalinii/minisatip/compare/v1.1.34...v1.1.44
:master patch: #5619
> [le10] minisatip: update to 1.1.44 (107)

- projects/Allwinner/devices/H3/patches/linux/0001-HACK-SW-CEC-implementation-for-H3.patch
- projects/Allwinner/patches/linux/0056-drm-sun4i-dw-hdmi-Fix-HDMI-PHY-clock-setup.patch
> [LE10] Allwinner: linux: Fix HDMI driver

- packages/mediacenter/LibreELEC-settings/package.mk
Weblate update + backup crash fix
> LibreELEC-settings: update to 8b1efa30

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
> [le10] linux (RPi): update to 5.10.63-a5d2df0

- projects/Allwinner/devices/H6/patches/linux/0013-WIP-OPi3-DT-fixes.patch
> [backport] Allwinner: linux: Fix OrangePi 3 DT

- packages/addons/addon-depends/snapcast-depends/shairport-sync/package.mk
- packages/addons/addon-depends/snapcast-depends/shairport-sync/patches/fix-libsnfile-dependencies.patch
- packages/audio/libsndfile/patches/libsndfile-add-required-static-libaries-to-pkg-config.patch
- shairport-sync: update to using pkg-config
- libsndfile: reorder static libraries
Issue due to static libraries not being included 
Master PR is #5694
> [le10] shairport-sync: update the build to use pkg-config

- packages/mediacenter/kodi/patches/kodi-100.32.add-le-repository-to-officials.patch
fixup for https://github.com/LibreELEC/LibreELEC.tv/pull/5696
> fixup! add "repository.libreelec.tv" to official repos

- packages/graphics/mesa/package.mk
Minor updates
release notes: https://docs.mesa3d.org/relnotes/21.2.3.html
> mesa: update to 21.2.3

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.13.12.html
> [le11] samba: update to 4.13.12

- packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2021-September/000066.html
- http://mm.icann.org/pipermail/tz-announce/2021-October/000067.html
> [le11] tz: update to 2021c

- packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2021-September/000066.html
- http://mm.icann.org/pipermail/tz-announce/2021-October/000067.html
:master is #5708
> [le10] tz: update to 2021c

- packages/linux-firmware/iwlwifi-firmware/package.mk
> iwlwifi-firmware: update to be9ab34

- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/cups/package.mk
- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
> [le10] chrome: update to 95.0.4638.54 and addon (109)

- packages/tools/crust/package.mk
This introduces wake up/power on via HDMI-CEC feature, requested by some.
> crust: Update package to 2e5f355790b5f9cd941f939280adda6b4b6581c0

- packages/linux-firmware/kernel-firmware/package.mk
> kernel-firmware: update to 20211027

- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- packages/network/sshpass/package.mk
> sshpass: add initial package and include with network-tools bundle

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
this adds a couple of bugfixes and initial version of deinterlace filter
runtime tested on RPi4
> [le11] ffmpeg: update rpi patch

- packages/network/sshpass/package.mk
> sshpass: fix build on x86_64

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Release notes: https://github.com/catalinii/minisatip/releases
- update 1.1.44 to 1.1.51
- diff: https://github.com/catalinii/minisatip/compare/v1.1.44...v1.1.51
> [le11] minisatip: update to 1.1.51 and addon (108)

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Release notes: https://github.com/catalinii/minisatip/releases
- update 1.1.44 to 1.1.51
- diff: https://github.com/catalinii/minisatip/compare/v1.1.44...v1.1.51
Upstream is #5941
> [le10] minisatip: update to 1.1.51 and addon (108)

- packages/mediacenter/LibreELEC-settings/package.mk
Include connman autoconnect fix and language updates.
> LibreELEC-settings: update to 0a634ef

- packages/addons/addon-depends/chrome-depends/pango/package.mk
- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
- pango: update to 1.49.3
- chrome: update to 96.0.4664.45 and addon (111)
backport of #5877
> [le10] chrome: update to 96.0.4664.45 and addon (111)

- packages/debug/strace/package.mk
Release notes:
- https://github.com/strace/strace/releases/tag/v5.15
Announcement:
- https://lists.strace.io/pipermail/strace-devel/2021-December/010783.html
> strace: update to 5.15

- config/graphic
- config/show_config
- distributions/LibreELEC/options
- distributions/LibreELEC/show_config
- projects/Generic/devices/Generic/options
- projects/Generic/devices/wayland/options
- projects/Generic/devices/x11/options
- clean up
- tweaks for show_config
- default to `OPENGL/OPENGLES=no` if not set
- sort `GRAPHIC_DRIVERS` & list them for all projects not just x11
- moved video acceleration out of graphic config
- moved `WINDOWMANAGER` var out of distributions to Generic projetcs
```
=================================================================================
Configuration for LibreELEC (community)
=================================================================================
Buildsystem configuration:
======================================================
- CPU:					 x86-64
- Kernel Architecture:			 x86
- Userland Architecture:		 x86_64
- CPU features:			 64bit mmx sse sse2
- LTO (Link Time Optimization) support: yes
- GOLD (Google Linker) Support:	 yes
- LLVM support:			 yes
- DEBUG:				 no
- …
```
> [le11] config/graphics & show_config: clean up & tweaks

- projects/Allwinner/patches/linux/0053-wip-fix-H6-4k-60.patch
> [LE10] Allwinner: linux: fix 4k60 mode on H6 with some HW

- packages/sysutils/e2fsprogs/package.mk
- packages/sysutils/open-vm-tools/package.mk
- packages/web/libmicrohttpd/package.mk
- e2fsprogs: update to 1.46.4 
- libmicrohttpd: update to 0.9.73
- https://lists.gnu.org/archive/html/info-gnu/2021-04/msg00007.html
- open-vm-tools: update to 11.3.5
- https://github.com/vmware/open-vm-tools/releases
> package updates: operating system

- packages/databases/sqlite/package.mk
sqlite 3.36 changelog: https://www.sqlite.org/releaselog/3_36_0.html
sqlite 3.37 changelog: https://www.sqlite.org/releaselog/3_37_0.html
> sqlite: update to 3.37.0

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/cec-framework/kodi-100.17-tinker-s-cec-disable-polling.patch
- packages/mediacenter/kodi/patches/kodi-100.15-rename-default-pulse-device.patch
- projects/Allwinner/patches/kodi/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- projects/Allwinner/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
- projects/RPi/patches/kodi/kodi-001-deinterlace.patch
- projects/Rockchip/patches/kodi/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- projects/Rockchip/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
> kodi: update to 2022-12-23

- packages/security/nss/package.mk
- packages/tools/nano/package.mk
- packages/web/libmicrohttpd/package.mk
Minor package updates
libmicrohttpd: update to 0.9.74
nano: update to 6.0
nss: update to 3.73.1
> [le11] Minor package updates

- packages/addons/addon-depends/system-tools-depends/bottom/package.mk
- packages/addons/addon-depends/system-tools-depends/depends/efivar/package.mk
- packages/addons/addon-depends/system-tools-depends/depends/efivar/patches/efivar-01-static_lib.patch
- packages/addons/addon-depends/system-tools-depends/efibootmgr/package.mk
- packages/addons/addon-depends/system-tools-depends/file/package.mk
- packages/addons/addon-depends/system-tools-depends/htop/package.mk
- packages/addons/addon-depends/system-tools-depends/nmon/package.mk
- packages/addons/addon-depends/system-tools-depends/unrar/package.mk
- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- Update bottom to 0.6.6
- Update efibootmgr to githash 2021-11-05
- Update efivar to githash 2021-12-10
- Update file to 5.41
- Update htop to 3.1.2
- Add libgpiod (1.6.3)
- Update nmon to 16n
- Update unrar to 6.1.3
- Update vim to 8.2.3878
> [le11] system-tools: update to (127)

- packages/python/devel/Mako/package.mk
- packages/python/devel/meson/package.mk
- packages/python/devel/waf/package.mk
Minor devtool updates
waf: update to 2.0.23
Mako: update to 1.1.6
meson: update to 0.60.3
> [le11] Devtools updates 

- packages/addons/addon-depends/ffmpegx-depends/libvpx/package.mk
- packages/addons/tools/ffmpeg-tools/changelog.txt
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/multimedia/aom/package.mk
Backport of #6036 
- aom: update to 3.2.0
- libvpx: update to 1.11.0
> [le10] ffmpeg-tools: update to 117

- packages/addons/addon-depends/ffmpegx-depends/libvpx/package.mk
- packages/addons/tools/ffmpeg-tools/changelog.txt
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/multimedia/aom/package.mk
- aom: update to 3.2.0
- libvpx: update to 1.11.0
> [le11] ffmpeg-tools: update to 117

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.13.15.html
> [le11] samba: update to 4.13.15

- packages/addons/service/inadyn/changelog.txt
- packages/addons/service/inadyn/package.mk
- packages/addons/service/prometheus-node-exporter/changelog.txt
- packages/addons/service/prometheus-node-exporter/package.mk
- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
btrfs-progs: update to 5.15.1
inadyn: update to 2.9.1 and addon (108)
prometheus-node-exporter: update to 1.3.1 and addon (101)
rsyslog: update to 8.2112.0 and addon to (109) and update PKG_URL to
> [le11] update addons

- packages/graphics/mesa/package.mk
- packages/multimedia/gmmlib/package.mk
- gmmlib: update to 22.0.1
- minor update
- https://github.com/intel/gmmlib/compare/intel-gmmlib-21.3.4...intel-gmmlib-22.0.1
- mesa: update to 21.3.3
- minor update
- https://docs.mesa3d.org/relnotes/21.3.3.html
- https://lists.freedesktop.org/archives/mesa-dev/2021-December/225612.html
> Mesa and Gmmlib updates

- tools/docker/README.md
>  tools/docker: update readme

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
update 1.17.0 (2021-06-02) to 1.18.5 (2021-11-22)
Release notes: https://github.com/syncthing/syncthing/releases
> syncthing: update to 1.18.5 (118)

- packages/databases/mariadb-connector-c/package.mk
- packages/databases/sqlite/package.mk
- mariadb-connector-c: update to 3.2.5
- sqlite: update to 3.37.1
> Databases package updates

- packages/python/security/pycryptodome/package.mk
- packages/python/system/simplejson/package.mk
- pycryptodome: update to 3.12.0
- https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst
- simplejson: update to 3.17.6
- https://github.com/simplejson/simplejson/releases/tag/v3.17.6
> Python package updates

- packages/sysutils/e2fsprogs/package.mk
- packages/sysutils/libevdev/package.mk
- packages/sysutils/usbutils/package.mk
- packages/sysutils/util-linux/package.mk
- util-linux: update to 2.37.2  
- libevdev: update to 1.12.0  
- e2fsprogs: update to 1.46.5  
- usbutils: update to 014
> Sysutils package updates

- packages/addons/addon-depends/chrome-depends/cups/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/chrome-depends/pango/package.mk
- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
- packages/graphics/harfbuzz/package.mk
- packages/textproc/icu/package.mk
- chrome: update to 97.0.4692.71
- cups: update to 2.4.0
- gtk3: update to 3.24.31
- harfbuzz: update to 3.2.0
- icu: update to 70.1 and PKG_SITE 
- pango: update to 1.50.3
https://chromestatus.com/features/schedule
> [le11] chrome: update to 97.0.4692.71 and addon (112)

- packages/addons/addon-depends/ttyd-depends/libuv/package.mk
- packages/addons/addon-depends/ttyd-depends/libwebsockets/package.mk
- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
> [le10] Update ttyd addon (104)

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
This adds support for deinterlacing, depends on #6090
> [le10] ffmpeg: update rpi patch

- packages/linux/udev.d/40-modeswitch.rules
> linux: add udev rule to switch mode on Realtek RTL8821CU devices

- packages/mediacenter/kodi-theme-Estuary/package.mk
> kodi-theme-Estuary: add unpack dependency on kodi

- packages/addons/addon-depends/vdr/package.mk
- packages/addons/service/vdr-addon/changelog.txt
- packages/addons/service/vdr-addon/package.mk
Tested for a few hours, seem to be working ok.
> vdr-addon: update VDR to 2.6.1

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Release notes:
- https://github.com/catalinii/minisatip/releases
> minisatip: update to 1.1.66 and addon (109)

- tools/mkpkg/update_binary-addons
- tools/mkpkg/update_common_functions
- tools/mkpkg/update_retroplayer-addons
backport of #5673, #5732 and #5755
> [le10] backport addon update scripts updates

- packages/addons/addon-depends/libzip/package.mk
- packages/addons/addon-depends/libzip/patches/libzip-001-fix-typo-which-prevents-expansion-of-libdir-in-pkgconfig.patch
- packages/addons/addon-depends/vdr/package.mk
- packages/addons/service/vdr-addon/changelog.txt
- packages/addons/service/vdr-addon/package.mk
> [le10] vdr-addon: update to 2.4.8 and addon (117)

- packages/mediacenter/kodi/system.d/kodi-autostart.service
Backport of PR #6142, if you want it for LE10.
> [le10] kodi: add shutdown hook to autostart

- packages/tools/dtc/package.mk
> [LE10] dtc: copy libfdt symlink and library

- packages/security/gnutls/package.mk
- packages/security/nettle/package.mk
- packages/security/nss/package.mk
- gnutls: update to 3.7.3
- nettle: update to 3.7.3
- nss: update to 3.75
> package updates: security libraries

- projects/Allwinner/patches/linux/0028-media-cedrus-hevc-Improve-buffer-management.patch
- projects/Allwinner/patches/linux/0054-media-cedrus-Fix-H265-aux-buffer-size.patch
- projects/Allwinner/patches/linux/0055-media-cedrus-Add-watchdog-for-job-completion.patch
> [LE10] Allwinner: linux: Update cedrus patches

- packages/graphics/glu/package.mk
- packages/textproc/libxml2/package.mk
- libxml2: tidy up package.mk and simplify with no overrides
- glu: change to meson
> Minor package updates and tidy ups

- projects/Allwinner/patches/linux/0056-media-cedrus-h264-Fix-neighbour-info-buffer-size.patch
> [LE10] Allwinner: linux: fix H264 buffer size

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.06-dont-set-_NET_WM_STATE_FULLSCREEN.patch
- packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch
- packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
- packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
- packages/mediacenter/kodi/patches/kodi-999.16-PR20632-base-m_bFullScreenRoot-setting-on-res-infos-bFullScreen.patch
- packages/multimedia/libdvdnav/package.mk
- packages/multimedia/libdvdread/package.mk
> kodi: update to lastest master version

- packages/mediacenter/kodi/patches/kodi-999.02-backport-pr19601-gbm-add-display-clock.patch
Backport of https://github.com/xbmc/xbmc/pull/19601
> kodi: add gbm "sync playback to display" backport patch

- packages/graphics/nvidia/package.mk
- packages/multimedia/nvidia-vaapi-driver/package.mk
Build & run tested on a GTX 1060
- https://github.com/elFarto/nvidia-vaapi-driver/releases/tag/v0.0.5
- https://www.nvidia.com/download/driverResults.aspx/187030/
> [le11] update NVIDIA packages for Wayland

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
- media-driver: update to 22.2.2
- gmmlib: update to 22.0.3
> Intel graphics updates

- packages/addons/addon-depends/system-tools-depends/mmc-utils/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
> [LE10] system-tools: include mmc-utils

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-999.02-backport-pr19601-gbm-add-display-clock.patch
> kodi: update to 19.4

- packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2022-March/000070.html
> [le11] tz: update to 2022a

- packages/sysutils/tz/package.mk
Backport of 
- #6305 
ann:
- http://mm.icann.org/pipermail/tz-announce/2022-March/000070.html
> [le10] tz: update to 2022a

- packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
See: https://github.com/flubshi/pvr.waipu/releases/tag/19.2.0-Matrix
New Features:
* Implement OAuth device login
* Translations updates from Weblate
> LE10: pvr.waipu: 19.2.0-Matrix

- packages/network/iwd/package.mk
- packages/network/openvpn/package.mk
- iwd: update to 1.26
- openvpn: update to 2.5.6
> [le11] network packages updates

- packages/addons/service/snapclient/changelog.txt
- packages/addons/service/snapclient/package.mk
- packages/addons/service/snapclient/source/system.d/service.snapclient.service
> snapclient: Set ALSA_PLUGIN_DIR (109)

- packages/sysutils/open-vm-tools/package.mk
Release notes:
- https://github.com/vmware/open-vm-tools/releases/tag/stable-12.0.0
> open-vm-tools: update to 12.0.0

- packages/lang/Python3/patches/Python3-0401-fix-bpo-46070-2.patch
See https://bugs.python.org/issue46070
Signed-off-by: Alban Browaeys <alban.browaeys@gmail.com>
> Python3: Add patch to fix crash in sqlite3 import

- packages/compress/p7zip/patches/p7zip-0501-change-numMethods-from-bool-to-unsigned.patch
Fix required due to #6253 update
> p7zip: patch to support C++17 compiler

- packages/web/curl/package.mk
- packages/web/curl/patches/curl-0001-pr-8664.patch
update 7.80.0 (2021-11-10) to 7.82.0 (2022-03-05)
changelog:
- https://curl.se/changes.html#7_82_0
- https://curl.se/changes.html#7_81_0
> curl: update to 7.82.0

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/index.html
- vulkan-loader: update to 1.3.212
- vulkan-headers: update to 1.3.212
- vulkan-tools: update to 1.3.212
> [le11] Vulkan updates

- packages/tools/qemu/package.mk
release notes:
- https://www.qemu.org/2022/04/19/qemu-7-0-0/
> qemu: update to 7.0.0

- packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220419
> intel-ucode: update to 20220419

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.31.le-addons-no-startupenable.patch
> kodi: update to 6f05bd9

- packages/sysutils/lirc/patches/0006-lirc-gpio-ir-0.10.patch
- packages/sysutils/lirc/patches/lirc-0101-kernel-5.18-fix.patch
> lirc: fix build with kernel 5.18, add another Debian patch

- packages/network/iwd/package.mk
changelog:
- Fix issue with hidden networks on connection error.
- Fix issue with directed roams if already trying to roam.
- Fix issue with checking for connected in FT frame event.
log:
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/
> iwd: update to 1.27

- packages/addons/addon-depends/librespot-depends/rust/package.mk
- packages/python/devel/Jinja2/package.mk
- [Jinja2: update to 3.1.2](https://github.com/LibreELEC/LibreELEC.tv/commit/c1d6dc89ef2e8a4af9cd45988143a9f96ade34dd)
- [rust: update to 1.60.0](https://github.com/LibreELEC/LibreELEC.tv/commit/734b9cb1f9e8c5199d981ce439a182ea95a56cc4)
> Update devtool packages

- packages/graphics/harfbuzz/package.mk
- packages/multimedia/libass/package.mk
- packages/print/freetype/package.mk
- packages/x11/other/fontconfig/package.mk
- libass: update to 0.15.2
- harfbuzz: update to 4.2.1
- fontconfig: update to 2.14.0
- freetype: update to 2.12.0
> Font package updates

- packages/databases/sqlite/package.mk
- packages/security/nss/package.mk
- packages/tools/nano/package.mk
- [nss: update to 3.78](https://github.com/LibreELEC/LibreELEC.tv/commit/bfccf0214001e097f81802c583fca5f034c6fe66)
- https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_77.html#mozilla-projects-nss-nss-3-77-release-notes
- https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_78.html#mozilla-projects-nss-nss-3-78-release-notes
- [sqlite: update to 3.38.3](https://github.com/LibreELEC/LibreELEC.tv/commit/b303642709c3b59c96ebbe3e2d6276c71aa0b680)
- https://www.sqlite.org/releaselog/3_38_3.html
- [nano: update to 6.3](https://github.com/LibreELEC/LibreELEC.tv/commit/8d3d41c1e5d48544f2c27770387e612a228ffde4)
- https://www.nano-editor.org/news.php
> [le11] package updates

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
> [le10] btrfs-progs: update to 5.17

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
> [le10] minisatip: update to 1.1.92 and addon (110)

- packages/debug/gdb/package.mk
ann:
- https://lists.gnu.org/archive/html/info-gnu/2022-05/msg00000.html
> gdb: update to 12.1

- packages/web/curl/package.mk
release notes:
- https://curl.se/changes.html#7_83_1
> curl: update to 7.83.1

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
Only build-tested for RPi4 yet
> kodi: update to 20.0a1-Nexus

- tools/docker/bionic/Dockerfile
- tools/docker/buster/Dockerfile
- tools/docker/focal/Dockerfile
- tools/docker/groovy/Dockerfile
- tools/docker/hirsute/Dockerfile
- tools/docker/sid/Dockerfile
- tools/docker/stretch/Dockerfile
Backport of:
- cf53953275c0cd41741caf28754ce142180ddd4c 
- 47d64e0ab01f5b9f75d2e6112a12828f10bc60d0
> [le10] backport of tools/docker/focal Dockerfile

- packages/addons/addon-depends/system-tools-depends/bottom/package.mk
Required update to package.mk due to #6502
> bottom: adjust to new rust build

- packages/addons/addon-depends/go/package.mk
- packages/python/devel/ninja/package.mk
- packages/python/graphics/Pillow/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rust: 1.61.0
- go: 1.18.2
- Pillow: 9.1.1
- ninja: 1.11.0
> [le11] Development language updates

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Changelog:
- https://github.com/KhronosGroup/Vulkan-Docs/commit/9b5562187a8ad72c171410b036ceedbc450153ba
> Vulkan updates: 1.3.215

- packages/sysutils/systemd/package.mk
- packages/sysutils/systemd/patches/systemd-0200-persist-persistent-timer-stamps.patch
ann:
- https://lists.freedesktop.org/archives/systemd-devel/2022-May/047976.html
log:
- https://github.com/systemd/systemd-stable/compare/v251...v251.1
> systemd: update to 251.1

- config/functions
Back port of 
- #6478 
note: code is the same; but the style matches the libreelec-10.0 branch
> [le10] config/functions: improve error message when there in not a device directory

- packages/devel/cmake/package.mk
- packages/devel/fakeroot/package.mk
- cmake: update to 3.23.2
- fakeroot: update to 1.29
> [le11] devel updates 

- packages/databases/sqlite/package.mk
release log:
- https://www.sqlite.org/releaselog/3_38_5.html
- https://www.sqlite.org/news.html#2022-05-06
> [le11] sqlite: update to 3.38.5

- packages/sysutils/open-vm-tools/package.mk
release notes:
- https://github.com/vmware/open-vm-tools/releases/tag/stable-12.0.5
- https://github.com/vmware/open-vm-tools/blob/stable-12.0.5/ReleaseNotes.md
- https://github.com/vmware/open-vm-tools/blob/stable-12.0.5/open-vm-tools/ChangeLog
> [le11] open-vm-tools: update to 12.0.5

- packages/graphics/libdrm/package.mk
ann:
- https://www.spinics.net/lists/dri-devel/msg349550.html
log:
- https://cgit.freedesktop.org/mesa/drm/log/
> libdrm: update to 2.4.111

- packages/graphics/glu/package.mk
- packages/multimedia/SDL2/package.mk
non impacting package updates:
- glu: add libglvnd as dependency
- SDL2: update to 2.0.22
> Minor package updates

- packages/addons/addon-depends/go/package.mk
- packages/python/devel/meson/package.mk
- packages/python/devel/waf/package.mk
- go: update to 1.18.3
- meson: update to 0.62.2
- waf: update to 2.0.24
> [le11] Development Tool package updates

- packages/addons/addon-depends/network-tools-depends/iperf/package.mk
- packages/addons/addon-depends/network-tools-depends/nmap/package.mk
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- iperf: update to 3.11
- nmap: update to 7.92 and HSTS
> [le11] network-tools: update addon to (114)

- packages/addons/tools/system-tools/package.mk
- projects/Generic/filesystem/usr/share/bootloader/canupdate.sh
- fix system-tools build due to updated minor version of the libonig.
- Update canupdate to allow change between Generic and Generic-legacy
> [le11] Minor fixes

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.217
- vulkan-loader: update to 1.3.217
- vulkan-tools: update to 1.3.217
Change log: https://github.com/KhronosGroup/Vulkan-Docs/commit/307906bddb5fab543dcf6d7fff737abeb15f8b10
> Vulkan updates to 1.3.217

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/service/jellyfin/changelog.txt
- packages/addons/service/jellyfin/package.mk
- packages/addons/service/jellyfin/source/bin/jellyfin-downloader
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
Update to the Jellyfin 10.8.0 and ASP.Net 6.0.6
> Jellyfin release 10.8.0

- packages/lang/llvm/package.mk
- https://discourse.llvm.org/t/llvm-14-0-5-release/63118
> llvm: update to 14.0.5

- packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/docs/relnotes/22.1.2.rst
> mesa: update to 22.1.2

- packages/linux-drivers/RTL8192DU/package.mk
- packages/network/ethtool/package.mk
- packages/network/libnftnl/package.mk
- ethtool: update to 5.18
- libnftnl: update to 1.2.2 and HTTPS
- RTL8192DU: update to 2022-06-18
> Network package updates

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.20.3
- gst-plugins-base: update to 1.20.3
- gstreamer: update to 1.20.3
> gstreamer update to 1.20.3

- packages/debug/strace/package.mk
Release notes
- https://github.com/strace/strace/releases/tag/v5.18
> strace: update to 5.18

- packages/multimedia/aom/package.mk
- packages/multimedia/libaacs/package.mk
- packages/multimedia/libass/package.mk
- aom: update to 3.4.0
- https://aomedia.googlesource.com/aom/+/refs/tags/v3.3.0
- https://aomedia.googlesource.com/aom/+/fc430c57c7b0307b4c5ffb686cd90b3c010d08d2/CHANGELOG
- libaacs: update to 0.11.1
- libass: update to 0.16.0
> Multimedia package updates

- packages/addons/service/tinc/changelog.txt
- packages/addons/service/tinc/package.mk
- https://www.tinc-vpn.org/news/release-1.1pre18/
> [le11] tinc: update to 1.1pre18

- packages/addons/service/tinc/changelog.txt
- packages/addons/service/tinc/package.mk
> [le10] tinc: update to 1.1pre18

- projects/Allwinner/linux/linux.arm.conf
> [LE10] Allwinner: linux: arm: Enable spidev

- packages/lang/llvm/package.mk
ann:
- https://discourse.llvm.org/t/llvm-14-0-6-release/63431
> llvm: update to 14.0.6

- packages/multimedia/aom/package.mk
> aom: update pkg_url 

- packages/graphics/libdrm/package.mk
ann:
- https://lists.freedesktop.org/archives/dri-devel/2022-July/362994.html
> libdrm: update to 2.4.112 and https

- packages/audio/alsa-lib/package.mk
- packages/audio/alsa-ucm-conf/package.mk
Change log:
- https://www.alsa-project.org/wiki/Changes_v1.2.7.1_v1.2.7.2
packages:
- alsa-ucm-conf: update to 1.2.7.2
- alsa-lib: update to 1.2.7.2
> alsa updates

- packages/addons/addon-depends/cxxtools/patches/cxxtools-3.0-gcc12-time.patch
- packages/addons/addon-depends/cxxtools/patches/cxxtools-3.0-lld-linking-openssl.patch
2 patches that were missed when I raised PR #6685
> cxxtools: patch to compile with openssl

- packages/python/devel/meson/package.mk
Release notes:
- https://mesonbuild.com/Release-notes-for-0-63-0.html
> meson: update to 0.63.0

- packages/databases/sqlite/package.mk
Release log:
- https://www.sqlite.org/releaselog/3_39_1.html
> sqlite: update to 3.39.1

- packages/sysutils/systemd/package.mk
Log:
- https://github.com/systemd/systemd-stable/compare/v251.2...v251.3
> systemd: update to 251.3

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.220
- vulkan-loader: update to 1.3.220
- vulkan-tools: update to 1.3.220
- 1.3.218 - https://github.com/KhronosGroup/Vulkan-Docs/commit/067a92d083e6a7ec97ef3bcc34e5b75fa71eec79
- 1.3.219 - https://github.com/KhronosGroup/Vulkan-Docs/commit/080f66a96b61419b8663872d6cab6ce68a3123e8
- 1.3.220 - https://github.com/KhronosGroup/Vulkan-Docs/commit/29f44f378cdeb1b96b47ce00fb32f49954f2d29d
> Vulkan update to 1.3.220

- packages/network/iwd/package.mk
- packages/network/libnl/package.mk
- [libnl: update to 3.7.0](https://github.com/LibreELEC/LibreELEC.tv/commit/9a3c42c427f108be8b34b19ea3a51a103d879f9c)
- log
- https://github.com/thom311/libnl/compare/libnl3_6_0...libnl3_7_0
- [iwd: update to 1.29](https://github.com/LibreELEC/LibreELEC.tv/commit/afc191d908f3d469cdaa172adde1c516d37c8b4f)
- log
> packages/network: updates

- packages/graphics/harfbuzz/package.mk
update 4.3.0 to 4.4.1
release notes:
- https://github.com/harfbuzz/harfbuzz/releases
- https://github.com/harfbuzz/harfbuzz/releases/tag/4.4.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/4.4.1
> harfbuzz: update to 4.4.1

- packages/addons/addon-depends/network-tools-depends/irssi/package.mk
- packages/addons/addon-depends/network-tools-depends/ngrep/package.mk
- packages/addons/addon-depends/network-tools-depends/ngrep/patches/port-to-pcre2-api-and-enable-jit-compilation.patch
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- network-tools: update addon to (115)
- irssi: update to 1.4.2 and meson build
- ngrep: update to using pcre2
> [le11] network tools update to 115

- packages/network/samba/package.mk
- https://www.samba.org/samba/history/samba-4.16.3.html
> samba: update to 4.16.3

- scripts/image
> [le10] scripts/image: cleanup ORIGIN_URL

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
release notes:
- https://blog.rust-lang.org/2022/07/19/Rust-1.62.1.html
> rust: update to 1.62.1

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://github.com/KhronosGroup/Vulkan-Docs/commit/8dcc7469b01529600b712596a5a48ec8c710e228
- vulkan-headers: update to 1.3.222
- vulkan-loader: update to 1.3.222
- vulkan-tools: update to 1.3.222
> Vulkan updates

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
Needs testing.
release notes:
https://github.com/catalinii/minisatip/releases
> [le11] minisatip: update to 1.2.7 and addon (111)

- packages/addons/addon-depends/libvncserver/package.mk
> libvncserver: remove PKG_MAINTAINER

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://github.com/KhronosGroup/Vulkan-Docs/commit/5ca346bf39db36ff06e24686f0a815754c5f7c16
- vulkan-headers: update to 1.3.224
- vulkan-loader: update to 1.3.224
- vulkan-tools: update to 1.3.224
> Vulkan update to 1.3.224

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
> [le10] minisatip: update to 1.2.7 and addon (111)

- projects/Allwinner/patches/u-boot/0003-sunxi-mmc-increase-stabilization-delay-from-1ms-to-20ms.patch
> [LE10] Allwinner: u-boot: Fix SD boot on some boards

- packages/sysutils/tz/package.mk
Announcement:
https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html
> [le11] tz: update to 2022b

- packages/debug/strace/package.mk
release notes:
- https://github.com/strace/strace/releases/tag/v5.19
> strace: update to 5.19

- packages/python/devel/meson/package.mk
log:
- https://github.com/mesonbuild/meson/compare/0.63.0...0.63.1
milestone:
- https://github.com/mesonbuild/meson/milestone/84?closed=1
> meson: update to 0.63.1

- packages/compress/lz4/package.mk
Release notes:
- https://github.com/lz4/lz4/releases/tag/v1.9.4
> lz4: update to 1.9.4

- packages/sysutils/tz/package.mk
> [le10] tz: update to 2022c

- packages/graphics/mesa/package.mk
Ann:
https://lists.freedesktop.org/archives/mesa-announce/2022-August/000685.html
> mesa: update to 22.1.7

- packages/security/nss/package.mk
release notes:
https://hg.mozilla.org/projects/nss/raw-file/d5af335e161d7db7f7b74d8091c9903bf9b74ba7/doc/rst/releases/nss_3_82.rst
> nss: update to 3.82

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Notes:
- https://github.com/KhronosGroup/Vulkan-Docs/commit/1f6a09901674b320bff7cf36c364a461cf1069a6
- vulkan-headers: update to 1.3.225
- vulkan-loader: update to 1.3.225
- vulkan-tools: update to 1.3.225
> Vulkan: update to 1.3.225

- packages/tools/qemu/package.mk
changelog:
- https://wiki.qemu.org/ChangeLog/7.1
ann:
- https://lore.kernel.org/all/166190001339.271991.6991052484622099743@amd.com/
(have been testing with 7.1.0-rc4)
> qemu: update to 7.1.0

- packages/compress/zip/package.mk
from:
- https://patchwork.ozlabs.org/project/buildroot/patch/1422113025-24848-4-git-send-email-romain.naour@openwide.fr/
- confirmed as tested and closing #6858
> zip: fix LARGE_FILE_SUPPORT check

- packages/mediacenter/LibreELEC-settings/package.mk
Changes since d6c41d4:
* Update translations from Weblate
* Rework manual update for new infrastructure
> LibreELEC-settings: update to d6c41d4

- packages/network/iwd/package.mk
changelog:
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=881807d14b7ee2a71f53c872303f6c05c4ee487a
log:
> iwd: update to 1.30

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
> [le10] btrfs-progs: update to 5.19 and addon to (109)

- packages/audio/pipewire/package.mk
Log
- https://github.com/PipeWire/pipewire/compare/0.3.55...0.3.56
- https://github.com/PipeWire/pipewire/compare/0.3.56...0.3.57
- https://github.com/PipeWire/pipewire/compare/0.3.57...0.3.58
changelog:
> pipewire: update to 0.3.58

- packages/lang/gcc/package.mk
- packages/mediacenter/kodi/package.mk
> [le10] fix ccache handling of kodi and gcc:bootstrap

- packages/security/nspr/package.mk
- packages/security/nss/package.mk
- [nspr: update to 4.34.1](https://github.com/LibreELEC/LibreELEC.tv/commit/2d6e183a468992557fe11447b824e4bffdb74b84)
- [nss: update to 3.83](https://github.com/LibreELEC/LibreELEC.tv/commit/8e2f54c329106a63a1b19dbf3b85ad7645ea4916)
> nss and nspr update

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/devel/libfmt/package.mk
- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/package.mk
- packages/network/samba/package.mk
- packages/sysutils/busybox/package.mk
- packages/sysutils/fuse/package.mk
basically somes fixes & improvements recycled from https://github.com/LibreELEC/LibreELEC.tv/pull/6875
- build libfmt shared
- fix Kodi gold linker
- build/link various packages with gold
> [le11] linker fix-ups for Kodi and various other packages

- packages/security/gnutls/package.mk
https://www.gnutls.org/manual/gnutls.html
> gnutls: update to 3.7.8

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Minor bump to include some new firmwares and symlinks
> brcmfmac_sdio: bump to include latest firmwares

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
- projects/RPi/patches/kodi/0001-CDVDVideoCodecDRMPRIME-Also-support-YUV420-buffers.patch
- projects/RPi/patches/kodi/0002-gbm-Set-max-bpc-for-high-bit-depth-videos.patch
- projects/RPi/patches/kodi/0003-CVideoLayerBridgeDRMPRIME-add-colourspace-connector-.patch
- projects/RPi/patches/kodi/0004-DVDVideoCodecDRMPRIME-use-AV_PIX_FMT_DRM_PRIME-for-f.patch
This fixes the "resume not working" issue #6864 
Also refreshed and renamed RPi kodi patches and added a patch to fix deinterlace of software decoded videos with latest ffmpeg patches
Runtime tested on RPi3B+ and RPi4
Fixes: #6864
> ffmpeg: update kodi patch

- packages/addons/addon-depends/ttyd-depends/libuv/package.mk
- packages/addons/addon-depends/ttyd-depends/libwebsockets/package.mk
- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
- ttyd: update to 1.7.1 and addon (106)
- libuv: update to 1.44.2
- libwebsockets: update to 4.3.2
> [le11] ttyd: update to 1.7.1 and addon (106)

- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
Changelog:
- https://github.com/rsyslog/rsyslog/blob/master/ChangeLog
> [le11] rsyslog: update to 8.2208.0

- packages/addons/addon-depends/network-tools-depends/iperf/package.mk
- packages/addons/addon-depends/network-tools-depends/nmap/package.mk
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- network-tools: update to addon (117)
- nmap: update to 7.93
- iperf: update to 3.12
> [le11] network-tools: update to addon (117).

- packages/audio/pipewire/package.mk
Log:
- https://github.com/PipeWire/pipewire/compare/0.3.58...0.3.59
> pipewire: update to 0.3.59

- packages/addons/service/prometheus-node-exporter/changelog.txt
- packages/addons/service/prometheus-node-exporter/package.mk
release notes:
- https://github.com/prometheus/node_exporter/releases/tag/v1.4.0
> [le11] prometheus-node-exporter: update to 1.4.0 and addon (102)

- packages/sysutils/systemd/package.mk
Regular update to system-stable
log:
- https://github.com/systemd/systemd-stable/compare/v251.4...v251.5
> systemd: update to 251.5

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.21.1
- gst-plugins-base: update to 1.21.1
- gstreamer: update to 1.21.1
> gstreamer: update to 1.21.1

- packages/network/openssh/package.mk
release notes:
- https://www.openssh.com/releasenotes.html#9.1p1
> openssh: update to 9.1p1

- packages/addons/addon-depends/go/package.mk
- packages/python/devel/meson/package.mk
- meson: update to 0.63.3
- go: update to 1.19.2
> Build tool updates

- packages/graphics/bcm2835-driver/package.mk
- packages/tools/bcm2835-bootloader/package.mk
This fixes no LAN on Pi400
see https://github.com/raspberrypi/firmware/issues/1754
> RPi: update to firmware 53f4941

- packages/mediacenter/LibreELEC-settings/package.mk
> [le10] LibreELEC-settings: update to f369cd1

- packages/graphics/nvidia/package.mk
> nvidia: update to 515.76

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
> btrfs-progs: update to 6.0 and addon to (110)

- packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2022-October/000074.html
> [le11] tz: update to 2022e

- packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2022-October/000074.html
backport:
- #6995
> [le10] tz: update to 2022e

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
> [le10] dotnet-runtime: Update ASP.NET 6.x to 6.0.10 and addon (123)

- packages/addons/service/minisatip/changelog.txt
- packages/addons/service/minisatip/package.mk
> [le10] minisatip: update to 1.2.36

- packages/addons/addon-depends/icu/package.mk
- packages/graphics/harfbuzz/package.mk
- harfbuzz: update to 5.3.1
- icu: update to 72.1
> [le11] harfbuzz and icu updates

- packages/network/netbase/package.mk
changelog:
- https://salsa.debian.org/md/netbase/-/commit/a0c50d66656551d076c545cd42a83c2e4140ea0e
> netbase: update to 6.4

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/drmprime-filter/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0002-WIP-DRMPRIME-deinterlace-filter.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0003-DVDVideoCodecDRMPRIME-Avoid-exception-with-AV_PIX_FM.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0004-DVDVideoCodecDRMPRIME-Leave-deinterlace-filter-activ.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0005-SetVideoInterlaced-Set-and-unset-deinterlace-method-.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0006-DVDVideoCodecDRMPRIME-Close-deinterlace-filter-on-er.patch
- packages/mediacenter/kodi/patches/kodi-100.05-make-binary-addons-executable.patch
- packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
- packages/mediacenter/kodi/patches/kodi-100.30-addons-refresh-etc-environment.patch
Trying to keep up with current kodi refactorings.
LE and drmprime-filter (deinterlace) patches are updated, runtime test on RPi4 was fine
> kodi: update to latest master

- packages/databases/sqlite/package.mk
release notes:
- https://www.sqlite.org/releaselog/3_39_4.html
> sqlite: update to 3.39.4

- packages/lang/llvm/package.mk
ann:
- https://discourse.llvm.org/t/llvm-15-0-3-released/66036
> llvm: update to 15.0.3

- packages/devel/mold/patches/mold-999.01-fix-strip-on-armv7.patch
- fixes https://github.com/rui314/mold/issues/801 otherwhise strip fails
> mold: fix strip on ARMv7 with binutils

- packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v251.6...v251.7
> systemd: update to 251.7

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Docs: https://github.com/KhronosGroup/Vulkan-Docs/commit/7dcf16f3b4a1118ff92207316b68145446f08bb3
- vulkan-headers: update to 1.3.232
- vulkan-loader: update to 1.3.232
- vulkan-tools: update to 1.3.232
> Vulkan update to 1.3.232

- packages/sysutils/exfatprogs/package.mk
- packages/tools/mtools/package.mk
- exfatprogs: update to 1.2.0
- mtools: update to 4.0.42
> Filesystem tool package updates

- packages/sysutils/tz/package.mk
ann:
- https://mm.icann.org/pipermail/tz-announce/2022-October/000075.html
> [le11] tz: update to 2022f

- packages/sysutils/tz/package.mk
ann:
- https://mm.icann.org/pipermail/tz-announce/2022-October/000075.html
> [le10] tz: update to 2022f

- packages/debug/strace/package.mk
- packages/debug/valgrind/package.mk
- packages/debug/valgrind/patches/valgrind-0001-enable-armv8.patch
- [strace: update to 6.0](https://github.com/LibreELEC/LibreELEC.tv/commit/16cac16c2821ae98bc37a484adbd0df6b4650bea)
- [valgrind: update to 3.20.0](https://github.com/LibreELEC/LibreELEC.tv/commit/44c9bcbae33ca30e0dfbd024eb3109160e5c5712)
> Update debug packages

- packages/addons/addon-depends/faad2/package.mk
- packages/addons/addon-depends/game-tools/linuxconsoletools/package.mk
- packages/addons/addon-depends/game-tools/linuxconsoletools/patches/linuxconsoletools-0001-disable-building-ffmvforce.patch
- packages/addons/service/mpd/changelog.txt
- packages/addons/service/mpd/package.mk
- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
- packages/addons/tools/game-tools/changelog.txt
- packages/addons/tools/game-tools/package.mk
- rsyslog: update to 8.2210.0 and addon (113)
- game-tools: update addons tools (104)
- linuxconsoletools: update to 1.8.1
- mpd: update to 0.23.10 and addon (115)
- faad2: update to 2.10.1
backport of
- #7059
> [le10] Addons updates

- packages/sysutils/systemd/package.mk
release notes:
- https://github.com/systemd/systemd/releases/tag/v252
Tested v252-rc[1-3] last few weeks
> systemd: update to 252

- packages/addons/addon-depends/jre-depends/jre-libXinerama/package.mk
- packages/multimedia/nv-codec-headers/package.mk
- packages/x11/lib/libXext/package.mk
- packages/x11/lib/libXinerama/package.mk
- packages/x11/lib/pixman/package.mk
- nv-codec-headers: update to 11.1.5.2
- jre-libXinerama: update unpack file
- libXinerama: update to 1.1.5 and https
- libXext: update to 1.3.5 and https
- pixman: update to 0.42.2
> X package updates

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.21.2
- gst-plugins-base: update to 1.21.2
- gstreamer: update to 1.21.2
> gstreamer: update to 1.21.2

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Changelog: https://github.com/KhronosGroup/Vulkan-Docs/commit/42d3f5a641810c52bbe53c0f049be1130af07f2f
- vulkan-headers: update to 1.3.233
- vulkan-loader: update to 1.3.233
- vulkan-tools: update to 1.3.233
> Vulkan update to 1.3.233

- packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v252...v252.1
> systemd: update to 252.1

- packages/addons/service/mariadb/changelog.txt
- packages/addons/service/mariadb/package.mk
- packages/addons/service/mariadb/source/bin/mariadb.start
- packages/addons/service/mariadb/source/bin/mariadb.stop
- packages/addons/service/mariadb/source/config/my.cnf
- packages/addons/service/mariadb/source/system.d/service.mariadb.service
MariaDB 10.9.4
- Release Notes: https://mariadb.com/kb/en/mdb-1094-rn/
- Changelog:     https://mariadb.com/kb/en/mdb-1094-cl/
> [le11] mariadb: update to 10.9.4 and addon (108)

- packages/network/openvpn/package.mk
Change log:
- https://github.com/OpenVPN/openvpn/blob/v2.5.8/ChangeLog
- https://github.com/OpenVPN/openvpn/blob/v2.5.8/Changes.rst
> openvpn: update to 2.5.8

- packages/compress/xz/package.mk
news:
- https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;h=c244b42a6771a6e8af206318dfc500d78929fd6f;hb=5476089d9c42b9b04e92b80e1800b384a98265cb
> xz: update to 5.2.8

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.7
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.8
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.9
6.0.7 - 240 patches
6.0.8 - 197 patches
6.0.9 - 190 patches
-
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.0.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.0.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.0
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build …
```
> linux: update to 6.0.y

- packages/databases/sqlite/package.mk
Release notes:
- https://sqlite.org/releaselog/3_40_0.html
> sqlite: update to 3.40.0

- packages/lang/llvm/package.mk
Announcement:
- https://discourse.llvm.org/t/llvm-15-0-5-release/66616
> llvm: update to 15.0.5

- packages/audio/pipewire/package.mk
> pipewire: update to 0.3.60

- packages/devel/mold/package.mk
release notes:
- https://github.com/rui314/mold/releases/tag/v1.7.1
> mold: update to 1.7.1

- packages/addons/addon-depends/network-tools-depends/irssi/package.mk
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- [irssi: update to 1.4.3](https://github.com/LibreELEC/LibreELEC.tv/commit/ebf501d497da6712d906d978c75cbe6256a88488)
> [le11] network-tools: update addon (119)

- packages/textproc/expat/package.mk
- packages/textproc/libidn2/package.mk
- packages/textproc/pugixml/package.mk
- expat: update to 2.5.0
- libidn2: update to 2.3.4
- pugixml: update to 1.13
> Textproc package updates

- packages/tools/nano/package.mk
News:
- https://www.nano-editor.org/news.php
> nano: update to 7.0

- packages/multimedia/libbluray/package.mk
Thanks @vpeter4 for the reminder that we forgot to bump it
> libbluray: update to 1.3.3

- packages/multimedia/libbdplus/package.mk
Just noticed there's another bluray package we didn't bump. Build tested for RPi4
> libbdplus: update to 0.2.0

- packages/sysutils/systemd/package.mk
Log:
- https://github.com/systemd/systemd-stable/compare/v252.1...v252.2
> systemd: update to 252.2

- packages/python/devel/meson/package.mk
log:
- https://github.com/mesonbuild/meson/compare/0.64.0...0.64.1
> meson: update to 0.64.1

- packages/addons/addon-depends/ccid/package.mk
- packages/addons/addon-depends/pcsc-lite/package.mk
- packages/addons/service/oscam/changelog.txt
- packages/addons/service/oscam/package.mk
- packages/addons/service/pcscd/changelog.txt
- packages/addons/service/pcscd/package.mk
- ccid: update to 1.5.1
- oscam: update to 11715 and addon (112)
- pcscd: update to addon (102)
- pcsc-lite: update to 1.9.9
> [le11] Addon updates - oscam and pcscd

- packages/tools/atf/package.mk
release notes:
- https://trustedfirmware-a.readthedocs.io/en/latest/change-log.html#id1
> atf: update to 2.8

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
Logs:
- https://github.com/kdave/btrfs-progs/compare/v6.0...v6.0.2
changes:
- https://github.com/kdave/btrfs-progs/blob/master/CHANGES
> [le11] btrfs-progs: update to 6.0.2 and addon (111)

- packages/sysutils/tz/package.mk
Release notes:
- https://mm.icann.org/pipermail/tz-announce/2022-November/000076.html
> [le11] tz: update to 2022g

- packages/wayland/wayland-protocols/package.mk
Package updates:
- wayland-protocols: update to 1.31
> Wayland package updates

- packages/graphics/libglvnd/package.mk
- packages/multimedia/libvdpau/package.mk
- packages/x11/lib/libXrandr/package.mk
- libglvnd: update to 1.6.0
- libvdpau: update to 1.5
- libXrandr: update to 1.5.3 and https
> X11 package updates

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
> [le10] btrfs-progs: update to 6.0.2 and addon (111)

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.21.3
- gst-plugins-base: update to 1.21.3
- gstreamer: update to 1.21.3
> Gstreamer update to 1.21.3

- packages/lang/Python3/patches/0001-Make-the-build-of-pyc-files-conditional.patch
- packages/lang/Python3/patches/0002-Disable-buggy_getaddrinfo-configure-test-when-cross-.patch
- packages/lang/Python3/patches/0003-Add-infrastructure-to-disable-the-build-of-certain-e.patch
- packages/lang/Python3/patches/0004-Adjust-library-header-paths-for-cross-compilation.patch
- packages/lang/Python3/patches/0005-Don-t-look-in-usr-lib-termcap-for-libraries.patch
- packages/lang/Python3/patches/0006-Don-t-add-multiarch-paths.patch
- packages/lang/Python3/patches/0007-Abort-on-failed-module-build.patch
- packages/lang/Python3/patches/0008-Serial-ioctl-workaround.patch
- packages/lang/Python3/patches/0009-Do-not-adjust-the-shebang-of-Python-scripts-for-cros.patch
- packages/lang/Python3/patches/0010-Misc-python-config.sh.in-ensure-sed-invocations-only.patch
- packages/lang/Python3/patches/0011-Add-an-option-to-disable-pydoc.patch
- packages/lang/Python3/patches/0012-Add-an-option-to-disable-lib2to3.patch
- packages/lang/Python3/patches/0013-Add-option-to-disable-the-sqlite3-module.patch
- packages/lang/Python3/patches/0014-Add-an-option-to-disable-the-tk-module.patch
- packages/lang/Python3/patches/0015-Add-an-option-to-disable-the-curses-module.patch
- packages/lang/Python3/patches/0016-Add-an-option-to-disable-expat.patch
- packages/lang/Python3/patches/0017-Add-an-option-to-disable-CJK-codecs.patch
- packages/lang/Python3/patches/0018-Add-an-option-to-disable-NIS.patch
- packages/lang/Python3/patches/0019-Add-an-option-to-disable-unicodedata.patch
- packages/lang/Python3/patches/0020-Add-an-option-to-disable-IDLE.patch
- packages/lang/Python3/patches/0021-Add-an-option-to-disable-decimal.patch
- packages/lang/Python3/patches/0022-Add-an-option-to-disable-the-ossaudiodev-module.patch
- packages/lang/Python3/patches/0023-Add-an-option-to-disable-openssl-support.patch
- packages/lang/Python3/patches/0024-Add-an-option-to-disable-the-readline-module.patch
- packages/lang/Python3/patches/0025-Add-options-to-disable-zlib-bzip2-and-xz-modules.patch
- packages/lang/Python3/patches/0026-python-config.sh-don-t-reassign-prefix.patch
- packages/lang/Python3/patches/0027-Add-an-option-to-disable-uuid-module.patch
- packages/lang/Python3/patches/0029-configure.ac-fixup-CC-print-multiarch-output-for-mus.patch
- packages/lang/Python3/patches/0030-Add-an-option-to-disable-the-berkeleydb-module.patch
- packages/lang/Python3/patches/0031-lib-crypt-uClibc-ng-doesn-t-set-errno-when-encryptio.patch
reference commit:
- https://git.busybox.net/buildroot/commit/package/python3?id=738500c296c8b1206f20e94ca3e7c5932a6a0486
> Python3: update to buildroot 3.11.0 patches

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- glslang: update to 11.13.0
- spirv-headers: update to githash 1d31a10
- spirv-tools: update to githash 40f5bf5
> glslang: update to 11.13.0

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
> [le10] syncthing: update to 1.22.2 and addon (123)

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.26-disable-internal-texturepacker.patch
We're not quite there yet but we'll need to update our texturepacker disable patch so I thought it'd be good to share current WIP early
> kodi: update to Nexus 20.0 RC 1

- packages/audio/pipewire/package.mk
release notes:
- https://gitlab.freedesktop.org/pipewire/pipewire/-/releases
> pipewire: update to 0.3.62

- packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v252.2...v252.3
> systemd: update to 252.3

- packages/security/nss/package.mk
release notes:
- https://hg.mozilla.org/projects/nss/file/50c4bb30904af6c87394ee77ee4192c2796d3003/doc/rst/releases/nss_3_86.rst
> nss: update to 3.86

- packages/addons/service/mariadb/package.mk
- packages/devel/pcre2/patches/libpcre2-pcre2posix-header.patch
pcre2 patch is needed to build mariadb: https://github.com/PCRE2Project/pcre2/issues/173
> mariadb: update to 10.10.2 and addon (1)
