LibreELEC/LibreELEC.tv

packages/security/libgpg-error/package.mk
=> libgpg-error: update to libgpg-error-1.37 [LibreELEC-9.2]

scripts/mkimage
tty parameter was removed with #3863 
Backport of  #4297
=> mkimage: replace deprecated "tty" with "systemd.debug_shell" for Generic

packages/sysutils/v4l-utils/package.mk
Changelog is really boring/minimal, just a build fix for gcc 10
```
v4l-utils-1.18.1
----------------
David Seifert (1):
Fix GCC 10 / -fno-common
```
=> v4l-utils: update to 1.18.1

packages/network/wireless-regdb/package.mk
```
wireless-regdb: update regulatory database based on preceding changes
wireless-regdb: update rules for US on 2.4/5G
GB: Extend to cover DMG channels 5 & 6
wireless-regdb: Update regulatory rules for Singapore (SG)
wireless-regdb: Update regulatory rules for Indonesia (ID)
regdb: fix compatibility with python2
wireless-regdb: Update regulatory rules for Russia (RU)
wireless-regdb: Harmonize ranges of CEPT countries (stand of July 2019)
wireless-regdb: Fix ranges of EU countries as they are harmonized since 2014
wireless-regdb: Extend 5470-5725 MHz range to 5730 MHz for Taiwan (TW)
wireless-regdb: Fix overlapping ranges for Switzerland and Liechtenstein
```
=> wireless-regdb: update to wireless-regdb-2020.04.29

packages/network/samba/package.mk
Security release.
*  CVE-2020-10700:
A client combining the 'ASQ' and 'Paged Results' LDAP controls can cause a
use-after-free in Samba's AD DC LDAP server.
*  CVE-2020-10704:
A deeply nested filter in an un-authenticated LDAP search can exhaust the
LDAP server's stack memory causing a SIGSEGV.
=> samba: update to samba-4.12.2

config/functions, packages/addons/addon-depends/containerd/package.mk, packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/libnetwork/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/package.mk, packages/addons/service/syncthing/changelog.txt, packages/addons/service/syncthing/package.mk
A couple of issues are now plaguing Jenkins:
1. `syncthing` is running `go generate -v` with a default `GOPATH` that results in `go` modules being installed into `$HOME/go`. Obviously this is messy and wrong, and there is no guarantee this is "thread safe" should multiple `go`-based packages concurrently install modules at the same time into the same `$HOME/go` directory.
2. `syncthing` installs `go` modules with bonkers [read-only file permissions](https://github.com/golang/go/issues/27455) that can't subsequently be deleted when cleaning the package or when deleting the entire build directory - this is breaking Jenkins. When cleaning packages we need to ensure we have read/write access prior to removal. The actual error is:
```
rm: cannot remove …
```
=> buildsystem: fix go-based packages

scripts/uboot_helper
The dtb for the Pine H64 Model B is created during the build, but the target image isn't created for DEVICE=H6 and can't be selected with UBOOT_SYSTEM=
The ethernet configuration in the image created for the original Pine H64 board doesn't work on the model B board.
=> uboot_helper: added support for Pine H64 Model B

packages/sysutils/dbus/tmpfiles.d/z_02_dbus.conf, packages/sysutils/systemd/package.mk
We have these issues:
```
Mar 06 12:38:53 LibreELEC systemd-tmpfiles[239]: [/usr/lib/tmpfiles.d/static-nodes-permissions.conf:17] Unknown group 'kvm'.
Mar 06 12:38:53 LibreELEC systemd-tmpfiles[254]: [/usr/lib/tmpfiles.d/z_02_dbus.conf:4] Duplicate line for path "/var/lib/dbus", ignoring.
Apr 21 17:00:21 rpi22 systemd-tmpfiles[723]: [/usr/lib/tmpfiles.d/static-nodes-permissions.conf:17] Unknown group 'kvm'.
Apr 21 17:00:21 rpi22 systemd-tmpfiles[723]: [/usr/lib/tmpfiles.d/z_02_dbus.conf:4] Duplicate line for path "/var/lib/dbus", ignoring.
```
* Adding the `kvm` and `render` groups fixes 50% of the problem.
* The `dbus` package installs the following:
```
rpi22:~ # cat /usr/lib/tmpfiles.d/dbus.conf
d /var/lib/dbus 0755 - - -
L /var/lib/dbus/machine-id - - - - /etc/machine-id
d …
```
=> dbus, systemd: fix duplicate tmpfiles and missing groups

packages/addons/addon-depends/libzip/package.mk, packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
Sync with kodi https://github.com/xbmc/xbmc/pull/17706 - we haven't updated `libzip` in a long while.
Only consumer appears to be `vdr-plugin-xmltv2vdr`, which I have build tested on `x86_64` but not able to run-time test.
=> libzip: update to libzip-1.6.1

projects/Allwinner/kodi/appliance.xml
This PR disables two things:
limited range selection - this is automatically handled by HDMI driver
audio passthrough - driver and alsa lib are not fixed yet to support it
=> Allwinner: Disable non-working Kodi settings

packages/security/gnutls/package.mk
Security fix: https://lists.gnupg.org/pipermail/gnutls-help/2020-March/004642.html
=> gnutls: update to 3.6.13

packages/linux/patches/default/linux.999.03-arm-vdso-add-vdso_clock_gettime64-phys-timer-syscall.patch
`glibc-2.31` and kernel 5.6.y+ (and possibly 5.5.y, but not 5.4.y) has erratic date/time due to (most likely) broken or incomplete 32-bit/64-bit y2038 time conversions when using `__vdso_clock_gettime64`.
Disable `__vdso_clock_gettime64` until a fix is available.
=>  linux: arm: vdso: add vdso_clock_gettime64 syscall for non virtual timers

packages/graphics/bcm2835-driver/system.d/unbind-console.service, packages/linux-firmware/brcmfmac_sdio-firmware/system.d/brcmfmac-firmware.service, packages/network/samba/system.d/samba-config.service, packages/security/openssl/system.d/openssl-config.service, packages/sysutils/systemd/system.d/hwdb.service, packages/sysutils/systemd/system.d/kernel-overlays.service
This is required since systemd 245, without it oneshot services
may get started more than once.
=> add RemainAfterExit=yes to our oneshot systemd services

tools/docker/README.md, tools/docker/bionic/Dockerfile, tools/docker/buster/Dockerfile, tools/docker/eoan/Dockerfile, tools/docker/focal/Dockerfile, tools/docker/stretch/Dockerfile, tools/docker/xenial/Dockerfile
This PR adds `libparse-yapp-perl` to the `Dockerfile`'s in `tools/docker` that was added to `scripts/checkdeps` in #4240, also adds a `buster` and `focal` container and changes to recommend `focal` in readme.
=> tools/docker: add libparse-yapp-perl and more

packages/python/devel/MarkupSafe/package.mk
This fix the following warning 
```
<<< MarkupSafe:host seq 55 <<<
BUILD      MarkupSafe (host)
TOOLCHAIN      manual
File "setup.py", line 6, in <module>
from setuptools import setup, Extension, Feature
ImportError: cannot import name 'Feature' from 'setuptools' (/home/clement/.local/lib/python3.7/site-packages/setuptools/__init__.py)
FAILURE: scripts/build MarkupSafe:host during makeinstall_host (package.mk)
$@
FAILURE: scripts/build MarkupSafe:host has failed!
The following log for this failure is available:
/home/clement/LibreELEC.tv/build.LibreELEC-H6.arm-9.80-devel/.threads/logs/55.log
>>> MarkupSafe:host seq 55 >>>
```
=> MarkupSafe: bump to 1.1.1

config/path, packages/lang/gcc-arm-aarch64-none-elf/package.mk, packages/security/openssl/package.mk, scripts/checkdeps
This commit enables building openssl on another systems instead of x86_64 (eg. arm)
=> Support cross-compile on aarch64 platform

packages/audio/alsa-lib/modprobe.d/intel-audio.conf
Users who want to use the Intel SST drivers included in LibreELEC
can override that via an (empty)
/storage/.config/modprobe.d/intel-audio.conf file
=> alsa-lib: use hda_intel driver on Intel boards with a DSP

packages/tools/rpi-eeprom/package.mk
While `critical/pieeprom-2019-09-10.bin` remains the default, this update adds `stable/pieeprom-2020-01-17.bin` firmware as an option which brings:
```
* Add a stable firmware directory based on the latest beta release.
Stable should be interpreted as feature-freeze releases. In this
case the core network boot is stable enough for most scenarios
and this de-risks adding new more experimental features in the
beta folder.
```
This could be backported to `libreelec-9.2` and included with any future Kodi 18.7 release.
----
New 2020-03-04 beta SPI firmware.
```
* Support static IP address configuration. The following fields may be
set manually using dotted decimal address. If set, then DHCP if skipped.
* CLIENT_IP
* SUBNET
* GATEWAY
* TFTP_IP
* If a fatal bootloader occurs then a HDMI …
```
=> rpi-eeprom: update to rpi-eeprom-<next>

packages/graphics/lcms2/package.mk, packages/graphics/libraw/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.mpo/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.raw/package.mk, packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk, packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk, packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk, packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
- imagedecoder.raw requires now lcms2 build along with libraw 0.19.5
- all binary addons updated
=> Kodi binary addons update

packages/security/openssl/cert/cacert.pem
Root CA 'AddTrust External Root' expired yesterday. In some cases, this causes troubles with implementations like GnuTLS, which is used as curl backend in LibreELEC.
The problem is described here:
https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration
I noticed this problem because the pvr plugin pvr.waipu is longer working. Running curl on LibreELEC fails due to certificate validation:
```bash
curl: (60) server certificate verification failed. CAfile: /run/libreelec/cacert.pem CRLfile: none
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
curl with Openssl …
=> Remove expired 'AddTrust External Root' ca from trust list

packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/bin/chrome-start, packages/addons/browser/chrome/source/default.py, packages/addons/browser/chrome/source/resources/language/English/strings.po, packages/addons/browser/chrome/source/resources/settings.xml, packages/addons/browser/chrome/source/settings-default.xml
Add a Dark Mode Toggle in Settings. 
Appends Chrome `--force-dark-mode` flag to enable Dark Mode for the browser. 
Defaults to Dark Mode off.
=> Add Dark Mode Toggle in Chrome Add-On

packages/mediacenter/kodi/package.mk
This prevents kodi from autodetecting the lcms2 lib which is not present
in the image.
picked from #4349
=> [le92] kodi: disable LCMS2

packages/multimedia/ffmpeg/patches/rpi-hevc/ffmpeg-001-pfcd_hevc_optimisations.patch
This fixes the kernel oops and kodi locking up issue reported here https://forum.libreelec.tv/thread/13245-kodi-18-0-update-for-slice/?postID=140610#post140610
Tested on RPi3B+
=> [le92] ffmpeg: update RPi HEVC patch to latest version

packages/audio/pulseaudio/package.mk
currently pulled via bluez, if no bluez is build glib:target is missing
=> pulseaudio: fix depend target for glib

packages/sysutils/systemd/package.mk, packages/sysutils/wait-time-sync/package.mk, packages/sysutils/wait-time-sync/sources/Makefile, packages/sysutils/wait-time-sync/sources/wait-time-sync.c, packages/sysutils/wait-time-sync/system.d/wait-time-sync.service
There was some [discussion in the forum](https://forum.libreelec.tv/thread/21906-wireguard-changes-the-default-route-although-not-configured/?postID=140348#post140348) that wireguard requires time-sync.target on systems without RTC.
Unfortunately the default systemd-time-wait-sync binary fails to detect system time slew adjusts and randomly hangs on devices with RTC (i.e. X86_64). The behavior is documented in the source, see [time-wait-sync.c](https://github.com/systemd/systemd/blob/v245/src/time-wait-sync/time-wait-sync.c#L117-L139).
Use the simple wait-time-sync tool instead.
(Only) tested on my Generic installation.
=>  wait-time-sync: new package to reliable detect ntp synchronized system time

packages/sysutils/systemd/package.mk, packages/sysutils/wait-time-sync/package.mk, packages/sysutils/wait-time-sync/sources/Makefile, packages/sysutils/wait-time-sync/sources/wait-time-sync.c, packages/sysutils/wait-time-sync/system.d/wait-time-sync.service
There was some [discussion in the forum](https://forum.libreelec.tv/thread/21906-wireguard-changes-the-default-route-although-not-configured/?postID=140348#post140348) that wireguard requires time-sync.target on systems without RTC.
Unfortunately the default systemd-time-wait-sync binary fails to detect system time slew adjusts and randomly hangs on devices with RTC (i.e. X86_64). The behavior is documented in the source, see [time-wait-sync.c](https://github.com/systemd/systemd/blob/v245/src/time-wait-sync/time-wait-sync.c#L117-L139).
Use the simple wait-time-sync tool instead.
Backport of  #4413
=> wait-time-sync: new package to reliable detect ntp synchronized system time

packages/network/wireguard-linux-compat/package.mk, packages/network/wireguard-tools/config/system.d/wireguard.service.sample, packages/network/wireguard-tools/package.mk
Add a dependency on `wait-time-sync.service` to the sample wireguard service and bump the wireguard-linux-compat and tools packages to current versions.
=> wireguard: bump packages and use wait-time-sync

packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/patches/vdr-plugin-xmltv2vdr-03-fix-epgdata2xmltv-linking.patch
this fixes vdr-addon build failure
build-tested for RPi4
=> vdr-plugin-xmltv2vdr: fix epgdata2xmltv static linking issue

packages/tools/rpi-eeprom/package.mk
partial backport of #4399 
RPi bootloader EEPROM with USB boot support has just been promoted to stable.
Bump rpi-eeprom so that the eeprom image is included in LE release images and available for manual update.
LE settings checks the critical branch so it won't be offered via the GUI for automatic update but users can manually upgrade the eeprom with
```
FIRMWARE_RELEASE_STATUS=stable rpi-eeprom-update -a
```
=> [le92] rpi-eeprom: update to 2a8c2e7

packages/compress/zstd/package.mk, packages/devel/glibc/package.mk, packages/lang/Python3/package.mk, packages/lang/gcc/package.mk, packages/multimedia/dav1d/package.mk, packages/security/gnutls/package.mk, packages/security/openssl/package.mk, packages/sysutils/tz/package.mk, scripts/image
Half is package bumps.
glibc minimum kernel version raised after rockchip-4.4's removal.
gcc changes host's c++ standard used to c++14 (the default since gcc6; target gcc already using default)
scripts/image zstd default compression for squashfs images has been 19. Setting value >19 requires passing --ultra (which I'm not sure is supported when called by squashfs). Just change stated default to 19 which is what has been getting tested.
=> April 2020 Package Updates

packages/addons/service/docker/source/system.d/service.system.docker.service
If you have multiple docker containers, boot process is slowing down drastically. Lets docker starting lastly.
=> Make docker not slowing down boot proccess

packages/addons/addon-depends/jre-depends/apache-ant/package.mk
We don't really need to build ant from source, as we don't use any
non-standard build options.
This avoids downloading dependencies at build time that maven stores
outside the build dir (to $HOME/.m2/repository). That also fixes build
issues on jenkins.
=> apache-ant: update to 1.10.8, switch to binary distribution

packages/addons/addon-depends/jre-depends/apache-ant/package.mk
this was accidentally removed in 387c11e253
=> apache-ant: make sure ${TOOLCHAIN}/bin exists

packages/multimedia/dav1d/package.mk
```
This release increases the speed of decoding on ARM32 by up to 28%,
adds some SSE2 optimizations, some AVX2 for MC scaled
and fixes a couple of minor issues.
```
builds for generic and armv8
=> dav1d: update to 0.7.1

packages/addons/addon-depends/ffmpegx-depends/libvpx/package.mk, packages/addons/addon-depends/ffmpegx-depends/x265/package.mk, packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk, packages/multimedia/aom/package.mk
changes are not yet runtime tested
I have not updated Tvh or Emby that depend on that addon at buildtime, its a bit meh but I think okay at the current state.
=> ffmpeg tools update

packages/multimedia/rtmpdump/patches/002_build-with-openssl11.patch
This patch update fixes issues with rtmpe streams and swf hash auto-calculation causing core dumps and Kodi crashes.
For more info, refer to https://github.com/xbmc/inputstream.rtmp/pull/46
=> Update SSL 1.1 patches

packages/addons/addon-depends/system-tools-depends/unrar/package.mk
strip program is used from host, which may not know target architecture.
=> unrar: Fix compilation

packages/addons/addon-depends/system-tools-depends/diffutils/patches/diffutils-001-no-man-or-doc.patch, packages/addons/addon-depends/system-tools-depends/screen/package.mk
diffutils jenkins build is failing in install doc phase, I couldn't reproduce that locally but as we don't need the docs anyways just drop them from recursive build/install. This should fix builds on jenkins, too.
I could reproduce the screen build issue, the "comm.h" not found error seems to be caused by a parallel build race. Building non-parallel fixed the issue here.
=> fix system-tools build

packages/graphics/bcm2835-driver/package.mk, packages/tools/bcm2835-bootloader/package.mk
partial backport of #4430 
This should fix channel swaps when playing multi-channel audio on RPi4
As I don't have a multi-channel AVR/setup it would be great if someone could runtime test this PR and check if the issue is resolved before merging.
=> RPi4: update to firmware 2b76cfc

packages/addons/addon-depends/rpi-tools-depends/RPi.GPIO/package.mk
This is due -fno-common being default starting with GCC 10. Because code was clearly written with "-fcommon" assumption, I just added it to CFLAGS.
=> RPi.GPIO: Fix compilation with gcc10

packages/network/samba/package.mk
Disclaimer, this is just a HACK because I found no proper way. Better ideas are welcome :)
If you build icu before samba, icu gets used at samba buildtime and fails (all archs).
That function was introduced at Samba 4.12 https://github.com/samba-team/samba/commit/107020793c7ea44e5e776a1401bbf4f8ccb9bd85
Likely the same happens if you have icu-dev at the host system.
```
[ 911/2444] Compiling libcli/security/dom_sid.c
/LE/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.1.0/../../../../x86_64-libreelec-linux-gnu/bin/ld: lib/util/charset/iconv.c.1.o: in function `sys_uconv':
iconv.c:(.text+0x9ba): undefined reference to `u_strFromUTF8_61'
/LE/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.1.0/../../../../x86_ …
```
=> samba: disable automatic icu pickup

packages/sysutils/busybox/config/busybox-init.conf, packages/sysutils/busybox/scripts/init
usleep is used by init's functions to create quarter and half second progress reports. Not having it spams output with the equivalent of 'usleep not found' when running spinners or percent progress.
=> Return usleep to busybox init

packages/emulation/libretro-fsuae/package.mk
This PR fixes compilation of game.libretro.fsuae addon with gcc 10.
=> libretro-fsuae: Fix compilation with gcc10

projects/Rockchip/patches/linux/default/linux-0011-v4l2-from-5.8.patch
There are few patches which are already merged. Removing from the .patch file to be able to compile the rockchip kernel.
=> Remove already existing kernel patches for Rockchip project

packages/mediacenter/kodi-binary-addons/visualization.matrix/package.mk
Hi.
This PR adds my new Matrix viz (https://github.com/sarbes/visualization.matrix) to Kodi. I've tested in on a RPI 1, where it archived 40-50 fps.
This is a pre-release version to get some feedback in.
=> Kodi binary add-ons: add visualization.matrix

packages/graphics/bcm2835-driver/package.mk, packages/tools/bcm2835-bootloader/package.mk
Partial backport of #4430 
The USB GPT fix may be beneficial to people using USB boot.
See https://github.com/raspberrypi/firmware/commit/66fc5eaac3d0af1d5a7ffa616086cbfaefd72e98 for changelog
I've been testing this firmware on my main LE9.2/RPi4 setup the last week and haven't noticed any issues yet
=> RPi4: update to July 2 firmware 66fc5ea

packages/audio/alsa-lib/patches/alsa-lib-001-iec958-hbr.patch, packages/audio/alsa-lib/patches/alsa-lib-002-iec958-format.patch, projects/RPi/filesystem/usr/share/alsa/cards/vc4-hdmi.conf
It's early days, everything still quite experimental, but initial tests looked fine and it would be good to get some more feedback.
Note: this depends on PR #4430
=> RPi4: add support for HBR audio passthrough (DTS-HD, TrueHD)

projects/Allwinner/patches/linux/0005-cedrus-improvements.patch, projects/Allwinner/patches/linux/0007-drm-fixes.patch
1. DRM patchset prevents glitches during playback. In some cases display engine was left in semi-usable state and only reboot solved the issue.
2. VPU patch prevents decoding videos with unsupported features in HW like 10-bit H264
=> Allwinner: DRM and VPU driver fixes

packages/mediacenter/kodi/package.mk
=> [le92] kodi: update to 18.8-Leia

packages/tools/rpi-eeprom/package.mk
partial backport of #4485 
New stable bootloader eeprom version 2020-07-16, new stable USB eeprom version 000138a1
=> [le92] rpi-eeprom: update to 8e9aca3

distributions/LibreELEC/options, distributions/LibreELEC/show_config, packages/mediacenter/kodi/package.mk, projects/Amlogic/options, projects/RPi/options, projects/Samsung/options
Runtime tested on RPi4 and RPi2 build on RPi3B+
As RPi has been switched to upstream kodi tree and no other project uses kodi vendor trees we can drop support for vendor trees.
=> kodi: update to 19.0a1-Matrix, drop kodi vendor tree support

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/service/tvheadend42/changelog.txt, packages/addons/service/tvheadend42/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk, packages/security/gnutls/package.mk, packages/security/nettle/package.mk
gnutls to 3.6.14
nettle to 3.6
ffmpegx to 4.2.4
ffmpeg-tools + tvheadend42 addon bumps to pull above in.
Only compile tested.
=> LE9.2 bump gnutls/nettle/ffmpeg

packages/emulation/libretro-pcsx-rearmed/package.mk, packages/emulation/libretro-pcsx-rearmed/patches/libretro-pcsx-rearmed-0001-aarch64-support.patch
The _game.libretro.pcsx-rearmed_ addon is currently broken and is crashing Kodi in both _master_ and _libreelec-9.2_ branches. The build needs to be updated to reflect the changes in the upstream Makefile.libretro:
https://github.com/libretro/pcsx_rearmed/commit/3d96277d011b4d683d682740eed61b1113a613b1
Fixes https://github.com/LibreELEC/LibreELEC.tv/issues/4431
Needs backport to LE 9.2
This is a second try to clean up the original PR #4469.
=> libretro-pcsx-rearmed: fix PCSX ReARMed build

packages/emulation/libretro-pcsx-rearmed/package.mk, packages/mediacenter/kodi-binary-addons/visualization.matrix/package.mk
libretro-pcsx-rearmed needs -fcommon with gcc 10 and visualization.matrix needs the fixes from the not yet released snapshot we had in LE before the last bump
=> fix game.libretro.pcsx-rearmed and visualization.matrix addon builds

packages/graphics/bcm2835-driver/package.mk, packages/tools/bcm2835-bootloader/package.mk
This should fix the black screen issues on TVs which default to interlaced mode in their edid as reported in #4523 and on the forum https://forum.libreelec.tv/thread/22478-updated-now-no-picture/ https://forum.libreelec.tv/thread/22477-libreelec-leia-9-2-4/?postID=143437#post143437
Test build is available here: https://www.horus.com/~hias/tmp/libreelec/LibreELEC-RPi4.arm-9.2-devel-20200817130411-96056bf.tar
Local testing with that build and the edids in the #4523 issue was fine, but wait for user feedback before merging
=> [le92] RPi4: revert back to June 26 firmware

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml
When people create issues they really should fill out the form and include log files.
Disable the "Open blank issue" link via config.yml and move "Log file" to a separate section so it's clearer that we want these.
=> improve github issue template

packages/security/nss/patches/nss-09-gcc-warning-workaround.patch
Due to unfortunate combination of glibc 2.32, gcc 10 and nss code and compiler flags, nss:host doesn't build anymore. nss has -Wall flag set which cause aggressive code checks. Those checks produce warning even though nss code is correct albeit it's using glibc specific behaviour. nss also sets -Werror flag which then breaks build.
=> nss: Fix building with glibc 2.32 and gcc 10

packages/lang/Python3/package.mk, packages/lang/Python3/patches/Python3-0000-default-is-optimized.patch, packages/lang/Python3/patches/Python3-0100-buildroot-patches.patch, packages/lang/Python3/patches/Python3-0201-xcompile.patch, packages/lang/Python3/patches/Python3-0202-xcompile.patch, packages/python/system/dbus-python/package.mk
Updates python to 3.8.5. Most patches required refreshing due to some refactoring upstream. I believe I've adjusted everything correctly.
Briefly tested on RPi3.
=> python: update to 3.8.5

packages/sysutils/eventlircd/evmap/skyqremote.evmap, packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Add support for SKY-Q remote (just this model).
Besides the usual button configuration I added some buttons that don't have a proper usage at Kodi.
1 - Stop
2 - tv
3 - videos
4 - music
5 - pictures
6 - directly to livetv
7 - directly to epg
Due the strange default handling of the power button you should add that to the keymaps otherwise you likely shutdown your htpc a lot. The kodi default is rather insane for modern remotes :(
`/storage/.kodi/userdata/keymaps/remote.xml`
```
<keymap>
<global>
<remote>
<power>ActivateWindow(ShutdownMenu)</power>
</remote>
</global>
</keymap>
```
**Pairing:**
press 7+9 till the red led goes off
wait 2-3sec
press 1+3 till the red led starts blinking
pair at LE
=> add support for SKY-Q remote

packages/sysutils/busybox/package.mk, packages/sysutils/busybox/scripts/init, packages/sysutils/busybox/scripts/libreelec-target-generator
Setting the target unit via the `--unit` systemd option has the huge disadvantage that it doesn't play nicely with software that expects the default unit to be set via the standard mechanisms (`systemctl set-default` or via `systemd.unit` kernel command line option).
The `systemd-debug-generator` is such an example, currently the debug shell only works when booting into kodi.target but not in installer, textmode, backup-restore or all other targets where a debug shell might be highly wanted.
The solution is rather easy though, instead of using the `--unit` option we can use a systemd generator to dynamically symlink the default target if needed.
Runtime tested on RPi4 with textmode, factory reset and fs-resize targets and with x86_64 installer.
=> use a systemd generator for selecting the default target

packages/mediacenter/kodi/config/appliance.xml
Kodi defaults to require authentication when the webserver is
enabled and as no password is set this results in an annoying
error box on fresh installations.
As neither disabling authentication or pre-setting a well known
password are great options just stop enabling the webserver via
appliance.xml. Users can enable it and choose authentication options
if they like via settings.
=> kodi: don't enable webserver by default

config/arch.aarch64
ARMv8.0-A cpus have an optional LSE feature. This is mandatory in ARMv8.1-A. By default, gcc will attempt to build support for runtime detection of the LSE feature on ARMv8.0-A. This causes build failures when attempting to create a 64-bit userland.
Packages that fail include gdb and mesa.
My understanding is this flag will be ignored on >=ARMv8.1 targets. I don't know that there are any such targets in LE at present, or if there are, if they're being built with a 64-bit userland.
Patch tested atop #4406 and an RPi3.
From GCC's docs: 
-moutline-atomics
-mno-outline-atomics
Enable or disable calls to out-of-line helpers to implement atomic operations. These helpers will, at runtime, determine if the LSE instructions from ARMv8.1-A can be used; if not, they will use the load/store-exclusive …
=> arch.aarch64: don't attempt to use the LSE cpu feature

scripts/mkimage
This is a leftover from ancient times when mkimage had to be run via sudo.
=> scripts/mkimage: drop chowning image to SUDO_USER

config/addon/xbmc.broken.xml, config/addon/xbmc.python.module.xml, config/addon/xbmc.python.script.xml, config/addon/xbmc.service.library.xml, config/addon/xbmc.service.pluginsource.xml, config/addon/xbmc.service.xml, distributions/LibreELEC/version, packages/addons/script/script.config.vdr/package.mk, packages/addons/script/script.config.vdr/sources/addon.xml, packages/addons/service/touchscreen/addon.xml, packages/addons/service/tvheadend42/addon.xml, packages/mediacenter/kodi/config/os.libreelec.tv/addon.xml, packages/mediacenter/kodi/config/os.openelec.tv/addon.xml, packages/mediacenter/kodi/package.mk
Getting rid of the add-on dependency to LE (and OE). 
Since LE9 it creates a annoying confirmation window for every add-on regardless if a dependency is needed or not.
- removed requirements for LE addons
- removed requirements for Kodi bin addons
- bump add-on repo version
Drawback: You could now install the addons somewhere else (Windows ...) and they won't work.
=> addons: drop dependency to LE

scripts/mkimage
Fix for [bug report](https://forum.libreelec.tv/thread/22357-libreelec-9-2-3-console-does-not-open-using-control-alt-f3/) in the forum.
systemd-debug-generator must be configured if not booting into systemd's `default.target`. In our case `installer.target` has to be set.
Backport of #4494
=> mkimage: really enable debug shell for installer

projects/RPi/devices/RPi/kodi/appliance.xml, projects/RPi/kodi/appliance.xml
The appliance.xml settings to show the guisize limit option in kodi settings got lost when moving to upstream kodi/gbm, add them back.
=> RPi: show guisize limit options in kodi

packages/graphics/libdrm/package.mk
=> libdrm: update to 2.4.102

packages/mediacenter/LibreELEC-settings/package.mk, packages/python/system/dbussy/package.mk
dbussy https://github.com/ldo/dbussy seems to be a very nice alternative to the other python dbus bindings. It's implemented purely in python 3 and only requires libdbus to be installed on the system.
I did a few quick test with the examples from https://github.com/ldo/dbussy_examples , `list_bus_names` and `introspect_all system net.connman` worked fine.
ping @edit4ever please have a look at this
=> add dbussy python package

packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat
This picks the firmware needed for WiFi support on Dell (Wyse) 3040 devices into the Generic image, as per forum posts:
https://forum.libreelec.tv/thread/21537-dell-wyse-3040-wifi-not-working/
=> linux-firmware: pick mrvl/sd8897_uapsta.bin for Generic

packages/sysutils/busybox/scripts/getedid
there's currently no need to check for the kernel in use anymore as the variable `$kernel` also is nowhere in use anymore. Hence we could clean that.
=> [getedid] remove kernel check

packages/sysutils/e2fsprogs/package.mk
Tested via hard reset on rpi3.
I dropped the symlinks for ext4dev because it stopped being a thing after 2.6.28 released (~2008), and I'm not sure LE could even mount such a filesystem (it's not listed in /proc/filesystems).
=> e2fsprogs: update to 1.45.6

packages/mediacenter/LibreELEC-settings/scripts/backup-restore, packages/sysutils/busybox/scripts/libreelec-target-generator
This allows restoring the system with a compressed tarball. gzip, bz2, and xz are the compressed formats busybox's tar understands, so those are wired up. Busybox's shell doesn't understand brace expansion, so using word splitting to cycle through the file extensions.
=> system: accept compressed configuration backups

packages/emulation/libretro-atari800/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
Runtime tested on RPi4.
Note: be careful for now with the update_retroplayer-addons script, libretro-atari800 is currently ahead of the version referenced by the kodi addon.
The libretro-atari800 bump is required as the currently referenced version doesn't build (libretro-atari800 got a git submodule a few months ago, so the archive was missing code, and this was finally reverted just 3 days ago).
=> add game.libretro.atari800

packages/network/connman/package.mk
Fixes a minor nit with ipv6 and the dns re-resolve feature added recently.
=> connman: minor bump for wireguard ipv6 issue

packages/sysutils/systemd/patches/systemd-0100-backport-pr-17267.patch
Revert the problematic systemd commit (plus a dependent one) that
causes partitions to be missing in kodi's "Files" list.
See https://github.com/systemd/systemd/issues/17259
=> systemd: add backport patch to fix device enumeration

packages/linux-drivers/bcm_sta/patches/bcm_sta-0400-kernel-5.9-fix.patch
This is required for Generic after #4594
=> bcm_sta: fix building on Linux 5.9

projects/Allwinner/devices/H6/patches/u-boot/008-wip-h6-dram-fix.patch
Some boards have issues booting due to DDR3 initialization. Rework that process.
=> Allwinner: H6: u-boot: fix rate DDR3 init issues

packages/sysutils/systemd/patches/systemd-0101-backport-pr-16648-16885.patch
This fixes systemd hanging on boot if no LAN cable is plugged
in (and thus time not set from NTP) with one core spinning at
100% CPU load.
See also this bug report on the forum
https://forum.libreelec.tv/thread/22806-rpi2-nightly-builds-stuck-at-le-logo-on-rpi-3/
=> systemd: backport cache timestamp fixes from master

packages/mediacenter/kodi/config/kodi.conf, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/system.d/kodi.service
Only set DISPLAY or WAYLAND_DISPLAY if actually running under
x11/wayland. This fixes latest kodi gbm refusing to start because
it thinks a window manager is active.
Also set the Nvidia-specific __GL_YIELD only when Nvidia drivers
are actually used and drop SDL_MOUSE_RELATIVE - kodi stopped using
SDL a long time ago.
Runtime tested on RPi4. Generic build test also looks good (correct /usr/lib/kodi/kodi.conf file created), but it would be nice if someone could runtime test this on Generic
=> kodi: move environment variables in systemd unit to environment file

README.md
This PR does some overdue cleanup to the README file: we forked 4.5 years ago, and we swapped from forum tickets to GH issues recently. It also rewords the copyright section for brevity and credits OpenBricks/GeekBox as the original source and inspiration for the build system we later inherited, to resolve #4607.
=> README: revise general text and credit OpenBricks/GeeXboX build system in copyright

packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/devel/libfmt/package.mk, packages/devel/spdlog/package.mk, packages/graphics/mesa/package.mk, packages/network/rsync/package.mk, packages/network/samba/package.mk
Run tested on RPi3. 
rsync:host tested in build. rsync:target (and hence network-tools) was not. Some configuration changes to make use of zstd (available on host) and external zlib on host & target since it's available and shrinks package slightly iirc. Makes it incompatible with very old versions of rsync (like 6+ years old).
samba-4.12.8 is available but made changes to heimdal which affects a patch here. Could be trivial; I didn't look.
=> October Package Updates 2: Electric Boogaloo

packages/tools/rpi-eeprom/package.mk
This makes the latest bootloader eeprom (2020-09-03) and VIA VL805 firmware (000138a1) versions available via LE settings.
rpi-eeprom-config now also includes a rather handy bootloader config edit option ("-e").
=> [le92] rpi-eeprom: update to latest version

tools/mkpkg/update_common_functions, tools/mkpkg/update_retroplayer-addons
If no tag with the kodi branch name can be found, fall back to the
latest tag in the branch.
This fixes ambiguity if both a -Leia and a -Matrix tag point to the
same githash.
=> update_retroplayer-addons: match lastest tag with kodi branch in name

packages/mediacenter/kodi/package.mk
=> [le92] kodi: update to 18.9-Leia

packages/addons/addon-depends/tini/package.mk
Fixes #4541
Could that be backported to 9.2?
=> Don't define -DMINIMAL=ON for tini

packages/linux-drivers/RTL8812AU/package.mk
Change the source code from @MilhouseVH repository to  [aircrack-ng](https://github.com/aircrack-ng/rtl8812au).
Repository looks maintained and updated.
aircrack-ng is used as upstream by other projects like [armbian](https://github.com/armbian/build/blob/master/lib/compilation-prepare.sh#L317).
=> RTL8812AU: Change source code to aircrack-ng

packages/graphics/kmscube/package.mk
FDO moved their upstream repos to gitlab so switch URLs to use them and bump to current HEAD. The buildsystem also changed to meson but setting "auto" works fine.
=> kmscube: bump to HEAD and revise package

projects/Allwinner/devices/H6/patches/linux/21-pineh64-model-b-wifi-bt.patch, projects/Allwinner/patches/linux/0008-ethernet-fixes.patch
This PR fixes one last ethernet issue, this time on OrangePi One Plus and adds BT and wifi support on PineH64 model B.
=> Allwinner: ethernet fix and bt/wifi support

packages/network/rsync/package.mk
broken for target since https://github.com/LibreELEC/LibreELEC.tv/pull/4604
@antonlacon, looks working
added 
```
--disable-asm \
--disable-md2man \
--disable-simd \
```
and sorted options
=> rsync: fix target build

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Sync with RPi-Distro repos, add Pi 400 firmwares
=> brcmfmac_sdio-firmware-rpi: update to 9c0ffe9

packages/graphics/mesa/package.mk
This PR updates Mesa to 20.2.2. Tested running on Generic.
Updating as it addresses a couple of intel bugs.
=> mesa: Update to mesa 20.2.2

projects/Allwinner/patches/linux/0009-ir-improvements.patch, projects/Allwinner/patches/linux/0010-regulator-fix.patch
This PR fixes boot on R40 (upstream kernel issue is not yet resolved) and improves IR driver (patch pending upstream) so it doesn't spam dmesg anymore.
Both patches may benefit other Allwinner SoCs too.
=> Allwinner: Fix R40 boot and IR

packages/linux-firmware/intel-ucode/package.mk
Resolution for SRBDS. 
Was previously rolled back in 20200616. 
Fixes Skylake CPUs. 
Also security updates for:
Security updates for INTEL-SA-00381.
Security updates for INTEL-SA-00389.
Release notes at https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases
Tested on NUC6
[    0.000000] microcode: microcode updated early to revision 0xe2, date = 2020-07-14
[    0.000000] Linux version 5.9.7 (rudi@10ad6d490609) (x86_64-libreelec-linux-gnu-gcc-10.2.0 (GCC) 10.2.0, GNU ld (GNU Binutils) 2.34) #1 SMP Wed Nov 11 10:04:38 UTC 2020
[    0.222354] SRBDS: Mitigation: Microcode
[    0.226459] smpboot: CPU0: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (family: 0x6, model: 0x4e, stepping: 0x3)
[    1.589680] microcode: sig=0x406e3, pf=0x40, revision=0xe2
[    1.589838] microcode: …
=> intel-ucode: update to intel-ucode-20201110

packages/network/bluez/package.mk
Tested in my own Amlogic images .. it didn't break (or fix) anything :)
=> bluez: bump to 5.55 release

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/default.py
Since guisettings.xml settings format was changed to version 2 the default audio device wss not detected any more.
Use Kodi json RPC to read the string.
at-spi2-core: building of the package failed when dbus-daemon binary was not installed on the build host (i.e. LE docker image). Set the target path.
In third commit the usage of oe.py is removed and a log warning fixed.
Runtime tested and checked that different device names are passed to chrome commend line.
=> chrome: fix default audio device detection

packages/addons/service/bluetooth-audio/changelog.txt, packages/addons/service/bluetooth-audio/package.mk, packages/addons/service/bluetooth-audio/source/bin/dbusservice.py, packages/addons/service/bluetooth-audio/source/default.py
Python 3 version of #3925 
There are still issues using dbus-python multi threaded, i.e. disabling bluetooth-audio addon terminates LibreELEC-settings  dbus bluetooth connection.
=> bluetooth-audio: Python 3 support / use separate dbus process

packages/linux-firmware/brcmfmac_sdio-firmware/scripts/brcmfmac-firmware-setup
Use BCM43430A1.vim for Banana Pi M2 Zero
=> brcmfmac_sdio-firmware: Banana Pi M2 Zero fix

packages/addons/addon-depends/chrome-depends/chrome-libxkbcommon/package.mk, packages/addons/addon-depends/chrome-depends/cups/package.mk, packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk
- added a buildfix for cups, if avahi and nss-mdns is build cups is confused
- libxkbcommon.so.0 is now required by chrome
[browser.chrome-9.80.8.104.zip](https://github.com/LibreELEC/LibreELEC.tv/files/5580472/browser.chrome-9.80.8.104.zip)
=> chrome: fix latest version

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libxkbcommon/package.mk, packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/default.py
Since guisettings.xml settings format was changed to version 2 the default audio device wss not detected any more.
Use Kodi json RPC to read the string.
at-spi2-core: building of the package failed when dbus-daemon binary was not installed on the build host (i.e. LE docker image). Set the target path.
Runtime tested and checked that different device names are passed to chrome commend line.
Partial backport of #4665 and #4686
=> chrome: fix default audio device detection / update for latest version

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Add nvram files for CuBox-i rev 1.3
=> brcmfmac_sdio-firmware: update to 6d49ff1

packages/linux-firmware/intel-ucode/package.mk
20201110 firmware has been running fine on my 5.9.x kernels 
My CPU
[    0.000000] microcode: microcode updated early to revision 0xe2, date = 2020-07-14
[    0.224611] smpboot: CPU0: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (family: 0x6, model: 0x4e, stepping: 0x3)
20201118 removes the following
- Removed TGL/06-8c-01/80 due to functional issues with some OEM platforms. 
Which are the following CPUs
- Core Gen11 Mobile
20201112 adds the following
- Security updates for INTEL-SA-00381.
- Security updates for INTEL-SA-00389.
For 
- Pentium Silver N/J5xxx, 
- Celeron N/J4xxx
=> intel-ucode: update to intel-ucode-20201118

packages/graphics/mesa/package.mk
Update to Mesa.
Tested on Generic / Intel NUC6i5SYB / Intel(R) Core(TM) i5-6260U
Minor bug fixes - https://docs.mesa3d.org/relnotes/20.2.3.html
2020-11-29 20:40:45.507 T:1144     INFO <general>: CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 20.2.3, Major: 4, Minor: 6
2020-11-29 20:40:45.507 T:1144     INFO <general>: GL_RENDERER = Mesa Intel(R) Iris(R) Graphics 540 (SKL GT3)
2020-11-29 20:40:45.507 T:1144     INFO <general>: GL_VERSION = 4.6 (Core Profile) Mesa 20.2.3
2020-11-29 20:40:45.508 T:1144     INFO <general>: GL_EXTENSIONS =
=> mesa: update to 20.2.3

packages/python/devel/ninja/package.mk
Split ninja out of package update #4667 bundle, as 1.10.2 was released. Package update has had 1.10.1 in it for a while.
Release notes are at:
https://groups.google.com/g/ninja-build/c/oobwq_F0PpA/m/FeJC5LoRBgAJ
Differences between 1.10.1 (tested extensively on Generic) and 1.10.2 are https://github.com/ninja-build/ninja/compare/v1.10.1...v1.10.2 .
=> ninja: update to v1.10.2

packages/x11/lib/libX11/package.mk
Splitting libX11: update to 1.6.12 out of main package update #4667 bundle.
Version 1.7.0 is out but it does include a new API. Suggesting we update to 1.6.12 which has been tested extensively on Generic. With a plan to merge 1.7.0 subsequently.
https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/README.md
=> libX11: update to 1.6.12

packages/tools/bcm2835-bootloader/files/config.txt
Add commended-out example dtoverlay line and info how to enable
GPIO IR receiver.
=> bcm2835-bootloader: config.txt cosmetics

packages/sysutils/busybox/scripts/dthelper
iMX6 devices use the `fsl` compatible
=> busybox: add fsl to dthelper compatibles

packages/multimedia/gmmlib/package.mk, packages/multimedia/libva/package.mk, packages/multimedia/media-driver/package.mk
For clean build with Mesa 20.3.0 https://github.com/LibreELEC/LibreELEC.tv/pull/4713 - I needed to update to Intel media-driver 20.4.2.
Note: 20.4.3 is not compiling https://github.com/intel/media-driver/issues/1103
```
01:45:24 up 22:58,  load average: 1.17, 1.22, 2.04
Generic.x86_64-devel-20201207142003-b781374
Linux LibreELEC 5.9.12 #1 SMP Mon Dec 7 14:05:54 UTC 2020 x86_64 GNU/Linux
Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
Kodi compiled 2020-12-07 by GCC 10.2.0 for Linux x86 64-bit version 5.9.12 (329996)
Running on LibreELEC (community): devel-20201207142003-b781374 9.80, kernel: Linux x86 64-bit version 5.9.12
FFmpeg version/source: 4.3.1-Kodi
Host CPU: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz, 4 …
```
=> media-driver: update to 20.4.3

packages/network/samba/package.mk, packages/network/samba/patches/samba-950-no-man.patch, packages/network/samba/patches/samba-951-no-man-4.13.patch
Update to current stable samba. Minor changes to patch files. 
This stable release of samba 4.13 will become maintenance in~ March 2021, and Security in ~ Sep 2021. So candidate to LE10 release. 
https://wiki.samba.org/index.php/Samba_Release_Planning
=> samba: update to current stable 4.13.2

packages/sysutils/util-linux/package.mk
Bump to 2.36.1 (current release of util-Linux).
Plan to move to 2.37 when released to support ARM changes.
https://github.com/karelzak/util-linux/issues/1207
=> util-linux: update to 2.36.1

packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/bin/chrome-downloader
Partial backport of #4702 including a work around for the missing post_install_addon() function.
No package bump either due merged with latest fix
The first commit is to sanitize the curl output. When i.e. German locale is configured "35,7%" is printed instead of "35.7%". The comma must not be used without protection.
LE9.2 testbuild: [browser.chrome-9.2.0.104.zip](https://github.com/LibreELEC/LibreELEC.tv/files/5632414/browser.chrome-9.2.0.104.zip)
=> chrome: update to 87 and using fixed versions / minor downloader fixes

packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/bin/chrome-downloader
- using fixed versions instead of "latest"
- cleanup of the chrome package
- no package bump due merged with latest fix
should stop breaking the package, old addon version installs old chrome version so likely more stable in general
LE10 test file
[browser.chrome-9.80.8.104.zip](https://github.com/LibreELEC/LibreELEC.tv/files/5616593/browser.chrome-9.80.8.104.zip)
=> chrome: update to 87 and using fixed versions

projects/Rockchip/devices/RK3399/README.md, scripts/uboot_helper
Fixes #4725 
It'd be nice to actually break the build in the event that DTBs are missing (I presume somewhere in `packages/Rockhip/bootloader/release`), but I'm not sure how that would affect the development workflow for the other Rockchip targets -- I see that there's a glob copy of all DTBs to DSTDIR but I'm assuming only one of those is actually necessary when building using the `make image` lines from the READMEs...
=> Fix Rock Pi 4 nightly builds

packages/network/openssh/system.d/sshd.service
This forum thread https://forum.libreelec.tv/thread/22564-official-le-test-images-for-amlogic-kodi-19/?postID=147436#post147436 flagged an issue where the SSH service cannot be enabled in the first-run wizard, and a suggested fix from CE which forces `/storage/.cache/ssh` to exist before the service starts. This works, but we create `/storage/.cache/ssh` and other similar dirs on first run via tmpfiles.d so the underlying issue is service ordering and we simply need to ensure tmpfiles.d runs before sshd starts. This can be done via wanting `systemd-tmpfiles-setup.service` or `network.target` in sshd.service. I've chosen the former so the relationship is more obvious. The change has been validated by the affected user.
=> openssh: ensure tmpfiles.d completes before sshd starts

packages/graphics/mesa/package.mk
This PR bumps mesa to 20.3.0 which is the first official release to support ARM Mali Bifrost GPUs with Panfrost. I've also switched the package source to the official FDO gitlab instance as this makes tracking mesa development snapshots easier (replace the version tag with a githash in package.mk). I've also cleaned up some of the build options where true/false are deprecated in favour of enabled/disabled and `drm` has been dropped (drm/surfaceless are enabled by default). I've only changed the true/false options that I have seen warnings on during build. There are probably more to change with different build options (something for future PRs).
=> mesa: bump to 20.3.0 and change source url

packages/network/openvpn/package.mk
Feel free to close if there is a plan to update to 2.5 instead of continuing to track 2.4.x.
=> openvpn: update to 2.4.10

packages/multimedia/dav1d/package.mk
The dav1d team have been making some good improvements, and 1080p AV1 files can now reliably be played on most of the LE platforms that you would expect to be capable of 1080p software decoding.
=> dav1d: updated to 0.8.0

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Sync with current RPi OS:
Add BCM43436 firmware
Fix 80MHz channels on BCM43456
Fix higher 5GHz channel and BLE issues on CYW43455
=> brcmfmac_sdio-firmware-rpi: update to c13705a

packages/network/samba/package.mk
Minor bug fixes for samba
https://www.samba.org/samba/history/samba-4.13.3.html
next planned bug fix release for samba - Tuesday, January 26 2020 - Planned release date for Samba 4.13.4.
=> samba: update to 4.13.3

packages/compress/libarchive/package.mk, packages/compress/lz4/package.mk, packages/compress/xz/package.mk
Update the following compres packages to current:
libarchive/package.mk 3.5.0
lz4/package.mk 1.9.3
minizip/package.mk 2.10.4
xz/package.mk 5.2.5
**Note: fixed minizip - it hadn't been compiling. miniunz_exec and minizip_exec were not valid targets, even when BUILD_TEST was corrected to MZ_BUILD_TEST
=> Compress packages updated

packages/wayland/libinput/package.mk, packages/wayland/libxkbcommon/package.mk, packages/wayland/mtdev/package.mk, packages/wayland/wayland-protocols/package.mk, packages/wayland/wayland/package.mk, packages/wayland/waylandpp/package.mk, packages/wayland/weston/package.mk
Moved wayland updates out of https://github.com/LibreELEC/LibreELEC.tv/pull/4667 
and updated
- libinput: update to 1.16.4
- libxkbcommon: update to 1.0.3
=> Wayland packages updates

packages/compress/lz4/package.mk
The cmake files were moved upstream [0] and the build now fails because it
silently falls back to the GNU Makefile:
install: cannot change permissions of '/usr/local/bin/': Operation not permitted
Point to the new location and set PKG_TOOLCHAIN explicitely to "cmake", which
would have caugth this issue:
CMake Error: The source directory "/tmp/libreelec/build.LibreELEC-H6.arm-9.80-devel/build/lz4-1.9.3/contrib/cmake_unofficial" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
FAILURE: ./scripts/build lz4:host during configure_host (default)
[0] https://github.com/lz4/lz4/commit/31d477db07c999afd639c3a37105894ecbf710fc
=> lz4: fix compilation

packages/python/graphics/Pillow/package.mk
Update to latest pillow and PKG_SITE.
Validated the backwards compatibilities via git grep and versions.
- https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
- https://pillow.readthedocs.io/en/stable/releasenotes/8.0.1.html
built and running against Generic
=> Pillow: updated to 8.0.1 and fixed PKG_SITE

packages/python/system/simplejson/package.mk
Minor bump from 3.17.0 to 3.17.2 
I have reviewed the code changes - they are minor
- https://github.com/simplejson/simplejson/compare/v3.17.0...v3.17.2
Change list is:
Version 3.17.2 released 2020-07-16
* Added arm64 to build matrix and reintroduced   manylinux wheels
https://github.com/simplejson/simplejson/pull/264
* No more bdist_wininst builds per PEP 527
https://github.com/simplejson/simplejson/pull/260
* Minor grammatical issue fixed in README
https://github.com/simplejson/simplejson/pull/261
=> simplejson: update to 3.17.2

packages/network/connman/package.mk
This include the revert of e17f601cf4af77bcc0b3cfe576c5d0414511e5aa
https://git.kernel.org/pub/scm/network/connman/connman.git/commit/?id=9aede91e811adc1d57518bd7ef108871acfdcab8
=> connman: bump to 40947be3

packages/linux-drivers/RTL8192CU/package.mk, packages/linux-drivers/RTL8192DU/package.mk, packages/linux-drivers/RTL8192EU/package.mk, packages/linux-drivers/RTL8812AU/patches/RTL8812AU-0001-fix_kernel_5_10.patch
Only needed for generic, arm architecture not are affected (yet).
Generic build tested with linux kernel 5.10-rc4
PKG_VERSION="418baf2c28f3473039f2f7377760bd8f6897ae18"  # 5.10-rc4
I'll keep this as draft while patches are accepted on upstream.
=> Update RTL wifi drivers to 5.10

projects/Allwinner/devices/R40/patches/linux/0018-r40-enable-deinterlace.patch
This PR enables deinterlace driver for R40.
=> Allwinner: R40: Enable deinterlace driver

packages/sysutils/systemd/system.d/modprobe@.service.d/dependencies.conf
kernel-overlays.service needs to be ordered before the modprobe@
instances, which were introduced in systemd 245, otherwise
modprobe@drm.service can run before /lib/firmware exists and
edid-override will fail.
Fix that by adding modprobe@.service template drop-in to order it
after kernel-overlays.service
=> systemd: fix kernel-overlays.service ordering

projects/Allwinner/devices/H5/patches/linux/18-enable-deinterlace.patch, projects/Allwinner/patches/linux/0002-media-cedrus-Fix-H264-decoding.patch
This PR fixes H264 decoding introduced in https://github.com/LibreELEC/LibreELEC.tv/pull/4606 and adds a patch which enables deinterlace core on H5.
=> Allwinner: Fix and improvement

packages/graphics/mesa/package.mk
The mesa 20.3.0 release has a bug that prevents older radeon cards from working. This is resolved in 20.3.1; fix confirmed by user testing in the forums https://forum.libreelec.tv/thread/23189-kodi-not-starting-nightly-20201221-84dd16d-x86-64/?postID=148093#post148093. The changeset from 20.3.0 is tiny so shouldn't impact other mesa using projects.
=> mesa: bump to 20.3.1 for radeonsi fix

packages/wayland/libxkbcommon/package.mk
Currently, the build fails while building on a machine with 32 threads. (Ryzen 9 5950X)
Adding this dependency fixes the problem.
=> libxkbcommon: fix missing dependency libxml2

packages/x11/lib/libX11/package.mk
LibX11 1.7.0 has been tested for the last 2 weeks with Generic:
- previous PR was - https://github.com/LibreELEC/LibreELEC.tv/pull/4709
- new api = https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/README.md
- XSetIOErrorExitHandler which provides a mechanism for applications
to recover from I/O error conditions instead of being forced to
exit.
```
22:38:25 up  4:12,  load average: 1.14, 1.41, 1.80
Generic.x86_64-devel-20201219065725-c2b7869
Linux LibreELEC 5.10.1 #1 SMP Wed Dec 16 13:02:48 UTC 2020 x86_64 GNU/Linux
Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
Kodi compiled 2020-12-15 by GCC 10.2.0 for Linux x86 64-bit version 5.10.0 (330240)
Running on LibreELEC (community): …
```
=> libX11: update to 1.7.0

packages/security/libgcrypt/package.mk
Very minor changes - https://dev.gnupg.org/T5113
=> libgcrypt: updated to 1.8.7

packages/x11/app/xkbcomp/package.mk, packages/x11/driver/xf86-input-libinput/package.mk, packages/x11/driver/xf86-video-intel/package.mk, packages/x11/lib/pixman/package.mk, packages/x11/other/fluxbox/package.mk
- fontconfig is a jump to devel. But have been running 2.13.92 for the last month.
- the next version 2.13.93 will be using meson build. (PRs in the devel releases 21.13.91,2.13.92 are mostly fixes) https://www.freedesktop.org/wiki/Software/fontconfig/Devel/
- fluxbox is only a change from .gz to .xz
all others are next increment packages
=> Update packages/x11 to latest 

packages/audio/pulseaudio/package.mk, packages/audio/pulseaudio/patches/pulseaudio-100.02-check_uid.patch
This has been tested in production for the last few weeks as 13.99.3
The release version is now out: v14.0
Release Notes are at: https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/
Some changes to take note of:
- Compile-time option to forget pre-14.0 stream routing(I have no enabled this)
- Automatic switching to HDMI is now disabled by default (been better on my system I think)
- qpaeq switched from Python 2 to Python 3
- reverted to pre 13.0 behavior  - pa_mainloop_prepare interprets the timeout argument as microseconds again
The git compare between 13.99.3 and 14.0 is minimal.
https://github.com/pulseaudio/pulseaudio/compare/v13.99.3...v14.0
Code changes between 13.99.3 and 14.0 are mostly cosmetic, +api version, + the microsecond change.
=> pulseaudio: update to 14.0

packages/devel/ncurses/package.mk
"dumb" terminfo added with #4186 was remove by accident in #4799. Include it again.
=> ncurses: include dumb terminfo again

packages/graphics/glmark2/package.mk, packages/graphics/lcms2/package.mk, packages/graphics/libde265/package.mk, packages/graphics/libdrm/package.mk, packages/graphics/libepoxy/package.mk, packages/graphics/libheif/package.mk, packages/graphics/libjpeg-turbo/package.mk, packages/graphics/libprojectM/package.mk, packages/graphics/libraw/package.mk, packages/graphics/tiff/package.mk
Graphics packages updated. Mostly minor.
Notable changes:
- libheif had a few version jumps.
- libde265 now using release number not a sha256
- glmark2 now compiled with meson
Notes/Todos: (these packages have not been updated in this PR)
- looks like **vsxu** has not been updated for a while? It has some updated releases, the GitHub is archived. Do we want to update this? 
- kmscube - skipping only a single commit
- cairo - are we bumping to 1.17.4? Also note maintainer update - https://gitlab.freedesktop.org/cairo/cairo/-/blob/156cd3eaaebfd8635517c2baf61fcf3627ff7ec2/NEWS
- glfw - working through the Xcursor dependancy with glfw-3.3.2
```
01:00:25 up 1 day,  2:31,  load average: 1.27, 1.22, 1.25
Generic.x86_64-devel-20201222112050-a9a38e4
Linux LibreELEC 5.10.2 #1 SMP …
```
=> update packages/graphics 

packages/mediacenter/LibreELEC-settings/package.mk
After recent changes `addon.xml` references `default.py` and `services.py` but we `python_compile` all files which changes them to *.pyc and breaks the add-on. Avoid this by only pre-compiling the /resources subfolder.
@thoradia do we also need to pre-compile `syspath.py` ?? (or could that live under /resources as well).
=> LibreELEC-settings: only python_compile /resources/lib/*

packages/multimedia/gmmlib/package.mk, packages/multimedia/intel-vaapi-driver/patches/0001-intel-vaapi-driver-2.4.1-Handle-odd-resolution.patch, packages/multimedia/media-driver/package.mk
**This brings all Intel video components up to current.**
Release notes:
- https://github.com/intel/media-driver/releases/tag/intel-media-20.4.5
Dependencies
- GmmLib: intel-gmmlib-20.4.1
- Libva: 2.10.0 (already in master)
Also including small upstream patch for intel-vaapi-driver https://github.com/intel/intel-vaapi-driver/commit/d87db2111a33b157d1913415f15d201cc5182850 since 2.4.1 was released. See compare @ https://github.com/intel/intel-vaapi-driver/compare/2.4.1...master
=> Intel Media Driver 2020Q4 Release - 20.4.5

packages/graphics/mesa/package.mk
Mesa 20.3.2 is a bug fix release which fixes bugs found since the 20.3.1 release. 
Release notes:
- https://docs.mesa3d.org/relnotes/20.3.2.html
More radeonsi fixes.
=> mesa: update to 20.3.2

projects/Allwinner/patches/atf/0001-sunxi-Don-t-enable-referenced-regulators.patch
Some boards, like OrangePi 3, needs special power on sequence for some regulators. Leave that to kernel.
Note: This is workaround. Possible solution was already discussed and fix will likely be included in one of the next ATF versions.
=> Allwinner: atf: Don't enable all regulators

packages/network/libssh/package.mk
- cleanup libssh and using full paths instead of relative paths
- copy libssh_version.h that is required by vfs.sftp
=> libssh: fix vfs.sftp and cleanup

packages/addons/service/minidlna/patches/minidlna-03-allow-gettext-0.20.patch
fixes
`*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.20`
* upstream https://sourceforge.net/p/minidlna/patches/186/
* works also with latest minidlna
=> minidlna: fix build for gettext 0.20 or newer

projects/Allwinner/devices/H6/patches/linux/22-opi3-crust-eth-workaround.patch, scripts/uboot_helper
This PR fixes ethernet when resumed from sleep on OrangePi3 and it introduces crust support for additional boards.
=> Allwinner: Crust fix and additional board configurations

packages/linux/package.mk, packages/tools/crust/package.mk, packages/tools/u-boot/package.mk, projects/Allwinner/bootloader/firmware, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H3/options, projects/Allwinner/devices/H5/options, projects/Allwinner/devices/H6/options, scripts/uboot_helper
This PR restores the `bootloader/firmware` script that was removed in #4762 and ensure `crust` is rebuilt for each unique release image. The `bootloader/firmware` script is needed to complete #4591.
Source of `bootloader/firmware` is also moved until after `make mrproper` to avoid issue with u-boot clean removing i.e. `bl31.elf` on rockchip platform.
It also decouple `crust` from the `u-boot` package and is no longer executing `scripts/uboot_helper` when `u-boot` `package.mk` is sourced.
~~The `linux` package is still executing `scripts/uboot_helper` when `linux` `package.mk` is sourced and is probably something that should be looked at in a separate PR.~~
`linux` package was changed to use `crust` patch dir when `UBOOT_FIRMWARE` contains `crust`.
Note: I have not tried a full Allwinner …
=> u-boot: restore bootloader/firmware script

projects/Allwinner/bootloader/firmware
This script is sourced in u-boot's package.mk, 'exit 0' just makes
building a no-op.
Suppress errors from uboot_helper instead.
=> u-boot: fix build for sunxi

packages/addons/addon-depends/game-tools/ecm-tools/package.mk
Only commit to the source repository was https://github.com/alucryd/ecm-tools/commit/2765930b79fff478a6a584a554c719b8bf041422 which updated the version number to semantic. 
This PR updates the PKG_VER to 1.0.3 from 55365b02f237f079334f207133dd85b45270ecd9
=> ecm-tools: update to 1.0.3 from githash

packages/devel/configtools/package.mk
Update configtools from 2020-01-01 to 2020-12-22
(2 commits - first updating the from version in the file before the update)
no changes that refer to LibreELEC hardware projects
=> configtools: update to 2020-12-22

packages/devel/ccache/package.mk
- Update to latest 3.x series.
- have also been testing 4.x (it works fine) but there is a recursive dependency on the initial build, this will need to be addressed before it can be incorporated.
=> ccache: update to 3.7.12

packages/devel/swig/package.mk
Version: 4.0.2 (8 Jun 2020) 
Version 4.0.1 (21 Aug 2019)
Mostly fixes
http://www.swig.org/Release/CHANGES.current
=> swig: update to 4.0.2

packages/sysutils/kmod/package.mk
24-Feb-2017 - 24
19-Feb-2020 - 27
mainstream distros using #27.
https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/tree/NEWS
https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/log/
=> kmod: update to 27

licenses/ISC.txt, packages/addons/addon-depends/inadyn/libconfuse/package.mk, packages/addons/addon-depends/inadyn/libconfuse/patches/gettext-0.20-libconfuse.patch, packages/addons/service/inadyn/changelog.txt, packages/addons/service/inadyn/package.mk
Update to current inadyn
- 18 month bump, but limited changes
- https://github.com/troglobit/inadyn/blob/master/ChangeLog.md
update libconfuse (dependency of inadyn)
- 2 year bump - minimal changes
- Includes get text 0.20 patch
- https://github.com/libconfuse/libconfuse/blob/master/ChangeLog.md
=> inadyn: addon update to 2.7 and gettext fix 

packages/linux/patches/default/linux-001-fix-ir-timeout.patch, packages/linux/patches/raspberrypi/linux-001-fix-ir-timeout.patch
This fixes the "double button press" issue with nuvoton-cir
as reported on the forum.
See https://forum.libreelec.tv/thread/23211-intel-nightly-build-problem-with-mce-remote/
upstream patch status: https://patchwork.linuxtv.org/project/linux-media/patch/20210105093023.5212-1-hias@horus.com/
=> linux: add patch to fix IR timeout handling

packages/addons/service/tigervnc/changelog.txt, packages/addons/service/tigervnc/package.mk
https://github.com/TigerVNC/tigervnc/releases/tag/v1.10.1
https://github.com/TigerVNC/tigervnc/releases/tag/v1.11.0
Note: it is not possible to update to 1.11.0 without reverting mandatory PAM patches.
Make PAM mandatory -
https://github.com/TigerVNC/tigervnc/commit/d80817f101d1b3f1a9b1c5ec268f28fffa2d75f9#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
Start sessions via PAM -
https://github.com/TigerVNC/tigervnc/commit/1af1cfdf8709dd1a5574efa19fb4f0e68a98021e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
=> tigervnc: addon update to 1.10.1 (105)

packages/devel/gmp/package.mk, packages/devel/mpc/package.mk, packages/devel/mpfr/package.mk
mpc from 1.1.0 to 1.2.1
- http://www.multiprecision.org/mpc/
- http://www.multiprecision.org/mpc/olds.html
mpfr from 4.0.2 to 4.1.0
- https://www.mpfr.org/mpfr-current/#changes
gmp from 6.2.0 to 6.2.1
- https://gmplib.org/gmp6.2
- bug fixes
=> arithmetic Libraries: update to current

packages/devel/pcre/package.mk
Regular PCRE 12 month bump. 8.43 to 8.44
http://www.pcre.org/original/changelog.txt
=> pcre: update to 8.44

packages/devel/libfmt/package.mk
Update of libfmt from 7.0.3 to 7.1.3
7.0.3 @vitaut vitaut released this on 7 Aug 2020
7.1.3 @vitaut vitaut released this on 26 Nov 2020
https://github.com/fmtlib/fmt/releases
a big update in https://github.com/fmtlib/fmt/releases/tag/7.1.0 remaining 7.1.x are just fixes
=> libfmt: update to 7.1.3

packages/addons/addon-depends/faad2/package.mk
Update from 2.8.8 to 2.10.0
mostly fixes (security): https://github.com/knik0/faad2/blob/master/ChangeLog
2.8.8 - 18 Dec 2017
2.10.0 -: 20 Oct 2020
https://github.com/knik0/faad2/releases
=> faad2: update to 2.10.0 and PKG_SITE and PKG_URL

packages/addons/service/syncthing/changelog.txt, packages/addons/service/syncthing/package.mk
Update from 1.5.0 to 1.12.0
1.12.0 released in Dec2020, 1.5.0 was May 2020
https://github.com/syncthing/syncthing/releases
=> syncthing: update to 1.12.0

packages/tools/hdparm/package.mk, packages/tools/mtools/package.mk
Mtools upgrade from Mar 22, 2020 to Nov 28, 2020
1 v4_0_26
2 	- Fix compilation on Macintosh
3 	- Ignore image file locking errors if we are performing a
4           read-only access anyways
5 	- Minor man-page fixes
6 v4_0_25
7 	- Preserve non-updated contents of info sector, just in case
8           it contains program code
9 	- When parsing config file, always use "C" locale for
10           case-insensitive comparisons
11 v4_0_24
12 	- Spelling fixes in documentation
13 	- Permit calling "make install" with >= -j2
14 	- Added AC_SYS_LARGEFILE, needed for compiling on certain ARM procs
minor fixes.
hdparm 
- 9.58 is 2018-10-26
- 9.60 is 2020-11-21
minor fixes - https://fossies.org/linux/hdparm/Changelog
=> Update tools - mtools and hdparm

packages/addons/addon-depends/chrome-depends/harfbuzz-icu/package.mk, packages/addons/addon-depends/chrome-depends/harfbuzz/package.mk, packages/addons/addon-depends/icu/package.mk, packages/addons/browser/chrome/package.mk, packages/graphics/harfbuzz/package.mk, packages/multimedia/SDL2/package.mk, packages/multimedia/aom/package.mk, packages/multimedia/libass/package.mk, packages/multimedia/libhdhomerun/package.mk, packages/multimedia/libudfread/package.mk, packages/multimedia/rtmpdump/package.mk
Limited testing on Generic so far.
- libass 0.15 now has a mandatory dependancy on harfbuzz
- harfbuzz 2.7.2 if using -Dicu=enable is fixed
all other package updates were quite minor
=> update packages/multimedia and their dependancies

packages/addons/tools/dotnet-runtime/changelog.txt, packages/addons/tools/dotnet-runtime/package.mk
Simple bump of package 3.1.9 (October 13, 2020 ) to 3.1.10 (November 10, 2020)
- https://versionsof.net/core/3.1/3.1.10/
- https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.10/3.1.10.md
https://github.com/dotnet/core/tree/master/release-notes
Note: - https://devblogs.microsoft.com/dotnet/announcing-net-5-0/
`.NET 5.0 is a current release. That means that it will be supported for three months after .NET 6.0 is released. As a result, we expect to support .NET 5.0 through the middle of February 2022. .NET 6.0 will be an LTS release and will be supported for three years, just like .NET Core 3.1.`
=> dotnet-runtime: update to ASP.NET Core Runtime 3.1.10

packages/security/nss/package.mk
With `NSS_BUILD_UTIL_ONLY=1` introduced by #4775 libnss3.so (and other libs) are not build any more.
Bug report: https://forum.libreelec.tv/thread/23273-missing-libnss3-so-in-nightly-20210106-1d5a0dc/
Removal for host may not be needed, but better be on the safe side.
=> nss: fix building libnss3 again

packages/x11/lib/pixman/package.mk
Additional meson build method was introduced with pixman 0.38. This is auto-detected by our build system but only configure is configured in the package.
Select `configure` again.
This is not against meson but changing the build method should be a development decision and not orruc by accident.
=> pixman: package configuration is for configure, use it

packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk
- libmediainfo: update to 20.09 from 18.05
https://mediaarea.net/MediaInfo/ChangeLog
- libzen: update to 0.4.38 from 0.4.37
https://github.com/MediaArea/ZenLib/blob/master/History.txt
- mediainfo: update to 20.09 from 18.05
https://mediaarea.net/MediaInfo/ChangeLog
- mpv-drmprime: update to 0.33.0 from 0.30.0
https://github.com/mpv-player/mpv/releases
- mpg123: update to 1.26.4 from 1.25.10
http://www.mpg123.org/cgi-bin/news.cgi
=>  multimedia-tools: update addon (113)

packages/graphics/cairo/package.mk, packages/graphics/kmscube/package.mk, packages/graphics/libepoxy/package.mk
libepoxy: update to 1.5.5
- https://github.com/anholt/libepoxy/releases/tag/1.5.5
- No change URI only and SHA256
kmscube: update to HEAD
- drm: grab correct handle for plane != 0
- Multiplanar formats can have different BOs for each plane, so call the
- correct GBM function to get the handle for a specific plane
cairo: update to 1.17.4
- bumping to 1.17.4.
- Also note maintainer update - https://gitlab.freedesktop.org/cairo/cairo/-/blob/156cd3eaaebfd8635517c2baf61fcf3627ff7ec2/NEWS
=> Update packages/graphics current

packages/addons/addon-depends/whois/package.mk
used simply for its toolchain.
proftpd/package.mk:    cp $(get_install_dir whois)/usr/bin/mkpasswd $ADDON_BUILD/$PKG_ADDON_ID/bin
=> whois: update to 5.5.7

packages/databases/sqlite/package.mk
This is a documentation only change. No versions or file name changes, just correcting the format of the PKG_vERSION field
=> sqlite: cleanup package.mk

packages/addons/addon-depends/ttyd-depends/json-c/package.mk, packages/sysutils/ir-bpf-decoders/package.mk
2 @CvH commits
- json-c is the same version. It is a document change only.
https://github.com/json-c/json-c/releases/tag/json-c-0.15-20200726
- ir-bpf-decoders is just variable updates
=> json-c and ir-bpf-decoders: version cleanup

packages/mediacenter/kodi/system.d/kodi-waitonnetwork.service
Fixup for #4802
Change to wait-time-sync was lost eventually on squash or rebase.
=> kodi-waitonnetwork.service: use wait-time-sync

packages/compress/libarchive/package.mk
Minor bump from 3.5.0 to 3.5.1
https://github.com/libarchive/libarchive/releases/tag/3.5.1
bugfixes
=> libarchive: update to 3.5.1

packages/audio/libopenmpt/package.mk, packages/audio/openal-soft/package.mk, packages/audio/sbc/package.mk
- sbc: update to 1.5 from 1.4
- - released 07-Dec-2020, 1.4 was Sep 2018
- openal-soft: update to 1.21.0 from 1.20.1
- - https://github.com/kcat/openal-soft/blob/master/ChangeLog
- libopenmpt: update to 0.4.16 from 0.4.11
- - further update to 0.5.4 will be submitted as a PR at a later date.
- - https://lib.openmpt.org/doc/changelog.html
- - https://lib.openmpt.org/libopenmpt/2020/11/29/releases-0.5.4-0.4.16-0.3.25/
=> Audio package updates

packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
Update to a modernish btrfs-progs 
https://btrfs.wiki.kernel.org/index.php/Changelog#By_feature
btrfs-progs v4.15.1 (Feb 2018)
btrfs-progs v4.8.4 (Nov 2016)
Further updates to either v4.20 or v5.7 need more work.
=> btrfs-progs: update to 4.15.1

packages/network/iwd/package.mk
upgrade from 1.9 (2020-09-04) to 1.11 (2021-01-07)
Commit logs:
https://git.kernel.org/pub/scm/network/wireless/iwd.git/log/
ver 1.11:
Add support for ACD client for static configuration.
Add support for intelligent scan of all frequencies.
ver 1.10:
Add support for DHCP v6 configuration.
Add support for DHCP server operation with AP mode.
Add support for IP allocation during the 4-Way Handshake.
Add support for P2P Group-owner handling.
=> iwd: update to 1.11

packages/debug/libva-utils/package.mk
https://github.com/intel/libva-utils/releases
- add Mediacopy Sample code
- Enable new caps for rate control TCBRC
- Add --repeat command line option to vp8enc.
- fix one null pointer dereference risk
=> libva-utils: update to 2.10.0

packages/audio/sbc/patches/sbc_primitives-Fix-build-on-non-x86.patch
Ref:
sbc_primitives: Fix build on non-x86
https://www.spinics.net/lists/linux-bluetooth/msg89603.html
=> sbc: fix linker issue if not x86_64

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, packages/tools/rpi-eeprom/package.mk
SD card filesystem corruption on RPi0-3 is fixed, tested on RPi2B and RPi3B+
RPi4 HD audio improvements are also included, tested with DTS HD MA and Dolby Atmos samples
=> linux (RPi): update to 5.10.5-a896a00

packages/sysutils/busybox/package.mk
update 1.32.0 (26 June 2020) to 1.32.1-stable (1 January 2021)
changelog: https://www.busybox.net
whilst busybox 1.33.0 has been released it is in the unstable track. 1.32.1 is the released stable. The only change from 1.32.0 is as a bug fix release 1.32.0:
- Bug fix release. 1.32.1 fixes a case where in ash, "wait" never finishes.
- https://git.busybox.net/busybox/log/?h=1_32_stable
=> busybox: update to 1.32.1

packages/linux/patches/default/linux-002-fix-ite-cir-timeout.patch
min_timeout was calculated wrong, leading to long key repeats
This fixes the issue on NUC reported here: https://forum.libreelec.tv/thread/23211-intel-nightly-build-problem-with-mce-remote/?postID=148823#post148823
Upstream patchwork link: https://patchwork.linuxtv.org/project/linux-media/patch/20210109201055.12051-1-hias@horus.com/
=> linux (default): add patch to fix ite-cir issues

packages/python/graphics/Pillow/package.mk
Update from 8.0.1 (2020-10-22) to 8.1.0 (2020-01-02)
Release notes at:
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst
=> Pillow: update to 8.1.0

packages/security/libgpg-error/package.mk
Upgrade from 1.39 to 1.41
https://files.gnupg.net/file/data/hhjxih2bil66zncwdjf4/PHID-FILE-jo3zbsuftkwqa2omsp22/NEWS
Noteworthy changes in version 1.41 (2020-12-21) [C31/A31/R1]
-----------------------------------------------
Release-info: https://dev.gnupg.org/T5192
* Fixes another glitch in the "ignore" meta command.
* Fixes two typos in the German translation.
Noteworthy changes in version 1.40 (2020-12-21) [C31/A31/R0]
-----------------------------------------------
Release-info: https://dev.gnupg.org/T5191
* New function gpgrt_access.
* Make "ignore" meta command work correctly in the option parser.
* On Windows gpgrt_getcwd and the internal getusername now handle
Unicode values.  [#5098]
* Update the build system.
* Interface changes relative to the 1.39 release: …
=> libgpg-error: update to 1.41

packages/security/nettle/package.mk
update 3.6 (2020-04-29) to 3.7 (2021-01-04)
changelog: https://git.lysator.liu.se/nettle/nettle/-/blob/master/ChangeLog
=> nettle: update to 3.7

packages/devel/arm-mem/package.mk
update from 0100445 (15 Mar 2019) to b48ea15 (30 Apr 2019)
changelog: https://github.com/bavison/arm-mem/commits/master
Included in this release are: 
- ARMv7: Ensure memcmp return value is always -1, 0 or +1
While other values are permitted by ISO, there are some fears that since
these are the values returned by glibc, we may expose latent bugs by
doing anything different.
this is the same version as is being used in https://github.com/RPi-Distro/arm-mem/tree/debian
=> arm-mem: update to 2019-04-30

packages/devel/fakeroot/package.mk, packages/devel/fakeroot/patches/fakeroot-001-disable-docs-tests.patch
update 1.24 (2019-09-07) to 1.25.3 (2020-10-08)
changelog: https://salsa.debian.org/clint/fakeroot/-/blob/master/debian/changelog
update PKG_SITE and do not build docs/tests
=> fakeroot: update to 1.25.3

packages/x11/font/liberation-fonts-ttf/package.mk
update 2.00.1 (Oct 04 2012) to 2.1.2 (Dec 21 2020)
changelog: https://raw.githubusercontent.com/liberationfonts/liberation-fonts/master/ChangeLog
updated the PKG_SITE
All 12 .ttf are still contained in tar file
=> liberation-fonts-ttf: update to 2.1.2

packages/sysutils/kmod/package.mk
update 27 (2020-02-18) to 28 (2021-01-07)
changelog: https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/log/
cleaned up configure flags
fix PKG_SITE
=> kmod: update to 28

packages/addons/addon-depends/enet/package.mk
update e33ca1d (1.3.13+vita) (2 Oct 2016) to 1.3.17+vita (10 Jan 2021)
changelog: https://raw.githubusercontent.com/cgutman/enet/moonlight/ChangeLog
**this is only used by libretro.dolphin**
=> enet: update to 1.3.17+vita

packages/network/libdnet/package.mk
update sgeto/libdnet 8029bf9 (Jun 20, 2017) to ofalk/libdnet 1.14 (4 Sep 2020)
changelog: https://github.com/ofalk/libdnet/commits/master
**this is only used by open-vm-tools**
=> libdnet: update to 1.14

packages/addons/service/docker/changelog.txt, packages/addons/service/docker/package.mk, packages/addons/service/docker/source/default.py, packages/addons/service/docker/source/lib/dockermon.py
Summary:
- Do not import oe
- Retry connection on error
- Add periodically kodi termination check via timeout
- Remove unneeded thread
With recent LibreELEC-Settings bump python module oe was moved resulting in
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named 'oe'
File "/storage/.kodi/addons/service.system.docker/default.py", line 15, in <module>
import oe
ModuleNotFoundError: No module named 'oe'
-->End of Python script error report<--
```
The only used function oe.execute() is replaced by subprocess.run() and the module import is removed.
Connection to the …
=> docker: fix python addon (rev 132)

packages/addons/addon-depends/chrome-depends/itstool/package.mk, packages/addons/addon-depends/chrome-depends/shared-mime-info/package.mk
https://github.com/freedesktop/xdg-shared-mime-info/blob/master/NEWS
previous version
- shared-mime-info 1.9 (2017-09-18)
new version 
- shared-mime-info 1.15 (2019-10-30)
**Building 2.1 not yet successful (and brand new)**
https://github.com/freedesktop/xdg-shared-mime-info/releases
Only used for :host
=> shared-mime-info: update to 1.15 and itstool:host dependency 

packages/python/security/pycryptodome/package.mk
Update from 3.9.8 to 3.9.9
Minor fix: https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst
=> pycryptodome: update to 3.9.9

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Accidentally paired the wrong SKY remote to my system and observed strange behavior. 
The keymap (from PR https://github.com/LibreELEC/LibreELEC.tv/pull/4546) wasn't picked up so I investigated. It looks like the remote name changes randomly if you pair it.
Thats the names I got from two of my remotes. Fixed it with an wildcard. Should support other Sky remotes too.
```
P235ruwido Sky Remote
U069ruwido Sky Remote
U189ruwido Sky Remote
U235ruwido Sky Remote
U251ruwido Sky Remote
```
=> evenlircd: fix SKY-Q remote

projects/Amlogic/options
Cleanup reference from https://github.com/LibreELEC/LibreELEC.tv/pull/4626
**fixes**
```
File "scripts/genbuildplan.py", line 367, in <module>
REQUIRED_PKGS = processPackages(args, ALL_PACKAGES)
File "scripts/genbuildplan.py", line 296, in processPackages
raise Exception(msg)
Exception: Invalid package reference: dependency qca-firmware in package linux-firmware::PKG_DEPENDS_TARGET is not valid
Parallel build failure - see log for details. Time of failure: Tue Jan 12 13:23:47 UTC 2021
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
```
=> qca-firmware: remove reference from Amlogic firmware

packages/addons/addon-depends/pngquant/package.mk
update 2.12.0 (2018-06-04) to 2.13.1 (2020-11-23)
the library has had a big bump, 
number of releases between 2.12.0 and 2.13.1 - being 2.12.1,2,3,4,5,6 and 2.13.0
changelogs:
- https://raw.githubusercontent.com/kornelski/pngquant/master/CHANGELOG
- https://github.com/kornelski/pngquant/compare/2.12.0...2.13.1
- https://github.com/ImageOptim/libimagequant/compare/feae85c61f58c1453f5c73ba3a32458b81750f42...5ea4f8a3c3186fa83e1e7c08c9238e071eedb95f
Used by tvheadend42 as pngquant:host
=> pngquant: update to 2.13.1

packages/addons/addon-depends/rpi-tools-depends/gpiozero/package.mk, packages/addons/tools/rpi-tools/changelog.txt, packages/addons/tools/rpi-tools/package.mk
gpiozero: update to 1.5.1
- update 1.5.0 (13 Feb 2019) to 1.5.1 (25 Jun 2019)
- **changelog**:
- https://raw.githubusercontent.com/gpiozero/gpiozero/master/debian/changelog
=> rpi-tools: update addon (109)

packages/tools/u-boot-tools/package.mk, packages/tools/u-boot/package.mk
This PR updates U-Boot and u-boot-tools to 2021.01 and it also removes unneeded dependency in tools.
=> U-Boot: update to 2021.01

packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk, packages/addons/addon-depends/vdr/package.mk, packages/addons/service/vdr-addon/changelog.txt, packages/addons/service/vdr-addon/package.mk
vdr: updated to 2.4.6
vdr-plugin-vnsiserver: changed source to github.com/mdre77/vdr-plugin-vnsiserver and updated  to 908684b
Runtime tested.
=> vdr-addon updates

packages/graphics/glmark2/package.mk
The recent bump fails on ARM/GBM, see https://github.com/glmark2/glmark2/issues/138 so this reverts to the immediate commit before the change to meson build-system (the breaking change) which still uses waf and compiles fine.
=> glmark2: revert to commit before meson change

packages/graphics/glmark2/package.mk
The meson build issue was resolved upstream a little faster than expected. So here's the original bump that switches the package to meson, plus fix.
=> glmark2: bump to latest meson commit

packages/addons/addon-depends/network-tools-depends/bwm-ng/package.mk, packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk, packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk, packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk
bwm-ng: update to 0.6.3
tcpdump: update to 4.99.0
libpcap: use configure, not cmake. review cmake in future release
=> network-tools: update addon to 108

packages/addons/service/lcdd/package.mk
Fixes build issue.
```
[63/64] [DONE] build   serdisplib:target
<<< lcdd:target seq 64 <<<
cp: cannot stat '/home/christian/Documents/Git/LE-CvH/build.LibreELEC-Generic.x86_64-9.80-devel/install_pkg/serdisplib-2.02/usr/lib/libserdisp.so.1': No such file or directory
FAILURE: scripts/install_addon lcdd:target during addon (package.mk)
cp -L $(get_install_dir serdisplib)/usr/lib/libserdisp.so.1 $ADDON_BUILD/$PKG_ADDON_ID/lib/
christian@ubuntu:~/Documents/Git/LE-CvH$ ls build.LibreELEC-Generic.x86_64-9.80-devel/install_pkg/serdisplib-2.02/usr/lib/
libserdisp.so  libserdisp.so.2  libserdisp.so.2.02
```
=> lcdd: fix addon build reference to serdisplib 2.02

packages/addons/service/ttyd/package.mk
Fix build issues
```
[48/49] [DONE] build   libwebsockets:target
<<< ttyd:target seq 49 <<<
cp: cannot stat '/home/christian/Documents/Git/LE-CvH/build.LibreELEC-Generic.x86_64-9.80-devel/install_pkg/libwebsockets-4.1.6/usr/lib/libwebsockets.so.16': No such file or directory
FAILURE: scripts/install_addon ttyd:target during addon (package.mk)
cp -p $(get_install_dir libwebsockets)/usr/lib/libwebsockets.so.16 $ADDON_BUILD/$PKG_ADDON_ID/lib
christian@ubuntu:~/Documents/Git/LE-CvH$ ls build.LibreELEC-Generic.x86_64-9.80-devel/install_pkg/libwebsockets-4.1.6/usr/lib/
cmake  libwebsockets.a  libwebsockets-evlib_uv.so  libwebsockets.so  libwebsockets.so.17  pkgconfig
```
=> ttyd: fix addon build reference to libwebsockets 4.1.6

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
update 2.38.0 to 2.39.1
changelog:
- https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/master/NEWS
note: NEWS:2.37.92 refers to 2.38.0 release
=> at-spi2-core: update to 2.39.1

packages/graphics/mesa/package.mk
update 20.3.2 to 20.3.3
changelog: https://docs.mesa3d.org/relnotes/20.3.3.html
```
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 20.3.3, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Iris(R) Graphics 540 (SKL GT3)
GL_VERSION = 4.6 (Core Profile) Mesa 20.3.3
Generic.x86_64-devel-20210114133055-c401a9f
Linux LibreELEC 5.10.7 #1 SMP Thu Jan 14 09:58:23 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
Kodi compiled 2021-01-12 by GCC 10.2.0 for Linux x86 64-bit version 5.10.5 (330245)
Running on LibreELEC (community): devel-20210114133055-c401a9f 9.80, kernel: Linux x86 64-bit version 5.10.7
FFmpeg version/source: 4.3.1-Kodi
Host CPU: Intel(R) Core(TM) i5-6260U CPU @ …
```
=> mesa: update to 20.3.3

packages/addons/addon-depends/system-tools-depends/i2c-tools/package.mk, packages/addons/addon-depends/system-tools-depends/i2c-tools/patches/pyinstalldir.patch
Both prefix and PREFIX are used in i2c-tools since version 4.1. Added PREFIX to makeinstall_target.
```
py-smbus/Module.mk:       $(DISTUTILS) install --prefix=$(DESTDIR)$(prefix)
Makefile:PREFIX   ?= /usr/local
```
test built both 
```
PROJECT=Generic ARCH=x86_64 scripts/create_addon system-tools
PROJECT=Allwinner ARCH=arm DEVICE=H6 UBOOT_SYSTEM=tanix-tx6 s/create_addon  system-tools
```
=> i2c-tools: fix dest PREFIX to /usr

packages/tools/grub/package.mk
update 2df2912 (2020-09-18) to 635ef55 (2020-12-18)
changelog: http://git.savannah.gnu.org/cgit/grub.git/log/
=> grub: update to 2020-12-18

packages/addons/script/driverselect/package.mk
change from fork:
- CvH/script.program.driverselect/tree/Matrix
to uostream
- b-jesch/script.program.driverselect/tree/Matrix
patch included and version bumped in upstream
Only additional commit is: https://github.com/CvH/script.program.driverselect/commit/69429715b16af3573008898a23a0930b457a55f7
=> driverselect: update to 2020-09-14 (3.0.1+matrix)

projects/Allwinner/patches/u-boot/0001-sunxi-call-fdt_fixup_ethernet-again-to-set-macaddr-f.patch
```
Sometimes some ethernet aliases do not exist in U-Boot FDT but they
exist in the FDT used to boot the system. In this situation
setup_environment is called again in ft_board_setup to generate macaddr
environment variable for them. However now the call to
fdt_fixup_ethernet is moved before the call of ft_board_setup.
```
from U-Boot ML
=> Allwinner: add u-boot patch for setting fixed MAC address

packages/security/gnutls/package.mk
Update from 3.6.15 (2020-09-04) to 3.7.0 (2020-12-02)
Release Notes:
https://lists.gnupg.org/pipermail/gnutls-help/2020-December/004670.html
=> gnutls: update to 3.7.0

packages/devel/slang/package.mk
This is a large update from slang 2.1.4 to 2.3.2.
A 10 year jump - https://www.jedsoft.org/releases/slang/
Newt still builds 😀
$ git grep slang
packages/devel/slang/package.mk:PKG_NAME="slang"
packages/devel/slang/package.mk:PKG_URL="ftp://space.mit.edu/pub/davis/slang/v2.1/$PKG_NAME-$PKG_VERSION.tar.gz"
packages/devel/slang/package.mk: # slang fails to build in subdirs
packages/devel/slang/package.mk: # slang fails to build in subdirs
packages/sysutils/util-linux/package.mk:                          --without-slang \
packages/tools/newt/package.mk:PKG_DEPENDS_TARGET="toolchain slang popt"
=> slang: update to 2.3.2

packages/security/nss/package.mk
update 3.60 (11-Dec-2020) to 3.60.1 (04-Jan-2021)
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.60.1_release_notes
=> nss: update to 3.60.1

packages/addons/service/tvheadend42/source/download.py
python: update xbmc.translatePath() to xbmcvfs - xbmc.translatePath is deprecated
=> Tvheadend 42: python: update xbmc.translatePath() to xbmcvfs

packages/sysutils/usbutils/package.mk
Cleanup of #4913.
Don't call do_autoreconf manually.
Tested on Generic.
=> usbutils: use autotools toolchain

tools/refresh-patches
This script uses quilt to refresh patches, e.g.:
./tools/refresh-patches linux
It tries to detect already applied patches and removes those.
The rest is refreshed, which means updating the hunk line offsets and
removing junk (so that the result is the same for everyone).
This makes it easy to update packages with large patch sets. It's
usable as-is without any additional git clone to rebase patches.
Note that there're alot of patches in-tree that contain multiple patches
per file. While quilt doesn't have a problem applying those, the
resulting file is a combined patch.
=> script to refresh patches

packages/sysutils/gptfdisk/package.mk, packages/sysutils/libevdev/package.mk, packages/sysutils/open-vm-tools/package.mk
- libevdev: update to 1.10.1
- open-vm-tools: update to 11.2.5
- gptfdisk: update to 1.0.6
=> packages/sysutils: small bumps of already bumped packages to latest.

packages/addons/addon-depends/snapcast-depends/snapcast/package.mk, packages/addons/addon-depends/snapcast-depends/snapcast/patches/snapcast-01_makefiles.patch, packages/addons/service/snapclient/changelog.txt, packages/addons/service/snapclient/package.mk, packages/addons/service/snapserver/changelog.txt, packages/addons/service/snapserver/package.mk
snapcast: update to 0.23.0 …
update 0.22.0 to 0.23.0
changelog: https://github.com/badaix/snapcast/blob/master/changelog.md
Features
- Client: Add PulseAudio player backend (Issue #722)
- Client: Configurable buffer time for alsa and pulse players
- Server: If docroot is not configured, a default page is served (Issue #711)
- Server: airplay source supports "password" parameter (Issue #754)
=> snapclient and snapserver: update to 0.23.0

packages/addons/addon-depends/ffmpegx-depends/x264/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk
x264: update to 2021-01-07
- update d4099dd (2019-03-06) to 6bc7fe4 (2020-01-07)
- change to PKG_URL
- changelog: https://code.videolan.org/videolan/x264/-/commits/master/
** used by ffmpegx
=> ffmpegx: update addon to 114 with x264 update to 2021-01-07

config/functions, scripts/build
Check if different toolchain is configured when building package.
Suggested by @CvH in https://github.com/LibreELEC/LibreELEC.tv/pull/4876#issuecomment-755607408
Clean Generic build without addons did succeed without detecting any further packages.
=> buildsystem: check wrong toolchain configuration

packages/addons/addon-depends/chrome-depends/shared-mime-info/package.mk, packages/addons/addon-depends/chrome-depends/shared-mime-info/patches/no-man-no-html.patch
update 1.9 to 1.15 and subsequently 2.1 - replacing https://github.com/LibreELEC/LibreELEC.tv/pull/4884
changelog: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/NEWS
=> shared-mime-info: update to 2.1

packages/emulation/libretro-vecx/package.mk
`PROJECT=Allwinner DEVICE=H3 ARCH=arm  scripts/create_addon game.libretro.vecx` command failed, ld unable to find GL, because Allwinner isn't config to support  OpenGL.
=> [game.libretro.vecx] fix build issue when opengl is disabled

packages/linux/package.mk, packages/tools/dt-overlays/package.mk, packages/tools/u-boot/package.mk, packages/tools/u-boot/patches/default/0001-pxe-add-support-for-FDT-overlays.patch, packages/tools/u-boot/patches/default/0002-sunxi-Add-fdtoverlay_addr_r-env-variable.patch, projects/Allwinner/bootloader/release, projects/Allwinner/bootloader/update.sh, projects/Allwinner/options, scripts/mkimage
This PR is initial work to support DT overlays also for other than RPi ARM SoCs. Several users already asked for that functionality directly or indirectly (how to modify dtb file?).
Note that this mostly just brings up infrastructure with one simple Allwinner H6 overlay. Please tell me if you concur with approach taken here and what would you change.
Before this is merged I would expect that dt-overlay repo is moved to LE github and maintained there.
=> Allwinner: Support for DT overlays

projects/NXP/devices/iMX6/bootloader/canupdate.sh, projects/NXP/devices/iMX6/bootloader/mkimage, projects/NXP/devices/iMX6/bootloader/update.sh, projects/NXP/devices/iMX6/filesystem/usr/share/bootloader/canupdate.sh, scripts/uboot_helper
This combines https://github.com/by-gnome/LibreELEC.tv/commit/de7b1d38ec57a71854afe4eb948e5ea32848578d and #4917 testing with FDTDIR to halve the number of iMX6 images from six to three. I've also added `canupdate.sh` to block upgrades from legacy images; total user numbers are small and support will be easier if we force a clean install. If testing subsequently proves upgrading LE 8.0/8.2 > LE 10.0 can be done reliably we can always merge another PR. Until then, it's been years since iMX6 had an active maintainer so let's keep it simple.
@by-gnome @etrax79 please test the images here https://chewitt.libreelec.tv/testing/9.80/ as I don't have iMX6 h/w
=> iMX6: repackage cubox/udoo/wandboard images to use FDTDIR

packages/audio/wavpack/package.mk
update 5.3.0 to 5.4.0
news: https://raw.githubusercontent.com/dbry/WavPack/master/NEWS
release notes: https://github.com/dbry/WavPack/releases/tag/5.4.0
=> wavpack: update to 5.4.0

tools/download-cleaner
This script is to help manage the content of one's SOURCES directory. It can prune the directory based on a single set of PROJECT, DEVICE, and ARCH, or it can build a new SOURCES directory using the current one as a collection to pull currently good tarballs from.
Note that it only considers one set of PROJECT/DEVICE/ARCH so if running against an RPi, then it will consider any generic kernel tarball to be bad, for example. If building for multiple projects, building a new SOURCE dir is the recommended method.
This script has been seen previously here: https://github.com/LibreELEC/LibreELEC.tv/pull/3020
=> tools/download-cleaner: add new tool

config/options, config/path
Two minors for the buildsystem. The first in `config/path` is an indent fix. The second in `config/options` converts embedded python to use f-strings. This is a very (very) small performance improvement, but it may be noticeable on slow machines given how often options is sourced.
Use of f-strings makes the assumption the host's python3 is >=3.6. Python 3.5 went EOL September 2020, so I believe that is fair.
=> buildsystem: minors

projects/Rockchip/options, scripts/checkdeps
The primary change is shifting dependency checking from using two arrays that are paired to each other by index position to using a single associative array to match them in [key]=value pairs. I've added a debug switch to the top of the script that when enabled will echo every array's mapping.
The second change is that I was moving the qemu-user-binfmt stuff out to the Rockchip project as it was added  for aarch64 native building to support the rkbin program. The EXTRA_* dependency arrays for project and distribution have been broken since checkdeps stopped sourcing config/options. Since it's been broken since November 2019 without complaint, I opted to remove this feature. About 95% of the necessary bits to have this work are in the first commit. (There are probably some bugs in that, as …
=> checkdeps: cleanup

packages/audio/pulseaudio/package.mk
- update 14.0 to 14.2
- release: https://lists.freedesktop.org/archives/pulseaudio-discuss/2021-January/031986.html
- release: https://lists.freedesktop.org/archives/pulseaudio-discuss/2021-January/031990.html
- news: https://raw.githubusercontent.com/pulseaudio/pulseaudio/stable-14.x/NEWS
**PulseAudio 14.1**
_A bug fix release._
* Support upto 8 mixer channels on ALSA devices
* Handle ALSA jacks with the same name but different index values
* Switch to plugged-in headset when mic availability is unknown
* Fix a potential segfault in the Bluetooth oFono HFP backend
* Fix a problem with module-ladspa-sink when avoid-resampling=true
* Fix database names containing canonical host for meson builds
**PulseAudio 14.2**
_A bug fix release._
* Fix port switching when unplugging headphones
=> pulseaudio: update to 14.2

packages/tools/dtc/package.mk
This should fix build issue for Allwinner images when dtc is not installed on system.
=> dtc: Build dtc also for host

scripts/checkdeps
Amlogic has image specific aml_encrypt_* binaries for creating(?) the firmware image package. Said binaries are for x86-64, so require qemu-binfmt-user on native builds.
@150balbes
=> checkdeps: add qemu-user as req for native aarch64 Amlogic builds

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Update CYW43455 firmware, this fixes wifi firmware crash on RPi4
=> brcmfmac_sdio-firmware-rpi: update to 4c47758

packages/network/samba/package.mk
Scheduled 6 weekly update of samba-stable
- update 4.13.3 to 4.13.4
- changelog: https://www.samba.org/samba/history/samba-4.13.4.html
=> samba: update to 4.13.4

packages/emulation/libretro-mrboom/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mrboom/package.mk
due to GET_HANDLER_SUPPORT limited to archive, libretro.mrboom has gitsubmodule,
which will not included in github's default release tar.gz, thus build failed.
add PKG_DEPENDS_UNPACK="libretro-common"
BTW, update version to 5.2
=> game.libretro.mrboom: fix build issue and update to 5.2

packages/sysutils/busybox/scripts/dthelper
It's good to know ram size for Pi boards (and works well) but for other SoC types the board name 99% correlates to a known config so we don't really need to capture it and Allwinner/Amlogic/Rockchip stats get easier to read. I've left 512MB devices as an exception since we don't formally support <1GB non-pi devices and it's good to expose them.
=> dthelper: only flag memsize for pi and 512mb boards

projects/Allwinner/filesystem/usr/bin/install2emmc
This PR adds installation script for Allwinner images. Script recreates clean image on eMMC using files from current installation. Storage partition is already extended to full size, so additional resize step after booting from eMMC is not necessary.
If user wants to transfer Kodi configuration, backup/restore functionality must be used.
=> Allwinner: Add installation script

packages/addons/addon-depends/go/package.mk
update 1.4.12 to 1.4.13
changelog: https://golang.org/doc/devel/release.html#go1.13.minor
milestone: https://github.com/golang/go/issues?q=milestone%3AGo1.13.14+label%3ACherryPickApproved
=> go: update to 1.14.13

packages/mediacenter/kodi-binary-addons/audiodecoder.dumb/package.mk
off_t in 32bit arch is 32bit, thus failed to build.
add a patch to change it to off64_t and pass build.
=> audiodecoder.dumb: fix build on 32bit arch

packages/linux/patches/raspberrypi/linux-010-vc4-plane-Dont-reject-fractional-source-coords.patch
This also fixes playback issues of 720p videos if no 720p modes
are whitelisted or refresh switch is disabled after the pixel-wrap
workaround commit 01e90a2882.
Fixes: #5048
=> linux (RPi): add patch to fix zoom in video player

packages/addons/addon-depends/system-tools-depends/i2c-tools/package.mk, packages/addons/addon-depends/system-tools-depends/strace/package.mk, packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
- i2c-tools: fix compile of libraries
- strace: fix compile on Generic due to mpers
- stress-ng: update to 0.12.02
Compile of i2c-tools was failing on a clean create_addon compile (on a build or a second go it would compile) isolated the issue down to the python compile of smbus.so must be done separately to pickup the shared library.
Took the opportunity to bump stress-ng 
compile of strace on Generic was also failing with m32/mx32 errors. Notes and reference to the addition of mpers setting - https://sourceforge.net/p/strace/mailman/message/36236388/
=> system-tools: fix addon compile issues and update stress-ng

projects/Allwinner/bootloader/release
Currently, if no DT overlay exists for specific device, image building fails. Fix that by ignoring copy error.
=> Allwinner: Fix DT overlay copy

scripts/uboot_helper
I originally wanted to use argparse when I wrote this script but didn't have the ability to do it then.
These change makes it much easier to read.
The functionality should be the exact same as before. The help has changed though.
```
$ ./scripts/uboot_helper --help                                                                                                                                                                                
usage: uboot_helper [-h] [project] [soc] [board] [dtb|config|crust_config]
Script to help with u-boot configuration
positional arguments:
project
soc
board
dtb|config|crust_config
optional arguments:
-h, --help            show this help message and exit
```
@jernejsk @Kwiboo please test if you have a chance
=> uboot_helper: convert to use argparse

packages/addons/addon-depends/qtbase/package.mk
This prevents qtbase picking up libzstd if it had been built before and creating broken hyperion binaries (dynamically linking to non-existent libzstd.so.1)
Fixes the issue reported on forum: https://forum.libreelec.tv/thread/23388-hyperion-x11-error-while-loading-shared-libraries-libzstd-so-1-cannot-open-share/
=> qtbase: disable zstd support

packages/debug/edid-decode/package.mk
update 15df4ae (2019-06-14) to 770cfb9 (2021-01-19)
changelog: https://git.linuxtv.org/edid-decode.git/log/
added mkpkg script as linuxtv is not accepting download requests
Hi Team, could you please have a look at this draft and suggest other options for the download. If there are none, can you please update the LibreELEC mirror with the mkpkg_edid-decode .tar.xz file.
=> edid-decode: update to 2021-01-19

packages/python/devel/Mako/package.mk
update 1.1.3 to 1.1.4
changelog: https://docs.makotemplates.org/en/latest/changelog.html#id1
=> Mako: update to 1.1.4

packages/sysutils/parted/package.mk
update 3.3 (2019-10-10) to 3.4 (2021-01-27)
news: https://git.savannah.gnu.org/cgit/parted.git/plain/NEWS?h=v3.4
=> parted: update to 3.4

config/arch.aarch64
These are the cpus used in Odroid N2/N2+ and Khadas VIM3
A311D/S922X-B/S922X - cortex-a73.cortex-a53
these are not used by default and only if overridden in **options** file
=> aarch64: add TARGET_CPU option cortex-a73.cortex-a53

packages/debug/strace/package.mk
32-bit binaries shouldn't be present in said build. Presently, it errors with:
checking for m32 personality compile support (using   -I.  )... no
checking whether to enable m32 personality support... no
configure: error: Cannot enable m32 personality support
=> strace: dont build 32bit support for aarch64

packages/x11/lib/libXt/package.mk, packages/x11/util/util-macros/package.mk
Update X11 packages
util-macros: update to 1.19.3
- update 1.19.2 (2018-03-05) to 1.19.3 (2021-01-24)
- changelog: https://gitlab.freedesktop.org/xorg/util/macros/-/commits/master/
libXt: update to 1.2.1
- update 1.2.0 (2019-06-21) to 1.2.1 (2021-01-24)
- changelog: https://github.com/freedesktop/xorg-libXt/commits/master
=> Update X11 packages (minors)

projects/NXP/devices/iMX6/patches/linux/linux-002-imx6qdl-wandboard-dtsi-i2c-bus-recovery.patch
In Wandboard the i2c bus sometimes(often) stuck during transmission, this can happen when reading EDID from the TV and lead to incorrect resolution and no sound. Add scl/sda gpios definitions to the device tree for i2c bus recovery.
=> iMX6: modify Wandboard device tree to apply i2c bus recovery

packages/sysutils/libevdev/package.mk
**view history here: https://gitlab.freedesktop.org/libevdev/libevdev/-/commits/master/** 
update 1.10.1 to 1.11.0
commit: https://gitlab.freedesktop.org/libevdev/libevdev/-/commit/60d4f1b2aea14a65a4c2cfed7631fade405b7adf
=> libevdev: update to 1.11.0

packages/addons/addon-depends/go/package.mk, packages/linux/package.mk
Minor update 1.14.13 (2020/12/03) to 1.14.14 (2021/01/19)
includes security fixes to the go command and the crypto/elliptic
package. See the Go 1.14.14 milestone on our issue tracker for details.
log: https://github.com/golang/go/issues?q=milestone%3AGo1.14.14+label%3ACherryPickApproved
diff: https://github.com/golang/go/compare/go1.14.13...go1.14.14
=> go: update to 1.14.14

packages/compress/pigz/package.mk
update 2.4 (2017-12-26) to 2.5 (2021-01-24)
log: https://github.com/madler/pigz/commits/master
changelog (from pigz.c):
- Add --alias/-A option to set .zip name for stdin input
- Add --comment/-C option to add comment in .gz or .zip
- Fix a bug that misidentified a multi-entry .zip
- Fix a bug that did not emit double syncs for -i -p 1
- Fix a bug in yarn that could try to access freed data
- Do not delete multi-entry .zip files when extracting
- Do not reject .zip entries with bit 11 set
- Avoid a possible threads lock-order inversion
- Ignore trailing junk after a gzip stream by default
=> pigz: update to 2.5

packages/graphics/libglvnd/package.mk
Switch to meson build & disable OpenGL ES1 & ES2 if it's not enabled.
=> libglvnd: switch to meson toolchain

packages/addons/addon-depends/go/package.mk, packages/linux/package.mk
this incorrectly included a kernel bump in #5077. (Linux: update to 5.10.12) 
This reverts commit 80f9c7e.
update 1.14.13 (2020/12/03) to 1.14.14 (2021/01/19)
includes security fixes to the go command and the crypto/elliptic
package. See the Go 1.14.14 milestone on our issue tracker for details.
log:
https://github.com/golang/go/issues?q=milestone%3AGo1.14.14+label%3ACherryPickApproved
diff: golang/go@go1.14.13...go1.14.14
=> go: update to 1.14.14 and revert accidentally update linux: update to 5.10.12

projects/RPi/devices/RPi4/patches/kodi/0001-hack-try-to-hide-pixel-wrap-issues.patch
The updated version fixes the "atomic commit failed" issues
that were present in the previous workaround.
=> kodi (RPi4): update workaround to hide pixel wrap issue

packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk, packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk, packages/mediacenter/kodi-binary-addons/pvr.octonet/package.mk, packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk, packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk, packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk, packages/textproc/jsoncpp/package.mk
Version 1.9.4 changed default build options so that the shared library is built by default which breaks addons linking against it.
Explicitly set the build options so that only the static library is built, as before the bump.
=> jsoncpp: only build static library

packages/addons/addon-depends/ccid/package.mk, packages/addons/service/pcscd/changelog.txt, packages/addons/service/pcscd/package.mk
ccid: update to 1.4.34
- update 1.4.33 (2020-06-25) to 1.4.34 (2021-01-24)
- changelog: https://salsa.debian.org/rousseau/CCID/blob/master/README.md
=> pcscd: update addon (101)

packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/changelog.txt, packages/addons/service/docker/package.mk
docker: update to 19.03.15 
- update 19.03.14 to 19.03.15
- changelog: https://docs.docker.com/engine/release-notes/19.03/
runc: update to 1.0.0-rc93
- update 1.0.0-rc92 (2020-08-06) to 1.0.0-rc93 (2021-02-03)
- changelog: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93
```
Docker version 19.03.15, build 99e3ed89195c4e551e87aad1e7453b65456b03ad
23:00:55 up 8 min,  load average: 1.22, 2.30, 1.68
Generic.x86_64-devel-20210206064519-ae98cfe
Linux LibreELEC 5.10.13 #1 SMP Sat Feb 6 07:47:22 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0-RC1 (18.9.910) Git:bb88e5e1db54844bc27befc7014c8118ae5ca275). Platform: Linux x86 64-bit
Kodi compiled 2021-02-06 by GCC 10.2.0 for Linux x86 64-bit version 5.10.13 (330253)
Running on LibreELEC …
```
=> docker: update addon to 19.03.15 (133)

projects/Allwinner/patches/linux/0046-drm-lima-add-governor-data-with-pre-defined-thresholds.patch, projects/Allwinner/patches/linux/0047-drm-lima-Use-delayed-timer-as-default-in-devfreq-profile.patch, projects/Allwinner/patches/linux/0048-drm-panfrost-Add-governor-data-with-pre-defined-thre.patch, projects/Allwinner/patches/linux/0049-drm-panfrost-Use-delayed-timer-as-default-in-devfreq.patch, projects/Allwinner/patches/linux/0050-clk-sunxi-ng-mp-fix-parent-rate-change-flag-check.patch, projects/Allwinner/patches/linux/0051-drm-sun4i-tcon-set-sync-polarity-for-tcon1-channel.patch, projects/Allwinner/patches/linux/0052-drm-sun4i-dw-hdmi-always-set-clock-rate.patch, projects/Allwinner/patches/linux/0053-drm-sun4i-Fix-H6-HDMI-PHY-configuration.patch, projects/Allwinner/patches/linux/0054-drm-sun4i-dw-hdmi-Fix-max.-frequency-for-H6.patch
This PR improves GUI responsiveness by adjusting lima/panfrost scheduler parameters and fixes plethora of different issues with H6 HDMI. 4K@60 and other HDMI2 modes also work now.
All patches are/will be upstreamed soon, so they'll go away in one or two kernel cycles.
=> Allwinner: linux: GPU and HDMI improvements

packages/emulation/libretro-dosbox-pure/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.dosbox-pure/package.mk
FYI:
https://github.com/schellingb/dosbox-pure
https://www.libretro.com/index.php/dosbox-pure-out-now-for-public-testing/
https://arstechnica.com/gadgets/2021/01/dosbox-pure-for-retroarch-aims-to-simplify-classic-ms-dos-gaming/
Build tested on Generic -> WIP / needs some testing
=> game.libretro.dosbox: add DOSbox-Pure to Kodi Game packages

packages/devel/heimdal/patches/0001-upstream-check-libtinfo-for-tgetent.patch, packages/devel/heimdal/patches/0002-upstream-fix-configure-err-msg.patch, scripts/checkdeps
These are some fixes for building with Fedora 33 Server as the host.
1 typo fix, newer java package and 3 new perl modules to check for in `scripts/checkdeps`.
A pair of upstreamed heimdal patches to resolve an issue where the build complains about not being able to find libncurses.
Fedora did, however, fail to build Kodi with a One Definition Rule C++ violation. I don't know if this is a new issue or not. I don't plan to investigate this further. Log: http://ix.io/2Obx
Series has been tested on a Ubuntu host and resulting image worked as expected.
=> Fedora buildhost fixes

packages/compress/pigz/package.mk
update 2.5 (2021-01-24) to 2.6 (2021-02-06)
log: https://github.com/madler/pigz/commits/master
changelog (from pigz.c):
- Add --huffman/-H and --rle/U strategy options
- Fix issue when compiling for no threads
- Fail silently on a broken pipe
=> pigz: update to 2.6

packages/x11/proto/xcb-proto/package.mk
update 1.14 to 1.14.1
announce: https://www.mail-archive.com/xorg-announce@lists.x.org/msg01270.html
=> xcb-proto: update to 1.14.1

packages/linux-drivers/bcm_sta/patches/bcm_sta-0012-kernel-4.14.patch
While looking at a build log I stumbled upon:
```
/home/docker/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/bcm_sta-6.30.223.271/x86-64/src/shared/linux_osl.c: In function 'osl_os_get_image_block':
/home/docker/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/bcm_sta-6.30.223.271/x86-64/src/shared/linux_osl.c:1083:28: warning: passing argument 2 of 'kernel_read' makes pointer from integer without a cast [-Wint-conversion]
1083 |  rdlen = kernel_read(fp, fp->f_pos, buf, len);
|                          ~~^~~~~~~
|                            |
|                            loff_t {aka long long int}
In file included from ./include/linux/huge_mm.h:8,
from ./include/linux/mm.h:687,
from /home/docker/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/bcm_sta …
```
=> bcm_sta: fix kernel_read() parameters

packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
only 2 pvr addons - pvr.zattoo bump should fix issue reported on forum https://forum.libreelec.tv/thread/23473-pvr-zattoo-not-working-fix-18-1-23-available-but-needs-compile-for-libreelec/
build-tested for RPi4
=> [le92] kodi binary addons: update to latest Leia versions

packages/network/connman/package.mk, packages/network/connman/patches/connman-06-timeserver_fix_warning.patch
Changes (from https://git.kernel.org/pub/scm/network/connman/connman.git/log/):
- src: Test return value of inet_pton consistently
- vpn: Do not do mixed declerations and code
- vpn: Export vpn_ipconfig_foreach as linker symbol
- vpnc: Do not lose credentials with VPN agent timeouts
- openvpn: Update documemtation for --proto
- wifi: Fix wireless interface not being added to tether bridge sometimes
- wifi: Base BSS expiration age on long scanning interval
- services: Escape passphrase string
- timeserver: Split new service and configuration update
- wifi: Always disconnect connection completely
- clock: Add TimeSynced signal emitted when the system time has been synced
- timeserver: Reset time sync on system timeserver update
- service: Restart online check when default service changes
- …
=> connman: update to 1.39

config/options, packages/virtual/libc/package.mk
Move the check if arm-mem should be included from virtual/libc
to config/options and set the ARM_MEM_SUPPORT variable accordingly.
This makes it possible to opt-out of using arm-mem which can
be helpful for performance testing and debugging (eg valgrind
doesn't play nicely with it).
=> config/options: add ARM_MEM_SUPPORT option to control arm-mem inclusion

packages/addons/addon-depends/go/package.mk
update 1.14.14 (2021/01/19) to 1.14.15 (2021-02-04)
See the Go 1.14.15 milestone on our issue tracker for details.
log: https://github.com/golang/go/issues?q=milestone%3AGo1.14.15+label%3ACherryPickApproved
diff: https://github.com/golang/go/compare/go1.14.14...go1.14.15
=> go: update to 1.14.15

packages/emulation/libretro-pcsx-rearmed/package.mk, packages/emulation/libretro-pcsx-rearmed/patches/libretro-pcsx-rearmed-995.01-disable-thread-rendering-for-arm.patch
disable threaded rendering for ARCH=arm/aarch64
Basically supersedes https://github.com/LibreELEC/LibreELEC.tv/pull/5047
Tested on Generic, RK3399 & VIM3 so should be fine for every SBC with NEON support which was broken by https://github.com/libretro/pcsx_rearmed/pull/462
=> libretro-pcsx-rearmed: updated to git 976907a / fix build

packages/addons/addon-depends/librespot-depends/rust/package.mk, packages/addons/service/librespot/changelog.txt, packages/addons/service/librespot/package.mk
rust: update to 1.50.0
- update 1.49.0 (2020-12-31) to 1.50.0 (2021-02-11)
- announcement: https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html
```
18:00:52 up 11 min,  load average: 0.27, 0.31, 0.20
AMLGX.aarch64-devel-20210212111004-6d60364
Linux odroid 5.11.0-rc7 #1 SMP PREEMPT Fri Feb 12 11:10:21 UTC 2021 aarch64 GNU/Linux
Starting Kodi (19.0-RC1 (18.9.910) Git:04303bf0c08adb47d9519cf7339acdd6edb1ec87). Platform: Linux ARM 64-bit
Kodi compiled 2021-02-12 by GCC 10.2.0 for Linux ARM 64-bit version 5.11.0 (330496)
Running on Amlogic Meson G12B (S922X) Hardkernel ODROID-N2Plus with LibreELEC (heitbaum): devel-20210212111004-6d60364 9.80, kernel: Linux ARM 64-bit version 5.11.0-rc7
FFmpeg version/source: 4.3.1-Kodi
Host CPU: ARMv8 Processor rev 2 …
```
=> librespot: update addon (126)

packages/linux/package.mk
Setting DTC_FLAGS as a make argument overrides the additional dtc flags
which are added in kernel's scripts/Makefile.lib.
This results in lots of noisy warnings when building RPi DT and overlays
and could be potentially problematic if kbuild adds important dtc flags.
Pass in DTC_FLAGS as an environment variable so that kbuild can
adjust DTC_FLAGS as needed.
@jernejsk I did an AW A64 kernel build and fdtdump showed that symbols were present in dtbs but doing a runtime test probably wouldn't hurt
=> linux: set DTC_FLAGS as environment variable instead of make argument

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk, packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
Build-tested for RPi4.
pvr.zattoo bump should fix issue reported on forum https://forum.libreelec.tv/thread/23473-pvr-zattoo-not-working-fix-18-1-23-available-but-needs-compile-for-libreelec/?postID=150461#post150461
=> kodi-binary-addons: update to latest versions

packages/virtual/debug/package.mk, projects/Amlogic/options, projects/RPi/options, projects/Samsung/options
valgrind can be useful to check if memory allocation is OK in release
builds and to check for issues that don't occur in debug builds.
As valgrind needs to be explicitly enabled removing the debug-only
restriction has no impact on normal builds.
Also drop unneeded VALGRIND="no" settings in project options files.
=> allow including valgrind in non-debug builds

packages/linux-firmware/kernel-firmware/package.mk
update 20201218 to 20210208
log: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/
```
Age	Commit message (Expand)	Author	Files	Lines
22 hours	Merge branch 'DG1-guc-huc-ADLS-dmc' of
git://anongit.freedesktop.org/drm/drm-...HEAD20210208mastermain
22 hours	Merge branch 'qcom-rb5' of
https://github.com/lumag/linux-firmware into main
22 hours	Mellanox: Add new mlxsw_spectrum firmware xx.2008.2304
22 hours	linux-firmware: add firmware for MT7921
22 hours	rtw88: RTL8821C: Update firmware to v24.8
22 hours	linux-firmware: Update firmware file for Intel Bluetooth AX210
22 hours	linux-firmware: Update firmware file for Intel Bluetooth AX200
22 hours	linux-firmware: Update firmware file for Intel Bluetooth AX201
11 days	i915: Add DMC v2.01 for ADL-S
11 days	i915: Add …
```
=> kernel-firmware: update to 20210208

packages/tools/procps-ng/package.mk
update 3.3.16 (2019-12-08) to 3.3.17 (2021-02-09)
news: https://gitlab.com/procps-ng/procps/-/blob/master/NEWS
tags: https://gitlab.com/procps-ng/procps/-/tags
=> procps-ng: update to 3.3.17

packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
The bump #4895 included the zstd depend which was introduced in btrfs-progs v4.13.1 (Sep 2017).
LibreELEC does not include libzstd in the core build so the tools were failing due to the missing library. 
This patch reverts to a btrfs-prongs without zstd thus fixing the introduced bug.
ref: 
- https://btrfs.wiki.kernel.org/index.php/Changelog
- https://btrfs.wiki.kernel.org/index.php/Changelog#btrfs-progs_v4.13_.28Sep_2017.29
=> btrfs-progs: update addon to (103) with disable-zstd

packages/python/devel/waf/package.mk
update 2.0.21 (2020-11-08) to 2.0.22 (2021-01-30)
changelog: https://gitlab.com/ita1024/waf/blob/master/ChangeLog
=> waf: update to 2.0.22

packages/tools/dt-overlays/package.mk, projects/Allwinner/patches/linux/0055-wip-h3-h5-cvbs.patch
This adds support for TVE (CVBS) on H3 and H5. It must be activated with DT overlays.
=> Allwinner: Add support for H3/H5 TVE

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Depends on https://github.com/LibreELEC/brcmfmac_sdio-firmware/pull/17
=> brcmfmac_sdio-firmware: update to 47c4aae

packages/audio/openal-soft/package.mk
The "native tools" have been dropped so cross compile should work again for ARM projects, tested on RK3399 & VIM3.
https://github.com/kcat/openal-soft/commit/9b11029af9274fc99414f4f007613f7073159fe5
=> openal-soft: clean up / drop host build

packages/graphics/glmark2/package.mk
update dab3e7d (2021-02-13) to 2021.02 (2021-02-15)
News: https://github.com/glmark2/glmark2/blob/master/NEWS
Release notes:
- Meson build system support for DRM/X11/Wayland builds.
- Fix precision handling in various fragment shaders.
- Fix spurious failures when using --validate.
- Always draw to the correct, offscreen buffer when using --off-screen.
- Don't prefer framebuffer formats with more than 8 bytes per component.
- Add basic mouse and keyboard support on Wayland.
=> glmark2: update to 2021.02

packages/audio/libopenmpt/package.mk
update 0.4.16 (2020-11-30) to 0.4.17 (2021-01-31)
changelog: https://lib.openmpt.org/libopenmpt/2021/01/31/releases-0.5.5-0.4.17-0.3.26/
change url to https as openmpt.org is now HSTS
=> libopenmpt: update to 0.4.17

packages/sysutils/systemd/package.mk
update 247 to 247.3
changelog: https://github.com/systemd/systemd-stable/commits/v247-stable
use systemd-stable source as it includes backports of patches from systemd
git to stable distributions
=> systemd: update to 247.3

tools/mkpkg/update_retroplayer-addons
Report which game addon packages are only present in LE but not in
the kodi game binary addon repo.
These packages are not automatically bumped by the script and should
either be removed from LE or added to the kodi game binary repo.
With current master this gives the following output:
```
Checking for orphaned addon packages in LE
ORHPANED game.libretro.4do, not present in kodi game repo
ORHPANED game.libretro.dosbox-pure, not present in kodi game repo
ORHPANED game.libretro.fbalpha, not present in kodi game repo
ORHPANED game.libretro.mame, not present in kodi game repo
ORHPANED game.libretro.mame2014, not present in kodi game repo
ORHPANED game.libretro.mupen64plus, not present in kodi game repo
ORHPANED game.libretro.reicast, not present in kodi game repo
ORHPANED …
```
=> update_retroplayer-addons: check for orphaned addon packages

packages/emulation/libretro-opera/package.mk, packages/emulation/libretro-opera/patches/libretro-opera-995.01-crosscompile.patch, packages/mediacenter/kodi-binary-addons/game.libretro.opera/package.mk
As follow up to https://github.com/LibreELEC/LibreELEC.tv/pull/5151#issue-574801219 and as a replacement for `game.libretro.4do` the 3DO emulator `game.libretro.opera` will be added.
=> [emulation] add game.libretro.opera as game.libretro.4do replacement

packages/security/openssl/package.mk
update 1.1.1i (2020-12-08) to 1.1.1j (2021-02-16)
changelog: https://www.openssl.org/news/changelog.html#openssl-111
tested on Generic
```
LibreELEC:~ # ssh -V
OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
```
=> openssl: update to 1.1.1j

packages/multimedia/dav1d/package.mk
update 0.8.1 to 0.8.2
release notes: https://code.videolan.org/videolan/dav1d/-/releases
This is a middle-size update of the dav1d decoder, from the 0.8.x branch.
This release adds most of the remaining NEON optimizations for ARM,
especially for 10/12bit bitdepth, in both ARM32 and ARM64.
This release also split the post-filters into their own threads.
This release speeds up quite a bit the desktop version, notably in the
coefficient decoding and the MSAC parts. It also introduces the first
10bit optimizations for x86.
Finally, this release improves the speed in numerous parts of the
decoder, improves the player shipped and brings other fixes.
=> dav1d: update to 0.8.2

packages/linux-firmware/iwlwifi-firmware/package.mk
update firmware for 5.10.16 from
- https://github.com/LibreELEC/iwlwifi-firmware/pull/28
https://www.intel.com/content/www/us/en/support/articles/000005511/wireless.html
updated:
- iwlwifi-3168-29.ucode
- iwlwifi-7265D-29.ucode
- iwlwifi-8000C-36.ucode
- iwlwifi-8265-36.ucode
- iwlwifi-9000-pu-b0-jf-b0-46.ucode
- iwlwifi-9260-th-b0-jf-b0-46.ucode
Add firmware for AX210
- iwlwifi-ty-a0-gf-a0-59.ucode
added: (ver 59)
- iwlwifi-Qu-b0-hr-b0-59.ucode (AX201)
- iwlwifi-Qu-b0-jf-b0-59.ucode (AX201)
- iwlwifi-Qu-c0-hr-b0-59.ucode (AX201)
- iwlwifi-Qu-c0-jf-b0-59.ucode (AX201)
- iwlwifi-QuZ-a0-hr-b0-59.ucode (AX201)
- iwlwifi-QuZ-a0-jf-b0-59.ucode (AX201)
- iwlwifi-cc-a0-59.ucode (AX200)
deleted: (ver 53) - replaced by (ver 59) - above
- iwlwifi-Qu-b0-hr-b0-53.ucode (AX201)
- …
=> iwlwifi-firmware: update to 7ffb8b6

packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk
These are the changes outside of project/device to have an RPi3.aarch64 image work. They're unobtrusive, so I hope to merge them despite LE not distributing such an image.
Change to the linux package.mk handling of .dts files lets it cope with the different locations of device tree files between arm and arm64 kernels. The same method is being used by u-boot devices. The safe_remove is because overlay_map.dtb is duplicated. The file should be in the `overlays/` directory (which it is), according to the RPi docs: https://www.raspberrypi.org/documentation/configuration/device-tree.md
Hardcoding to arm's overlay devicetrees because that's where they live in RPi's kernel tree. This is admittedly a guess at the "right thing", as there isn't an `overlays/` dir in `arch/arm64/boot/dts/broadcom/`. …
=> Friendlier for RPi aarch64

packages/debug/strace/package.mk, packages/debug/strace/patches/strace-0001-autoreconf.patch
- update 5.10 (2020-12-14) to 5.11 (2021-02-17)
- release notes: https://github.com/strace/strace/releases/tag/v5.11
- news: https://github.com/strace/strace/blob/master/NEWS
**some important and interesting improvements**
* Implemented decoding of V4L2_BUF_TYPE_META_CAPTURE,
V4L2_BUF_TYPE_META_OUTPUT, and VIDIOC_QUERY_EXT_CTRL ioctl commands.
* Updated lists of BPF_*, BTRFS_*, CLOSE_RANGE_*, ETH_*, IORING_*, KVM_*,
PR_*, PTRACE_*, RTA_*, RTAX_*, RTM_*, RTNH_*, SCTP_*, SO_*, SYS_*, UFFD_*,
and V4L2_* constants.
* Updated lists of ioctl commands from Linux 5.11.
```
Generic # strace -V
strace -- version 5.11
Copyright (c) 1991-2021 The strace developers <>.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```
=> strace: update to 5.11

projects/NXP/devices/iMX8/patches/u-boot/0001-v2-tools-imx8mimage-Restore-the-original-__ALIGN_MASK-macro.patch, projects/NXP/devices/iMX8/patches/u-boot/0002-ARM-dts-imx8mq-evk-Remove-u-boot-off-on-delay-us-property.patch, projects/NXP/devices/iMX8/patches/u-boot/0003-imx8mq_evk-add-distro-boot-cmd-support.patch
This adds some u-boot patches:
1) Fix booting from sdcard, this seems to have broke a little while back
https://patchwork.ozlabs.org/project/uboot/patch/20210222161643.315161-1-festevam@gmail.com/
https://patchwork.ozlabs.org/project/uboot/patch/20210222174047.464227-1-festevam@gmail.com/
2) Enable distro defaults to allow booting from an extlinux.conf file
With these patches I'm successfully able to boot LibreELEC on the iMX8mq-evk board
=> iMX8 add u-boot patches

projects/RPi/filesystem/usr/lib/udev/rules.d/80-alsa-preallocsize.rules
The default of 512k is too small at 192kHz/8ch, kodi can only get a
86ms buffer instead of the 200ms buffer it usually wants. That results
in occasional buffer underruns when playing media from local storage
which is uncached in kodi's default settings.
Increase the alsa buffer size to 1.2MB so kodi can get the audio buffer
size it likes to have.
=> RPi: add udev rule to increase alsa buffer size to 1.2MB

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, packages/tools/rpi-eeprom/package.mk
Nothing spectacular in the kernel update, but the firmware update contains a fix for non-working DMA channel 6 https://github.com/raspberrypi/firmware/issues/1541 (which could probably affect all devices that get that channel assigned, not only the audio card mentioned in the issue)
=> linux (RPi): update to 5.10.17

packages/mediacenter/kodi/patches/kodi-995.20-gbm-default-to-original-crtc-mode.patch
This brings kodi's RES_DESKTOP handling in line with other
windowing systems, kodi's default is now the mode configured
prior to kodi startup.
Kodi PR is here: https://github.com/xbmc/xbmc/pull/19244
Tested on RPi4: custom video mode set on kernel command line, kodi folder removed, kodi used the configured custom video mode (instead of the DRM "preferred" mode) and set screenmode to DESKTOP in guisettings.xml.
=> kodi: add patch to fix gbm default resolution handling

packages/network/connman/package.mk
From https://git.kernel.org/pub/scm/network/connman/connman.git/log/:
- wifi: Check valid network in disconnect callback
- wifi: Reset disconnecting status of any network
- service: Add online check interval config options
- service: Fix integer type for online check interval
We should include the post 1.39 wifi fixes
=> connman: update to 69a221f9

packages/network/bluez/package.mk
Builds fine for Generic, RK3399 & AMLG12B. Tested with 8bitdo controllers @chewitt tested it too with some devices. The new config option needs further testing!
Release notes:
http://www.bluez.org/release-of-bluez-5-56/
@HiassofT
added `JustWorksRepairing=always` to config
```
#JustWorksRepairing = never
```
***
BlueZ 5.54 adds new policy support for Just-Works repairing. The Bluetooth Just-Works pairing is for when hitting a button on the smartphone/computer and Bluetooth device to initiate pairing without entering of keys. The policy support is around Just-Works repairing for after the fact when there is an incoming JW pairing by the paired device. This policy support offers via the configuration file for BlueZ of never / confirm / always. Never is the default mode for BlueZ 5.54's …
=> bluez: update to bluez-5.56 / set JustWorksRepairing=always

packages/addons/addon-depends/multimedia-tools-depends/mesa-demos/package.mk
remove PKG_ARCH=i386
Cleanup.of i386 (following on from https://github.com/LibreELEC/LibreELEC.tv/commit/bebaafb33145dd4260cb95f57308e09196629a3c)
=> mesa-demos: drop i386 support

packages/mediacenter/kodi/scripts/pastekodi
@mglae  recently pointed out on the forum that pastekodi is a bit broken on LE9.2/RPi0-3 https://forum.libreelec.tv/thread/23566-pastekodi-unknown-command-and-no-log-on-first-attempt/?postID=151282#post151282 which reminded me I wanted to extend pastekodi a bit for quite some time :)
No huge changes, only a few minor things which are really helpful for debugging user issues though:
- On RPi include the get_throttled output - insufficient power supplies and cooling are still quite common and cause all sorts of weird issues. A quick glance at the log if throttled is 0x0 is great to tick that off the list
- Users often have old config file leftovers on their systems they've long forgotten about - listing the contents of .config, .config/system.d and .config/udev.rules.d should flag up the …
=> pastekodi cleanup and improvements

packages/network/openssh/package.mk, packages/network/openssh/patches/openssh-silence-missing-identity-error.patch
update 8.4p1 (2020-09-27) to 8.5p1 (2021-03-03)
release notes: http://www.openssh.com/txt/release-8.5
update patches - reverting openssh-portable patch:
- https://github.com/openssh/openssh-portable/commit/acadbb3402b70f72f14d9a6930ad41be97c2f9dc
```
Generic.x86_64-devel-20210304120039-2afdd84
Linux LibreELEC 5.10.20 #1 SMP Thu Mar 4 12:01:01 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0 (19.0.0) Git:19.0-Matrix). Platform: Linux x86 64-bit
Kodi compiled 2021-02-28 by GCC 10.2.0 for Linux x86 64-bit version 5.10.19 (330259)
Running on LibreELEC (heitbaum): devel-20210304120039-2afdd84 10.0, kernel: Linux x86 64-bit version 5.10.20
FFmpeg version/source: 4.3.1-Kodi
[ …
```
=> openssh: update to 8.5p1

packages/network/wireguard-tools/package.mk
update 1.0.20200827 to 1.0.20210223
log: https://git.zx2c4.com/wireguard-tools/log/
announce: https://www.mail-archive.com/wireguard@lists.zx2c4.com/msg06037.html
--
A new version, v1.0.20210223, of wireguard-tools has been tagged in the git
repository, containing various required userspace utilities, such as the
wg(8) and wg-quick(8) commands and documentation.
== Changes ==
* wg-quick: android: do not free iterated pointer
* wg-quick: openbsd: no use for userspace support
* embeddable-wg-library: sync latest from netlink.h
* wincompat: recent mingw has inet_ntop/inet_pton
* wincompat: add resource and manifest and enable lto
* wincompat: do not elevate by default
* completion: add help and syncconf completions
* sticky-sockets: do not use SO_REUSEADDR
* man: LOG_LEVEL variables changed …
=> wireguard-tools: update to 1.0.20210223

packages/devel/fakeroot/patches/fakeroot-002-build-fix.patch
This is upstream fix for host build issues introduced with glibc 2.33. Issue can be observed on Arch and upcoming Fedora.
Since this package is used only during build process, it should be safe to include in LE10.
More info:
https://bugs.archlinux.org/task/69572
https://bugzilla.redhat.com/show_bug.cgi?id=1901049
https://bugzilla.redhat.com/show_bug.cgi?id=1889862
Fix:
https://salsa.debian.org/clint/fakeroot/-/merge_requests/10
=> fakeroot: host build fix with glibc 2.33

packages/lang/Python3/package.mk
**release schedule:** https://www.python.org/dev/peps/pep-0569/
This is the second last of the scheduled Python 3.8.y series.
The ninth and final 3.8 bugfix update will be released in May 2021. After that, it is expected that security updates (source only) will be released until 5 years after the release of 3.8 final, so until approximately October 2024. 
update 3.8.7 (2020-12-21) to 3.8.8 (2021-02-19)
release: https://www.python.org/downloads/release/python-388/
diff: https://github.com/python/cpython/compare/v3.8.7...v3.8.8
- bpo-42938: Avoid static buffers when computing the repr of ctypes.c_double and ctypes.c_longdouble values. This issue was assigned CVE-2021-3177.
- bpo-42967: Fix web cache poisoning vulnerability by defaulting the query args separator to &, and allowing the user …
=> Python3: update to 3.8.8

config/functions
This fixes building packages into init with the meson buildsystem.
The issue is that `setup_toolchain` exports `$CC` and not `$TARGET_CC`, which in turn leads us create a meson.conf file where the compiler is emptystring.
To make the code clear I decided against reusing `create_meson_conf_host` which actually might look exactly the same now, but I want to make sure it's obvious that the init configuration is generated.
Also I just fixed CC, CXX, AR, STRIP and I'm not sure if other variables need changes as well.
I might be able to judge it once I can actually run my WIP branch and verify the init packages work.
=> buildsystem: fix building meson:init

packages/sysutils/v4l-utils/package.mk
Pretty simple, include v4l-compliance utility when using a devel build.
=> v4l-utils: install v4l-compliance utility

packages/addons/driver/hdhomerun/source/resources/actions.py, packages/addons/driver/imon-mce/source/default.py, packages/addons/driver/sundtek-mediatv/source/resources/actions.py, packages/addons/service/librespot/source/resources/lib/ls_addon.py, packages/addons/service/net-snmp/source/default.py
Update addon code to conform to the the migration away from xbmc.translatePath to xbmcvfs.translatePath.
- net-snmp: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath
- sundtek-mediatv: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath
- hdhomerun: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath
- imon-mce: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath
- librespot: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath
=> Addons: update xbmc.translatePath (deprecated) to xbmcvfs.translatePath

packages/audio/pulseaudio/config/system.pa
...from system.pa config to get rid of journalctl warning:
>Mar 04 18:26:04 phoenix pulseaudio[482]: E: [pulseaudio] module-rescue-streams.c: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/#module-rescue-streamsisdeprecatedfunctionalitymovedtothecore
=> pulseaudio: module-rescue-stream is deprecated - remove it 

projects/Allwinner/devices/H6/patches/u-boot/0008-arm64-dts-allwinner-h6-tanix-tx6-enable-emmc.patch
This PR adds DT node for emmc in U-Boot, which is needed to properly load mmc driver in U-Boot. Without it, it's impossible to boot LE from emmc.
=> Allwinner: H6: Fix emmc in U-Boot for Tanix TX6

projects/NXP/devices/iMX8/filesystem/usr/bin/cputemp, projects/NXP/devices/iMX8/filesystem/usr/bin/gputemp
Pretty simple, just add the normal cputemp/gputemp scripts.
Note that kodi doesn't actually show gpu temp for arm platforms. I'll PR a fix upstream for that.
ref: https://github.com/xbmc/xbmc/blob/master/xbmc/windows/GUIWindowSystemInfo.cpp#L144-L146
=> iMX8: add cputemp and gputemp scripts

projects/NXP/devices/iMX8/bootloader/update.sh, projects/NXP/devices/iMX8/filesystem/usr/bin/install2emmc, projects/NXP/devices/iMX8/linux/linux.aarch64.conf
This adds support for the SPI-NOR chip on the i.MX8MQ-evk board
ref: https://cateee.net/lkddb/web-lkddb/MTD_SPI_NOR.html
I've added support to the `update.sh` script to be able to update the bootloader if located on the eMMC.
I've also added the `install2emmc` script from Allwinner and made a few changes specific to i.MX8
=> i.MX8: add SPI-NOR eMMC driver and install2emmc script

projects/Generic/options
Likewise if the path is too long where the LE git is located this error turns up, no proper fix yet so disable for now that jenkins is happy again
`/bin/sh: Argument list too long`
```
LD [M]  /var/lib/jenkins/LE/build4/workspace/Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-10.0-devel/build/crazycat-4a6d5e54cb90363e50f20a91af93aec84eef3205/v4l/dvb-vidtv-demod.o
make[4]: /bin/sh: Die Argumentliste ist zu lang
make[4]: *** [scripts/Makefile.build:414: /var/lib/jenkins/LE/build4/workspace/Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-10.0-devel/build/crazycat-4a6d5e54cb90363e50f20a91af93aec84eef3205/v4l/modules.order] Fehler 127
```
=> Generic: disable dvb add-ons

packages/addons/service/syncthing/changelog.txt, packages/addons/service/syncthing/package.mk
update 1.13.1 (2021-02-04) to 1.14.0 (2021-03-03)
release notes: https://github.com/syncthing/syncthing/releases/tag/v1.14.0
=> syncthing: update to 1.14.0 (addon 114)

packages/mediacenter/LibreELEC-settings/package.mk, packages/mediacenter/LibreELEC-settings/scripts/factory-reset, packages/sysutils/busybox/scripts/libreelec-target-generator
This is a cleanup of the system reset script. Two functional changes:
The hard reset is now filesystem agnostic, meaning it will use rm to clear /storage, instead of recreating the filesystem.
The soft reset now specifically deletes .cache, .config and .kodi only. These are the same directories preserved by LE backups
=> factory-reset: cleanup

packages/network/avahi/package.mk
Currently there is only `/etc/avahi/services/sftp-ssh.service` which announces `_sftp-ssh._tcp`.
There should also be `/etc/avahi/services/ssh.service` which should announce `_ssh._tcp`.
Discussion:
https://github.com/LibreELEC/LibreELEC.tv/issues/4841
Replaces https://github.com/LibreELEC/LibreELEC.tv/pull/4843
=> avahi: do not delete ssh.service

packages/addons/addon-depends/snapcast-depends/aixlog/package.mk
SHA256 has been updated since it was first downloaded.
```
<<< aixlog:target seq 392 <<<
^[[1;36mGET^[[0m      aixlog (archive)
--2021-03-10 17:17:46--  https://github.com/badaix/aixlog/archive/v1.5.0.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/badaix/aixlog/tar.gz/v1.5.0 [following]
--2021-03-10 17:17:46--  https://codeload.github.com/badaix/aixlog/tar.gz/v1.5.0
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: …
```
=> aixlog: update sha256

packages/audio/alsa-lib/package.mk
I'm not sure if this was on purpose or not. It's also pretty harmless as we check if a user was added already, but there is no circumstances where we include alsa-lib without systemd so let's just remove this.
duplicate of:
https://github.com/LibreELEC/LibreELEC.tv/blob/965d74e6e166f6bcb29ca3e76c3ae6b40ce0d0d6/packages/sysutils/systemd/package.mk#L264
=> alsa-lib: remove duplicate user creation (already in systemd)

packages/network/bluez/patches/bluez-999.01-fix-removing-all-remote-SEPs-when-loading-from-cache.patch
Some users reported issues with repairing after package bump 5.56 https://github.com/LibreELEC/LibreELEC.tv/commit/24c3d53f8ad0e1411920d707eca38807d5d6a2a5 but I can't proof it since my devices worked fine before & after adding the patch.
Tested with Generic & RK builds + Anker Soundcore & Echo Dot 3. + 8bitdo controllers
Fixes:
- https://github.com/bluez/bluez/issues/102
=> bluez: add patch "Fix removing all remote SEPs when loading from cache"

packages/linux-firmware/dvb-firmware/package.mk
Fixes reported issue: https://github.com/LibreELEC/dvb-firmware/pull/17
- PCTV 461e v2 DVB-S adapter
=> dvb-firmware: update to 1.4.2

packages/web/libmicrohttpd/package.mk
Allow kodi web server to use https. With this change "Settings->Services->Control->Enable SSL" is visiible and can be used.
Kodi size is only increased by ~20k
Reported in issue #5136
=> libmicrohttpd: enable https for kodi webserver

packages/security/gnutls/package.mk
Built and running on RPi3. I don't know with certainty what ffmpeg uses it for to say it's tested too, but streaming addons are working.
=> gnutls: update to 3.7.1

.gitignore
This allows git to ignore the .old files created when using `./tools/adjust_kernel_config` (they are actually created by `kbuild`.
before:
```
$ git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
projects/Generic/linux/linux.x86_64.conf.old
projects/NXP/devices/iMX8/linux/linux.aarch64.conf.old
```
=> add old linux configs to gitignore

packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch, packages/mediacenter/kodi/scripts/service-addon-wrapper
This reverts commit 3fc36563b1ae228e26979751439a6a069e078136.
This fixes service addons not being started after installation.
Tested on RPi4 with lcdd addon: systemd service was started on installation, before update service was stopped and started again after update
=> Revert "kodi: service addon wrapper call fix"

packages/network/samba/package.mk
update 4.13.4 to 4.13.5
changelog: https://www.samba.org/samba/history/samba-4.13.5.html
samba 4.13 is now officially in maintenance mode, with the release of 4.14 on 2021-03-09.
It will transition to security fixes only ~2021-09 - September 2021
And be discontinued (EOL) ~2022-03 - March 2022
- https://wiki.samba.org/index.php/Samba_Release_Planning
=> samba: update to 4.13.5

packages/sysutils/busybox/scripts/createlog
Seems like this was broken for 6+ years :)
=> busybox: fix createlog udev rule wildcard

packages/security/openssl/package.mk
Security fix for 2 CVEs: https://www.openssl.org/news/changelog.html#openssl-111
=> openssl: update to 1.1.1k

packages/network/samba/package.mk
update 4.13.5 to 4.13.7
changelog:
- https://www.samba.org/samba/history/samba-4.13.6.html
- https://www.samba.org/samba/history/samba-4.13.7.html
=> samba: update to 4.13.7

packages/security/nettle/package.mk
update 3.7 (2021-01-04) to 3.7.2 (2021-03-21)
changelog: https://git.lysator.liu.se/nettle/nettle/-/blob/master/ChangeLog
news: https://git.lysator.liu.se/nettle/nettle/-/blob/master/NEWS
NEWS for the Nettle 3.7.2 release
This is a bugfix release, fixing a bug in ECDSA signature
verification that could lead to a denial of service attack
(via an assertion failure) or possibly incorrect results. It
also fixes a few related problems where scalars are required
to be canonically reduced modulo the ECC group order, but in
fact may be slightly larger.
Upgrading to the new version is strongly recommended.
Even when no assert is triggered in ecdsa_verify, ECC point
multiplication may get invalid intermediate values as input,
and produce incorrect results. It's trivial to construct
alleged …
=> nettle: update to 3.7.2

packages/python/graphics/Pillow/package.mk
Update 8.1.0 (2021-01-02) to 8.1.2 (2021-03-06)
Release notes at: https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst
- Use more specific regex chars to prevent ReDoS. CVE-2021-25292 [hugovk]
- Fix OOB Read in TiffDecode.c, and check the tile validity before reading. CVE-2021-25291 [wiredfool]
- Fix negative size read in TiffDecode.c. CVE-2021-25290 [wiredfool]
- Fix OOB read in SgiRleDecode.c. CVE-2021-25293 [wiredfool]
- Incorrect error code checking in TiffDecode.c. CVE-2021-25289 [wiredfool]
- PyModule_AddObject fix for Python 3.10 #5194 [radarhere]
- Fix Memory DOS in BLP (CVE-2021-27921), ICNS (CVE-2021-27922) and ICO (CVE-2021-27923) Image Plugins [wiredfool]
=> Pillow: update to 8.1.2

scripts/unpack
In case two packages has dependency on each other unpacking fails because unpack script goes to loop and eats all the computer resources. With this change unpack fails on third pass.
```
unpack recursive limit hit [package1, package2]
${SCRIPTS}/unpack "${p}" "${PARENT_PKG}"
${SCRIPTS}/unpack "${p}" "${PARENT_PKG}"
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
```
=> unpack: prevent circular unpacking between two packages

packages/mediacenter/kodi/system.d/kodi-waitonnetwork.service
if the kodi-waitonnetwork service timed out we shouldn't consider it failed.
=> kodi: waitonnetwork service shouldn't be considered failed if it timed out

packages/tools/crust/package.mk, projects/Allwinner/patches/linux/0056-arm64-dts-allwinner-h6-beelink-gs1-Remove-ext.-32-kH.patch, scripts/uboot_helper
Beelink GS1 has non-working RTC due to problems with external 32768 Hz oscillator. This also impacts HDMI-CEC and Crust firmware, used for suspend/resume functionality. Fix that by switching to internal, less precise oscillator. Linux patch was submitted upstream.
=> Allwinner: Fix few Beelink GS1 issues

packages/addons/service/snapclient/changelog.txt, packages/addons/service/snapclient/package.mk, packages/addons/service/snapclient/source/addon.py, packages/addons/service/snapclient/source/bin/snapclient.start, packages/addons/service/snapclient/source/resources/language/English/strings.po, packages/addons/service/snapclient/source/resources/settings.xml, packages/addons/service/snapclient/source/settings-default.xml
The listing of sound cards failed due to the previous method used returned bytes instead of str.
=> snapclient: Fixed incompatible types when listing sound cards and added --host support

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk, packages/multimedia/aom/package.mk
- aom (AV1): update to 3.0.0
- move aom from git hash to version numbering
- but since 2020-05-07 official releases have been made available starting with v2.0.0 "Applejack".
- ffmpegx: update to 4.3.2
- ffmpeg-tools: update addon to 115
=> ffmpegx: update to 4.3.2 and ffmpeg-tools (115)

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libxshmfence/package.mk, packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk, packages/addons/addon-depends/chrome-depends/gtk3/package.mk, packages/addons/addon-depends/chrome-depends/gtk3/patches/disable-to-pixdata-build.patch, packages/addons/addon-depends/chrome-depends/pango/package.mk, packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk
Note: these are only chrome dependancies - so no impact to other LE10 core or addons
- gdk-pixbuf: update to 2.42.4
- gtk3: disable use of to-pixdata during build
- gtk3: update to 3.24.28
- pango: update to 1.48.4
- at-spi2-core: update to 2.40.0
- chrome: update to 89.0.4389.114 and fix gtk3 compile issues and addon (105)
- New dependency for chrome 89 versus 87 - chrome-libxshmfence
- harfbuzz bump is not included as it is also used by libass
- Build tested against master [HEAD]
- Run tested on TGL
=> chrome: update to 89.0.4389.114 and fix gtk3 compile issues and addon (105)

packages/graphics/mesa/package.mk
- https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0.2-Released
- https://lists.freedesktop.org/archives/mesa-dev/2021-April/225039.html
> This un-breaks AMD vaapi.
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1249483-mesa-21-0-2-released-with-lavapipe-fixes-improved-amd-l3-cache-calculation?p=1249484#post1249484
=> mesa: updated to 21.0.2

projects/Allwinner/filesystem/usr/lib/systemd/sleep.conf.d/memonly.conf
Avoid using "freeze" method, which is used by systemd in case default "mem" method fails.
"freeze" type suspend can't be woken from using IR remote and Crust firmware
on Allwinner boards.
=> Allwinner: configure systemd-suspend.service to only use suspend-to-ram

packages/addons/service/syncthing/changelog.txt, packages/addons/service/syncthing/package.mk, packages/addons/service/syncthing/source/bin/syncthing-service
- update 1.14.0 (2021-03-03) to 1.15.1 (2021-04-06)
- release notes: https://github.com/syncthing/syncthing/releases/tag/v1.15.1
- also fix reported issue https://forum.libreelec.tv/thread/972-syncthing/?postID=153781#post153781
- reference to 1 is located in https://docs.syncthing.net/dev/debugging.html?highlight=stnodefaultfolder
=> syncthing: update to 1.15.1

packages/linux-driver-addons/dvb/crazycat/package.mk, packages/linux-driver-addons/dvb/depends/media_tree/package.mk, packages/linux-driver-addons/dvb/dvb-latest/package.mk, projects/Generic/options
- update dvb-latest to kernel 5.13ish
- workaround `/bin/sh: Argument list too long` problem due too long filepaths, instead of using the git hash we use now a tag that is much shorter, avoids adding other strange workarounds like disabling modules to reduce amount of files etc
should hopefully fix jenkins
=> DVB add-on fixes

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
pretty big important Leia backport update that fixes a lot of add-ons
https://github.com/xbmc/inputstream.adaptive/pull/634
=> inputstream.adaptive: bump to 2.4.7-Leia

packages/sysutils/busybox/package.mk, packages/sysutils/busybox/scripts/create-edid-cpio, packages/sysutils/busybox/scripts/dump-active-edids-drm, packages/sysutils/busybox/scripts/getedid-drm, packages/sysutils/busybox/scripts/update-bootloader-edid-rpi
This script simply creates /flash/edid.cpio with the contents from
.config/firmware/edid
Compared to the x86 specific getedid script this works on all platforms
as it doesn't contain any platform specific code. Eventually getedid
should be refactored make use of this helper script, too.
=> busybox: add getedid script for RPi

projects/RPi/devices/RPi4/patches/kodi/0002-set-colorspace-connector-property.patch
This enables signalling of BT.2020 colorspace via HDMI.
#5319 is needed for this, HDR video playback looks OK now (only 10bit output is missing ATM)
=> kodi (RPi4): add patch to set colorspace connector property

packages/linux/package.mk, projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.27
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.28
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.29
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.30
5.10.27,- 219 patches
5.10.28 - 126 patches
5.10.29 - 41 patches
5.10.30 - 188 patches
log - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.10.y
- Generic (TGL) - build and run tested 5.10.27,5.10.28,5.10.29, 5.10.30 - heitbaum
=> [Allwinner,Generic,Rockchip] linux: Update to 5.10.30

packages/graphics/mesa/patches/fix_for_ticket4605.patch
reference: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4605
After mesa upgrade 20.3.5 -> 21.0.2, AMD Kabini vaapi H264 hw. decode
stopped working
System information
Describe the issue
After mesa sources upgrade from 20.3.5 -> 21.0.2 & recompile, vaapi H264
decode stopped working. Recompiling back to 20.3.5 brings vaapi decode
back. Mesa sources change is single change causing vaapi decode to stop
working.
fix from warpme - Piotr Oniszczuk
=> mesa: fix for AMD Kabini vaapi H264 hw decode stopped working

packages/addons/service/librespot/changelog.txt, packages/addons/service/librespot/package.mk, packages/addons/service/librespot/source/resources/lib/ls_librespot.py
Bug reported an fix tested in: https://forum.libreelec.tv/thread/23822-rpi4-le10-0-nightly-20210411-5a67b41-librespot-crashes-after-playing-some-songs/
=> librespot: use utf-8 encoding in Python when parsing librespot

packages/network/wireless-regdb/package.mk
Previous checksum refers to the 2020.11.20 release.
=> wireless-regdb: update checksum for 2021.04.21 release

packages/graphics/mesa/package.mk
update 21.0.2 to 21.0.3
announce: https://lists.freedesktop.org/archives/mesa-dev/2021-April/225130.html
AMD revert patch is not included in the release
=> mesa: update to 21.0.3

packages/lang/Python3/package.mk
update form 3.8.8 to 3.8.9
changelog: https://docs.python.org/release/3.8.9/whatsnew/changelog.html#python-3-8-9
release schedule: PEP 569 - https://www.python.org/dev/peps/pep-0569/
3.8.8: Friday, 2021-02-19
3.8.9: Friday, 2021-04-02 (security hotfix)
3.8.10: Monday, 2021-05-03 - Final regular bugfix release with binary installers:
=> Python3: update to 3.8.9 (security hotfix)

projects/ARM/options
Only a cleanup of unused option.
=> exfat: cleanup no longer in use fuse EXFAT option

packages/debug/libva-utils/package.mk, packages/multimedia/gmmlib/package.mk, packages/multimedia/libva/package.mk, packages/multimedia/media-driver/package.mk, packages/x11/driver/xf86-video-intel/package.mk
Intel driver refresh
This brings all Intel video components up to current.
Dependencies
- libva: update to 2.11.0
- gmmlib: update to 21.1.2
- libva-utils: update to 2.11.1
- media-driver: update to 21.1.3
Also included is:
- xf86-video-intel: update to latest 2021-01-15
- which I have run with SKL/TGL since Jan 2021
- https://github.com/intel/media-driver/releases/tag/intel-media-21.1.3
Supported Platforms
- BDW/SKL/APL(BXT)/KBL/CFL/WHL/CML/ICL/EHL/JSL/TGL/RKL/DG1/SG1/ADL-S/ADL-P
What's New
- TGL/RKL/DG1/SG1/ADL-S/ADL-P New Features
- List of new features comparing to previous release as below. You could refer to Readme for more information.
- Optimized AV1 Decode software latency
- Enhanced AV1 Decode robustness for error clip
- Put render/VEBOX heap in local memory if needed on DGFX …
=> Intel Media Driver 2021Q1 Release - 21.1.3

packages/graphics/libdrm/package.mk
update 2.4.104 (2021-01-11) to 2.4.105 (2021-04-07)
commits: https://gitlab.freedesktop.org/mesa/drm/-/commits/master/
Release **seems** to only have changes for Intel and AMD. 
Release notes: https://lists.freedesktop.org/archives/dri-devel/2021-April/302515.html
=> libdrm: update to 2.4.105

projects/Allwinner/patches/ffmpeg/0003-v4l2_request-revert-changes.patch
This makes interlaced H264 content decoding more resilient on stream errors, which often come in a form of missing reference frames. Such errors are especially common when switching from one to another DVB channel. It can also be occasionally observed without channel switch, like in this sample: http://jernej.libreelec.tv/videos/cedrus_broken.ts
Forum ref: https://forum.libreelec.tv/thread/17565-nightly-images-for-a64-h3-h5-h6-and-r40-boards/?postID=154789#post154789
=> Allwinner: ffmpeg: make H264 interlaced decoding more error proof

packages/graphics/libdrm/patches/revert-xf86drmMode-set-FB_MODIFIERS-flag-when-modifiers-are-supplied.patch
Bug introduced in #5301 
- https://github.com/LibreELEC/LibreELEC.tv/pull/5301#issuecomment-827952096
Fix is included in libdrm master (and likely 2.4.106)
- https://gitlab.freedesktop.org/mesa/drm/-/commit/40f73d0b0b3936ccadc693edc25aad70c1225766
=> libdrm: Revert set FB_MODIFIERS flag when modifiers are supplied

packages/debug/xorg-intel-gpu-tools/package.mk, packages/tools/procps-ng/package.mk
Fix build of xorg-intel-gpu-tools:
- error occurring:
```
../lib/igt_aux.c:54:10: fatal error: proc/readproc.h: No such file or directory
54 | #include <proc/readproc.h>
|          ^~~~~~~~~~~~~~~~~
```
- procps-ng: install missing headers required for dependant packages
- additionally tested build of **busybox** which is dependant on procps-ng 
- xorg-intel-gpu-tools: update to 1.26
- update 1.25 (2020-03-20) to 1.26 (2021-04-23)
- news: https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/tree/NEWS
- Update the URLs
=> Fix build of xorg-intel-gpu-tools

packages/network/netbase/package.mk
update 6.2 to 6.3
diff: https://salsa.debian.org/md/netbase/-/compare/v6.2...v6.3
This PR given that 6.2 not available directly for download.
=> netbase: update to 6.3

packages/network/samba/package.mk
update 4.1.7 (2021-03-24) to 4.18.8 (2021-04-29)
release notes: https://www.samba.org/samba/history/samba-4.13.8.html
==
This is a security release in order to address the following defect:
o CVE-2021-20254: Negative idmap cache entries can cause incorrect group entries
in the Samba file server process token.
=======
Details
=======
o  CVE-2021-20254:
The Samba smbd file server must map Windows group identities (SIDs) into unix
group ids (gids). The code that performs this had a flaw that could allow it
to read data beyond the end of the array in the case where a negative cache
entry had been added to the mapping cache. This could cause the calling code
to return those values into the process token that stores the group
membership for a user.
Most commonly this flaw caused the calling …
=> samba: update to 4.13.8

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk
This reverts the RPi kernel and firmware bumps of #5348 as the recent changes caused a regression - see https://github.com/LibreELEC/LibreELEC.tv/pull/5348#issuecomment-830673202
Kernel and firmware are now back to the versions used in LE10 beta2 and runtime test on RPi4 was fine
=> linux (RPi): revert to 5.10.27-7fb9d00

config/options, packages/devel/glibc/patches/arm/glibc-add-support-for-SHT_RELR-sections.patch, packages/devel/gperftools/package.mk, packages/virtual/libc/package.mk
All credit for finding the solution goes to @wagnerch
Full story here: https://github.com/xbmc/inputstream.adaptive/issues/678
On ARM targets, we are using libwidevine extracted from ChromeOS. Starting from June 1st, Google will be deprecating Widevine older than 4.10.2252.0. Unfortunately, the latest libwidevine.so changed significantly and does not work on LibreELEC (or any other OS) because of the following issues:
1. Using SHT_RELR relocations not available in vanilla glibc.
2. Odd usage of static TLS that causes `cannot allocate memory in static TLS block` error.
This PR aims to target these issues in the following ways:
1. Add a glibc patch from ChromeOS that adds SHT_RELR section support to glibc dynamic linker - the patch does not modify behaviour for any other sections and should …
=> [ARM] Add suport for libwidevine.so >= 4.10.2252.0

packages/devel/glibc/patches/arm/glibc-add-support-for-SHT_RELR-sections.patch, packages/devel/gperftools/package.mk, packages/virtual/libc/package.mk
Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/5376
Alternative approach (linking Kodi) available at https://github.com/LibreELEC/LibreELEC.tv/compare/libreelec-9.2...wagnerch:widevine_support-le9.2
Due to lack of resources only unpack-tested but @wagnerch reported his approach works: https://github.com/LibreELEC/LibreELEC.tv/pull/5376#issuecomment-841848760
=> [ARM][9.2] Add suport for libwidevine.so >= 4.10.2252.0

packages/devel/gperftools/package.mk
release files != git .... 
gperftools release files contain no cmake, just the source dump of the release files contain cmake
reverted back to configure because we want to use release files :)
@kszaq can you check if 9.2 works ?
=> gperftools: fix for release files

packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk, packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk
- libmediainfo: update to 21.03
- libzen: update to 0.4.39
- mediainfo: update to 21.03
- mpg123: update to 1.27.2
- mpv-drmprime: update to 0.33.1
- squeezelite: update to 2021-05-13 (1.9.9.1386)
=> multimedia-tools: update addon to 115

packages/sysutils/busybox/scripts/kernel-overlays-setup
In forum thread https://forum.libreelec.tv/thread/23927-version-9-95-2-de-librelec/ some users are annoyed by the depmod error message due to the stale nvidia.ko symbolic link.
Log depmod messages to /dev/kmsg too. On real errors they will be visible in dmesg/journal.
It is possible that kmsg rate limit is triggered with larger output but I see no support impact here.
=> busybox: kernel-overlays-setup: log depmod to /dev/kmsg

packages/mediacenter/LibreELEC-settings/package.mk, packages/mediacenter/kodi/scripts/kodi-config
This adds the LD_PRELOAD content to kodi.conf and also bumps the settings add-on to pick-up one minor fix and the dtflags stats change (both are backports of things we've run in master for some time).
=> prep for 9.2.7 widevine release

projects/Allwinner/devices/H6/patches/linux/0020-arm64-dts-allwinner-h6-tanix-tx6-add-bt-enable-rtw88.patch
- Add the regulator - reg_vcc_wifi_io
- Add the wifi_pwrseq
- Add the mmc1 node for the SDIO card (rtl8822cs)
- Add the uart1 node for Bluetooth (rtl8822cs-bt)
- &mmc1
- wifi SDIO is yet to be added to the mainline rtw88 driver
- &uart1
- Bluetooth is registered - rtl8822cs-bt
```
[    6.470501] Bluetooth: Core ver 2.22
[    6.470711] Bluetooth: HCI device and connection manager initialized
[    6.470789] Bluetooth: HCI socket layer initialized
[    6.470819] Bluetooth: L2CAP socket layer initialized
[    6.470918] Bluetooth: SCO socket layer initialized
[    6.514784] Bluetooth: HCI UART driver ver 2.3
[    6.514811] Bluetooth: HCI UART protocol H4 registered
[    6.514815] Bluetooth: HCI UART protocol BCSP registered
[    6.514977] Bluetooth: HCI UART protocol LL registered
[ …
```
=> Allwinner: linux: enable BT on Tanix TX6 and add wifi node for rtl8822cs (rtw88)

packages/mediacenter/kodi/patches/kodi-100.31.le-addons-no-startupenable.patch
The feature is not only not needed for LE but as well does enable the DVB driver addons.
Fix for #5397
Tested on Generic.
=> Kodi: Remove "disable addon dialog at startup" for LibreELEC

packages/network/samba/package.mk
Scheduled samba maintenance release (July and September are the next two scheduled maintenance releases of 4.13 - at which time there will be security releases till ~Mar-2022)
- https://wiki.samba.org/index.php/Release_Planning_for_Samba_4.13
- https://wiki.samba.org/index.php/Samba_Release_Planning
—-
update 4.13.8 (2021-04-29) to 4.13.9 (2021-05-11)
release notes: https://www.samba.org/samba/history/samba-4.13.9.html
This is the latest stable release of the Samba 4.13 release series.
Changes since 4.13.8
o  Jeremy Allison <jra@samba.org>
* BUG 14696: s3: smbd: SMB1 SMBsplwr doesn't send a reply packet on success.
o  Andrew Bartlett <abartlet@samba.org>
* BUG 14689: Add documentation for dsdb_group_audit and dsdb_group_json_audit
to "log level", synchronise "log …
=> samba: update to 4.13.9

packages/sysutils/systemd/scripts/systemd-machine-id-setup, packages/sysutils/systemd/system.d/machine-id.service
Since systemd v247 the [first boot machine-id handling](https://www.freedesktop.org/software/systemd/man/machine-id.html#First%20Boot%20Semantics) has changed slightly: the file is overmounted. 
That is no issue for the normal installation on an empty disk without `/storage/.cache` but if `/storage/.cache/systemd-machine-id` can be created the file is overmounted by a read only temporary id and a new machine ID is created on any boot:
```
May 26 16:56:51 LibreELEC systemd[1]: Initializing machine ID from random generator.
[..]
May 26 16:56:51 LibreELEC systemd[1]: Starting Setup machine-id...
[..]
May 26 16:56:51 LibreELEC systemd[1]: machine-id.service: Main process exited, code=exited, status=1/FAILURE
May 26 16:56:51 LibreELEC systemd[1]: machine-id.service: Failed with result …
```
=> systemd: fix systemd-machine-id-setup for v247 special case

projects/Rockchip/README.md, projects/Rockchip/bootloader/release, projects/Rockchip/devices/RK3399/README.md, projects/Rockchip/patches/linux/default/linux-0030-regulator-from-list.patch, projects/Rockchip/patches/linux/default/linux-0040-rockchip-dts.patch, scripts/uboot_helper
- add the additional dts sections to 
- gpu
- tcs4525 and tcs4526 regulators
- disable the VOP_LIT (Video Output Processor - Little)
- enable i2s2
- enable hdmi_sound
- add gpio/rst/slp
- enable uart2 for serial console
- rockchip - regulator: fan53555: Add TCS4525 DCDC support
- Peter Geis
- regulator: fan53555: fix TCS4525 voltage calulation
- regulator: fan53555: only bind tcs4525 to correct chip id
- regulator: fan53555: fix tcs4525 function names
- @heitbaum - add TCS4526 as used by rk3399pro - vdd_gpu: tcs4526
- update the uboot_helper to include the additional rock-pi-n10 section
- update release to copy pro files in addition of RK3399
- update README
- run tested with LE10b3
- run tested with LE10b3 + 5.10.40 - http://ix.io/3nRY
- run tested with LE10b3 + 5.12.7
=> Rockchip: RK3399pro: add initial support for “Radxa ROCK Pi N10”

packages/readme.md, scripts/extract
Some archive do not include a top level directory.
By this new var the user is able to disable `strip-components` from `TAR_OPTS`.
=> scripts/extract: add option 'PKG_TAR_STRIP_COMPONENTS'

projects/Allwinner/patches/linux/0061-ARM-dts-sun8i-h3-orangepi-plus-Fix-ethernet-phy-mode.patch
=> Allwinner: linux: fix OrangePi Plus ethernet

packages/tools/crust/package.mk
This update fixes resume reliability issues and lowers power consumption in standby. Tested on PineH64 model B.
=> crust: update to v0.4

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
bump to https://github.com/LibreELEC/brcmfmac_sdio-firmware/commit/3ddc301c272f081aa5513c1934f6d530bf80de4a
=>  brcmfmac_sdio-firmware: bump to 3ddc301c272f

projects/Allwinner/devices/H5/patches/u-boot/0001-OrangePi-PC2-Update-defaults.patch
After double checking BSP values, original ZQ value is correct, so drop this change. Other changes are correct though and in process of upstreaming.
=> Allwinner: H5: u-boot: Fix OrangePi PC2 config

config/functions, projects/ARM/devices/ARMv8/options, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H5/options, projects/Allwinner/devices/H6/options, projects/Amlogic/devices/AMLGX/options, projects/NXP/devices/iMX8/options, projects/Qualcomm/devices/Dragonboard/options, projects/Rockchip/devices/RK3328/options, projects/Rockchip/devices/RK3399/options, scripts/unpack
While testing https://github.com/LibreELEC/LibreELEC.tv/pull/5422, I wondered why this change doesn't work on RK3328. It turns out, it couldn't work, because the glibc patches weren't applied for this device.
Thats because AML/AW/iMX8/Qualcomm/RK projects are using split configs for aarch64 devices, i.e. aarch64 kernel with arm userspace and the unpack script checks for `TARGET_PATCH_ARCH` when trying to figure out the `PATCH_ARCH` for any package.
These glibc patches are using (the correct) arm patches subdirectory, but those split-config project/devices are specifing `TARGET_PATCH_ARCH=aarch64`, which actually defines the the kernel (-drivers, u-boot etc.) patch arch. 
This introduces the new `TARGET_KERNEL_PATCH_ARCH` and replaces `TARGET_PATCH_ARCH` in the options of those devices (it …
=> buildsystem: introduce TARGET_KERNEL_PATCH_ARCH

packages/mediacenter/LibreELEC-settings/package.mk
partly fixes BT at the settings addon
=> LibreELEC-settings: update to caee341

packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
I used `tools/mkpkg/update_binary-addons` to update binary tools. Changes:
* **pvr.waipu** (2.8.4-Matrix -> 2.9.0-Matrix)
* Internal session handling changes (Handle expire date of JWT for several tokens)
*  support Waipu device_id, to identify a device and prevent other device from being logged out
=> Update binary addons

packages/addons/service/mpd/changelog.txt, packages/addons/service/mpd/package.mk, packages/audio/wavpack/package.mk
include wavpack as a dependency
- update mpd 0.22.6 to 0.22.9
- wavpack fix includedir 
Ref: https://forum.libreelec.tv/thread/24193-raspberry-pi-4-libreelec-music-player-daemon-wavpack-dsd-fail/?postID=157364#post157364
=> mpd: update to 0.22.9 and addon (111)

tools/refresh-patches
A leftover from https://github.com/LibreELEC/LibreELEC.tv/pull/5431
I missed to check tools - there should be no further cases now:
```
~/LibreELEC.tv$ grep -r TARGET_PATCH_ARCH
tools/refresh-patches:  PATCH_ARCH="${TARGET_PATCH_ARCH:-${TARGET_ARCH}}"
scripts/unpack:      PATCH_ARCH="${TARGET_PATCH_ARCH:-${TARGET_ARCH}}"
```
=> tools: refresh-patches: fix PATCH_ARCH

packages/mediacenter/kodi/scripts/kodi-config
This is necessary for script.module.inputstreamhelper addon to detect that the glibc package already contains the [TLS 64-byte alignment](https://github.com/LibreELEC/LibreELEC.tv/commit/5ce550c35407a8b20af0fce094b163695be64e9e#diff-246ec78884f9e3f4631cd12faacde7f0bfcbf7c16824b02791f573c3bb095ce6) patch.
References:
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/457
=> [LE 10] add LIBC_WIDEVINE_PATCHLEVEL environment variable to kodi config

packages/devel/glibc/package.mk, packages/mediacenter/kodi/scripts/kodi-config
This is necessary for script.module.inputstreamhelper addon to detect that the glibc package already contains the [TLS 64-byte alignment](https://github.com/LibreELEC/LibreELEC.tv/commit/16921614dcb206d53e78b654c60a1e06e8e72f25#diff-246ec78884f9e3f4631cd12faacde7f0bfcbf7c16824b02791f573c3bb095ce6) patch.
References:
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/457
=> [LE 9.2] add LIBC_WIDEVINE_PATCHLEVEL to kodi config and fix aarch64 patchload from arm

packages/addons/tools/dotnet-runtime/changelog.txt, packages/addons/tools/dotnet-runtime/package.mk
update 3.1.10 (2020-11-10) to 3.1.16 (2021-06-08)
release notes:
- 3.1.11 (security) - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.11/3.1.11.md
- 3.1.12 (security) - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.12/3.1.12.md
- 3.1.13 (security) - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.13/3.1.13.md
- 3.1.14 - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.14/3.1.14.md
- 3.1.15 (security) - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.15/3.1.15.md
- 3.1.16 (security) - https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.16/3.1.16.md
```
1448 root      0:03 dotnet /storage/.kodi/addons/service.emby4/libs/system/EmbyServer.dll -programdata /storage/.kodi/userdata/addon_data/service.emby4 …
```
=> dotnet-runtime: update to 3.1.16

packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk, packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk, packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/addon-depends/system-tools-depends/vim/package.mk, packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
Updates:
- network-tools: update to 110
- system-tools: update to 123
Packages:
- libpcap: update to 1.10.1
- stress-ng: update to 0.12.11
- tcpdump: update to 4.99.1
- unrar: update to 6.0.7
- vim: update to 8.2.3095
=> network-tools and system-tools updates

packages/debug/strace/package.mk
Noteworthy changes in strace 5.12 (2021-04-26)
Improvements
- Implemented --secontext[=full] option to display SELinux contexts.
- Implemented decoding of mount_setattr syscall introduced in Linux 5.12.
- Updated decoding of IFLA_BRPORT_* netlink attributes to match Linux 5.12.
- Updated lists of DEVCONF_*, IORING_*, KVM_*, MPOL_*, MTD_*, NFT_MSG_*, RESOLVE_*, RTM_*, ST_*, and V4L2_* constants.
- Updated lists of ioctl commands from Linux 5.12.
Bug fixes
- Fixed build using bionic libc.
Portability
- Added binutils 2.36 support to --enable-mpers builds.
=> strace: update to 5.12

packages/addons/service/syncthing/changelog.txt, packages/addons/service/syncthing/package.mk
Release notes: 
- https://github.com/syncthing/syncthing/releases/tag/v1.17.0
Update from 1.16.1 (2021-05-05) to 1.17.0 (2021-06-02)
=> syncthing: update to 1.17.0 and addon (117)

packages/addons/addon-depends/libconfig/package.mk
This PR fixes the call on the build server to rebuild .texi files. This matches the functionality of 1.7.2 - but uses the --disable-doc syntax, instead of the patch.
=> libconfig: disable build of doc and tests

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, projects/RPi/devices/RPi4/config/distroconfig.txt
Updated kernel and firmware now correctly release the firmware-allocated framebuffer when KMS takes over and we can drop the temporary workaround
=> linux (RPi): update to 5.10.46-69b899c

projects/Allwinner/devices/H3/patches/linux/0001-HACK-SW-CEC-implementation-for-H3.patch
This PR fixes H3 build failure after recent Linux update to 5.10.47.
=> Allwinner: H3: linux: Fix CEC patch

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
https://github.com/xbmc/inputstream.adaptive/releases/tag/2.4.8-Leia
=> inputstream.adaptive: bump to 2.4.8-Leia

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Update CYW43455 bluetooth firmware:
Second Spectra fix for CYW43455 (CVE-2020-10370)
=> brcmfmac_sdio-firmware-rpi: update to 883b726

packages/emulation/libretro-picodrive/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.picodrive/package.mk
The PicoDrive was removed by ba5db73131f35d7d58ba5d68fbe86cc6b51bd410 due to the "missing upstream files".
I'd like to get it back so I reverted it, updated it to the latest version and changed the source URL from https://github.com/libretro/picodrive/ to https://github.com/kodi-game/picodrive/ which seems to have fixed the missing file.
It seems to build fine again but there is a runtime error on ARM platforms which I'd like to fix as well. This runtime error was there for a long time before the package removal:
`ERROR: AddOnLog: Sega - MS/MD/CD/32X (PicoDrive): Unable to load: /storage/.kodi/addons/game.libretro.picodrive/game.libretro.picodrive.so: unexpected reloc type 0x03
`
I've found a reference to the same error but the solution is not explained here: …
=> libretro-picodrive: revert PicoDrive removal

packages/graphics/bcm2835-driver/package.mk, packages/tools/bcm2835-bootloader/package.mk
This fixes non-working USB on RPi4 rev 1.4 as reported on the forum https://forum.libreelec.tv/thread/24284-no-usb-on-rpi-4-after-upgrading-to-le10-rc1/
=> RPi: update to firmware 775e6a7

projects/RPi/devices/RPi4/config/distroconfig.txt
Enabling 4kp60 by default was premature, we got a report that TV shows "no signal" after putting it into standby in 4kp50/60 modes - which isn't great as 4kp60 is the default GUI mode on fresh installations with 4k TVs and 4kp60 enabled.
So better leave 4kp60 disabled for now, we can revisit this topic later again when the issues are resolved.
Also see https://forum.libreelec.tv/thread/24279-pi4-no-screen-after-turning-tv-off-and-on-in-4k-50hz-or-4k-60hz/ and https://github.com/raspberrypi/linux/issues/4486
=> Revert "RPi4: make 4kp60 enabled per default"

packages/graphics/lcms2/package.mk, packages/graphics/libraw/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.raw/package.mk
- forum bug raised.
- https://forum.libreelec.tv/thread/22435-libraw-image-decoder-not-working/?postID=158474#post158474
- lcms2 was compiled as shared and libraw was linking against the shared library and consequently imagedecoder.raw.so.3.0.1 was dependant on liblcms2.so.2
Referenced in bug #5524 
**ldd looks correct now**
```
nuc11:/var/media/DATA/home-rudi/LibreELEC.tv # ldd build.LibreELEC-Generic.x86_64-10.0-devel/addons/imagedecoder.raw:target/imagedecoder.raw/imagedecoder.raw.so.3.0.1
linux-vdso.so.1 (0x00007ffcabbdf000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f9e352f5000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f9e351b4000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9e3519a000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f9e34fe2000)
/usr/lib64/ld-linux-x86-64.so.2 …
```
=> imagedecoder.raw: link against static lcms2

packages/addons/addon-depends/librespot-depends/rust/package.mk, packages/addons/addon-depends/system-tools-depends/bottom/package.mk, packages/addons/service/librespot/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
PR that fixes the rust TARGET=HOST build issues
- librespot: fix build where TARGET=HOST with rust 1.54
-  system-tools: update to (124)
- bottom: fix build where TARGET=HOST with rust 1.54
- rust: use nightly until 1.54 is released
this was tested with **nightly-x86_64-unknown-linux-gnu installed - rustc 1.55.0-nightly (ce1d5611a 2021-06-18)**
no planned to be pulled into master until 1.54 is released - 29th July 2021
- https://github.com/rust-lang/rust/pull/85926 (cargo update)
- https://github.com/rust-lang/cargo/pull/9322 (patch to cargo)
- https://github.com/rust-lang/cargo/issues/9453 (Tracking issue)
- https://github.com/rust-lang/rust/milestone/82?closed=1 (1.54 milestone)
- https://doc.rust-lang.org/nightly/cargo/reference/unstable.html?highlight=feature#target-applies-to-host
- …
=> Update rust resolving TARGET=HOST build issues 

packages/network/wireguard-tools/package.mk
Minor bump to wireguard-tools. I've been using this in private images for several months.
=> wireguard-tools: bump to v1.0.20210424

scripts/genbuildplan.py
Fixes a small typo, causing the original error to not be displayed.
=> genbuildplan: fix typo in circular dep. detection

packages/addons/addon-depends/containerd/package.mk, packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/go/patches/go-0001-add-ca-cert-location.patch, packages/addons/addon-depends/libnetwork/package.mk, packages/addons/service/docker/package.mk
GO111MODULE set to "off" for libnetwork / containerd/ docker because old go sources need this to continue compiling.
https://maelvls.dev/go111module-everywhere/
=> go: update to 1.16.6

packages/mediacenter/kodi/scripts/pastekodi, packages/sysutils/busybox/system.d/storage-log.service, packages/sysutils/busybox/system.d/var-log.mount, packages/sysutils/systemd/package.mk
Part of system integration of #5526 suggested by @chewitt 
Allow Settings Addon to enable the existing persistent log feature of the LE "debugging" option and add possibility to configure journald.
Implement simple log rotate to avoid unlimited growing of logs.
For the user interface LibreELEC/service.libreelec.settings#233 is required but this PR can be committed any time and the Settings Addon bumped later.
=> systemd/busybox: allow configuration of persistent logs and journal

packages/network/connman/package.mk, packages/network/connman/patches/connman-01-do-not-cleanup-routes.patch, packages/network/connman/patches/connman-04-ipv6-disabled-by-default.patch, packages/network/connman/patches/connman-05_link-against-ncurses.patch
Update of githash to release incorporating post 1.39 patches that were necessary bugfixes.
- patches post 1.40 do not look applicable
- tidy up of patches (fuzz)
=> connman: update to 1.40

packages/sysutils/e2fsprogs/package.mk, packages/virtual/image/package.mk
Updates e2fsprogs to 1.45.7, which is a bugfix release: http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.45.7
1.46.x releases have already started. I don't intend on updating to that at this time.
This also moves diskdev_cmds (HFSTOOLS) out of a depend for e2fsprogs and as one for virtual/image.
Built and run tested on RPi3.
=> e2fsprogs: update to 1.45.7

packages/compress/zstd/package.mk, packages/compress/zstd/patches/zstd-999.01-build-fix.patch
Tested on Generic, RK, AML, RPi.
Release notes:
https://www.phoronix.com/scan.php?page=news_item&px=Zstd-1.4.9-Released
Patch:
https://github.com/facebook/zstd/pull/2548
=> zstd: update to 1.4.9 / add upstreamed build fix patch

packages/devel/glib/package.mk
glib: update to 2.68.1
updated 2.67.2 (8 Jan 2021) to 2.68.1 (8 Apr 2021)
changelog:
- https://raw.githubusercontent.com/GNOME/glib/master/NEWS
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.67.3
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.67.4
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.67.5
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.67.6
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.68.0
- https://gitlab.gnome.org/GNOME/glib/-/releases#2.68.1
=> glib: update to 2.68.1

packages/web/nghttp2/package.mk
Update 1.42.0 to 1.43.0
Changelog: https://github.com/nghttp2/nghttp2/releases/tag/v1.43.0
Announcement: https://nghttp2.org/blog/2021/02/02/nghttp2-v1-43-0/
=> nghttp2: update to 1.43.0

packages/sysutils/dosfstools/package.mk
update 4.1 (24 Jan 2017) to 4.2 (31 Jan 2021)
changelog: https://github.com/dosfstools/dosfstools/releases/tag/v4.2
=> dosfstools: update to 4.2

packages/python/security/pycryptodome/package.mk
update 3.9.9 (2020-11-02) to 3.10.1 (2021-02-09)
changelog: https://raw.githubusercontent.com/Legrandin/pycryptodome/master/Changelog.rst
=> pycryptodome: update to 3.10.1

packages/sysutils/busybox/config/busybox-host.conf, packages/sysutils/busybox/config/busybox-init.conf, packages/sysutils/busybox/config/busybox-target.conf
These are the minors split off of #5096.
Refresh of the busybox configs.
Dropping of pivot_root from busybox:init. Documentation for this says it's intended for linux 2.4 systems using initrd. init is using switch_root, which is intended for linux >=2.6 using initramfs.
=> Busybox minors

packages/security/nspr/package.mk, packages/security/nss/package.mk
nspr: update to 4.30 
nss: update to 3.64
- update 3.60.1 (04-Jan-2021) to 3.64 (15-Apr-2021)
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Releases
=> nss: update to 3.64 and nspr to 4.30

packages/devel/libcap/package.mk
update 2.46 to 2.49
logs: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/log/
releasenotes: https://sites.google.com/site/fullycapable/release-notes-for-libcap
=> libcap: update to 2.49

packages/devel/heimdal/patches/c4cff6859d183a40fb35a76e2bc1ce084b3a6d67.patch, packages/devel/heimdal/patches/cc6a3f337bac0411d0bb1c924fd857603a258d2f.patch
Add the patches to allow heimdal to be build by automake 1.16+
Note we are not using automake 1.16 yet.
=> heimdal: add patches for automake 1.16+

packages/linux-firmware/intel-ucode/package.mk
update 20201118 to 20210608
skipped 20210216 as it was only relevant to Server chips.
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20210608
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20210216
Testing:
- Skylake SKL i5-6260U (6th Gen)
- was:
- [    0.000000] microcode: microcode updated early to revision 0xe2, date = 2020-07-14
- [    1.550067] microcode: sig=0x406e3, pf=0x40, revision=0xe2
- is:
- [    0.000000] microcode: microcode updated early to revision 0xea, date = 2021-01-25
- [    1.609035] microcode: sig=0x406e3, pf=0x40, revision=0xea
- Tigerlake TGL i7-1165G7 (11th Gen)
- was:
- [    2.223390] microcode: sig=0x806c1, pf=0x80, revision=0x72
- is:
- [    0.000000] …
=> intel-ucode: update to 20210608

config/functions, config/show_config, tools/viewconfig
First commit kicks running `config/show_config` directly into its own script, `tools/viewconfig`. The show_config trick stopped working for me at some point, and I probably should have made it a standalone script when I put it in.
The last known user of `fix_module_depends` was dvbhdhomerun, which was removed from the tree in 2019, and stopped being built in 2016 for being broken, and 2013 before that. (`git log -S fix_module_depends` && `git grep fix_module_depends`).
=> Buildsystem minor cleanups

packages/lang/Python3/package.mk
**This is the final regular bugfix release of Python 3.8**
Run tested on x86_64 TGL and AMLG12
update 3.8.9 (2021-04-02) to 3.8.10 (2021-05-03)
changelog: https://docs.python.org/release/3.8.10/whatsnew/changelog.html
This is the final regular bugfix release of Python 3.8. Security
releases will follow until October 2024. Release schedule can be found
at https://www.python.org/dev/peps/pep-0569/
Update URLs to https inline with HSTS policy of python.org.
=> Python3: update to 3.8.11 and HSTS

packages/network/openssh/package.mk
update 8.5p1 (2021-03-03) to 8.6p1 (2021-04-19)
release notes: http://www.openssh.com/txt/release-8.6
This release contains mostly bug fixes.
=> openssh: update to 8.6p1

packages/lang/gcc/package.mk
Build & run tested on Generic (APL/SKL), Rockchip (RK3399) & Amlogic (AMLG12B)
>GCC 10.3 is a bug-fix release from the GCC 10 branch
containing important fixes for regressions and serious bugs in
GCC 10.2 with more than 178 bugs fixed since the previous release.
- https://www.phoronix.com/scan.php?page=news_item&px=GCC-10.3-Released
=> gcc: update to 10.3.0 / updated license short identifier

packages/sysutils/systemd/package.mk
update 247.3 (2021-02-03) to 247.7 (2021-05-16)
diffs: https://github.com/systemd/systemd-stable/compare/v247.3...v247.4
diffs: https://github.com/systemd/systemd-stable/compare/v247.4...v247.5
diffs: https://github.com/systemd/systemd-stable/compare/v247.5...v247.6
diffs: https://github.com/systemd/systemd-stable/compare/v247.6...v247.7
prs: https://github.com/systemd/systemd-stable/pulls?q=is%3Apr+is%3Aclosed
logs: https://github.com/systemd/systemd-stable/commits/v247.7
I have been running 247.4 for 2 weeks. there isn’t anything specific I saw that is needed for LE10, but PR’ing if others note something worthy of committing now.
=> systemd: update to 247.7

packages/lang/llvm/package.mk
build & run tested with Mesa 21.0.y & 21.1.y-RC on SKL/APL
- https://www.phoronix.com/scan.php?page=news_item&px=LLVM-12.0-Released
=> llvm: updated to v12.0.0

packages/python/devel/setuptools/package.mk
- release history: https://pypi.org/project/setuptools/#history
- log: https://github.com/pypa/setuptools/compare/v51.1.2...v52.0.0
- change log: https://github.com/pypa/setuptools/blob/main/CHANGES.rst
**v53.0.0 Breaking Changes**
https://github.com/pypa/setuptools/issues/1527 
https://github.com/pypa/setuptools/pull/2543 
Removed bootstrap script. Now Setuptools requires pip or another pep517-compliant builder such as 'build' to build. Now Setuptools can be installed from Github main branch.
=> setuptools: update to 52.0.0

config/functions, packages/devel/glib/package.mk, packages/python/devel/meson/package.mk
I'm opening this PR to discuss a fix for glib failing to build on a docker container on an aarch64 device for other ARM based devices.
This combination fails after the last meson bump, due to several issues converging.
1. The current implementations of `create_meson_conf_host` and `create_meson_conf_target` are outdated, and use deprecated labels.
2. The `PKG_MESON_PROPERTIES_TARGET` variable in glib package has no effect, ~~as in older meson these options were never even picked up, and in meson 0.56.0 you get a warning about them being unsupported.
`WARNING: Unknown options: "growing_stack, have_c99_snprintf, have_c99_vsnprintf, root, va_val_copy"`~~
3. This commit: https://github.com/mesonbuild/meson/commit/cc201a539674babf46f726859587afb5ed6a6867 introduced in meson 0.56.0 causes the …
=> Update build system for new meson and fix up glib package

scripts/get_git
The script originally looked at every file AND folder in the sources folder, which is incorrect and causes unintentional deletion of archive files. After the fix the script checks only folders.
=> get_git: check only folder, not files

packages/devel/glibc/package.mk, packages/sysutils/busybox/package.mk, packages/sysutils/busybox/profile.d/10-locale.conf, packages/sysutils/busybox/system.d/locale.service
Normally Locale addon must be installed but users don't know that. Simplify this with adding default C.UTF-8 locale in image. Users can still install Locale addon to use some other locale.
fixes Python3 error
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-41: ordinal not in range(128)`
like
https://github.com/croneter/PlexKodiConnect/issues/1447
https://forum.libreelec.tv/thread/23116-pvr-recorder-unsuppored-locale/?postID=147453
from Kodi Python
before
```
sys.getdefaultencoding(): utf-8
sys.getfilesystemencoding(): ascii
```
after
```
sys.getdefaultencoding(): utf-8
sys.getfilesystemencoding(): utf-8
```
from SSH console
before
```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX" …
```
=> glibc: include C.UTF-8 locale in image

packages/sysutils/busybox/scripts/init
This stops LE's update checker from accepting OE images as system updates. The checker may be disabled if someone wants to do this. LE stopped generating OPENELEC_ARCH in its images in May 2019 (#3026).
=> init: stop checking for OPENELEC_ARCH

config/functions
Update check_toolchain_config to use CMAKE variables when using CMAKE-MAKE, the same logic as AUTOTOOLS and CONFIGURE
=> toolchain: enable correct handling of cmake-make in check_toolchain_config

packages/devel/binutils/package.mk
Moving from my NUC6 to a NUC11 as a build host / Kodi test binutils fails to compile (and I believe it is a parallel issue)
This is the error log 
- http://paste.ubuntu.com/p/VYSv72W6CF/ 
- lines 3668-3676
- `/usr/bin/ld: cannot find -lbfd`
If I execute `PROJECT=Generic ARCH=x86_64 make image` a second time it finishes the build.
the patch attached fixes the dependancy. Not sure if it is the right way, but happy to take a direction to resolve.
the details of the build host below (old was Skylake 4 CPU, new Tiger Lake 8 CPU)
```
$ rm -rf build.LibreELEC-Generic.x86_64-9.80-devel/
$ PROJECT=Generic ARCH=x86_64 make image
...
Total Build Time: 01:09:06.950 (wall clock)
Accum Build Time: 09:12:55.500 (8 slots)
Breakdown by status (all slots):
Status   Usage         ( Pct )  Count  State …
```
=> binutils: fix parallel build with libctf requiring bfd

packages/mediacenter/kodi/package.mk
without -DENABLE_SMBCLIENT=xx the kodi build will include smbclient if it finds it, or will fail if it doesn't. This define should be set so as to match the intention of the KODI_SAMBA_SUPPORT setting.
=> kodi: honour KODI_SAMBA_SUPPORT variable

config/functions, packages/compress/zstd/package.mk, scripts/checkdeps, scripts/extract, tools/docker/bionic/Dockerfile, tools/docker/buster/Dockerfile, tools/docker/focal/Dockerfile, tools/docker/groovy/Dockerfile, tools/docker/hirsute/Dockerfile, tools/docker/sid/Dockerfile, tools/docker/stretch/Dockerfile
This adds support for packages packed in .tar.zst's. The zstdcat | tar approach is used to be compatible with older versions of tar (<1.32, iirc). Thus far, I've only found zstd itself packed in such a tarball.
Also cleans up scripts/extract some.
=> scripts/extract: cleanup and add support for zstd tarballs

packages/web/curl/package.mk
curl: update to 7.78.0 and HSTS
update 7.74.0 (2020-12-09) to 7.78.0 (2021-07-21)
changelog:
- https://curl.se/changes.html#7_78_0
- https://curl.se/changes.html#7_77_0
- https://curl.se/changes.html#7_76_1
- https://curl.se/changes.html#7_76_0
- https://curl.se/changes.html#7_75_0
metalink removed: https://github.com/curl/curl/pull/7176
=> curl: update to 7.78.0 and HSTS

packages/debug/libva-utils/package.mk, packages/graphics/libdrm/package.mk, packages/multimedia/gmmlib/package.mk, packages/multimedia/libva/package.mk, packages/multimedia/media-driver/package.mk
Update to latest libva and Intel media driver to match and support Mesa #5358 
- gmmlib: update to 21.2.1 from 21.1.2
- libdrm: update to 2.4.107 from 2.4.106
- libva: update to 2.12.0 from 2.11.0
- libva-utils: update to 2.12.0 from 2.11.1
- media-driver: update to 21.3.1 from 21.1.3
PR fixes over enthusiastic bump of Mesa to 21.2
```
Run-time dependency libdrm_intel found: NO (tried cmake)
../meson.build:1557:4: ERROR: Invalid version of dependency, need 'libdrm_intel' ['>=2.4.107'] found '2.4.106'.
```
Run tested extensively on TGL
=> media-driver: update to 21.3.1 and dependancies

packages/sysutils/systemd/package.mk
update from 247.7 (2021-05-16) to 247.9 (2021-08-07)
changelog:
- https://github.com/systemd/systemd-stable/compare/v247.7...v247.9
testing has been done with 248 and 249 in dev tree, having some Seg faults in init with RiscV (not sure on issue - but will hold that version till addressed / excluded)
=> systemd: update to 247.9

packages/addons/addon-depends/opus/package.mk, packages/multimedia/aom/package.mk
With recent updates to the build environment, both aom and opus require -fPIC to compile tvheadend42 and tvheadend43 successfully.
- aom: build with -fPIC
- opus: build with -fPIC
`
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.3.0/../../../../x86_64-libreelec-linux-gnu/bin/ld.gold: error: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libaom.a(av1_fwd_txfm1d_sse4.c.o): requires unsupported dynamic reloc 11; recompile with -fPIC
`
`
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.3.0/../../../../x86_64-libreelec-linux-gnu/bin/ld.gold: error: …
=> build with -fPIC: aom and opus

packages/linux/package.mk
With the latest kernels - the following error is displayed instead of the no-op.
```
...
BUILD      linux (host)
TOOLCHAIN      make (auto-detect)
make[1]: Entering directory LibreELEC.tv/build.LibreELEC- ...
=================== WARNING ===================
Since Linux 5.5, 'make headers_check' is no-op,
and will be removed after Linux 5.15 release.
Please remove headers_check from your scripts.
===============================================
...
```
=> linux: remove make headers_check

packages/lang/gcc/patches/gcc-libsanitiser.patch
GCC 10.2 needs a patch (https://www.mail-archive.com/gcc@gcc.gnu.org/msg95386.html) to avoid failing with a missing header when building against newer kernels due to removal of cyclades support (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux?h=v5.12&id=f76edd8f7ce06cdff2fe5b6b39a49644c684a161). The patch can be dropped in a future package bump.
Build and boot tested with RPi4 (5.10.x) and Amlogic (5.14-rc4) images.
=> gcc: add libsanitiser patch for 5.12+ kernels

packages/mediacenter/kodi-binary-addons/audiodecoder.2sf/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.fluidsynth/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.gsf/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.ncsf/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.nosefart/package.mk, packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
- audiodecoder.2sf: update 19.0.0-Matrix to 19.0.1-Matrix
- audiodecoder.fluidsynth: update 3.0.0-Matrix to 19.0.0-Matrix
- audiodecoder.gsf: update 3.0.0-Matrix to 19.0.0-Matrix
- audiodecoder.ncsf: update 3.0.0-Matrix to 19.0.0-Matrix
- audiodecoder.nosefart: update 3.0.0-Matrix to 19.0.0-Matrix
- pvr.demo: update 7.1.4-Matrix to 7.1.5-Matrix
LE10 - #5575
=> kodi-binary-addons: update to latest versions (LE11)

packages/sysutils/parted/package.mk
**discovered this issue whilst bringing up RiscV but issue occurring on all**
First assumuption of the PATH not working was proved wrong. The actual issue was that `parted:init` when INITRAMFS_PARTED_SUPPORT is set to "yes" would not allow the link `ln -sfn /usr/sbin ${INSTALL}/sbin`
~~_PATH was set to include /usr/sbin, but not honoured without specifying as below._~~
~~The fsck step in init fails as fsck.ext4 can't be found.
Update the script to set the path for fsck to PATH=/usr/sbin~~
~~This fixes the below error.~~
~~```~~
~~+/usr/sbin/fsck -T -M -p -a 'UUID=1408-4055' 'UUID=01c82ea0-a853-4848-aa03-cb8702e48869'~~
~~+FSCK_RET=8~~
~~+cat /dev/fsck.latest~~
~~+'[' 8 -ge 16 ]~~
~~+'[' 8 -eq 8 ]~~
~~+'[' 0 -eq 0 ]~~
~~```~~
~~`[   22.919572] fsck: fsck: error 2 (No such file or …
=> parted: update that if INITRAMFS_PARTED_SUPPORT is set to "yes" then files are placed in /usr/sbin

packages/sysutils/parted/package.mk
Backport of #5566 
**discovered this issue whilst bringing up RiscV but issue occurring on all**
The issue is that `parted:init` when INITRAMFS_PARTED_SUPPORT is set to "yes" would not allow the link `ln -sfn /usr/sbin ${INSTALL}/sbin` to be created as the /sbin directory already existed with the `parted` and `partprobe` files in it.
=> parted: update parted:init to use /usr/sbin

packages/network/wireless-regdb/package.mk
update 2021.04.21 to 2021.08.28
Release notes:
2021-08-28: Released
2021-08-28 wireless-regdb: update regulatory database based on preceding changes
2021-08-27 Update regulatory rules for Ecuador (EC)
2021-08-06 wireless-regdb: Update regulatory rules for Norway (NO) on 6 and 60 GHz
2021-08-02 wireless-regdb: Update regulatory rules for Germany (DE) on 6GHz
2021-07-14: Released
2021-07-14 wireless-regdb: update regulatory database based on preceding changes
2021-07-14 wireless-regdb: reduce bandwidth for 5730-5850 and 5850-5895 MHz in US
2021-07-08 wireless-regdb: remove PTMP-ONLY from 5850-5895 MHz for US
2021-07-06 wireless-regdb: recent FCC report and order allows 5850-5895 immediately
2021-06-08 wireless-regdb: update 5725-5850 MHz rule for GB
=> wireless-regdb: update to 2021.08.28

packages/network/wireless-regdb/package.mk
update 2021.04.21 to 2021.08.28
Release notes:
2021-08-28: Released
2021-08-28 wireless-regdb: update regulatory database based on preceding changes
2021-08-27 Update regulatory rules for Ecuador (EC)
2021-08-06 wireless-regdb: Update regulatory rules for Norway (NO) on 6 and 60 GHz
2021-08-02 wireless-regdb: Update regulatory rules for Germany (DE) on 6GHz
2021-07-14: Released
2021-07-14 wireless-regdb: update regulatory database based on preceding changes
2021-07-14 wireless-regdb: reduce bandwidth for 5730-5850 and 5850-5895 MHz in US
2021-07-08 wireless-regdb: remove PTMP-ONLY from 5850-5895 MHz for US
2021-07-06 wireless-regdb: recent FCC report and order allows 5850-5895 immediately
2021-06-08 wireless-regdb: update 5725-5850 MHz rule for GB
Upstream is #5579
=> [le10] wireless-regdb: update to 2021.08.28

packages/mediacenter/kodi-binary-addons/audiodecoder.organya/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.heif/package.mk, packages/mediacenter/kodi-binary-addons/imagedecoder.mpo/package.mk, packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
- audiodecoder.organya: update 3.0.0-Matrix to 19.0.0-Matrix
- imagedecoder.heif: update 1.4.0-Matrix to 19.0.0-Matrix
- imagedecoder.mpo: update 2.0.1-Matrix to 19.0.0-Matrix
- pvr.filmon: update 6.1.2-Matrix to 6.1.3-Matrix
- pvr.iptvsimple: update 7.6.9-Matrix to 7.6.10-Matrix
- pvr.vuplus: update 7.4.9-Matrix to 7.4.11-Matrix
Downstream ref: #5584
=> [le11] kodi-binary-addons: update to latest versions

packages/multimedia/gmmlib/package.mk, packages/multimedia/media-driver/package.mk
Update media-driver and gmmlib
- media-driver: update to 21.3.2
- [Decode] MHW AVC Refactor
- This is a patch for mhw avc refactor, committing MFX and avc decode related cmds.
- https://github.com/intel/media-driver/compare/intel-media-21.3.1...intel-media-21.3.2
- gmmlib: update to 21.2.2
- Intel Graphics Memory Management Library 2021 Q2 Release 2.
- https://github.com/intel/gmmlib/compare/intel-gmmlib-21.2.1...intel-gmmlib-21.2.2
=> Update media-driver and gmmlib

packages/network/iwd/package.mk
update 1.11 (2021-01-07) to 1.17 (2021-08-22)
changelog: https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/ChangeLog
ver 1.17:
- Fix issue with sending additional and vendor IEs.
- Fix issue with IE ordering for 802.11-2020 support.
- Fix issue with frequency update on channel switch events.
- Fix issue with drivers and handling of IF_OPER_UP setting.
ver 1.16:
- Fix issue with writing provisioning files with a passphrase.
- Add support for Authenticator & Supplicant RSN Extension elements.
- Add support for handling Transition Disable info.
- Add support for SAE Hash-to-Element feature.
ver 1.15:
- Add support for FT-over-DS procedure with multiple BSS.
- Add support for estimation of VHT RX data rate.
- Add support for exporting Daemon information.
ver 1.14:
- Fix issue with …
=> iwd: update to 1.17

packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk, packages/network/libssh/package.mk
A security release has been issued for libssh. Update the vfs.sftp addon to use this updated package.
libssh security release:
- https://www.libssh.org/2021/08/26/libssh-0-9-6-security-release/
**libssh is only used by `vfs.sftp`**
```
packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk:PKG_DEPENDS_TARGET="toolchain kodi-platform libssh"
```
=> vfs.sftp: update PKG_REV to build with libssh-0.9.6

packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk, packages/network/libssh/package.mk
A security release has been issued for libssh. Update the vfs.sftp addon to use this updated package.
libssh security release:
- https://www.libssh.org/2021/08/26/libssh-0-9-6-security-release/
**libssh is only used by `vfs.sftp`**
```
packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk:PKG_DEPENDS_TARGET="toolchain kodi-platform libssh"
```
Upstream #5581
=> [le10] vfs.sftp: update PKG_REV to build with libssh-0.9.6

packages/addons/addon-depends/opus/package.mk, packages/multimedia/aom/package.mk
Backport of #5555 
Both aom and opus require -fPIC to compile tvheadend42 and tvheadend43 successfully.
- aom: build with -fPIC
- opus: build with -fPIC
`
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/../../../../x86_64-libreelec-linux-gnu/bin/ld.gold: error: /var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libaom.a(av1_dx_iface.c.o): requires unsupported dynamic reloc 11; recompile with -fPIC
`
issue due to: https://github.com/LibreELEC/LibreELEC.tv/pull/5488/commits/a27a0b96220e92fd2263f2027c8e685a6a1a0c78
=> [le10] build with -fPIC: aom and opus

packages/multimedia/media-driver/package.mk
intel-media-21.3.3: [VP] fix one HDR CSC return error about BT.709
- fix one HDR CSC return error about BT.709, driver can process BT.709 output, no need veboxpreprocess.
Thanks @smp79 
> The fix from https://github.com/LibreELEC/LibreELEC.tv/pull/5601/commits/a5c0a1d0875f160de96ac8fa32246909568a7a32 is now merged into [media-driver 21.3.3](https://github.com/intel/media-driver/compare/intel-media-21.3.2...intel-media-21.3.3)
#5591 / #5601
=> media-driver: update to 21.3.3

projects/Allwinner/patches/linux/0034-HACK-h3-h5-Add-HDMI-sound-card.patch
With Linux 5.14, HDMI audio stopped working on H3 and H5. It turns out that functions, used by I2S driver, require DMA for both directions. Until that's fixed upstream, add dummy RX DMA description (it won't be used anyway).
=> Allwinner: linux: Fix audio on 5.14 for H3 and H5

packages/network/samba/package.mk
update 4.13.9 to 4.13.11
release notes:
- https://www.samba.org/samba/history/samba-4.13.10.html
- https://www.samba.org/samba/history/samba-4.13.11.html
=> samba: update to 4.13.11

projects/Allwinner/patches/linux/0023-media-cedrus-add-check-for-H264-and-HEVC-limitations.patch
This again enables VP8 HW decoding on H6 after a mistake at patch rebase for kernel 5.14.
=> Allwinner: linux: fix Cedrus patch

projects/Allwinner/devices/H3/patches/linux/0001-HACK-SW-CEC-implementation-for-H3.patch, projects/Allwinner/patches/linux/0056-drm-sun4i-dw-hdmi-Fix-HDMI-PHY-clock-setup.patch
Currently there is no image on HDMI output until Kodi is started. That's because there is issue in HDMI driver and first mode set always fail on all LE supported SoCs, except H6.
This MR fixes driver bug (patch was send to dri-devel).
I'll provide LE10 backport as soon as I test fix there.
=> Allwinner: linux: Fix HDMI driver

packages/addons/addon-depends/network-tools-depends/depends/libstatgrab/package.mk, packages/addons/addon-depends/network-tools-depends/iperf/package.mk, packages/addons/service/mariadb/changelog.txt, packages/addons/service/mariadb/package.mk, packages/addons/service/minidlna/changelog.txt, packages/addons/service/minidlna/package.mk, packages/addons/service/minidlna/patches/minidlna-02-fix-autoconf-271.patch, packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk
- mariadb: update to 10.4.21 and addon (105)  …
- update from 10.4.18 (2021-02-22) to 10.4.21 (2021-08-06)
- release notes and changelog:
- https://mariadb.com/kb/en/changes-improvements-in-mariadb-104/
- minidlna: fix build with autoconf 2.71 and addon (103)
- network-tools: update addon (111)
- iperf: update to 3.10.1
- https://github.com/esnet/iperf/blob/master/RELNOTES.md
- http://software.es.net/iperf/news.html#iperf-3-10-1-released
- iperf 3.10 is principally a bugfix release.
- A few new features have been added (--time-skew-threshold, --bind-dev, --rcv-timeout, and --dont-fragment).
- More information on these new features can be found in the release notes.
- libstatgrab: update to 0.92.1
- https://libstatgrab.org/#current-version
- The current release is libstatgrab 0.92.1 …
=> Addon fixes from devtools update

packages/multimedia/gmmlib/package.mk
Intel Graphics Memory Management Library 2021 Q3 Release.
update 21.2.2 to 21.3.1
only 1 minor change: Generic fixes for Linear tiling selection (#65)
- https://github.com/intel/gmmlib/compare/intel-gmmlib-21.2.2...intel-gmmlib-21.3.1
=> gmmlib: update to 21.3.1

packages/addons/service/tvheadend43/changelog.txt, packages/addons/service/tvheadend43/package.mk
- update to latest
- fix missing library (only an issue on x86_64 systems)
- simplify x86_64 versus other architectures (no double negative)
Reported as:
- https://forum.libreelec.tv/thread/24511-tvheadend-4-3-doesn-t-start-on-todays-nightly-generic-20210912-85b190b/
- https://forum.libreelec.tv/thread/3416-tvheadend-nightly-builds-for-le/?postID=159651#post159651
- https://forum.libreelec.tv/thread/13738-intel-true-10bits-hevc-hdr-support/?postID=159889#post159889 (not related)
=> tvheadend43: update to 4.3-1979

packages/linux-drivers/mali-midgard/package.mk
Include the following fixes to compile with kernel 5.14
- struct mm_struct: update from mmap_sem to mmap_lock (5.7 --> 5.8)
- get_user_pages_remote: support kernel 5.9 (5.8 --> 5.9)
- add_mm_counter: update to support 5.5
- from https://forum.odroid.com/viewtopic.php?f=184&t=41300
=> mali-midgard: update to 055a545

scripts/get_archive
Allows to change just the commit hash at bumping a package. The hash of the downloaded file gets pushed to the package.mk after first download.
Background:
If you change the githash at a package and run scripts/build|unpack... you get an error message that the hash is wrong (obviusly). So you need to generate/copy the hash from the downloaded file and edit the package.mk to make it work. 
After the change you need to download it again.
Adding CHANGE_HASH to parameter or .libreelec allows to work at packages without manually changing file hashes and avoiding redownload the file again.
`PROJECT=Generic ARCH=x86_64 scripts/build kodi` -> `PROJECT=Generic ARCH=x86_64 CHANGE_HASH=yes scripts/build kodi`
=> scripts/get_archive: allow changing sha256 on the fly

tools/update-scan
Add update-scan tool to check PKG_VERSION of packages against release monitoring site. This tool currently uses Anitya from https://release-monitoring.org/ with the following distribution https://release-monitoring.org/distro/LibreELEC/
other potential backends that could be integrated are: 
- https://github.com/whohas/whohas
- https://repology.org/
- https://pkgs.org/
outstanding issues:
- api handle to Anitya includes alpha, beta and release candidates
- doesn’t take into account preferred release series
- Git logic could be improved
- cache is currently not enabled
- on api failure a blank field is returned, enable retry
=> update-scan: initial commit

packages/debug/gdb/package.mk, packages/debug/memtester/package.mk, packages/debug/strace/package.mk, packages/debug/valgrind/package.mk
Update debug tools
- gdb: update to 11.1
- memtester: update to 4.5.1
- strace: update to 5.14
- valgrind: update to 3.17.0
=> Update debug tools

config/options
This fixes building and calling into build scripts without PROJECT,
DEVICE and ARCH set.
=> config/options: default to Generic device when building Generic project

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk
This fixes console/splash not shown on HDMI0 if HDMI1 is connected https://github.com/raspberrypi/linux/issues/4540
=> [le11] linux (RPi): update to 5.10.63-a5d2df0

packages/graphics/mesa/package.mk
update 21.2.1 to 21.2.2
ann:
- https://lists.freedesktop.org/archives/mesa-dev/2021-September/225490.html
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.2/docs/relnotes/21.2.2.rst
=> mesa: update to 21.2.2

packages/lang/Python3/package.mk
update 3.8.11 (2021-06-28) to 3.8.12 (2021-08-30)
release notes: (security release)
- https://docs.python.org/release/3.8.12/whatsnew/changelog.html#changelog
release schedule:
- https://www.python.org/dev/peps/pep-0569/
=> Python3: update to 3.8.12

packages/network/ethtool/package.mk, packages/network/iwd/package.mk, packages/network/wireguard-tools/package.mk
Update kernel support network packages
- ethtool: update to 5.14 and HSTS
- iwd: update to 1.18
- wireguard-tools: update to 1.0.20210914
=> Update kernel support network packages

packages/debug/gdb/package.mk
GDB now needs libgmp, so it should be listed as a dependency. Additionally, when compiling for target, search path must be set in order for libgmp to be found.
This fixes build issue on Arch. It's unclear to me why other distros worked without this fix.
=> gdb: Add gmp dependency

projects/Allwinner/patches/linux/0057-HACK-Disable-MBUS-due-to-fw_devlink-on.patch
Add a (hacky) patch, which allows loading deinterlace drivers on all but H6 SoCs.
This fixes deinterlacing with current master branch (LE10 works correctly).
=> Allwinner: linux: workaround for deinterlace driver loading

projects/Allwinner/patches/linux/0058-WIP-OPi3-DT-fixes.patch
As discussed on forum (https://forum.libreelec.tv/thread/24344-orange-pi-3-irregular-system-freezing/), OrangePi 3 image is unstable. In some cases Kodi crashes without apparent reason. It was discovered that adjusting CPU voltage range in DT fixes this instability.
=> Allwinner: linux: Fix OrangePi 3 DT

packages/audio/fluidsynth/package.mk, packages/audio/fluidsynth/patches/libsndfile-use-static-libraries.patch, packages/audio/libsndfile/package.mk, packages/audio/libsndfile/patches/libsndfile-add-required-static-libaries-to-pkg-config.patch, packages/audio/soxr/package.mk
With recent kodi-binary-addons: update to latest versions `audiodecoder.fluidsynth: update 3.0.0-Matrix to 19.0.0-Matrix` #5575 the build fails due to new dependency on libgomp
refs: (Thanks @HiassofT)
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/192203d4756772b57ebfecbcc23f5f8007e16f37
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/2978ef181cfb925198c2237509425b95efd3b8a3
Build fails with:
```
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-ARMv7/LibreELEC.tv/build.LibreELEC-ARMv7.arm-11.0-devel/toolchain/lib/gcc/armv7a-libreelec-linux-gnueabihf/10.3.0/../../../../armv7a-libreelec-linux-gnueabihf/bin/ld.gold: error: cannot find -lgomp
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FAILURE: scripts/build …
```
=> [le10] fluidsynth: update to 2.2.3 and use with audiodecoder.fluidsynth 19.0.1-Matrix

packages/audio/fluidsynth/package.mk, packages/audio/fluidsynth/patches/libsndfile-use-static-libraries.patch, packages/audio/libsndfile/package.mk, packages/audio/libsndfile/patches/libsndfile-add-required-static-libaries-to-pkg-config.patch, packages/audio/soxr/package.mk
Master update of #5583
With recent kodi-binary-addons: update to latest versions `audiodecoder.fluidsynth: update 3.0.0-Matrix to 19.0.0-Matrix` #5575 the build fails due to new dependency on libgomp
refs: (Thanks @HiassofT)
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/192203d4756772b57ebfecbcc23f5f8007e16f37
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/2978ef181cfb925198c2237509425b95efd3b8a3
Build fails with:
```
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-ARMv7/LibreELEC.tv/build.LibreELEC-ARMv7.arm-11.0-devel/toolchain/lib/gcc/armv7a-libreelec-linux-gnueabihf/10.3.0/../../../../armv7a-libreelec-linux-gnueabihf/bin/ld.gold: error: cannot find -lgomp
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FAILURE: …
```
=> [le11] fluidsynth: update to 2.2.3 and use with audiodecoder.fluidsynth 19.0.1-Matrix

packages/addons/addon-depends/snapcast-depends/shairport-sync/package.mk, packages/addons/addon-depends/snapcast-depends/shairport-sync/patches/fix-libsnfile-dependencies.patch, packages/audio/libsndfile/patches/libsndfile-add-required-static-libaries-to-pkg-config.patch
- shairport-sync: update to using pkg-config
- libsndfile: reorder static libraries
Issue due to static libraries not being included 
Upstreamed PR: https://github.com/mikebrady/shairport-sync/pull/1303
=> shairport-sync: update the build to use pkg-config

packages/network/samba/package.mk
update 4.13.9 to 4.13.11
release notes:
- https://www.samba.org/samba/history/samba-4.13.10.html
- https://www.samba.org/samba/history/samba-4.13.11.html
=> [le10] samba: update to 4.13.11

packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/network/rsync/package.mk, packages/network/rsync/patches/0001-Work-around-glibc-s-lchmod-issue-a-better-way.patch
Fixes #5675, which is a regression introduced by glibc implementation of lchmod.  It appears that glibc is more or less waiting on a new syscall from the kernel to fix it properly, until then lchmod is broken when /proc is not mounted.
Tested on LE10 using rsync.conf:
```
list = yes
port = 873
log file = /storage/rsyncd.log
timeout = 300
[Synology3_Backup]
comment = Synology3 Video Backup
path = /tmp/test
max connections = 0
read only = false
hosts allow = 192.168.0.1
uid = root
gid = root
```
And running rsync as daemon:
```
mkdir -p /tmp/test
rsync --daemon --config=/storage/rsync.conf
```
And on remote server pushing a directory:
```
rsync -avWH ~/py3/ rsync://libreelec/Synology3_Backup/
```
Permissions should be set on folder structure under /tmp/test.
=> [LE11] rsync: add lchmod workaround patches

packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk, packages/network/rsync/package.mk, packages/network/rsync/patches/0001-Work-around-glibc-s-lchmod-issue-a-better-way.patch
Fixes #5675, which is a regression introduced by glibc implementation of lchmod.  It appears that glibc is more or less waiting on a new syscall from the kernel to fix it properly, until then lchmod is broken when /proc is not mounted.
Tested on LE10 using rsync.conf:
```
list = yes
port = 873
log file = /storage/rsyncd.log
timeout = 300
[Synology3_Backup]
comment = Synology3 Video Backup
path = /tmp/test
max connections = 0
read only = false
hosts allow = 192.168.0.1
uid = root
gid = root
```
And running rsync as daemon:
```
mkdir -p /tmp/test
rsync --daemon --config=/storage/rsync.conf
```
And on remote server pushing a directory:
```
rsync -avWH ~/py3/ rsync://libreelec/Synology3_Backup/
```
Permissions should be set on folder structure under /tmp/test.
=> [LE10] rsync: add lchmod workaround patches

packages/x11/other/fontconfig/conf.d/05-kodi-fonts.conf, packages/x11/other/fontconfig/package.mk
This is no longer needed as kodi Matrix/Nexus already make
.kodi/media/Fonts available to libass.
Large collections of fonts should better be stored in the default
XDG_DATA_HOME fonts location of fontconfig (/storage/.local/share/fonts)
though to avoid slow movie startup and kodi potentially running out
of memory as kodi/libass will load all fonts from .kodi/media/Fonts
into RAM. Making the fonts available to libass via fontconfig avoids
this issue.
=> fontconfig: remove kodi's font folder from fontconfig dirs

packages/addons/service/tvheadend43/changelog.txt, packages/addons/service/tvheadend43/package.mk
Upstream is #5623 
- update to latest
- fix missing library (only an issue on x86_64 systems)
- simplify x86_64 versus other architectures (no double negative)
Reported as:
- https://forum.libreelec.tv/thread/24511-tvheadend-4-3-doesn-t-start-on-todays-nightly-generic-20210912-85b190b/
- https://forum.libreelec.tv/thread/3416-tvheadend-nightly-builds-for-le/?postID=159651#post159651
- https://forum.libreelec.tv/thread/13738-intel-true-10bits-hevc-hdr-support/?postID=159889#post159889 (not related)
=> [le10] tvheadend43: update to 4.3-1979

packages/mediacenter/kodi-binary-addons/audiodecoder.sacd/package.mk
- audiodecoder.sacd: update 0.1.2-Matrix to 19.0.0-Matrix
=> [le10] kodi-binary-addons: update to latest versions

packages/addons/addon-depends/system-tools-depends/mtpfs/package.mk, packages/emulation/libretro-pcsx-rearmed/package.mk, packages/linux-driver-addons/dvb/depends/media_tree/package.mk, packages/linux-driver-addons/dvb/depends/media_tree_cc/package.mk, packages/linux/package.mk, packages/wayland/weston/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk, tools/packages-checker
This adds removal of trailing whitespace to the tasks `tools/packages-checker` does. It also makes a list of the checks it does, and has the current output of the script on the packages tree.
=> packages-checker: remove trailing whitespace

packages/multimedia/media-driver/package.mk
Minor updates
[VP] Fix regression which caused by #1229
Fix regression:libva conformance failures since #1229
Release notes: https://github.com/intel/media-driver/releases/tag/intel-media-21.3.4
=> media-driver: update to 21.3.4

packages/addons/service/librespot/changelog.txt, packages/addons/service/librespot/package.mk, packages/addons/service/librespot/source/resources/language/English/strings.po, packages/addons/service/librespot/source/resources/lib/ls_addon.py, packages/addons/service/librespot/source/resources/lib/ls_librespot.py, packages/addons/service/librespot/source/resources/settings.xml
Running librespot behind a firewall requires a predefined port for Spotify Connect. This PR adds a new setting to set the "Connect Port", keeping the default value of '0' falls back to the current behavior (automatic port assignment).
=> librespot: add new setting for zerconf port

packages/mediacenter/kodi/scripts/kodi.sh
If system time was not set via NTP on RTC-less devices, current crash log may have the oldest time stamp and is deleted.
Seen in the forum after [requesting logs](https://forum.libreelec.tv/thread/23717-le-9-95-1-backup-reboot-libreelec-on-rp4/?postID=160278#post160278) of an RPI4.
=> [le11] kodi.sh: never delete just created crash log

packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.13.12.html
:master is #5710
=> [le10] samba: update to 4.13.12

config/functions, scripts/build, scripts/image, scripts/mkimage, scripts/unpack
This series is about reducing the number of subprocesses invoked in the buildsystem. Mostly reducing `basename` and `dirname` usage through bash builtins. Also replacing some `cat $file | patch ...` with `patch ... < $file`.
I've been using since Christmas or so.
=> Reduce subprocesses in buildsystem

config/arch.aarch64, config/arch.arm, config/arch.x86_64, config/options, config/path, config/show_config, projects/ARM/devices/ARMv8/options, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H5/options, projects/Allwinner/devices/H6/options, projects/Amlogic/devices/AMLGX/options, projects/Generic/options, projects/NXP/devices/iMX6/options, projects/NXP/devices/iMX8/options, projects/Qualcomm/devices/Dragonboard/options, projects/RPi/options, projects/Rockchip/devices/RK3288/options, projects/Rockchip/devices/RK3328/options, projects/Rockchip/devices/RK3399/options
This moves the sourcing of `config/arch.$ARCH` from `config/path` into `config/options`. It remains between distro/project/device options and `config/path` being sourced, but comes in before the buildsystem does a self-check.
This also allows moving TARGET_FEATURES and TARGET_KERNEL_ARCH out to the arch.$ARCH files, so do so.
Built / run tested on RPi3.aarch64.
=> buildsystem: change when config/arch.$ARCH is sourced

packages/addons/addon-depends/containerd/package.mk, packages/addons/addon-depends/libnetwork/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/changelog.txt, packages/addons/service/docker/package.mk
update docker addon (134) utilising updated supporting packages
- containerd: update to 1.5.6
- libnetwork: update to 2021-05-25
- runc: update to 1.0.2
=> [le11] docker: update addon to (134)

packages/network/samba/package.mk
Backport #5831 done
update 4.13.12 (2021-09-22) to 4.13.13 (2021-10-29)
release notes:
- https://www.samba.org/samba/history/samba-4.13.13.html
Changes since 4.13.12
---------------------
o  Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
* BUG 14868: rodc_rwdc test flaps.
* BUG 14881: Backport bronze bit fixes, tests, and selftest improvements.
o  Andrew Bartlett <abartlet@samba.org>
* BUG 14642: Provide a fix for MS CVE-2020-17049 in Samba [SECURITY] 'Bronze
bit' S4U2Proxy Constrained Delegation bypass in Samba with
embedded Heimdal.
* BUG 14836: Python ldb.msg_diff() memory handling failure.
* BUG 14845: "in" operator on ldb.Message is case sensitive.
* BUG 14848: Release LDB 2.3.1 for Samba 4.14.9.
* BUG 14871: Fix Samba support for UF_NO_AUTH_DATA_REQUIRED.
* BUG 14874: Allow …
=> [le11] samba: update to 4.13.13

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libxkbcommon/package.mk, packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk, packages/addons/addon-depends/chrome-depends/pango/package.mk
- at-spi2-core: correct meson build options
- chrome-libxkbcommon: correct meson build options
- gdk-pixbuf: correct meson build options
- pango: correct meson build options
further to #5799
=> [le11] More Fixes to meson: unknown options are now always fatal

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/addon-depends/chrome-depends/chrome-libxkbcommon/package.mk, packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk, packages/addons/addon-depends/chrome-depends/pango/package.mk
Have raised this as a backport, as these are active packages used by addons (chrome.)
- at-spi2-core: correct meson build options
- chrome-libxkbcommon: correct meson build options
- gdk-pixbuf: correct meson build options
- pango: correct meson build options
further to #5799
Upstream is #5833
=> [le10] Fixes to meson: unknown options are now always fatal

packages/tools/u-boot-tools/package.mk, packages/tools/u-boot/package.mk
mkimage and several other tools now require openssl on the host.
Add the missing dependencies and host compiler/linker options so openssl from the toolchain is properly picked up and used.
only build-tested for AW A64 - some more build+runtime tests would be great
=> u-boot: fix build openssl-related build errors

packages/addons/tools/network-tools/package.mk, packages/network/sshpass/package.mk
sshpass is useful for running rsync over ssh when the remote target is not running an rsync daemon
=> sshpass: add initial package and include with network-tools bundle

packages/linux-drivers/mali-midgard/package.mk
Fix mali-midgard build for kernel >= 5.11 (needed for 5.15) thanks to @ToKe79 for finding the kernel commit.
=> mali-midgard: update to 4d72a50

packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2021-October/000069.html
This release reflects the following changes:
Changes to future timestamps
Palestine will fall back 10-29 (not 10-30) at 01:00.
(Thanks to P Chan and Heba Hemad.)
=> [le10] tz: update to 2021e

packages/sysutils/tz/package.mk
ann:
- http://mm.icann.org/pipermail/tz-announce/2021-October/000069.html
This release reflects the following changes:
Changes to future timestamps
Palestine will fall back 10-29 (not 10-30) at 01:00.
(Thanks to P Chan and Heba Hemad.)
backport is #5855
=> [le11] tz: update to 2021e

projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
Sorry, this slipped through in testing.
Runtime tested on RPi3B+
=> RPi: fix non-working USB and ethernet on RPi2

packages/network/samba/package.mk
update 4.13.13 (2021-10-29) to 4.13.14 (2021-11-09)
release notes: https://www.samba.org/samba/history/samba-4.13.14.html
===============================
Release Notes for Samba 4.13.14
November 9, 2021
===============================
o CVE-2016-2124:  SMB1 client connections can be downgraded to plaintext
authentication.
https://www.samba.org/samba/security/CVE-2016-2124.html
o CVE-2020-25717: A user on the domain can become root on domain members.
https://www.samba.org/samba/security/CVE-2020-25717.html
(PLEASE READ! There are important behaviour changes described)
o CVE-2020-25718: Samba AD DC did not correctly sandbox Kerberos tickets issued
by an RODC.
https://www.samba.org/samba/security/CVE-2020-25718.html
o …
=> [le11] samba: update to 4.13.14

packages/network/samba/package.mk
update 4.13.12 (2021-09-22) to 4.13.14 (2021-11-09)
release notes:
- https://www.samba.org/samba/history/samba-4.13.13.html
- https://www.samba.org/samba/history/samba-4.13.14.html
Changes since 4.13.12
---------------------
o  Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
* BUG 14868: rodc_rwdc test flaps.
* BUG 14881: Backport bronze bit fixes, tests, and selftest improvements.
o  Andrew Bartlett <abartlet@samba.org>
* BUG 14642: Provide a fix for MS CVE-2020-17049 in Samba [SECURITY] 'Bronze
bit' S4U2Proxy Constrained Delegation bypass in Samba with
embedded Heimdal.
* BUG 14836: Python ldb.msg_diff() memory handling failure.
* BUG 14845: "in" operator on ldb.Message is case sensitive.
* BUG 14848: Release LDB 2.3.1 for Samba 4.14.9.
* BUG 14871: Fix Samba support for …
=> [le10] samba: update to 4.13.13

packages/devel/slang/package.mk
A make -j17 release looks to have caused an race/out-of-order build. Add corrected dependency.
=> slang: add pcre dependency 

packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/service/mpd/changelog.txt, packages/addons/service/mpd/package.mk, packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
Updates of 2 addon and the currently unused mpv-drmprime.
- mpd: update to 0.23.3 and addon (112)
- regular update (and fix meson build removing tidal option - no longer valid)
- mpv-drmprime: update to 0.34.0
- fix build failure due to PKG_CONFIGURE variable not match “manual” build
- update package
- btrfs-progs: update to 5.15 and addon (104)
- don’t build unnecessary python support
- Remove now obsolete command `btrfs-zero-log` 
- Updated command is `btrfs rescue zero-log`
=> [le11] Update addons (mpd, btrfs-progs)

packages/wayland/weston/package.mk
- add dependency of `wayland`
- remove invalid meson option `-Dsimple-dmabuf-drm=intel `
- weston does not build with NDEBUG (requires assert for tests)
=> weston: fix meson options and NDEBUG compile

packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/service/mpd/changelog.txt, packages/addons/service/mpd/package.mk, packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
Updates of 2 addon and the currently unused mpv-drmprime.
- mpd: update to 0.23.3 and addon (112)
- regular update (and fix meson build removing tidal option - no longer valid)
- mpv-drmprime: update to 0.34.0
- fix build failure due to PKG_CONFIGURE variable not match “manual” build
- update package
- btrfs-progs: update to 5.15 and addon (104)
- don’t build unnecessary python support
- Remove now obsolete command `btrfs-zero-log` 
- Updated command is `btrfs rescue zero-log`
Upstream is #5841
=> [le10] Update addons (mpd, btrfs-progs)

projects/Allwinner/filesystem/usr/bin/install2emmc, projects/NXP/devices/iMX8/filesystem/usr/bin/install2emmc, scripts/image
Script uses arbitrary values for FAT32 partition and name of the
distribution. Using placeholders in the script and replacing them at
build time offers flexibility, i.e. no need to change arbitrary values
in script when SYSTEM_SIZE is changed.
=> install2emmc: use SYSTEM_SIZE and DISTRONAME in script

packages/devel/pcre/package.mk
Update 8.44 to 8.45
website https://ftp.pcre.org/pub/pcre/ no longer working as per the note on http://www.pcre.org/. Downloads should be done from soureforge.
http://www.rexegg.com/pcre-doc/ChangeLog
Version 8.45 15-June-2021
This is the final release of PCRE1. A few minor tidies are included.
1. CMakeLists.txt has two user-supplied patches applied, one to allow for the setting of MODULE_PATH, and the other to support the generation of pcre-config file and libpcre*.pc files.
2. There was a memory leak if a compile error occurred when there were more than 20 named groups (Bugzilla 2613).
3. Fixed some typos in code and documentation.
4. Fixed a small (*MARK) bug in the interpreter (Bugzilla 2771).
=> pcre: update to 8.45 and PKG_URL

packages/sysutils/exfatprogs/package.mk, packages/virtual/image/package.mk
Add the userspace utilities that contain all of the standard utilities for creating and fixing and debugging exfat filesystems. https://github.com/exfatprogs/exfatprogs/
RFQs:
- which tools **shouldn’t** be included?
- should the tools be included in `init` as well?
- Is `packages/virtual/image/package.mk` the right `package.mk` for the dependency?
These are the file sizes on x86_64:
```
exfatprogs-1.1.2$ ls -l ./usr/sbin/
-rwxr-xr-x 1 docker docker 18952 Nov  7 19:55 dump.exfat
-rwxr-xr-x 1 docker docker 19016 Nov  7 19:55 exfatlabel
-rwxr-xr-x 1 docker docker 35680 Nov  7 19:55 fsck.exfat
-rwxr-xr-x 1 docker docker 31120 Nov  7 19:55 mkfs.exfat
-rwxr-xr-x 1 docker docker 19144 Nov  7 19:55 tune.exfat
```
=> exfatprogs: add standard utilities for creating and fixing and debugging exfat filesystems

packages/addons/addon-depends/chrome-depends/pango/package.mk, packages/addons/addon-depends/chrome-depends/shared-mime-info/patches/migrate-from-custom-itstool-to-builtin-msgfmt-for-creating-translated-XML.patch, packages/addons/addon-depends/chrome-depends/shared-mime-info/patches/no-man-no-html.patch, packages/addons/browser/chrome/changelog.txt, packages/addons/browser/chrome/package.mk, packages/graphics/harfbuzz/package.mk
- shared-mime-info: meson fix - migrate itstool to builtin msgfmt
- pango: update to 1.49.3
- harfbuzz: update to 3.1.1
- chrome: update to 96.0.4664.45 and addon (111)
=> [le11] chrome: update to 96.0.4664.45 and addon (111)

packages/graphics/mesa/package.mk, packages/multimedia/gmmlib/package.mk, packages/multimedia/media-driver/package.mk
- gmmlib: update to 21.3.3  
- media-driver: update to 21.4.1
- mesa: update to 21.3.0
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/9ca91d9bbe30bd2a6792ce353439367e5ae37054/docs/relnotes/21.3.0.rst
Mesa 21.3.0 is a new development release. People who are concerned
with stability and reliability should stick with a previous release or
wait for Mesa 21.3.1.
Mesa 21.3.0 implements the OpenGL 4.6 API, but the version reported by
glGetString(GL_VERSION) or glGetIntegerv(GL_MAJOR_VERSION) /
glGetIntegerv(GL_MINOR_VERSION) depends on the particular driver being used.
Some drivers don't support all the features required in OpenGL 4.6. OpenGL
4.6 is only available if requested at context creation.
Compatibility contexts may report a lower version depending on each driver.
Mesa 21.3.0 …
=> Mesa and Intel updates

packages/mediacenter/kodi/config/advancedsettings.xml
- the timeout of 30sec is already default at Kodi since K18 https://github.com/xbmc/xbmc/commit/73be9522c13601f17bd2800ac379fa32611f9cfe
=> kodi: cleanup samba client timeout

packages/network/iw/package.mk, packages/network/iwd/package.mk
- iw: update to 5.16
- https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git/log/
- update 5.9 to 5.16
- iwd: update to 1.20
- **ver 1.20:**
-  Fix issue with handling Hotspot 2.0 requirements.
-  Add support for evict_nocarrier setting during roaming.
-  Add support for experimental NetworkConfigurationAgent API.
- **ver 1.19:**
-  Fix issue with handling OCV if offloading is supported.
-  Fix issue with handling SA Query on channel switch event.
- Fix issue with starting FT-over-DS actions after roaming.
-  Add support for OWE transition networks.
-  Add support for extended key IDs.
=> Wireless updates

packages/wayland/wayland-protocols/package.mk, packages/wayland/waylandpp/package.mk
Minor tidy up to allow build of waylandpp and wayland-protocols independently. dependancies added. 
tested the following.
```
make clean
scripts/build waylandpp
make clean
scripts/build wayland-protocols
```
following on from #5864
=> waylandpp and wayland-protocols: dependancies

projects/Generic/devices/Generic-legacy/options, projects/Generic/devices/Generic/options
As follow up to https://github.com/LibreELEC/LibreELEC.tv/pull/5814 & https://github.com/LibreELEC/LibreELEC.tv/pull/5881 we should add crocus to graphic drivers. The i965 driver can be dropped later if there are no issues. 
FYI [_i965_ supports gen4-gen12](https://wiki.gentoo.org/wiki/Intel#Feature_support) Intel GPUs but is superseded by Gallium drivers _crocus_ (gen4-gen7.5)  & _iris_ (gen8+)
- added crocus to Generic project graphic drivers
- clean up
=> [le11] projects/Generic: clean up & add crocus graphic driver

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch, packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch, packages/mediacenter/kodi/patches/kodi-100.26-disable-internal-texturepacker.patch, packages/mediacenter/kodi/patches/kodi-995.01-fix-missing-wayland-scanner-pkg-config.patch
- latest kodi 20
- added workaround for ?hack introduced at https://github.com/xbmc/xbmc/pull/20413
- supersedes https://github.com/LibreELEC/LibreELEC.tv/pull/5872
if a better solution is found  the workaround could be replaced, for now it looks working
build + runs for generic
=> kodi: update to latest

projects/Allwinner/devices/H2-plus/options, projects/Allwinner/devices/H2-plus/patches/u-boot/0001-DO-NOT-MERGE-sunxi-psci-Delegate-PSCI-to-SCPI.patch, projects/Allwinner/patches/linux/0063-bananapim2-zero-key_power.patch, scripts/uboot_helper
This enables poweroff on the Banana PI M2 Zero and reduces the current
consumption after poweroff from ~160mA to ~40mA
=> Allwinner: add Crust support for bananapi-m2-zero

config/graphic, packages/addons/addon-depends/ffmpegx/package.mk, packages/graphics/libdrm/package.mk, packages/graphics/mesa/package.mk, packages/virtual/mediacenter/package.mk, projects/ARM/options, projects/Allwinner/options, projects/Generic/devices/Generic-legacy/options, projects/Generic/devices/Generic/options, projects/NXP/options, projects/Qualcomm/devices/Dragonboard/options, projects/Rockchip/options
mesa GRAPHIC_DRIVERS: delete classic drivers (DRI) 
- in preparation for Mesa 22.0.0
- this removes the classic Mesa drivers.
- https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10153
- mesa GRAPHIC_DRIVERS: 
- remove classic DRI drivers (i915, i965, r100, r200, nouveau)
- add the i915g driver
The following **gallium** drivers are available in mesa
- https://gitlab.freedesktop.org/mesa/mesa/-/tree/main/src/gallium/drivers
- Enable the i915 gallium driver
- The i965 driver has been replaced with the crocus driver
- nouveau is available as a gallium driver
- r200 has NO replacement
#5885 added the crocus driver to Generic and Generic-legacy
=> mesa GRAPHIC_DRIVERS: delete classic drivers (DRI)

packages/graphics/libdrm/package.mk, packages/multimedia/media-driver/package.mk
Update packages
- media-driver: update to 21.4.2
- libdrm: update to 2.4.109 
```
Generic.x86_64-devel-20211126090242-6168d44
Linux nuc11 5.15.5 #1 SMP Fri Nov 26 08:42:07 UTC 2021 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:08b7599d63e063545e34a24bb17fc3738cd4dde7). Platform: Linux x86 64-bit
Kodi compiled 2021-11-26 by GCC 10.3.0 for Linux x86 64-bit version 5.15.5 (331525)
Running on LibreELEC (heitbaum): devel-20211126090242-6168d44 11.0, kernel: Linux x86 64-bit version 5.15.5
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0041.2021.0811.1505 08/11/2021
RetroPlayer[PROCESS]: Registering …
```
=> Update Intel media-driver and libdrm

packages/mediacenter/kodi/patches/kodi-999.01-nfs-timeout-to-15sec.patch
backport of https://github.com/xbmc/xbmc/pull/20475
If the NAS uses HDD spin up/down the nfs timeout was too short to allow a spinup without creating errors at the gui.
SMB has a 30sec timeout.
=> Kodi: NFS timeout to 30 secs

projects/RPi/patches/kodi/kodi-001-deinterlace.patch
It's time for broader testing, local testing with interlaced SD (MPEG2, H264) and HD (H264) videos on RPi4 already looked quite good.
=> RPi: add kodi deinterlace patch

packages/tools/u-boot-tools/package.mk, packages/tools/u-boot/package.mk
Whilst tidying up my build environment (and moving to the focal docker build) - the `Makefile.host` is trying to use cc (as HOSTCC is not being past through.) update the package.mk to pass HOSTCC and other HOSTxxx variables through to the `u-boot` and `u-boot-tools` make.
=> u-boot and u-boot-tools: fix HOSTCC build issues

projects/RPi/patches/kodi/kodi-001-deinterlace.patch
This fixes the horizontal line glitches seen with software decoding (eg MPEG2 on RPi4)
=> RPi: update kodi deinterlace patch

packages/tools/mtools/package.mk, scripts/mkimage
Updated mtools to latest version.
Modified `scripts/mkimage` so image with `SYSTEM_SIZE` above 1024 MB can be created and errors during mformat/mcopy/mmd will be caught.
=> Update mtools + optimize mkimage to catch errors / to allow SYSTEM_SIZE >= 1024 / for speed

packages/mediacenter/kodi-binary-addons/pvr.plutotv/package.mk
This PR adds the new pvr plugin pvr.plutotv.
See: https://github.com/kodi-pvr/pvr.plutotv
It is now official kodi addon: https://github.com/xbmc/repo-binary-addons/pull/153
=> kodi-binary-addons: add pvr.plutotv

packages/mediacenter/kodi-binary-addons/pvr.plutotv/package.mk
See #5933
This PR adds the new pvr plugin pvr.plutotv.
See: https://github.com/kodi-pvr/pvr.plutotv
It is now official kodi addon: https://github.com/xbmc/repo-binary-addons/pull/152
=> [le10] kodi-binary-addons: add pvr.plutotv

packages/tools/rpi-eeprom/package.mk
This fixes the bootloader update issue reported on the forum https://forum.libreelec.tv/thread/24931-rpi4-bootloader-update/
Latest beta version also got promoted to stable
=> rpi-eeprom: update to 86eee57

config/functions
Currently building a package with
GET_HANDLER_SUPPORT="file"
PKG_URL="file:///some_path_to_file_with_sources"
throws an error
ERROR: using manual toolchain but PKG_TAR_COPY_OPTS is configured.
=> config/functions: fix file get_handler_support with manual toolchain

projects/Generic/linux/linux.x86_64.conf
CONFIG_I2C_HID_CORE was removed by accident with 221bd5a397d68e65cd23c39fa74f2bf8a0c2bde0 and my I2C connected touchpad is not detected any more.
Add CONFIG_I2C_HID_CORE and CONFIG_I2C_HID_ACPI to let the touchpad work again.
Other changes are result of `make oldconfig`.
=> linux config Generic: add CONFIG_I2C_HID_CORE to fix I2C touchpad regression

packages/python/system/dbussy/package.mk
Test the dbussy improvement/fix triggered by LibreELEC/service.libreelec.settings#245 in nightlies.
I've seen no issues while using it in my LE10/LE11 Generic development images.
=> dbussy: update to a694e3b, status cleanup fix

packages/debug/xorg-intel-gpu-tools/patches/xorg-intel-gpu-tools-1-26-meson-build.patch
Upstream patch to fix meson builds.
=> xorg-intel-gpu-tools: upstream fix from meson 0.60.0 build

packages/tools/crust/patches/fix-cc.patch
- `PROJECT=Allwinner ARCH=arm DEVICE=A64 make image`
crust build fails when cc link is missing (e.g. minimal Ubuntu 20.04)
use host-gcc from the toolchain instead.
addition of the patch fixes the following error.
BUILD      crust (target)
TOOLCHAIN      manual
...
HOSTCC  build/3rdparty/kconfig/conf.o
/bin/sh: 1: exec: cc: not found
make[1]: *** [Makefile:170: build/3rdparty/kconfig/conf.o] Error 127
...
```
-BUILDCC		 = cc
+BUILDCC		 ?= cc
```
And update the `package.mk` to override **BUILDCC**
=> crust: use host-gcc from toolchain not cc

packages/security/nspr/package.mk, packages/security/nss/package.mk
- nspr: update to 4.32
- https://groups.google.com/a/mozilla.org/g/dev-tech-crypto/c/4eyMP8SrUGk/m/Oywjzs4SAAAJ
- https://groups.google.com/a/mozilla.org/g/dev-tech-crypto/c/M01xJ10PkAc/m/S2FWp3KHAQAJ
- nss: update to 3.73
- https://groups.google.com/a/mozilla.org/g/dev-tech-crypto/c/vy9284s8APM
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Releases
- https://firefox-source-docs.mozilla.org/security/nss/releases/index.html
=> nss and nspr: update packages

packages/graphics/mesa/package.mk, packages/multimedia/media-driver/package.mk
Mesa:
release notes: https://docs.mesa3d.org/relnotes/21.3.1.html
media-driver:
[CP] Media trace RT log/error for CP -2
add media trace RT log/error for CP GPU HAL part -2
=> mesa: update to 21.3.1 and (Intel) media-driver: update to 21.4.3

config/functions, config/optimize, scripts/build
Meson 0.49 introduduced an option for describing [native environments](https://mesonbuild.com/Native-environments.html) which allows to build `package:host` with native args & `package:target` with cross compile args. Currently all packages were build as "cross compile" which results in build failures if `meson.build` files use statements like `if meson.is_cross_build()`  e.g.: https://gitlab.freedesktop.org/wayland/wayland/-/issues/256
- added `[build_machine]` section to host & target meson conf
- updated the `[host_machine]` section for meson conf to match build machine cpu
- added `MACHINE_HARDWARE_CPU` determined by `uname -p` 
- updated build script to load meson host conf per `--native-file` instead `--cross-file`
Build tested for Generic & RK3399, runtested on Intel APL (wayland …
=> [le11] use Meson native build for package:host

packages/network/bluez/package.mk
bluez.pc is needed to convience pulseaudio that bluez is present. Another alternative would be to enable library, but it's not needed and it would increase size for around 186 KiB on ARM.
=> bluez: install empty bluez.pc

projects/Allwinner/patches/linux/0065-wip-fix-H6-4k-60.patch
With some TV and H6 board combinations, 4k@60 mode didn't work. TV didn't detect any HDMI signal. This PR fixes this issue.
=> Allwinner: linux: fix 4k60 mode on H6 with some HW

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Add 43438 firmware 7.45.98.118 + external clm_blob
Add 43455 firmware 7.45.241 and clm_blob
=> [LE11] brcmfmac_sdio-firmware-rpi: update to ea9963f

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Add 43438 firmware 7.45.98.118 + external clm_blob
Add 43455 firmware 7.45.241 and clm_blob
backport of #5962
=> [LE10] brcmfmac_sdio-firmware-rpi: update to ea9963f

packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/jre-depends/apache-ant/package.mk, packages/addons/addon-depends/librespot-depends/rust/package.mk, packages/devel/cmake/package.mk
- apache-ant: update to 1.10.12
- cmake: update to 3.22.1
- go: update to 1.17.5
- rust: 1.57.0
=> devtools: minor updates

packages/wayland/wayland-protocols/package.mk
Announcement:
- https://lists.freedesktop.org/archives/wayland-devel/2021-November/042039.html
This release adds feedback to the DMA buffer protocol, allowing smarter and
more dynamic DMA buffer allocation semantics. Other changes include
documentation improvements and improved testing infrastructure.
This is also the first release of wayland-protocols that do not include a
autotools build description.
Alex Richardson (2):
tests: allow cross-compiling the tests
tests: check whether -Wl,--unresolved-symbols=ignore-all is supported
Demi Marie Obenour (2):
Use “software” instead of “user space”
Improve tiled_* enum summary
Fabrice Fontaine (1):
meson.build: wayland-scanner is only needed for tests
Jonas Ådahl (1):
build: Bump version to 1.24
Simon Ser (4):
Drop autotools
linux-dmabuf: add …
=> wayland-protocols: update to 1.24

packages/graphics/glu/package.mk, packages/multimedia/gmmlib/package.mk
- glu: update to 9.0.2 and HSTS and updated URL
- https://lists.freedesktop.org/archives/mesa-announce/2021-June/000634.html
- gmmlib: update to 21.3.4
- Intel Graphics Memory Management Library 2021 Q3 Release 4
- https://github.com/intel/gmmlib/compare/intel-gmmlib-21.3.3...intel-gmmlib-21.3.4
=> Minor Graphics updates: glu and gmmlib

packages/lang/gcc-or1k-linux/package.mk
Build tested with all of:
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
```
=> gcc-or1k-linux: update to 2021.05-1

packages/multimedia/media-driver/patches/media-driver-0001-GMM-Multi-Adapter-Interface-Changes.patch
Error during build
- #5966 
- Missed dependancy during partial build.
- Require media-driver 21.4.4 to support gmmlib 21.3.4 fully.
- Added upstream patch
Ref: 
- https://github.com/intel/gmmlib/issues/93
- https://github.com/intel/media-driver/commit/42ffd7983a32b75cf8403c235d8d0f727191390c
=> media-driver: fix to support gmmlib 21.3.4 until media-driver 21.4.4

packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk, packages/addons/tools/system-tools/package.mk
Tools for interacting with the linux GPIO character device (gpiodetect,
gpioinfo, gpioget, gpioset, gpiofind, gpiomon)
=> system-tools: include libgpiod

packages/security/gnutls/package.mk, packages/security/openssl/package.mk
Update openssl to 1.1.1l. It's security fixes.
Release announce: https://mta.openssl.org/pipermail/openssl-announce/2021-August/000206.html
Update gnutls to 3.7.2. Development work.
Release announce: https://lists.gnupg.org/pipermail/gnutls-help/2021-May/004708.html
=> crypto updates

packages/graphics/mesa/package.mk
https://docs.mesa3d.org/relnotes/21.3.2.html
Mesa 21.3.2 is a bug fix release which fixes bugs found since the 21.3.1 release.
- Flickering and blackscreen on Mpv and Clapper (and also low performance on glxgears)
- DXVK SIGBUS with Turnip on Poco F1 at loading to open world.
- RADV: IsHelperInvocationEXT query is not considered volatile in ACO
- [GraphicsFuzz] dEQP-VK.graphicsfuzz.stable-binarysearch-tree-nested-if-and-conditional
- [bisected] Mesa 21.3.x breaks GBM with NVIDIA closed source driver 495.44
- [DG2] dEQP—GL[45|ES31].functional.shaders.builtin_functions.pack_unpack.packhalf2x16_compute fail
=> mesa: update to 21.3.2

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
this adds support for 10/12bit RGB and 12bit YCbCr 4:2:2 video output
=> linux (RPi): update to 5.15.10-6f15bf3

packages/sysutils/gptfdisk/package.mk, packages/textproc/expat/package.mk, packages/tools/hdparm/package.mk, packages/tools/qemu/package.mk
- expat: update to 2.4.1
- gptfdisk: update to 1.0.8
- hdparm: update to 9.62
- qemu: update to 6.2.0 and configure
=> development tools

packages/addons/addon-depends/ttyd-depends/libwebsockets/package.mk, packages/addons/service/ttyd/changelog.txt, packages/addons/service/ttyd/package.mk
- libwebsockets: update to 4.3.0
update to support OpenSSL 3.0.1
=> ttyd: update addon (103)

packages/compress/zstd/package.mk
Good for another ~0.5MB reduction of the image for me.
Changelog: https://github.com/facebook/zstd/releases/tag/v1.5.1
=> zstd: update to 1.5.1

packages/x11/driver/xf86-video-intel/patches/xf86-video-intel-100.01-prefer-iris-and-crocus-over-i965.patch
- the xf86-video-intel driver is harcoded against the classic i915/i965 drivers: https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/blob/master/src/sna/sna_dri2.c#L3705-3711
- after the removal of them by https://github.com/LibreELEC/LibreELEC.tv/pull/5887 GLX was broken if used on Intel systems since e.g. `i965_dri.so` was missing
- the modesetting driver is not a real alternative because of https://gitlab.freedesktop.org/xorg/xserver/-/issues/928
- this patch loads the gallium drivers depending on the matching generation
Tested on a Skylake system with `iris` - crocus & i915 untested but should work the same way.
```
[     7.268] (II) intel(0): [DRI2] Setup complete
[     7.268] (II) intel(0): [DRI2]   DRI driver: iris
[     7.268] (II) intel(0): [DRI2]   VDPAU driver: va_gl …
```
=> xf86-video-intel: prefer iris & crocus over classic drivers

packages/addons/addon-depends/snapcast-depends/alsa-plugins/package.mk, packages/addons/addon-depends/snapcast-depends/asio/package.mk, packages/addons/addon-depends/snapcast-depends/popl/package.mk, packages/addons/addon-depends/snapcast-depends/snapcast/package.mk, packages/addons/service/snapclient/changelog.txt, packages/addons/service/snapclient/package.mk, packages/addons/service/snapserver/changelog.txt, packages/addons/service/snapserver/package.mk
Backport of #6010 
Release notes:
- https://github.com/badaix/snapcast/releases/tag/v0.26.0 
- update 0.25.0 (2021-05-15) to 0.26.0 (2021-12-23)
Update addons:
- snapclient: update snapcast to 0.26.0 (108)
- snapserver: update snapcast to 0.26.0 (108)
Update packages:
- alsa-plugins: update to 1.2.6
- asio: update to 1.21.0
- popl: update to 1.3.0
- snapcast: update to 0.26.0
- fixed dependency on pulseaudio
=> [le10] snapcast: update to 0.26.0 and addon (108)

packages/addons/addon-depends/snapcast-depends/alsa-plugins/package.mk, packages/addons/addon-depends/snapcast-depends/asio/package.mk, packages/addons/addon-depends/snapcast-depends/popl/package.mk, packages/addons/addon-depends/snapcast-depends/snapcast/package.mk, packages/addons/service/snapclient/changelog.txt, packages/addons/service/snapclient/package.mk, packages/addons/service/snapserver/changelog.txt, packages/addons/service/snapserver/package.mk
Release notes:
- https://github.com/badaix/snapcast/releases/tag/v0.26.0 
- update 0.25.0 (2021-05-15) to 0.26.0 (2021-12-23)
Update addons:
- snapclient: update snapcast to 0.26.0 (108)
- snapserver: update snapcast to 0.26.0 (108)
Update packages:
- alsa-plugins: update to 1.2.6
- asio: update to 1.21.0
- popl: update to 1.3.0
- snapcast: update to 0.26.0
- fixed dependency on pulseaudio
=> [le11] snapcast: update to 0.26.0 and addon (108)

packages/mediacenter/kodi/package.mk
Looking around Kodi source revealed that libhdhomerun is not used anymore for a long time. This dependency was added after Kodi lost direct support for it (PR #641), which is a bit mysterious. There is proper support for it via addon.
=> kodi: remove libhdhomerun dependency

packages/addons/addon-depends/system-tools-depends/bottom/package.mk, packages/addons/addon-depends/system-tools-depends/depends/efivar/package.mk, packages/addons/addon-depends/system-tools-depends/depends/efivar/patches/efivar-01-static_lib.patch, packages/addons/addon-depends/system-tools-depends/depends/libmtp/package.mk, packages/addons/addon-depends/system-tools-depends/depends/libssh2/package.mk, packages/addons/addon-depends/system-tools-depends/diffutils/package.mk, packages/addons/addon-depends/system-tools-depends/efibootmgr/package.mk, packages/addons/addon-depends/system-tools-depends/file/package.mk, packages/addons/addon-depends/system-tools-depends/htop/package.mk, packages/addons/addon-depends/system-tools-depends/i2c-tools/package.mk, packages/addons/addon-depends/system-tools-depends/inotify-tools/package.mk, packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk, packages/addons/addon-depends/system-tools-depends/nmon/package.mk, packages/addons/addon-depends/system-tools-depends/pv/package.mk, packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/addon-depends/system-tools-depends/vim/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
backport of
- #5767
- #5775
- #5787
- #5915
- #6019
- Update bottom to 0.6.6
- Update diffutils to 3.8
- Update efibootmgr to githash 2021-11-05
- Update efivar to githash 2021-12-10
- Update file to 5.41
- Update htop to 3.1.2
- Update i2c-tools to 4.3 and fix build prefix
- Update inotify-tools to 3.21.9.6
- Add libgpiod (1.6.3)
- Update libmtp to 1.1.19
- Update libssh2 to 1.10.0
- Update nmon to 16n
- Update pv to 1.6.20
- Update stress-ng to 0.13.05 and the PKG_URL
- Update unrar to 6.1.3
- Update vim to 8.2.3878
=> [le10] system-tools: update to (127)

packages/graphics/mesa/package.mk, packages/mediacenter/kodi/package.mk, packages/multimedia/intel-vaapi-driver/package.mk, packages/multimedia/libva/package.mk, packages/virtual/wl/package.mk, packages/virtual/x11/package.mk, packages/wayland/libxkbcommon/package.mk, packages/wayland/weston/patches/weston-999.01-PR486-avoid-setting-WAYLAND_DISPLAY=wayland-0.patch, projects/ARM/options, projects/Allwinner/options, projects/Amlogic/options, projects/Generic/devices/Generic/options, projects/Generic/devices/wayland/options, projects/Generic/devices/x11/options, projects/NXP/options, projects/Qualcomm/devices/Dragonboard/options, projects/RPi/options, projects/Rockchip/options, projects/Samsung/options
This PR decouples Wayland & Weston which allows to alter or replace the windowmanager / compositor if needed without editing other packages beside the project options.
- add backported patch for Weston to use `WAYLAND_DISPLAY=wayland-1` as other compositors do & updated Kodi conf
- use `DISPLAYSERVER="wl"` & `WINDOWMANAGER="weston"` for wayland builds
- set `WINDOWMANAGER="no"` instead `WINDOWMANAGER="none"` for all GBM builds
- added a virtual `wl` package which allows to add dependencies/tools at a central place if necessary
- the virtual package adds the windowmanager dependency instead of adding Weston, or else, as dep.
Build & run tested with generic
=> [le11] rework wayland displayserver & windowmanager handling

packages/graphics/libheif/package.mk
Update 1.10.0 to 1.12.0
Changelog: https://github.com/strukturag/libheif/releases
-  check for MIAF conformance and add as compatible brand
-  signaling of premultiplied alpha
-  parse AV1 obu_sequence_header for av1C box
-  write pixi box in AVIFs
-  save alpha as monochrome in AVIF if possible
-  many build fixes (thanks to the numerous external contributors)
-  fix writing ispe box in HEIFs
-  nclx output profile encoding parameters
-  change the way nclx profiles is written so that macOS can read them
-  API for listing file brands and checking file type
-  fix heif_image_handle_get_depth_image_representation_info()
=> libheif: update to 1.12.0

packages/addons/addon-depends/snapcast-depends/asio/package.mk, packages/sysutils/open-vm-tools/package.mk, scripts/autoreconf, scripts/build
PKG_BUILD path was hard coded in autoreconf script. Use path of PKG_CONFIGURE_SCRIPT that is by default set to "${PKG_BUILD}/configure".
See discussion of #4972
=> autoreconf: support custom PKG_CONFIGURE_SCRIPT

packages/graphics/cairo/package.mk
Dear maintainers,
here are two fixes I made to upstream while porting Lakka to LibreELEC master branch. There are more changes for Lakka, but those are Lakka specific (e.g. Lakka requires in some cases shared libs instead of static, different boot messages / menus, vulkan drivers, ...), so I am not sending those over.
`cairo`
Originally the package file chose between OpenGL and OpenGLES flags based on the presence of the DISPLAYSERVER. These flags should be most probably set based on the fact if OpenGL or OpenGLES (or neither of both) is used.
`get_git`
The script originally looked at every file AND folder in the sources folder, which is incorrect and causes unintentional deletion of archive files. After the fix the script checks only folders.
If it is preferred to have two separate pull …
=> cairo: set options based on OPENGL/ES

packages/devel/glib/package.mk
Fix build issue since https://github.com/LibreELEC/LibreELEC.tv/commit/ad84c1e24b0860d3eb68899c7b757edd85162e9f 
- meson version 0.60.y now fail on errors.
- The reference of a duplicate line `needs_exe_wrapper ` resulted in the failure #6023
=> glib: remove needs_exe_wrapper from makefile

packages/addons/addon-depends/libhdhomerun/package.mk, packages/addons/addon-depends/libhdhomerun/patches/shared-to-static.patch
Several addons (pvr.hdhomerun, tvheadend42, tvheadend43) link against libhdhomerun shared library. However, that doesn't work in our case, because addons don't carry shared libraries. This PR transforms libhdhomerun to static library so addons include all needed functions directly into them.
Note that only downside now is that there is no hdhomerun_config program. If there is a need, we can always make separate addon for it. 
Not sure if addons need to be bumped. At least they need to be rebuilt.
@CvH @heitbaum please test
=> libhdhomerun: make lib static

packages/addons/service/inadyn/changelog.txt, packages/addons/service/inadyn/package.mk, packages/addons/service/rsyslog/changelog.txt, packages/addons/service/rsyslog/package.mk, packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
btrfs-progs: update to 5.15.1
inadyn: update to 2.9.1 and addon (108)
rsyslog: update to 8.2112.0 and addon to (109) and update PKG_URL to
backport of #6038 
- ~~prometheus-node-exporter: update to 1.3.1 and addon (101)~~
- not included as it is not backported.
=> [le10] update addons

packages/network/samba/package.mk
Backport of #6031
release notes:
- https://www.samba.org/samba/history/samba-4.13.15.html
=> [le10] samba: update to 4.13.15

packages/audio/libogg/package.mk, packages/compress/libarchive/package.mk, packages/textproc/libidn2/package.mk
Bugfix releases for a few mixed packages.
libogg 1.3.5: https://github.com/xiph/ogg/releases/tag/v1.3.5
libarchive 3.5.2: https://github.com/libarchive/libarchive/releases/tag/v3.5.2
libidn2 2.3.1: https://lists.gnu.org/archive/html/info-gnu/2021-05/msg00009.html
libidn2 2.3.2: https://lists.gnu.org/archive/html/info-gnu/2021-07/msg00008.html
=> Package Updates Dec 2021

packages/linux-firmware/firmware-imx/package.mk
update 8.9 (2020-09-13) to 8.14 (2021-11-25)
release notes:
Logs from: **SolidRun Cubox-i Dual/Quad**
```
firmware-imx: 8.9
cubox:~ # dmesg | grep -i firmware
[    1.552046] imx-sdma 20ec000.sdma: loaded firmware 3.5
[    3.436809] coda 2040000.vpu: Firmware code revision: 46076
[    3.436874] coda 2040000.vpu: Firmware version: 3.1.1
[    7.250703] kernel-overlays-setup: added firmware from /usr/lib/kernel-overlays/base/lib/firmware
[   16.295532] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac4330-sdio.solidrun,cubox-i-q.bin failed with error -2
[   16.797925] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4330/4 wl0: Oct 25 2011 19:34:12 version 5.90.125.104
firmware-imx: 8.14
cubox:~ #  dmesg | grep -i …
```
=> firmware-imx: update to 8.14

packages/debug/vadumpcaps/package.mk, packages/graphics/glmark2/package.mk
- glmark2: update to 2021.12
- vadumpcaps: update githash to 2022-01-01
=> update (debug/performance tools): glmark2 and vadumpcaps packages

packages/addons/addon-depends/libzip/package.mk, packages/addons/addon-depends/libzip/patches/libzip-001-fix-typo-which-prevents-expansion-of-libdir-in-pkgconfig.patch, packages/addons/addon-depends/vdr/package.mk, packages/addons/service/vdr-addon/changelog.txt, packages/addons/service/vdr-addon/package.mk
- libzip: update to 1.8.0
- and patch to fix pkgconfig
- vdr-addon: update to 2.4.8 and addon (117)
- vdr: update to 2.4.8
- http://git.tvdr.de/?p=vdr.git;a=log;h=cea1e4061fa2e5a33c5cc4aab65fa385125252aa
- Minor update to stable.
**2021-12-27: Version 2.4.8**
- Fixed a possible crash in the Schedule menu, in case Setup.EPGLinger is 0.
- Fixed cTsPayload::AtPayloadStart() to ignore TS packets from other PIDs.
- Fixed unlocking vs. call to EpgHandlers.EndSegmentTransfer() (reported by Christoph  Haubrich).
- Fixed a memory leak in handling the NIT (thanks to Helmut Binder).
- Fixed a possible memory leak in creating fonts (reported by Helmut Binder).
- Fixed calculating the disk use percentage if there's more than 20TB of recordings  (reported by Timo Weingärtner).
- Official release.
=> vdr-addon: update to 2.4.8 and addon (117)

packages/web/libmicrohttpd/package.mk, packages/web/nghttp2/package.mk
- libmicrohttpd: update to 0.9.75
- https://lists.gnu.org/archive/html/info-gnu/2021-12/msg00010.html
- nghttp2: update to 1.46.0
- https://nghttp2.org/blog/2021/10/19/nghttp2-v1-46-0/
- https://github.com/nghttp2/nghttp2/releases/tag/v1.46.0
=> Web package updates

packages/print/freetype/package.mk, packages/print/freetype/patches/freetype-01-fix-pkgconf.patch
CHANGES BETWEEN 2.10.4 and 2.11.0
I. IMPORTANT CHANGES
- A  new rendering  module has  been  added to  create 8-bit  Signed
Distance Field (SDF)  bitmaps for both outline  and bitmap glyphs.
The new  rendering mode is called  `FT_RENDER_MODE_SDF`, the pixel
mode is  `FT_PIXEL_MODE_GRAY8`, and the corresponding  raster flag
is `FT_RASTER_FLAG_SDF`.
This work was Anuj Verma's GSoC 2020 project.
- A new, experimental API is  now available for surfacing properties
of 'COLR' v1  color fonts (as the name says,  this is an extension
to  the  'COLR' table  for  outline  color  fonts using  the  SFNT
container  format).   'COLR'  v1  fonts are  a  recently  proposed
addition to OFF and OpenType; specification work currently happens
in
https://github.com/googlefonts/colr-gradients-spec/
'COLR'  v1 …
=> freetype: update to 2.11.1

packages/linux/udev.d/40-modeswitch.rules
[    2.325991@0] usb 1-1.1: new high-speed USB device number 3 using xhci-hcd
[    2.486315@0] usb 1-1.1: New USB device found, idVendor=0bda, idProduct=1a2b
[    2.486319@0] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.486321@0] usb 1-1.1: Product: DISK
[    2.486323@0] usb 1-1.1: Manufacturer: Realtek
[    2.487139@0] usb-storage 1-1.1:1.0: USB Mass Storage device detected
[    2.487397@0] scsi host0: usb-storage 1-1.1:1.0
[    5.906100@2] usb 1-1.1: reset high-speed USB device number 3 using xhci-hcd
[    6.054094@0] usb 1-1.1: device firmware changed
[    6.054633@0] usb 1-1.1: USB disconnect, device number 3
[    6.218828@0] usb 1-1.1: new high-speed USB device number 5 using xhci-hcd
[    6.366480@0] usb 1-1.1: New USB device found, idVendor=0bda, …
=> linux: add udev rule to switch mode on Realtek RTL8821CU devices

packages/graphics/mesa/package.mk
release notes:
- https://docs.mesa3d.org/relnotes/21.3.4.html
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/relnotes/21.3.4.rst
Bug fixes
- i965: gen5 exposes EXT_texture_integer incorrectly
- [radeonsi, regression, bisected]: Rendering issues with Factorio
- mesa >= 21.x (with llvmpipe) will break the game JVGS
- Panfrost - RK3399 - FACTORIO - glitches everywhere
- Baldurs Gate 3 (Patch 6) - ribbon-like artifacts on textures
- Game Starsector crashes under certain circumstances with mesa 21.3.+
- FreeSpace models incorrectly rendered on Polaris cards, causing system freeze
- Incomplete evaluation of nested DEFINE macros
- [r300g, bisected] piglit glsl-fs-discard-04 fails
- Panfrost G52 Firefox terrible glitches on youtube playback
=> mesa: update to 21.3.4

packages/network/samba/package.mk
update 4.13.15 (2021-12-15) to 4.13.16 (2022-01-10)
release notes:
- https://www.samba.org/samba/history/samba-4.13.16.html
- https://www.samba.org/samba/security/CVE-2021-43566.html
=> [le11] samba: update to 4.13.16

distributions/LibreELEC/options, packages/audio/espeak-ng/package.mk, packages/mediacenter/kodi/package.mk
The eSpeak program was removed for unknown reasons, and it makes impossible to make LibreELEC accessible without a default TTS. Added eSpeak-NG, the improved and updated version of eSpeak.
=> [LE10] eSpeak-NG: initial package

distributions/LibreELEC/options
The espeak-ng package doesn't build so disable it until that's fixed
=> distro: disable espeak

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
This fixes the ac3 transcoding bug https://forum.libreelec.tv/thread/24741-librelec-nightly-dolby-digital-transcoding-bug/
Runtime tested on RPi4, DTS to AC3 transcoding worked fine
=> kodi: update to e976cd0
