LibreELEC/LibreELEC.tv

distributions/LibreELEC/options

I've uploaded *all* of the necessary sources to the new DISTRO_SRC url.
There are probably a couple that I missed, so let me if something is missing.
Add-ons I will upload tomorrow.

LibreELEC/options: change source and add-on url

---

packages/mediacenter/LibreELEC-settings/package.mk

This will allow people to build after #6

LibreELEC-settings: update to 659a94c

---

config/path
packages/sysutils/systemd/package.mk
packages/x11/driver/xf86-video-nvidia-legacy/package.mk
packages/x11/driver/xf86-video-nvidia/package.mk
scripts/extract
scripts/get
scripts/unpack

@MilhouseVH are you happy with this currently?

Add PKG_SOURCE_NAME for non-standard package tarballs

---

packages/tools/installer/scripts/installer

also, OE->LE rebranding
Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>

installer: add notification dialog upon completion of install

---

packages/tools/installer/scripts/installer

Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>

installer: OE->LE text replacement

---

packages/network/samba/config/smb.conf

Spotted by "Mario S." in LE forums. Thanks :)

samba: change server name to LibreELEC

---

projects/RPi/patches/kodi-theme-Confluence/kodi-theme-Confluence-001-jarvis-rbp-backports.patch
projects/RPi/patches/kodi/kodi-001-jarvis-rbp-backports.patch
projects/RPi2/patches/kodi-theme-Confluence/kodi-theme-Confluence-001-jarvis-rbp-backports.patch
projects/RPi2/patches/kodi/kodi-001-jarvis-rbp-backports.patch

Not yet build tested, will do that later today.

RPi/RPi2: Linux and Kodi Updates

---

packages/sysutils/busybox/scripts/fs-resize
packages/sysutils/busybox/scripts/init

this is more concise on-screen and avoids calling my box a computer, which it is, but also isn't :)

installer: not all computers are computers

---

projects/imx6/filesystem/usr/lib/systemd/system/serial-console.service

projects/imx6: enable cursor in serial console service

---

projects/RPi/patches/kodi/kodi-001-jarvis-rbp-backports.patch
projects/RPi2/patches/kodi/kodi-001-jarvis-rbp-backports.patch

Hopefully this will be the final set of updates for RPi before we head into Beta.
The Jarivs commits include the fix for stuttering when "sync playback to display" is disabled.

RPi/RPi2: Linux 4.4.6 and Kodi Jarvis updates

---

packages/tools/u-boot/package.mk
packages/tools/u-boot/scripts/update.sh
projects/imx6/patches/u-boot/012-hb1-fb-device.patch

hide dd output when updating bootloader
add patch for kernel 4.4

u-boot: update to u-boot-imx6-408544d for imx6 project

---

packages/devel/libcec/patches/libcec-03-amlogic-support.patch
packages/devel/libcec/patches/libcec-PR208.patch
projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

This PR adds 2 libcec updates from @gdachs:
* https://github.com/Pulse-Eight/libcec/pull/208 - works as advertised with my AVR 
* updated WeTek kernel and libcec patches
Tested only with WeTek Play.

LibCEC patches update

---

packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk

Build and run-time tested on both RPi and Generic.

screensaver.shadertoy: Add package

---

packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/patches/pvr.vdr.vnsi-preset-picon-path.patch
packages/network/samba/config/smb.conf

- other path changes are made through the addons

preset directories and paths for picons

---

README.md

An initial cleanup on the README text.

readme: update README.md text

---

packages/graphics/mesa/package.mk
packages/network/bluez/package.mk
packages/python/devel/setuptools/package.mk
packages/python/graphics/Pillow/package.mk
packages/python/graphics/Pillow/patches/Pillow-0001-crosscompiling.patch
packages/x11/other/fontconfig/package.mk
packages/x11/proto/inputproto/package.mk

Package updates

---

scripts/clean

As requested by @chewitt 
This allow cleaning one package for all projects.

scripts/clean: allow cleaning package for all projects

---

scripts/clean

scripts/clean: fixup previous commit

---

packages/addons/service/boblightd/package.mk

boblightd: bump version

---

packages/addons/service/hyperion/changelog.txt
packages/addons/service/hyperion/package.mk

- added a changelog.txt
- small cleanup

hyperion: updated description and bump version

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-live/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
packages/addons/addon-depends/vdr/package.mk

this fixes the libiconv location for VDR

vdr libiconv fixes

---

packages/addons/service/tvheadend/package.mk

tvheadend: buildfix

---

tools/distro-tool
tools/download-tool
tools/repo-tool

repo-tool is for dealing with addon repos. It allows one to bump the PKG_REV, update the addons.xml and sync the addon repos.
download-tool allows one to download all the necessary packages before building LibreELEC.
Setting the PROJECT and ARCH is require because there are package.mk files that use case statements to select the PKG_VERSION depending on the PROJECT or ARCH.

new scripts

---

packages/linux-firmware/brcmfmac_sdio-firmware-aml/system.d/brcmfmac_sdio-firmware@.service
packages/linux-firmware/brcmfmac_sdio-firmware-aml/udev.d/80-brcmfmac_sdio.rules

brcmfmac_sdio-firmware-aml: Fix built-in bluetooth on WeTek Core

---

packages/devel/glibc/package.mk

thanks @stefansaraev 
this allows to build in parrellel, I'd appreciate if someone else can test too @MilhouseVH

glibc: dont use perl/makeinfo. build parallel

---

scripts/image
scripts/mkimage

copy the dt-blob to image

---

packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk

screensaver.shadertoy and visualization.shadertoy

kodi-binary-addons: fix for imx6 project

---

projects/RPi/patches/kodi-theme-Confluence/kodi-theme-Confluence-001-jarvis-rbp-backports.patch
projects/RPi/patches/kodi/kodi-001-jarvis-rbp-backports.patch
projects/RPi2/patches/kodi-theme-Confluence/kodi-theme-Confluence-001-jarvis-rbp-backports.patch
projects/RPi2/patches/kodi/kodi-001-jarvis-rbp-backports.patch

RBP: Bump Kodi Jarvis backport (for LE7)

---

packages/textproc/tinyxml2/patches/tinyxml2-0001-really-disable-shared-build.patch

I guess we need this backported too?

tinyxml2: really disable shared

---

packages/textproc/tinyxml2/patches/tinyxml2-0001-really-disable-shared-build.patch

tinyxml2: really disable shared (backport)

---

packages/addons/addon-depends/go/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch

this also updates golang to 1.6.2

docker: update to 1.11.0

---

packages/addons/addon-depends/go/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch

backport of #193 

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

RBP: Update RPi kernel and firmware (LE7 backport)

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/go/patches/go-0001-add-ca-cert-location.patch
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/package.mk
packages/addons/service/docker/source/systemd/service.system.docker.service

docker: fix build for 1.11.0

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/go/patches/go-0001-add-ca-cert-location.patch
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/package.mk
packages/addons/service/docker/source/systemd/service.system.docker.service

backport of #209 

---

packages/mediacenter/LibreELEC-settings/package.mk

updated to get the skinning changes

settings: bump to v0.7.2

---

packages/addons/script/script.config.vdr/package.mk

script.config.vdr: update to 1.1.1

---

packages/addons/script/script.config.vdr/package.mk

backport of #212

---

tools/repo-tool

see #191 for the output when used with this PR

repo-tool: add ability to update PKG_REPO_VERSION

---

packages/addons/script/script.config.vdr/package.mk

script.config.vdr: update to 1.1.2

---

packages/addons/script/script.config.vdr/package.mk

- fix reading lines from sources.conf in the right order

script.config.vdr: update to 1.1.3

---

packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk

kodi-binary-addons: update to latest Jarvis versions

---

packages/network/bluez/package.mk
packages/network/bluez/system.d/bluetooth.service

backport of #203

---

projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

backport of #230 

---

packages/tools/mtools/patches/mtools-05-fix-install.patch

should fix occasional mtools installation problems few of us had

mtools: removes installing of floppyd, manual and info

---

projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

WeTek_Core/WeTek_Play: fix new cec driver patch

---

packages/addons/service/tvheadend/source/bin/tv_grab_file
packages/addons/service/tvheadend42/source/bin/tv_grab_file

This fixes detection of the tv_grab_file script, that can be configured through addon settings from Kodi.

tvheadend xmltv fix

---

packages/addons/tools/dvb-tools/package.mk
packages/addons/tools/multimedia-tools/package.mk
packages/addons/tools/network-tools/package.mk
packages/addons/tools/system-tools/package.mk

@lrusak pls have a look if nice enough

addon-tools: add packages list to description

---

packages/mediacenter/kodi/config/appliance.xml

This is needed by Kodi 17.0alpha2 now that various settings have moved around following the Settings reorg.

kodi: Update appliance.xml after Settings reorg

---

packages/textproc/tinyxml2/patches/tinyxml2-0001-really-disable-shared-build.patch

- patch needs mixed line endings

tinyxml2: fix disable shared patch

---

packages/linux-drivers/RTL8192CU/patches/RTL8192CU-add_more_products.patch

see, see, https://forum.libreelec.tv/thread-236-post-1814.html

RTL8192CU: add Netgear WNA1000Mv2 id

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch

backport of #280 

---

packages/mediacenter/kodi/patches/kodi-100.02-add-libreelec.tv-RSS-news.patch

This add the libreelec.tv rss feed to kodi

kodi: add libreelec.tv RSS feed

---

packages/mediacenter/kodi/patches/kodi-100.02-add-libreelec.tv-RSS-news.patch

backport of #300 

---

projects/Odroid_C2/patches/u-boot/u-boot-0001-set-default-boot-options.patch

This fixes the u-boot bootloop issue.

Odroid_C2/u-boot: adjust u-boot patch

---

packages/lang/Python/package.mk
packages/lang/Python/patches/Python-2.7.11-017-link-curses-module-against-termcap.patch

@MilhouseVH can you include this in your test builds?
we link conman and bluez with readline so might as well with Python

Python: build readline and curses modules

---

projects/Odroid_C2/patches/u-boot/u-boot-0001-set-default-boot-options.patch

Hopefully this is the last time.....

Odroid_C2/u-boot: really fix the u-boot patch this time

---

packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.smoothstream/package.mk
packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.njoy/package.mk
packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk

kodi-binary-addons: update to latest versions

---

packages/addons/addon-depends/jasper/package.mk
packages/addons/addon-depends/jasper/patches/jasper-1.900.1-security_fixes-2.patch
packages/addons/browser/chromium/package.mk

Update repo version in package.mk and add Jasper (removed in error during the update to Krypton) to addon-depends so that Chromium builds for the 8.0 repo.

fix chromium for 8.0 repo

---

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-05-fix-AP-timeout.patch
packages/linux-drivers/RTL8812AU/patches/RTL8812AU-06-disable-power-saving.patch

RTL8812AU: Fix AP timeout and disable power saving

---

packages/sysutils/busybox/package.mk
packages/sysutils/systemd/scripts/systemd-machine-id-setup

systemd: fix machine-id uniqueness

---

packages/addons/driver/sundtek-mediatv/changelog.txt
packages/addons/driver/sundtek-mediatv/package.mk
packages/addons/driver/sundtek-mediatv/source/system.d/driver.dvb.sundtek-mediatv.service

sundtek-mediatv: bugfix for wait for network

---

packages/network/bluez/patches/bluez-11_sixaxis-fix-PID-navigation-controller.patch
packages/network/bluez/patches/bluez-12_sixaxis-add-support-for-setting-SDP-record.patch
packages/network/bluez/patches/bluez-13_sixaxis-provide-dualshock-3-SDP-record.patch
packages/network/bluez/patches/bluez-14_sixaxis-remove-not-needed-checks.patch
packages/network/bluez/patches/bluez-15_sixaxis-fix-multi-line-comments-style.patch
packages/network/bluez/patches/bluez-20-sixaxis-autotrust.patch

backport of #351 

---

packages/addons/addon-depends/system-tools-depends/lm_sensors/package.mk
packages/addons/service/syncthing/package.mk
packages/addons/tools/system-tools/package.mk

backport of #354 

---

packages/network/bluez/patches/bluez-11_sixaxis-fix-PID-navigation-controller.patch
packages/network/bluez/patches/bluez-12_sixaxis-add-support-for-setting-SDP-record.patch
packages/network/bluez/patches/bluez-13_sixaxis-provide-dualshock-3-SDP-record.patch
packages/network/bluez/patches/bluez-14_sixaxis-remove-not-needed-checks.patch
packages/network/bluez/patches/bluez-15_sixaxis-fix-multi-line-comments-style.patch
packages/network/bluez/patches/bluez-20-sixaxis-autotrust.patch

Patch bluez to enable DualShock 3 auto pairing

---

packages/mediacenter/LibreELEC-settings/package.mk

This include all the estuary changes.

LibreELEC-settings: update to latest master

---

.gitmodules

@lrusak forgotten to commit that
this remove the oe unofficial addon git repo

packages/unofficial: remove git submodule

---

scripts/image

Git makes this change looks a bit scary, but it's basically just adjusting the indent for the if statements.
@chewitt give this a test please

scripts/image: make the images as well when running make noobs

---

.gitmodules

packages/unofficial: remove git submodule

backport of #375

---

packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk

some package cleanup @awiouy take note ;)

squeezelite: cleanup package

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/dtc/package.mk

needed by dtparam
```
./dtparam iqaudio-dac=on
sh: dtc: not found
* Failed to read active DTB
```

dtc: add package

---

packages/addons/script/moonlight/package.mk

moonlight: bump PKG_REV

---

packages/sysutils/udevil/udev.d/95-udevil-mount.rules

see http://www.matthuisman.nz/2015/10/remove-libreelec-file-manager-extra-sources.html for details

udevil: prevent noobs partitions from auto-mounting

---

packages/sysutils/udevil/udev.d/95-udevil-mount.rules

[backport] udevil: prevent noobs partitions from auto-mounting

---

packages/linux/patches/4.6/linux-231-Terratec-Cinergy-S2-Rev.3.patch

linux: add support for Terratec Cinergy S2 Rev.3

---

packages/linux/patches/4.4.7/linux-232-Terratec-Cinergy-S2-Rev.3.patch.patch

linux: add support for Terratec Cinergy S2 Rev.3

backport of #402

---

packages/addons/service/mpd/changelog.txt
packages/addons/service/mpd/package.mk

@lrusak cleanup of the addon for master (pls gave a look for long and short description - the a/an problem)

mpd: cleanup and change descriptions

---

packages/addons/service/mpd/package.mk

backport of #415

---

packages/addons/service/mpd/package.mk

mpd: fix description

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

This enables upgrading Syncthing from within Syncthing.
Please commit and backport.

Syncthing: enable automatic upgrades

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

Syncthing: enable automatic upgrades (backport of #418)

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

just some small fixes, https://github.com/docker/docker/releases/tag/v1.11.2

docker: update to 1.11.2

---

packages/tools/mtools/patches/mtools-01-fix-creation-of-dot-directories.patch

mtools: Fix creation of dot directories (. and ..) [backport]

---

packages/tools/bcm2835-bootloader/scripts/update.sh

RPi: Add a cleanup step (backport)

---

scripts/mkimage

Later will backport to 7.0 too.

scripts/mkimage: check filesystem on system partition

---

packages/addons/service/mpd/package.mk

mpd: enable build from clean

---

packages/addons/addon-depends/emby-depends/imagemagick/package.mk

@islipfd19: updated to point to an available source tarball.

imagemagick: update version

---

packages/addons/addon-depends/unclutter/package.mk
packages/addons/browser/chromium/changelog.txt
packages/addons/browser/chromium/package.mk
packages/addons/browser/chromium/source/bin/chromium
packages/addons/browser/chromium/source/resources/language/English/strings.xml
packages/addons/browser/chromium/source/resources/settings.xml

@islipfd19 This builds and runs on my RPi3. Would you known how to wire it to Chromium?

unclutter: initial package

---

packages/addons/addon-depends/unclutter/package.mk
packages/addons/browser/chromium/changelog.txt
packages/addons/browser/chromium/package.mk
packages/addons/browser/chromium/source/bin/chromium
packages/addons/browser/chromium/source/resources/language/English/strings.xml
packages/addons/browser/chromium/source/resources/settings.xml

Backport of #466

---

packages/sysutils/systemd/package.mk

see #470 fix journal truncation on time jumps

Backport of #470

---

packages/linux-firmware/wlan-firmware/package.mk

wlan-firmware: update to wlan-firmware-0.0.32

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk

@chewitt pls merge if you haven't build the addons yet, if you build them I bump the rev too

vdr-addon: update satip plugin

---

scripts/image

not sure if this is a desired backport but here it is

make the images as well when running make noobs

---

packages/mediacenter/kodi-binary-addons/inputstream.mpd/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.smoothstream/package.mk
packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk
packages/mediacenter/kodi-theme-Estuary/package.mk
packages/mediacenter/kodi/package.mk

Bump binary addons. Add inputstream.rtmp.

kodi: update to 17.0 alpha2 d9fd774

---

packages/addons/service/hyperion/patches/hyperion-0002-fix-isnan-member-std.patch

error: '__builtin_isnan' is not a member of 'std'

hyperion: fix compile error

---

packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-theme-Estuary/package.mk
packages/mediacenter/kodi/package.mk
tools/mkpkg/mkpkg_kodi

Final 17.0-alpha2 revision. Mirror updated.

kodi: 17.0 alpha2 f3ca4eaf9

---

packages/linux-firmware/cpu-firmware/package.mk

Release. Intel CPU microcode update. 20160607 (1.30)

update cpu-firmware to latest release

---

packages/sysutils/amremote/package.mk

- Fix issues when compiled for aarch64

amremote update to latest d4f6458

---

packages/sysutils/amremote/scripts/remote-config

Update remote-config to check first in user defined remote.conf

Backport of #550

---

packages/addons/driver/sundtek-mediatv/changelog.txt
packages/addons/driver/sundtek-mediatv/package.mk
packages/addons/driver/sundtek-mediatv/source/bin/sundtek-mediatv.start
packages/addons/driver/sundtek-mediatv/source/bin/sundtek-update-driver.sh
packages/addons/driver/sundtek-mediatv/source/resources/language/English/strings.xml
packages/addons/driver/sundtek-mediatv/source/resources/language/German/strings.xml
packages/addons/driver/sundtek-mediatv/source/resources/settings.xml

show driver version in addon settings
allow update for aarch64 architecture
german translation

sundtek-mediatv: update driver to latest version on first install

---

packages/addons/driver/sundtek-mediatv/changelog.txt
packages/addons/driver/sundtek-mediatv/package.mk
packages/addons/driver/sundtek-mediatv/source/bin/sundtek-mediatv.start
packages/addons/driver/sundtek-mediatv/source/bin/sundtek-update-driver.sh
packages/addons/driver/sundtek-mediatv/source/resources/language/English/strings.xml
packages/addons/driver/sundtek-mediatv/source/resources/language/German/strings.xml
packages/addons/driver/sundtek-mediatv/source/resources/settings.xml

show driver version in addon settings
german translation

backport of #559 sundtek-mediatv: update driver to latest version on first install

---

packages/addons/service/tvheadend42/patches/tvheadend42-03_fix_x264_url.patch

@chewitt should fix the build problem

tvheadend42: fix x264 url

---

packages/compress/zlib/package.mk

Thiw will add libminizip.a to sysroot so that some programs can link to it.

zlib : Add libMinizip build to package

---

packages/sysutils/lirc/udev.d/98-lircd.rules

from https://forum.libreelec.tv/thread-1079.html

lirc: add Atric IR-Wakeup-USB support

---

scripts/image

Same PR like https://github.com/LibreELEC/LibreELEC.tv/pull/574 for master.

Fix NAND auto installs on WeTek devices

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/go/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/patches/docker-001-use-addon-storage-location.patch
packages/addons/service/docker/source/config/docker.conf
packages/addons/service/docker/source/systemd/service.system.docker.service

backport of #557 (docker: update to 1.12.0)

---

packages/tools/u-boot/scripts/update.sh

As the name says, backport of #586

u-boot: Fix update.sh script for imx6 (backport of #586)

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

backport of #589  docker: include docker-proxy

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

fixes a bug as reported in https://forum.libreelec.tv/thread-1143.html

docker: include docker-proxy

---

packages/mediacenter/kodi/patches/kodi-999.99-PR10164-add-aetempo-filter.patch

Kodi is a moving target, particularly for RPi...

RPi: Fix Kodi build failure due to aetempo commits

---

projects/imx6/patches/kodi/kodi-100-krypton-from-mk01.patch

confirmed to be working very well

projects/imx6: update kodi patch for 17.0-alpha3-fc46cf2

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

Builds and runs here. I hope it now builds everywhere :D

syncthing: upgrade to 0.14.3

---

packages/sysutils/busybox/patches/busybox-04-default-to-universe-scope-fix-9141.patch

This is a bugfix for busybox 1.25.0 until https://bugs.busybox.net/show_bug.cgi?id=9141 is fixed, which I'm assuming won't be any time soon.
See: http://forum.kodi.tv/showthread.php?tid=269815&pid=2388388#pid2388388

busybox: Default to UNIVERSE scope, fixes 9141

---

packages/addons/service/dispmanx_vnc/package.mk
packages/addons/service/emby/package.mk
packages/addons/service/inadyn/package.mk
packages/addons/service/syncthing/package.mk
packages/addons/service/tinc/package.mk
packages/addons/tools/mono/package.mk

Cosmetic changes.
@cvh would you please be so kind to review?

addons: clean up

---

packages/addons/service/vdr-addon/source/bin/vdr.start
packages/addons/service/vdr-addon/source/resources/settings.xml
packages/addons/service/vdr-addon/source/settings-default.xml

add option/setting to start satip vdr plugin with specified number of devices

Add satip devices option

---

packages/addons/README.md

@lrusak pls have a look and hit the button if okay - the gang had already a look

addons: add doc for addon template

---

packages/addons/service/spotify-connect-web/changelog.txt
packages/addons/service/spotify-connect-web/package.mk
packages/addons/service/spotify-connect-web/source/bin/spotify-connect-web.start
packages/addons/service/spotify-connect-web/source/resources/language/English/strings.po
packages/addons/service/spotify-connect-web/source/resources/settings.xml
packages/addons/service/spotify-connect-web/source/settings-default.xml
packages/addons/service/spotify-connect-web/source/wizard.py

Work in progress, needs testing

spotify-connect-web: rework

---

packages/addons/service/webgrabplus/changelog.txt
packages/addons/service/webgrabplus/package.mk
packages/addons/service/webgrabplus/source/bin/webgrabplus.start

The home folder of the addon is not acessible to other addons.
Therefore copying the generated epg files to /storage/downloads/webgrabplus
Users' requests

webgrabplus: add user defined pre/post processing

---

packages/addons/addon-depends/xdotool/package.mk
packages/addons/browser/chromium/changelog.txt
packages/addons/browser/chromium/package.mk

chromium: add xdotool

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-dvbapi/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
packages/addons/addon-depends/vdr/patches/vdr-20_Implement-H.265-frame-parser.patch
packages/addons/service/vdr-addon/changelog.txt
packages/addons/service/vdr-addon/package.mk

added patch for VDR and updated VNSI
tested with DVB-S2 S19.2E and S13.0E 4k channels

VDR with 4k/HEVC support

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

Backport of #544, #610 and #613.
Update to latest version of Syncthing

syncthing: update to 0.14.4

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk
packages/addons/service/webgrabplus/package.mk
packages/addons/tools/mono/changelog.txt
packages/addons/tools/mono/package.mk
packages/addons/tools/mono/patches/mono-01.debian-changes.patch

Work in progress:
Latest stable mono release builds static for arm and x86_64.
Not worth pushing without aarch64.
If someone knows where I could find the patches required to build mono 4 for aarch64, please let me know ;)

mono: update to 4.2.1.102

---

packages/addons/service/spotify-connect-web/changelog.txt
packages/addons/service/spotify-connect-web/package.mk
packages/addons/service/spotify-connect-web/source/bin/spotify-connect-web.start
packages/addons/service/spotify-connect-web/source/resources/language/English/strings.po
packages/addons/service/spotify-connect-web/source/resources/settings.xml

enables passwordless/mutiuser login

spotify-connect-web: add avahi login

---

packages/multimedia/ffmpeg/package.mk

adds x11grab_xcb, which supersedes x11grab
@piotrasd please close #523 and test if this works

ffmpeg: add indev x11grab_xcb

---

packages/addons/addon-depends/emby-depends/imagemagick/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk
packages/addons/service/webgrabplus/package.mk
packages/addons/tools/mono/changelog.txt
packages/addons/tools/mono/package.mk
packages/addons/tools/mono/patches/mono-01.debian-changes.patch

If source of imagemagick is not available anymore, use that of master

Backport of Mono, Emby and WebGrab+Plus

---

config/functions
config/path
scripts/image
scripts/unpack

This stuff should never have been merged in the first place.
Let me know if I missed anything.

cleanup: clean build scripts to make more reproducible builds

---

packages/addons/service/webgrabplus/changelog.txt
packages/addons/service/webgrabplus/package.mk
packages/addons/service/webgrabplus/source/bin/webgrabplus.start

This updates mdb ini files, and fixes mdb post-processing

webgrabplus: update mdb ini files

---

packages/network/connman/patches/connman-06-fix-dns-ordering.patch

Picked from OSMC's repo - @islipfd19 please test this solves the issue you're seeing

connman: fix DNS ordering

---

packages/addons/service/tvheadend/changelog.txt
packages/addons/service/tvheadend/package.mk

- fixes picons download from Tvh server

tvheadend42: update to 4.0.9-12

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

backport of #691 (docker: update to 1.12.1)

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

docker: update to 1.12.1

---

packages/linux-firmware/dvb-firmware/package.mk

dvb-firmware: update to 1.1.0

---

packages/addons/service/rsyslog/changelog.txt
packages/addons/service/rsyslog/package.mk
packages/addons/service/rsyslog/source/default.py
packages/addons/service/rsyslog/source/settings-default.xml

Version bump to 102
Tested on WeTek hub

Rsyslog: add first run wizard configuration menu

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-streamdev/patches/vdr-plugin-streamdev-01_4k_hevc_support.patch
packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
packages/addons/service/vdr-addon/changelog.txt
packages/addons/service/vdr-addon/package.mk

- add streamdev HEVC support
- update VNSI to 1b96c6a
- update Sat>IP plugin to db0c18b

vdr-addon: update plugins

---

packages/tools/u-boot-v2/package.mk
packages/tools/u-boot-v2/patches/u-boot-v2-010-tbs2910.patch
packages/tools/u-boot-v2/patches/u-boot-v2-020-udoo.patch
packages/tools/u-boot/package.mk
projects/imx6/options

everything is installed from main u-boot package (files from second package is copied there)
needed for different systems
For better organization of this two packages I'm open for suggestions. But this one is working for me for a long time.

u-boot: build second u-boot package for imx6 project

---

packages/addons/addon-depends/moonlight-common-c/package.mk
packages/addons/addon-depends/moonlight-embedded/package.mk
packages/addons/script/moonlight/changelog.txt
packages/addons/script/moonlight/package.mk

updates to latest version
- should fix some major problems reported (waiting for tester feedback)
- added changelog.txt :trollface:
- reworded description to fit our "standards"

moonlight: update addon

---

packages/addons/addon-depends/moonlight-common-c/package.mk
packages/addons/addon-depends/moonlight-embedded/package.mk
packages/addons/script/moonlight/changelog.txt
packages/addons/script/moonlight/package.mk

moonlight: update addon
updates to latest version
- should fix some major problems reported (waiting for tester feedback)
- added changelog.txt :trollface:
- reworded description to fit our "standards"

Backport of #725

---

packages/x11/driver/xf86-video-amdgpu/package.mk
packages/x11/driver/xf86-video-ati/package.mk

Background: http://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-1.1.1-Released

Package updates: xf86-video-amdgpu 1.1.1, xf86-video-ati 7.7.1

---

packages/graphics/mesa/package.mk
packages/lang/llvm/package.mk

this builds llvm-config for the host machine.

llvm: build llvm-config for host

---

packages/linux-drivers/gpu-aml/package.mk

thanks @stefansaraev 
@codesnake ok with you?

gpu-aml: simplify build. strip

---

packages/mediacenter/LibreELEC-settings/scripts/backup-restore
packages/mediacenter/LibreELEC-settings/scripts/factory-reset

Mainly cosmetic improvements of the messages we show during backup and reset.

backup: fix up messages

---

packages/addons/addon-depends/libvncserver/package.mk

Not sure if there are any other issues, but I'll leave this open for a bit until I flush them out.

fixups after cmake changes

---

scripts/build

scripts/build: use debug option for target instead of host

---

projects/WeTek_Core/filesystem/usr/lib/systemd/system/serial-console.service
projects/WeTek_Hub/filesystem/usr/lib/systemd/system/serial-console.service
projects/WeTek_Play/filesystem/usr/lib/systemd/system/serial-console.service

These devices have a nice UART connector. Let's make use of it.

projects/WeTek: add serial console service

---

projects/WeTek_Play_2/linux/linux.aarch64.conf

I'm not sure if anything else is needed as I don't have a device to test with.

WeTek_Play_2: set CONFIG_AML_AO_CEC=y

---

projects/imx6/kodi/advancedsettings.xml
projects/imx6/patches/RTL8812AU/RTL8812AU-010-compile-3.14.patch
projects/imx6/patches/kodi/kodi-050-from-openbricks.patch
projects/imx6/patches/kodi/kodi-100-master-fixes.patch
projects/imx6/patches/linux/3.14-mx6-sr/linux-800-from-openbricks.patch

imx6 updates

---

projects/imx6/options

Signed-off-by: Jérôme Benoit <jerome.benoit@grenouille.com>

Indentation fix for options file in i.MX6 project.

---

packages/graphics/libdrm/package.mk

https://www.phoronix.com/scan.php?page=news_item&px=Libdrm-2.4.71-Released

libdrm: update to libdrm-2.4.71

---

scripts/build

scripts/build: no need to setup toolchain twice and before really building

---

scripts/build

Thanks @stefansaraev if you want your name removed from the commit let me know.
I'd like to cleanup the stripping part too, but need some advice there.

scripts/build: cleanup

---

packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk

emby: update to 3.0.8100

---

config/addon/xbmc.python.module.xml
config/addon/xbmc.python.script.xml
config/addon/xbmc.service.pluginsource.xml
config/addon/xbmc.service.xml
scripts/create_addon

Simple enough, if someone has a better solution please let me know. I had a hard time figuring out the \n line endings in order for the sed command to work.
this changed in, https://github.com/xbmc/xbmc/pull/9351

scripts/create_addon: add changelog to new "news" item

---

packages/databases/sqlite/package.mk

http://phoronix.com/scan.php?page=news_item&px=SQLite-3.15-Released

sqlite: update to sqlite-autoconf-3150000

---

projects/imx6/options

now that there is RTL8812AU patch for older kernel

imx6: build all additional drivers

---

packages/addons/service/webgrabplus/changelog.txt
packages/addons/service/webgrabplus/package.mk
packages/addons/service/webgrabplus/source/bin/webgrabplus.run
packages/addons/service/webgrabplus/source/bin/webgrabplus.start
packages/addons/service/webgrabplus/source/resources/language/English/strings.po
packages/addons/service/webgrabplus/source/resources/settings.xml
packages/addons/service/webgrabplus/source/settings-default.xml
packages/addons/service/webgrabplus/source/system.d/service.webgrabplus.service

add system.d timer
update siteini.pack to 20161021
add license headers

webgrabplus: add system.d timer

---

packages/addons/addon-depends/containerd/package.mk
packages/addons/addon-depends/runc/package.mk
packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

Pretty trivial, I run time tested and it works fine.

docker: update to 1.12.2

---

packages/addons/driver/sapphire/changelog.txt
packages/addons/driver/sapphire/package.mk

@chewitt let me know if this gets it to build for you for aarch64 projects

sapphire: fix build and cleanup

---

packages/graphics/mesa/package.mk

mesa: update to 13.0.0

---

packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_DHT/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_SI1145/package.mk
packages/addons/libraries/adafruit-libraries/changelog.txt
packages/addons/libraries/adafruit-libraries/package.mk

@InuSasha take a look. DHT need's to be compiled

adafruit-libraries: include SI1145 library, update DHT install path

---

packages/sysutils/lirc/package.mk
packages/sysutils/lirc/system.d/lircd-defaults.service
packages/sysutils/lirc/system.d/lircd@.service

This is needed with https://github.com/LibreELEC/service.libreelec.settings/pull/38

lirc: allow disabling

---

packages/devel/cmake/package.mk
packages/devel/cmake/patches/cmake-000-disable-sslv3.patch
packages/devel/cmake/patches/cmake-001-disable-free-comp-methods.patch

Signed-off-by: Jérôme Benoit jerome.benoit@piment-noir.org

CMake: update to 3.6.2

---

projects/WeTek_Play_2/patches/linux/revert_default_dvb_core.patch
projects/WeTek_Play_2/patches/linux/wetek_dvb.patch

Update DVB patches for WeTek Play 2 according to the recent kernel update.

projects/WeTek_Play_2: Update DVB patches

---

packages/linux-drivers/RTL8812AU/patches/aarch64/RTL8812AU-02-fix-multiple-definitions.patch

Just running through after the big merges. Leave this open for a bit

build fixes

---

packages/addons/service/inadyn/package.mk

This reverts commit 67a26e96b07bdc20d375300b1e10d826c897a525.

Revert "inadyn: disable autoreconf"

---

config/docker/changelog.txt
config/docker/package.mk
config/docker/source/bin/docker
config/docker/source/default.py
config/docker/source/resources/language/English/strings.po
config/docker/source/resources/settings.xml
config/docker/source/system.d/docker.service
scripts/create_docker_package

This script enables to create a package for a docker addon by simply specifying docker options, eg
```
ARCH=arm scripts/create_docker_package --name=minisatip -e PGID=0 -e PUID=0 -e TZ=GMT -p 8875:8875 -p 554:554 -p 1900:1900/udp --device=/dev/dvb:/dev/dvb lsioarmhf/minisatip
```

script: create_docker_package

---

scripts/checkdeps

scripts/checkdeps: check for distro specific packages

---

packages/network/bluez/package.mk

contains some bug fixes for a2dp

bluez: updated to 5.43

---

packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk

inputstream.rtmp: fixes kodi crash on closing pvr.filmon channel

---

packages/addons/addon-depends/network-tools-depends/lftp/package.mk
packages/addons/addon-depends/network-tools-depends/lftp/patches/lftp-0001-link-readline-with-termcap.patch

this fixes the build failure with gcc6, not sure if I should bump network-tools also

lftp: update to 4.7.4

---

packages/addons/addon-depends/moonlight-embedded/patches/moonlight-embedded-0002-require-pthread.patch

There is probably a better way to do this, but this works.

moonlight-embedded: add patch to link against pthread

---

packages/addons/addon-depends/network-tools-depends/udpxy/package.mk

udpxy: fix build after gcc changes

---

packages/addons/addon-depends/network-tools-depends/lftp/package.mk

lftp: fix build after gcc changes

---

packages/addons/driver/steamcontroller/package.mk

steamcontroller: mute python compileall.py output

---

packages/audio/alsa-lib/package.mk
packages/devel/glib/package.mk
packages/devel/libirman/package.mk
packages/devel/libplist/package.mk
packages/graphics/libdrm/package.mk
packages/graphics/mesa/package.mk
packages/security/libressl/package.mk
packages/x11/lib/libX11/package.mk

@vpeter4 @escalade 
Thank you for reporting.
Please double check I did not miss packages that require autoreconf

re-enable autoreconf for packages that require it

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/source/bin/ctop
packages/addons/service/docker/source/default.py

I also added the ctop utility from https://github.com/yadutaf/ctop

docker: update to 1.12.3

---

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk

Decrypter lib was missing in the version before.

Inputstream.adaptive: include decrypter lib

---

projects/WeTek_Core/patches/libcec/libcec-00-amlogic-support.patch
projects/WeTek_Play/patches/libcec/libcec-00-amlogic-support.patch

Thanks to @GDachs for spotting the issue.

projects/WeTek_Play,WeTek_Core: fix CEC

---

packages/linux-drivers/brcmap6xxx-aml/package.mk

Not sure how I missed this..
should probably be merged ASAP

brcmap6xxx-aml: fix after /usr merge

---

packages/linux-firmware/brcmfmac_sdio-firmware-aml/patches/brcmfmac_sdio-firmware-aml-0001-install-firmware-in-usr.patch

brcmfmac_sdio-firmware-aml: use unified /usr

---

projects/imx6/options

imx6: remove dvbhdhomerun from additional drivers

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Add support for BCM2837 based RPi2.

RBP: Update firmware d760a4f (LE7)

---

config/version

Reverts LibreELEC/LibreELEC.tv#1042 as there's more to add

Revert "config: set version to devel"

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.8.13

linux: update to linux-4.8.13

---

packages/addons/addon-depends/moonlight-embedded/patches/moonlight-embedded-0003-fix-libcec4-compilation.patch

fixed upstream https://github.com/irtimmer/moonlight-embedded/issues/445
https://github.com/irtimmer/moonlight-embedded/commit/90bfcdcc4da4178b0fd6c6013947006cd1c07377

moonlight: add upstream patch to fix libcec 4.0.0 compatibility

---

packages/graphics/bcm2835-driver/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.dumb/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.njoy/package.mk
packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk
packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
packages/mediacenter/kodi-binary-addons/visualization.spectrum/package.mk
packages/mediacenter/kodi-theme-Estuary/package.mk
packages/mediacenter/kodi/package.mk
projects/RPi/patches/kodi/kodi-001-backport.patch
projects/RPi2/patches/kodi/kodi-001-backport.patch

I just wanted to get the ball rolling because I am taking over the Krypton bumps from @MilhouseVH 
We can either merge this and I can bump again next week when beta7 is released or we can just let this sit and update it later.
I'd rather get it in now so we can have less changes later.

kodi: update to 17.0-beta7-7581c4a

---

packages/linux-firmware/dvb-firmware/package.mk

- added all TBS firmwares
- added Geniatech T230C firmware

dvb-firmware: update to 1.2.0

---

packages/addons/browser/chromium/source/default.py

chromium: updated default.py to allow installing flash

chromium: updated default.py to allow installing flash

---

packages/addons/addon-depends/moonlight-common-c/package.mk
packages/addons/script/moonlight/changelog.txt
packages/addons/script/moonlight/package.mk

backport of #1070  (moonlight: bump depends and rebuild)

---

packages/addons/addon-depends/protobuf/package.mk

protobuf: fix path to CMakeLists.txt

---

packages/sysutils/atvclient/package.mk

leave open until I receive user confirmation that it works okay

atvclient: update for Krypton changes

---

packages/mediacenter/kodi/config/advancedsettings.xml
projects/RPi/kodi/advancedsettings.xml
projects/RPi2/kodi/advancedsettings.xml
projects/imx6/kodi/advancedsettings.xml

kodi: update advancedsettings.xml

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk
packages/addons/service/docker/source/default.py

This should fix the issue now that the systemd service path has now changed.

docker: add temporary cleanup method for old systemd service

---

create_tar.sh

create_tar.sh: remove a leftover reference to OpenELEC

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Bump to version that reverts problematic CEC code clean up.

RBP: update to firmware 87edb82

---

scripts/build

Dump the cmake command being executed which may assist with future debugging.

build: dump cmake/configure/make command and variables before building

---

projects/imx6/patches/kodi/kodi-050-from-openbricks.patch

as described in #1119 
Thanks to all involved.

imx6: update kodi patch (fix partially broken deinterlace)

---

packages/x11/driver/xf86-video-intel/package.mk

https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/log/

xf86-video-intel: update to 028c946

---

packages/linux/package.mk
packages/mediacenter/kodi/patches/kodi-999.16-amlogic_timing.patch

Please add "Don't merge" and "WIP"
vc-1 a/v sync issue resolved
mpeg4 a/v sync issue resolved
See https://github.com/LibreELEC/linux-amlogic/pull/37
and https://github.com/LibreELEC/linux-amlogic/pull/38

kodi: update amltiming patch

---

packages/linux-drivers/media_build/sources/media_build/backports/linux-202-lnbp22_patch_for_more_power_if_rotor.patch

see https://forum.libreelec.tv/thread-3381-post-25787.html#pid25787
for more info
This patch is from the original driver author, I found it in https://www.spinics.net/lists/linux-media/msg38226.html
I have tested it with TT S2-3650CI and a HH90 rotor and it works.

added lnbp22.c patch for more power

---

packages/sysutils/lirc/system.d/lircd-uinput@.service

@Raybuntu @escalade please test this

lirc: fix lircd-uinput@.service

---

config/functions
packages/mediacenter/kodi/package.mk
packages/multimedia/libdvdcss/package.mk
packages/multimedia/libdvdnav/package.mk
packages/multimedia/libdvdread/package.mk

Wow a solution without a patch! What a miracle!
Thanks for the tip @wsnipex!! :+1:

kodi: build libdvd* in the kodi depends

---

packages/sysutils/e2fsprogs/package.mk

Fixes writing to EXT4 filesystem with populatefs as described on forum: https://forum.libreelec.tv/thread-2586-post-27679.html

e2fsprogs: update to 1.43.3

---

packages/tools/populatefs/package.mk

populatefs: update to version 1.0

---

packages/addons/addon-depends/tini/package.mk

tini: fix cmake build

---

packages/linux-firmware/dvb-firmware/package.mk

backport of #1205

---

packages/mediacenter/kodi/scripts/kodi.sh

kodi: create sym link for latest crashlog [backport]

---

packages/mediacenter/kodi/package.mk

backport of #1236

---

scripts/checkdeps

Added support for install missing (host) packages for elementary os.

Elementaryos

---

packages/addons/service/mpd/changelog.txt
packages/addons/service/mpd/package.mk

backport of #1231

---

packages/addons/service/oscam/changelog.txt
packages/addons/service/oscam/package.mk

backport of #1229

---

packages/addons/service/tigervnc/changelog.txt
packages/addons/service/tigervnc/package.mk

backport of #1227

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk
packages/addons/service/tvheadend42/source/bin/tvheadend42.start
packages/addons/service/tvheadend42/source/resources/language/English/strings.xml
packages/addons/service/tvheadend42/source/resources/settings.xml

tvheadend42: update to 4.1.2415
- added custom start options to addon
- added FRITZ!Box Sat>IP server support to addon
- update to Tvheadend 4.1.2415
- fix debug if activated but nothing selected

backport of #1222

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

RBP: update to firmware debe2d2

---

projects/RPi/patches/kodi/kodi-001-backport.patch
projects/RPi2/patches/kodi/kodi-001-backport.patch

rebase required for current building

kodi: update RPi/RPi2 backports patch

---

packages/mediacenter/LibreELEC-settings/package.mk

settings: bump LE settings add-on to v0.8.8

---

packages/linux/package.mk
projects/RPi/linux/linux.arm.conf
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/linux/linux.arm.conf
projects/RPi2/patches/linux/linux-01-RPi_support.patch

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.6
Add support for SND_SOC_ADAU7002.

linux: update to linux-4.9.6

---

packages/graphics/libdrm/package.mk

as require mesa - bump to 2.4.75
https://cgit.freedesktop.org/mesa/mesa/commit/?id=b8acb6b1798151d1038acec035835243706a4a6a
tested

libdrm: update to 2.4.75

---

packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.steamcontroller/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.xarcade/package.mk

Could also probably use some cleanup but it's pretty straightforward

Retroplayer support add-ons

---

tools/mkpkg/update_binary-addons-retroplayer
tools/mkpkg/update_emulation

I use these to update all the emulators and the binary add-ons.

Retroplayer Support Scripts

---

packages/mediacenter/kodi-platform/package.mk
packages/mediacenter/p8-platform/package.mk
tools/mkpkg/update_binary-addons

Script error caused a couple of addons to update incorrectly.

kodi-binary-addons: bump missed addons

---

distributions/LibreELEC/options

LibreELEC/options: fix spelling mistake

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/patches/linux/linux-01-RPi_support.patch

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.8

linux: update to linux-4.9.8

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/linux/linux.arm.conf
projects/RPi/patches/linux/linux-01-RPi_support.patch
projects/RPi2/linux/linux.arm.conf
projects/RPi2/patches/linux/linux-01-RPi_support.patch

linux: update to linux-4.9.8 [LE8]

---

packages/emulation/libretro-beetle-saturn/package.mk
packages/emulation/libretro-mrboom/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.beetle-saturn/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.mrboom/package.mk

These currently only work for x86

add new retroplayer emulators

---

packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.octonet/package.mk
packages/mediacenter/kodi/package.mk
projects/RPi/patches/kodi/kodi-001-backport.patch
projects/RPi2/patches/kodi/kodi-001-backport.patch
tools/mkpkg/update_binary-addons

this is needed to put retroplayer stuff in sync

kodi: update to 4c792db

---

packages/emulation/libretro-beetle-pcfx/package.mk
packages/emulation/libretro-craft/package.mk
packages/emulation/libretro-desmume/package.mk
packages/emulation/libretro-mame/package.mk
packages/emulation/libretro-mame2000/package.mk
packages/emulation/libretro-mame2010/package.mk
packages/emulation/libretro-mame2014/package.mk
packages/emulation/libretro-mupen64plus/package.mk
packages/emulation/libretro-pcsx-rearmed/package.mk
packages/emulation/libretro-ppsspp/package.mk
packages/emulation/libretro-reicast/package.mk

retroplayer add-ons: add WeTek_Core support

---

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
packages/linux-drivers/media_build/sources/backports/linux-240-pctv452e_kernel_oops_in_4.9.patch

media_build: fix TT-S2-3600

---

packages/linux/package.mk

Some IR fixes and ethernet driver fixes

linux-amlogic: update to 83803a1

---

packages/addons/repository/repository.linuxserver.docker/changelog.txt
packages/addons/repository/repository.linuxserver.docker/package.mk
packages/addons/repository/repository.linuxserver.docker/sources/addon.xml

Backport of #1331 (change repo location for linuxserver addon zips)

---

packages/sysutils/v4l-utils/patches/v4l-utils-10-backport-streamzap-fix.patch
packages/sysutils/v4l-utils/patches/v4l-utils-24-fix-streamzap-keymap.patch

Fixes from #1330 backported to LE8

[LE8 backport] v4l-utils: fix issues with streamzap remote

---

packages/addons/service/docker/changelog.txt
packages/addons/service/docker/package.mk

docker: enable journald buildtag

---

config/version

config: set version to devel

---

packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk

to be merged after 8.0.0 release and config/version is set back to devel

kodi: updates to binary add-ons

---

packages/lang/Python/package.mk

Python: use -j1 for makeinstall_host [backport]

---

README.md

Changed some links.
Seems not to be possible for openelec.tv

Changed links inside README.md to 'https://...' if possible

---

packages/graphics/libraw/package.mk
packages/mediacenter/kodi-binary-addons/imagedecoder.raw/package.mk

This is the start of the imagedecoder add-ons.
ref, https://github.com/xbmc/xbmc/pull/11086

imagedecoder.raw: add add-on

---

packages/addons/service/lcdd/changelog.txt
packages/addons/service/lcdd/package.mk

Yet another attempt to make this work.
Do not merge

lcdd: update to 0.5.8

---

packages/addons/service/lcdd/changelog.txt
packages/addons/service/lcdd/package.mk

Yet another attempt to make this work.
Do not merge

Backport of #1275

---

packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/system.d/brcmfmac_sdio-firmware.service
packages/linux-firmware/brcmfmac_sdio-firmware-rpi/udev.d/90-rpi-add-serial.rules

brcmfmac_sdio-firmware-rpi: Implement Raspbian udev rules and btuart [backport]

---

packages/graphics/libdrm/package.mk

@MilhouseVH can you try this in a test build please?

libdrm: adjust default options

---

config/functions
packages/x11/xserver/xorg-server/package.mk
scripts/image

Backport of #1251, needed after #1423.
@escalade can you test this PR just to be sure?

cleanup: avoid using find command to determine package directory [backport]

---

tools/repo-tool

This just makes things easier.
I plan on reworking this whole script soonish. So this is just mid term solution.

repo-tool: add retroplayer support

---

packages/mediacenter/kodi/scripts/cputemp

Still needs some more work
would be nice if people could post the results of this script
```
#!/bin/bash
for i in /sys/class/hwmon/*; do
if [ ! -f "$i/name" ]; then
echo "$(basename $i): $(cat $i/device/name)"
for j in $i/device/temp*_input; do
if [ -f "$j" ]; then
echo "$(basename $j): $(($(cat $j) / 1000)) C"
fi
done
else
echo "$(basename $i): $(cat $i/name)"
for j in $i/temp*_input; do
if [ -f "$j" ]; then
echo "$(basename $j): $(($(cat $j) / 1000)) C"
fi
done
fi
done
```

kodi: adjust cputemp/gputemp script

---

tools/RPi/gen-rpi-kodi-patch.sh
tools/RPi/gen-rpi-linux-patch.sh

tools: fixup RPi gen scripts after devices

---

scripts/create_addon

create_addon: add device support

---

packages/linux-firmware/iwlwifi-firmware/package.mk

iwlwifi: udpate to ba301aa

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/Generic/linux/linux.x86_64.conf
projects/RPi/devices/RPi/linux/linux.arm.conf
projects/RPi/devices/RPi2/linux/linux.arm.conf
projects/RPi/patches/linux/linux-01-RPi_support.patch

4.10.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.10.5
4.10.6 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.10.6

linux: update to linux-4.10.6

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

This fixes the firmware reported in https://github.com/Hexxeh/rpi-firmware/issues/145
Includes couple of new linux commits for AudioInjector soundcard driver.

RPi: update linux backports and firmware bug fix

---

packages/addons/service/lcdd/changelog.txt
packages/addons/service/lcdd/package.mk
packages/addons/service/lcdd/patches/lcdd-0.5.6-dm140_henlar_v0.2.patch
packages/addons/service/lcdd/patches/lcdd-0.5.6-libftdi1.patch

Do not merge.
Would someone be so kind to check the patches for me, it is out of my league. Thanks.

lcdd: update to 466edd3

---

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-01-add_new_cards.patch

reported in https://forum.libreelec.tv/thread-7057.html - needs user confirmation of the fix before merging. If good I will add to master as well..

RTL8812AU: add device ID for TP-Link T4U ver 2

---

projects/imx6/patches/linux/4.4-xbian/linux-800-from-vero.patch

imx6/linux: kernel fixes from vero (forward port of #1436)

---

packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
packages/linux-drivers/media_build/sources/backports/linux-220-cx231xx-suspend-fix.patch

fixes suspend for cx231xx cards as seen here https://github.com/tbsdtv/linux_media/issues/40

media_build: fix suspend of cx231xx

---

packages/sysutils/busybox/config/transmission.conf
packages/sysutils/busybox/package.mk

pls have a look if it conflict with https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/systemd/package.mk#L219 (the only touching points of this)

busybox: cleanup unused config

---

packages/graphics/bcm2835-driver/package.mk

In our distro, mpv will now fetch a Rpi environment checking pkgconfig files. so this commit adds them to sysroot.

bcm2835 : deploy pkgconfig files as well

---

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk

routine bumping to pick-up new versions; several are being asked for in forums

kodi: bumps to binary-addons

---

packages/network/connman/patches/connman-07-fix-ip-forwarding.patch

Should resolve the issue when using LibreELEC as a WiFi Access Point.
Forum posts:
https://forum.libreelec.tv/thread-4066-post-46101.html#pid46101
https://forum.libreelec.tv/thread-2236-post-46262.html#pid46262
I'll include in nightly test builds. Can backport if needed (and confirmed fix).

connman: fix ipv4 IP Forwarding bug

---

packages/network/connman/patches/connman-07-fix-ip-forwarding.patch

connman: fix ipv4 IP Forwarding bug [backport]

---

packages/sysutils/e2fsprogs/package.mk

replaces #1514 to fix the build issue; this PR doesn't include the unnecessary fonts commit

e2fsprogs: bump to 1.43.3

---

packages/addons/addon-depends/qtbase/patches/qtbase-001-stdlib-error.patch

this solves a long-running build error in qtbase when building hyperion for Generic

qtbase: fix stdlib.h build error

---

packages/addons/addon-depends/emby-depends/ffmpegx/package.mk

this fixes creation of the emby add-on

ffmpegx: fix build issue after openssl change

---

packages/sysutils/tz/package.mk

timezone-data: update to 2017b

backport of #1519

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Latest kernel updates for 4.9.24 from `4.9.y-rebase`.
Switch to `stable` branch of RPi firmware.

linux: update RPi support patches and firmware [LE8]

---

packages/sysutils/busybox/scripts/createlog

createlog: bring sanity to kodi log order [backport]

---

packages/graphics/imx-gpu-viv/package.mk

Fixes thumbnails creation in kodi.
https://forum.libreelec.tv/thread-3462.html

imx-gpu-viv: update to galcore v5 on linux 4.4

---

packages/graphics/imx-gpu-viv/package.mk

Fixes thumbnails creation in kodi.
https://forum.libreelec.tv/thread-3462.html

imx-gpu-viv: update to galcore v5 on linux 4.4 [backport of #1603]

---

packages/linux-firmware/wlan-firmware/package.mk

wlan-firmware: update to wlan-firmware-cf02ad3

---

packages/addons/addon-depends/dvb-tools-depends/dvb-fe-tool/patches/dvb-fe-tool-01-add-libudev-depend.patch

dvb-fe-tool can now be build without systemd

dvb-fe-tool: add build dependency

---

projects/Odroid_C2/patches/u-boot/u-boot-0003-update_cec_simplink_wakeup.patch

Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/1611

Odroid_C2/u-boot: Make LG CEC (Simplink) wakeup work

---

projects/WeTek_Hub/linux/linux.aarch64.conf
projects/WeTek_Play_2/linux/linux.aarch64.conf

Update kernel config for WeTek Hub and WeTek Play 2 after recent kernel bump.

Update kernel config for WeTek Hub and WeTek Play 2

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-dvbapi/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
packages/addons/service/vdr-addon/changelog.txt
packages/addons/service/vdr-addon/package.mk

bump for https://github.com/LibreELEC/LibreELEC.tv/pull/1475

vdr-addon: update addon

---

packages/mediacenter/kodi-binary-addons/adsp.biquad.filters/package.mk
packages/mediacenter/kodi-binary-addons/adsp.freesurround/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.njoy/package.mk
packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
packages/mediacenter/kodi/package.mk
tools/mkpkg/update_binary-addons

I'll leave this open to accumulate add-on bumps as well

kodi: update to 17.2

---

packages/mediacenter/kodi/package.mk

kodi: use correct 17.2 githash

---

packages/graphics/bcm2835-driver/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-binary-addons/pvr.njoy/package.mk
packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
packages/mediacenter/kodi/package.mk
packages/multimedia/ffmpeg/patches/ffmpeg-99.1003-pfcd_hevc_optimisations.patch
packages/multimedia/ffmpeg/patches/ffmpeg-99.1008-73fde6f9f3d01f7fc0f3ae4b66f6c725f9fb1105.patch
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/kodi/kodi-000-revert-pr11222.patch
projects/RPi2/patches/kodi/kodi-000-revert-pr11222.patch

WIP - needs kodi rev and updated addons.
RPi firmware is from `stable` branch.

kodi: update to 17.3

---

packages/addons/addon-depends/rpi-tools-depends/lan951x-led-ctl/package.mk
packages/addons/tools/rpi-tools/package.mk

backport of #1653 (add lan951x-led-ctl)

---

packages/graphics/libdrm/package.mk
packages/graphics/mesa/package.mk

this adds support for hi10p hevc with vaapi.

mesa and libdrm update

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
packages/x11/driver/xf86-video-nvidia/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch

WIP: Don't merge until the kernel hits 4.11.4.
4.11.1 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.1
4.11.2 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.2
4.11.3 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.3
4.11.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.11.4

linux: update to linux-4.11.4

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk

+ use go:host instead of system:go

syncthing: update to 0.14.29 [backport]

---

packages/sysutils/e2fsprogs/package.mk

e2fsprogs: do not build fuse2fs [backport]

---

packages/addons/addon-depends/system-tools-depends/screen/package.mk
packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk

backport of #1678 (GNU screen color fixes)

---

packages/audio/alsa-lib/package.mk
packages/audio/alsa-utils/package.mk
packages/debug/libva-utils/package.mk
packages/graphics/mesa/package.mk
packages/multimedia/intel-vaapi-driver/package.mk
packages/multimedia/libva/package.mk

some alsa stuff is needed for kernel 4.12
the rest just include some small fixes.

minor package bumps

---

packages/addons/addon-depends/system-tools-depends/inotify-tools/package.mk

failed in same builds, with doxygen. Disable doxygen solves the problem

inotify-tools: build without doxygen

---

packages/sysutils/busybox/patches/busybox-04_fix_for_brain_damaged_http_servers.patch

Fixes broken wget:
https://bugs.busybox.net/show_bug.cgi?id=9471
https://bugs.busybox.net/show_bug.cgi?id=9981
Drop after next bump etc.

busybox: fix wget with brain-damaged http servers

---

packages/security/openssl/package.mk

1.0.2 changelog: https://www.openssl.org/news/cl102.txt (bit light on detail)
commit diff: https://github.com/openssl/openssl/compare/OpenSSL_1_0_2k...OpenSSL_1_0_2l

openssl: update to openssl-1.0.2l

---

packages/addons/service/mpd/changelog.txt
packages/addons/service/mpd/package.mk

to be in sync with 8.2 (no rev bump because master addons wasn't build at all)

mpd: update to 0.20.9

---

packages/linux-firmware/intel-ucode/package.mk

see, https://www.phoronix.com/scan.php?page=news_item&px=Intel-HT-Bug-KBL095
and, https://lists.debian.org/debian-devel/2017/06/msg00308.html

intel-ucode: update to 20170511

---

packages/addons/addon-depends/system-tools-depends/p7zip/package.mk
packages/addons/addon-depends/system-tools-depends/unrar/package.mk
packages/addons/tools/system-tools/changelog.txt
packages/addons/tools/system-tools/package.mk

system-tools: bump p7zip and unrar

---

packages/audio/alsa-lib/package.mk
packages/audio/alsa-utils/package.mk

alsa-lib/util update to latest (there are included changes for kernel 4.11-12)

alsa - update lib/util to latest

---

packages/devel/libcap/package.mk

should fix #1430 
ping @escalade @rinaldus

libcap: build without gperf

---

packages/multimedia/ffmpeg/patches/ffmpeg-99.1001-pfcd_hevc_optimisations.patch

This fixes the build issue after #1758

ffmpeg: include hevc optimisation patch from popcornmix

---

packages/addons/service/librespot/changelog.txt
packages/addons/service/librespot/package.mk

librespot: update addon

---

packages/mediacenter/LibreELEC-settings/package.mk

This bumps the settings to include the Samba change.

LibreELEC-settings: update to LibreELEC-settings-a40fb4f

---

packages/addons/service/librespot/changelog.txt
packages/addons/service/librespot/package.mk
packages/addons/service/librespot/patches/librespot-02_update_system_information_string.patch

This fixes yet another change in the Spotify API
Tested on RPi2.
Ready to merge

librespot: update system_information_string

---

packages/devel/netbsd-curses/package.mk

194ddef is the first version that builds after 0.2.1

netbsd-curses: update to 4c156be

---

packages/addons/addon-depends/system-tools-depends/htop/patches/htop-01_netbsd-curses_support.patch

backport of #1804

---

packages/devel/heimdal/package.mk
packages/network/samba/package.mk

samba/heimdal: update to samba-4.6.6 and heimdal-7.4.0 [backport]

---

packages/mediacenter/kodi/config/appliance.xml
packages/mediacenter/kodi/patches/kodi-999.18-PR12111-smbclient-changes-for-samba4.patch
packages/network/samba/patches/samba-951-backport-SMB3_11-default.patch

~~Updates the PR patch so we default to writing no extra config and autonegotiation is used~~

kodi: update PR12111 patch

---

packages/linux-firmware/intel-ucode/package.mk
packages/linux/package.mk

intel-ucode: update to intel-ucode-20170707 [backport]

---

packages/addons/service/librespot/changelog.txt
packages/addons/service/librespot/package.mk
packages/addons/service/librespot/patches/librespot-03_libreelec_hooks.patch
packages/addons/service/librespot/source/addon.py
packages/addons/service/librespot/source/bin/librespot.env
packages/addons/service/librespot/source/bin/librespot.onstart
packages/addons/service/librespot/source/bin/librespot.onstop
packages/addons/service/librespot/source/bin/librespot.start
packages/addons/service/librespot/source/default.py
packages/addons/service/librespot/source/resources/settings.xml
packages/addons/service/librespot/source/system.d/service.librespot.service

Displays artist and title in a notification

librespot: ux improvements

---

packages/network/avahi/config/resolv.conf
packages/network/avahi/config/samba.service
packages/sysutils/systemd/package.mk
packages/sysutils/systemd/scripts/userconfig-setup
packages/sysutils/systemd/system.d/userconfig.service

userconfig change should have been backported with samba.

userconfig: overwrite our sample files / avahi cleanup

---

packages/linux-firmware/iwlwifi-firmware/package.mk

See https://github.com/LibreELEC/iwlwifi-firmware/pull/7

iwlwifi-firmware: update to iwlwifi-firmware-53913d7

---

packages/graphics/libdrm/package.mk
packages/graphics/mesa/package.mk

mesa 17.2 includes many fixes and updates it should be tested thoroughly.

Mesa update

---

packages/databases/sqlite/package.mk

Tested on RPi2 and Generic, no issues.

sqlite: update to sqlite-autoconf-3200000

---

packages/sysutils/busybox/scripts/init

init: fix error handling during get_project_arch [backport]

---

packages/linux-drivers/RTL8192DU/package.mk
packages/linux-drivers/RTL8812AU/patches/RTL8812AU-kernel-4.11.9.patch
packages/linux/package.mk

linux: update to linux-4.11.12 [le82, Generic]

---

packages/mediacenter/LibreELEC-settings/package.mk

bump to pick-up the manual > auto change

settings: update to 4f81a2d

---

projects/WeTek_Hub/install/updater-script
projects/WeTek_Play_2/install/updater-script

Fix an issue on WeTek Hub and WeTek Play 2 when LE cannot boot after installing on top of Android Marshmallow.

[LE 8.2] Fix installation to internal storage on top of Android Marshmallow on WeTek Hub and WeTek Play 2

---

packages/linux/package.mk

Final update for libreelec-8.2.

linux: update to linux-4.9.43 [le82, RPi]

---

packages/network/samba/package.mk

samba: update to samba-4.6.7 [le82]

---

packages/addons/service/oscam/changelog.txt
packages/addons/service/oscam/package.mk

Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/1912

oscam: update to 11391

---

packages/addons/service/tvheadend42/changelog.txt
packages/addons/service/tvheadend42/package.mk

renamed addon `Tvheadend 4.2` -> `Tvheadend Server 4.2`

tvheadend42: update to 4.2.3-20

---

packages/network/samba/package.mk

Changelog: https://www.samba.org/samba/history/samba-4.6.7.html

samba: update to samba-4.6.7

---

scripts/mkimage

* drop .img extension for the open virtual appliance (cosmetic)
* change the default syslinux entry from installer to run for the open virtual appliance
Tested with VMware Player 12

build system: drop .img extension for the open virtual appliance

---

packages/network/connman/package.mk
packages/sysutils/dbus/package.mk

Package Updates: dbus 1.11.16, connman-1.35 [Backport]

---

packages/network/samba/scripts/smbd-config

samba: ensure new properties are populated on upgrade [backport]

---

packages/linux-drivers/RTL8812AU/package.mk

Adds ability to turn on/off LEDs.
Requested by user on forum.

RTL8812AU: update to RTL8812AU-8e7ccba

---

packages/network/libdnet/package.mk
packages/wayland/mtdev/package.mk

this is needed when building without LTO

build some more packages with fPIC

---

packages/network/wireless-regdb/package.mk

wireless-regdb: update to wireless-regdb-2017.03.07 [backport]

---

packages/sysutils/busybox/scripts/getedid

updated getedid script because of an issue

---

packages/network/samba/config/smb.conf
packages/network/samba/scripts/samba-config

samba: validate samba user config and don't use if legacy or incompatible [backport]

---

packages/x11/driver/xf86-video-amdgpu/package.mk
packages/x11/driver/xf86-video-ati/package.mk

not much here really but some tearfree fixes.

amd updates

---

packages/mediacenter/kodi-binary-addons/pvr.teleboy/package.mk

pvr.teleboy: new pvr addon

---

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk

with latest inputstream.adaptive the sub directory of libssd_wv.so changed

changed libssd_wv.so to correct sub directory

---

packages/sysutils/busybox/scripts/init

Backport of #1995, if you want this (if not close it).

init: recover from a failed upgrade [Backport]

---

tools/mkpkg/update_retroplayer-addons
tools/repo-tool

This adds device support to `repo-tool`
this uses `--single-branch` for doing a checkout in `update_retroplayer-addons`

some minor script updates

---

scripts/extract
scripts/unpack

scripts/unpack: avoid calling scripts/extract for each tarball pattern [backport]

---

packages/network/samba/package.mk

samba: update to samba-4.6.8 [backport]

---

packages/network/bluez/patches/bluez-21-blueborne-vulnerability.patch

This is the second element that needs fixing for the blueborne vulnerability.

bluez: add patch for CVE-2017-1000250

---

packages/linux/package.mk

Update Amlogic kernel to 3.14-c8c32b4.

linux: update amlogic-3.14 kernel to 3.14-c8c32b4

---

packages/mediacenter/kodi/scripts/kodi.sh

kodi: switch to using find to avoid argument limit

---

packages/mediacenter/LibreELEC-settings/package.mk

settings: bump to fix backup free-space calc

---

packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-systemd-services.patch

follow: https://github.com/xbmc/xbmc/pull/12839

kodi: fix build after PR2053

---

packages/addons/service/locale/changelog.txt
packages/addons/service/locale/package.mk
packages/addons/service/locale/source/default.py

This fixes the Locale add-on for LibreELEC 9.0.
I am looking forward to seeing it in the repository again.
Thank you in advance.

locale: include localedef

---

packages/audio/pulseaudio/package.mk

@fritsch I think this is all that is required yes?

pulseaudio: set remixing-use-all-sink-channels = no

---

packages/graphics/mesa/package.mk

mesa: update to 17.2.2

---

projects/Allwinner/options

U-Boot version in the project options does not exist. Fix it.

Allwinner: Fix U-Boot selection

---

packages/addons/addon-depends/rpi_ws281x/package.mk
packages/addons/service/hyperion/changelog.txt
packages/addons/service/hyperion/package.mk

hyperion: update to 1c21232

---

packages/mediacenter/kodi-binary-addons/game.libretro/package.mk

forgot to PR this a while ago.

game.libretro: but PKG_REV to 104

---

packages/x11/xserver/xorg-server/package.mk

Mostly security fixes.
https://www.phoronix.com/scan.php?page=news_item&px=xorg-server-1.19.5

xorg-server: update to xorg-server-1.19.5

---

packages/linux-drivers/RTL8188EU/package.mk

Backport of #2096
Add TP-Link TL-WN722N v2
Fix buffer overrun warning

RTL8188EU: update to c5113ff

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/linux/patches/default/linux-999-i915-implement-passthrough-colors.patch
packages/tools/bcm2835-bootloader/package.mk
projects/RPi/patches/linux/linux-01-RPi_support.patch
tools/distro-tool

Merge target: ~4.13.4~ 4.13.6
4.13.1 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.1
4.13.2 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.2
4.13.3 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.3
4.13.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.4
4.13.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.5
4.13.6 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.6

linux: update to linux-4.13.6

---

packages/network/wpa_supplicant/patches/wpa_supplicant-001-krack-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-002-krack-Prevent-reinstallation-of-an-already-in-use-group-ke.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-003-krack-Extend-protection-of-GTK-IGTK-reinstallation-of-WNM-.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-004-krack-Prevent-installation-of-an-all-zero-TK.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-005-krack-Fix-PTK-rekeying-to-generate-a-new-ANonce.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-006-krack-TDLS-Reject-TPK-TK-reconfiguration.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-007-krack-WNM-Ignore-WNM-Sleep-Mode-Response-without-pending-r.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-008-krack-FT-Do-not-allow-multiple-Reassociation-Response-fram.patch

wpa_supplicant: add security patches against KRACK attack

---

packages/network/wpa_supplicant/package.mk
packages/network/wpa_supplicant/patches/wpa_supplicant-001-krack-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-002-krack-Prevent-reinstallation-of-an-already-in-use-group-ke.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-003-krack-Extend-protection-of-GTK-IGTK-reinstallation-of-WNM-.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-004-krack-Prevent-installation-of-an-all-zero-TK.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-005-krack-Fix-PTK-rekeying-to-generate-a-new-ANonce.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-006-krack-TDLS-Reject-TPK-TK-reconfiguration.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-007-krack-WNM-Ignore-WNM-Sleep-Mode-Response-without-pending-r.patch
packages/network/wpa_supplicant/patches/wpa_supplicant-008-krack-FT-Do-not-allow-multiple-Reassociation-Response-fram.patch

[8.2] wpa_supplicant: update to 2.6 and add patches against KRACK attack

---

packages/devel/boost/package.mk

boost: update to 1.65.1, add chrono, date_time, python and random

---

packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk

libmediainfo exists in github.
I took the liberty to bump to it to the latest release.

libmediainfo: use github and update to 0.7.99

---

packages/network/samba/scripts/smbd-config

https://support.microsoft.com/en-us/help/4046019/guest-access-smb2-disabled-by-default-in-windows-10-server-2016

samba: fix authentication with Win10 Fall Creators Update

---

packages/graphics/mali-rockchip/package.mk
projects/Rockchip/devices/MiQi/options
projects/Rockchip/devices/MiQi/patches/linux/rockchip-4.4/linux-0001-miqi.patch

This PR adds basic support for MiQi device
Thanks to @Ntemis for testing this

MiQi: new device

---

packages/addons/service/touchscreen/package.mk

from version="8.2.100.100" to version="8.2.100"

touchscreen: fix addon version

---

scripts/image

scripts/image: restore old functionality

---

packages/addons/service/net-snmp/changelog.txt
packages/addons/service/net-snmp/package.mk
packages/addons/service/net-snmp/patches/net-snmp-0003-config.sub.patch

Hi,
This pull request give a fully functionnal net-snmp daemon.
See https://forum.libreelec.tv/thread/2997-snmpd/?postID=68955#post68955
Test on wetek play 2 and Rpi2 sucessfully on 8.2.0 release
I request pull to master , but making it available to libreleec 8 would be great !

Fix net-snmp addon build

---

packages/addons/service/net-snmp/changelog.txt
packages/addons/service/net-snmp/source/bin/snmpd.start

this fix this https://sourceforge.net/p/net-snmp/mailman/message/21333882/

Net-snmp addon : Avoid loading config two time

---

packages/network/samba/package.mk

Changelog: https://www.samba.org/samba/history/samba-4.6.10.html

samba: update to samba-4.7.2

---

packages/addons/service/net-snmp/changelog.txt
packages/addons/service/net-snmp/package.mk
packages/addons/service/net-snmp/patches/net-snmp-0003-config.sub.patch
packages/addons/service/net-snmp/source/bin/snmpd.start

- Fix build
- don't load config file twice

[LE 8.2] Net-snmp addon

---

packages/linux/package.mk

linux: bump amlogic-3.14 to 2e193b8

---

packages/addons/addon-depends/bash/package.mk

bash: fix LIBS

---

packages/addons/addon-depends/system-tools-depends/dstat/package.mk
packages/addons/addon-depends/system-tools-depends/unrar/package.mk

fixes dstat and unrar compiling after https://github.com/LibreELEC/LibreELEC.tv/pull/2151

addon compiling fixes

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-dvbapi/patches/vdr-plugin-dvbapi-02-kernel-4.14-support.patch
packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk
packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
packages/addons/service/vdr-addon/changelog.txt
packages/addons/service/vdr-addon/package.mk

- updates some core plugins and fix compiling at current master

vdr-addon update

---

packages/addons/addon-depends/dvb-tools-depends/mumudvb/package.mk
packages/addons/tools/dvb-tools/changelog.txt

fixes building of mumudvb with kernel >= 4.14

mumudvb: fix compiling

---

packages/linux-drivers/RTL8189FS/package.mk

Compiled/Tested against TX3 Pro (S905)
Needed for #2254

RTL8189FS: new driver package

---

config/version

Set version back to development.

[LE 8.2] config: Set version to devel

---

packages/graphics/mesa/package.mk

Removing no longer needed workaround(s), renaming local variables and documenting others.
This series is a preparation for Mesa VAAPI support. I'll submit that as this has landed, until then take a look at the branch https://github.com/evelikov/LibreELEC.tv/tree/mesa-vaapi

Various Mesa fixes

---

packages/x11/other/fontconfig/conf.d/05-kodi-fonts.conf
packages/x11/other/fontconfig/package.mk

fixes SSA/ASS subtitles (*.ass) with custom fonts
https://forum.libreelec.tv/thread/10874-custom-fonts-for-subtitles-issue/?postID=72234

fontconfig: add kodi font folder to a search list

---

scripts/checkdeps

- partial refactoring of checkdeps
- fix multiple dependencies for java on arch
- add missing dependency for XML::Parser

Refactor scripts/checkdeps, fix missing deps

---

projects/Odroid_C2/initramfs/platform_init

Up port of https://github.com/LibreELEC/LibreELEC.tv/pull/2342

projects/Odroid_C2: Turn off annoying blue flashing LED on boot

---

config/version

because the kids need their 3D movies for Christmas :)

config: set version to 8.2.2

---

projects/S905/packages/u-boot/package.mk

our customized version of fw_setenv which allows us to reboot to internal does not work, this PR addresses that issue

projects/S905: fix project specific u-boot

---

packages/sysutils/systemd/package.mk

systemd: update to 236

---

packages/network/samba/package.mk
packages/network/samba/patches/samba-950-no-man.patch
packages/network/samba/patches/samba-999-fix-compilation-of-samba-4.7.4-with-disabled-ADS.patch

https://www.samba.org/samba/history/samba-4.7.4.html

samba: update to samba-4.7.4

---

packages/compress/zstd/package.mk

Lots of bug fixes, many of which address data corruption: https://github.com/facebook/zstd/releases/tag/v1.3.3

zstd: update to zstd-1.3.3

---

packages/linux-firmware/brcmfmac_sdio-firmware-imx/package.mk

brcmfmac_sdio-firmware-imx: install firmware to correct location

---

packages/network/iptables/config/home.v4
packages/network/iptables/config/home.v6
packages/network/iptables/scripts/iptables_helper
packages/network/iptables/system.d/iptables.service

- iptables.service: Fix flush on stop if EnviromentFile becomes
unavailable
- home.v*: Fix wifi tethering
- iptables_helper: fix check_docker function

iptables: Fix several issues

---

packages/linux-drivers/amlogic/RTL8188EU-aml/package.mk
packages/linux-drivers/amlogic/RTL8189ES-aml/package.mk
packages/linux-drivers/amlogic/RTL8189FS-aml/package.mk
packages/linux-drivers/amlogic/RTL8723BS-aml/package.mk
packages/linux-drivers/amlogic/RTL8723DS-aml/package.mk
packages/linux-drivers/amlogic/RTL8822BU-aml/package.mk
packages/linux-drivers/amlogic/ap6xxx-aml/package.mk
projects/Amlogic/devices/LePotato/packages/u-boot/patches/u-boot-0004-faster-boot.patch

This PR contains the latest updates by @kszaq in his 8.2 branch ported over to master
I have tested all changes compile ok

Amlogic updates

---

packages/x11/xserver/xorg-server/package.mk

xorg-server: update to xorg-server-1.19.6

---

packages/web/curl/package.mk

curl: update to curl-7.58.0 [backport]

---

config/noobs/partitions.json
scripts/image

See: https://forum.libreelec.tv/thread/10650-rpi-noobs-partition-information

NOOBS: shorten partition labels, add $DEVICE support

---

tools/RPi/rpi-linux-rebase.sh

See: https://github.com/LibreELEC/LibreELEC.tv/pull/2382#issuecomment-362468188

RPi support: drop ksoftirqd commit

---

packages/devel/slang/package.mk
packages/network/libdnet/patches/00-fix_strlcpy_strlcat.patch
packages/network/samba/package.mk

Changes described here: https://forum.libreelec.tv/thread/11494-how-to-build-the-latest-libreelec-git-under-gentoo/

Fixes for building Generic/x86_64 under Gentoo/amd64

---

projects/Amlogic/linux/linux.aarch64.conf
projects/Amlogic/options
projects/Amlogic/packages/u-boot-tools-aml/package.mk

...and fix kernel config after an update.

Amlogic: clean up for u-boot-tools

---

packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk

minor update as followup to https://github.com/LibreELEC/LibreELEC.tv/pull/2332

vdr-plugin-satip: update to 0a15717

---

packages/debug/libva-utils/package.mk
packages/multimedia/intel-vaapi-driver/package.mk
packages/multimedia/libva/package.mk

libva: update libva/libva-utils/intel-vaapi-driver 2.1.0

---

packages/mediacenter/kodi-binary-addons/visualization.goom/package.mk

visualization.goom: fix build

---

packages/graphics/mesa/package.mk

Bug fixes.
17.3.4: https://www.mesa3d.org/relnotes/17.3.4.html
17.3.5: https://www.mesa3d.org/relnotes/17.3.5.html

mesa: update to mesa-17.3.5

---

projects/Amlogic_GX/patches/linux/0003-meson-ir-timeout.patch

@HiassofT please don't forget to send this upstream!

linux: add meson-ir timeout patch

---

packages/mediacenter/LibreELEC-settings/package.mk

fixes a backup issue in the settings addon

settings: bump version to 0768930

---

packages/mediacenter/LibreELEC-settings/package.mk

bump settings to pick-up firewall config fixes

settings: bump package for firewall fixes

---

packages/linux/package.mk

bump version and change to longer githash format

linux: bump to 4.16-rc5

---

packages/network/samba/package.mk
packages/network/samba/patches/samba-950-no-man.patch
packages/network/samba/patches/samba-954-fix-build-without-ads.patch

https://www.samba.org/samba/security/CVE-2018-1057.html

samba: update to samba-4.6.14

---

config/version

leave merge until we confirm whether there are any last minute changes, thx

config: set version to 8.2.4

---

packages/mediacenter/kodi-binary-addons/audiodecoder.2sf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.dumb/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.gsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.modplug/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.ncsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.nosefart/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.sidplay/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.ssf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk
packages/mediacenter/kodi-binary-addons/audioencoder.vorbis/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk
packages/mediacenter/kodi-binary-addons/vfs.libarchive/package.mk
packages/mediacenter/kodi-binary-addons/vfs.rar/package.mk
packages/mediacenter/kodi/package.mk
packages/mediacenter/kodi/scripts/kodi.sh

Merge this about mid-March, ish.

kodi: mid-March update

---

packages/network/samba/patches/samba-950-no-man.patch

solves build problem after #2586
@adamg88: can you confirm the patch?

 samba: fix noman patch 

---

packages/linux-driver-addons/dvb/crazycat/package.mk
projects/Rockchip/options
projects/Rockchip/patches/linux/rockchip-4.4/linux-0010-dvbcompat.patch
projects/Rockchip/patches/linux/rockchip-4.4/linux-0011-add-bitfield-header.patch

Crazycat, Hauppauge driver Addons for Rockchip

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

Includes `Partial revert for eemc clock change for slice`.

RPi: update firmware 75de5d7 [backport]

---

config/functions

Minor improvement, as discussed: https://github.com/LibreELEC/LibreELEC.tv/pull/2607#issuecomment-376517421

config/functions: use Here doc for create_meson_conf

---

packages/graphics/libdrm/package.mk
packages/graphics/mesa/package.mk
packages/lang/llvm/package.mk

keep open till final releases are available
@MilhouseVH for testing

graphics package updates

---

projects/RPi/filesystem/usr/share/alsa/cards/AlloDigiOne.conf
projects/RPi2/filesystem/usr/share/alsa/cards/AlloDigiOne.conf

Backport of #2636 
See https://forum.libreelec.tv/thread/12047-allo-digione/?postID=87335#post87335

RPi,RPi2: add alsa card conf for Allo DigiOne to enable passthrough

---

projects/RPi/filesystem/usr/share/alsa/cards/AlloDigiOne.conf

See https://forum.libreelec.tv/thread/12047-allo-digione/?postID=87335#post87335

RPi: add alsa card conf for Allo DigiOne to enable passthrough

---

packages/addons/addon-depends/network-tools-depends/iperf/package.mk
packages/addons/addon-depends/network-tools-depends/irssi/package.mk
packages/addons/addon-depends/network-tools-depends/iw/package.mk
packages/addons/addon-depends/network-tools-depends/lftp/package.mk
packages/addons/addon-depends/network-tools-depends/ncftp/package.mk
packages/addons/addon-depends/network-tools-depends/ngrep/package.mk
packages/addons/addon-depends/network-tools-depends/nmap/package.mk
packages/addons/addon-depends/network-tools-depends/rsync/package.mk
packages/addons/addon-depends/network-tools-depends/sshfs/package.mk
packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk
packages/addons/addon-depends/network-tools-depends/udpxy/package.mk
packages/addons/addon-depends/network-tools-depends/wireless_tools/package.mk
packages/addons/tools/network-tools/changelog.txt
packages/addons/tools/network-tools/package.mk
packages/addons/tools/network-tools/source/default.py

basically to fix Jenkins, if it works I include a network-tools bump

network-tools update

---

scripts/image
scripts/mkimage

@islipfd19 is this the missing functionality you are looking for?

create sha256 checksum files of tars and images

---

packages/devel/make/patches/make-glibc_alloc_fix.patch

RPi build test under debian buster and squeeze

make: fix build against actual host glibc

---

packages/wayland/libinput/package.mk

moving to the meson build system

libinput: update to 1.10.4

---

packages/graphics/mesa/package.mk

https://lists.freedesktop.org/archives/mesa-dev/2018-April/193440.html

mesa: update to mesa-18.0.2

---

packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_DHT/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_GPIO/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LED_Backpack/package.mk
packages/addons/libraries/adafruit-libraries/changelog.txt
packages/addons/libraries/adafruit-libraries/package.mk

adafruit-libraries: update of various modules [master]

---

packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_ADS1x15/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_ADXL345/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_BMP/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_CharLCD/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_DHT/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_GPIO/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LED_Backpack/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LSM303/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_MCP3008/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_MCP4725/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_PCA9685/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_PureIO/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_SI1145/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_TCS34725/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_VCNL40xx/package.mk
packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_WS2801/package.mk
packages/addons/libraries/adafruit-libraries/changelog.txt
packages/addons/libraries/adafruit-libraries/package.mk

solves: https://forum.libreelec.tv/thread/12420-temperature-sensor-dht11-22-via-gpio-using-adafruit-libraries/
please publish new addon version.

adafruit-libraries: update of various modules [8.2]

---

packages/addons/addon-depends/mpd-mpc/package.mk
packages/addons/service/mpd/changelog.txt
packages/addons/service/mpd/package.mk
packages/addons/service/mpd/source/default.py
packages/addons/service/mpd/source/resources/language/English/strings.po
packages/addons/service/mpd/source/resources/language/English/strings.xml
packages/addons/service/mpd/source/resources/settings.xml
packages/addons/service/mpd/source/settings-default.xml
packages/addons/service/mpd/source/sleep.d/mpd.power

- adds mpd cli client (mpc)
- reworked for k18

mpd: update to 0.20.19

---

packages/network/samba/package.mk

https://www.samba.org/samba/history/samba-4.8.2.html

samba: update to samba-4.8.2

---

packages/addons/addon-depends/librespot-depends/rustup.rs/patches/rustup.rs-01_wget.patch

rustup.rs: use wget if curl is unavailable

---

packages/graphics/libdrm/package.mk

libdrm: change to use meson and update

---

packages/audio/pulseaudio/package.mk

removed fix, works now without
+ minor cleanup, changed to `PKG_VAR`

pulseaudio: remove fix and cleanup

---

config/graphic
packages/graphics/libdrm/package.mk
packages/multimedia/ffmpeg/package.mk

This just removes some work from our feature branches

some v4l2 and libdrm updates

---

packages/addons/service/tvmosaic/source/settings-default.xml

tvmosaic: oops, tvm_delay is lower case

---

packages/lang/Python2/package.mk

See [https://bugs.python.org/issue9210](https://bugs.python.org/issue9210)
Solves umlaut issue reported at [https://forum.kodi.tv/showthread.php?tid=333003](https://forum.kodi.tv/showthread.php?tid=333003)

Python2: remove --with-wctype-functions

---

packages/addons/driver/sapphire/changelog.txt
packages/addons/driver/sapphire/package.mk

successor of https://github.com/LibreELEC/LibreELEC.tv/pull/2683
tx to @jlazkano - here an "fixed" version of your PR
can you test it ? (if you tell me your platform I can build you an testaddon)

sapphire: update add-on to 6.9

---

packages/network/samba/package.mk

https://www.samba.org/samba/history/samba-4.8.3.html

samba: update to samba-4.8.3

---

packages/addons/script/script.config.vdr/changelog.txt
packages/addons/script/script.config.vdr/package.mk
packages/addons/script/script.config.vdr/sources/addon.xml

addons: update script.config.vdr maintainer

---

packages/addons/repository/repository.kodinerds/package.mk

addons: bump kodinerds repo version

---

packages/x11/driver/xf86-video-nvidia/package.mk

Announcement: [forum](https://devtalk.nvidia.com/default/topic/1037553), [alt](http://www.nvidia.com/Download/driverResults.aspx/136120/en-us)

xf86-video-nvidia: update to xf86-video-nvidia-390.77

---

packages/addons/addon-depends/protobuf/package.mk
packages/addons/service/boblightd/source/bin/boblightd.start
packages/devel/configtools/package.mk

spdx: missed packages

---

packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk

added two missing addons - no function test from my side due missing usecase

kodi binary addons

---

packages/emulation/libretro-4do/package.mk
packages/emulation/libretro-dosbox/package.mk
packages/emulation/libretro-gambatte/package.mk
packages/emulation/libretro-reicast/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.4do/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.dosbox/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.gambatte/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.prosystem/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro.reicast/package.mk
packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.steamcontroller/package.mk
packages/mediacenter/kodi-binary-addons/peripheral.xarcade/package.mk

update to latest (buildtested)
@garbear

retroplayer: update add-ons

---

packages/linux-driver-addons/dvb/crazycat/package.mk
packages/linux-driver-addons/dvb/digital_devices/package.mk
packages/linux-driver-addons/dvb/hauppauge/package.mk

or addons get build with `scripts/create_addon all`

DVB Addons are embedded

---

packages/addons/service/syncthing/changelog.txt
packages/addons/service/syncthing/package.mk
packages/addons/service/syncthing/source/settings-default.xml

syncthing: update to 0.14.49

---

packages/tools/dtc/package.mk

dtc: cosmetic change

---

scripts/create_addon

* allow to build addons with sourced `PKG_IS_ADDON` variable
* change state of "not supported" messages from `ERROR` to `SKIP`

create_addon: two improvments

---

packages/network/wpa_supplicant/patches/wpa_supplicant-100-EAPOL-Ignore-unauthenticated-encrypted-EAPOL-Key-data.patch

wpa_supplicant: Fix EAPOL vulnerability [backport]

---

packages/network/wpa_supplicant/patches/wpa_supplicant-100-EAPOL-Ignore-unauthenticated-encrypted-EAPOL-Key-data.patch

http://seclists.org/oss-sec/2018/q3/84

wpa_supplicant: Fix EAPOL vulnerability

---

packages/mediacenter/kodi-binary-addons/vfs.sftp/package.mk

vfs.sftp: rebuild

---

packages/readme.md

according to the slack discussion

docs: force full githashes

---

packages/mediacenter/LibreELEC-settings/package.mk

Ensure Slice/Slice3 send rev flags.

LibreELEC-settings: update to LibreELEC-settings-5a4bde7

---

tools/mkpkg/mkpkg_bcm2835-driver
tools/mkpkg/mkpkg_libcec
tools/mkpkg/mkpkg_libretro-ppsspp
tools/mkpkg/mkpkg_linux-amlogic
tools/mkpkg/mkpkg_lockdev
tools/mkpkg/mkpkg_rtmpdump

Use full revision when creating a package tarball.

mkpkg: use full rev

---

packages/network/samba/package.mk
packages/network/samba/patches/samba-950-no-man.patch

https://www.samba.org/samba/history/samba-4.8.5.html

samba: update to samba-4.8.5

---

packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch

I broke this patch with the last Kodi bump. :frowning_face:

kodi: fix CEC not turning TV off on exit

---

config/functions

This should be cosmetic (tested without problems) and is a more general fix than the original version.

config/functions: clean up recursion test

---

packages/addons/addon-depends/chrome-depends/chrome-libXcomposite/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libXdamage/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libXfixes/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libXi/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libXrender/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libXtst/package.mk
packages/addons/addon-depends/chrome-depends/chrome-libxcb/package.mk
packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk
packages/addons/addon-depends/chrome-depends/gtk3/package.mk
packages/addons/addon-depends/chrome-depends/libXScrnSaver/package.mk
packages/addons/addon-depends/chrome-depends/libXcursor/package.mk
packages/addons/addon-depends/chrome-depends/libXft/package.mk
packages/addons/addon-depends/chrome-depends/libxss/package.mk
packages/addons/addon-depends/chrome-depends/pango/package.mk
packages/addons/addon-depends/chrome-depends/scrnsaverproto/package.mk
packages/addons/addon-depends/chrome-depends/shared-mime-info/package.mk
packages/addons/browser/chrome/package.mk

should fix failure of hyperion at `scripts/create_addon all` and tigervnc
@awiouy @MilhouseVH

chrome: don't copy libs to toolchain

---

projects/WeTek_Core/options

WeTek_Core: disable dvb driver addons

---

packages/addons/addon-depends/rsyslog-depends/libestr/package.mk
packages/addons/addon-depends/rsyslog-depends/libfastjson/package.mk
packages/addons/addon-depends/rsyslog-depends/liblogging/package.mk
packages/addons/addon-depends/rsyslog-depends/liblognorm/package.mk
packages/addons/addon-depends/rsyslog-depends/librelp/package.mk
packages/addons/service/rsyslog/changelog.txt
packages/addons/service/rsyslog/package.mk
packages/addons/service/rsyslog/source/resources/settings.xml
packages/addons/service/rsyslog/source/settings-default.xml

@islipfd19 could you runtime test this ? (http://cvh.libreelec.tv/addons/9.0/rsyslog/)

rsyslog: update to latest

---

packages/sysutils/busybox/scripts/getedid

No further description needed ;)

[getedid] Fixed a little typo

---

packages/emulation/libretro-mame2000/package.mk
packages/emulation/libretro-mame2003/package.mk
packages/emulation/libretro-mame2010/package.mk
packages/emulation/libretro-mame2010/patches/libretro-mame2010-0001_fix-cross-build.patch
packages/emulation/libretro-mame2014/package.mk
packages/emulation/libretro-mame2014/patches/libretro-mame2014-0001_fix-cross-compile.patch

update mame core to latest version
need https://github.com/LibreELEC/LibreELEC.tv/pull/2981 to get merged too

update mame cores

---

packages/network/samba/config/samba4-cache.txt
packages/network/samba/package.mk

Announcement: https://www.samba.org/samba/history/samba-4.9.0.html
Wiki: https://wiki.samba.org/index.php/Samba_4.9_Features_added/changed

samba: update to samba-4.9.0

---

packages/databases/sqlite/package.mk

Changelog: https://www.sqlite.org/releaselog/3_25_0.html

sqlite: update to sqlite-autoconf-3250000

---

packages/devel/elfutils/package.mk
packages/textproc/libxml2/package.mk
packages/textproc/libxslt/package.mk

elfutils-0.173 fixes https://github.com/LibreELEC/LibreELEC.tv/commit/9adf3204b9152938218ce3fb36ccf9ff48b65aed#r30447601

Update various packages (201809)

---

packages/addons/addon-depends/dotnet-runtime-depends/curl3/package.mk
packages/addons/addon-depends/dotnet-runtime-depends/krb5/package.mk
packages/addons/addon-depends/dotnet-runtime-depends/lttng-ust/package.mk
packages/addons/addon-depends/dotnet-runtime-depends/userspace-rcu/package.mk
packages/addons/addon-depends/emby-depends/imagemagick/package.mk
packages/addons/service/emby/changelog.txt
packages/addons/service/emby/package.mk
packages/addons/tools/dotnet-runtime/changelog.txt
packages/addons/tools/dotnet-runtime/package.mk

This also updates and fixes dotnet-runtime

Emby: update to 3.5.3.0

---

packages/network/samba/package.mk

https://www.samba.org/samba/history/samba-4.9.1.html

samba: update to samba-4.9.1

---

packages/mediacenter/LibreELEC-settings/package.mk

This adds: https://github.com/LibreELEC/service.libreelec.settings/pull/104

LibreELEC-settings: update to LibreELEC-settings-e93c231

---

scripts/image

Show BUILDER_NAME in Kodi System Information and LE Settings -> About instead of community.

scripts: image: show BUILDER_NAME in System Information and LE settings

---

packages/addons/addon-depends/dvb-tools-depends/blindscan-s2/package.mk
packages/addons/addon-depends/dvb-tools-depends/depends/bitstream/package.mk
packages/addons/addon-depends/dvb-tools-depends/depends/libev/package.mk
packages/addons/addon-depends/dvb-tools-depends/dvb-apps/package.mk
packages/addons/addon-depends/dvb-tools-depends/dvblast/package.mk
packages/addons/addon-depends/dvb-tools-depends/dvbsnoop/package.mk
packages/addons/addon-depends/dvb-tools-depends/mumudvb/package.mk
packages/addons/addon-depends/dvb-tools-depends/szap-s2/package.mk
packages/addons/addon-depends/dvb-tools-depends/t2scan/package.mk
packages/addons/addon-depends/dvb-tools-depends/tune-s2/package.mk
packages/addons/addon-depends/dvb-tools-depends/w_scan/package.mk
packages/addons/tools/dvb-tools/changelog.txt
packages/addons/tools/dvb-tools/package.mk

- added t2scan, basically w_scan for only DVB-T done right
- everything updated to latest
- cleanup every depend to latest standard

update and cleanup dvb-tools

---

packages/mediacenter/kodi/package.mk
packages/mediacenter/kodi/patches/kodi-100.14-use-alsa-and-pulse-together.patch
packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch
packages/multimedia/ffmpeg/patches/ffmpeg-99.1003-pfcd_hevc_optimisations.patch

Runtime test on RPi3B+ was fine. Not tested for other projects/devices yet

kodi: update to 18.0b3-Leia

---

packages/linux/package.mk

fixed RPi problems, bumped generic too to stay in sync

kernel 4.18.11 bump

---

packages/x11/xserver/xorg-server/package.mk

Changelog:
https://lists.x.org/archives/xorg-announce/2018-October/002924.html

Xorg server 1.20.2

---

projects/RPi/devices/RPi/options
projects/RPi/devices/RPi2/options
projects/RPi/options

This moves configuration controlled by if statements in project/options out to device/options for the respective boards.

projects/rpi: move device settings to device options

---

packages/x11/xserver/xorg-server/package.mk

https://www.phoronix.com/scan.php?page=news_item&px=xorg-server-1.20.3-Released

xorg-server: update to xorg-server-1.20.3

---

packages/linux-driver-addons/dvb/crazycat/package.mk
packages/linux-driver-addons/dvb/depends/media_tree_cc/package.mk
projects/Generic/options
projects/RPi/options

updates CC to 4.19 kernel base

crazycat: update to 2018-11-04

---

packages/addons/service/lcdd/changelog.txt
packages/addons/service/lcdd/package.mk

This fixes undefined symbols issues like reported here https://forum.libreelec.tv/thread/13625-le-8-90-006-lcdproc-broken/

lcdd: build with optimization

---

packages/network/samba/package.mk

Changelog: https://www.samba.org/samba/history/samba-4.9.2.html

samba: update to samba-4.9.2

---

scripts/get_git

Fixes a couple of errors introduced by #3098.

scripts/get_git: fix a couple of errors

---

packages/devel/libcec/package.mk
packages/mediacenter/kodi/package.mk

build and runtime tested for RPi2

kodi: update to 18.0rc1

---

packages/multimedia/aom/package.mk

fixes AML build and reduces overall build time

aom: disable options

---

packages/linux-driver-addons/dvb/depends/media_tree/package.mk
packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-01-hauppauge.patch
packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-02-add-t230c2.patch
packages/linux-driver-addons/dvb/dvb-latest/package.mk

- based at 4.20-rc4 ish
- refreshed Hauppauge patch
- added Geniatech T230C2 support (patch)

dvb-latest: update to 2018-11-23

---

packages/compress/zstd/package.mk

Nothing particularly exciting for LE in this update, but here it is.

zstd: update to 1.3.7

---

packages/emulation/libretro-mgba/package.mk

- switched to upstream repo
- changed PKG_TOOLCHAIN to "cmake-make"
- updated dependencies

libretro-mgba: updated to git 38bad71

---

packages/graphics/mesa/package.mk
packages/python/devel/Mako/package.mk
packages/python/devel/setuptools/package.mk

I'll leave the summary to Phoronix:
https://www.phoronix.com/scan.php?page=news_item&px=Mesa-18.3.0-Released

mesa: update to mesa-18.3.1

---

packages/databases/sqlite/package.mk

sqlite: update to 3.26

---

packages/mediacenter/kodi/package.mk
packages/multimedia/rkmpp/package.mk
projects/Rockchip/README.md
projects/Rockchip/devices/RK3399/README.md
projects/Rockchip/devices/RK3399/options
projects/Rockchip/patches/linux/rockchip-4.4/linux-0001-rockchip.patch
projects/Rockchip/patches/linux/rockchip-4.4/linux-0002-ir.patch
projects/Rockchip/patches/linux/rockchip-4.4/linux-0005-dts.patch
scripts/uboot_helper

This PR updates Kodi to `rockchip_18.0rc3-Leia`, rkmpp to latest and adds initial support for Khadas Edge (thanks @150balbes)
Tested on Khadas Edge.

Rockchip: update kodi to 18.0rc3 and more

---

projects/Amlogic/bootloader/update.sh

update.sh: Fix dtb not updating

---

packages/network/samba/package.mk

Changelog: https://www.samba.org/samba/history/samba-4.9.4.html

samba: update to samba-4.9.4

---

packages/addons/service/tigervnc/changelog.txt
packages/addons/service/tigervnc/package.mk
packages/graphics/libjpeg-turbo/package.mk

tigervnc: update to 1.9.0

---

packages/web/curl/package.mk
packages/web/libmicrohttpd/package.mk
packages/web/libmicrohttpd/patches/libmicrohttpd-001-remove-extra-unescape-PR14991.patch

web: update to libmicrohttpd-0.9.61/curl-7.62.0

---

packages/network/libshairplay/package.mk

libshairplay: update to 096b61a

---

packages/graphics/bcm2835-driver/package.mk
packages/linux/package.mk
packages/tools/bcm2835-bootloader/package.mk
projects/Generic/linux/linux.x86_64.conf
projects/RPi/devices/RPi/linux/linux.arm.conf
projects/RPi/devices/RPi2/linux/linux.arm.conf

4.19.13 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.13
4.19.14 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.14

linux (RPi/Generic): update to linux-4.19.16

---

packages/addons/service/minidlna/changelog.txt
packages/addons/service/minidlna/package.mk

@awiouy @HiassofT 
what about that approach for the addon "version"
I would even more like `2018-05-05` but this opens the question is it year-day-month or year-month-day.
-edit-
or `May 2018`or `2018-05`

minidlna: update to 799e6cf

---

packages/addons/addon-depends/network-tools-depends/rar2fs/package.mk

rar2fs: add fuse depend

---

scripts/image

fixes https://github.com/LibreELEC/LibreELEC.tv/pull/3245

scripts/image: add OVA_SIZE variable

---

packages/addons/addon-depends/system-tools-depends/hddtemp/db/hddtemp.db
packages/addons/addon-depends/system-tools-depends/hddtemp/package.mk

As per @MilhouseVH comments on my earlier attempt:
- updated PKG_SITE to the new location
- added the 'hddtemp.db' text file to the source tree
I have built the rpi2 and x86_64 versions. If needed I could do a build for all supported platforms
Hopefully this time I followed the correct procedure

Hddtemp: FIX build:  update urls, local hddtemp.db

---

packages/addons/service/webgrabplus/package.mk
packages/addons/tools/mono/package.mk

to disable the addons if updating from LE8.x

mono/webgrabplus: add marked broken addons

---

packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
packages/linux/patches/default/linux-902-extend-rc6-toggle-support-for-zotac.patch
packages/linux/patches/raspberrypi/linux-902-extend-rc6-toggle-support-for-zotac.patch

[le9.0] add patch to fix Zotac IR remotes

---

distributions/LibreELEC/version

This needs to go in sooner than later.

distro: bump OS_VERSION/ADDON_VERSION to 9.1

---

scripts/build_mt
tools/mtstats.py

Plus small fixup for `tools/mtstats.py`

buildsystem: add multithreaded ad-hoc package build

---

config/functions
config/options

buildsystem: fix debug broken by #3171 [backport]

---

config/functions

config/functions: add cross-compile property support [backport]
