LibreELEC/LibreELEC.tv

- packages/linux/package.mk
A couple of vc4 fixes, this one https://github.com/raspberrypi/linux/pull/4826 should help with blank screen / flip_done on some setups
> linux (RPi): update to 5.15.13-b85f176

- packages/linux/package.mk
same as #6125: A couple of vc4 fixes, this one https://github.com/raspberrypi/linux/pull/4826 should help with blank screen / flip_done on some setups
> [le10] linux (RPi): update to 5.10.90-e13d4e9

- packages/multimedia/media-driver/package.mk
```
Generic.x86_64-devel-20220114083908-b1f573f
Linux nuc11 5.16.1-rc1 #1 SMP Fri Jan 14 08:40:35 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:5ad708b518e6bb3e8ac31a9c7b5a8908573a409f). Platform: Linux x86 64-bit
Kodi compiled 2022-01-13 by GCC 10.3.0 for Linux x86 64-bit version 5.16.0 (331776)
Running on LibreELEC (heitbaum): devel-20220114083908-b1f573f 11.0, kernel: Linux x86 64-bit version 5.16.1-rc1
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0041.2021.0811.1505 08/11/2021
RetroPlayer[PROCESS]: Registering process …
```
> media-driver: update to 22.1.1

- projects/Allwinner/patches/linux/0056-bluetooth-btrtl-add-hci-ver-rtl8822cs.patch
Add the missing id hci_ver = 0x8 to the ic_id_table[]
Before:
[   11.288818] Bluetooth: hci0: RTL: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8822
[   11.512883] Bluetooth: hci0: RTL: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8822
[   11.512940] Bluetooth: hci0: RTL: unknown IC info, lmp subver 8822, hci rev 000c, hci ver 0008
[   11.512957] Bluetooth: hci0: RTL: no config loaded
After:
[   12.642167] Bluetooth: hci0: RTL: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8822
[   12.671911] Bluetooth: hci0: RTL: rom_version status=0 version=3
[   12.671961] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_fw.bin
[   12.706248] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_config.bin
[   12.730251] Bluetooth: hci0: RTL: cfg_sz 33, total sz 40737
[ …
> linux (Allwinner): bluetooth btrtl: add hci_ver 0x8 for rtl8822cs_bt as found on Tanix TX6

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
- libmediainfo: update to 21.09
- mediainfo: update to 21.09
- mpg123: update to 1.29.3
- mpv-drmprime: update to 0.34.1
- squeezelite: update to 2022-01-06 (1.9.9.1395)
> [le11] multimedia-tools: update addon to 116

- packages/addons/addon-depends/whois/package.mk
- packages/addons/service/proftpd/changelog.txt
- packages/addons/service/proftpd/package.mk
- proftpd: update to 1.3.7c
- release notes:
- http://www.proftpd.org/docs/RELEASE_NOTES-1.3.7c
- whois: update to 5.5.11
> [le11] proftpd: update to 1.3.7c

- packages/mediacenter/kodi-theme-Estuary/package.mk
This fixes old Estuary skin in image after kodi bump when doing
unclean builds.
> kodi-theme-Estuary: add unpack dependency on kodi

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
- packages/mediacenter/kodi/patches/kodi-100.26-disable-internal-texturepacker.patch
We haven't bumped kodi for quite some time, so bring it up to date while we wait for 19.4.
The "Set demuxer speed to normal on flush" should help with issues after seek which have been reported on our forums, too.
> kodi: update to latest Matrix version

- packages/sysutils/dbus/package.mk
This branch updates dbus package to the latest version (1.13.20).
> [LE11] dbus: update to 1.13.20

- packages/python/devel/Jinja2/package.mk
- packages/sysutils/systemd/package.mk
- packages/sysutils/systemd/patches/systemd-0001-move-etc-systemd-system-to-storage-.config-system.d.patch
- packages/sysutils/systemd/patches/systemd-0002-move-hwdb.bin-to-run.patch
- packages/sysutils/systemd/patches/systemd-0003-remove-nonexistant-dependency.patch
- packages/sysutils/systemd/patches/systemd-0200-persist-persistent-timer-stamps.patch
- packages/sysutils/systemd/patches/systemd-0300-config-env-unhide-cursor.patch
new build dependency used by systemd v249 
systemd >= v249 requires Jinja2 for templating
- refer: https://github.com/systemd/systemd/pull/19630: Use jinja2 for templating
- m4 use is dropped, and the two parallel substitution systems in meson are unified.
can be added at anytime. 
Not required until systemd v249
Including Jinja2 with the v250 systemd
Systemd NEWS: https://github.com/systemd/systemd/blob/main/NEWS
systemd: update from v247 to v250
issues: 
- FIXED: need to track down error: `systemd-journald[360]: Failed to write entry (22 items, 760 bytes), rotating before retrying: Argument list too long`
- FIXED: why is my docker console output getting into `journalctl -f`
- FIXED: Issue with 250-rc3 - systemd/systemd 21829 - temp patch -
c7f6f36 - fixed in …
> systemd: update to 250.3 and include Jinja2

- tools/docker/README.md
update the `docker run` command to set `--log-driver none` otherwise the logs go through to journald
observed the journald logs during the testing of systemd v250
refer to #6029
> tools/docker/README.md: log-driver command line update

- config/graphic
- config/show_config
- packages/graphics/mesa/package.mk
- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-loader/patches/vulkan-loader-995.01-fix-cross-compile.patch
- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.01-cmakelists-opts.patch
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.02-fix-find-pkg-wayland-protocols.patch
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.03-fix-cube-cross-compile.patch
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.04-fix-glslangValidator-logik.patch
- packages/x11/driver/xf86-video-intel/package.mk
- packages/x11/driver/xf86-video-nvidia/package.mk
- packages/x11/lib/libxcb/package.mk
- projects/ARM/options
- projects/Allwinner/options
- projects/Amlogic/options
- projects/Generic/devices/Generic/options
- projects/Generic/devices/wayland/options
- projects/Generic/devices/x11/options
- projects/NXP/options
- projects/Qualcomm/devices/Dragonboard/options
- projects/RPi/options
- projects/Rockchip/options
- projects/Samsung/options
This PR provides the necessary packages to use [Vulkan](https://www.vulkan.org/) for all projects with supported hardware e.g. AMD, Intel & Nvidia GPUs, RPi4 & hopefully sooner or later all SBCs covered by panfrost. I guess Vulkan can be useful once [Vulkan Video](https://www.phoronix.com/scan.php?page=news_item&px=FFmpeg-Branch-Vulkan-Video) is supported by FFmpeg and [Kodi might also support Vulkan](https://github.com/lrusak/xbmc/tree/vulkan).
- added Vulkan packages
- added glslang package + tool/header dependencies to allow offline build of vulkan-tools
- updated mesa & nvidia opts to build/install Vulkan ICD & libs
- xf86-video-intel conditionally default to DRI3 if Vulkan support is enabled
- added Vulkan to show config:
```
- Vulkan API support (provider):	 yes (vulkan-loader)
- …
```
> [le11] add Vulkan API support

- tools/mkpkg/update_common_functions
- tools/mkpkg/update_retroplayer-addons
Only accept standard github archive URLs and warn about other URLs
that aren't supported by the update script.
This avoids trashing PKG_VERSION with garbage, eg in libretro-mrboom
> update_retroplayer-addons: do stricter libretro version checks

- packages/multimedia/ffmpeg/package.mk
When testing ffmpeg / hardware decoders it's very convenient
if one can do that with ffmpeg instead of only kodi. Using the
same ffmpeg patches and options as used by kodi also reduces the
risk of testing a different version than what's used by LE/kodi.
As the ffmpeg binary is way too minimal for normal use and only
intended for internal testing this feature is disabled by default
and has to be explicitly requested by building with FFMPEG_TESTING=yes
In addition to ffmpeg and ffprobe binaries this enables the null muxer
and wrapped_avframe encoder so one can test with "-f null".
On RPi it also enables vout_drm (which is only included in jc's
tree / RPi ffmpeg patches) so "-f vout_drm" can be used, too.
> ffmpeg: optionally allow minimal ffmpeg binary in image

- packages/addons/addon-depends/librespot-depends/rust/package.mk
- packages/addons/addon-depends/system-tools-depends/bottom/package.mk
- packages/addons/service/librespot/package.mk
Looks like we can set this without passing a command line option.
> rust: cleaner rust target-applies-to-host fix

- packages/devel/glibc/package.mk
- packages/sysutils/dosfstools/package.mk
fsck during boot ERRORs with unable to access the gconv/*.so files. These are dynamically loaded by fsck.fat
whilst this is a harmless error. This adding of the missing libraries removes the error.
```
[    2.527416] fsck: Cannot initialize conversion from codepage 850 to ANSI_X3.4-1968: Invalid argument
[    2.527438] fsck: Cannot initialize conversion from ANSI_X3.4-1968 to codepage 850: Invalid argument
[    2.527450] fsck: Using internal CP850 conversion table
[    2.527459] fsck: fsck.fat 4.2 (2021-01-31)
```
fsck is compiled —with-iconv (gconv) - define this in the `package.mk` file for clarity.
additional files in `init` image.
```
-rwxr-xr-x   1 docker   docker      14376 Jan 18 12:46 /usr/lib/gconv/IBM850.so
-rw-r--r--   1 docker   docker        189 Jan 18 12:46 …
```
> Boot warning: fsck.fat

- packages/compress/zstd/package.mk
release notes:
- https://github.com/facebook/zstd/releases/tag/v1.5.2
> zstd: update to 1.5.2

- packages/devel/glibc/package.mk
- packages/sysutils/dosfstools/package.mk
looks like it breaks all ARM builds, revert #6152 till it is fixed
```
BUILD      glibc (init)
TOOLCHAIN      configure (auto-detect)
grep: /LE/build.LibreELEC-RPi4.arm-11.0-devel/build/glibc-2.32/.armv8a-libreelec-linux-gnueabihf/iconvdata/gconv-modules.d/gconv-modules-extra.conf: No such file or directory
FAILURE: scripts/build glibc:init during makeinstall_init (package.mk)
grep IBM850 ${PKG_BUILD}/.${TARGET_NAME}/iconvdata/gconv-modules.d/gconv-modules-extra.conf > ${INSTALL}/usr/lib/gconv/gconv-modules.d/gconv-modules-extra.conf
FAILURE: scripts/build glibc:init has failed!
```
> reverts #6152

- packages/tools/dtc/package.mk
Fixes issues with fdtget/fdtput & "missing" shared library.  Currently only copies libfdt.so symlink (dereferenced), but program is linked against libfdt.so.1.
```sh
fdtget: error while loading shared libraries: libfdt.so.1: cannot open shared object file: No such file or directory
```
> [LE11] dtc: copy libfdt symlink and library

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.02-fix-find-pkg-wayland-protocols.patch
- after https://github.com/LibreELEC/LibreELEC.tv/pull/5979 the packages need to check for `wl` instead `weston` as `DISPLAYSERVER` - fix Wayland builds
- just install `vkcube` as test graphic tool instead `vkcube` & `vkcubepp`
- update to Vulkan 1.2.203
> [le11] Vulkan: update to 1.2.203 & small fixes

- projects/Allwinner/patches/linux/0087-media-hantro-sunxi-Fix-VP9-steps.patch
Fix for VP9 decoding videos which have width or height which is not multiple of 32.
> Allwinner: linux: Fix VP9 decoding

- packages/graphics/mesa/package.mk
- glGetActiveUniform failing with GL_INVALID_VALUE for no reason
- CopelliaSim crashes on adding vision sensor to a scene on Ubuntu 20+, runs fine on Ubuntu 18.04
- Dirt Rally: Flickering glitches on certain foliage going from Mesa 21.2.5 to 21.3.0
- FrontFacing input is broken on Intel/Vulkan
- llvmpipe: Unimplemented get_driver_uuid/get_device_uuid causes segfaults in e.g. Wine
release notes: 
- https://docs.mesa3d.org/relnotes/21.3.5.html
```
Generic.x86_64-devel-20220128110147-f20fbb1
Linux nuc11 5.16.4-rc1 #1 SMP Fri Jan 28 11:03:53 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:e976cd0e3ad9ed0e4ff80e2f97e2fce1922717be). Platform: Linux x86 64-bit
Kodi compiled 2022-01-20 by GCC 10.3.0 for Linux x86 64-bit version 5.16.2 …
```
> mesa: update to 21.3.5

- packages/network/samba/package.mk
Backport of #6114 and #6181
update 4.13.15 (2021-12-15) to 4.13.17 (2022-01-31)
release notes:
- https://www.samba.org/samba/history/samba-4.13.16.html
- https://www.samba.org/samba/security/CVE-2021-43566.html
- https://www.samba.org/samba/history/samba-4.13.17.html
> [le10] samba: update to 4.13.17

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.13.17.html
===============================
Release Notes for Samba 4.13.17
January 31, 2022
===============================
o CVE-2021-44142: Out-of-Bound Read/Write on Samba vfs_fruit module.
https://www.samba.org/samba/security/CVE-2021-44142.html
o CVE-2022-0336:  Re-adding an SPN skips subsequent SPN conflict checks.
https://www.samba.org/samba/security/CVE-2022-0336.html
Changes since 4.13.16
---------------------
o  Ralph Boehme <slow@samba.org>
* BUG 14914: CVE-2021-44142
o  Joseph Sutton <josephsutton@catalyst.net.nz>
* BUG 14950: CVE-2022-0336
> [le11] samba: update to 4.13.17

- packages/mediacenter/kodi/system.d/kodi-autostart.service
This adds an "autostop.sh" script, which is based on the conversation and related threads [here](https://forum.libreelec.tv/thread/25150-solved-kodi-on-rpi4-on-libreelec-run-custom-script-upon-kodi-power-off/?postID=165518#post165518).
The kodi-autostart.service already has RemainAfterExit set, so the service already fires a "stop" at shutdown.  So just added the ExecStop with a shell test for "/storage/.config/autostop.sh" and TimeoutStopSec=5min to allow the stop script to run up to 5 minutes.
The script itself is implemented just like autostart.sh, and would run at stopping of kodi-autostart.service which normally would happen before poweroff.target is met (while networking is still available).  This gives you an opportunity to run some shutdown scripts before the network is shutdown. …
> [le11] kodi: add shutdown hook to autostart

- packages/network/libnfs/package.mk
This commit below required more updated libnfs than 4.0.0
https://github.com/xbmc/xbmc/pull/17512
> libnfs: update to 5.0.1

- packages/devel/fakeroot/package.mk
- seems 1.26 was hard pulled, didn't investigate
- allows master to build again
> fakeroot: bump to 1.27 (from no-longer-existing 1.26)

- packages/python/devel/waf/package.mk
Commit bde858fe3cedb3b823c4e72f322e269784c42479 changed waf package URL to
tar.bz2 source archive, but unpack() and makeinstall_host() assumes waf
executable file is downloaded directly.
Revert to direct executable download and adjust SHA256 accordingly.
> waf: use binary from source archive

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
Backport of #6135 
- libmediainfo: update to 21.09
- mediainfo: update to 21.09
- mpg123: update to 1.29.3
- mpv-drmprime: update to 0.34.1
- squeezelite: update to 2022-01-06 (1.9.9.1395)
> [le10] multimedia-tools: update addon to 116

- packages/addons/addon-depends/whois/package.mk
- packages/addons/service/proftpd/changelog.txt
- packages/addons/service/proftpd/package.mk
backport of #6132 
- proftpd: update to 1.3.7c
- release notes:
- http://www.proftpd.org/docs/RELEASE_NOTES-1.3.7c
- whois: update to 5.5.11
> [le10] proftpd: update to 1.3.7c

- packages/devel/libcap/package.mk
- packages/devel/readline/package.mk
- packages/security/libgpg-error/package.mk
- packages/sysutils/libusb/package.mk
- packages/sysutils/util-linux/package.mk
- packages/textproc/expat/package.mk
- expat: update to 2.4.4
- libcap: update to 2.63
- libgpg-error: update to 1.44
- libusb: update to 1.0.25
- readline: update to 8.1.2
- util-linux: update to 2.37.3
> package updates: support binaries and libraries

- packages/python/graphics/Pillow/package.mk
- packages/python/security/pycryptodome/package.mk
- Pillow: update to 9.0.1
- update from 8.4.0 to 9.0.1
- https://pillow.readthedocs.io/en/latest/releasenotes/9.0.0.html
- https://pillow.readthedocs.io/en/latest/releasenotes/9.0.1.html
- pycryptodome: update to 3.14.1
- update from 3.12.0 to 3.14.1
- https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst
> packages updates: python

- packages/addons/addon-depends/rpi-tools-depends/RPi.GPIO/package.mk
- packages/addons/tools/rpi-tools/changelog.txt
- packages/addons/tools/rpi-tools/package.mk
Release Notes:
- https://pypi.org/project/RPi.GPIO/0.7.1/
Change Log:
- Better RPi board + peri_addr detection (issue 190 / 191)
- Fix PyEval_InitThreads deprecation warning for Python 3.9 (issue 188)
- Fix build using GCC 10 (issue 187)
- Fix docstrings to not include licence
- Remove Debian/Raspbian stretch packaging support
- Use setuptools instead of distutils
- Added detection of Zero 2 W
- Tested and working with Python 2.7, 3.7, 3.8, 3.9, 3.10
> [le11] rpi-tools: update to latest and addon (111)

- packages/addons/addon-depends/rpi-tools-depends/RPi.GPIO/package.mk
- packages/addons/tools/rpi-tools/changelog.txt
- packages/addons/tools/rpi-tools/package.mk
backport of #6204
Release Notes:
- https://pypi.org/project/RPi.GPIO/0.7.1/
Change Log:
- Better RPi board + peri_addr detection (issue 190 / 191)
- Fix PyEval_InitThreads deprecation warning for Python 3.9 (issue 188)
- Fix build using GCC 10 (issue 187)
- Fix docstrings to not include licence
- Remove Debian/Raspbian stretch packaging support
- Use setuptools instead of distutils
- Added detection of Zero 2 W
- Tested and working with Python 2.7, 3.7, 3.8, 3.9, 3.10
> [le10] rpi-tools: update to latest and addon (111)

- projects/Allwinner/patches/linux/0021-media-cedrus-hevc-Improve-buffer-management.patch
- projects/Allwinner/patches/linux/0088-media-cedrus-Fix-H265-aux-buffer-size.patch
- projects/Allwinner/patches/linux/0089-media-cedrus-Add-watchdog-for-job-completion.patch
Cedrus HEVC driver have two bugs, which are fixed here. Additionally, Cedrus watchdog is added, so any potential lockups due to corrupted video streams can be recovered gracefully.
> [LE11] Allwinner: linux: Update cedrus patches

- packages/graphics/mesa/package.mk
Release notes:
- https://docs.mesa3d.org/relnotes/21.3.6.html
Bug fixes
- radv: CullDistance fail
- i965: Segmentation fault during glinfo context destruction, regression in 21.3.x
- Vulkan Wayland WSI returns empty surface formats
- [REGRESSION][BISECTED] iris: Qutebrowser/QtWebEngine sporadically flashes the window in white
- Flickering Intel Uhd 620 Graphics
- Broken Terraria & Glitches in Forza Horizon 4
> mesa: update to 21.3.6

- packages/linux-firmware/intel-ucode/package.mk
Security updates for INTEL-SA-00528
Security updates for INTEL-SA-00532
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220207
tested on:
```
[    0.000000] microcode: microcode updated early to revision 0x9a, date = 2021-08-06
[    0.000000] Linux version 5.16.8 (docker@57352c438204) (x86_64-libreelec-linux-gnu-gcc-10.3.0 (GCC) 10.3.0, GNU ld (GNU Binutils) 2.37) #1 SMP Wed Feb 9 09:19:18 UTC 2022
was
[    0.000000] microcode: microcode updated early to revision 0x88, date = 2021-03-31
```
> intel-ucode: update to 20220207

- packages/addons/addon-depends/go/package.mk
go1.17.7 (released 2022-02-10) includes security fixes to the
crypto/elliptic, math/big packages and to the go command, as well as bug
fixes to the compiler, linker, runtime, the go command, and the
debug/macho, debug/pe, and net/http/httptest packages. See the Go 1.17.7
milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.17.7+label%3ACherryPickApproved
> go: update to 1.17.7 (lang - for addons)

- packages/mediacenter/LibreELEC-settings/package.mk
> [le10] LibreELEC-settings: update to 1bc8388

- packages/emulation/libretro-mame2016/patches/libretro-mame2016-0001-python39.patch
Add upstream patch
- https://github.com/libretro/mame2016-libretro/pull/52
required since python 3.9
- #6227 
Closes 
- #6231
> libretro-mame2016: fix build with Python 3.9

- projects/Allwinner/patches/linux/0090-media-cedrus-h264-Fix-neighbour-info-buffer-size.patch
It turns out that H264 decoding on Allwinner H6 has same issue as HEVC - one of the auxiliary buffers is too small. Fix that.
> Allwinner: linux: fix H264 buffer size

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
**Mesa 21.3.6,22.0.0-rc1,22.0.0-rc2 have been tested with these updates**
- gmmlib: update to 22.0.2
- media-driver: update to 22.2.0
[Media Common] Fix mos_query_engines_count issue
1. Previous length is the size for allocating membar to get engine count, add correct flow to get engine count
```
Generic.x86_64-devel-20220209091907-ac278fc
Linux nuc11 5.16.8 #1 SMP Wed Feb 9 09:19:18 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:e976cd0e3ad9ed0e4ff80e2f97e2fce1922717be). Platform: Linux x86 64-bit
Kodi compiled 2022-02-04 by GCC 10.3.0 for Linux x86 64-bit version 5.16.5 (331781)
Running on LibreELEC (heitbaum): devel-20220209091907-ac278fc 11.0, kernel: Linux x86 64-bit version 5.16.8
Host …
```
> Intel Graphics updates

- packages/network/wireless-regdb/package.mk
Log (https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/log/):
- Update regulatory rules for the Netherlands (NL) on 6GHz
- Update regulatory rules for China (CN)
- Update regulatory rules for South Korea (KR)
- Revert "wireless-regdb: Update regulatory rules for South Korea (KR)"
- Update regulatory rules for Spain (ES) on 6GHz
- add 802.11ah bands to world regulatory domain
- add support for US S1G channels
- Update regulatory rules for France (FR) on 6 and 60 GHz
- Update regulatory rules for South Korea (KR)
- Update regulatory rules for Croatia (HR) on 6GHz
- Raise DFS TX power limit to 250 mW (24 dBm) for the US
> [le11] wireless-regdb: update to 2022.02.18

- packages/network/wireless-regdb/package.mk
- #6256
(https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/log/):
- Update regulatory rules for the Netherlands (NL) on 6GHz
- Update regulatory rules for China (CN)
- Update regulatory rules for South Korea (KR)
- Revert "wireless-regdb: Update regulatory rules for South Korea (KR)"
- Update regulatory rules for Spain (ES) on 6GHz
- add 802.11ah bands to world regulatory domain
- add support for US S1G channels
- Update regulatory rules for France (FR) on 6 and 60 GHz
- Update regulatory rules for South Korea (KR)
- Update regulatory rules for Croatia (HR) on 6GHz
- Raise DFS TX power limit to 250 mW (24 dBm) for the US
> [le10] wireless-regdb: update to 2022.02.18

- packages/lang/gcc-or1k-linux/package.mk
Detail of release: https://toolchains.bootlin.com/releases_openrisc.html
Toolchain:     openrisc--musl--stable-2021.11-5
GCC:           10.3.0
GDB:           -
Linux headers: 4.9.291
musl:          1.2.2
binutils:      2.36.1
I have been running 2021.11-1, 2021.11-4, 2021.11-5 for builds since Dec 2021/Jan 2022
> gcc-or1k-linux: update to 2021.11-5

- packages/graphics/mesa/package.mk
release-notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.3/docs/relnotes/21.3.7.rst
Mesa 21.3.7 is a bug fix release which fixes bugs found since the 21.3.6 release.
Mesa 21.3.7 implements the OpenGL 4.6 API, but the version reported by
glGetString(GL_VERSION) or glGetIntegerv(GL_MAJOR_VERSION) /
glGetIntegerv(GL_MINOR_VERSION) depends on the particular driver being used.
Some drivers don't support all the features required in OpenGL 4.6.
OpenGL 4.6 is only available if requested at context creation.
Compatibility contexts may report a lower version depending on each driver.
Mesa 21.3.7 implements the Vulkan 1.2 API, but the version reported by
the apiVersion property of the VkPhysicalDeviceProperties struct
depends on the particular driver being used.
New features
None
Bug …
> mesa: update to 21.3.7

- packages/network/openssh/package.mk
- packages/network/openssh/patches/openssh-8.9p1-keydir.patch
release notes:
- https://www.openssh.com/releasenotes.html
```
nuc11:~ # ssh -V
OpenSSH_8.9p1, OpenSSL 3.0.1 14 Dec 2021
```
> [le11] openssh: update to 8.9p1

- packages/sysutils/util-linux/package.mk
util-linux 2.37.4 Release Notes
===============================
This release fixes security issue in chsh(1) and chfn(8):
CVE-2022-0563
The readline library uses INPUTRC= environment variable to get a path
to the library config file. When the library cannot parse the
specified file, it prints an error message containing data from the
file.
Unfortunately, the library does not use secure_getenv() (or a similar
concept), or sanitize the config file path to avoid vulnerabilities that
could occur if set-user-ID or set-group-ID programs.
> util-linux: update to 2.37.4

- packages/python/system/dbussy/package.mk
- packages/sysutils/dbus/package.mk
- dbus: update to 1.13.22
- announcement - https://lists.freedesktop.org/archives/dbus/2022-February/018129.html
- https://gitlab.freedesktop.org/dbus/dbus/-/blob/master/NEWS
- dbussy: update to 60d3c15
- 2 minor commits
- No functional change 
- https://github.com/ldo/dbussy/compare/a694e3b525e988dc5362f2278e2aacdf06b3a179...6325cbfd99138b7fba320265d5dcd4faff8fb457
> Update dbus and dbussy packages

- packages/network/bluez/package.mk
- packages/network/ethtool/package.mk
- packages/network/iwd/package.mk
- packages/network/openvpn/package.mk
- packages/network/rpcbind/package.mk
- packages/network/rpcbind/patches/rpcbind-1.2.6-vulnerability_fixes-1.patch
- packages/network/wpa_supplicant/package.mk
- packages/network/wpa_supplicant/patches/wpa_supplicant-2.4-libnl3-includes.patch
- packages/web/nghttp2/package.mk
- bluez: update to 5.63
- ethtool: update to 5.16
- iwd: update to 1.25
- nghttp2: update to 1.47.0
- openvpn: update to 2.5.5
- rpcbind: update to 1.2.6
- wpa_supplicant: update to 2.10
> package updates: networking and bluetooth

- scripts/image
- tools/viewconfig
config/functions: `setup_toolchain` will add some additional values to TARGET_CFLAGS and TARGET_LDFLAGS. Move `show_config` to after this occurs to improve accuracy of reported CFLAGS/LDFLAGS. Packages may still alter these flags and I don't intend to do any further changes to report those alterations.
Should close #5517.
> Account for setup_toolchain in show_config's reported CFLAGS/LDFLAGS

- config/arch.x86_64
-m64 -mmmx -msse -msse2 -mfpmath=sse are not needed for x86-64 targets and are already enabled by default. Probably leftovers from 32-bit OpenELEC days. 
Build and runtime tested on Gemini Lake.
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
> Remove redundant ARCH specific *FLAGS for x86-64

- packages/addons/addon-depends/system-tools-depends/mmc-utils/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
Include the `mmc` utility in the system-tools
- https://www.kernel.org/doc/html/latest/driver-api/mmc/mmc-tools.html"
> [LE11] system-tools: include mmc-utils

- packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
- projects/Allwinner/patches/linux/0091-media-hantro-Fix-G2-HEVC-negotiated-pixelformat.patch
- projects/Allwinner/patches/linux/0092-media-Add-P010-tiled-format.patch
- projects/Allwinner/patches/linux/0093-media-Add-P010-format.patch
- projects/Allwinner/patches/linux/0094-media-hantro-Support-format-filtering-by-depth.patch
- projects/Allwinner/patches/linux/0095-media-hantro-postproc-Fix-buffer-size-calculation.patch
- projects/Allwinner/patches/linux/0096-media-hantro-postproc-Fix-legacy-regs-configuration.patch
- projects/Allwinner/patches/linux/0097-media-hantro-Store-VP9-bit-depth-in-context.patch
- projects/Allwinner/patches/linux/0098-media-hantro-sunxi-Enable-10-bit-decoding.patch
- projects/Allwinner/patches/linux/0099-media-hantro-postproc-Properly-calculate-chroma-offs.patch
10-bit VP9 decoding almost worked before, it just needed some plumbing.
@heitbaum if this goes in, please remove projects/Allwinner/patches/linux/0091-media-hantro-Fix-G2-HEVC-negotiated-pixelformat.patch in your Linux 5.17 PR
> Allwinner: VP9 10-bit support

- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
- packages/lang/lua52/config/lua52.pc
- packages/lang/lua52/package.mk
**Building with Lua 5.2 library enables mpv support of builtin stats OSD.**
Lua 5.2 is required to enable mpv player support of builtin stats OSD.
MPV doesn't support later Lua versions, newer versions aren't backwards
compatible, thus including version in a package name.
Upstream Lua doesn't include pkg-config file, including one from ArchLinux.
See https://github.com/mpv-player/mpv/wiki/FAQ#Why_does_mpv_not_support_Lua_53_or_newer
Build and run tested on Allwinner.
> mpv-drmprime: enable Lua support for support of built-in stats OSD

- packages/sysutils/dbus/package.mk
minor update from 1.13.22 (release candidate) to 1.14.0 (stable release
version of dbus)
changelog:
- https://gitlab.freedesktop.org/dbus/dbus/-/compare/dbus-1.13.22...dbus-1.14?from_project_id=1187
> dbus: update to 1.14.0

- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/librespot-depends/rust/package.mk
- packages/devel/autoconf-archive/package.mk
- packages/devel/autoconf-archive/patches/autoconf-archive-0001-AX_CC_MAXOPT-Fix-nvhpc-case.patch
- packages/devel/fakeroot/package.mk
- packages/python/devel/MarkupSafe/package.mk
- packages/python/devel/meson/package.mk
- autoconf-archive: update to 2022.02.11
- fakeroot: update to 1.28
- go: update to 1.17.8
- MarkupSafe: update to 2.1.0
- meson: update to 0.61.2
- rust: update to 1.59.0
> devtool package updates

- packages/linux/patches/raspberrypi/linux-999.03-fix-dirty-pipe.patch
Fix for https://dirtypipe.cm4all.com/
- build tested for RPi2, RPi4
- runtime tested for RPi4
In case for RPi it is not as easy as for the rest of LE10 to update the kernel to at least 5.10.102 is here just the dirty pipe fix.
> [LE10] linux (RPi): fix dirty pipe CVE-2022-0847

- packages/graphics/mesa/package.mk
no longer necessary since all classic drivers have been removed
> mesa: remove "prefer-crocus=true" opt

- packages/audio/alsa-lib/package.mk
- packages/audio/alsa-ucm-conf/package.mk
- packages/audio/alsa-utils/package.mk
Alsa website: https://www.alsa-project.org/wiki/Main_Page
update Alsa to 1.2.6
- alsa-ucm-conf: update to 1.2.6.3
- alsa-lib: update to 1.2.6.1
- alsa-utils: update to 1.2.6
> Update Alsa from 1.2.5 (2021-06) to 1.2.6 (2021-12)

- packages/security/openssl/package.mk
- https://www.openssl.org/news/secadv/20220315.txt
- https://www.openssl.org/news/changelog.html#openssl-30
update 3.0.1 to 3.0.2
Fixed a bug in the BN_mod_sqrt() function that can cause it to loop forever for non-prime moduli.
Internally this function is used when parsing certificates that contain elliptic curve public keys in compressed form or explicit elliptic curve parameters with a base point encoded in compressed form.
It is possible to trigger the infinite loop by crafting a certificate that has invalid explicit curve parameters.
Since certificate parsing happens prior to verification of the certificate signature, any process that parses an externally supplied certificate may thus be subject to a denial of service attack. The infinite loop can also be reached when parsing crafted …
> openssl: update to 3.0.2

- packages/lang/Python3/package.mk
- packages/lang/Python3/patches/Python3-0100-buildroot-patches.patch
- packages/python/devel/Mako/package.mk
- packages/python/devel/MarkupSafe/package.mk
- Python3: update 3.9.10 to 3.9.11
- https://www.python.org/downloads/release/python-3911/
- One of the buildroot patches was upstreamed
- MarkupSafe: update 2.1.0 to 2.1.1
- Mako: update 1.1.0 to 1.2.0
```
nuc11:~ # python -V
Python 3.9.11
```
> [le11] Python3 updates

- packages/mediacenter/kodi/profile.d/00-addons.conf
If user input in an addon setting text field includes a double quote, call to `oe_setup_addon` will fail with error, as current function tries to `eval $(var="someinputwith"doublequotes")` which includes additional unescaped double quote, resulting in unfinished string.
Proposed modification uses `sed` to single quote all strings and escape possible single quotes included in original input, avoiding also possible security issues.
> fixed oe_setup_addon unsafe with user inputs from addons settings

- packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
This PR updates the binary addon pvr.waipu to version 20.4.0-Nexus.
Changes in this release:
* Implement Device Authentication
Since I need some testers before backporting to Matrix, it would be great if you could upload this package to the repo soon @CvH
> pvr.waipu: update to 20.4.0-Nexus

- packages/tools/grub/package.mk
this package can only be build on an x86_64 host.
it uses the :target compiled grub-mkimage during the build.
whilst my testing to update to GLIBC_2.33 has raised the error, review /
remidiation could be looked at using :host grub-mkimage / cross-compile / ...
the problem being addressed here is:
- /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found
- (required by grub-mkimage)
refer: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=8ed005daf0ab03e142500324a34087ce179ae78e
Notes about the root cause:
Until glibc 2.32, stat64 etc. were redirected to __xstat64 etc. by
inline functions or macros; glibc 2.33 changed them to true
functions. As a result, code compiled against glibc 2.32 or older
will get the old __xstat64 etc.  implementation that is still
present, whereas …
> grub: use host:grub-mkimage to run grub - fix glibc host and target mismatched 

- packages/multimedia/dav1d/package.mk
- packages/multimedia/ffmpeg/patches/ffmpeg-support-dav1d-1-0-0.patch
release notes:
- https://code.videolan.org/videolan/dav1d/-/blob/master/NEWS
Only included the require FFmpeg patches to support the new unified threading of dav1d 1.0.0
- https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libdav1d.c
- the last commit to the 4.4 FFmpeg release was the Mar 16, 2021
- `lavc: rename AV_CODEC_CAP_AUTO_THREADS->AV_CODEC_CAP_OTHER_THREADS`
- https://github.com/FFmpeg/FFmpeg/commit/7d09579190def3ef7562399489e628f3b65714ce
- upstream commits required on top of FFmpeg 4.4
- https://github.com/FFmpeg/FFmpeg/commit/7ee17ec7e46afef0e0af20af196292ec75f50b62 (only the `define FF_DAV1D_VERSION_AT_LEAST(x,y)`)
- https://github.com/FFmpeg/FFmpeg/commit/d873b5fffc8292242549c4c026023e370e15c05b
- https://github.com/FFmpeg/FFmpeg/commit/e204846ec16c1ab34c7f3a681734cf5 …
> dav1d: update to 1.0.0 and patch ffmpeg to support

- projects/Generic/devices/x11/patches/kodi/kodi-100.06-dont-set-_NET_WM_STATE_FULLSCREEN.patch
... and move patch to Generic-x11
This reverts commit 40661a4054158f135b9fb1c5d817c816519426b6.
The patch is required to start X11 applications like 'chrome' or 'st' on top of kodi.
> Revert "kodi: remove X11 patch"

- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/addons/tools/system-tools/source/bin/7z
- packages/addons/tools/system-tools/source/bin/7za
- Fix for #6296 using missed fix from https://github.com/LibreELEC/LibreELEC.tv/pull/4441#commitcomment-55580567.
- Revision bump.
Partial backport of #6316
> system-tools: rev 129; Set executable flag of 7z/7za

- packages/tools/grub/package.mk
With these changes configure_target no longer complains about no-prefix
on cross compiling. On an aarch64 build host the target_ compile fails
when the build host gcc is used with the -m32 option. On an x86_64 build
host, the host gcc compiles grub (-m32 and assembly) successfully.
before:
```
checking for i386-pc-linux-gcc... no
checking for i386-pc-linux-egcs... no
checking for i386-pc-linux-cc... no
checking for gcc... gcc
configure: WARNING: using cross tools not prefixed with host triplet
checking for i386-pc-linux-objcopy... no
checking for objcopy... objcopy
checking for i386-pc-linux-strip... no
checking for strip... strip
checking for i386-pc-linux-nm... no
checking for nm... nm
checking for i386-pc-linux-ranlib... no
checking for ranlib... ranlib
checking which extra warnings …
```
> grub: fix builds on non x86_64 build hosts by using TARGET_ for build

- packages/lang/Python3/package.mk
release notes: https://www.python.org/downloads/release/python-3912/
This is a special release which fixes a regression introduced by BPO
46968 which caused Python to no longer build on Red Hat Enterprise Linux
6. There are only 12 other bugfixes on top of 3.9.11 in this release.
> Python3: update to 3.9.12

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
This fixes juddery playback with certain files, as reported on the forum
https://forum.libreelec.tv/thread/25384-skipping-stuttering-on-sd-iptv-with-10-0-2/
and adds several VC1 optimizations to improve SW decoding on ARM
> ffmpeg: update rpi patch

- packages/databases/sqlite/package.mk
update 3.37.1 to 3.38.2
release logs:
- https://www.sqlite.org/releaselog/3_37_2.html
- https://www.sqlite.org/releaselog/3_38_2.html
Additional changes in version 3.37.2 (2022-01-06):
Fix a bug introduced in version 3.35.0 (2021-03-12) that can cause
database corruption if a SAVEPOINT is rolled back while in PRAGMA
temp_store=MEMORY mode, and other changes are made, and then the outer
transaction commits. Check-in 73c2b50211d3ae26
Fix a long-standing problem with ON DELETE CASCADE and ON UPDATE CASCADE
in which a cache of the bytecode used to implement the cascading change
was not being reset following a local DDL change. Check-in
5232c9777fe4fb13.
Other minor fixes that should not impact production builds.
Changes in version 3.38.0 (2022-02-22):
Added the -> and ->> operators for easier …
> sqlite: update to 3.38.2

- packages/tools/nano/package.mk
The file browser clears the prompt bar also when using --minibar.
Linting now works also with a newer 'pyflakes'.
The behavior of ^K at a prompt has been enhanced: when there
is text after the cursor, just this text is erased. (In the usual 
situation, however, when the cursor is at the end of the answer,
the behavior is as before: the whole answer is erased.) 
At a prompt, M-6 copies the current answer into the cutbuffer.
Large external pastes into nano are handled more quickly.
> nano: update to 6.2

- packages/security/gnutls/package.mk
- packages/security/nss/package.mk
gnutls: update to 3.7.4
- https://lists.gnupg.org/pipermail/gnutls-help/2022-March/004738.html
nss: update to 3.76.1
- https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_76.html
- https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_76_1.html
- Bug 1756271 - Remove token member from NSSSlot struct.
- https://hg.mozilla.org/projects/nss/rev/932ffb74083cee8d5ef2f2934969870b4a354fc8
> security package updates

- packages/sysutils/squashfs-tools/package.mk
minor updates:- https://github.com/plougher/squashfs-tools/releases/tag/4.5.1
4.5.1	17 MAR 2022	New Manpages, Fix CVE-2021-41072 and miscellaneous improvements and bug fixes
1. Major improvements
1.1 This release adds Manpages for Mksquashfs(1), Unsquashfs(1),
Sqfstar(1) and Sqfscat(1).
1.2 The -help text output from the utilities has been improved
and extended as well (but the Manpages are now more
comprehensive).
1.3 CVE-2021-41072 which is a writing outside of destination
exploit, has been fixed.
2. Minor improvements
2.1 The number of hard-links in the filesystem is now also
displayed by Mksquashfs in the output summary.
2.2 The number of hard-links written by Unsquashfs is now
also displayed in the output summary.
2.3 Unsquashfs will now write to a pre-existing destination
directory, …
> squashfs-tools: update to 4.5.1

- packages/network/bluez/package.mk
Release of BlueZ 5.64
- 19th March 2022, 06:18 am by Tedd Ho-Jeong An
This is another release mostly with the bug fixes on HOG, GATT, A2DP,
Media, AVDTP, AVRCP, and scanning failure. Also, this release includes a
fix for building with old glibc (< 2.25), and other minor issues found
with the static code analyzing tool. ISO packet support is added to the
emulator as a part of LE Audio development.
> bluez: update to 5.64

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
- gmmlib: update to 22.1.2
- minors
- https://github.com/intel/gmmlib/compare/intel-gmmlib-22.1.0...intel-gmmlib-22.1.2
- media-driver: update to 22.3.1
- https://github.com/intel/media-driver/compare/intel-media-22.3.0...intel-media-22.3.1
```
Generic.x86_64-devel-20220331150530-2ba6e2f
Linux nuc11 5.17.1 #1 SMP Wed Mar 30 09:33:15 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:2f11e994f322f7376476b186293a3df34246b9a7). Platform: Linux x86 64-bit
Kodi compiled 2022-03-30 by GCC 12.0.1 for Linux x86 64-bit version 5.17.1 (332033)
Running on LibreELEC (heitbaum): devel-20220331150530-2ba6e2f 11.0, kernel: Linux x86 64-bit version 5.17.1
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 …
```
> Intel Graphic Updates

- packages/sysutils/util-linux/package.mk
update 2.37.4 to 2.38
release notes:
- https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/v2.38-ReleaseNotes
additionally handle minus '-' in PKG_VERSION="2.38-rc4" in PKG_URL
includes NEW COMMAND: lsfd
lsfd is a NEW COMMAND. lsfd is intended to be a modern replacement for lsof(8)
on Linux systems. Unlike lsof, lsfd is specialized to Linux kernel; it supports
Linux specific features like namespaces with simpler code. lsfd is not a
drop-in replacement for lsof; they are different in the command line interface
and output formats. lsfd uses Libsmartcols for output formatting and filtering.
For example: lsfd -Q 'ASSOC == "exe"' prints all running executables.
(Thanks to Masatake YAMATO)
/usr/bin/lsfd is 107760 bytes on Generic
man page here:
- …
> util-linux: update to 2.38

- packages/graphics/mesa/package.mk
- packages/graphics/mesa/patches/mesa-999.01-panfrost-process-scissor-state-earlier.patch
announce:
https://lists.freedesktop.org/archives/mesa-announce/2022-March/000667.html
```
Generic.x86_64-devel-20220329230628-893f7ac
Linux nuc11 5.17.1 #1 SMP Tue Mar 29 04:22:04 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:2f11e994f322f7376476b186293a3df34246b9a7). Platform: Linux x86 64-bit
Kodi compiled 2022-03-29 by GCC 12.0.1 for Linux x86 64-bit version 5.17.1 (332033)
Running on LibreELEC (heitbaum): devel-20220329230628-893f7ac 11.0, kernel: Linux x86 64-bit version 5.17.1
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021
CApplication::CreateGUI - …
```
> mesa: update to 22.0.1

- packages/network/bluez/patches/bluez-22-Fix-gatt-db-attribute-get-index.patch
This PR add a patch to fix a gatt database issue which caused the 2nd Gen Amazon Fire TV remote (the model with volume ,microphone and power buttons) to stop working correctly after bluez 5.64 bump.
Bluez bug report https://github.com/bluez/bluez/issues/326
This PR will also close https://github.com/LibreELEC/LibreELEC.tv/issues/6348
> bluez: add upstream patch to fix gatt database issue 

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
This fixes wifi channels 12+13 not working with the brcmfmac driver.
> [le11] linux (RPi): update to 5.15.32-ddd39a7

- packages/addons/service/jellyfin/changelog.txt
- packages/addons/service/jellyfin/package.mk
- packages/addons/service/jellyfin/source/bin/jellyfin-downloader
Jellyfin 10.8.0 for LE11 support.
- #6064
- #6065
- #6066
> jellyfin: update to 10.8.0-beta1 and addon (101)

- packages/compress/zlib/package.mk
- packages/sysutils/systemd/package.mk
- packages/x11/data/xkeyboard-config/package.mk
- packages/x11/lib/xtrans/package.mk
- packages/x11/proto/xorgproto/package.mk
- packages/x11/proto/xorgproto/patches/xorgproto-0001-pkgconfig.patch
- packages/x11/util/util-macros/package.mk
Tested built across all except RPi,Amlogic - as below.
Why did I create this PR - whilst testing the current `ncurses 6.3-20220122` release it was noted that only zlib was in the HOST toolchain/share/pkgconfig directory, and that the majority of .pc files are in lib for both TARGET and HOST. The bug identified in 20220122 has been rectified in 20220129 - but the PR is to tidy up the LE build environment.
- https://lists.gnu.org/archive/html/bug-ncurses/2022-01/msg00017.html
- https://lists.gnu.org/archive/html/bug-ncurses/2022-01/msg00018.html
Reading: 
- https://bugs.freedesktop.org/show_bug.cgi?id=89769
Based on the reading - all Independant `.pc` files should be in the `datadir` which is  `share`. But given that the LE build is exclusively a cross compile environment - that statement …
> PKGCONFIG use ./lib/pkgconfig/ for both host and target

- packages/compress/zlib/package.mk
Changelog: https://www.zlib.net/ChangeLog.txt
ChangeLog file for zlib
Changes in 1.2.12 (27 Mar 2022)
- Cygwin does not have _wopen(), so do not create gzopen_w() there
- Permit a deflateParams() parameter change as soon as possible
- Limit hash table inserts after switch from stored deflate
- Fix bug when window full in deflate_stored()
- Fix CLEAR_HASH macro to be usable as a single statement
- Avoid a conversion error in gzseek when off_t type too small
- Have Makefile return non-zero error code on test failure
- Avoid some conversion warnings in gzread.c and gzwrite.c
- Update use of errno for newer Windows CE versions
- Small speedup to inflate [psumbera]
- Return an error if the gzputs string length can't fit in an int
- Add address checking in clang to -w option of configure
- …
> zlib: update to 1.2.12

- packages/network/openssh/package.mk
nuc11:~ # ssh -V
OpenSSH_9.0p1, OpenSSL 3.0.2 15 Mar 2022
OpenSSH 9.0 was released on 2022-04-08. It is available from the
mirrors listed at https://www.openssh.com/.
OpenSSH is a 100% complete SSH protocol 2.0 implementation and
includes sftp client and server support.
Once again, we would like to thank the OpenSSH community for their
continued support of the project, especially those who contributed
code or patches, reported bugs, tested snapshots or donated to the
project. More information on donations may be found at:
https://www.openssh.com/donations.html
Changes since OpenSSH 8.9
=========================
This release is focused on bug fixing.
Potentially-incompatible changes
--------------------------------
This release switches [scp(1)](https://man.openbsd.org/scp.1) from using …
> openssh: update to 9.0p1

- config/arch.aarch64
- config/arch.arm
- packages/devel/binutils/package.mk
- packages/devel/binutils/patches/binutils-01-warn-for-uses-of-system-directories-when-link.patch
- packages/devel/binutils/patches/nodocs.patch
- packages/devel/glibc/package.mk
- packages/devel/glibc/patches/arm/glibc-add-support-for-SHT_RELR-sections.patch
- packages/devel/glibc/patches/arm/glibc-tls-libwidevinecdm.so-since-4.10.2252.0-has-TLS-with.patch
- packages/devel/glibc/patches/glibc-fix-dns-with-broken-routers.patch
- packages/lang/gcc/package.mk
- packages/sysutils/fuse/package.mk
- packages/sysutils/fuse/patches/fuse-0003-build-with-glibc-2.34.patch
This updates binutils to 2.37 and glibc to 2.34. Patches were refreshed for both. ~~BlueZ gets updated and~~ fuse gets patched for glibc-2.34 compatibility. Gcc and glibc configure options have been updated. Glibc is removing a nonexistent option, and disabling Werror. gcc is removing a nonexistent option and restoring some defaults since GCC5.
Glibc-2.34 will probably be disruptive. From the release announce: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html
> In order to support smoother in-place-upgrades and to simplify
the implementation of the runtime all functionality formerly
implemented in the libraries libpthread, libdl, libutil, libanl has
been integrated into libc.  New applications do not need to link with
-lpthread, -ldl, -lutil, -lanl anymore.  For …
> Toolchain Updates

- packages/sysutils/busybox/patches/busybox-07-hwclock_fix_settimeofday.patch
As reported in the [forum](https://forum.libreelec.tv/thread/25472-le11-rpi4-rtc-hwclock-not-working/?postID=168162#post168162)  using `hwclock --hctosys ...` result in 
```
hwclock: settimeofday: Invalid argument
```
Add upstream busybox patch for glib v2.31+ compatibility.
Fix for master branch is included in #6154
> busybox: hwclock: add settimeofday() fix

- packages/network/wireless-regdb/package.mk
log:
- https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/log/
> wireless-regdb: update to 2022-04-08

- packages/addons/addon-depends/cxxtools/patches/cxxtools-2.2.1-make-cxxtools-char-a-trivial-class-by-defining-the-default.patch
- packages/addons/addon-depends/cxxtools/patches/cxxtools-2.2.1-make-explicit-cast-in-cxxtools-char-when-moving-or-copying-data.patch
- packages/addons/addon-depends/cxxtools/patches/cxxtools-2.2.1-superflous-copy-constuctor.patch
reference:
- https://github.com/maekitalo/cxxtools/issues/30
To fix the following error:
```
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/11.2.0/string_view:101:21: error: static assertion failed
101 |       static_assert(is_trivial_v<_CharT> && is_standard_layout_v<_CharT>);
|                     ^~~~~~~~~~~~~~~~~~~~
```
Subsequent to the update to the gcc 11 
- #6253
> cxxtools: fix compile with gcc11

- packages/emulation/libretro-uae4arm/patches/libretro-fix-ordered-comparison-of-pointer-with-integer-zero.patch
Fixes compile error with gcc 11.2
raised as upstream: 
- https://github.com/libretro/uae4arm-libretro/pull/22
```
armv7a-libreelec-linux-gnueabihf-g++ -fPIC -march=armv7-a -mtune=cortex-a8 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv3 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -D__NEON_OPT -DGIT_VERSION=6440e1cb65 -O3 -fomit-frame-pointer -finline -fno-builtin -D__LIBRETRO__ -DCPU_arm -DARM_ASSEMBLY -DARMV6_ASSEMBLY -DPANDORA -DROM_PATH_PREFIX=\"./\" -DDATA_PREFIX=\"./data/\" -DSAVE_PREFIX=\"./saves/\" -DRASPBERRY -DPICASSO96 -DUSE_ARMNEON -DINLINE="inline"  -fexceptions -fpermissive   -I./src -I./libretro/osdep -I./src/include -I./libretro -I./libretro/libco -I./libretro/core -I./utils -I./deps/zlib -I./libretro/libco -I./libretro/core …
```
> libretro-uae4arm: fix gcc11 build

- packages/emulation/libretro-dosbox/package.mk
reference:
- https://github.com/libretro/dosbox-libretro/issues/137
To fix the following error:
```
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -march=x86-64 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -fPIC -DPIC -D__LIBRETRO__ -fPIC -I./src -I./libretro -I./libretro-common/include -I./include -I./src/midi/munt -DC_HAVE_MPROTECT="1" -O3 -DNDEBUG -DGIT_VERSION=\"" 6440e1cb65"\" -DSVN_VERSION=\"\" -c libretro/dosbox.cpp -o libretro/dosbox.o
In file included from libretro/dosbox.cpp:38:
./include/setup.h:92:35: error: ISO C++17 does not allow dynamic exception specifications
92 |         Value& operator= (Hex in) throw(WrongType)                { return copy(Value(in));} …
```
> libretro-dosbox: build with -std=gnu++11 to fix gcc11 build

- packages/emulation/libretro-mame2015/patches/libretro-mame2015-100.01-cross-compile.patch
- packages/emulation/libretro-mame2015/patches/libretro-mame2015-900.01-update-for-python3-and-enable-override-on-objdump.patch
backport of:
- https://github.com/libretro/mame2015-libretro/pull/91
> libretro-mame2015: update for python3 and enable override on OBJDUMP

- packages/lang/gcc-arm-aarch64-none-linux-gnu/package.mk
64bit arm kernel builds (RPi4, RK3399, AML) fail with an internal compiler error since kernel gcc was bumped to 11.2. see eg this RPi4 build log of LE master http://ix.io/3UX4 or  #6372
Revert the gcc bump until the issue is resolved
Fixes:  #6372
> Revert "gcc-arm-aarch64-none-linux-gnu: update to 11.2-2022.02"

- packages/addons/service/mariadb/changelog.txt
- packages/addons/service/mariadb/package.mk
TokuDB's configure script seems somewhat broken when it comes to
cross-compilation so we shall disable it and also disable TokuDB.
Additionally TokuDB has been deprecated in MariaDB 10.5.y.
release notes of MariaDB 10.4.22:
- https://mariadb.com/kb/en/mariadb-10422-release-notes/
note: we haven’t updated to 10.4.24 at this time as there is a build issue with 10.4.24
```
CMake Error at /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR)
(Required is at least version "3.3.24")
Call Stack (most recent call first):
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/share/cmak …
```
> mariadb: update to 10.4.22 and addon (106)

- packages/devel/crossguid/package.mk
- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
- packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch
- packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
- update to latest kodi
- crossguid change to cmake (needed due https://github.com/xbmc/xbmc/pull/20982)
- rebased sigterm patch due https://github.com/xbmc/xbmc/pull/21200
broken again :) @mglae mind a look? 
is this something we could actually upstream ? I am not really understanding why we carry a patch that allows to close kodi at linux
```
/LE/build.LibreELEC-x11.x86_64-11.0-devel/build/kodi-89eeb1432acba1d8e417a29632c8d75fd5ecfaed/xbmc/Application.cpp:3222:8: error: 'm_ExitCodeSet' was not declared in this scope; did you mean 'm_ExitCode'?
3222 |   if (!m_ExitCodeSet)
|        ^~~~~~~~~~~~~
|        m_ExitCode
[826/1604] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/SeekHandler.cpp.o
ninja: build stopped: subcommand failed.
```
> kodi: update to 2022-04-13

- packages/emulation/libretro-mame2015/patches/libretro-mame2015-100.01-cross-compile.patch
REALCC is already set in package.mk so the hunk can be dropped
> [le11] libretro-mame2015: simplify cross-compile patch

- packages/emulation/libretro-mame2015/patches/libretro-mame2015-100.01-cross-compile.patch
> [le10] libretro-mame2015: simplify cross-compile patch

- packages/mediacenter/kodi/package.mk
Currently, kodi builds internal rapidjson, even though it's provided as dependency due to missing config option. Fix that.
> [LE11] kodi: external rapidjson should be used

- packages/devel/binutils-or1k/package.mk
- packages/lang/gcc-or1k/package.mk
There is no reason to depend on target gcc, so depend on toolchain:host instead of toolchain.
> [LE11] Relax or1k toolchain dependency

- packages/addons/addon-depends/go/package.mk
- packages/debug/valgrind/package.mk
- packages/devel/cmake/package.mk
- packages/python/graphics/Pillow/package.mk
- packages/tools/mtools/package.mk
- Pillow: update to 9.1.0
- go: update to 1.18.1
- valgrind: update to 3.19.0
-  mtools: update to 4.0.39
- cmake: update to 3.23.1
> devtool updates

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
Update to GStreamer 1.20.1:
- gst-plugins-bad: update to 1.20.1
- gst-plugins-base: update to 1.20.1
- gstreamer: update to 1.20.1
Release notes:
https://gstreamer.freedesktop.org/releases/1.20/#1.20.1
> GStreamer updates

- packages/devel/glibc/package.mk
These are relics of an ancient past and are no longer needed
nowadays - thus no one noticed the ld.so symlink was broken,
pointing to 'ld-*.so'.
So let's just get rid of it.
> glibc: drop broken ld.so symlinks

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
**Update glslang to 11.9.0:**
- spirv-headers: update githash to 2022-03-16
- spirv-tools: update githash to 2022-04-05
- glslang: update to 11.9.0
[CHANGES.md](https://github.com/KhronosGroup/glslang/blob/11.9.0/CHANGES.md#other-changes)
**11.9.0 2022-04-06**
Other changes
Add GLSL version override functionality
Add eliminate-dead-input-components to -Os
Add enhanced-msgs option
Explicitly use Python 3 for builds
> Vulkan updates

- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/addons/tools/system-tools/source/bin/7z
- packages/addons/tools/system-tools/source/bin/7za
- packages/addons/tools/system-tools/source/default.py
- Fix for #6296 using missed fix from https://github.com/LibreELEC/LibreELEC.tv/pull/4441#commitcomment-55580567.
- ~Only include "st" terminal for X11, it is useless for other Generic devices.~
- Execute "st" only on X11 device.
- Revision bump.
> system-tools: rev 129; Execute "st" only on Generic X11; Set executable flag of 7z/7za 

- distributions/LibreELEC/options
This adds a one minute pause when mounting iSCSI devices during busybox's init to present a deprecation notice.
My understanding from past discussion is no one within LE uses iSCSI and consensus was to remove this feature in a future release. This PR is meant to either encourage people to move off iSCSI prior to its outright removal in LE11 (or later), or to have someone that uses iSCSI step up to maintain it.
> distro: disable iscsi support

- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
fix for reported bug at:
- https://forum.libreelec.tv/thread/25517-service-ttyd-web-ssh-terminal-missing-libraries-on-10-0-2-on-raspberry/?postID=168543
```
LD_LIBRARY_PATH=$LD_LIBARY_PATH:.kodi/addons/service.ttyd/lib .kodi/addons/service.ttyd/bin/ttyd -O -T xterm256 -p 11111 login root
[2022/04/17 19:55:12:4690] N: ttyd 1.6.3 (libwebsockets 4.3.0-10.0.0-2468-g5197a00a90)
[2022/04/17 19:55:12:4691] N: tty configuration:
[2022/04/17 19:55:12:4691] N:   start command: login root
[2022/04/17 19:55:12:4691] N:   close signal: SIGHUP (1)
[2022/04/17 19:55:12:4691] N:   terminal type: xterm256
[2022/04/17 19:55:12:4692] N:   check origin: true
[2022/04/17 19:55:12:4699] E: lws_create_context: failed to load evlib_uv
[2022/04/17 19:55:12:4699] E: libwebsockets context creation failed
```
``` …
```
> [le11] ttyd: include missing evlib_uv library and addon (105)

- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
> [le10] ttyd: include missing evlib_uv library and addon (105)

- packages/addons/service/jellyfin/changelog.txt
- packages/addons/service/jellyfin/package.mk
> [le11] jellyfin: update to 10.8.0-beta2

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/addons/tools/ffmpeg-tools/package.mk
The buildhost had the shared libraries libxcb available, and FFmpegx has been picking them up. This updates the ffmpegx packages to not use libxcb unless explicitly compiled with x11. 
In addition x265 was being included in both the `PKG_DEPENDS_TARGET` and the specific **x86_64** `PKG_DEPENDS_TARGET` - removed from the main `PKG_DEPENDS_TARGET`.
the `ffmpeg-tools` addon has been updated to included the required shared libraries. Currently ffmpeg errors unable to find libxcb-shm.
> [le11] tools.ffmpeg-tools: fix missing libraries and addon (118)

- packages/tools/dtc/package.mk
- packages/tools/dtc/patches/dtc-0001-libfdt-soname-version.patch
- superceeds #5050
- Incorporates comments on #5050
- Updates 1.6.0 to 1.6.1
- Did not update to meson at this time (as it has not yet been update to include version number, etc …) to review on next update.
- https://git.kernel.org/pub/scm/utils/dtc/dtc.git/log/
- A number of fixes have accumulated, so rolling up another release. 
- https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/?id=b6910bec11614980a21e46fbccc35934b671bd81
> dtc: update to 1.6.1

- packages/lang/gcc-aarch64/package.mk
- packages/lang/gcc-or1k/package.mk
- packages/lang/gcc/package.mk
Update from 11.2.0 (July 28, 2021) to 11.3.0 (April 21, 2022)
- https://gcc.gnu.org/gcc-11/
- 189 bugs fixed
- https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&list_id=344738&resolution=FIXED&target_milestone=11.3
- https://gcc.gnu.org/gcc-11/changes.html
> gcc: update to 11.3.0

- Makefile
- scripts/makefile_helper
This adds a script to handle sourcing of BUILD_DIR from `${ROOT}/.librelec/options` or `${HOME}/.libreelec/options` when running `make clean` or `make distclean`. I understand that there are additional places that BUILD_DIR could be set, but I believe these are the most likely places that a builder would use.
Closes #6292.
> Have make clean/distclean respect builder's set BUILD_DIR

- scripts/makefile_helper
Add a check for the 2 variables, if for whatever reason they weren’t set 
`rm -rf /.*/*` evaluates equivalent of `rm -rf /`
> scripts/makefile_helper: make sure variables are set before running an rm

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
- packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
- inputstream.adaptive: update 20.1.2-Nexus to 20.2.0-Nexus
- inputstream.ffmpegdirect: update 20.1.0-Nexus to 20.2.0-Nexus
- inputstream.rtmp: update 20.1.0-Nexus to 20.2.0-Nexus
> [le11] kodi-binary-addons: update to latest versions - inputstream.*

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/addon-depends/dotnet-runtime-depends/dotnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
Update:
- [dotnet6-runtime: update to 6.0.4](https://github.com/LibreELEC/LibreELEC.tv/commit/bb4d06d709c5c104a09a06b49d380ceac183f3f8)
- [aspnet6-runtime: update to 6.0.4](https://github.com/LibreELEC/LibreELEC.tv/commit/3ba1dbcf94dd397da30db55c349b361373827020)
As fyi - emby4.7 will require dotnet 6. The bootstrap will need to be checked against 4.7.
- https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.7.0.36
- https://github.com/MediaBrowser/Emby.Releases/releases
- https://emby.media/community/index.php?/topic/21348-emby-latest-versions/
> update dotnet 6.0.1 to 6.0.4

- scripts/makefile_helper
Hopefully a workaround for Jenkin's build setup. (Trying to build RPi2.x86_64?)
> makefile_helper: only source necessary values from buildsystem's config

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
changelog:
- https://github.com/syncthing/syncthing/releases
support for go1.18
> [le11] syncthing: update to 1.20.0 and addon (119)

- packages/security/openssl/package.mk
- two moderate and two low severity fixes
- https://www.openssl.org/news/secadv/20220503.txt
- Changelog:
- https://www.openssl.org/news/changelog.html#openssl-30
> openssl: update to 3.0.3

- packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
patch from:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=688601
- https://savannah.gnu.org/bugs/?45763
To fix the issue identified with the `kernel-firmware` > `20220209` as part of the 
- #6423 kernel update
- https://github.com/LibreELEC/LibreELEC.tv/pull/6423/commits/9e00430a58f4608b17de0fa5999d7b2df34ddb7d
```
make[4]: /bin/sh: Argument list too long
make[4]: *** [scripts/Makefile.build:442: drivers/base/firmware_loader/builtin/built-in.a] Error 127
make[3]: *** [scripts/Makefile.build:550: drivers/base/firmware_loader/builtin] Error 2
make[2]: *** [scripts/Makefile.build:550: drivers/base/firmware_loader] Error 2
make[1]: *** [scripts/Makefile.build:550: drivers/base] Error 2
make[1]: *** Waiting for unfinished jobs....
```
> make: fails to execute extraordinarily long command lines

- packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
as aclocal-1.16 may not be available on the build host as make has no
dependancies. remove patch to configure.ac. patch still works as the
required depends are still available.
fix error introduced with #6452
> make: update command line patch not to touch configure.ac

- packages/wayland/lib/fcft/package.mk
- packages/wayland/lib/seatd/package.mk
- packages/wayland/libinput/package.mk
- packages/wayland/libxkbcommon/package.mk
- packages/wayland/util/bemenu/package.mk
- packages/wayland/util/foot/package.mk
- packages/wayland/waylandpp/package.mk
Wayland updates:
- fcft: update to 3.0.1
- seatd: update to 0.6.4
- bemenu: update to 0.6.7
- foot: update to 1.11.0
- waylandpp: update to 0.2.10
- libxkbcommon: update to 1.4.0 and HSTS
- libinput: update to 1.20.0
> Wayland updates

- packages/devel/automake/patches/automake-02-build-fix-race-in-parallel-builds.patch
Jenkin build failed with
`
[@]system_acdir[@],/var/lib/jenkins/LE/build4/workspace/H5/LibreELEC.tv/build.LibreELEC-H5.arm-11.0-devel/toolchain/share/aclocal,g'\'' -e '\''s,[@]am__isrc[@],!!@!!am__isrc!!@!!,g'\'' | /bin/bash ./config.status --file=- | sed -e '\''s,!!@!!am__isrc!!@!!,@'\'''\''am__isrc@,g'\'' ) </var/lib/jenkins/LE/build4/workspace/H5/LibreELEC.tv/build.LibreELEC-H5.arm-11.0-devel/build/automake-1.16.5/$in >t/ax/test-defs.sh-t	if LC_ALL=C grep '\''@[a-zA-Z0-9_][a-zA-Z0-9_]*@'\'' t/ax/test-defs.sh-t; then echo "t/ax/test-defs.sh contains unexpanded substitution (see lines above)"; exit 1; fi; chmod a-w t/ax/test-defs.sh-t && mv -f t/ax/test-defs.sh-t t/ax/test-defs.sh	if LC_ALL=C grep '\''@[a-zA-Z0-9_][a-zA-Z0-9_]*@'\'' lib/Automake/Config.pm-t; then echo …
> automake: fix race in parallel builds

- distributions/LibreELEC/options
- projects/ARM/options
- projects/Allwinner/options
- projects/Amlogic/options
- projects/Generic/options
- projects/NXP/options
- projects/Qualcomm/devices/Dragonboard/options
- projects/RPi/options
- projects/Rockchip/options
- projects/Samsung/options
`ALSA_SUPPORT` is a staple of the distro it should be included in the distro options.
This also fixes an issue with `rpi-cirrus-config` always including `alsa-utils` even when `ALSA_SUPPORT="no"`
> move ALSA_SUPPORT from project options to distro options

- packages/linux/package.mk
- tools/check_kernel_config
This fixes an issue where string options aren't checked properly:
```
LINUX: kernel options not correct: 
CONFIG_NLS_DEFAULT="utf8"
Please run ./tools/check_kernel_config
```
> scripts/check_kernel_config: handle string options

- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
source files for 1.20.0 have been removed.
release notes:
- https://github.com/syncthing/syncthing/releases/tag/v1.20.1
bug fixes:
- Spurious failure of new connections ("unknown (newer?) version of the protocol" etc)
- 
Replaces #6455
> syncthing: update to 1.20.1 and addon (120)

- packages/multimedia/media-driver/package.mk
log:
- https://github.com/intel/media-driver/compare/intel-media-22.4.0...intel-media-22.4.1
```
Generic.x86_64-devel-20220508090822-195fdfb
Linux nuc11 5.18.0-rc5 #1 SMP Sun May 8 09:10:00 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:ee3663fd468ec417ea0bba20b0d18f3448c8980c). Platform: Linux x86 64-bit
Kodi compiled 2022-05-08 by GCC 12.1.0 for Linux x86 64-bit version 5.18.0 (332288)
Running on LibreELEC (heitbaum): devel-20220508090822-195fdfb 11.0, kernel: Linux x86 64-bit version 5.18.0-rc5
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021 …
```
> media-driver: update to 22.4.1

- packages/linux-firmware/intel-ucode/package.mk
```
[    0.000000] microcode: microcode updated early to revision 0xa4, date = 2022-02-01
[    0.000000] Linux version 5.18.0-rc6 (docker@b96190ee693f) (x86_64-libreelec-linux-gnu-gcc-12.1.0 (GCC) 12.1.0, GNU ld (GNU Binutils) 2.38) #1 SMP Wed May 11 01:10:30 UTC 2022
```
release notes:
- https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00617.html
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220510
> intel-ucode: update to 20220510

- distributions/LibreELEC/options
I initially added support for IWD 4 years ago. It's time to switch in LE 11. The required kernel options should be propagated to all the platforms now as well.
I've been using it in my personal builds since adding it and it has been wonderful
I would recommend anyone wanting to try it in their own builds use
```
echo WIRELESS_DAEMON=\"iwd\" >> ~/.libreelec/options
```
> default to using iwd

- packages/sysutils/open-iscsi/package.mk
- packages/sysutils/open-iscsi/patches/open-iscsi-07-usr-run-for-config.patch
- packages/sysutils/open-iscsi/system.d/iscsi-initiator.service
- packages/sysutils/open-iscsi/tmpfiles.d/iscsi.conf
- packages/virtual/network/package.mk
This allows using the iscsiadm at all utilities from userspace.
I added a patch that was adapted from fedora sources (the patch doesn't apply). https://src.fedoraproject.org/rpms/iscsi-initiator-utils/blob/rawhide/f/0006-use-var-for-config.patch
The patch is needed to move configuration to r/w space.
`open-iscsi:target` depends on `open-iscsi:host` because of `iscsi-iname` which is used to create a unique initiator name for the target.
I tested this on my RPi4
```
Linux LibreELEC 5.15.32 #1 SMP Wed May 4 19:30:26 PDT 2022 aarch64 GNU/Linux
192.168.1.108:3260,1 iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1
Logging in to [iface: default, target: iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1, portal: 192.168.1.108,3260] (multiple)
Login to [iface: default, target: …
```
> open-iscsi: allow installing utilities for target

- projects/RPi/filesystem/usr/share/alsa/cards/vc4-hdmi.conf
See https://mailman.alsa-project.org/pipermail/alsa-devel/2022-April/200025.html
Only a few minor cleanups compared to our current version.
> RPi: update vc4-hdmi ALSA card conf to version sent upstream

- packages/tools/grub/patches/grub-0001-Fix-Werror-array-bounds-array-subscript-0-is-outside-array-bounds.patch
- packages/tools/grub/patches/grub-0002-lib-reed-solomon-Fix-array-subscript-0-outside-array-bounds.patch
- packages/x11/driver/xf86-video-vmware/patches/xf86-video-vmware-0001-gcc12.patch
- packages/x11/xserver/xorg-server/patches/xorg-server-100.03-render-fix-build-with-gcc12.patch
Testing of gcc-12 has been going on for the last couple of months against :master. Many of the packages have already incorporated the gcc-12 issues in the updates integrated into LE11.
These are the remaining packages that need patching to support the new compiler (all of which are already in upstream or (in the case of the xf86-video-vmware patch - waiting for merge.))
- grub: enable build with gcc-12.1.0
- xf86-video-vmware: vmwgfx: fix missing array notation for gcc-12.1.0
- https://gitlab.freedesktop.org/xorg/driver/xf86-video-vmware/-/merge_requests/1
- This is actually a bug fix
- xorg-server: allow build with gcc-12.1.0
this PR is ready to go.
build of all of:- successful (with the above patches and gcc-12.1.0)
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner …
```
> upstream patches to support gcc-12.1.0

- packages/web/libmicrohttpd/package.mk
- the examples link against host glibc 2.35 which fails, fixes 
```
libtool: link: /build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -march=x86-64 -Wall -pipe -O2 -fomit-frame-pointer -DNDEBUG -fno-strict-aliasing -march=x86-64 -Wl,--as-needed -fuse-ld=gold -o benchmark benchmark-benchmark.o  ../../src/microhttpd/.libs/libmicrohttpd.a -L/build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib -lpthread /build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libgnutls.so -L/usr/lib -lz /build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libidn2.so -lnettle -lhogweed …
```
> libmicrohttpd: disable examples / fix build

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.05-cubepp-fix-VK-KHR-display-compile-error.patch
- vulkan-loader: update to 1.3.213
- vulkan-tools: update to 1.3.213
- vulkan-headers: update to 1.3.213
Reference:
- https://github.com/KhronosGroup/Vulkan-Tools/pull/650
- https://github.com/KhronosGroup/Vulkan-Docs/commit/71decb7f868d3891974eab139f03c7c6c87fea4d#
* Update release number to 213 for this update.
Public Issues:
* Replace the list of <<formats-packed, Packed Formats>> with a generated
version, and update the format generator script to support conditionals
(public pull request 1823).
* Fix typo in apiext:VK_INTEL_performance_query (public issue 1845).
Internal Issues:
* Add valid usage statement limiting
slink:VkDisplaySurfaceCreateInfoKHR::pname:transform to a single,
supported transformation (internal merge request 5166).
* Update sample code for apiext:VK_KHR_ray_query …
> Vulkan updates: 1.3.213

- packages/emulation/libretro-fsuae/package.mk
The host utils are meant to be build on the host (using the host
libaries.) This fixes the error when the glibc libraries are older on
the build host, than the target.
./gen/build68k < ./src/table68k > ./gen/cpudefs.c
./gen/build68k: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./gen/build68k)
make[1]: *** [Makefile:2011: gen/cpudefs.c] Error 1
> libretro-fsuae: add host build for gen target as designed

- packages/emulation/libretro-sameboy/package.mk
- packages/sysutils/util-linux/package.mk
fix `hexdump` not found 
```
echo "/* AUTO-GENERATED */" > ../libretro/agb_boot.c
echo "const unsigned char agb_boot[] = {" >> ../libretro/agb_boot.c
hexdump -v -e '/1 "0x%02x, "' ../BootROMs/prebuilt/agb_boot.bin >> ../libretro/agb_boot.c
/bin/sh: 1: hexdump: not found
make: *** [Makefile:371: ../libretro/agb_boot.c] Error 127
```
- libretro-sameboy: update dependency to include util-linux:host as hexdump is needed for the build
-  util-linux: enable all-programs in :host build so that hexdump is available in toolchain/bin
> Fix libretro-sameboy build

- packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
Further Fix for
- #6452
- #6461 
fixed with a small patch.
`features/long_command_line .............................. ok     (1 passed) `
as we can’t patch `configure.ac` without a dependency loop. 
- and with the #6461 thus not defining `HAVE_LINUX_BINFMTS_H` and `HAVE_SYS_USER_H` 
The below patch always includes the required `#include` files.
```
diff --git a/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch b/packages/devel/make/patches/make-02-fix-l
arge-command-line-on-POSIX-systems.patch
index 0e4cc274306..12ac8b767a2 100644
--- a/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
+++ b/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
@@ -44,14 +44,12 @@ diff --git a/src/job.c b/src/job.c …
```
> make: fails to execute extraordinarily long command lines - further fix

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/addon-depends/dotnet-runtime-depends/dotnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
Refer:
- https://forum.libreelec.tv/core/conversation/5928-dotnet-6-0-on-arm32/
- https://dotnet.microsoft.com/en-us/download/dotnet/6.0
- Release notes:
- https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.5/6.0.5.md
> dotnet-runtime: Update .NET and ASP.NET 6.x to 6.0.5 and addon (117)

- packages/graphics/mesa/package.mk
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/docs/relnotes/22.1.0.rst
ann:
- https://lists.freedesktop.org/archives/mesa-announce/2022-May/000675.html
```
Generic.x86_64-devel-20220518214014-a6715da
Linux nuc11 5.18.0-rc7 #1 SMP Mon May 16 13:55:03 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:ee3663fd468ec417ea0bba20b0d18f3448c8980c). Platform: Linux x86 64-bit
Kodi compiled 2022-05-16 by GCC 12.1.0 for Linux x86 64-bit version 5.18.0 (332288)
Running on LibreELEC (heitbaum): devel-20220518214014-a6715da 11.0, kernel: Linux x86 64-bit version 5.18.0-rc7
[    0.000000] DMI: Intel(R) Client …
```
> mesa: update to 22.1.0

- config/functions
note how the ouput below displays * as a device because it can’t expand. The proposed fix reports the the device directory is not there.
https://github.com/LibreELEC/LibreELEC.tv/blob/812b14eaf93fea4d5446980100371157ae6609c1/config/functions#L777-L779
```
docker@af7b5ccc9042:/var/media/DATA/home-rudi/LibreELEC.master$ mv projects/Generic/devices projects/Generic/devicesx
docker@af7b5ccc9042:/var/media/DATA/home-rudi/LibreELEC.master$ PROJECT=Generic ARCH=x86_64 DEVICE=x  make image
./scripts/image mkimage
=================================================================================
ERROR: Specify a valid device for the Generic project
=================================================================================
Valid devices for project: Generic
- *
*********** FAILED COMMAND …
```
> [le11] config/functions: improve error message when there in not a device directory

- distributions/LibreELEC/options
- packages/mediacenter/kodi/config/kodi.conf.in
- packages/mediacenter/kodi/package.mk
- packages/virtual/image/package.mk
This PR aims to improve separation between audio programs and kodi build options.
This creates the ability to build kodi with out `ALSA` support but to keep alsa included in the build. The same is true for pulseaudio. This will also be true for the pipewire PR I have for after this.
This doesn't change any default behaviour and just make the build system more flexible.
> Kodi: dynamically set KODI_AE_SINK env from build options

- distributions/LibreELEC/options
- packages/audio/ldacBT/package.mk
- packages/audio/libfreeaptx/package.mk
- packages/audio/libldac/package.mk
- packages/audio/pipewire/package.mk
- packages/audio/sbc/package.mk
- packages/audio/wireplumber/package.mk
- packages/devel/readline/package.mk
- packages/lang/lua54/config/lua54.pc
- packages/lang/lua54/package.mk
- packages/mediacenter/kodi/config/kodi.conf.in
- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/0001-CPlatformLinux-ifdef-alsa-support.patch
- packages/network/bluez/package.mk
- packages/sysutils/systemd/package.mk
- packages/virtual/image/package.mk
This PR adds pipewire support to LibreELEC and kodi (if enabled). It defaults to off as it isn't configured as a pulse alternative. I have a branch to change pulse to use pipewire but I'd rather get this in first and I can figure out pulseaudio later.
This has some commits that are part of #6501 and will need that to be merged first, then I'll rebase this PR. I wanted to PR it early while I had some spare time.
Currently Kodi is broken while building without ALSA so I added my patch that was submitted upstream https://github.com/xbmc/xbmc/pull/21415
Pipewire requires the bluez libbluetooth library. That could probably be conditional on `PIPEWIRE_SUPPORT` but I didn't bother for now.
I also added a couple fixes to `readline` and `sbc` to allow pipewire to build and link properly with …
> Add Pipewire Support

- packages/devel/libbpf/package.mk
- packages/devel/libbpf/patches/libbpf-fix-crosscompile-and-sysroot.patch
This fixes loading the raw bpf IR decoder which was broken with 0.6.1.
Note: #6510 is still needed to have working IR BPF decoders
Runtime tested on RPi4 with raw and pulse-distance IR BPF decoders
> libbpf: update to 0.8.0

- packages/lang/llvm/package.mk
- fix bug introduced in #6502 
Error occuring - due to RPATH/RUNPATH
```
./build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/llvm-config:
symbol lookup error:
./build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/../lib/libc.so.6:
undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```
Before fix
$ ldd
build.LibreELEC-gbm.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/llvm-config
linux-vdso.so.1 (0x00007ffc515d6000)
libLLVM-13.so => /home/lukas/git/libreelec/build.LibreELEC-gbm.x86_64-11.0-devel/toolchain/lib/libLLVM-13.so (0x00007fedc6fdb000)
libstdc++.so.6 => /home/lukas/git/libreelec/build.LibreELEC-gbm.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/b …
> llvm: fix build issue with llvm-config

- packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
Fix download hash
```
[1;36mGET[0m      pvr.sledovanitv.cz (archive)
--2022-05-24 12:58:48--  https://github.com/palinek/pvr.sledovanitv.cz/archive/4.5.1-Matrix.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/palinek/pvr.sledovanitv.cz/tar.gz/refs/tags/4.5.1-Matrix [following]
--2022-05-24 12:58:48--  https://codeload.github.com/palinek/pvr.sledovanitv.cz/tar.gz/refs/tags/4.5.1-Matrix
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified …
```
> [le10] pvr.sledovanitv.cz: update githash

- packages/tools/crust/package.mk
- packages/tools/u-boot/package.mk
- backport of #5953 using upstreamed patch
- backport of #5923 dfac76b2fb14e4e54525987de7e6ffc5a0d86c60
- `PROJECT=Allwinner ARCH=arm DEVICE=A64 make image`
crust build fails when cc link is missing (e.g. minimal Ubuntu 20.04)
use host-gcc from the toolchain instead.
addition of the patch fixes the following error.
BUILD      crust (target)
TOOLCHAIN      manual
...
HOSTCC  build/3rdparty/kconfig/conf.o
/bin/sh: 1: exec: cc: not found
make[1]: *** [Makefile:170: build/3rdparty/kconfig/conf.o] Error 127
...
required update the `package.mk` to override **BUILDCC**
Whilst tidying up my build environment (and moving to the focal docker build) - the `Makefile.host` is trying to use cc (as HOSTCC is not being past through.) update the package.mk to pass HOSTCC and other HOSTxxx variables …
> [le10] crust: allow override of BUILDCC and u-boot: fix make config with HOSTCC

- packages/lang/llvm/package.mk
- packages/lang/llvm/patches/llvm-14.0.0-force-disable-cmakelist-options.patch
llvm: update to 14.0.4
- use llvm-project not llvm, due to the packaging changes in v14
- Supersedes #6375
> llvm: update to 14.0.4

- config/show_config
```
=================================================================================
Configuration for LibreELEC (community)
=================================================================================
Buildsystem configuration:
======================================================
- CPU:					 x86-64
- Kernel Architecture:			 x86
- Userland Architecture:		 x86_64
- CPU features:			 64bit mmx sse sse2
- LTO (Link Time Optimization) support: yes
- GOLD (Google Linker) Support:	 yes
- LLVM support:			 yes
- DEBUG:				 no
- CFLAGS:				 -march=x86-64 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG
- LDFLAGS:				 -march=x86-64 -Wl,--as-needed -fuse-ld=gold
```
> [le11] config/show_config: ident cflags/ldflags

- packages/graphics/assimp/package.mk
- packages/graphics/vulkan/vkmark/package.mk
- packages/graphics/vulkan/vkmark/patches/vkmark-999.01-drop-dependency-on-vkCreateDmaBufImageINTEL.patch
- the `vkmark` package basically adds the same functionality for Vulkan as `glmark2` does for OpenGL / GLES
- since the RPi4 and Generic as well already could support Vulkan this benchmark is might be handy for tests
> [le11] add vkmark Vulkan benchmarking suite 

- packages/devel/automake/package.mk
fix race in parallel builds
```
Executing (host): make
cd /build/build.LibreELEC-Generic.x86_64-11.0-devel/build/automake-1.16.5 && "/build/build.LibreELEC-Generic.x86_64-11.0-devel/build/automake-1.16.5/.x86_64-linux-gnu/pre-inst-env" automake-1.16 --gnu --ignore-deps Makefile
/build/build.LibreELEC-Generic.x86_64-11.0-devel/build/automake-1.16.5/.x86_64-linux-gnu/pre-inst-env: 41: exec: automake-1.16: not found
make: *** [Makefile:2485: /build/build.LibreELEC-Generic.x86_64-11.0-devel/build/automake-1.16.5/Makefile.in] Error 127
FAILURE: scripts/build automake:host during make_host (default)
```
> automake: further fix race in parallel builds

- packages/sysutils/util-linux/package.mk
so that in :host hexdump is available in toolchain/bin
- back port of #6532
> [le10] util-linux: set all-programs option in init and target not common

- packages/security/openssl/package.mk
In the past, openssl didn't provide support for parallel building. However, with the 3.0 release this works well. Let's enable it.
This improves image build time since openssl:host is bottleneck, at least on my system.
> openssl: enable parallel build

- packages/multimedia/nvidia-vaapi-driver/package.mk
- packages/wayland/lib/fcft/package.mk
- packages/wayland/lib/seatd/package.mk
- packages/wayland/libinput/package.mk
- packages/wayland/libxkbcommon/package.mk
- packages/wayland/util/swaybg/package.mk
- packages/x11/app/setxkbmap/package.mk
- packages/x11/driver/xf86-input-libinput/package.mk
- packages/x11/driver/xf86-video-amdgpu/package.mk
- packages/x11/lib/libxcb/package.mk
- packages/x11/proto/xcb-proto/package.mk
- packages/x11/proto/xorgproto/package.mk
- fcft: update to 3.1.2
- libinput: update to 1.20.1
- libxcb: update to 1.15
- libxkbcommon: update to 1.4.1
- nvidia-vaapi-driver: update to 0.0.6
- seatd: update to 0.7.0
- setxkbmap: update to 1.3.3
- swaybg: update to 1.1.1
- xcb-proto: update to 1.15
- xf86-input-libinput: update to 1.2.1
- xf86-video-amdgpu: update to 22.0.0
- xorgproto: update to 2022.1
> X11 and Wayland updates

- packages/network/iptables/package.mk
- packages/network/iptables/patches/iptables-0001-xshared-fix-build-for--werror-format-security.patch
- packages/network/iptables/patches/iptables-0002-xshared-fix-for-build-in-sub-directory.patch
- packages/network/iw/package.mk
- packages/network/libmnl/package.mk
- packages/network/libnftnl/package.mk
- packages/network/libnl/package.mk
- packages/network/libtirpc/package.mk
- packages/network/nss-mdns/package.mk
- packages/network/wsdd2/package.mk
- iptables: update to 1.8.8
- iw: update to 5.19
- libmnl: update to 1.0.5
- libnftnl: update to 1.2.1
- libnl: update to 3.6.0
- libtirpc: update to 1.3.2
- nss-mdns: update to 0.15.1
- wsdd2: update to 1.8.7
> [le11] package/network updates

- packages/graphics/mesa/package.mk
Release notes: https://docs.mesa3d.org/relnotes/22.1.1.html
```
Generic.x86_64-devel-20220602091013-7710f0e
Linux nuc11 5.18.1 #1 SMP Wed Jun 1 23:09:17 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.701) Git:20.0a1-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-06-01 by GCC 12.1.0 for Linux x86 64-bit version 5.18.1 (332289)
Running on LibreELEC (heitbaum): devel-20220602091013-7710f0e 11.0, kernel: Linux x86 64-bit version 5.18.1
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021 …
```
> mesa: update to 22.1.1

- packages/addons/repository/repository.linuxserver.docker/changelog.txt
- packages/addons/repository/repository.linuxserver.docker/package.mk
update to activate:
- kodi: ls.io repository update to new style - 526945a9308
fixes
```
2022-06-04 13:37:46.174 T:80474   ERROR <general>: Repository add-on repository.linuxserver.docker uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2022-06-04 13:37:46.174 T:80474   ERROR <general>: Repository add-on repository.linuxserver.docker does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
```
> [le11] repository.linuxserver.docker: new style

- packages/addons/addon-depends/containerd/package.mk
- packages/addons/addon-depends/libnetwork/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
- containerd: update to 1.6.5
- libnetwork: update to 2022-03-16
- runc: update to 1.1.2
```
Client:
Version:           19.03.15
API version:       1.40
Go version:        go1.18.3
Git commit:        99e3ed89195c4e551e87aad1e7453b65456b03ad
Built:             Thu Jun  2 13:43:33 UTC 2022
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          19.03.15
API version:      1.40 (minimum version 1.12)
Go version:       go1.18.3
Git commit:       99e3ed89195c4e551e87aad1e7453b65456b03ad
Built:            Thu Jun  2 13:43:33 UTC 2022
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.6.4
GitCommit:        8686ededfc90076914c5238eb96c883ea093a8ba
runc:
Version:          1.1.2
GitCommit: …
```
> [le11] docker: update addon to (135)

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- https://github.com/KhronosGroup/Vulkan-Docs/commit/899dd1c16d5de69bd24e108f393d134fa2989512
Packages
- Vulkan updated to 1.3.216
- spirv-tools: update githash to 2022-06-01
- spirv-headers: update githash to 2022-05-26
- glslang: update to 11.10.0
> Vulkan package updates

- packages/network/openvpn/package.mk
https://openvpn.net/community-downloads/
The OpenVPN community project team is proud to release OpenVPN 2.5.7.
This is mostly a bugfix release, but adds limited support for OpenSSL
3.0. Full support will arrive in OpenVPN 2.6.
> openvpn: update to 2.5.7

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
changelog:
- https://github.com/kdave/btrfs-progs/blob/master/CHANGES
```
btrfs-progs-5.18 (2022-05-25)
-----------------------------
* fixes:
* dump-tree: don't print traling zeros in checksums
* recognize paused balance as exclusive operation state, allow to start
device add
* convert: properly initialize target filesystem label
* mkfs: don't create free space bitmaps for empty filesystem
* restore: make lzo support build-time configurable, print supported
compression in help text
* update kernel-lib sources
* other:
* documentation updates, finish conversion to RST, CHANGES and INSTALL
could be included into RST
* fix build detection of experimental mode
* new tests
```
> [le11] btrfs-progs: update to 5.18

- packages/network/wireless-regdb/package.mk
- wireless-regdb: update regulatory database based on preceding changes
- wireless-regdb: Unify 6 GHz rules for EU contries
- wireless-regdb: Remove AUTO-BW from 6 GHz rules
- wireless-regdb: update regulatory rules for Bulgaria (BG) on 6GHz
- Regulatory update for 6 GHz operation in FI
- Regulatory update for 6 GHz operation in United States (US)
- Regulatory update for 6 GHz operation in Canada (CA)
> [le11] wireless-regdb: update to 2022.06.06

- packages/addons/tools/btrfs-progs/changelog.txt
- packages/addons/tools/btrfs-progs/package.mk
[btrfs-progs-5.18.1 (2022-06-06)](https://btrfs.readthedocs.io/en/latest/CHANGES.html#btrfs-progs-5-18-1-2022-06-06)
Minors:
- fixes:
- convert: fix self reference of toplevel directory
- build: make kernel lib headers compatible with C++
- zoned mode: verify minimum zone size 4MiB
- libbtrfs: clean-ups, merge headers and remove declarations of unexported symbols
- other: documentation updates
> [le11] btrfs-progs: update to 5.18.1

- packages/audio/pulseaudio/package.mk
- https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/16.0/
```
nuc11:~ # pulseaudio --version
pulseaudio 16.0
=== build tested with ===
Generic.x86_64-devel-20220529091040-85eb4c7
Linux nuc11 5.18.0 #1 SMP Sun May 29 09:24:58 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.701) Git:20.0a1-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-05-29 by GCC 12.1.0 for Linux x86 64-bit version 5.18.0 (332288)
Running on LibreELEC (heitbaum): devel-20220529091040-85eb4c7 11.0, kernel: Linux x86 64-bit version 5.18.0
```
ref:
[1] https://www.systutorials.com/docs/linux/man/1-pulseaudio/
> pulseaudio isn't used by default and needs be tested as Bluetooth audio (main use case),
> and/or stop Kodi and pactl load-module module-udev-detect, then start Kodi …
> pulseaudio: update to 16.0

- projects/Allwinner/patches/linux/0019-media-cedrus-hevc-tiles-hack.patch
Allocation method for HEVC neighbor info buffer changed some time ago, but LE patch wasn't updated to reflect that. Fix it.
> [LE11] Allwinner: linux: fix HEVC patch

- packages/sysutils/systemd/package.mk
This enables use of cgroups v2 by default. I believe the only reason we needed the legacy version was because of docker. Docker needs to be at least 20.10 to use cgroups v2. The PR is in at #6577 
ref:
https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.10-systemd-cgroup
https://wiki.archlinux.org/title/cgroups
https://systemd.io/CGROUP_DELEGATION/
https://docs.docker.com/engine/release-notes/#20100
> systemd: use unified cgroups

- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
Minor security update: 
- containerd: update to 1.6.6
- https://github.com/containerd/containerd/releases/tag/v1.6.6
- The sixth patch release for containerd 1.6 includes a fix for
[CVE-2022-31030](https://github.com/containerd/containerd/security/advisories/GHSA-5ffw-gxpp-mxpf).
- runc: update 1.1.3
> [le11] docker: update addon to (137)

- packages/graphics/nvidia/package.mk
- packages/wayland/lib/seatd/system.d/seatd.service
- fix seatd startup
- update nvidia to 515.48.07 - finally Kodi doesn't run at / is limited to ~40fps while the screen is set to 60Hz
> [le11] Wayland updates & fixes

- packages/security/nettle/package.mk
news:
- https://git.lysator.liu.se/nettle/nettle/-/commit/a2be57f0502bae7869956c83d1ba620bfab051b3
of note - for aarch64:
New ARM64 implementation of AES, GCM, Chacha, SHA1 and
SHA256, for processors supporting crypto extensions. Great
speedups, and fat builds are supported. Contributed by
Mamone Tarsha.
> nettle: update to 3.8 and HTTPS

- packages/devel/libfmt/package.mk
Kodi has been updated to support 8.1.1
- https://github.com/fmtlib/fmt/releases/tag/8.1.0
- https://github.com/fmtlib/fmt/releases/tag/8.1.1
> libfmt: update to 8.1.1

- packages/devel/binutils-aarch64/package.mk
- packages/devel/binutils-bpf/package.mk
- packages/devel/binutils-or1k/package.mk
- binutils-or1k: do not build documentation
- binutils-bpf: do not build documentation
- binutils-aarch64: do not build documentation
Fixes
- Fixes introduced error in #6361
building of the following now work.
- binutils-aarch64:host
- binutils-bpf:host
- binutils-or1k:host
> binutils-yyy: do not build documentation

- packages/network/rsync/patches/rsync-schar-fix-3.2.4.patch
See:
- https://lists.samba.org/archive/rsync-announce/2022/000111.html
- https://github.com/WayneD/rsync/commit/4f741addbd5fd59de2c2655e5a044d6c2fe44aa5
- https://github.com/WayneD/rsync/issues/317
> rsync: fix potentially wrong rolling checksum values on ARM

- packages/linux/package.mk
RPi firmware since around September 2020 is able to decompress gzipped kernels prior to handing over control. Arm64 kernels do not do self-decompression, so use the firmware's capability.
I don't know exactly which firmware release allows this as the release notes are rather concise. I found this mentioned in this comment: https://github.com/raspberrypi/firmware/issues/1467#issuecomment-693327677
Reduces my .tar by ~11MB on RPi3.
> linux: gzip 64bit kernels on RPi

- .github/FUNDING.yml
This adds an OC sponsorship link to our main repo.
> github: add opencollective sponsorship link

- packages/security/openssl/package.mk
- packages/security/openssl/patches/openssl-3-0-4-0001-fix-compile-issues-in-test-v3ext-c-with-no-rfc3779.patch
upstream patches for build:
- https://github.com/openssl/openssl/issues/18619
- https://github.com/openssl/openssl/pull/18188
- https://github.com/openssl/openssl/pull/18634 <—— this is included in the PR.
https://www.openssl.org/news/changelog.html
In addition to the c_rehash shell command injection identified in CVE-2022-1292, further bugs where the c_rehash script does not properly sanitise shell metacharacters to prevent command injection have been fixed.
When the CVE-2022-1292 was fixed it was not discovered that there are other places in the script where the file names of certificates being hashed were possibly passed to a command executed through the shell.
This script is distributed by some operating systems in a manner where it is automatically executed. On such operating …
> openssl: update to 3.0.4

- packages/audio/flac/package.mk
(missed this one in the audio update bunch)
https://xiph.org/flac/changelog.html
FLAC 1.3.4 (20-Feb-2022)
This release mostly fixes (security related) bugs. When building with MSVC, using CMake is preferred, see the README under "Building with CMake" for more information. Building with MSVC using solution files is deprecated and these files will be removed in the future.
- General:
- Fix 12 decoder bugs found by oss-fuzz, including CVE-2020-0499 (erikd, Martijn van Beurden)
- Fix encoder bug CVE-2021-0561 (NeelkamalSemwal)
- Integrate oss-fuzzers (erikd, Guido Vranken)
- Seeking fixes (NeelkamalSemwal, Robert Kausch)
- Various fixes and improvements (Andrei Astafev, Rosen Penev, Håkan Kvist, oreo639, erikd, Tamás Zahola, Ulrik Mikaelsson, Tyler Dunn, tmkk)
- FLAC format:
- (none)
- Ogg …
> flac: update to 1.3.4 and HSTS

- packages/addons/addon-depends/containerd/package.mk
- packages/addons/addon-depends/libnetwork/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
- backport of #6563 and #6582
Packages updates:
- containerd: update to 1.6.6
- libnetwork: update to 2022-03-16
- runc: update to 1.1.3
> [le10] docker: update addon to (134)

- projects/Allwinner/linux/linux.arm.conf
It seems that spidev is useful to users. Enable it for arm kernel. It's already enabled for arm64.
> [LE11] Allwinner: linux: arm: Enable spidev

- packages/linux-drivers/bcm_sta/patches/bcm_sta-0600-kernel-5.17-fix.patch
- packages/network/connman/package.mk
This PR relate to issues seen in https://forum.libreelec.tv/thread/25714-adding-boot-parameters-to-the-rpi-and-any-arm-build-probably/
Starting with kernel 5.17 netdev->dev_addr is const and must be changed through a helper function. Update the patch using a solution around.
Warning in the log http://ix.io/40Bd:
```
Jun 21 19:02:32 nightly kernel: wl 0000:04:00.0 wlan0: Current addr:  00 25 56 b6 4e 4a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 21 19:02:32 nightly kernel: wl 0000:04:00.0 wlan0: Expected addr: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 21 19:02:32 nightly kernel: ------------[ cut here ]------------
Jun 21 19:02:32 nightly kernel: netdevice: wlan0: Incorrect netdev->dev_addr
Jun …
```
> [network] bcm_sta: improve kernel 5.17 patch / connman: 4388028 (1.41+/2022-05-25)

- packages/debug/gdb/patches/0001-gdbserver-ctrl-c-handling.patch
See: https://sourceware.org/bugzilla/show_bug.cgi?id=18772
Signed-off-by: Dom Cobley <popcornmix@gmail.com>
> gdb: Fix ctrl-c handling with gdbserver

- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/graphics/kmsxx/package.mk
Especially kmsprint is very handy.
Note: kmsxx isn't included in images by default ATM, you have to add it to ADDITIONAL_PACKAGES. I'm wondering though if we should include it as it's rather small and kmsprint output is so much more readable than modetest output
> kmsxx: add new package providing KMS utilities

- packages/addons/addon-depends/system-tools-depends/depends/efivar/package.mk
This reverts commit 3b70bb1c285e795dd50f59213e10d7bbe0ca2b44.
Revert efivar package to 10 Dec 2021
- as last known good working dependant version of efibootmgr
- efibootmgr 17 (08 Sep 2021)
Fix build of system-tools addon on x86_64
> Revert "efivar: update to 38"

- packages/multimedia/gmmlib/package.mk
Log:
- https://github.com/intel/gmmlib/compare/intel-gmmlib-22.1.3...intel-gmmlib-22.1.4
With the change in the gmmlib Cmakefiles
- https://github.com/intel/gmmlib/commit/19963011a40afd62c2a90e54d750fc3c60482ab7
- It was necessary to set the **CMAKE_BUILD_TYPE** to **Release**
- #6422
- would make it unnecessary set `-DCMAKE_BUILD_TYPE=Release`
```
CMake Error at Tools/bldsys/include/bs_base_utils.cmake:48 (message):
Build Type: MinSizeRel is undefined, Please enter correct value - exiting!
Call Stack (most recent call first):
Tools/bldsys/include/bs_base_utils.cmake:67 (bs_compare_build_type)
Tools/bldsys/bs_init.cmake:33 (bs_check_build_type)
Source/GmmLib/CMakeLists.txt:114 (include)
```
> gmmlib: update to 22.1.4

- packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/docs/relnotes/22.1.3.rst
```
Generic.x86_64-devel-20220630120226-d9e6cd3
Linux nuc11 5.18.8 #1 SMP Thu Jun 30 12:05:27 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.701) Git:20.0a1-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-06-30 by GCC 12.1.0 for Linux x86 64-bit version 5.18.8 (332296)
Running on LibreELEC (heitbaum): devel-20220630120226-d9e6cd3 11.0, kernel: Linux x86 64-bit version 5.18.8
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021
CApplication::CreateGUI - trying to init gbm …
```
> mesa: update to 22.1.3

- packages/databases/sqlite/package.mk
- packages/devel/binutils-aarch64/package.mk
- packages/devel/binutils-bpf/package.mk
- packages/devel/binutils-or1k/package.mk
- packages/devel/binutils/package.mk
- packages/devel/flatbuffers/package.mk
- packages/sysutils/kmod/package.mk
- packages/textproc/nlohmann-json/package.mk
- packages/web/nghttp2/package.mk
Documentation changes only
- binutils-aarch64: add comments on MAKEINFO usage
- binutils-bpf: add comments on MAKEINFO usag
- binutils-or1k: add comments on MAKEINFO usage
- binutils: add comments on MAKEINFO usage
Toolchain
- nlohmann-json: build using meson
Package updates
- kmod: update to 30
- flatbuffers: update to 2.0.6
- sqlite: update to 3.39.0
- nghttp2: update to 1.48.0
> Miscellaneous package updates

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/addons/tools/ffmpeg-tools/package.mk
Update the packages for both of these to handle the shared library and the potentially unneeded libxcb
- [ffmpegx: disable libxcb for non X11 builds](https://github.com/LibreELEC/LibreELEC.tv/commit/6f6a534ef51b34c0cd1eb9762de5c71f823c3ac4)
- [tools.ffmpeg-tools: fix missing libraries and addon (118)](https://github.com/LibreELEC/LibreELEC.tv/commit/d2c70cc46128cfd4511090dd876de4c15f95a866)
Fix for: https://forum.libreelec.tv/thread/25834-ffmpeg-tools-addon-is-it-broken/
Run tested on LE10 x86_64 and build tested for ARMv8
- Backport of #6406
WAS:
```
nuc6:~ # ffmpeg
ffmpeg: error while loading shared libraries: libx265.so.199: cannot open shared object file: No such file or directory
```
IS:
```
nuc6:~ # ffmpeg
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with …
```
> [le10] tools.ffmpeg-tools: fix missing libraries and addon (118)

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Update rust packages
- Tested alongside #6660 and #6667
- cargo-snapshot: update to 1.62.0
- rust-std-snapshot: update to 1.62.0
- rustc-snapshot: update to 1.62.0
- rust: update to 1.62.0
- Announcement:
- https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html
> rust: update to 1.62.0

- packages/audio/pipewire/package.mk
- packages/audio/wireplumber/package.mk
- pipewire: update to 0.3.54
- https://github.com/PipeWire/pipewire/blob/master/NEWS
- wireplumber: update to 0.4.11
- https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/master/NEWS.rst
> pipewire updates

- packages/linux-firmware/kernel-firmware/firmwares/any.dat
Add rtw88 firmware to image for both pci devices and future USB/SDIO devices.
kernel modules are already in place.
```
[    5.061961] rtw_8822be 0000:03:00.0: enabling device (0100 -> 0103)                                                                       
[    5.062027] rtw_8822be 0000:03:00.0: Direct firmware load for rtw88/rtw8822b_fw.bin failed with error -2                                  
[    5.062033] rtw_8822be 0000:03:00.0: failed to request firmware                                                                          
[    5.068176] rtw_8822be 0000:03:00.0: failed to load firmware                                                                              
[    5.068186] rtw_8822be 0000:03:00.0: failed to setup chip efuse info …
```
> kernel-firmware: add rtw88/* to image

- config/arch.x86_64
- projects/Generic/options
- first things first: this should not change the current build behaviour/result
- set default `TARGET_CPU` to `x86-64` instead `core2` if none was specified
- [GCC 11 introduced x86-64 microarchitecture feature levels](https://www.phoronix.com/scan.php?page=news_item&px=GCC-11-x86-64-Feature-Levels) so we can depend on them
- Generic is always 64bit nowadays so git rid of additional 64bit userland opts & add it  to `TARGET_FEATURES`
- clean up the "SIMD support" leftovers after https://github.com/LibreELEC/LibreELEC.tv/pull/2577
- replace them with the actual target cpu feature set defined by [GCC](https://github.com/gcc-mirror/gcc/blob/releases/gcc-11.2.0/gcc/config/i386/i386.h#L2520-L2521)
- If necessary it also allows to fine tune packages for target features like …
> [le11] config/arch.x86_64: updated TARGET_CPU & TARGET_FEATURES

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-001-pr21673-drmprime-fix-dvd-menu.patch
- projects/RPi/patches/kodi/kodi-001-deinterlace.patch
This PR includes https://github.com/xbmc/xbmc/pull/21673 which can be dropped when it's merged in kodi.
Quick runtime test on RPi4 looks good, DVD menus and deinterlace are working fine
> [le10] kodi: update to latest Matrix and include DVD menu fix PR

- packages/linux/package.mk
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.6
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.7
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.8
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.9
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.10
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.11
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.18.12
5.18.6 - 141 patches
5.18.7 - 11 patches
5.18.8 - 181 patches
5.18.9 - 6 patches
5.18.10 - 102 patches
5.18.11 - 112 patches
5.18.12 - 1 patches
- ~https://comsec.ethz.ch/research/microarch/retbleed/~
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-5.18.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.gi …
> linux: update to 5.18.y

- packages/graphics/mesa/package.mk
rel notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/docs/relnotes/22.1.4.rst
```
Generic.x86_64-devel-20220715234007-c6729f9
Linux nuc11 5.18.12 #1 SMP Fri Jul 15 23:37:57 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:20.0a2-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-07-14 by GCC 12.1.0 for Linux x86 64-bit version 5.18.11 (332299)
Running on LibreELEC (heitbaum): devel-20220715234007-c6729f9 11.0, kernel: Linux x86 64-bit version 5.18.12
CApplication::CreateGUI - trying to init gbm …
```
> mesa: update to 22.1.4

- packages/web/curl/package.mk
- https://curl.se/changes.html#7_84_0
Fixed in 7.84.0 - June 27 2022
**Changes:**
[curl: add --rate to set max request rate per time unit](https://curl.se/bug/?i=8671)
[curl: deprecate --random-file and --egd-file](https://curl.se/bug/?i=8670)
[curl_version_info: add CURL_VERSION_THREADSAFE](https://curl.se/bug/?i=8680)
[CURLINFO_CAPATH/CAINFO: get the default CA paths from libcurl](https://curl.se/bug/?i=8888)
[lib: make curl_global_init() threadsafe when possible](https://curl.se/bug/?i=8680)
[libssh2: add CURLOPT_SSH_HOSTKEYFUNCTION](https://curl.se/bug/?i=7959)
[opts: deprecate RANDOM_FILE and EGDSOCKET](https://curl.se/bug/?i=8670)
[socks: support unix sockets for socks proxy](https://curl.se/bug/?i=8668)
**Bugfixes:**
[aws-sigv4: fix potentional NULL pointer …
> curl: update to 7.84.0

- packages/web/curl/patches/0001-easy_lock.h-include-sched.h-if-available-to-fix-buil.patch
Building curl currently fails for arm32 userspace and needs to be patched: See https://github.com/curl/curl/issues/9159
> curl: add patch to fix build for 7.84.0

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
[media-driver: update to 22.5.0](https://github.com/LibreELEC/LibreELEC.tv/commit/f7fda61824efbac64d96e17bea960bbc9d46bad4)
- https://github.com/intel/media-driver/compare/intel-media-22.4.4...intel-media-22.5.0
[gmmlib: update to 22.1.6](https://github.com/LibreELEC/LibreELEC.tv/commit/6ec0bfbc9292e508eb01561dfc27f21399bc4288)
- minor
- https://github.com/intel/gmmlib/compare/intel-gmmlib-22.1.5...intel-gmmlib-22.1.6
```
Generic.x86_64-devel-20220717053735-0ed554b
Linux nuc11 5.19.0-rc6 #1 SMP Sat Jul 16 11:10:01 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:20.0a2-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-07-14 by GCC 12.1.0 for Linux x86 64-bit version 5.18.11 (332299)
Running on LibreELEC (heitbaum): …
```
> Intel updates

- config/functions
- scripts/clean
- scripts/image
- scripts/install
This adds support for logging QA checks via a new `log_qa_check` function. This function takes a title (of the check) and a message that explains the issues and possibly how to solve it.
This is needed so we can catch some simple problems that seems to keep making their way into master.
This changes `safe_remove` to be a qa check and logs anything that `safe_remove` flags.
The QA checks are logged in `${BUILD}/qa_checks/${PKG_NAME}-${PKG_VERSION}/`
These checks are then printed at the end of a build.
I plan to add more qa checks in the future that are related to kernel configs and rpaths and some other things. This PR just lays the base of this expansion.
I would be in favour of killing the build when encountering a QA issue but it's not possible until all the QA issues are solved.
For …
> Add support for logging and reporting QA Checks

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/drmprime-filter/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0002-WIP-DRMPRIME-deinterlace-filter.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0003-DVDVideoCodecDRMPRIME-Avoid-exception-with-AV_PIX_FM.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0004-DVDVideoCodecDRMPRIME-Leave-deinterlace-filter-activ.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0005-SetVideoInterlaced-Set-and-unset-deinterlace-method-.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0006-DVDVideoCodecDRMPRIME-Close-deinterlace-filter-on-er.patch
- projects/RPi/patches/kodi/kodi-001-deinterlace.patch
The filter/deinterlaced patches were rebased by @popcornmix 
Runtime test on RPi4 was fine, DVD menus and deinterlacing still works.
@knaerzche @jernejsk please test on AW/RK
> [le11] update to latest kodi master with DRMPRIME DVD fix

- packages/devel/libfmt/package.mk
changelog:
- https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst
supported since:
- #6717 
- https://github.com/xbmc/xbmc/pull/21649
> libfmt: update to 9.0.0

- packages/network/rsync/package.mk
This pares down rsync:host as it's only used for file copying while building linux.
For rsync:host,
disable-md2man disables manpage creation
disable-ipv6 disables ipv6 support
disable-iconv disables the --iconv option, which does character conversion
reorders options to match how they appear in configure output
For rsync:target, some options were renamed in 3.2.4's release.
> rsync: cleanup options

- packages/graphics/assimp/package.mk
- packages/graphics/glmark2/patches/glmark2-999.01-fix-gcc12.1-build.patch
- packages/lang/gcc/package.mk
- packages/lang/gcc/patches/gcc-crosscompile-badness.patch
- packages/tools/atf/package.mk
changes:
- https://gcc.gnu.org/gcc-12/changes.html
- https://gcc.gnu.org
~requires #6469 as a precursor~ - DONE
it is presented as draft so others can test as required.
build of all of:- successful (with the above patches and gcc-12.1.0)
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
PROJECT=NXP ARCH=arm DEVICE=iMX8 make image 
^^^^^ FAILs - see atf workaround below.
PROJECT=Qualcomm ARCH=arm …
```
> gcc: update to 12.1.0

- projects/Allwinner/patches/kodi/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- projects/Allwinner/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
- projects/Rockchip/patches/kodi/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- projects/Rockchip/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
Completely untested except unpacking kodi sources+patches so it should at least fix the CI build error.
I replaced the deinterlace patches with the versions we use on RPi and I added back the LOGERROR->LOGDEBUG change for RK.
@jernejsk @knaerzche please give this a try and report back if it works fine.
> [le10] Update kodi deinterlace patches for Allwinner and Rockchip

- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/atk/package.mk
- packages/addons/addon-depends/chrome-depends/cups/package.mk
- packages/addons/addon-depends/chrome-depends/gdk-pixbuf/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/chrome-depends/json-glib/package.mk
- packages/addons/addon-depends/chrome-depends/libXcursor/package.mk
- packages/addons/addon-depends/chrome-depends/pango/package.mk
- packages/addons/addon-depends/icu/package.mk
- packages/addons/addon-depends/jasper/package.mk
- packages/addons/browser/chrome/changelog.txt
- packages/addons/browser/chrome/package.mk
- packages/graphics/harfbuzz/package.mk
Build in LE11 must be done with `PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/create_addon chrome`
- this fixes the `gdk-pixbuf` introduced regression
- 0cf76756960b6d58a8e24db483792751e9d7daae
- #6128
- **chrome** addon wants to install the `/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders`
- at-spi2-core: update to 2.45.1
- atk: update to 2.38.0
- chrome: update to 103.0.5060.134
- cups: update to 2.4.2
- gdk-pixbuf: update to 2.42.8
- gtk3: update to 3.24.34
- icu: update to 71.1
- libXcursor: update to 1.2.1
- jasper: update to 3.0.6
- pango: update to 1.50.8
- json-glib: build depends on glib-mkenums from glib:host
https://chromestatus.com/roadmap
> [le11] chrome: update to 103.0.5060.134 and addon (113)

- packages/network/samba/package.mk
ann:
- https://lists.samba.org/archive/samba/2022-July/241442.html
release notes:
- https://www.samba.org/samba/history/samba-4.16.4.html
> samba: update to 4.16.4

- projects/Generic/linux/linux.x86_64.conf
required in order to be able to detect passthrough scsi devices such as hdds or cdrom in the vm which run Libreelec
Signed-off-by: Dagg Stompler <daggs@gmx.com>
> generic: enable scsi virtio support

- packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Sync with RPi-Distro repo
- Updated 43436P firmware for Zero 2 W
The shipping firmware for the SYN43436P does not support 4-way
handshake offloading. This new firmware (version string
"Version: 9.88.4.77 CRC: 143f9f15 Date: Thu 2022-03-31 17:25:16 CST
Ucode Ver: 1043.20743 FWID: 01-3b307371") fixes that.
- Updated SYN43436S firmware
The embedded clm_blob in the previous SYN43436S firmware did not offer
any channels when the country code was set to KR (Korea). This firmware
fixes that.
- Braktooth fix for CYW43455
This updated Bluetooth firmware contains Braktooth fixes for
CYW43455, addressing the following vulnerabilities:
https://github.com/advisories/GHSA-7j4h-6cq9-gmjv https://github.com/advisories/GHSA-jg54-6p86-rp5q https://github.com/advisories/GHSA-m739-9w4c-mx4g …
> brcmfmac_sdio-firmware-rpi: update to b4fa915

- packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
Patch created using revisions 081225c..ab65af8
from branch v4l2-request-hwaccel-4.4 of https://github.com/jernejsk/FFmpeg
It's required for both hantro G1 (RK SoCs) and G2 (AW) to work correctly with https://github.com/LibreELEC/LibreELEC.tv/pull/6658
> ffmpeg: update v4l2-request patch

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Vulkan update to 1.3.223
- https://github.com/KhronosGroup/Vulkan-Docs/commit/9ecfc67442754c9e4c4fecf5e61c48483608a074
- vulkan-headers: update to 1.3.223
- vulkan-loader: update to 1.3.223
- vulkan-tools: update to 1.3.223
> Vulkan update to 1.3.223

- packages/graphics/mesa/package.mk
Release Notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/docs/relnotes/22.1.5.rst
```
Generic.x86_64-devel-20220804123859-9c53e09
Linux nuc11 5.19.0 #1 SMP Thu Aug 4 12:39:09 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:80f18db9500c0738d3522f4efdf789aa012e9930). Platform: Linux x86 64-bit
Kodi compiled 2022-08-01 by GCC 12.1.1 for Linux x86 64-bit version 5.19.0 (332544)
Running on LibreELEC (heitbaum): devel-20220804123859-9c53e09 11.0, kernel: Linux x86 64-bit version 5.19.0 …
```
> mesa: update to 22.1.5

- packages/databases/sqlite/package.mk
- https://www.sqlite.org/releaselog/3_39_2.html
- Add (long overdue) support for [RIGHT and FULL OUTER JOIN](https://www.sqlite.org/lang_select.html#rjoin).
- Add new binary comparison operators [IS NOT DISTINCT FROM](https://www.sqlite.org/lang_expr.html#isdf) and [IS DISTINCT FROM](https://www.sqlite.org/lang_expr.html#isdf) that are equivalent to IS and IS NOT, respective, for compatibility with PostgreSQL and SQL standards.
- Add a new return code (value "3") from the [sqlite3_vtab_distinct()](https://www.sqlite.org/c3ref/vtab_distinct.html) interface that indicates a query that has both DISTINCT and ORDER BY clauses.
- Added the [sqlite3_db_name()](https://www.sqlite.org/c3ref/db_name.html) interface.
- The unix os interface resolves all symbolic links in database filenames to create …
> sqlite: update to 3.39.2

- packages/addons/tools/btrfs-progs/patches/btrfs-progs-01-compile-with-glibc-2.36.patch
> btrfs-progs: enable compile with glibc 2.36

- packages/multimedia/bento4/package.mk
inputstream.adaptive is switching bento4 to the kodi fork, next release will use that and have all patches removed - see https://github.com/xbmc/inputstream.adaptive/pull/1017
This is not an immediate issue now but will become one at the next i.a update.
Only build tested for now
> bento4: switch to xbmc fork

- packages/devel/binutils/package.mk
- packages/devel/binutils/patches/binutils-02-binutils-2-39-dont-error-on-missing-makeinfo.patch
- packages/linux/patches/default/linux-100-kernel-5-19-io-series-664369.patch
- packages/linux/patches/raspberrypi/linux-100-kernel-5-19-io-series-664369.patch
- projects/Amlogic/devices/AMLGX/patches/linux/linux-100-kernel-5-19-io-series-664369.patch
Update `binutils` to 2.39
- release notes:
- https://sourceware.org/pipermail/binutils/2022-August/122246.html
- details of the patch for kernel patch to support build with `binutils` 
- https://lore.kernel.org/bpf/20220801013834.156015-2-andres@anarazel.de/
- The patches for `Amlogic` and [default](url) are the same
- The back ported patch for `RPi` has a minor change to the aforementioned patch to `tools/bpf/bpftool/Makefile`
> binutils: update to 2.39

- packages/linux-firmware/intel-ucode/package.mk
Release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220809
> intel-ucode: update to 20220809

- packages/tools/atf/package.mk
- packages/tools/crust/patches/fix-binutils-2-39.patch
Fix build error with binutils-2.39 and atf.
set LDFLAGS="--no-warn-rwx-segments" for build of bl31.elf on iMX8, A64,
H5 and H6 socs. As the link fails with a non-zero exit code (because
of --fatal-warnings).
relevant commit:
- https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ba951afb99912da01a6e8434126b8fac7aa75107
The ELF linker will now generate a warning message if the stack is made
executable.  Similarly it will warn if the output binary contains a
segment with all three of the read, write and execute permission
bits set.  These warnings are intended to help developers identify
programs which might be vulnerable to attack via these executable
memory regions.  The warnings are enabled by default but can be
disabled via a command line option.
compile error:
LD …
> atf and crust: support build with binutils 2.39

- packages/graphics/mesa/patches/mesa-0001-22-1-5-Revert-pan-bi-Require-ATEST-coverage-mask-input-in-R60.patch
Revert "pan/bi: Require ATEST coverage mask input in R60"
This reverts commit [7ead2568](https://gitlab.freedesktop.org/mesa/mesa/-/commit/7ead256891cec7a301d2fd415405a7f9106b1f46).
See [7025](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7025) for the
details, but the short version is that this was causing a segfault.
> mesa: Revert "pan/bi: Require ATEST coverage mask input in R60"

- packages/sysutils/tz/package.mk
> [le10] tz: update to 2022b

- packages/multimedia/media-driver/package.mk
Log:
- https://github.com/intel/media-driver/compare/intel-media-22.5.1...intel-media-22.5.2
```
Generic.x86_64-devel-20220811100323-9998288
Linux nuc11 5.19.1-rc1 #1 SMP Wed Aug 10 13:46:15 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:80f18db9500c0738d3522f4efdf789aa012e9930). Platform: Linux x86 64-bit
Kodi compiled 2022-08-08 by GCC 12.1.1 for Linux x86 64-bit version 5.19.0 (332544)
Running on LibreELEC (heitbaum): devel-20220811100323-9998288 11.0, kernel: Linux x86 64-bit version 5.19.1-rc1 …
```
> Intel media-driver: update to 22.5.2

- packages/graphics/mesa/package.mk
Upstream patch included and 4 other patches.
Log:
- https://gitlab.freedesktop.org/mesa/mesa/-/commits/22.1/
ann:
- https://lists.freedesktop.org/archives/mesa-announce/2022-August/000683.html
```
Generic.x86_64-devel-20220811100323-9998288
Linux nuc11 5.19.1-rc1 #1 SMP Wed Aug 10 13:46:15 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:80f18db9500c0738d3522f4efdf789aa012e9930). Platform: Linux x86 64-bit
Kodi compiled 2022-08-08 by GCC 12.1.1 for Linux x86 64-bit version 5.19.0 (332544)
Running on LibreELEC (heitbaum): devel-20220811100323-9998288 11.0, kernel: Linux x86 64-bit version 5.19.1-rc1
[    0.000000] DMI: …
```
> mesa: update to 22.1.6

- packages/network/wireless-regdb/package.mk
log:
wireless-regdb: update regulatory database based on preceding changes
wireless-regdb: update 5 GHz rules for PK and add 60 GHz rule
wireless-regdb: add 5 GHz rules for GY
> [le11] wireless-regdb: update to 2022.08.12

- packages/network/wireless-regdb/package.mk
- back port of #6794 
log:
wireless-regdb: update regulatory database based on preceding changes
wireless-regdb: update 5 GHz rules for PK and add 60 GHz rule
wireless-regdb: add 5 GHz rules for GY
> [le10] wireless-regdb: update to 2022.08.12

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Announcement: https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html
> rust: update to 1.63.0

- scripts/image
When no QA issues are present, an error message is output about not being able to `ls` a non-existent directory. This happens because the `[` test operator doesn't short-circuit, so it continues to evaluate the test, even though the first part was false.
This changes it to just route the error message to /dev/null. The alternative would be to use the `[[` operator, which I'm open to, but generally isn't used by the project.
Ref: #6666
> scripts: suppress qa_check error message when no issues present

- packages/devel/pcre2/package.mk
- Fixes #6782 build on aarch64 of pcre2
@pretoriano80 please check this works for you too.
> pcre2: fix build on aarch64 without ncurses

- packages/graphics/libdrm/package.mk
This hopefully fixes the _incredible important_ QA issues & removes a _blocker_ for a proper future release by conditionally removing `amdgpu_stress` which is only build if radeonsi flag is set. Otherwise e.g. ARM builds yield a QA issue message like:
```
<<< libdrm:target seq 208 <<<
INSTALL      libdrm (target)
[QA CHECK] [libdrm] [safe_remove]:
path does not exist: /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/install_pkg/libdrm-2.4.112/usr/bin/amdgpu_stress
>>> libdrm:target seq 208 >>>
[208/441] [DONE] install libdrm:target
```
I'm not sure though if other projects yield different errors, I've tested Generic, RK3399, AMLGX and looks like they're fine.
> [le11] libdrm: fix QA issues by conditionally removing test programs

- packages/compress/xz/package.mk
5.2.6 released on 2022-08-12. This includes a security fix to xzgrep
(CVE-2022-1271, ZDI-CAN-16587) for which a standalone patch was already
released on 2022-04-07.
news: https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;hb=HEAD
> xz: update to 5.2.6 and https and PKG_URL

- packages/addons/skin/estouchy/package.mk
Build estouchy standalone rather that kodi builds it and we copy it from the kodi build dir.
- Kodi is now not required to build estouchy addon
- use TexturePacker to create texture.xbt
Allows #6425 to drop additional deps.
Could not check yet with a full build LE but should work there too.
> estouchy: build standalone

- packages/emulation/libretro-vecx/package.mk
- packages/graphics/glm/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
- packages/mediacenter/kodi-platform/package.mk
- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-999.20-headers-only.patch
This PR intends to avoid full Kodi build with all dependencies just to build one simple addon. With these changes, this works pretty well. Amount of packages for pvr.iptvsimple went down from 173 to 51. However, if all addons are built, this effect is greatly diminished. Building them for Allwinner H6, there are only 2 packages less to build (638 -> 636). This is because Estouchy skin requires Kodi to be build. If it is disabled, amount of packages goes down from 636 to 601.
Downside of this PR is that many addons don't list all dependencies, because they were already build for Kodi. This is the reason why this is WIP. Currently problematic addons:
audiodecoder.2sf
btrfs-progs
audiodecoder.fluidsynth
game.libretro.vecx
hyperion
pvr.vdr.vnsi
syncthing
screensaver.asteroids …
> [LE11] Decouple addons build

- packages/multimedia/media-driver/package.mk
Log
- https://github.com/intel/media-driver/compare/intel-media-22.5.2...intel-media-22.5.3
```
Generic.x86_64-devel-20220825124014-db5ffb3
Linux nuc11 5.19.4 #1 SMP Thu Aug 25 12:44:07 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:80f18db9500c0738d3522f4efdf789aa012e9930). Platform: Linux x86 64-bit
Kodi compiled 2022-08-23 by GCC 12.2.0 for Linux x86 64-bit version 5.19.4 (332548)
Running on LibreELEC (heitbaum): devel-20220825124014-db5ffb3 11.0, kernel: Linux x86 64-bit version 5.19.4 …
```
> media-driver: update to 23.5.3

- packages/linux-drivers/RTL8192DU/package.mk
- packages/linux-drivers/RTL8812AU/package.mk
- packages/linux-drivers/bcm_sta/patches/bcm_sta-0600-kernel-6.0-fix.patch
- packages/network/ethtool/package.mk
- ethtool: update to 5.19
- LOG: https://git.kernel.org/pub/scm/network/ethtool/ethtool.git
- bcm_sta: patch to compile with Linux 6.0
- RTL8812AU: update to githash 20220827
- also supports kernels 5.19.2 and 6.0 
- RTL8192DU: update to githash 20220819
- also supports kernels 5.19.2 and 6.0
> Ethtool and Wireless Driver updates

- packages/audio/libopenmpt/package.mk
- packages/graphics/libglvnd/package.mk
- packages/network/libssh/package.mk
- packages/textproc/libxml2/package.mk
- packages/textproc/libxslt/package.mk
- libglvnd: update to 1.5.0
- https://github.com/NVIDIA/libglvnd/compare/v1.4.0...v1.5.0
- libxml2: update to 2.10.2
- https://gitlab.gnome.org/GNOME/libxml2/-/releases
- libxslt: update to 1.1.37
- https://gitlab.gnome.org/GNOME/libxslt/-/blob/master/NEWS
- libopenmpt: update to 0.6.5
- https://lib.openmpt.org/libopenmpt/2022/08/21/releases-0.6.5-0.5.19-0.4.31-0.3.39/
- libssh: update to 0.10.0 and dont build examples
- https://git.libssh.org/projects/libssh.git/tag/?h=libssh-0.10.0
> Library updates

- packages/graphics/lcms2/package.mk
- packages/textproc/jsoncpp/package.mk
- packages/web/nghttp2/package.mk
- [lcms2: migrate to meson build](https://github.com/LibreELEC/LibreELEC.tv/commit/a260370bbf2b650fd764b2b0bcdacf653813f890)
- 768k meson
- 3772k autotools (768k after removing bin files)
- [jsoncpp: migrate to meson build](https://github.com/LibreELEC/LibreELEC.tv/commit/c2ca0ff90e879f60030f23d75d6b2900c96a9f3e)
- 552k cmake release
- 520k meson
- [nghttp2: migrate to cmake build](https://github.com/LibreELEC/LibreELEC.tv/commit/833b671f5c09625b0f63b6485d7861a2a35857ca)
- 408k cmake release 
- 412k configure
- part of #5970
> migrate to cmake and meson builds

- config/show_config
was:
- OpenGL (GLX) support (provider):      no (no)
- OpenGL ES support (provider):         yes (mesa)
- Vulkan API support (provider):        no (no)
is:
- OpenGL (GLX) support (provider):      no ()
- OpenGL ES support (provider):         yes (mesa)
- Vulkan API support (provider):        no ()
> config/show_config: do not display provider when provider is no

- packages/network/samba/package.mk
Samba browsing in LibreELEC 11.0 has been not working since samba 4.16.
- fix #6241 and #6719 
by adding the `samba-dcerpcd` to support `DCERPC` in the member server setup.
DCERPC services have been broken out from smbd, the new samba-dcerpcd binary has been created.
It is invoked (in LE) on demand from smbd to serve DCERPC over named pipes. The required rpc_ service binaries are also required. 
```
Password for [WORKGROUP\libreelec]:
Sharename       Type      Comment
---------       ----      -------
Update          Disk      
Videos          Disk      
Music           Disk      
TV Shows        Disk      
Recordings      Disk
…
```
> samba: fix dcerpc and srvsvc browsing

- scripts/checkdeps
Tested on a clean install/fresh installation and works ootb.
- adds arch based https://endeavouros.com/
- fixes Java by pacman installing [`[java]=jdk8-openjdk`](https://archlinux.org/packages/extra/x86_64/jdk-openjdk/) which also provides https://archlinux.org/packages/extra/any/java-environment-common/
> [le11] scripts/checkdeps: add EndeavourOS & fix Java

- packages/graphics/libde265/package.mk
- packages/graphics/libde265/patches/libde265-0001-275-Add-CMake-option-ENABLE-SDL.patch
- packages/graphics/libde265/patches/libde265-0002-Add-CMake-option-ENABLE-ENCODER.patch
- packages/graphics/libheif/package.mk
- packages/graphics/tiff/package.mk
- packages/graphics/tiff/patches/tiff-0001-only-build-library.patch
- Cmake patches from upstream.
- libde265 patch submitted upstream
- https://github.com/strukturag/libde265/pull/331
Updates
- libde265: migrate to cmake build
- resulting library `liblibde265.a` is larger, but resulting build of libheif (which uses this library is smaller)
- Don’t build decoder or encoder binaries (as they are not used)
- libheif: migrate to cmake build
- resulting build are smaller
- tiff: migrate to cmake build
- resulting build are smaller
This PR is more of
- #5970
> More migrate to cmake builds

- packages/linux-firmware/firmware-imx/package.mk
release notes:
Binary files updated in this release:
- firmware/ddr/synopsys/lpddr4_dmem_1d_v202201.bin
- firmware/ddr/synopsys/lpddr4_dmem_2d_v202201.bin
- firmware/ddr/synopsys/lpddr4_imem_1d_v202201.bin
- firmware/ddr/synopsys/lpddr4_imem_2d_v202201.bin
- firmware/hdmi/cadence/dp_ls1028a.bin
- firmware/hdmi/cadence/signed_dp_imx8m.bin
- firmware/vpu/vpu_fw_imx8_dec.bin
> firmware-imx: update to 8.17 (iMX8 updates)

- packages/addons/addon-depends/go/package.mk
- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
- [syncthing: update to 1.21.0 and addon (121)](https://github.com/LibreELEC/LibreELEC.tv/commit/dcd1e66913b3bf415d09b934015a941055053638)
- [go: update to 1.19.1](https://github.com/LibreELEC/LibreELEC.tv/commit/596aaff80d1b9f55515435c0123b1203649d4c28)
- all other go packages already tested building with go 1.19 (Syncthing was the remaining package that needed to be updated - to support go 1.19)
> syncthing: update to 1.21.0 and addon (121)

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.16.5.html
> samba: update to 4.16.5

- packages/lang/Python3/package.mk
changelog:
- https://docs.python.org/3.9/whatsnew/changelog.html
```
Generic.x86_64-devel-20220908121749-e843efd
Linux nuc11 6.0.0-rc4 #1 SMP Thu Sep 8 11:56:34 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:1ade57db993d29ea314420c416b77b028d142135). Platform: Linux x86 64-bit
Kodi compiled 2022-09-08 by GCC 12.2.0 for Linux x86 64-bit version 6.0.0 (393216)
Running on LibreELEC (heitbaum): devel-20220908121749-e843efd 11.0, kernel: Linux x86 64-bit version 6.0.0-rc4
CApplication::CreateGUI - trying to init …
```
> Python3: update to 3.9.14

- packages/linux/package.mk
- projects/Allwinner/patches/linux/crust/0036-firmware-arm_scpi-Support-unidirectional-mailbox-cha.patch
- 5.10.136
- https://lore.kernel.org/lkml/20220809175512.853274191@linuxfoundation.org/
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.136
- 5.10.137 - 541 patches
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.137
- 5.10.138 - 157 patches
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.138
- 5.10.139 - 1 patch
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.139
- 5.10.140 - 86 patches
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.140
- 5.10.141 - 37 patches
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.141
- 5.10.142 - 80 patches
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.14#
- more speculation fixes …
> linux: update to 5.10.y

- packages/multimedia/ffmpeg/package.mk
This PR picks up the pkg version & writes it to the `RELEASE` / `VERSION` file which is picked up by the ffmpeg build
`FFmpeg version/source: 9.0.0-10379-g73795073fa`
```
AMLGX.arm-RR-20220907-62dd248
Linux vim1 5.19.0 #1 SMP PREEMPT Wed Sep 7 22:21:57 CEST 2022 aarch64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:1ade57db993d29ea314420c416b77b028d142135). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-09-07 by GCC 12.2.0 for Linux ARM 32-bit version 5.19.0 (332544)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20220907-62dd248 11.0, kernel: Linux ARM 64-bit version 5.19.0
FFmpeg version/source: 9.0.0-10379-g73795073fa
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled …
```
> [le11] ffmpeg: fix version output

- packages/mediacenter/LibreELEC-settings/package.mk
Backport of #6882 
Changes since d6c41d4:
Update translations from Weblate
Rework manual update for new infrastructure
> [LE10] Backport: LibreELEC-settings: update to d6c41d4

- config/arch.aarch64
- config/arch.arm
- config/arch.x86_64
This removes march & mtune from LDFLAGS. I don't know why they were added. Way back when, when using LTO, C(XX)FLAGS were added en masse to LDFLAGS, but that's not what this is doing. Generic's '-m64' is probably superfluous but I don't build generic / want to speak with authority on it.
The flags added, sort-common, and O1 in non-debug both relate to application start up performance, which should mostly translate to a faster boot time.
Wider testing appreciated.
> [le11] build: LDFLAGS cleanup

- packages/lang/gcc/package.mk
- packages/mediacenter/kodi/package.mk
Kodi's own ccache support was incorrectly enabled when switching from configure to cmake builds in commit 98a96ef1f721e8a444a7769321a6185f156b6f46
This resulted in ccache misses on clean rebuilds and about 1GB of data being added to the cache on each clean rebuild and longer rebuild times.
Restore the old behavior to speed things up again.
Also gcc:bootstrap didn't install a ccache wrapper so glibc was being rebuilt without ccache. Add the wrapper to speed up builds.
I'm now getting a 99.67% cache hit rate on clean RPi4 rebuilds (with ccache intact) and roughly 15-20% faster rebuilds.
> fix ccache handling of kodi and gcc:bootstrap

- projects/Allwinner/patches/linux/0036-wip-h3-h5-cvbs.patch
As it turns out, H5 CVBS output doesn't work. I thought it's same as on H3, but it has some specifics, which need different handling. Update patch so there is at least some image displayed.
While testing, both me and forum user experienced some issues. However, they are different. CVBS works well for me but not the user. I experienced Kodi crashes, but user presumably didn't (not 100% sure).
NOTE: This means that H5 CVBS output on LE10 is totally broken. However, I'm hesitant to backport this patch because resulting image doesn't work well. While issues in my case doesn't seem really connected to CVBS (Kodi crash), they can be observed only when CVBS is enabled and HDMI unplugged.
Ref: https://forum.libreelec.tv/thread/26022-cvbs-out-on-orange-pi-pc-2/
> [LE11] Allwinner: linux: Fix H5 CVBS patch

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://github.com/KhronosGroup/Vulkan-Docs/commit/355367640f2eabd2a0d492010a0afc166696aa72
- vulkan-headers: update to 1.3.228
- vulkan-loader: update to 1.3.228
- vulkan-tools: update to 1.3.228
> Vulkan: update to 1.3.228

- packages/mediacenter/kodi/package.mk
- fix build of latest binary add-ons
> kodi: update to 9f7e9e0

- packages/graphics/mesa/package.mk
https://lists.freedesktop.org/archives/mesa-announce/2022-September/000687.html
```
Generic.x86_64-devel-20220921111509-e527050
Linux nuc12 6.0.0-rc6 #1 SMP Wed Sep 21 11:15:30 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA3 (19.90.710) Git:9f7e9e02313cd935f93ee47b30758de051c09d91). Platform: Linux x86 64-bit
Kodi compiled 2022-09-19 by GCC 12.2.0 for Linux x86 64-bit version 6.0.0 (393216)
Running on LibreELEC (heitbaum): devel-20220921111509-e527050 11.0, kernel: Linux x86 64-bit version 6.0.0-rc6
FFmpeg version/source: 4.4.1-Nexus-Alpha1-Kodi
CApplication::CreateGUI …
```
> mesa: update to 22.2.0

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
- packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.demo/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.freebox/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.njoy/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.octonet/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.plutotv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.teleboy/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vdr.vnsi/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.wmc/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
Updating LibreELEC 11 nighlty to latest version (20220920-5d1ef41) disables all previously enabled PVR addons due to API incompatibility.
Kodi PR https://github.com/xbmc/xbmc/pull/21424 requires all PVR and inputstream addons to be re-compiled. Thus, all packages were bumped. As an example, pvr.waipu version was bumped to 20.6.0 (https://github.com/flubshi/pvr.waipu/pull/212).
In LibreELEC this update for all binary addons was merged in https://github.com/LibreELEC/LibreELEC.tv/pull/6896 (2022-09-17). The corresponding Kodi update was merged in https://github.com/LibreELEC/LibreELEC.tv/pull/6906 (2022-09-19), which means that the binary addons were compiled with the old API version.
This package bump `update_binary-addons -b` updates all PKG_REV to ensure binary addons are re-compiled …
> Bump PVR/inputstream binary addons

- packages/web/nghttp2/package.mk
announcement:
- https://nghttp2.org/blog/2022/09/21/nghttp2-v1-50-0/
- https://github.com/nghttp2/nghttp2/releases/tag/v1.50.0
> nghttp2: update to 1.50.0

- packages/addons/service/mariadb/changelog.txt
- packages/addons/service/mariadb/package.mk
- packages/addons/service/mariadb/source/bin/mariadb.start
compatibility issues with the le11 build environment are why the intermediate 10.6 were not compiled for le11. This release could be backported to le10 if required to be.
manage build cross compile build errors:
- CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately
variables required to be defined
LSTAT_FOLLOWS_SLASHED_SYMLINK_EXITCODE=0
LSTAT_FOLLOWS_SLASHED_SYMLINK_EXITCODE__TRYRUN_OUTPUT=““
MASK_LONGDOUBLE_EXITCODE=0
MASK_LONGDOUBLE_EXITCODE__TRYRUN_OUTPUT=“”
STAT_EMPTY_STRING_BUG_EXITCODE=0
STAT_EMPTY_STRING_BUG_EXITCODE__TRYRUN_OUTPUT=“”
> [le11] mariadb: update to 10.9.3 and addon (107)

- scripts/extract
add flag "-o" to overwrite file on unzipping.
when a build is interrupted by some issues, it will cause a re-substitution problem after a rebuild the target whose source code come from a zip file (like target jzintv)
> [le11] scripts/extract: force overwrite file on unziping files

- projects/Samsung/patches/mesa/panfrost-0001-panfrost-enable-Mali-T628-support.patch
- Update patch to support #6907
without the updated patch
```
UNPACK      mesa
APPLY PATCH (project)      projects/Samsung/patches/mesa/panfrost-0001-panfrost-enable-Mali-T628-support.patch
patching file src/panfrost/lib/pan_props.c
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file src/panfrost/lib/pan_props.c.rej
patch -d "${PKG_BUILD}" -p1 < ${i} 1>&${VERBOSE_OUT}
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
```
> mesa: update panfrost: enable Mali T628 support patch for mesa 22.

- packages/sysutils/tz/package.mk
Release 2022d - 2022-09-23 12:02:57 -0700
Briefly:
Palestine transitions are now Saturdays at 02:00.
Simplify three Ukraine zones into one.
Changes to future timestamps
Palestine now springs forward and falls back at 02:00 on the
first Saturday on or after March 24 and October 24, respectively.
This means 2022 falls back 10-29 at 02:00, not 10-28 at 01:00.
(Thanks to Heba Hamad.)
Changes to past timestamps
Simplify three Ukraine zones to one, since the post-1970
differences seem to have been imaginary.  Move Europe/Uzhgorod and
Europe/Zaporozhye to 'backzone'; backward-compatibility links
still work, albeit with different timestamps before October 1991.
> [le11] tz: update to 2022d

- packages/debug/edid-decode/package.mk
- packages/devel/configtools/package.mk
- packages/devel/libcap/package.mk
- packages/lang/lua54/package.mk
- packages/python/devel/Mako/package.mk
- packages/tools/mtools/package.mk
- mtools: update to 4.0.41
- https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00011.html
- Mako: update to 1.2.3
- https://docs.makotemplates.org/en/latest/changelog.html#id1
- configtools: update to 2022-08-01
- edid-decode: update to 2022-09-23
- libcap: update to 2.66
- lua54: update to 5.4.4
- https://www.lua.org/bugs.html
- https://www.lua.org/work/diffs-lua-5.4.3-lua-5.4.4.html
> package updates and tidy ups

- packages/sysutils/tz/package.mk
Release 2022d - 2022-09-23 12:02:57 -0700
Briefly:
Palestine transitions are now Saturdays at 02:00.
Simplify three Ukraine zones into one.
Changes to future timestamps
Palestine now springs forward and falls back at 02:00 on the
first Saturday on or after March 24 and October 24, respectively.
This means 2022 falls back 10-29 at 02:00, not 10-28 at 01:00.
(Thanks to Heba Hamad.)
Changes to past timestamps
Simplify three Ukraine zones to one, since the post-1970
differences seem to have been imaginary.  Move Europe/Uzhgorod and
Europe/Zaporozhye to 'backzone'; backward-compatibility links
still work, albeit with different timestamps before October 1991.
> [le10] tz: update to 2022d

- config/functions
- scripts/build
Timing detail reporting can be enabled by setting
TRACE_BUILD_TIMING=1
This enables timestamping collecting at various build stages so we can easily analyze how long eg configure, make/build, install etc steps take.
Example output:
```
build timing details:
total:     25.277
unpack:      1.367
pre-build setup:      0.004
configure:      7.848
make:     14.622
make install:      1.090
copy sysroot:      0.301
cleanup install:      0.045
```
> buildsystem: add support for reporting build timing details

- projects/Generic/linux/linux.x86_64.conf
AMD sienna_cichlid  GPU support is missing in Generic kernel although possible. Enable:
```
config DRM_AMD_DC_DCN3_0
bool "DCN 3.0 family"
depends on DRM_AMD_DC && X86
depends on DRM_AMD_DC_DCN
help
Choose this option if you want to have
sienna_cichlid support for display engine
```
Reported in forum: https://forum.libreelec.tv/thread/26124-no-screen-after-gpu-upgrade/
Let's test in nightlys.
> Generic kernel config: enable sienna_cichlid support 

- packages/network/connman/package.mk
This bumps connman to the latest snapshot which includes some CVE fixes.
> connman: bump to include latest changes

- packages/sysutils/busybox/package.mk
- packages/sysutils/busybox/scripts/vfd-clock
- packages/sysutils/busybox/system.d/vfd-clock.service
This adds a small vfd-clock script/service to overwrite 'boot' text on the Tanix TX3 VFD display with a clock, leveraging the bitbang 7-segment display driver that's in the process of being upstreamed to the kernel. It should be expandable to other devices given time for fiddling and experiments.
> busybox: add vfd-clock script/service

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
- packages/sysutils/open-vm-tools/package.mk
- media-driver: update to 22.5.4
- https://github.com/intel/media-driver/compare/intel-media-22.5.3...intel-media-22.5.4
- gmmlib: update to 22.2.0
- https://github.com/intel/gmmlib/compare/intel-gmmlib-22.1.8...intel-gmmlib-22.2.0
- open-vm-tools: update to 12.1.0
- https://github.com/vmware/open-vm-tools/releases/tag/stable-12.1.0
```
Generic.x86_64-devel-20221001030611-6655a24
Linux nuc12 6.0.0-rc7 #1 SMP Sat Oct 1 03:08:07 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA3 (19.90.710) Git:9f7e9e02313cd935f93ee47b30758de051c09d91). Platform: Linux x86 64-bit
Kodi compiled 2022-10-01 by GCC 12.2.0 for Linux x86 64-bit version 6.0.0 (393216)
Running on LibreELEC (heitbaum): devel-20221001030611-6655a24 11.0, kernel: Linux x86 64-bit version …
```
> Intel driver updates

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch
- packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
spdlog PR finally got merged, so spdlog is no longer used in header-only mode. This seems to have sped up kodi rebuild by about 10%
Our disable minimimize and sigterm patches are adatped to the recent kodi changes (moving Application.h/cpp)
> kodi: update to latest master

- packages/addons/service/prometheus-node-exporter/changelog.txt
- packages/addons/service/prometheus-node-exporter/package.mk
release notes:
- https://github.com/prometheus/node_exporter/releases/tag/v1.4.0
- backport of #6955
> [le10] prometheus-node-exporter: update to 1.4.0 and addon (102)

- packages/linux/sysctl.d/network.conf
Temporary addresses are privacy-preserving for outgoing traffic, as they
don't disclose the MAC address.
See also https://blog.apnic.net/2022/06/10/iot-devices-endanger-ipv6-privacy/
The MAC-derived IPv6 stays, so clients (e.g. IP-based remotes) have a
permanent IPv6 as before.
Servers, including local ones, will see changing IPv6 addresses when
contacted by LibreELEC. Users who don't like this may revert this
setting.
This shouldn't break anything. It only has an effect for IPv6-enabled networks.
> Generate and use temporary IPv6 addresses

- packages/mediacenter/kodi/package.mk
- packages/multimedia/aom/package.mk
- kodi: do not set ENABLE_NEON for target x86_64
- tidy up cmake warning
- If ENABLE_NEON is set whilst building x86_64 with cmake. 
- cmake warns that the variable is not been used.
- aom: update to 3.5.0 and do not set ENABLE_NEON for target x86_64
> Do not set ENABLE_NEON_ for not target aarch64 and arm

- packages/addons/addon-depends/ttyd-depends/libuv/package.mk
- packages/addons/addon-depends/ttyd-depends/libwebsockets/package.mk
- packages/addons/service/ttyd/changelog.txt
- packages/addons/service/ttyd/package.mk
Updates
-  ttyd: update to 1.7.1 and addon (106)
- libuv: update to 1.44.2
- libwebsockets: update to 4.3.2
backport 
- of #6943
> [le10] ttyd: update to 1.7.1 and addon (106)

- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
- backport of #6941 
Changelog:
- https://github.com/rsyslog/rsyslog/blob/master/ChangeLog
> [le10] rsyslog: update to 8.2208.0

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Docs: 
- 1.3.229 https://github.com/KhronosGroup/Vulkan-Docs/commit/07560427085af01aafb985bf0cffa959bf85cb8c
- 1.3.230 https://github.com/KhronosGroup/Vulkan-Docs/commit/ac3762095459e0190a75c433af1f85d2f6023d44
- vulkan-headers: update to 1.3.230
- vulkan-loader: update to 1.3.230
- vulkan-tools: update to 1.3.230
> Vulkan update to 1.3.230

- scripts/checkdeps
This replaces #6823, which I assume has been abandoned.
Rather than test if it's Fedora version >= 34, it just checks if it's Fedora because Fedora 34 and earlier are EOL (https://docs.fedoraproject.org/en-US/releases/eol/). I assume RHEL and its clones will need a similar change at some point, but as this has been possibly broken since Fedora 34's release 18+ months ago, I just assume wait for a report to show up instead of guess.
> scripts/checkdeps: fedora bdftopcf package name change

- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
Upgrade vim from version 8.2.5052 to 9.0.0453. This is the latest version as reported by script tools/update-scan.
To build this change :
docker run --rm --log-driver none -v `pwd`:/build -w /build -it libreelec scripts/create_addon system-tools
To test this change on the target:
1.  Install addon from zip file. Located at target/addons/10.80.8/Generic/x86_64/virtual.system-tools/virtual.system-tools-10.80.8.132.zip
2. ssh into the target and type in:
vim --version. 
It should display VIM - Vi IMproved 9.0
> vim: update to 9.0.0453

- config/functions
- config/optimize
- config/show_config
- distributions/LibreELEC/options
- packages/devel/glibc/package.mk
- packages/mediacenter/kodi/package.mk
- packages/readme.md
This is an alternative to #6922 allowing more flexible linker configuration.
Default linker can be set with DEFAULT_LINKER in options.
Packages can influence linker selection both by positive and/or negative PKG_BUILD_FLAGS, eg +bfd or -gold.
Positive build flags take priority over the default linker so eg DEFAULT_LINKER="gold" and PKG_BUILD_FLAGS="+bfd" will select bfd.
Negative flags mean a specifiy linker should not be used, eg -gold prevent using gold.
If the default linker is disabled via a build flag then any other available linker will be used (typically falling back to bfd which is always present).
Optional linkers like gold have to be enabled with eg GOLD_SUPPORT="yes" in options. If an optional linker is not enabled it won't be a candidate for linker selection. So eg "+mold" …
> buildsystem: support choosing default linker

- packages/addons/addon-depends/go/package.mk
- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
these are backports of LE11
Package updates
- go: update to 1.19.2
- syncthing: update to 1.22.0 and addon (122)
- requires 1.18 or 1.19 golang.
build of all go:host dependencies completed.
```
s/create_addon service.docker
s/create_addon service.prometheus-node-exporter
s/create_addon service.syncthing
```
> [le10] syncthing: update to 1.22.0 and addon (122) and dependent golang

- packages/audio/wireplumber/package.mk
Release notes:
- https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/master/NEWS.rst
> wireplumber: update to 0.4.12

- config/functions
- config/optimize
- config/show_config
- distributions/LibreELEC/options
- packages/devel/mimalloc/package.mk
- packages/devel/mold/package.mk
- packages/devel/mold/patches/mold-999.01-PR740-allow-custom-mold-binary-install-path.patch
- packages/devel/spdlog/package.mk
- packages/devel/tbb/package.mk
- packages/devel/tbb/patches/tbb-999.01-PR824-retry-if-pthread_create-fails-with-EAGAIN.patch
- packages/lang/gcc-aarch64/package.mk
- packages/lang/gcc-arm-none-eabi/package.mk
- packages/lang/gcc-bpf/package.mk
- packages/lang/gcc-or1k/package.mk
- packages/lang/gcc/package.mk
- packages/mediacenter/kodi/package.mk
- packages/readme.md
The basic idea is based on this PR https://github.com/LibreELEC/LibreELEC.tv/pull/6665 which is somewhat stalled, not completely functional & needs rebase. Since mold linker benchmarks show nice performance gains it could speed up the compilation of the distro image on systems with a lot of cores/threads see https://github.com/rui314/mold#readme & https://github.com/xbmc/xbmc/pull/20891 for details.
- build `mold:host` conditionally as `gcc` packages dependency
- add `MOLD_SUPPORT` distro var
- build `spdlog` as shared lib to fix Kodi linking by mold 
- add `Kodi` support for `mold` linking in pkg build opts
EDIT: rebased on https://github.com/LibreELEC/LibreELEC.tv/pull/6928
> [le11] Add support for building with MOLD linker v2

- packages/addons/addon-depends/mpd-mpc/package.mk
- packages/addons/service/mpd/changelog.txt
- packages/addons/service/mpd/package.mk
- packages/devel/libfmt/package.mk
- packages/devel/spdlog/package.mk
As of https://github.com/xbmc/xbmc/pull/21674 - Kodi Matrix now supports libfmt 9. Backport libfmt 9 to LE10.
To support libfmt 9 - the following minimum updates to other packages are also required:
- spdlog - 1.9.2
- mpd - 0.23.8 (addon)
The following packages are updated in this PR:
- libfmt: update to 9.1.0
- spdlog: update to 1.10.0
- mpd: update to 0.23.8 and addon (114)
- mpd-mpc: update to 0.34 — used by mpd
> [le10] libfmt: update to 9.1.0

- packages/graphics/bcm2835-driver/package.mk
- packages/tools/bcm2835-bootloader/package.mk
Backport of #6977 , fixes no LAN on Pi400
> [le10] RPi: update to firmware 53f4941

- packages/mediacenter/LibreELEC-settings/package.mk
This should fix Bluetooth paring / pin entry https://github.com/LibreELEC/service.libreelec.settings/pull/283
> LibreELEC-settings: update to f369cd1

- packages/debug/libva-utils/package.mk
- packages/multimedia/libva/package.mk
Version 2.16.0 - 8.Oct.2022
* trace: print the display being attempted
* ci: upgrade FreeBSD to 13.1
* meson: Search for threads in top-level meson.build
* meson: produce summary() when 0.53.0 is present
> libva and libva-utils: update to 2.16.0 

- projects/Allwinner/patches/linux/0056-media--cedrus--Fix-watchdog-race-condition.patch
This fixes a bug for cases where Cedrus finishes job immediately, most likely due to some failure, before watchdog is activated.
> [LE10] Allwinner: linux: fix cedrus watchdog race condition

- packages/graphics/harfbuzz/package.mk
- packages/graphics/harfbuzz/patches/harfbuzz-100.01-fix-meson-icu-opts.patch
- update to 5.3.0
- seems like the ICU detection is "broken" now and pulls in system ICU files which leads to `HAVE_ICU` defined and ends up with a broken build. These [changes](https://github.com/harfbuzz/harfbuzz/commit/53a194aa3f5f7de0b40e879e41fcbe0de6e9fefe#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4R112) lead to:
```
Determining dependency 'ICU' with CMake executable '-DCMAKE_INSTALL_PREFIX=/usr'
Try CMake generator: auto
Calling CMake (['cmake', '-DCMAKE_TOOLCHAIN_FILE=/mnt/build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf', '-DCMAKE_INSTALL_PREFIX=/usr']) in /mnt/build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/build/harfbuzz-5.2.0/.x86_64-libreelec-linux-gnu/meson-private/cmake_ICU with: …
```
> harfbuzz: update to 5.3.0 and fix build after 5.2.0 update

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
- mediainfo: update to 22.09
- libmediainfo: update to 22.09
- mpg123: update to 1.30.2 and https
- squeezelite: update to 2022-04-10 (1.9.9.1403)
> [le11] multimedia-tools: update addon to (117)

- packages/compress/xz/package.mk
- set PKG_TOOLCHAIN="configure" as the cmake support in xz is experimental
- due to https://git.tukaani.org/?p=xz.git;a=commit;h=31d80c6b261b24220776dfaeb8a04f80f80e0a24 and the static builds of xz - --enable-symbol-versions=no needs to be set to compile Python3
- tested builds of dependant addons too.
- https://tukaani.org/xz/
- https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;h=0205423e79ce8297102096b0fc8b030ddf5b2023;hb=d2003362dd42004355a5550ee7a60ace3b3ea2d8
* liblzma:
- Made lzma_filters_copy() to never modify the destination
array if an error occurs. lzma_stream_encoder() and
lzma_stream_encoder_mt() already assumed this. Before this
change, if a tiny memory allocation in lzma_filters_copy()
failed it would lead to a crash (invalid free() or invalid
memory reads) in the cleanup …
> xz: update to 5.2.7

- packages/graphics/mesa/package.mk
Ann:
- https://lists.freedesktop.org/archives/mesa-announce/2022-October/000688.html
```
Generic.x86_64-devel-20221011223717-7859258
Linux nuc12 6.0.1-rc1 #1 SMP Tue Oct 11 07:33:39 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA3 (19.90.710) Git:3066d800934f39c28b951c69930d3cbee5fd6308). Platform: Linux x86 64-bit
Kodi compiled 2022-10-10 by GCC 12.2.0 for Linux x86 64-bit version 6.0.0 (393216)
Running on LibreELEC (heitbaum): devel-20221011223717-7859258 11.0, kernel: Linux x86 64-bit version 6.0.1-rc1
FFmpeg version/source: 4.4.1-Nexus-Alpha1-Kodi …
```
> mesa: update to 22.2.1

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/tools/multimedia-tools/changelog.txt
- packages/addons/tools/multimedia-tools/package.mk
- mediainfo: update to 22.09
- libmediainfo: update to 22.09
- mpg123: update to 1.30.2 and https
- squeezelite: update to 2022-04-10 (1.9.9.1403)
backport of:
- #6984
> [le10] multimedia-tools: update addon to (117)

- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Dependencies are:
- llvm: do not build with zstd
- rust does not build when LLVM has been built with LLVM_ENABLE_ZSTD
- rust bootstrap LD tries to find -llibzstd.so.1.5.2
Rust:
- rust: update to 1.64.0
- rustc-snapshot: update to 1.64.0
- rust-std-snapshot: update to 1.64.0
- cargo-snapshot update to 1.64.0
rust builds cleanly with llvm-15.0.y
> llvm: update to 15.0.2 and rust: update to 1.64.0

- packages/lang/Python3/package.mk
Release notes:
- https://www.python.org/downloads/release/python-3915/
```
LibreELEC (heitbaum): devel-20221012113704-76c159a (Generic.x86_64)
nuc12:~ # python --version
Python 3.9.15
```
> Python3: update to 3.9.15

- projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch
Update patch to support both Linux 6.0 and 6.1. vb2_find_timestamp is dropped in 6.1-rc1
> linux (Rockchip): media: rkvdec-hevc: Use vb2_find_buffer

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.1
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0.2
- 
6.0.1 - 17 patches
6.0.2 - 34 patches (Wifi security)
- wifi fixes https://www.phoronix.com/news/Linux-6.0.2-Point-Releases-WiFi
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.0.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.0.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.0
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 …
```
> linux: update to 6.0.y

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.1.html
> samba: update to 4.17.1

- packages/graphics/mesa/package.mk
Announcement:
- https://lists.freedesktop.org/archives/mesa-announce/2022-October/000689.html
```
Generic.x86_64-devel-20221020073928-b7e17be
Linux nuc12 6.0.3-rc1 #1 SMP Wed Oct 19 10:24:18 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA3 (19.90.710) Git:3066d800934f39c28b951c69930d3cbee5fd6308). Platform: Linux x86 64-bit
Kodi compiled 2022-10-19 by GCC 12.2.0 for Linux x86 64-bit version 6.1.0 (393472)
Running on LibreELEC (heitbaum): devel-20221020073928-b7e17be 11.0, kernel: Linux x86 64-bit version 6.0.3-rc1
FFmpeg version/source: 4.4.1-Nexus-Alpha1-Kodi …
```
> mesa: update to 22.2.2

- packages/network/rsync/package.mk
news:
- https://download.samba.org/pub/rsync/NEWS#3.2.7
cleanup build warnings
> rsync: update to 3.2.7

- projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch
Since https://github.com/LibreELEC/LibreELEC.tv/pull/7017 HEVC decoding is failing for Rockchip, since the `vb2_buffer` is not correctly initalized.
Fix it.
> Rockchip: linux: Fix HEVC decoding

- packages/mediacenter/LibreELEC-settings/package.mk
This is the change to manual update to keep from updating to a lower major version.
> LibreELEC-settings: update to 1d458c6

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- [spirv-tools: update githash to 2022-10-13](https://github.com/LibreELEC/LibreELEC.tv/commit/7dd0d7b342a69d8781b757c694471fb27c0a8e2d)
- [spirv-headers: update githash to 2022-10-06](https://github.com/LibreELEC/LibreELEC.tv/commit/dc69aa3af98e79cef8d58ad49a4eb5c4c9c8e121)
- [glslang: update to 11.12.0](https://github.com/LibreELEC/LibreELEC.tv/commit/6c79cb246e6277bc9da2bd262688543235541732)
> glslang: update to 11.12.0

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
Release notes:
- https://github.com/KhronosGroup/Vulkan-Docs/commit/7a319840243ea33aa4caa42cdce0143b150e02bb
packages
- vulkan-headers: update to 1.3.231
- vulkan-loader: update to 1.3.231
- vulkan-tools: update to 1.3.231
> Vulkan update to 1.3.231

- packages/audio/alsa-lib/package.mk
- packages/audio/alsa-ucm-conf/package.mk
- packages/audio/alsa-utils/package.mk
- alsa-utils: update to 1.2.8
- alsa-lib: update to 1.2.8
- alsa-ucm-conf: update to 1.2.8
release notes:
- https://www.alsa-project.org/wiki/Changes_v1.2.7.2_v1.2.8
> Alsa updates to 1.2.8

- packages/multimedia/nvidia-vaapi-driver/package.mk
- packages/wayland/util/bemenu/package.mk
- packages/x11/data/xkeyboard-config/package.mk
- packages/x11/lib/libXmu/package.mk
- packages/x11/lib/libXrender/package.mk
- packages/x11/lib/libXtst/package.mk
- packages/x11/lib/libXxf86vm/package.mk
- packages/x11/lib/libpciaccess/package.mk
- packages/x11/lib/libxkbfile/package.mk
- packages/x11/lib/libxshmfence/package.mk
- packages/x11/lib/pixman/package.mk
- packages/x11/other/fontconfig/package.mk
- bemenu: update to 0.6.13
- libXxf86vm: update to 1.1.5
- libXtst: update to 1.2.4
- nvidia-vaapi-driver: update to 0.0.7
- xkeyboard-config: update to 2.37
- libXmu: update to 1.1.4 and https
- libpciaccess: update to 0.17 and https
- libxkbfile: update to 1.1.1 and https
- pixman: update to 0.42.0 and https
- libxshmfence: update to 1.3.1 and https
- fontconfig: update to 2.14.1 and https and PKG_SITE
- libXrender: update to 0.9.11
> Wayland and X11 updates

- packages/addons/addon-depends/chrome-depends/chrome-libXrender/package.mk
- packages/addons/addon-depends/chrome-depends/chrome-libXtst/package.mk
Both chrome-libXrender and chrome-libXtst fail to build because the unpack step refers to the bz2 file which is now an xx file.
> Addon fixes

- packages/sysutils/exfatprogs/package.mk
```
supervisedthinking@x220l:/mnt/dev/LibreELEC-RR$ scripts/get exfatprogs
GET      exfatprogs (archive)
--2022-10-29 14:47:09--  https://github.com/exfatprogs/exfatprogs/releases/download/1.2.0/exfatprogs-1.2.0.tar.xz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/234896758/64659926-52bb-4b64-8b6c-dfa775d6d1ba?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20221029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221029T124709Z&X-Amz-Expires=300&X-Amz-Signature=ba39403b64cefeaad585b33935df0b4184605be4c3a0a984760fae2c66bdeeeb&X-Amz-SignedHeaders=host&actor_id=0& …
```
> exfatprogs: fix SHA256

- packages/addons/addon-depends/chrome-depends/chrome-libxshmfence/package.mk
- packages/addons/addon-depends/faad2/package.mk
- packages/addons/addon-depends/game-tools/linuxconsoletools/package.mk
- packages/addons/addon-depends/game-tools/linuxconsoletools/patches/linuxconsoletools-0001-disable-building-ffmvforce.patch
- packages/addons/service/mpd/changelog.txt
- packages/addons/service/mpd/package.mk
- packages/addons/service/rsyslog/changelog.txt
- packages/addons/service/rsyslog/package.mk
- packages/addons/service/syncthing/changelog.txt
- packages/addons/service/syncthing/package.mk
- packages/addons/tools/game-tools/changelog.txt
- packages/addons/tools/game-tools/package.mk
- [syncthing: update to 1.22.0 and addon (122)](https://github.com/LibreELEC/LibreELEC.tv/commit/969a9c4ffdcb7eb415c11b3276cec9b35f51247f)
- [rsyslog: update to 8.2210.0 and addon (113)](https://github.com/LibreELEC/LibreELEC.tv/commit/e313518be0521c1dfcb124cf9849403c5b00d0c4)
- [game-tools: update addons tools (104)](https://github.com/LibreELEC/LibreELEC.tv/commit/c6b31de98d32018aec75f21abc9873a9cf5672c0)
- [linuxconsoletools: update to 1.8.1](https://github.com/LibreELEC/LibreELEC.tv/commit/c7ab1c7e7acb7847a02d28204d23f6aca2591aa2)
- [mpd: update to 0.23.10 and addon (115)](https://github.com/LibreELEC/LibreELEC.tv/commit/99b928bc4cddb5a5f16c0f4d6b0653600faddba1)
- [faad2: update to 2.10.1](https://github.com/LibreELEC/LibreELEC.tv/commit/03a402191e86041374fc8d86d230e96dc7b967a8)
- …
> [le11] Addons updates

- packages/network/samba/package.mk
Security release:
https://www.samba.org/samba/history/samba-4.17.2.html
> samba: update to 4.17.2

- packages/security/openssl/package.mk
Release notes:
- https://www.openssl.org/blog/blog/2022/11/01/email-address-overflows/
> openssl: update to 3.0.7

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Announcement: https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html
- rust: update to 1.65.0
- rustc-snapshot: update to 1.65.0
- rust-std-snapshot: update to 1.65.0
- cargo-snapshot update to 1.65.0
> Rust update to 1.65.0

- packages/linux/package.mk
This fixes the "no signal after bringing some TVs out of standby" issue reported on the forum
https://forum.libreelec.tv/thread/26214-rpi-4b-no-video-signal-after-lg-tv-started-from-previous-standby/?postID=173853#post173853
> linux (RPi): update to 6.0.6

- packages/sysutils/systemd/config/hwdb.d/99-osmcrf.hwdb
As requested by users, this adds support for two missing VID/PID HW remaps that are missing in LE.
> Update OSMC hwdb remapping

- packages/multimedia/gstreamer/gstreamer/package.mk
Build was failing when doing standalone build of `gstreamer` from `make clean` while checking https://forum.libreelec.tv/thread/26238-package-dependency-not-building/
> gstreamer: update PKG_DEPENDS_TARGET

- packages/devel/libbpf/package.mk
- packages/sysutils/v4l-utils/patches/v4l-utils-002-support-libbpf-1-0-0.patch
- packages/sysutils/v4l-utils/patches/v4l-utils-003-enable-bpf-without-clang.patch
- v4l-utils: support build with libbpf 1.0.1
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018915
- libbpf: update to 1.0.1
https://git.linuxtv.org/v4l-utils.git/log/
> libbpf update to 1.0.1 and patch v4l-utils to support build with libbpf 1.0.1 

- packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20221108
```
nuc12:~ # dmesg | head
[    0.000000] microcode: microcode updated early to revision 0x424, date = 2022-09-19
[    0.000000] Linux version 6.1.0-rc4 (docker@c22ecb9022af) (x86_64-libreelec-linux-gnu-gcc-12.2.0 (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39) #1 SMP Wed Nov  9 04:44:40 UTC 2022
```
> intel-ucode: update to 20221108

- packages/sysutils/util-linux/config/swap.conf
- packages/sysutils/util-linux/scripts/mount-swap
These are shellcheck adjustments for mount-swap, and comments in swap.conf to help users set the variables correctly when copying it.
> util-linux: cleanup mount-swap, add comments to swap.conf

- packages/mediacenter/kodi/package.mk
- https://github.com/xbmc/xbmc/releases/tag/20.0b1-Nexus
```
AMLG12B.arm-RR-20221109-1bcd80b
Linux vim3 5.19.14 #1 SMP PREEMPT Tue Nov 8 15:13:13 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-11-09 by GCC 12.2.0 for Linux ARM 32-bit version 5.19.14 (332558)
Running on Amlogic Meson G12B (A311D) Khadas VIM3 with LibreELEC (ST): RR-20221109-1bcd80b 11.0, kernel: Linux ARM 64-bit version 5.19.14
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 6 cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
EGL_VENDOR = Mesa Project …
```
> kodi: update to 20.0b1-Nexus / v20 beta1

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
This adds back the vc4 force_hotplug module parameter which was missing in 6.x kernels
> linux (RPi): update to 6.0.8

- packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
Adds the evdev mapping for a Xaomi BT remote as reported in the forums: https://forum.libreelec.tv/thread/26261-fix-for-xiaomi-bluetooth-remote-with-nonworking-button/
> systemd: add xaomi remote to 70-local-keyboard.hwdb

- packages/security/nss/package.mk
Release notes:
- https://hg.mozilla.org/projects/nss/file/tip/doc/rst/releases/nss_3_85.rst
and remove make warnings from non x86 builds
> nss: update to 3.85

- packages/addons/addon-depends/network-tools-depends/sshfs/package.mk
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/sysutils/fuse3/package.mk
- packages/sysutils/open-vm-tools/package.mk
Fixes #5996
fuse3 is only supported by `open-vm-tools` and `sshfs` in the addons made available to LibreELEC. Remaining packages using fuse (fuse2) do not have planned fuse3 upgrades.
fuse was dropped from the LE11 base because ntfs3g (which used fuse2) was replaced by the kernel ntfs3. Thus fuse was no longer included; unless open-vm-tools was included. So the libfuse was only included on x86_64.
In addition to migrating to fuse3 (where possible); the fuse libraries have been included in the `system-tools` and `network-tools` addons. 
- fuse3: initial package
- open-vm-tools: migrate to fuse3 
- sshfs: update to 3.7.3 and fuse3
- network-tools: add fuse and fuse3 to addon and sshfs to 3.7.3 and addon to (116)
- system-tools: add fuse to addon and addon to (132)
The libfuse3 libraries are …
> Migrate to fuse3

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.3.html
==============================
Release Notes for Samba 4.17.3
November 15, 2022
==============================
o CVE-2022-42898: Samba's Kerberos libraries and AD DC failed to guard against
integer overflows when parsing a PAC on a 32-bit system, which
allowed an attacker with a forged PAC to corrupt the heap.
https://www.samba.org/samba/security/CVE-2022-42898.html
Changes since 4.17.2
o  Joseph Sutton <josephsutton@catalyst.net.nz>
* BUG 15203: CVE-2022-42898
o  Nicolas Williams <nico@twosigma.com>
* BUG 15203: CVE-2022-42898
> samba: update to 4.17.3

- packages/web/nghttp2/package.mk
release notes:
- https://github.com/nghttp2/nghttp2/releases/tag/v1.51.0
- https://nghttp2.org/blog/2022/11/13/nghttp2-v1-51-0/
> nghttp2: update to 1.51.0

- scripts/build
- see https://github.com/mesonbuild/meson/commit/3c7ab542c0c4770241eae149b0d4cd8de329aee0 for details
before:
```
Found ninja-1.11.1 at /mnt/dev/LibreELEC-RR/build.LibreELEC-RK3399.arm-11.0-devel/toolchain/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Executing (target): ninja 
```
after:
```
Found ninja-1.11.1 at /mnt/dev/LibreELEC-RR/build.LibreELEC-RK3399.arm-11.0-devel/toolchain/bin/ninja
Executing (target): ninja
```
> scripts/build: fix meson 0.64.0 deprecation warning

- packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.2/docs/relnotes/22.2.3.rst
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.2/docs/relnotes/22.2.4.rst
```
Generic.x86_64-devel-20221117101703-8fc598f
Linux nuc12 6.1.0-rc5 #1 SMP Wed Nov 16 14:28:30 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-11-16 by GCC 12.2.0 for Linux x86 64-bit version 6.1.0 (393472)
Running on LibreELEC (heitbaum): devel-20221117101703-8fc598f 11.0, kernel: Linux x86 64-bit version 6.1.0-rc5
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS …
```
> mesa: update to 22.2.4

- packages/devel/cmake/package.mk
Release notes:
- https://cmake.org/cmake/help/v3.25/release/3.25.html
have been tracking this since rc1
> cmake: update to 3.25.0

- packages/sysutils/sed/package.mk
Doing a clean rebuild to test the Amlogic kernel bump the sed package download failed. This updates PKG_URL to a working one (also https).
> sed: update package URL

- packages/addons/addon-depends/system-tools-depends/depends/libmtp/package.mk
- packages/addons/addon-depends/system-tools-depends/efibootmgr/package.mk
- packages/addons/addon-depends/system-tools-depends/fdupes/package.mk
- packages/addons/addon-depends/system-tools-depends/file/package.mk
- packages/addons/addon-depends/system-tools-depends/inotify-tools/package.mk
- packages/addons/addon-depends/system-tools-depends/mmc-utils/package.mk
- packages/addons/addon-depends/system-tools-depends/st/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/addon-depends/system-tools-depends/unrar/package.mk
- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/graphics/kmsxx/package.mk
- efibootmgr: update to 18
- fdupes: update to 2.2.1
- file: update to 5.43
- inotify-tools: update to 3.22.6.0
- kmsxx: update to githash 2022-11-05
- libmtp: update to 1.1.20
- mmc-utils: update to 2022-11-09
- stress-ng: update to 0.14.06
- st: update to 0.9
- unrar: update to 6.2.2
- vim: update to 9.0.0905
> [le11] system-tools: update to addon (134)

- packages/network/iwd/package.mk
ver 2.0:
Fix issue with handling P2P and limiting ciphers to CCMP.
Fix issue with scanning before forced roaming action.
Fix issue with provided scan frequencies from RRM.
Fix issue with handling Michael MIC failure message.
Fix issue with handling timestamp size in MPDU frames.
Fix issue with handling enablement of OCVC for FT AKMs.
Fix issue with handling FT work as highest priority.
Fix issue with handling roaming events and Multi-BSS.
Add support for utilizing roaming candidates list.
Add support for utilizing TLS session caching.
Add support for ciphers with 256 bits key size.
Add support for Access Point mode with legacy TKIP.
Add support for MAC address changes while powered.
Add support for IPv4 and IPv6 network configuration.
> iwd: update to 2.0

- packages/graphics/gdk-pixbuf/package.mk
- packages/graphics/lcms2/package.mk
- packages/graphics/libheif/package.mk
- packages/graphics/pango/package.mk
- gdk-pixbuf: prevent downloading wrapped subprojects
- gdk-pixbuf: update to 2.42.10
- lcms2: update to 2.14
- libheif: update to 1.14.0
- pango: update to 1.50.12
> Graphics package updates 

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
Latest release notes:
- https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.11/6.0.11.md?WT.mc_id=dotnet-35129-website 
- https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> dotnet-runtime: Update ASP.NET 6.x to 6.0.11 and addon (125)

- packages/devel/flatbuffers/package.mk
- packages/devel/heimdal/package.mk
- packages/devel/libffi/package.mk
- packages/devel/mimalloc/package.mk
- packages/devel/mpfr/package.mk
- packages/devel/spdlog/package.mk
- packages/devel/swig/package.mk
- flatbuffers: update to 22.10.26
- heimdal: update to githash 2022-11-17
- libffi: update to 3.4.4
- mimalloc: update to 2.0.7
- mpfr: update to 4.1.1
- spdlog: update to 1.11.0
- swig: update to 4.1.0
> devel package updates

- packages/multimedia/ffmpeg/package.mk
- packages/multimedia/ffmpeg/patches/kodi/ffmpeg-001-kodi.patch
- tools/ffmpeg/gen-patches.sh
This is the patchset rework part of the ffmpeg 5.1.2 PR #7043 backported to ffmpeg 4.4.x
ffmpeg source code we build from is unchanged, but everything's now based on upstream ffmpeg and kodi patches are applied via a patchsets as well.
This allows us to easily drop kodi patches if they cause issues, update to a newer ffmpeg patchlevel release or test with newer ffmpeg versions.
I kept this simple and avoided any other changes / bumps so it's easy to review and verify if sources and generated patches are identical.
`tools/ffmpeg/gen-patches.sh rpi` will show there are updates available, I'll PR them separately
Diffing unpacked ffmpeg sources will show missing .gitignore / and .giitattributes files and a new VERSION file and different RELEASE - that's OK as that means our ffmpeg build will …
> ffmpeg: rework patchset handling

- packages/compress/zlib/package.mk
The http://zlib.net/zlib-VERSION link only works for the currently released version and break whenever zlib releases a new version (which happened twice this year). This is also problematic when building older LibreELEC versions as the older zlib can't be downloaded.
Switch PKG_URL to the tar.gz files at https://zlib.net/fossils/ as this location provides all (current and older) releases.
> zlib: fix download URL

- packages/audio/pipewire/package.mk
Release notes:
- https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.61
> pipewire: update to 0.3.61

- packages/sysutils/util-linux/package.mk
Release notes:
- https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/v2.38.1-ReleaseNotes
> util-linux: update to 2.38.1

- packages/wayland/libinput/package.mk
- packages/wayland/wayland-protocols/package.mk
Package updates:
- wayland-protocols: update to 1.30
- libinput: update to 1.22.0
> Wayland package updates

- packages/devel/glib/package.mk
Release notes:
- https://gitlab.gnome.org/GNOME/glib/-/releases
> glib: update to 2.75.0

- packages/addons/addon-depends/ccid/package.mk
- packages/addons/addon-depends/pcsc-lite/package.mk
- packages/addons/service/oscam/changelog.txt
- packages/addons/service/oscam/package.mk
- packages/addons/service/pcscd/changelog.txt
- packages/addons/service/pcscd/package.mk
Back port of:
- #7175 
package updates
- ccid: update to 1.5.1
- oscam: update to 11715 and addon (112)
- pcscd: update to addon (102)
- pcsc-lite: update to 1.9.9
> [le10] Addon updates - oscam and pcscd

- packages/sysutils/tz/package.mk
Back port of 
- #7183
release notes:
- https://mm.icann.org/pipermail/tz-announce/2022-November/000076.html
> [le10] tz: update to 2022g

- packages/graphics/nvidia/package.mk
-  tested with latest wayland + sway 1.8-rc1 = video decoding works fine
- release notes https://www.nvidia.com/Download/driverResults.aspx/193764/en-us/
- 525.60.11 was also released but broke nvidia-vaapi-driver decoding
> nvidia: update to 520.56.06

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://github.com/KhronosGroup/Vulkan-Docs/commit/db2b908b59b7774da9aa8b07baed4f5d018ae4d9
- vulkan-headers: update to 1.3.236
- vulkan-loader: update to 1.3.236
- vulkan-tools: update to 1.3.236
> Vulkan update to 1.3.236

- packages/audio/wavpack/package.mk
- packages/compress/xz/package.mk
- packages/devel/cmake/package.mk
- packages/devel/swig/package.mk
- packages/multimedia/libass/package.mk
- packages/sysutils/pciutils/package.mk
Package updates
- cmake: update to 3.25.1
- libass: update to 0.17.0
- pciutils: update to 3.9.0
- swig: update to 4.1.1
- wavpack: update to 5.6.0
- xz: update to 5.2.9
> Packages updates

- packages/multimedia/ffmpeg/package.mk
- license should match https://spdx.org/licenses/GPL-3.0-or-later.html or https://spdx.org/licenses/LGPL-3.0-or-later.html because of those configure [opts](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/multimedia/ffmpeg/package.mk#L157-L158)
> ffmpeg: clean up & change license to GPL-3.0-only

- packages/mediacenter/kodi/patches/kodi-100.01.fix-mesa-22.3.0-build.patch
- https://gitlab.freedesktop.org/mesa/mesa/-/commit/f5bb9dd738ace274c97507adea073b6c609469b2 removed eglextchromium.h
- fix for https://github.com/xbmc/xbmc/issues/21792 - we don't need checks for older mesa versions
> kodi: fix build with mesa 22.3.0

- config/functions
- config/path
- packages/devel/ccache/package.mk
- packages/devel/make/package.mk
- packages/readme.md
- scripts/build
In very early stages of the build we don't have ccache available in toolchain which means those packages will always have to be rebuilt on clean builds with hot ccache.
At the moment this isn't a big deal as only make and ccache are affected by that - and they build in a few seconds.
But this has changed drastically as more and more packages, like ccache 4, have dropped support for simple configure/make and now start to require cmake for configuring.
cmake, unfortunately, has become a monster and takes ages to build - about 7 minutes with all dependencies on my HP Z240 workstation - so when switching to ccache 4 this means every clean rebuild would take that hit.
To mitigate that let's add support for optionally building early stage packages with ccache from the build host:
Simply set …
> support early stage host package builds with ccache from buildhost

- config/options
- config/show_config
- distributions/LibreELEC/options
Use of ccache on build host is now controlled by the LOCAL_CCACHE_SUPPORT option. Setting it to "no" will disable use of local ccache.
> options: automatically use ccache on build host if it's available

- scripts/build
- reformatted the build timing details 
```
<<< edid-decode:target seq 184 <<<
UNPACK      edid-decode
BUILD      edid-decode (target)
TOOLCHAIN      make (auto-detect)
/mnt/dev/LibreELEC-RR/build.LibreELEC-RK3399.arm-11.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabihf-g++  -Wall  -Wl,--as-needed -fuse-ld=mold -g -DSHA=9ba4e90f3c07 -o edid-decode calc-gtf-cvt.cpp calc-ovt.cpp               edid-decode.cpp parse-base-block.cpp parse-cta-block.cpp               parse-displayid-block.cpp parse-ls-ext-block.cpp               parse-di-ext-block.cpp parse-vtb-ext-block.cpp -lm
Build timing details:
================================
unpack:      0.468
pre-build setup:      0.027
configure:      0.005
make:     13.671
make install:      0.018
copy sysroot:      0.036
cleanup install: …
```
> scripts/build: update TRACE_BUILD_TIMING

- packages/multimedia/SDL2/package.mk
- packages/sysutils/usbutils/package.mk
SDL2: update to 2.26.1
- https://github.com/libsdl-org/SDL/releases/tag/release-2.26.1
usbutils: update to 015
- log: https://github.com/gregkh/usbutils/compare/v014...v015
usbutils 015
============
Greg Kroah-Hartman (6):
usb-devices: list the root devices in numerical order
usb-devices: use 'local' variable type to handle recursion
lsusb: remove unused wireless check
lsusb: remove wireless descriptor information
usb-devices: fix field width on device speed field
lsusb: fix up Midi Device specification devices
Han Han (1):
Fix an runtime error reported by undefind sanitizer
Robert Hancock (1):
lsusb: Improve status display for SuperSpeedPlus hubs
Tan Li Boon (1):
lsusb-t: Fix recursive sorting on child devices.
> Minor package updates

- packages/addons/service/proftpd/package.mk
release notes:
- http://proftpd.org/docs/RELEASE_NOTES-1.3.8
news:
- http://proftpd.org/docs/NEWS-1.3.8
webpage:
- http://proftpd.org/
includes the change of pcre to pcre2 
- #6798
> [le11] proftpd: update to 1.3.8 and addon (1)

- packages/addons/service/syncthing/package.mk
Release notes:
- update from 1.22.0 to 1.22.2
- https://github.com/syncthing/syncthing/releases
> [le11] syncthing: update to 1.22.2 and addon (1)

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
https://github.com/KhronosGroup/Vulkan-Docs/commit/0e28607b55dc1eee4ff80967f1e0a7e99356d075
- vulkan-headers: update to 1.3.237
- vulkan-loader: update to 1.3.237
- vulkan-tools: update to 1.3.237
> Vulkan: update to 1.3.237

- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/chrome-depends/libXScrnSaver/package.mk
- packages/addons/addon-depends/chrome-depends/libXft/package.mk
- packages/addons/addon-depends/chrome-depends/libxss/package.mk
- packages/x11/app/xkbcomp/package.mk
- packages/x11/app/xrandr/package.mk
- packages/x11/lib/libICE/package.mk
- packages/x11/lib/libXau/package.mk
- packages/x11/lib/libXcomposite/package.mk
- packages/x11/lib/libXdamage/package.mk
- packages/x11/lib/libfontenc/package.mk
- packages/x11/lib/libxkbfile/package.mk
- packages/x11/lib/libxshmfence/package.mk
- at-spi2-core: update to 2.46.0 and https
- gtk3: update to 3.24.35
- libICE: update to 1.1.1 and https
- libXau: update to 1.0.11
- libXcomposite: update to 0.4.6 and https
- libXdamage: update to 1.1.6 and https
- libXft: update to 2.3.6 and https
- libXScrnSaver: update to 1.2.4
- libfontenc: update to 1.1.7
- libxkbfile: update to 1.1.2
- libxshmfence: update to 1.3.2
- libxss: update to 1.2.4
- xkbcomp: update to 1.4.6 and https
- xrandr: update to 1.5.2 and https
> X11 updates

- packages/x11/lib/libICE/package.mk
- packages/x11/lib/libSM/package.mk
- packages/x11/lib/libXcomposite/package.mk
- packages/x11/lib/libXdamage/package.mk
- packages/x11/lib/libXfixes/package.mk
- packages/x11/lib/libXi/package.mk
- packages/x11/lib/libXrender/package.mk
- packages/x11/lib/libXtst/package.mk
- packages/x11/lib/libxshmfence/package.mk
- libXcomposite by xf86-video-intel & xorg-server
- libXdamage by xf86-video-intel & mesa
- libXfixes by mesa, libva, libXcomposite, libXdamage, libXi
- (...)
And all will be used by Chrome so it makes sense to build them shared instead static. In a follow up PR the chrome dependencies can be cleaned up.
> X11: build shared and/or enable position independent code (pic)

- packages/addons/addon-depends/chrome-depends/chrome-libXcomposite/package.mk
- packages/addons/addon-depends/chrome-depends/chrome-libXdamage/package.mk
- chrome-libXcomposite: fix source file name from bz2 to xz
- chrome-libXdamage: fix source file name from bz2 to xz
> Fix Chrome addon build due to file name changes bz2 to xz 

- packages/graphics/mesa/package.mk
ann:
- https://lists.freedesktop.org/archives/mesa-dev/2022-December/225902.html
```
Generic.x86_64-devel-20221215102014-d77dc53
Linux nuc12 6.1.0 #1 SMP Thu Dec 15 10:23:51 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-RC1 (19.90.901) Git:20.0rc1-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-12-12 by GCC 12.2.0 for Linux x86 64-bit version 6.1.0 (393472)
Running on LibreELEC (heitbaum): devel-20221215102014-d77dc53 11.0, kernel: Linux x86 64-bit version 6.1.0 …
```
> mesa: update to 22.3.1

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Ann:
- https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html
> rust: update to 1.66.0

- packages/devel/boost/package.mk
- packages/tools/qemu/package.mk
- boost: update to 1.81.0
- https://www.boost.org/users/history/version_1_81_0.html
- qemu: update to 7.2.0
- https://www.qemu.org/2022/12/14/qemu-7-2-0/
> qemu and boost package updates

- packages/textproc/nlohmann-json/package.mk
- the meson build is rather incomplete & not all packages were satisfied by a pkgconfig file which it provides, those looking for cmake config files e.g by calling `find_package(nlohmann_json 3.8 REQUIRED)` will fail because they rely on `nlohmann_jsonConfig.cmake` `nlohmann_jsonConfigVersion.cmake` `nlohmann_jsonTargets.cmake` located in `/usr/share/cmake/nlohmann_json` which meson does not provide.
- both binary addons `pvr.freebox` & `pvr.freebox` depend on the package were successfully build
- reverts https://github.com/LibreELEC/LibreELEC.tv/commit/4a32a3ded67617cd6b16251c020d00df4ec31d5f
> nlohmann-json: use cmake toolchain

- packages/graphics/vulkan/vulkan-loader/package.mk
- fixes build failure, if Xrandr.h headers is missing for X11 builds:
```
[1/20] Building C object loader/CMakeFiles/asm_offset.dir/asm_offset.c.o
FAILED: loader/CMakeFiles/asm_offset.dir/asm_offset.c.o 
/mnt/build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -DAPI_NAME=\"Vulkan\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DHAVE_ALLOCA_H -DHAVE_CET_H -DHAVE_SECURE_GETENV -DLOADER_ENABLE_LINUX_SORT -DSYSCONFDIR=\"/etc\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -D_GNU_SOURCE -I/mnt/build/LibreELEC-RR/build.LibreELEC-x11.x86_64-11.0-devel/build/vulkan-loader-1.3.237/loader …
```
> vulkan-loader: add libXrandr dependency to fix X11 build

- packages/network/ethtool/package.mk
- packages/network/iwd/package.mk
iwd: update to 2.1
- Fix issue with handling FT-over-DS action.
- Fix issue with handling scan and 6 GHz support check.
- Fix issue with handling when periodic scans get aborted.
- Add support for using 5 GHz frequencies in AP mode.
log:
ethtool: update to 6.1
- December 19, 2022
* Feature: update link mode tables
* Feature: register dump for NXP ENETC driver (-d)
* Feature: report TCP header-data split (-g)
* Feature: support new message types in pretty print
* Fix: fix compiler warnings
* Fix: man page syntax fixes
log:
- https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/log/
> iwd: update to 2.1 and ethtool: update to 6.1

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
- dotnet-runtime: Update ASP.NET 6.x to 6.0.12 and addon (1)
- aspnet6-runtime: update to 6.0.12 
Backport of 
- #7248
> [le10] dotnet-runtime: Update ASP.NET 6.x to 6.0.12 and addon (124)

- packages/graphics/mesa/package.mk
-  we only need libglvnd to make mesa work along nvidia drivers so only depend & enable libglvnd in mesa if they are enabled in `GRAPHIC_DRIVERS` otherwhise libglvnd would be build e.g. for RK3399 if you would test wayland builds
> mesa: enable/depend on libglvnd only for nvidia drivers

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/service/docker/package.mk
- packages/addons/service/docker/source/bin/docker-config
- packages/addons/service/docker/source/config/docker.conf
- cli: update to 23.0.0-beta.1
- docker: update to 23.0.0-beta.1 and addon (2)
- moby: update to 23.0.0-beta.1
- docker: update docker.conf
```
Client:
Version:           23.0.0-beta.1
API version:       1.42
Go version:        go1.19.4
Git commit:        65d3f7830d8f73aeabe649ca17386f5ae5655210
Built:             Sat Dec 17 20:45:32 UTC 2022
OS/Arch:           linux/amd64
Context:           default
Server:
Engine:
Version:          library-import
API version:      1.42 (minimum version 1.12)
Go version:       go1.19.4
Git commit:       library-import
Built:            library-import
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.6.13
GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
runc:
Version:          1.1.4
GitCommit: …
```
> docker: update to 23.0.0-beta.1 and addon (2)

- packages/addons/tools/btrfs-progs/package.mk
- packages/graphics/libraw/package.mk
- packages/mediacenter/kodi-binary-addons/imagedecoder.raw/package.mk
- imagedecoder.raw: rebuild with libraw 0.21.0 and addon (4)
- btrfs-progs: update to 6.1 and addon (1)
- libraw: update to 0.21.0 and HSTS
> [le11] Addon updates

- packages/devel/glib/package.mk
log:
- https://gitlab.gnome.org/GNOME/glib/-/releases
- (Bug fix release)
> glib: update to 2.75.1

- packages/devel/mold/package.mk
- packages/devel/tbb/package.mk
update to mold 1.8.0 and oneTBB 2021.8 instead of the upstream patch
~~Compiling mold 1.7.1 fails during link stage~~
~~fixes:
/usr/bin/ld: build.LibreELEC-yyy/toolchain/lib/libcrypto.a(libcrypto-lib-threads_pthread.o):
undefined reference to symbol 'pthread_rwlock_destroy@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status~~
~~Upstream mold bugfix to cmake file~~
- ~~https://github.com/rui314/mold/issues/924~~
- ~~https://github.com/rui314/mold/commit/a3a98ac5f581c450756147a043589764625499fc~~
> mold: fix pthread DSO build error

- packages/graphics/mesa/package.mk
- build codecs for vc1dec, h264dec, h264enc, h265dec, h265enc
- https://www.phoronix.com/news/Mesa-Optional-Video-Codecs
I guess this should fix https://github.com/LibreELEC/LibreELEC.tv/issues/7278
> mesa: enable video-codecs

- packages/wayland/compositor/sway/package.mk
- packages/wayland/compositor/sway/patches/sway-100.02-allow-running-as-root.patch
- packages/wayland/compositor/sway/patches/sway-100.03-do-not-use-git-version.patch
- packages/wayland/lib/hwdata/package.mk
- packages/wayland/lib/wlroots/package.mk
- packages/wayland/util/swaybg/package.mk
- hwdata: initial package
- dependency for wlroots, they have moved the pci.ids out of the wlroots
- https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/eec95e3d5e1a4f2e13b1f6b34cc287475ca57daf
- wlroots: update to 0.16.1
- swaybg: update to 1.2.0
- sway: update to 1.8
> wlroots 0.16.1 and 1.8 sway updates

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.1
6.1.1 - 25 patches
-
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.1.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.1.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.1
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux …
```
> linux: update to 6.1.y

- packages/databases/sqlite/package.mk
release log:
- https://www.sqlite.org/releaselog/3_40_1.html
Additional changes in version 3.40.1 (2022-12-28):
- Fix the --safe command-line option to the CLI such that it correctly disallows the use of SQL functions like writefile() that can cause harmful side-effects.
- Fix a potential infinite loop in the memsys5 alternative memory allocator. This bug was introduced by a performance optimization in version 3.39.0.
- Various other obscure fixes.
> sqlite: update to 3.40.1

- packages/graphics/mesa/package.mk
ann:
- https://lists.freedesktop.org/archives/mesa-dev/2022-December/225903.html
```
Generic.x86_64-devel-20221230042649-3bed528
Linux nuc12 6.1.2-rc1 #1 SMP Thu Dec 29 07:33:53 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-RC2 (19.90.905) Git:20.0rc2-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2022-12-28 by GCC 12.2.0 for Linux x86 64-bit version 6.1.1 (393473)
Running on LibreELEC (heitbaum): devel-20221230042649-3bed528 11.0, kernel: Linux x86 64-bit version 6.1.2-rc1 …
```
> mesa: update to 22.3.2

- packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk
- packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk
- packages/addons/tools/network-tools/package.mk
- libpcap: update to 1.10.2 and HSTS
- https://git.tcpdump.org/libpcap/blob/HEAD:/CHANGES
- tcpdump: update to 4.99.2 and HSTS
- https://git.tcpdump.org/tcpdump/blob/HEAD:/CHANGES
- https://www.tcpdump.org/index.html#latest-releases
> [le11] network-tools: update addon (1)

- packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk
- packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk
- packages/addons/tools/network-tools/changelog.txt
- packages/addons/tools/network-tools/package.mk
- libpcap: update to 1.10.2 and HSTS
- https://git.tcpdump.org/libpcap/blob/HEAD:/CHANGES
- tcpdump: update to 4.99.2 and HSTS
- https://git.tcpdump.org/tcpdump/blob/HEAD:/CHANGES
- https://www.tcpdump.org/index.html#latest-releases
- Backport of #7325
> [le10] network-tools: update addon (120)

- packages/network/connman/package.mk
This bumps the connman version for LE10 to current. I've been running the current connman version in my private LE10 image with periodic updates for a long time without issues; and if you go back through the (now lengthy) commits list this probably resolves some 'cannot connect' issues we see in occasional forum posts. We are using something much more current in master too.
The second commit allows ethernet tethering to be enabled from connmanctl without having to change the connman configuration. Using a reverse tether (sharing WiFi via Ethernet) is not exposed in the GUI so there is no change to the user experience (maybe in the future).
I will send a forward-port PR for both to master.
> connman: minor changes

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/multimedia/bento4/package.mk
Update Bento4 to match version used in inputstream.adaptive tree: https://github.com/xbmc/inputstream.adaptive/blob/20.3.1-Nexus/depends/common/bento4/bento4.txt
Update commit log: https://github.com/xbmc/Bento4/compare/1.6.0-639-Nexus...1.6.0-639-4-Nexus
The update should resolve a crash in inputstream.adaptive, so bump its PKG_REV.
> bento4: update to 1.6.0-639-4-Nexus

- packages/python/system/dbussy/package.mk
commit log:
- Threads for async calls should be daemon threads.
- https://github.com/ldo/dbussy/commit/691a8a8a1914416b7ea1545fb931d74f2e381f09
> dbussy: update to githash 691a8a8a 2022-12-21

- packages/lang/Python3/patches/Python3-0600-pyexpat_revert_24061.patch
cpython's _elementtree.c can crash kodi by using addons, see https://github.com/xbmc/xbmc/issues/22344.
Revert causing commit until it is fixed upstream.
Upstream issue is https://github.com/python/cpython/issues/100689
> Python3: fix elementtree crash in 3.10ff

- packages/audio/libcdio/patches/0001-Use-getmntent-setmntent-for-reading-mounts.patch
Cherry-pick commit 0d550dc93 from upstream to decode fstab style path.. This fixes kodi eject failing on DVD with spaces in their titles.
Signed-off-by: Alban Browaeys <alban.browaeys@gmail.com>
-------------------
Picked from upstream commit https://git.savannah.gnu.org/cgit/libcdio.git/commit/?id=0d550dc9307901edd817333a5b530241d08ad889 . It is not in a libcdio release yet, then this patch will have to be removed and the libcdio upped.
> libcdio: add patch to fix cdio eject media when path has spaces

- packages/python/system/simplejson/package.mk
minor fix: rest is cosmetic.
Remove unnecessary `i` variable from encoder module namespace
https://github.com/simplejson/simplejson/pull/303
release notes:
- https://github.com/simplejson/simplejson/releases/tag/v3.18.1
log:
- https://github.com/simplejson/simplejson/compare/v3.18.0...v3.18.1
> simplejson: update to 3.18.1

- packages/sysutils/lirc/patches/0006-lirc-gpio-ir-0.10.patch
- packages/sysutils/lirc/patches/lirc-0101-kernel-5.18-fix.patch
This is a backport of https://github.com/LibreELEC/LibreELEC.tv/pull/6419 which I should have PR'ed about half a year ago but somehow managed to slip through.
The Debian gpio-ir patch fixes irrecord not working properly with 5.10 (and later kernels)
> [le10] lirc: backport fixes from master

- packages/tools/rpi-eeprom/package.mk
This is a backport of LE master and updates rpi-eeprom to the latest default version (2022-12-07)
> [le10] update rpi-eeprom to latest default version

- packages/addons/service/nextpvr/changelog.txt
- packages/addons/service/nextpvr/package.mk
- packages/addons/service/nextpvr/source/bin/nextpvr-downloader
- packages/addons/service/nextpvr/source/settings-default.xml
Kodi doesn't pass environment variables to the startup script unless the user saves a configuration via settings configuration, even if it is defaults.  The service starts before the user has a chance to save settings and the setting for the NextPVR service are optional.
<del>Ideally Kodi should pass the default values from the global settings.xml</del>  
As pointed out by @mglae the reason for this issue is the addon wasn't including settings-default.xml.  This PR adds the required file.
> nextpvr: add default settings file

- packages/debug/libva-utils/package.mk
- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
media-driver: update to 22.6.6
- 1 revert for Discrete Intel DG/ARC cards
- https://github.com/intel/media-driver/commit/3c2063c6af0c2d2f994d79957a67bde978c722ec 
- https://github.com/intel/media-driver/compare/intel-media-22.6.5...intel-media-22.6.6
gmmlib: update to 22.3.3
- https://github.com/intel/gmmlib/compare/intel-gmmlib-22.3.2...intel-gmmlib-22.3.3
libva-utils: update to 2.17.1
- https://github.com/intel/libva-utils/compare/2.17.0...2.17.1
> Intel Updates (minors)

- tools/change_addon_version
Adds a tool to bump the addon version of the distribution and cleaning up all changelogs and resets the PKG_REVs. After that it created the nessesary git commits. This tool is just intended to use for the master branch.
It is written with whiptail to make it userfriendly. No idea if this creates a problem for other distros that are not debians.
> tool to change addon version

- packages/devel/libbpf/package.mk
- packages/devel/libbpf/patches/libbpf-fix-crosscompile-and-sysroot.patch
release notes:
- https://github.com/libbpf/libbpf/releases/tag/v1.1.0
- https://github.com/libbpf/libbpf/compare/v1.0.1...v1.1.0
@HiassofT - I had not planned to PR this for LE11 - but in review of changelog and kernel support …. Do we require this. Or add to LE12 queue?
> libbpf: update to 1.1.0

- packages/addons/addon-depends/go/package.mk
Release notes
- https://go.dev/doc/devel/release#go1.19.minor
> go: update to 1.19.5

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
release notes:
- https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1661-2023-01-10
- https://blog.rust-lang.org/2023/01/10/Rust-1.66.1.html
> rust: update to 1.66.1

- packages/linux-firmware/wlan-firmware/package.mk
- projects/Allwinner/patches/linux/0101-Bluetooth-Add-new-quirk-for-broken-local-ext-features.patch
- projects/Allwinner/patches/linux/0102-Bluetooth-btrtl-Add-support-for-RTL8822BS-UART.patch
- projects/Allwinner/patches/linux/0103-arm64-dts-allwinner-h6-tanix-tx6-Add-compatible-blue.patch
- projects/Allwinner/patches/linux/0104-Bluetooth-btrtl-set-HCI_QUIRK_BROKEN_LOCAL_EXT_FTR_M.patch
Found in some variants of Tanix TX6
Before:
[    7.512876] rtw_8822bs mmc2:0001:1: Firmware version 27.2.0, H2C version 13
[    8.219545] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    8.430833] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    8.430866] Bluetooth: hci0: RTL: unknown IC info, lmp subver 8822, hci rev 000b, hci ver 0007
After:
[    8.958224] rtw_8822bs mmc2:0001:1: Firmware version 27.2.0, H2C version 13
[    9.017294] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    9.021399] Bluetooth: hci0: RTL: rom_version status=0 version=2
[    9.021428] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822bs_fw.bin
[    9.024180] Bluetooth: hci0: RTL: loading …
> linux (Allwinner): Bluetooth: btrtl: Add support for RTL8822BS UART

- packages/linux-firmware/wlan-firmware/package.mk
Previous wlan-firmware repo had the rtl_bt in the wrong directory.
- https://github.com/LibreELEC/wlan-firmware/pull/11
- Run tested
> wlan-firmware: update rt_btl

- packages/sysutils/systemd/package.mk
With kernel 6.0 the legacy efi vars interface at /sys/firmware/efi/vars was removed (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?h=v6.0&id=0f5b2c69a4cbe4166ca24b76d5ada98ed2867741).
The efibootmgr tool requires now to mount the efivarfs pseudo-filesystem on /sys/firmware/efi/efivars. Enabling upstream EFI support for systemd is the easiest way to get it mounted on EFI systems but still having correct (non-)support for legacy boot.
No additional files are added to the image.
> systemd: build with -Defi=true on Generic

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
brcmfmac_sdio-firmware: update to githash 59fe14f (2023-01-16)
> brcmfmac_sdio-firmware: update to githash 59fe14f (2023-01-16)

- packages/lang/llvm/package.mk
- packages/lang/llvm/patches/llvm-15.0.0-D108864-misleading-indentation.patch
add patch to "not warn" during build for missing indentation.
- https://reviews.llvm.org/D108864
release notes
- https://discourse.llvm.org/t/llvm-15-0-7-release/67638
> llvm: update to 15.0.7

- packages/security/nss/package.mk
Release notes:
- https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_87.html
> nss: update to 3.87

- packages/addons/service/tvheadend42/package.mk
- Fixes #7400 
- Was originally fixed in #5623
- but only for tvheadend43
> [le11] tvheadend42: rebuild missing library and addon (2)

- packages/addons/service/tvheadend42/changelog.txt
- packages/addons/service/tvheadend42/package.mk
- Fixes #7400 
- Was originally fixed in #5623
- but only for tvheadend43
- backport of #7402
> [le10] tvheadend42: rebuild missing library and addon (127)

- config/functions
When creating a debug image with `DEBUG=yes` the debug symbols are missing for kodi.
Dependency base packages like "kodi+" have to be matched in build_with_debug().
> functions: fix build_with_debug() to include dependency base packages like "kodi+"

- packages/tools/installer/scripts/installer
Installer failure was reported with logs in the [forum](https://forum.libreelec.tv/thread/26485-unable-to-install-no-devices-x86-64l). Fixes #7380
Failing on e.g. "/dev/sda:512GB:scsi:512:512:gpt:ATA Samsung SSD 850:pmbr_boot;"
Fixed by only matching the device name when removing rpmb and boot devices
RE was added for MMC support in #9d1d032 and removes special MMC areas like /dev/mmcblk0rmpb or /dev/mmcblk0boot1
> installer: fix device detection with pmbr_boot flag set

- projects/ARM/options
- projects/Allwinner/options
- projects/Amlogic/options
- projects/Generic/options
- projects/RPi/options
- projects/Rockchip/options
- projects/Samsung/options
Some project's option files do erase ADDITIONAL_DRIVERS and/or ADDITIONAL_PACKAGES.
Packages RTL8192DU and  RTL8812AU of ADDITIONAL_DRIVERS are not build on these projects. Furthermore  ADDITIONAL_PACKAGES cannot be used in distribution either.
Fixes #7375
> options: allow using  ADDITIONAL_DRIVERS and ADDITIONAL_PACKAGES of distribution

- packages/debug/xorg-intel-gpu-tools/package.mk
Release 1.27.1 (2023-01-18)
-------------------------
- Removed gcc option -fcommon from meson.build and fix broken build on Linux RedHat platform. (Zbigniew Kempczyński)
- Updated CONTRIBUTING guidelines for interface deprecation. (Petri Latvala)
- Fixed one additional test bug (Zbigniew Kempczyński)
ref:
- https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/commit/2b29e8ac07fbcfadc48b9d60e4d736a6e3b289ab
> xorg-intel-gpu-tools: update to 1.27.1

- packages/graphics/bcm2835-driver/package.mk
- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
Default bootloader version now contains VL805 firmware fixes and HID fixes
> linux (RPi): update to 6.1.7

- packages/tools/rpi-eeprom/package.mk
It's redundant and causes merge issues with other projects
Signed-off-by: Demetris Ierokipides <ierokipides.dem@gmail.com>
> rpi-eeprom: clean pkg arch restictions

- packages/linux/package.mk
This should fix two long standing issues:
- occasional glitches at the bottom of the screen
- no picture after boot on some TVs
> linux (RPi): update to 6.1.8

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- packages/wayland/util/wlr-randr/package.mk
- glslang: update to 12.0.0
- gst-plugins-bad: update to 1.22.0
- gst-plugins-base: update to 1.22.0
- gstreamer: update to 1.22.0
- spirv-headers: update to d13b522
- spirv-tools: update to 63de608
- vulkan-headers: update to 1.3.239
- vulkan-loader: update to 1.3.239
- vulkan-tools: update to 1.3.239
- wlr-randr: update to 0.3.0
- https://git.sr.ht/~emersion/wlr-randr/log
- https://git.sr.ht/~emersion/wlr-randr/refs/v0.3.0
> gstreamer and vulkan updates

- packages/audio/pipewire/package.mk
Log
- https://github.com/PipeWire/pipewire/compare/0.3.64...0.3.65
News
- https://github.com/PipeWire/pipewire/blob/master/NEWS
> pipewire: update to 0.3.65

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.5.html
> samba: update to 4.17.5

- packages/mediacenter/kodi/patches/kodi-100.40-estuary-settings-icon.patch
This relocates the LE settings icon from it's current awkward position on the fourth row to top-right, displacing the event viewer which has never shown any interesting or useful content, at least for me, and restoring a 3x3 grid layout:
> kodi: move settings icon in estuary

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/package.mk
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
- aspnet6-runtime: update to 6.0.13
- dotnet-runtime: Update ASP.NET 6.x to 6.0.13 and addon (1)
> [le11] dotnet-runtime: Update ASP.NET 6.x to 6.0.13 and addon (1)

- packages/network/iwd/package.mk
ver 2.2:
+	Fix issue with handling FT and multiple roaming scans.
+	Fix issue with handling multiple wiphy registrations.
+	Fix issue with with EAP-PEAP session resumption.
+	Add support for using PTK rekeying in AP mode.
+	Add support for setting country IE in AP mode.
+	Add support for setting WMM parameter IE in AP mode.
> iwd: update to 2.2

- packages/network/iwd/patches/iwd-0001-wiphy-Fix-buffer-overflow-due-to-off-by-one-error.patch
Able to reproduce both the error and can confirm the fix.
Fixes: https://forum.libreelec.tv/thread/26531-wi-fi-usb-ralink-rt2870f-not-work-on-last-nightly-rpi4/?postID=176217#post176217
Patch from: https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=54a06835580bc4e15c453ee87db8c14655e900ef
Fix malloc error as below (introduced in iwd 2.2.)
```
Wireless daemon version 2.2
iwd-2.2/src/main.c:main() Using configuration directory /etc/iwd iwd-2.2/src/storage.c:storage_create_dirs() Using state directory /var/lib/iwd iwd-2.2/src/main.c:nl80211_appeared() Found nl80211 interface iwd-2.2/src/module.c:iwd_modules_init()
station: Network configuration is disabled.
iwd-2.2/src/wsc.c:wsc_init()
iwd-2.2/src/knownnetworks.c:known_network_frequencies_load() No known frequency file found. …
```
> iwd: Fix buffer overflow due to off-by-one error

- packages/network/connman/package.mk
iwd fixes:
- service: Fix an additional case of autoconnect breakage under iwd
- iwd : fix iwd autoconnect being set wrongly on new connections
- iwd: Fix typo in create_known_network name
- iwd: Rename autoconnect fields to clarify meaning
log:
- https://git.kernel.org/pub/scm/network/connman/connman.git/
> connman: update to 1.41 + HEAD 2023-01-16

- tools/docker/focal/Dockerfile
use recent release of golang for bootstrap builds. 
- updates from golang-1.13 to golang-1.18
> tools/docker: update focal/Dockerfile to install golang-1.18

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/cli/patches/cli-0001-path-for-cli-plugins.patch
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/service/docker/package.mk
- docker: update to 23.0.0 and addon (2)
- https://github.com/moby/moby/releases/tag/v23.0.0
- cli: update to 23.0.0
- cli: update path for cli-plugins for LibreELEC image
- moby: update to 23.0.0
- containerd: update to 1.6.16
> docker: update to 23.0.0 and addon (2)

- packages/addons/tools/system-tools/changelog.txt
- packages/addons/tools/system-tools/package.mk
- packages/graphics/kmsxx/package.mk
- packages/mediacenter/kodi/scripts/pastekodi
- packages/virtual/debug/package.mk
modetest output is practically unreadable for normal users and also way too chatty to be included in pastekodi - which makes it hard to debug "no display after boot" issues.
kmsprint however produces nice, terse output which is also something normal users can cope with, gives us some useful information to point users in the right direction (eg wrong HDMI port used, no display detected, or odd weird non-default mode set) and it's short enough to be included in pastekodi logs.
eg here on RPi4:
```
LibreELEC:~ # modetest | wc
2913      8204     79487
LibreELEC:~ # kmsprint | wc
7        82       489
LibreELEC:~ # kmsprint
Connector 0 (32) HDMI-A-1 (connected)
Encoder 0 (31) TMDS
Crtc 3 (96) 1920x1200@59.95 154.000 1920/48/32/80/+ 1200/3/6/26/- 60 (59.95) P|D 
Plane 6 (119) fb-id: 344 (crtcs: …
```
> move kmsxx from addon to image and include kmsprint output in pastekodi log

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rust/patches/rust-0001-105624.patch
- packages/rust/rustc-snapshot/package.mk
Rust toolchain only used for addons
- rust: update to 1.67.0
- rustc-snapshot: update to 1.67.0
- rust-std-snapshot: update to 1.67.0
- cargo-snapshot: update to 1.67.0
> rust: update to 1.67.0

- packages/tools/atf/package.mk
- projects/Allwinner/patches/atf/0003-sunxi-Don-t-enable-referenced-regulators.patch
Now that boot issue found on boards without PMIC is solved, let's re-introduce workaround for OrangePi 3 network instead of keeping all regulators off. It turns out that there is Beelink GS1 variant which need enabling regulators in ATF. Workaround will still keep OrangePi 3 board happy.
> Allwinner: atf: Revert to old workaround

- packages/security/openssl/package.mk
- 07-Feb-2023 | Security Advisory: one high and seven moderate severity fixes
- 07-Feb-2023 | OpenSSL 3.0.8 is now available, including bug and security fixes
- https://www.openssl.org/news/secadv/20230207.txt
> openssl: update to 3.0.8

- packages/graphics/mesa/package.mk
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.3/docs/relnotes/22.3.5.rst
```
Generic.x86_64-devel-20230209100207-8c26779
Linux nuc12 6.1.11-rc1 #1 SMP Thu Feb  9 10:03:09 UTC 2023 x86_64 GNU/Linux
Starting Kodi (20.0 (20.0.0) Git:20.0-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2023-02-08 by GCC 12.2.0 for Linux x86 64-bit version 6.1.11 (393483)
Running on LibreELEC (heitbaum): devel-20230209100207-8c26779 11.0, kernel: Linux x86 64-bit version 6.1.11-rc1
CApplication::CreateGUI - trying to init gbm windowing …
```
> mesa: update to 22.3.5

- packages/graphics/libdrm/package.mk
mostly AMD fixes & an Intel tidy up.
log:
- https://gitlab.freedesktop.org/mesa/drm/-/compare/libdrm-2.4.114...libdrm-2.4.115?from_project_id=177&straight=false
> libdrm: update to 2.4.115

- packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk
Minors:
- https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/log/?h=v1.6.x
Bug fixes:
- fix a typo in bats dependency test
- fix an unterminated double quote in configure
- fix a null-pointer dereference in error path in tests
- fix a build issue related to the AM_PATH_PYTHON() automake macro
Improvements:
- check for the timeout program before running the gpio-tools tests
> libgpiod: update to 1.6.4

- packages/databases/mariadb-connector-c/package.mk
release notes:
- https://mariadb.com/kb/en/mariadb-connector-c-3-3-4-release-notes/
changelog
- https://mariadb.com/kb/en/mariadb-connector-c-3-3-4-changelog/
> mariadb-connector-c: update to 3.3.4

- packages/linux-firmware/kernel-firmware/package.mk
- packages/linux/patches/default/linux-122-rtw88-USB-fixes.patch
- linux: rtw88: upstream patches
- https://forum.libreelec.tv/thread/23001-0bda-b812-rtl88x2bu-kernel-module/?postID=176876#post176876
- kernel-firmware: update to 20230210
- Includes 8822cs Firmware version 9.9.14 - as below
```
LibreELEC:~ # dmesg | grep -e rtw -e wlan -e hci0 -e 6.1.11
[    0.000000] Linux version 6.1.11 (docker@ed6f8f34d420) (aarch64-none-elf-gcc-12.2.0 (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39) #1 SMP PREEMPT Sat Feb 11 04:18:21 UTC 2023
[    0.000000] Machine model: Tanix TX6
[    3.236950] kernel-overlays-setup: added modules from /usr/lib/kernel-overlays/base/lib/modules/6.1.11
[    9.345695] rtw_8822bs mmc1:0001:1: Firmware version 27.2.0, H2C version 13
[    9.372739] Bluetooth: …
```
> kernel firmware and rtw88 upstream patches

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
- Include: https://github.com/LibreELEC/brcmfmac_sdio-firmware/pull/33
> brcmfmac_sdio-firmware: update to githash c70355f9 (2023-02-11)

- packages/tools/atf/package.mk
- projects/Rockchip/README.md
- projects/Rockchip/bootloader/firmware
- projects/Rockchip/bootloader/install
- projects/Rockchip/bootloader/mkimage
- projects/Rockchip/bootloader/update.sh
- projects/Rockchip/devices/RK3288/filesystem/usr/bin/cputemp
- projects/Rockchip/devices/RK3288/filesystem/usr/bin/gputemp
- projects/Rockchip/patches/linux/default/linux-1002-for-libreelec.patch
- scripts/image
- when copying files to the filesystem in `scripts/image` form PROJECT/DEVICE eventually existing symlinks aren't replaced (which is caused by the necessary `-P` option) - I added `--remove-destination` to `cp` to make sure they replaced as expected. That might be needed in other places, too.
- fixed thermal_zone numbers for RK3288
- dropped a no-longer required panfrost patch for Rockchip
- atf package will now use ATF_PLATFORM instead of PROJECT/DEVICE for platform specific quirks in package.mk
- replaced options for `dd` in Rockchip bootloader scripts used in order to speedup writing the bootloader. thanks for the hint @kwiboo
- allow `ROCKCHIP_LEGACY_BOOT` (used for boards w/o upstream u-boot support or known to have Android preinstalled) to passed from command line when building and …
> Rockchip: fixes/improvements

- packages/mediacenter/kodi/patches/kodi-995.11-smbc_getxattr.patch
Since a couple of days I noticed strange errors in kodi.log when accessing files from my NAS via Samba:
```
2023-02-02 18:22:41.039 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Doctor%20Who'
unix_err:'5f' error: 'Operation not supported' return: 0
2023-02-02 18:22:41.044 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Frieden%20(2020)'
unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.048 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Mum'
unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.053 T:1091    error <general>: Getting extended attributes for the …
```
> kodi: fix for changed return value of smbc_getxattr() for Samba >= 4.17.5

- packages/addons/service/mariadb/package.mk
ann:
- https://mariadb.org/mariadb-10-11-2-ga-now-available/
- [MariaDB Server 10.11.2](https://mariadb.com/kb/en/mariadb-10-11-2-release-notes/), is the first GA release of the MariaDB 10.11 series, a Long Term Support release.
release notes:
- https://mariadb.com/kb/en/mariadb-10-11-2-release-notes/
changelog:
- https://mariadb.com/kb/en/mariadb-10-11-2-changelog/
what is mariadb 10.11:
- https://mariadb.com/kb/en/changes-improvements-in-mariadb-1011/
n
> mariadb: update to 10.11.2 and addon (2)

- packages/audio/pipewire/package.mk
Release notes:
- https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/08b0ed65765a1033424a5c0d897a392a61f8a2a3
> pipewire: update to 0.3.66

- projects/Rockchip/patches/u-boot/0001-202301-arm-rockchip-rk3399-Program-PLL-clock-for-DDR-at-50-.patch
This adds a backport of a u-boot patch which is included 2023.01: DRAM initialization might fail for RK3399, because initial PLL settings are inexact. This patch fixes it.
On my side, I can't reproduce, but it might help for other (LP)DDR4 boards.
> Rockchip: RK3399: u-boot: backport 2023.01 patch 

- packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20230214
tested with:
```
Before
[    0.000000] microcode: microcode updated early to revision 0x424, date = 2022-09-19
After
[    0.000000] microcode: microcode updated early to revision 0x429, date = 2023-01-11
[    0.163557] smpboot: CPU0: 12th Gen Intel(R) Core(TM) i7-1260P (family: 0x6, model: 0x9a, stepping: 0x3)
```
> intel-ucode: update to 20230214

- packages/network/wireless-regdb/package.mk
log:
- https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git
> wireless-regdb: update to 2023.02.13

- config/optimize
Since gcc 11 -gsplit-dwarf no longer implicitly enables -g and needs a separate -g option. For some yet unknown reasons the default DWARF 5 format doesn't work, gdb doesn't show debug info, but DWARF 4 works fine so use that.
> Fix missing symbols when building with split debug info

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
v20.3.4 (2023-02-23)
overhaul url utils to follow RFC 3986
[Debug] option to save manifests to disk for debugging purposes
[DRM] fix bug when supplying license_data property
translation updates
> inputstream.adaptive: update to 20.3.4-Nexus

- packages/linux/patches/default/linux-150-dev_input_xpad_add_8bitdo_pro_2_wired_controller_support.patch
This should improve support for popular controller.
> linux: Improve 8bitdo pro 2 wired controller support

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.13
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.14
6.1.13 - 118 patches
6.1.14 - 47 patches
-
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.1.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.1.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.1
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux …
```
> linux: update to 6.1.14

- packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
Was missed due to Generic-legacy
> visualization.projectm: update to 20.2.0-Nexus

- config/arch.aarch64
- Fixes #7559
@lrusak - could you please review. Or are there cases where `gnueabi` will be `gnu`?
> config/arch.aarch64: drop TARGET_ABI=eabi

- packages/sysutils/fuse3/package.mk
release notes:
- https://github.com/libfuse/libfuse/releases/tag/fuse-3.13.0
used by addons (and on Generic by open-vm-tools)
> fuse3: update to 3.13.0

- packages/multimedia/dav1d/package.mk
Release notes: https://code.videolan.org/videolan/dav1d/-/releases/1.1.0
Updated PKG_SITE / PKG_URL to project's videolan page / mirrors.
> dav1d: update to 1.1.0

- packages/compress/zstd/package.mk
Release notes: https://github.com/facebook/zstd/releases/tag/v1.5.4
> zstd: update to 1.5.4

- packages/tools/bcm2835-userland/package.mk
- packages/tools/bcm2835-utils/package.mk
- projects/RPi/devices/RPi/options
- projects/RPi/devices/RPi2/options
- projects/RPi/devices/RPi4/options
- projects/RPi/options
This adds the foundation for a usable/testable image for RPi using an aarch64 userland, meaning it boots, runs Kodi, and plays media. There are no prebuilt addons from LE being distributed for such a platform at this time.
Regarding bcm2835-drivers v. bcm2835-userland:
bcm2835-drivers has everything bcm2835-userland does and then some, but it's distributed pre-built for arm. bcm2835-userland is distributed in source form so it may build for aarch64. This gets the useful commands vcgencmd, dtoverlay, dtparam, and their needed libraries. Other libraries are available (listed and commented in package), but I haven't identified a use for them, so left them out. (Thanks @ToKe79 for pointing me in this direction.)
This is split from an RPi3 device branch. I expect it to be fine as a start for …
> Add aarch64 userland to RPi

- packages/web/curl/package.mk
- packages/web/nghttp2/package.mk
changes:
- https://curl.se/changes.html
- Mostly bugfixes and a security fix. 
- regular 56 day release
new / changed functionality 
- [curl: add --url-query](https://curl.se/bug/?i=9691)
- [CURLOPT_QUICK_EXIT: don't wait for DNS thread on exit](https://curl.se/bug/?i=2975)
- [lib: add CURL_WRITEFUNC_ERROR to signal write callback error](https://curl.se/bug/?i=9874)
- [openssl: reduce CA certificate bundle reparsing by caching](https://curl.se/bug/?i=9620)
- [version: add a feature names array to curl_version_info_data](https://curl.se/bug/?i=9583)
- 
- [curl.h: add CURL_HTTP_VERSION_3ONLY](https://curl.se/bug/?i=10264)
- [share: add sharing of HSTS cache among handles](https://curl.se/bug/?i=10138)
- [src: add --http3-only](https://curl.se/bug/?i=10264)
tool_operate: share HSTS between …
> curl: update to 7.88.1 and nghttp2: update to 1.52.0

- config/functions
- returns the `PKG_SHA256` hash of a given package file
- useful if you reuse a base package as source & if you want to keep it synced
> config/functions: add get_pkg_sha256

- packages/mediacenter/kodi/package.mk
This bumps the joystick API and fixes current LE master builds
runtime tested on RPi4
> kodi: update to 497636a

- packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.3/docs/relnotes/22.3.6.rst
```
Generic.x86_64-devel-20230223104503-68224ac
Linux nuc12 6.1.13-rc1 #1 SMP Tue Feb 21 13:28:17 UTC 2023 x86_64 GNU/Linux
Starting Kodi (20.0 (20.0.0) Git:20.0-Nexus). Platform: Linux x86 64-bit
Kodi compiled 2023-02-14 by GCC 12.2.0 for Linux x86 64-bit version 6.1.12 (393484)
Running on LibreELEC (heitbaum): devel-20230223104503-68224ac 11.0, kernel: Linux x86 64-bit version 6.1.13-rc1
CApplication::CreateGUI - trying to init gbm windowing …
```
> mesa: update to 22.3.6

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.6.html
> [le12] samba: update to 4.17.6

- packages/graphics/mesa/package.mk
Last iteration of mesa 22.
- https://docs.mesa3d.org/relnotes/22.3.6.html
- https://docs.mesa3d.org/relnotes/22.3.7.html
- Backport of #7578
> [le11] mesa: update to 22.3.7

- packages/devel/flatbuffers/package.mk
Release notes:
- https://github.com/google/flatbuffers/releases
> flatbuffers: update to 23.3.3

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.19
- Fix for Wireless WPA issues.
- 6.1.19 - 5 patches
commit 7b3eac1950e791c6a52888cd41aef472660d4530
Author: Hector Martin <marcan@marcan.st>
Date:   Sat Mar 11 23:19:14 2023 +0900
wifi: cfg80211: Partial revert "wifi: cfg80211: Fix use after free for wext"
commit 79d1ed5ca7db67d48e870c979f0e0f6b0947944a upstream.
This reverts part of commit 015b8cc5e7c4 ("wifi: cfg80211: Fix use after
free for wext")
This commit broke WPA offload by unconditionally clearing the crypto
modes for non-WEP connections. Drop that part of the patch.
Signed-off-by: Hector Martin <marcan@marcan.st>
Reported-by: Ilya <me@0upti.me>
Reported-and-tested-by: Janne Grunau <j@jannau.net>
Reviewed-by: Eric Curtin <ecurtin@redhat.com>
Fixes: 015b8cc5e7c4 …
> [le12] linux: update to 6.1.19

- packages/linux/package.mk
> [le11] linux: update to 6.1.19

- packages/multimedia/gmmlib/package.mk
- packages/multimedia/media-driver/package.mk
- packages/multimedia/nv-codec-headers/package.mk
- packages/multimedia/nvidia-vaapi-driver/package.mk
- packages/sysutils/open-vm-tools/package.mk
- packages/x11/driver/xf86-video-amdgpu/package.mk
- packages/x11/driver/xf86-video-intel/package.mk
- gmmlib: update to 22.3.4
- media-driver: update to 23.1.3
- nv-codec-headers: update to 12.0.16.0
- nvidia-vaapi-driver: update to 0.0.9
- open-vm-tools: update to 12.2.0
- xf86-video-amdgpu: update to 23.0.0
- xf86-video-intel: update to githash 20230201
> x86 driver updates

- packages/tools/dtc/package.mk
log:
- https://git.kernel.org/pub/scm/utils/dtc/dtc.git/log/
> dtc: update to 1.7.0

- packages/web/libmicrohttpd/package.mk
Ann:
- https://lists.gnu.org/archive/html/libmicrohttpd/2023-02/msg00000.html
GNU libmicrohttpd 0.9.76 released with just one small change that fixes a security problem in the MHD_PostProcessor where malformed inputs can be used to crash the server (for denial-of-service). While the bug is not believed to be exploitable in other ways and only applies for applications that use the (optional) MHD_PostProcessing logic, we of course encourage everyone to upgrade.
Thanks to Gynvael Coldwind and Dejan Alvadzijevic for responsibly disclosing the problem and even proposing a good solution.
> libmicrohttpd: update to 0.9.76

- packages/audio/libsndfile/package.mk
- packages/devel/mpfr/package.mk
- packages/devel/ncurses/package.mk
- packages/devel/ncurses/patches/ncurses-004-fix_configure_pkgconfig.patch
- packages/tools/nano/package.mk
- nano: update to 7.2
- ncurses: update to 6.4
- libsndfile: update to 1.2.0 and PKG_URL
- mpfr: update to 4.2.0
> misc packages updates

- packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Announcement:
- https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html
> rust: update to 1.68.0

- packages/print/freetype/package.mk
- packages/x11/font/encodings/package.mk
- packages/x11/font/font-bitstream-type1/package.mk
- packages/x11/font/font-cursor-misc/package.mk
- packages/x11/font/font-misc-misc/package.mk
- packages/x11/font/font-util/package.mk
- packages/x11/font/font-xfree86-type1/package.mk
- packages/x11/other/fontconfig/package.mk
- packages/x11/util/util-macros/package.mk
- encodings: update to 1.0.7
- font-bitstream-type1: update to 1.0.4 and https
- font-cursor-misc: update to 1.0.4 and https
- font-misc-misc: update to 1.1.3 and https
- font-xfree86-type1: update to 1.0.5 and https
- fontconfig: update to 2.14.2
- freetype: update to 2.13.0
- font-util: update to 1.4.0
- util-macros: update to 1.20.0 and https
> Font updates

- packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
introduced in https://github.com/LibreELEC/LibreELEC.tv/pull/7386
LibreELEC:~ # udevadm hwdb --update
/usr/lib/udev/hwdb.d/70-local-keyboard.hwdb:28: Property expected, ignoring record with no properties.
> systemd: fix error in 70-local-keyboard.hwdb

- packages/security/gnutls/package.mk
Release notes:
- https://lists.gnupg.org/pipermail/gnutls-help/2023-February/004816.html
- https://gnutls.org/security-new.html#GNUTLS-SA-2020-07-14
> gnutls: update to 3.8.0

- packages/devel/glib/package.mk
Release notes:
- https://gitlab.gnome.org/GNOME/glib/-/releases
> glib: update to 2.76.0

- config/functions
meson: allow skipping of run check for IPC_RMID_DEFERRED_RELEASE
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/134
needed for:
- 727fdb8b72b123050627e62a3009bb057dc59754
- I missed adding this in #7635
> config/functions: in meson cross-file set ipc_rmid_deferred_release = true

- packages/sysutils/busybox/scripts/createlog
This cleans up busybox/scripts/createlog:
Only create a logfile for the previous boot if persistent journal is being used.
Drops the $GIT line in the logfile headers. This is extracted from /etc/issue, which doesn't have a githash in it. See the commit in the /etc/release naming instead (if field exists).
Resolved shellcheck warnings:
`...` to $(...)
Verifying variable is set ${var:?} before rm'ing
Useless use of cat
Command grouping when the commands redirect to the same file
Use of == in [...]
[ test1 -a test2 ] to [ test1 ] && [ test2 ]
> Cleanup busybox/scripts/createlog

- packages/graphics/mesa/package.mk
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/staging/23.0/docs/relnotes/23.0.0.rst
release calendar:
- https://docs.mesa3d.org/release-calendar.html
run tested on `Kodi (21.0-ALPHA1 (20.90.101) Git:497636acc7dabb03b88872d8ef5607140a342608). `
```
[    0.000000] Linux version 6.1.20 (docker@85cd1a58f653) (aarch64-none-elf-gcc-12.2.0 (GCC) 12.2.0, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT Sat Mar 18 10:58:49 UTC 2023
[    0.000000] Machine model: Tanix TX6
EGL_VENDOR = Mesa Project
GL_VENDOR = Mesa
GL_RENDERER = Mali-T720 (Panfrost)
GL_VERSION = OpenGL ES 2.0 Mesa 23.0.0
[    0.000000] Linux version 6.1.20-rc2 (docker@51e2e869476c) (x86_64-libreelec-linux-gnu-gcc-12.2.0 (GCC) 12.2.0, GNU ld (GNU Binutils) 2.40) #1 SMP Fri Mar 17 07:56:13 UTC 2023
[    0.000000] DMI: …
```
> mesa: update to 23.0.0

- packages/devel/ccache/package.mk
release notes:
- https://ccache.dev/releasenotes.html#_ccache_4_8
> ccache: update to 4.8

- packages/addons/addon-depends/system-tools-depends/bottom/package.mk
- packages/addons/addon-depends/system-tools-depends/diffutils/package.mk
- packages/addons/addon-depends/system-tools-depends/htop/package.mk
- packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk
- packages/addons/addon-depends/system-tools-depends/lshw/package.mk
- packages/addons/addon-depends/system-tools-depends/mc/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/addon-depends/system-tools-depends/unrar/package.mk
- packages/addons/addon-depends/system-tools-depends/vim/package.mk
- packages/addons/tools/system-tools/package.mk
system-tools: update to addon (1)
- bottom: update to 0.8.0
- diffutils: update to 3.9
- htop: update to 3.2.2
- libgpiod: update to 2.0
- lshw: fix lshw -version display
- mc: update to 4.8.29
- stress-ng: update to 0.15.06
- unrar: update to 6.2.6
- vim: update to 9.0.1413
> [le12] system-tools: update to addon (1)

- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
log:
- https://github.com/GNOME/gtk/compare/3.24.36...3.24.37
Overview of Changes in GTK+ 3.24.37, 02-03-2023
===============================================
* Support the file transfer portal for copy-paste and DND
* Treat XKB_MODE_NAME_LODO as super key
* Refactor startup notification handling to be in sync with GTK 4
* GL: Synchronie when calling MakeCurrent
* CSS: Fix a problem with stopping animations
* Wayland: Drop the legacy text input module
* Windows: Set the default file extension in the native file chooser
* Translation updates:
* Abkhazian
* Turkish
> gtk3: update to 3.24.37

- packages/mediacenter/kodi/tmpfiles.d/kodi-userdirs.conf
- packages/network/samba/config/smb.conf
- packages/sysutils/busybox/tmpfiles.d/z_01_busybox.conf
Samba has the option to run commands before entering shared directories. This has been used to create the directories, as well as run createlog for the logfiles special share.
This moves the directory creation to boot time, instead of attempting every time the share is accessed. For the logfiles share, the createlog script itself will create /storage/logfiles if needed before moving the zipped logs there.
systemd-tempfiles-setup.service is called early in boot, so I don't see a need to alter kodi or samba startup service files. See `systemctl list-dependencies systemd-tempfiles-setup.service --all --reverse`
> samba: move directory creation to busybox or kodi tmpfiles.d

- packages/devel/libcap/package.mk
Log:
- https://git.kernel.org/pub/scm/libs/libcap/libcap.git/log/
release notes:
- https://sites.google.com/site/fullycapable/release-notes-for-libcap?authuser=0#h.o8papfkfh1x9
> libcap: update to 2.67

- packages/addons/tools/system-tools/package.mk
fix build error
from the libgpiod release notes:
libgpiod v2.0
=============
This is a major release that breaks compatiblity with the v1.6.x series. The entire data model has been overhauled in order to make using the library more intuitive and less cumbersome, while also making the code future-proof and extensible. Please refer to the documentation for details.
New features:
- rework the entire API: core C library as well as C++ and Python bindings
- rework the command-line tools in order to make them more line-name-oriented
- drop gpiofind as tools can now resolve line names on their own
- add the interactive mode to gpioset
- add Rust bindings
- make tests work with the gpio-sim kernel module
> system-tools: drop gpiofind

- packages/addons/service/tigervnc/package.mk
- backport of #7699
- Fixes #7698
> [le11] tigervnc: copy missing library libXtst to addon directory

- packages/sysutils/tz/package.mk
News:
- https://github.com/eggert/tz/blob/71faa2a55db2c9f21f4099b58c28536673982e0a/NEWS
- Backport of #7684
> [le11] tz: update to 2023b

- packages/tools/bcm2835-userland/package.mk
Log:
- https://github.com/raspberrypi/userland/commits/master
> bcm2835-userland: update to githash 9d5250f (2023-03-23)

- packages/network/iwd/package.mk
ver 2.4:
+	Fix issue with FT-over-Air and same channel operation.
+	Fix issue with AP mode and missing support for GTK.
+	Fix issue with AP mode and channel switch event.
+	Fix issue with SSID string conversion handling.
> [le12] iwd: update to 2.4

- packages/network/iwd/package.mk
- backport of #7703
ver 2.4:
+	Fix issue with FT-over-Air and same channel operation.
+	Fix issue with AP mode and missing support for GTK.
+	Fix issue with AP mode and channel switch event.
+	Fix issue with SSID string conversion handling.
> [le11] iwd: update to 2.4

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.7.html
> [le12] samba: update to 4.17.7

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
release notes:
- https://blog.rust-lang.org/2023/03/28/Rust-1.68.2.html
- https://github.com/rust-lang/rust/releases/tag/1.68.2
- https://github.com/rust-lang/rust/compare/1.68.1...1.68.2
> rust: update to 1.68.2

- packages/sysutils/tz/package.mk
log:
- https://github.com/eggert/tz/compare/2023b...2023c
- Backport of #7707
> [le11] tz: update to 2023c

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/package.mk
- cli and moby - update to 23.0.2
- runc: update to 1.1.5
- https://github.com/opencontainers/runc/releases/tag/v1.1.5
- https://github.com/opencontainers/runc/compare/v1.1.4...v1.1.5
> [le12] docker: update to 23.0.2 and addon (2)

- scripts/build
Package building honor's the strip flag so we can prevent executables from being stripped.
But copying files to INSTALL ignored that flag which meant the flag had practically no effect.
Fix this by using the same logic as we do in the meson strip handling in line 170 and in config/functions
> scripts/build: properly honor strip build flag

- packages/sysutils/udevil/package.mk
When mounting a single ntfs file system there is log spam generated. This PR removes e.g. the following lines of mounting /dev/sda2 (extracted from [here](https://forum.libreelec.tv/thread/26917-ext-hds-not-mounted-after-11-01-update/?postID=179118#post179118)):
```
Mar 30 21:44:04.086628 LibreELEC kernel: ext3: Unknown parameter 'fmask'
Mar 30 21:44:04.109778 LibreELEC kernel: ext2: Unknown parameter 'fmask'
Mar 30 21:44:04.109819 LibreELEC kernel: ext4: Unknown parameter 'fmask'
Mar 30 21:44:04.109839 LibreELEC kernel: squashfs: Unknown parameter 'fmask'
Mar 30 21:44:04.113141 LibreELEC kernel: F2FS-fs (sda2): Magic Mismatch, valid(0xf2f52010) - read(0x8e0e8966)
Mar 30 21:44:04.113157 LibreELEC kernel: F2FS-fs (sda2): Can't find valid F2FS filesystem in 1th superblock
Mar 30 …
```
> udevil: improve mount.ntfs script

- packages/network/samba/package.mk
release notes:
- https://www.samba.org/samba/history/samba-4.17.6.html
- https://www.samba.org/samba/history/samba-4.17.7.html
- backport of #7574 
- backport of #7716
> [le11] samba: update to 4.17.7

- packages/compress/zstd/package.mk
release notes:
- https://github.com/facebook/zstd/releases/tag/v1.5.5
> zstd: update to 1.5.5

- packages/multimedia/media-driver/package.mk
Intel Media Driver 2023Q1 Release - 23.1.6
- https://github.com/intel/media-driver/releases/tag/intel-media-23.1.6
log:
- https://github.com/intel/media-driver/compare/intel-media-23.1.5...intel-media-23.1.6
- Minor change from 23.1.5
> media-driver: update to 23.1.6

- packages/mediacenter/kodi/package.mk
This needs to be merged together with the ffmpeg 6.0 update PR #7735
```
2023-04-11 15:48:13.199 T:839      info <general>: Starting Kodi (21.0-ALPHA1 (20.90.101) Git:12048c03a762328e2b7d537486155bc50a6fcc80). Platform: Linux ARM 64-bit
2023-04-11 15:48:13.199 T:839      info <general>: Using Release Kodi x64
2023-04-11 15:48:13.199 T:839      info <general>: Kodi compiled 2023-04-11 by GCC 12.2.0 for Linux ARM 64-bit version 6.1.21 (393493)
2023-04-11 15:48:13.199 T:839      info <general>: Running on BCM2835 with LibreELEC (HiassofT): devel-20230411130334-c454ebc 12.0, kernel: Linux ARM 64-bit version 6.1.21
2023-04-11 15:48:13.199 T:839      info <general>: FFmpeg version/source: 6.0
```
> kodi: update to current master

- packages/multimedia/ffmpeg/package.mk
- packages/multimedia/ffmpeg/patches/libreelec/ffmpeg-001-libreelec.patch
- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
- packages/multimedia/ffmpeg/patches/v4l2-drmprime/ffmpeg-001-v4l2-drmprime.patch
- packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
- packages/multimedia/ffmpeg/patches/vf-deinterlace-v4l2m2m/ffmpeg-001-vf-deinterlace-v4l2m2m.patch
- projects/RPi/patches/kodi/0006-fixup-ffmpeg-avformats.patch
- tools/ffmpeg/gen-patches.sh
This PR depends on the kodi ffmpeg 6.0 bump https://github.com/xbmc/xbmc/pull/22967 which isn't merged yet so I'm creating it as draft.
I've updated all ffmpeg patches and switched the AML ffmpeg version to current RPi version, so everything should build fine.
Runtime testing on RPi looks good so far
> ffmpeg: update to 6.0

- packages/devel/libdisplay-info/package.mk
- packages/mediacenter/kodi/package.mk
This adds support for [libdisplay-info](https://gitlab.freedesktop.org/emersion/libdisplay-info).
This is required by the upcoming Kodi PR -> https://github.com/xbmc/xbmc/pull/19141
> add libdisplay-info dependency for gbm builds

- packages/linux/package.mk
- packages/linux/patches/default/linux-122-rtw88-USB-fixes2.patch
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.20
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.21
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.22
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.23
6.1.20 - 140 patches
6.1.21 - 199 patches
6.1.22 - 224 patches
6.1.23 - 177 patches
- [linux: rtw88: USB bug fixes](https://github.com/LibreELEC/LibreELEC.tv/pull/7621/commits/531da5248deba91e7e1400f527f5e6c6d4b50d89)
- wifi: rtw88: usb: fix priority queue to endpoint mapping
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.1.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.1.y
- …
> [le12] linux: update to 6.1.y

- packages/graphics/mesa/package.mk
When `mesa` finds llvm, it compiles “gallium draw” with llvm, this is subsequently linked into the `iris_dri.so` - this can be checked using `readelf` with the `LLVMInitializeX86TargetInfo` symbol being present.
the build of the libLLVM library doesn’t include X86 in the target (only AMDGPU)
https://github.com/LibreELEC/LibreELEC.tv/blob/97410801443b391895b8a626b7811ba4e71b8038/packages/lang/llvm/package.mk#L91
so don’t let mesa build to use llvm for the TARGET_ARCH (only AMDGPU - which is “supported as per mesa PR 9259)
- Fixes #7764
ref:
- https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9259
maybe candidate for backport.
Reason for this appearing now is - change in handling the dlopen?
> mesa: do not use LLVM for gallium draw

- projects/Allwinner/patches/u-boot/0014-unreliable-dram.patch
With this patch applied, I couldn't replicate DRAM size mis-detection issue anymore.
> [LE12] Allwinner: u-boot: Fix sporadic DRAM size misdetection

- projects/Allwinner/patches/u-boot/0014-unreliable-dram.patch
With this patch applied, I couldn't replicate DRAM size mis-detection issue anymore.
> [LE11] Allwinner: u-boot: Fix sporadic DRAM size misdetection

- packages/sysutils/busybox/scripts/fs-resize
- packages/sysutils/gptfdisk/patches/0001-Fix-failure-crash-of-sgdisk-when-compiled-with-lates.patch
- packages/sysutils/gptfdisk/patches/0002-Updated-guid.cc-to-deal-with-minor-change-in-libuuid.patch
- packages/sysutils/gptfdisk/patches/0003-Updated-URLs-in-man-pages-to-HTTPS-rather-than-HTTP.patch
- packages/sysutils/gptfdisk/patches/0004-Fix-NULL-dereference-when-duplicating-string-argumen.patch
- packages/sysutils/gptfdisk/patches/0005-Use-64bit-time_t-on-linux-as-well.patch
- packages/sysutils/gptfdisk/patches/0006-Allow-partition-dynamically-allocated-by-largest-new.patch
- packages/sysutils/gptfdisk/patches/0007-Document-recent-merge.patch
- packages/sysutils/gptfdisk/patches/0008-Document-recent-mergest.patch
- packages/sysutils/gptfdisk/patches/0009-Do-some-explicit-casts-in-gptcurses.cc-to-eliminate-.patch
- packages/sysutils/gptfdisk/patches/0010-Truncate-decimal-inputs-e.g.-9.5G-becomes-9G.patch
- packages/sysutils/gptfdisk/patches/0011-Document-previous-merge.patch
- packages/sysutils/gptfdisk/patches/0012-Minor-code-cleanup-based-on-valgrind-analysis.patch
Since update to 1.09 `sgdisk -e /dev/<device>` is failing in fs_resize.
The issue was reported in [forum](https://forum.libreelec.tv/thread/26882-libreelec-11-0-0-generic-for-virtual-machines-cannot-be-updated/).
After add adding logging the error was visible. 
There is no gptfdisk 1.09.2 source available on  Sourceforge. To avoid issues with downloading from git the upstream patches are added.
To ease research on future errors the logging code is included in this PR, it only creates a short log on success:
```
2023-03-26T11:36:57+0000
/dev/sda2 /storage ext4 rw,noatime 0 0
DISK: /dev/sda  PART: /dev/sda2
*** sgdisk -e /dev/sda >>/flash/fs-resize.log 2>&1
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) …
```
> gptfdisk: update to 1.09.2 / fs_resize: improvements

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.248
- vulkan-loader: update to 1.3.248
- vulkan-tools: update to 1.3.248
> Vulkan update to 1.3.248

- packages/sysutils/systemd/config/hosts.conf
- packages/sysutils/systemd/scripts/network-base-setup
This partially addresses #7674. Another part will be needed in the settings addon.
In short, the settings addon will just append localhost entries to user or image set /etc/hosts. This moves settings to the network-base.service, and makes adding entries contingent on the image's hosts.conf matching the same content as the one located in /storage. If there is any mismatch, no changes are made.
127.0.1.1 is added as the hostname's hosts entry as recommended by Debian's reference manual: https://qref.sourceforge.net/quick/ch-gateway.en.html see 10.4. It's for applications that believe the hostname should resolve to an address.
I don't believe it's enabled, but my understanding is ipv6 has only the one localhost address so there's no change to be made there.
The intended change in the …
> systemd: network-base: alter hosts.conf if contents still default

- packages/tools/qemu/package.mk
the --disable-blobs option to configure was deprecated in 6.2 and is replaced with --disable-install-blobs
ref: https://wiki.qemu.org/ChangeLog/6.2
> qemu: update to 8.0.0

- packages/tools/bcm2835-userland/package.mk
Commit:
- https://github.com/raspberrypi/userland/commit/cc1ca18fb0689b01cc2ca2aa4b400dcee624a213
> bcm2835-userland: update to githash cc1ca18 update (2023-04-20)

- packages/addons/addon-depends/chrome-depends/chrome-libXfixes/package.mk
chrome-libXfixes: update package filename to match libXfixes
- Commit 5a91268dd1fadc20b85a1da7c0563f5eda66276d changed from .bz2 to .xz. Update chrome-libXfixes to match.
> Fix chrome build

- packages/addons/service/jellyfin/package.mk
- https://github.com/jellyfin/jellyfin/releases/tag/v10.8.10
CRITICAL SECURITY ADVISORY: [GHSA-9p5f-5x8v-x65m](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m) and [GHSA-89hp-h43h-r5pq](https://github.com/jellyfin/jellyfin-web/security/advisories/GHSA-89hp-h43h-r5pq) can be combined to allow remote code execution for any authenticated Jellyfin user including non-admin users. While the particular execution mechanism of the former dates to the 10.8.0 release, the latter was present for all Jellyfin releases before this point. It is thus absolutely critical for all Jellyfin administrators, regardless of version, to upgrade to this version if they allow any untrusted users and/or expose their instance to the Internet.
> [le12] jellyfin: update to 10.8.10 and addon (1)

- packages/addons/service/jellyfin/changelog.txt
- packages/addons/service/jellyfin/package.mk
- https://github.com/jellyfin/jellyfin/releases/tag/v10.8.10
CRITICAL SECURITY ADVISORY: [GHSA-9p5f-5x8v-x65m](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m) and [GHSA-89hp-h43h-r5pq](https://github.com/jellyfin/jellyfin-web/security/advisories/GHSA-89hp-h43h-r5pq) can be combined to allow remote code execution for any authenticated Jellyfin user including non-admin users. While the particular execution mechanism of the former dates to the 10.8.0 release, the latter was present for all Jellyfin releases before this point. It is thus absolutely critical for all Jellyfin administrators, regardless of version, to upgrade to this version if they allow any untrusted users and/or expose their instance to the Internet.
> [le11] jellyfin: update to 10.8.10 and addon (1)

- packages/graphics/nvidia/package.mk
Wayland version 520.56.06 of nvidia fails to compile - due to changes in kernel apis in 6.2/6.3.
Update to latest stable nvidia driver. 
- https://www.nvidia.com/Download/driverResults.aspx/204639/en-us/
> nvidia: update to 525.116.03 fixes wayland build with kernel 6.3

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.249
- vulkan-loader: update to 1.3.249
- vulkan-tools: update to 1.3.249
> Vulkan update to 1.3.249

- packages/wayland/compositor/sway/patches/sway-999.01-fix-build-with-updated-libinput.patch
- patch from: https://github.com/swaywm/sway/issues/7539
- patch required because on libinput 1.23.0 and gcc warning - https://github.com/LibreELEC/LibreELEC.tv/pull/7718/commits/9853a290e0ffd3c7c5898c3d9de6e51bd1fbeb12
wayland build now successful again: `PROJECT=Generic ARCH=x86_64 DEVICE=wayland make image`
> sway: fix build with updated libinput

- packages/sysutils/busybox/scripts/createlog
When persistent logging is enabled the binary journal files are included into createlog's ZIP file.
Omit them to minimize the file size.
> busybox: createlog: don't include journal files of persistent logging

- packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk
- packages/addons/addon-depends/network-tools-depends/iperf/package.mk
- packages/addons/addon-depends/network-tools-depends/irssi/package.mk
- packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk
- packages/addons/tools/network-tools/package.mk
- iperf: update to 3.13-mt1
- irssi: update to 1.4.4
- libpcap: update to 1.10.4
- tcpdump: update to 4.99.
> [le12] network-tools: update addon (2) 

- packages/addons/addon-depends/system-tools-depends/depends/libmtp/package.mk
- packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/tools/system-tools/package.mk
- libgpiod: update to 2.0.1
- libmtp: update to 1.1.21
- stress-ng: update to 0.15.07
> [le12] system-tools: update addon (2) 

- packages/graphics/libheif/package.mk
release notes:
- https://github.com/strukturag/libheif/releases
> libheif: update to 1.16.1

- packages/addons/service/mariadb/package.mk
- packages/addons/service/mariadb/patches/mariadb-0001-disable-plugin-auth-pam.patch
release notes:
- https://mariadb.com/kb/en/mariadb-10-11-3-release-notes/
- The update supports gcc-13.1.0
> [le12] mariadb: update to 10.11.3 and addon (2)

- packages/addons/addon-depends/snapcast-depends/snapcast/patches/snapcast-03-1124-fix-gcc13.patch
- packages/addons/addon-depends/ttyd-depends/libwebsockets/patches/libwebsockets-0001-PR2824.patch
- packages/emulation/libretro-bsnes-hd/patches/bsnes_hd-002-fix-build-with-gcc-13.patch
- packages/emulation/libretro-bsnes/patches/0002-PR60-fix-build-with-gcc13.patch
- packages/lang/gcc/package.mk
- packages/mediacenter/kodi-binary-addons/audiodecoder.timidity/patches/77.patch
- packages/mediacenter/kodi-binary-addons/imagedecoder.heif/patches/PR63-fix-build-with-gcc-13.patch
- packages/mediacenter/kodi-binary-addons/imagedecoder.mpo/patches/PR55-fix-build-with-gcc-13.patch
- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/patches/1240-fix-gcc13.patch
- packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/patches/PR238-fix-gcc-13-build.patch
- packages/multimedia/media-driver/patches/1648.patch
- packages/security/nss/patches/nss-11-D174822-allow-build-with-gcc-13.patch
- packages/wayland/waylandpp/patches/waylandpp-0001-PR71-support-build-with-gcc13.patch
Packages that need,to,be updated before this PR can be moved forward
- ~~mariadb - patch to be included in 10.11.3~~
- ~~https://jira.mariadb.org/browse/MDEV-31057~~
- ~~https://github.com/MariaDB/server/commit/cf4a16b5557be5fb3568c1de0d6cc0a18291afc9~~
- These patches are included in the #7826 10.11.3 release
- media-driver - not yet incorporated
- https://github.com/intel/media-driver/pull/1648
- nss - patch already in nss master
other minors that the plan is to go with the patch:
- https://github.com/warmcat/libwebsockets/pull/2824
- https://github.com/badaix/snapcast/pull/1124 (just waiting on a release)
- Kodi addons (all have been accepted into master)
- https://github.com/NilsBrause/waylandpp/pull/71
All gcc-13 “build error” fixes are upstream patches (or have been submitted to …
> gcc: update to 13.1.0

- packages/graphics/mesa/package.mk
- mesa: enable intel-xe-kmd
- mesa: update to 23.1.0
- https://lists.freedesktop.org/archives/mesa-announce/2023-May/000720.html
```
Generic.x86_64-devel-20230511092738-b73f370
Linux nuc12 6.1.28-rc2 #1 SMP Thu May 11 08:37:42 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA1 (20.90.101) Git:1a04aa12cb4e5457867451f41ab4dcdcd201b1a9). Platform: Linux x86 64-bit
Kodi compiled 2023-05-10 by GCC 13.1.0 for Linux x86 64-bit version 6.3.2 (393986)
Running on LibreELEC (heitbaum): devel-20230511092738-b73f370 12.0, kernel: Linux x86 64-bit version 6.1.28-rc2
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0085.2022.0718.1739 …
```
> mesa: update to 23.1.0

- packages/network/samba/package.mk
ann:
- https://lists.samba.org/archive/samba-announce/2023/000635.html
backport of:
- #7830
> samba: update to 4.17.8

- packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20230512
tested ADL:
was
`[    0.000000] microcode: updated early: 0x421 -> 0x429, date = 2023-01-11 `
is
`[    0.000000] microcode: updated early: 0x421 -> 0x42a, date = 2023-02-14`
> [le12] intel-ucode: update to 20230512

- packages/mediacenter/kodi/patches/drmprime-filter/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0002-WIP-DRMPRIME-deinterlace-filter.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0003-DVDVideoCodecDRMPRIME-Avoid-exception-with-AV_PIX_FM.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0004-DVDVideoCodecDRMPRIME-Leave-deinterlace-filter-activ.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0005-SetVideoInterlaced-Set-and-unset-deinterlace-method-.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0006-DVDVideoCodecDRMPRIME-Close-deinterlace-filter-on-er.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0007-DVDVideoCodecDRMPRIME-Fix-missing-flush-after-eof.patch
This should fix the "no video on live TV" issue reported here
https://github.com/xbmc/xbmc/issues/23222
https://forum.libreelec.tv/thread/27018-tvh-live-streaming-buggy/?postID=180416#post180416
> kodi: update drmprime-filter patches

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/docker/moby/patches/moby-001-user-addon-storage-location.patch
- packages/addons/addon-depends/docker/moby/patches/moby-002-use-unconfined-seccomp-profile-as-default.patch
- packages/addons/service/docker/package.mk
docker: update to 24.0.1 and addon (6)
- cli: update to 24.0.1
- moby: update to 24.0.1
release notes:
- https://github.com/moby/moby/releases/tag/v24.0.0
- https://github.com/moby/moby/releases/tag/v24.0.1
> [le12] docker: update to 24.0.1 and addon (6) 

- packages/databases/sqlite/package.mk
- packages/linux-firmware/intel-ucode/package.mk
- packages/multimedia/media-driver/package.mk
- packages/sysutils/busybox/package.mk
- packages/sysutils/exfatprogs/package.mk
- packages/sysutils/util-linux/package.mk
- packages/sysutils/util-linux/patches/util-linux-01-fix-pkgconf.patch
- packages/textproc/libxml2/package.mk
- packages/web/curl/package.mk
- packages/web/nghttp2/package.mk
- packages/x11/app/setxkbmap/package.mk
- busybox: update to 1.36.1
- curl: update to 8.1.0
- exfatprogs: update to 1.2.1
- intel-ucode: update to 20230516 (documentation only)
- libxml2: update to 2.11.4
- media-driver: update to 23.2.2
- nghttp2: update to 1.53.0
- setxkbmap: update to 1.3.4
- sqlite: update to 3.42.0
- util-linux: update to 2.39
> package updates 

- packages/devel/ccache/package.mk
- packages/devel/cmake/package.mk
- packages/lang/llvm/package.mk
- packages/python/security/pycryptodome/package.mk
- ccache: update to 4.8.1
- cmake: update to 3.26.4
- llvm: update to 16.0.4
- pycryptodome: update to 3.18.0
> development package updates

- packages/network/wireless-regdb/package.mk
log:
- https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git
backport of 
- #7839
> [le11] wireless-regdb: update to 2023.05.03

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
Backport of:
- #7815
- #7850
Includes
- update moby and cli to 23.0.6
- containerd: update to 1.7.1
- runc: update to 1.1.7
> [le11] docker: update to 23.0.6 and addon (4)

- packages/graphics/mesa/package.mk
release notes:
- https://docs.mesa3d.org/relnotes/23.1.1.html
```
Generic.x86_64-devel-20230526003843-af8aa1f
Linux nuc12 6.4.0-rc3 #1 SMP Fri May 26 00:39:15 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA1 (20.90.101) Git:1a04aa12cb4e5457867451f41ab4dcdcd201b1a9). Platform: Linux x86 64-bit
Kodi compiled 2023-05-21 by GCC 13.1.0 for Linux x86 64-bit version 6.3.3 (393987)
Running on LibreELEC (heitbaum): devel-20230526003843-af8aa1f 12.0, kernel: Linux x86 64-bit version 6.4.0-rc3
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0087.2023.0306.1931 03/06/2023 …
```
> mesa: update to 23.1.1

- packages/multimedia/media-driver/package.mk
Log:
- https://github.com/intel/media-driver/compare/intel-media-23.2.2...intel-media-23.2.3 
```
Generic.x86_64-devel-20230531125537-1498f16
Linux nuc12 6.3.5 #1 SMP Wed May 31 11:34:55 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA1 (20.90.101) Git:1a04aa12cb4e5457867451f41ab4dcdcd201b1a9). Platform: Linux x86 64-bit
Kodi compiled 2023-05-28 by GCC 13.1.0 for Linux x86 64-bit version 6.4.0 (394240)
Running on LibreELEC (heitbaum): devel-20230531125537-1498f16 12.0, kernel: Linux x86 64-bit version 6.3.5
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0087.2023.0306.1931 03/06/2023
CApplication::CreateGUI - trying to …
```
> media-driver: update to 23.2.3

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
> [le11] linux (RPi): update to 6.1.31

- packages/debug/gdb/package.mk
- packages/lang/llvm/package.mk
- packages/python/devel/MarkupSafe/package.mk
- packages/python/devel/meson/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- packages/tools/qemu/package.mk
- gdb: update to 13.2
- llvm: update to 16.0.5
- MarkupSafe: update to 2.1.3
- meson: update to 1.1.1
- qemu: update to 8.0.2
- rust: update to 1.70.0
- cargo-snapshot: update to 1.70.0
- rustc-snapshot: update to 1.70.0
- rust-std-snapshot: update to 1.70.0
> Toolchain Package updates 

- packages/addons/addon-depends/protobuf/patches/9936.patch
- packages/security/nss/patches/nss-20-Bug-1836781-Disabling-ASM-C25519-for-A-but-X86_64-r.patch
- protobuf: Use __constinit only in GCC 12.2 and up
- required due to use of jammy buildserver (which uses the host gcc-12.1)
- nss: fix Bug 1836781 - Disabling ASM C25519 for A but X86_64 r
- build errors with ARMv8 aarch64
> Upstream patches

- packages/lang/Python3/package.mk
- packages/lang/Python3/patches/0012-Add-an-option-to-disable-lib2to3.patch
- packages/lang/Python3/patches/0014-Add-an-option-to-disable-the-tk-module.patch
Tested on 
```
nuc12:~/.kodi/temp # head kodi.log
2023-06-07 11:30:04.953 T:2637     info <general>: -----------------------------------------------------------------------
2023-06-07 11:30:04.953 T:2637     info <general>: Starting Kodi (21.0-ALPHA1 (20.90.101) Git:1a04aa12cb4e5457867451f41ab4dcdcd201b1a9). Platform: Linux x86 64-bit
2023-06-07 11:30:04.953 T:2637     info <general>: Using Release Kodi x64
2023-06-07 11:30:04.953 T:2637     info <general>: Kodi compiled 2023-06-07 by GCC 13.1.0 for Linux x86 64-bit version 6.4.0 (394240)
2023-06-07 11:30:04.953 T:2637     info <general>: Running on LibreELEC (heitbaum): devel-20230607090404-e409313 12.0, kernel: Linux x86 64-bit version 6.4.0-rc5
2023-06-07 11:30:04.953 T:2637     info <general>: FFmpeg version/source: 6.0
2023-06-07 …
```
> Python3: update to 3.11.4

- packages/network/samba/scripts/samba-config
Fixup for 6a7c071568, reported in the [forum](https://forum.libreelec.tv/thread/27142-samba-auth-settings-for-local-shares-not-persisting-after-reboots/). 
smbpasswd requires a valid smb.conf, use fresh created tempfile as parameter. Allow logging to journal to make future errors visible.
> samba: samba-config: call smbpasswd with valid smb.conf

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/service/docker/package.mk
- cli: update to 24.0.2
- containerd: update to 1.7.2
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.2
- go: update to 1.20.5
- moby: update to 24.0.2
- release notes: https://github.com/moby/moby/releases/tag/v24.0.2
> [le12] docker: update to 24.0.2 and addon (1)

- packages/security/openssl/package.mk
release annoucement:
- https://www.openssl.org/news/secadv/20230530.txt
> [le11] openssl: update to 3.0.9

- packages/addons/addon-depends/snapcast-depends/asio/package.mk
- packages/addons/addon-depends/snapcast-depends/nqptp/package.mk
- packages/addons/addon-depends/snapcast-depends/shairport-sync/package.mk
- packages/addons/service/snapclient/changelog.txt
- packages/addons/service/snapclient/package.mk
- packages/addons/service/snapserver/changelog.txt
- packages/addons/service/snapserver/package.mk
- backport of #7876 
- asio: update to 1.28.0
- nqptp: update to 1.2.1
- shairport-sync: update to 4.2
- snapclient: update shairport-sync to 4.2 and addon (2)
- snapserver: update shairport-sync to 4.2 and addon (2)
> [le11] snapclient and snapserver: update shairport-sync to 4.2 and addon (2)

- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/tools/dotnet-runtime/changelog.txt
- packages/addons/tools/dotnet-runtime/package.mk
- backport of #7929
- dotnet-runtime: update aspnet6-runtime to 6.0.18 and addon (1)
- aspnet6-runtime: update to 6.0.18
> dotnet-runtime: update aspnet6-runtime to 6.0.18 and addon (3)

- packages/addons/addon-depends/jre-depends/apache-ant/package.mk
- packages/addons/addon-depends/jre-depends/jre-libbluray/package.mk
- Update jre-libbluray build to be built on arm and aarch64
- Fixes #7936
> Update jre-libbluray build to be built on arm and aarch64

- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
https://gstreamer.freedesktop.org/
- gst-plugins-bad: update to 1.22.4
- gst-plugins-base: update to 1.22.4
- gstreamer: update to 1.22.4
> gstreamer update to 1.22.4

- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rustc-snapshot/package.mk
- Update rust build to be built on arm and aarch64
- Update llvm build to be built on arm and aarch64
- Fixes #7937
> Update rust and llvm build to be built on arm and aarch64.

- packages/network/iwd/package.mk
> iwd: update to 2.6

- tools/docker/jammy/Dockerfile
Testing with Ampere A1 - build was failing `checkdeps` on Rockchip and Amlogic images
- This has been tested with `actions`.
- Required for build of Amlogic and Rockchip images
- Fixes checkdeps requirement for: qemu-user-binfmt and libc6:amd64
https://github.com/LibreELEC/LibreELEC.tv/blob/5755426aea7b892389cb165c3bf3ceb9a484c8ef/scripts/checkdeps#L95-#L105
- There is a further build issue using a aarch64 build host - #7926 - tracking separately
> tools/docker: jammy: support qemu amd64 on aarch64

- packages/mediacenter/LibreELEC-settings/package.mk
Only noticeable change for users is a bugfix for setting the hostname via the addon on new installs where `/storage/.cache/hostname` does not already exist.
> LibreELEC-settings: update to b920d5d

- packages/network/iwd/package.mk
Fix issue with handling FT-8021X and SHA256 PMKID derivation.
> iwd: update to 2.7

- packages/network/samba/package.mk
Changes since 4.17.8
o  Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
* BUG 15404: Backport --pidl-developer fixes.
o  Ralph Boehme <slow@samba.org>
* BUG 15275: smbd_scavenger crashes when service smbd is stopped.
* BUG 15378: vfs_fruit might cause a failing open for delete.
o  Samuel Cabrero <scabrero@samba.org>
* BUG 14030: named crashes on DLZ zone update.
o  Volker Lendecke <vl@samba.org>
* BUG 15361: winbind recurses into itself via rpcd_lsad.
* BUG 15382: cli_list loops 100% CPU against pre-lanman2 servers.
* BUG 15391: smbclient leaks fds with showacls.
o  Stefan Metzmacher <metze@samba.org>
* BUG 15374: aes256 smb3 encryption algorithms are not allowed in smb3_sid_parse().
* BUG 15413: winbindd gets stuck on NT_STATUS_RPC_SEC_PKG_ERROR.
o  Jones Syue …
> [le12] samba: update to 4.17.9

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/tools/dotnet-runtime/package.mk
Release notes:
- https://github.com/moby/moby/releases/tag/v24.0.3
> docker: update to 24.0.3 and addon (3)

- packages/python/graphics/Pillow/patches/Pillow-0002-Fix-missing-symbols-as-libtiff-can-depend-on-libjpeg.patch
- packages/textproc/libxslt/package.mk
- Pillow: Fix missing symbols as libtiff can depend on libjpeg
- https://github.com/python-pillow/Pillow/pull/7269
- https://github.com/python-pillow/Pillow/pull/7270
- https://forum.libreelec.tv/thread/27288-addons-script-embuary-helper-and-script-litebox-are-broken-with-package-updates/
- libxslt: update SHA256 and URL
> Fixes for Pillow and update libxslt package SHA256 

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/service/docker/package.mk
log:
- https://github.com/moby/moby/compare/v24.0.3...v24.0.4
Fix a regression introduced during 24.0.3 that causes a panic during live-restore of containers with bind mounts.
> [le12] docker: update to 24.0.4 and addon (2)

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.257
- vulkan-loader: update to 1.3.257
- vulkan-tools: update to 1.3.257
> Vulkan update to 1.3.257

- packages/linux/package.mk
- Includes security fix for StackRot (6.1.37) - https://www.openwall.com/lists/oss-security/2023/07/05/1
> [le11] linux: update to 6.1.y

- packages/addons/addon-depends/system-tools-depends/stress-ng/patches/stress-ng-0001-workaround-cross-compilation-issue.patch
- ref: https://github.com/ColinIanKing/stress-ng/issues/300
- fixes #7981
> stress-ng: workaround cross compilation issue since 0.15.09

- packages/graphics/mesa/package.mk
ann:
- https://lists.freedesktop.org/archives/mesa-announce/2023-July/000724.html
```
Generic.x86_64-devel-20230721150033-4ee7ae7
Linux nuc12 6.5.0-rc2 #1 SMP Fri Jul 21 09:26:04 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA2 (20.90.201) Git:21.0a2-Omega). Platform: Linux x86 64-bit
Kodi compiled 2023-07-17 by GCC 13.1.0 for Linux x86 64-bit version 6.5.0 (394496)
Running on LibreELEC (heitbaum): devel-20230721150033-4ee7ae7 12.0, kernel: Linux x86 64-bit version 6.5.0-rc2 …
```
> mesa: update to 23.1.4

- packages/addons/addon-depends/go/package.mk
- packages/devel/cmake/package.mk
- packages/devel/fakeroot/package.mk
- packages/python/devel/meson/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rust-std-snapshot: update to 1.71.0
- cargo-snapshot: update to 1.71.0
- rustc-snapshot: update to 1.71.0
- rust: update to 1.71.0
- fakeroot: update to 1.32.1
- go: update to 1.20.6
- cmake: update to 3.27.0
- meson: update to 1.2.0
> Development tool package updates

- tools/distro-tool
- tools/update-scan
- tools/update-scan: include short (7 digit) githash when Commit date displayed
- tools/update-scan: always check github for version if pkg_version is a githash
- tools/update-scan: handle some corner cases
- tools/distro-tool: Fix python3.10 threading DeprecationWarnings
> Support Tools Updates

- packages/network/samba/package.mk
```
===============================
Release Notes for Samba 4.17.10
July 19, 2023
===============================
o CVE-2022-2127:  When winbind is used for NTLM authentication, a maliciously
crafted request can trigger an out-of-bounds read in winbind
and possibly crash it.
https://www.samba.org/samba/security/CVE-2022-2127.html
o CVE-2023-3347:  SMB2 packet signing is not enforced if an admin configured
"server signing = required" or for SMB2 connections to Domain
Controllers where SMB2 packet signing is mandatory.
https://www.samba.org/samba/security/CVE-2023-3347.html
o CVE-2023-34966: An infinite loop bug in Samba's mdssvc RPC service for
Spotlight can be triggered by an unauthenticated attacker by
issuing a …
```
> [le12] samba: update to 4.17.10

- packages/security/gnutls/package.mk
- packages/security/nettle/package.mk
- packages/security/nettle/patches/nettle-0001-host-lib64.patch
- packages/textproc/libidn2/package.mk
- packages/tools/amlogic-boot-fip/package.mk
- packages/tools/u-boot-tools/package.mk
Use architecture independent u-boot-tools configuration. 
- https://u-boot.readthedocs.io/en/latest/build/tools.html
> Fix AMLGX build on aarch64 

- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
- projects/RPi/patches/kodi/0001-gbm-Set-max-bpc-for-high-bit-depth-videos.patch
- projects/RPi/patches/kodi/0002-CDVDVideoCodecDRMPRIME-Also-support-YUV420-buffers.patch
- projects/RPi/patches/kodi/0003-CDVDVideoCodecDRMPRIME-Adjust-av-formats-to-match-re.patch
- projects/RPi/patches/kodi/0004-DVDVideoCodecDRMPRIME-Add-support-for-arbitrary-outp.patch
- projects/RPi/patches/kodi/0005-DVDVideoCodecDRMPRIME-Remove-obsolete-thread_safe_ca.patch
- projects/RPi/patches/kodi/0006-DVDVideoCodecDRMPRIME-Clear-m_pFilterGraph.patch
- projects/RPi/patches/kodi/0007-DVDVideoCodecDRMPRIME-Move-FilterTest-from-open-to-f.patch
- projects/RPi/patches/kodi/0008-DVDVideoCodecDRMPRIME-Rework-filtering-code-to-handl.patch
- projects/RPi/patches/kodi/0009-VideoPlayer-ffmpeg-change-default-software-deinterla.patch
- projects/RPi/patches/kodi/0010-CDVDVideoCodecDRMPRIME-Support-decoding-to-DRMPRIME-.patch
- projects/RPi/patches/kodi/0011-DVDVideoCodecDRMPRIME-Request-v4l2-buffers-be-alloca.patch
- projects/RPi/patches/kodi/0012-DVDVideoCodecDRMPRIME-Add-setting-to-enable-hw-deint.patch
This add's Kodi PR https://github.com/xbmc/xbmc/pull/23298 to use bwdif instead of yadif for SW deinterlace, adds an option to disable HW deinterlace in kodi's player settings and updates the ffmpeg patch to add NEON optimized bwdif deinterlace.
With HD content bwdif deinterlace quality is superior to HW deinterlace so disabling HW deinterlace (which is still enabled by default) should result in better quality.
> RPi: add support for bwdif deinterlace

- packages/devel/fakeroot/patches/fakeroot-002-fix-missing-header-file-race-condition-1041674.patch
Unable to reproduce the build issue on my buildhost, but believe the proposed patch attached should fix the build issue on the GHA CI/CD. 
- https://github.com/LibreELEC/actions/actions/runs/5623416630/job/15238056958
ref:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041674
> fakeroot: fix missing header file race condition

- packages/mediacenter/kodi-binary-addons/game.libretro.dosbox-pure/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.dosbox/package.mk
This PR updates the two existing dosbox cores, dosbox and dosbox-pure, with buttonmaps added/corrected upstream:
* https://github.com/kodi-game/game.libretro.dosbox/pull/14
* https://github.com/kodi-game/game.libretro.dosbox-pure/pull/1
Successfully compiled both dosbox cores for Generic x86.
> [le12] Update dosbox game add-ons with new buttonmaps

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.259
- vulkan-loader: update to 1.3.259
- vulkan-tools: update to 1.3.259
glslang
- spirv-headers: update to githash f1ba373
- spirv-tools: update to githash 4b6bd5a
- glslang: update to 12.3.1
> Vulkan and glslang updates

- packages/linux/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
Also enable the pwn-fan kernel module which is required to control the fan on the POE HAT
> linux (RPi): update to 6.1.42

- packages/security/openssl/package.mk
> [le12] openssl: update to 3.1.2

- packages/security/openssl/package.mk
> [le11] openssl: update to 3.0.10

- packages/debug/libunwind/package.mk
- packages/devel/cmake/package.mk
- packages/devel/mold/package.mk
- packages/lang/gcc/package.mk
- gcc: update to 13.2.0
- mold: update to 2.0.0 and license change to MIT
- cmake: update to 3.27.1
- libunwind: update to 1.7.2
> Toolchain package updates

- packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
use explicit cast to ADDON::LE_ADDON_CONTEXT when formatting
this patch is required in addition to kodi PR23453 to build with libfmt-10
ref: https://github.com/xbmc/xbmc/pull/23453
future PR will be raised for libfmt-10 which will require updated spdlog
> Fix building with fmt >= 10

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/package.mk
Release notes: 
- https://github.com/moby/moby/releases/tag/v24.0.5
Updates:
- cli: update to 24.0.5
- containerd: update to 1.7.3
- docker: update to 24.0.5 and addon (1)
- go: update to 1.20.7
- moby: update to 24.0.5
- runc: update to 1.1.8
> [le12] docker: update to 24.0.5 and addon (1)

- packages/addons/addon-depends/ffmpegx/patches/fmpegx-0001-Fixes-assembling-with-binutils-as-2.41.patch
- packages/audio/alsa-utils/patches/alsa-utils-PR225.patch
- packages/devel/binutils/package.mk
- packages/devel/glibc/package.mk
- packages/multimedia/ffmpeg/patches/fmpegx-0001-Fixes-assembling-with-binutils-as-2.41.patch
- packages/network/libdnet/package.mk
- glibc: update to 2.38
- alsactl: add define to compile with glibc 2.38
- https://github.com/alsa-project/alsa-utils/pull/225
- libdnet: update to compile with glibc 2.38
- binutils: update to 2.41
> glibc update to 2.38 and binutils 2.41

- packages/network/samba/package.mk
- Backport of #7970
- Backport of #8000
Changes since 4.17.8
o  Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
* BUG 15404: Backport --pidl-developer fixes.
o  Ralph Boehme <slow@samba.org>
* BUG 15275: smbd_scavenger crashes when service smbd is stopped.
* BUG 15378: vfs_fruit might cause a failing open for delete.
o  Samuel Cabrero <scabrero@samba.org>
* BUG 14030: named crashes on DLZ zone update.
o  Volker Lendecke <vl@samba.org>
* BUG 15361: winbind recurses into itself via rpcd_lsad.
* BUG 15382: cli_list loops 100% CPU against pre-lanman2 servers.
* BUG 15391: smbclient leaks fds with showacls.
o  Stefan Metzmacher <metze@samba.org>
* BUG 15374: aes256 smb3 encryption algorithms are not allowed in smb3_sid_parse().
* BUG 15413: winbindd gets stuck on …
> [le11] samba: update to 4.17.10

- packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20230808
on ADL `[    0.000000] microcode: updated early: 0x42a -> 0x42c, date = 2023-04-18`
> intel-ucode: update to 20230808

- packages/devel/ccache/patches/ccache-0001-work-around-gcc-12-3-bug-109241.patch
ref:
- https://github.com/ccache/ccache/commit/689168c292f1ed26c5f4a3070aeb649dad7facb5
- Fixes #8047
> ccache: fix: Work around GCC 12.3 bug 109241

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
This cleans up the bug-report template a little, and we add links for general help and feature requests that take users to the forum. See https://github.com/python/cpython/issues/new/choose for an example of the latter.
> templates: issue template improvements and links

- packages/addons/addon-depends/opus/package.mk
Issues building opus (using meson) with arm fixed point.
- FIXED: https://github.com/xiph/opus/issues/273
- PROPOSED: https://github.com/xiph/opus/pull/296
- STILL AN ISSUE: https://github.com/xiph/opus/issues/295 (further issues once this is fixed) with the include
- backport of #8065
> [le11] opus: revert to using configure

- packages/addons/addon-depends/libzip/package.mk
Fixes:
- https://github.com/nih-at/libzip/issues/399
- https://github.com/nih-at/libzip/pull/400
- https://github.com/nih-at/libzip/commit/ccf2ce42926c04648da8fda3c9cfdb7805aa4894
corner case issue in libzip when zstd is not included and private libraries are included.
impacts build of vdr-plugin-xmltv2vdr
> [le12] libzip: update to 1.10.1 (fixes bug introduced in 1.10.0 for static builds)

- packages/lang/Python3/package.mk
Announcement:
- https://pythoninsider.blogspot.com/2023/08/python-3115-31013-3918-and-3818-is-now.html 
```
Python Version: 3.11.5 (main, Aug 25 2023, 12:43:15) [GCC 13.2.0]
Generic.x86_64-devel-20230825122859-af08c28
Linux nuc12 6.5.0-rc7 #1 SMP Fri Aug 25 12:50:16 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA2 (20.90.201) Git:f5ab9fd5d2d6d3589470208a774bbfa757a63ee9). Platform: Linux x86 64-bit
Kodi compiled 2023-08-25 by GCC 13.2.0 for Linux x86 64-bit version 6.5.0 (394496)
Running on LibreELEC (heitbaum): devel-20230825122859-af08c28 12.0, kernel: Linux x86 64-bit version 6.5.0-rc7
[    0.000000] DMI: Intel(R) Client Systems …
```
> Python3: update to 3.11.5

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Announcement:
- https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html
updates:
- cargo-snapshot: update to 1.72.0
- rustc-snapshot: update to 1.72.0
- rust-std-snapshot: update to 1.72.0
- rust: update to 1.72.0
> rust: update to 1.72.0

- packages/addons/addon-depends/libzip/package.mk
> [le11] libzip: update to 1.10.1 (fixes bug introduced in 1.10.0 for static builds)

- packages/devel/flatbuffers/package.mk
- packages/devel/libfmt/package.mk
- packages/devel/spdlog/package.mk
- libfmt: update to 10.1.0
- https://github.com/fmtlib/fmt/releases/tag/10.0.0
- https://github.com/fmtlib/fmt/releases/tag/10.1.0
- https://github.com/fmtlib/fmt/releases/tag/10.1.1
- spdlog: update to 1.12.0
- https://github.com/gabime/spdlog/releases/tag/v1.12.0
- flatbuffers: update to 23.5.26
Dependant on 
- #7951
- https://github.com/xbmc/xbmc/pull/23453
> Update libfmt to 10.1.1 with spdlog 1.12.0

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- glslang: update to 13.0.0
- spirv-headers: update to githash 124a966
- spirv-tools: update to githash 89ca3aa
- vulkan-headers: update to 1.3.262
- vulkan-loader: update to 1.3.262
- vulkan-tools: update to 1.3.262
> Vulkan update to 1.3.262

- packages/sysutils/busybox/system.d/var-log.mount
- packages/sysutils/systemd/system.d/machine-id.service
machine-id.service fix for:
```
systemd[1]: local-fs.target: Found ordering cycle on local-fs-pre.target/start
systemd[1]: local-fs.target: Found dependency on systemd-tmpfiles-setup-dev.service/start
systemd[1]: local-fs.target: Found dependency on machine-id.service/start
systemd[1]: local-fs.target: Found dependency on local-fs.target/start
systemd[1]: local-fs.target: Job local-fs-pre.target/start deleted to break ordering cycle starting with local-fs.target/start
```
Resolve #8077
var-log.mount fix for:
```
systemd[1]: local-fs.target: Found ordering cycle on var-log.mount/start
systemd[1]: local-fs.target: Found dependency on local-fs-pre.target/start
systemd[1]: local-fs.target: Found dependency on systemd-tmpfiles-setup-dev.service/start
systemd[1]: local-fs.target: Found …
```
> systemd/busybox: fix unit permissions after systemd v254 bump

- packages/network/wireless-regdb/package.mk
> wireless-regdb: update to 2023.09.01
