packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
Same issue as @vpeter4 discovered with
- #7232
=> visualization.pictureit: update 20.0.0-Nexus to 20.2.0-Nexus

packages/addons/addon-depends/snapcast-depends/shairport-sync/package.mk, packages/addons/service/snapserver/package.mk
- shairport-sync: update to 4.1.1
- snapserver: update shairport-sync to 4.1.1 and addon (1)
=> snapserver: update shairport-sync to 4.1.1 and addon (1)

packages/addons/addon-depends/chrome-depends/libXft/package.mk, packages/x11/xserver/xorg-server/package.mk
- xorg-server: update to 21.1.5
- libXft: update to 2.3.7
=> X11 updates

packages/graphics/vulkan/glslang/package.mk, packages/graphics/vulkan/glslang/patches/glslang-100.01-build-static-spirv-tools.patch
- clean up & fix target build
- build & run tested for packages which rely on host & target builds
=> glslang: updated for target build

packages/compress/xz/package.mk
Update to latest stable
news:
- https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;hb=HEAD
=> xz: update to 5.4.0

config/show_config
- get rid of leading whitespace
- according to https://ccache.dev/ it's "Ccache"
=> config/show_config: minor clean up

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk, packages/linux-firmware/wlan-firmware/package.mk
- wlan-firmware: update to githash 4d3eab2b (2022-11-16)
- brcmfmac_sdio-firmware: update to githash 528134d7 (2022-12-05)
=> wlan firmwares

packages/wayland/weston/package.mk
ann:
- https://lists.freedesktop.org/archives/wayland-devel/2022-December/042538.html
=> weston: update to 11.0.1

packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v252.3...v252.4
=> systemd: update to 252.4

packages/addons/service/minisatip/package.mk
log:
- https://github.com/catalinii/minisatip/compare/v1.2.36...v1.2.49
Backport of
- #7272
=> minisatip: update to 1.2.49 and addon (113)

packages/addons/service/minisatip/package.mk
log:
- https://github.com/catalinii/minisatip/compare/v1.2.36...v1.2.49
=> minisatip: update to 1.2.49 and addon (1)

packages/addons/service/tvheadend42/patches/tvheadend42-06-satip-upnp-fix.patch
- backport from tvheadend43: https://github.com/tvheadend/tvheadend/pull/1448
=> tvheadend42: SAT>IP client: UPnP header field names are case insensitive

packages/addons/addon-depends/vdr/package.mk, packages/addons/service/vdr-addon/package.mk
- vdr-addon: update to 2.6.3 and addon (2)
- vdr: update to 2.6.3
=> vdr-addon: update to 2.6.3 and addon (2)

packages/tools/amlogic-boot-fip/package.mk
=> amlogic-boot-fip: update to 36f258b8 (2022-12-24)

packages/devel/glibc/package.mk
Update enable kernel to 6.0 (until Amlogic changes) then will set to 6.1.
=> glibc: update enable-kernel=6.0.0

packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk, packages/addons/tools/multimedia-tools/package.mk
- libmediainfo: update to 22.12
- libzen: update to 0.4.40
- mediainfo: update to 22.12
=> multimedia-tools: update to mediainfo 22.12 and addon (2)

packages/devel/mimalloc/package.mk
log:
- https://github.com/microsoft/mimalloc/compare/v2.0.7...v2.0.9
(Only used by mold)
=> mimalloc: update to 2.0.9

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/addon-depends/docker/moby/patches/moby-001-user-addon-storage-location.patch, packages/addons/service/docker/package.mk
- docker: update to 23.0.0-rc.1 and addon (3)
- cli: update to 23.0.0-rc.1
- moby: update to 23.0.0-rc.1
=> docker: update to 23.0.0-rc.1 and addon (3)

packages/mediacenter/kodi/package.mk
just unpack tested, not build tested
=> kodi: update to 19.5

packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
backporting the same addition from master to complete a forum request.
=> systemd: add xaomi remote to 70-local-keyboard.hwdb

packages/addons/addon-depends/snapcast-depends/snapcast/patches/snapcast-03_boost.patch, packages/addons/service/mpd/patches/mpd-1682.patch
mpd: patch to support boost 1.81.0
- https://github.com/MusicPlayerDaemon/MPD/issues/1693
snapcast: patch to support boost 1.81.0
- https://github.com/badaix/snapcast/issues/1082
- https://github.com/badaix/snapcast/pull/1084
=> Boost 1.81.0 fixes

packages/network/connman/package.mk
=> connman: minor changes

packages/devel/mold/package.mk
Release notes:
- https://github.com/rui314/mold/releases/tag/v1.9.0
=> mold: update to 1.9.0

packages/devel/glib/package.mk
changelog:
- https://gitlab.gnome.org/GNOME/glib/-/commit/ec3b1bfc45216850c1a861055ad2fd9d9906813a
=> glib: update to 2.75.2

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/tools/ffmpeg-tools/package.mk
- [ffmpegx: update to 4.4.2](https://github.com/LibreELEC/LibreELEC.tv/commit/94eb3465fc3703a08b4989045500a3790dd8a9c3)
=> [le11] ffmpeg-tools: update ffmpeg to 4.4.2 and addon (2)

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/tools/ffmpeg-tools/changelog.txt, packages/addons/tools/ffmpeg-tools/package.mk
=> [LE10] ffmpeg-tools: update ffmpeg to 4.4.2 and addon (119)

packages/addons/addon-depends/ffmpegx/package.mk, packages/addons/tools/ffmpeg-tools/package.mk
- [ffmpegx: update to 4.4.3](https://github.com/LibreELEC/LibreELEC.tv/commit/258c695d5fee6d5004c7947eec9c0bab98f44a51)
=> [le11] ffmpeg-tools: update ffmpeg to 4.4.3 and addon (3)

packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk, packages/addons/addon-depends/chrome-depends/unix_ar/package.mk, packages/addons/browser/chrome/package.mk, packages/addons/browser/chrome/source/bin/chrome-downloader, packages/addons/browser/chrome/source/bin/deb_extract_data, packages/addons/browser/chrome/source/default.py
- chrome: update 109.0.5414.74 and addon (1)
=> [le11] chrome: update to 109.0.5414.74 and addon (1)

packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/163489ab935b1b9ebdd3a6983aadc6cd28e8cd48/docs/relnotes/22.3.3.rst
=> mesa: update to 22.3.3

packages/compress/xz/package.mk
release notes:
- https://github.com/tukaani-project/xz/releases/tag/v5.4.1
=> xz: update to 5.4.1

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/containerd/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/addon-depends/docker/moby/patches/moby-001-user-addon-storage-location.patch, packages/addons/service/docker/package.mk
- cli: update to cli-23.0.0-rc.2
- containerd: update to 1.6.15
- moby: update to 23.0.0-rc.2
=> [le11] docker: update addon (4)

packages/addons/service/nextpvr/changelog.txt, packages/addons/service/nextpvr/package.mk, packages/addons/service/nextpvr/source/bin/nextpvr-downloader, packages/addons/service/nextpvr/source/settings-default.xml
=> nextpvr: add default settings file

packages/addons/service/minisatip/package.mk
log:
- https://github.com/catalinii/minisatip/compare/v1.2.49...v1.2.56
=> minisatip: update to 1.2.56 and addon (2)

packages/addons/service/minisatip/package.mk
log:
- https://github.com/catalinii/minisatip/compare/v1.2.49...v1.2.56
- Backport of #7382
=> minisatip: update to 1.2.56 and addon (114)

packages/addons/addon-depends/system-tools-depends/file/package.mk, packages/python/devel/waf/package.mk
Used in addon builds
- waf: update to 2.0.25
- file: update to 5.44
=> Addon build tool updates

packages/graphics/libheif/package.mk, packages/graphics/libpng/package.mk, packages/graphics/libraw/package.mk
- libraw: update to 0.21.1
- libheif: update to 1.14.2
- libpng: update to 1.6.39
=> Image format package updates

packages/linux-firmware/kernel-firmware/package.mk
=> kernel-firmware: update to 20230117

packages/databases/mariadb-connector-c/package.mk
release notes:
- https://mariadb.com/kb/en/mariadb-connector-c-3-3-3-release-notes/
- https://mariadb.com/kb/en/mariadb-connector-c-3-3-3-changelog/
- https://github.com/mariadb-corporation/mariadb-connector-c/compare/v3.3.2...v3.3.3
=> mariadb-connector-c: update to 3.3.3

packages/devel/mold/package.mk
- https://github.com/rui314/mold/releases/tag/v1.10.0
- https://github.com/rui314/mold/releases/tag/v1.10.1
=> mold: update to 1.10.1

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
- cli: update to 23.0.0-rc.3
- moby: update to 23.0.0-rc.3
=> docker: update to 23.0.0-rc.3 and addon (1)

packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/relnotes/22.3.4.rst
=> mesa: update to 22.3.4

projects/Allwinner/devices/H2-plus/patches/u-boot/0007-sunxi-psci-Add-support-for-H3-CPU-0-hotplug.patch, projects/Allwinner/devices/H2-plus/patches/u-boot/0010-sunxi-Enable-support-for-SCP-firmware-on-H3.patch
This fixes build issue for H2+ board.
=> Allwinner: u-boot: Add missing patches for H2+

packages/sysutils/systemd/package.mk
changelog:
- https://github.com/systemd/systemd-stable/compare/v252.4...v252.5
=> systemd: update to 252.5

packages/sysutils/e2fsprogs/package.mk
commit 1.46.6:
- https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?h=maint&id=0127761a94aac2183c46448b34e052006c45b246 
commit 1.46.6-rc1:
- https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?h=maint&id=8e70bf2a1c2998b0580ac55c97ffb00983bfc80d
=> e2fsprogs: update to 1.46.6

packages/network/openssh/package.mk
release notes:
- https://www.openssh.com/releasenotes.html#9.2p1
log:
- https://github.com/openssh/openssh-portable/compare/V_9_1_P1...V_9_2_P1
=> openssh: update to 9.2p1

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk, packages/wayland/lib/hwdata/package.mk
- vulkan-headers: update to 1.3.240
- vulkan-loader: update to 1.3.240
- vulkan-tools: update to 1.3.240
- hwdata: update to 0.367
=> Vulkan and Wayland updates

licenses/7-Zip.txt, packages/addons/tools/system-tools/package.mk, packages/addons/tools/system-tools/source/bin/7z, packages/addons/tools/system-tools/source/bin/7za, packages/compress/7-zip/package.mk
- 7-zip: initial package
- system-tools: migrate from p7zip to 7-zip and addon (2)
=> [le11] system-tools: migrate from p7zip to 7-zip and addon (2)

packages/linux-drivers/RTL8812AU/package.mk
Log:
- https://github.com/astsam/rtl8812au/compare/450db78f7bd23f0c611553eb475fa5b5731d6497...d98018d038a5db96066e79f26ed4a72f2fe1774e
=> RTL8812AU: update to githash 20230204

packages/linux/package.mk
=> linux (RPi): update to 6.1.10

packages/addons/service/mariadb/package.mk
Release notes:
- https://mariadb.com/kb/en/mariadb-10-10-3-release-notes/
=> mariadb: update to 10.10.3

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
=> inputstream.adaptive: update to 20.3.3-Nexus

packages/devel/glibc/patches/arm/glibc-HACK-Don-t-check-GLIBC_ABI_DT_RELR-support-for-Chrom.patch, packages/devel/glibc/patches/arm/glibc-tls-libwidevinecdm.so-since-4.10.2252.0-has-TLS-with.patch
=> Document more context around widevine glibc patches

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
release notes:
- https://github.com/moby/moby/releases/tag/v23.0.1
=> docker: update to 23.0.1 and addon (1)

packages/wayland/compositor/sway/package.mk, packages/wayland/lib/wlroots/package.mk
- wlroots: update to 0.16.2
- https://gitlab.freedesktop.org/wlroots/wlroots/-/compare/0.16.1...0.16.2
- sway: update to 1.8.1
- https://github.com/swaywm/sway/releases/tag/1.8.1
- https://github.com/swaywm/sway/compare/1.8...1.8.1
=> Wayland updates

projects/Allwinner/patches/linux/0105-ARM-dts-sun8i-r40-Add-interconnect-to-video-codec.patch
Fix for HW video decoding on R40.
=> [LE11] Allwinner: linux: Fix HW decoding on R40

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk
Firmware update should fix issue with @chewitt 's video
Runtime tested on RPi3B+ and RPi4
=> linux (RPi): update to 6.1.12

packages/addons/service/minisatip/package.mk
Log
- https://github.com/catalinii/minisatip/compare/v1.2.56...v1.2.84
=> minisatip: update to 1.2.84

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.241
- vulkan-loader: update to 1.3.241
- vulkan-tools: update to 1.3.241
=> Vulkan update to 1.3.241

packages/python/devel/meson/package.mk
log:
- https://github.com/mesonbuild/meson/compare/0.64.1...1.0.0
- https://github.com/mesonbuild/meson/compare/1.0.0...1.0.1
- https://mesonbuild.com/Release-notes-for-1-0-0.html
=> meson: update to 1.0.1

packages/devel/libcap-ng/package.mk, packages/network/openvpn/package.mk
- openvpn: update to 2.6.0
- libcap-ng: initial package
=> openvpn: update to 2.6.0

packages/security/nss/package.mk
release notes:
- https://hg.mozilla.org/projects/nss/file/tip/doc/rst/releases/nss_3_88.rst
- https://hg.mozilla.org/projects/nss/file/tip/doc/rst/releases/nss_3_88_1.rst
=> nss: update to 3.88.1

packages/tools/grub/package.mk, packages/tools/grub/patches/grub-0003-util-mkimage--Fix-dangling-pointer-may-be-used-error.patch, packages/tools/grub/patches/grub-gnulib-regcomp.patch
- enable build of grub:host with HOST_CC=gcc-12.2.0
=> grub: update to 2.06

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk, packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk, packages/mediacenter/kodi-binary-addons/peripheral.xarcade/package.mk, packages/mediacenter/kodi-binary-addons/pvr.freebox/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk, packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk, packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk, packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
A couple of addons already have separate Omega versions, so let's use those
=> kodi-binary-addons: update to latest Omega versions

packages/devel/glib/package.mk
changelog:
- https://gitlab.gnome.org/GNOME/glib/-/commit/b65044c52b78fab65a0415e2148f4b98a1680da2
=> glib: update to 2.75.3

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.1
- gst-plugins-base: update to 1.22.1
- gstreamer: update to 1.22.1
=> gstreamer: update to 1.22.1

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.242
- vulkan-loader: update to 1.3.242
- vulkan-tools: update to 1.3.242
=> Vulkan: update to 1.3.242

packages/devel/glib/package.mk
Changelog:
- https://gitlab.gnome.org/GNOME/glib/-/commit/084a35620c1d886650223555c4dd647824c0ce64
=> [le12] glib: update to 2.75.4

packages/graphics/mesa/package.mk
Last interaction of mesa 22.
- https://docs.mesa3d.org/relnotes/22.3.7.html
=> [le12] mesa: update to 22.3.7

packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v252.6...v252.7
=> [le12] systemd: update to 252.7

packages/mediacenter/kodi/package.mk
build and runs at generic, unpack fine at rpi
=> kodi: update to 20.1-Nexus

packages/tools/amlogic-boot-fip/package.mk
=> amlogic-boot-fip: update to githash e96b6a6 (2023-03-04)

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/linux/patches/raspberrypi/linux-010-fix-vc4-rgb-check.patch, packages/tools/bcm2835-bootloader/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
=> [le11] linux (RPi): update to 6.1.19-e3376fb

packages/databases/sqlite/package.mk
Release notes:
- https://www.sqlite.org/releaselog/3_41_1.html
=> sqlite: update to 3.41.1

projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0115-WIP-arm64-dts-meson-add-SPI-VFD-to-Sunvell-T95Z-Plus.patch, projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0116-WIP-dt-bindings-arm-amlogic-add-support-for-BananaPi.patch, projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0117-WIP-arm64-dts-meson-add-support-for-BananaPi-M2S-var.patch, projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0118-WIP-arm64-dts-meson-p23x-q20x-fix-usb-init-don-t-for.patch, projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0119-WIP-arm64-dts-meson-add-WiFi-BT-support-to-BananaPi-.patch, projects/Amlogic/devices/AMLGX/patches/linux/amlogic-0120-WIP-media-meson-vdec-fix-memory-leak-of-new_frame.patch
Minor bump to correct the VFD display on the T95Z (S912) box for 11.0.1
=> linux: update Amlogic 6.1.y patches

packages/devel/mold/package.mk
release notes:
- https://github.com/rui314/mold/releases/tag/v1.11.0
=> mold: update to 1.11.0

packages/devel/cmake/package.mk
release notes:
- https://cmake.org/cmake/help/latest/release/3.26.html
=> cmake: update to 3.26.0

packages/network/openssh/package.mk
release notes:
- https://www.openssh.com/releasenotes.html#9.3
=> openssh: update to 9.3p1

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.243
- vulkan-loader: update to 1.3.243
- vulkan-tools: update to 1.3.243
=> vulkan: update to 1.3.243

packages/compress/xz/package.mk
ann:
- https://www.mail-archive.com/xz-devel@tukaani.org/msg00635.html
=> xz: update to 5.4.2

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/tools/multimedia-tools/package.mk
- mpg123: update to 1.31.3
- mpv-drmprime: update to 0.35.1
=> [le12] multimedia-tools: update addon to (1)

packages/addons/service/ttyd/package.mk
release notes:
- https://github.com/tsl0922/ttyd/releases/tag/1.7.3
log:
- https://github.com/tsl0922/ttyd/compare/1.7.2...1.7.3
=> [le12] ttyd: update to 1.7.3 and addon (1)

packages/addons/service/mpd/package.mk
release notes:
- https://raw.githubusercontent.com/MusicPlayerDaemon/MPD/v0.23.12/NEWS
log:
- https://github.com/MusicPlayerDaemon/MPD/compare/v0.23.11...v0.23.12
=> [le12] mpd: update to 0.23.12 and addon (1)

packages/debug/gdb/package.mk, packages/debug/gdb/patches/0001-gdbserver-ctrl-c-handling.patch, packages/debug/strace/package.mk
- gdb: update to 13.1
- strace: update to 6.2
=> Debug package updates

packages/wayland/lib/hwdata/package.mk
Changelog:
- https://github.com/vcrhonek/hwdata/compare/v0.367...v0.368
=> hwdata: update to 0.368

packages/graphics/mesa/package.mk
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/23.0/docs/relnotes/23.0.1.rst
=> mesa: update to 23.0.1

packages/security/openssl/package.mk
Changelog:
- https://www.openssl.org/news/cl31.txt
=> openssl: update to 3.1.0

packages/addons/service/tigervnc/package.mk
- should fix #7698
looks better
```
unzip -v target/addons/11.80.0/Generic-legacy/x86_64/service.tigervnc/service.tigervnc-11.80.0.0.zip 
Archive:  target/addons/11.80.0/Generic-legacy/x86_64/service.tigervnc/service.tigervnc-11.80.0.0.zip
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
0  Stored        0   0% 2023-03-26 12:46 00000000  service.tigervnc/
908  Defl:N      462  49% 2023-03-26 12:46 2930faf0  service.tigervnc/addon.xml
0  Stored        0   0% 2023-03-26 12:46 00000000  service.tigervnc/bin/
325  Defl:N      232  29% 2023-03-26 12:46 63f468be  service.tigervnc/bin/tigervnc.start
118224  Defl:N    45946  61% 2023-03-26 12:46 11b277c0  service.tigervnc/bin/vncconfig
31504  Defl:N    12177  61% …
```
=> [le12] tigervnc: copy missing library libXtst to addon directory

packages/devel/cmake/package.mk
Ann:
- https://cmake.org/cmake/help/v3.26/release/3.26.html#id1
=> cmake: update to 3.26.1

packages/rust/cargo-snapshot/package.mk, packages/rust/rust-std-snapshot/package.mk, packages/rust/rust/package.mk, packages/rust/rustc-snapshot/package.mk
Ann:
- https://blog.rust-lang.org/2023/03/23/Rust-1.68.1.html
=> rust: update to 1.68.1

packages/sysutils/tz/package.mk
News:
- https://github.com/eggert/tz/blob/71faa2a55db2c9f21f4099b58c28536673982e0a/NEWS
=> [le12] tz: update to 2023b

packages/addons/addon-depends/ccid/package.mk, packages/addons/service/pcscd/changelog.txt, packages/addons/service/pcscd/package.mk
- backport of #7665 
- ccid: update to 1.5.2
=> [le11] pcscd: rebuild with ccid 1.5.2 and addon (1)

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk, packages/addons/tools/multimedia-tools/changelog.txt, packages/addons/tools/multimedia-tools/package.mk
- backport of #7663
- mpg123: update to 1.31.3
- mpv-drmprime: update to 0.35.1
=> [le11] multimedia-tools: update addon to (1)

packages/addons/addon-depends/network-tools-depends/depends/libpcap/package.mk, packages/addons/addon-depends/network-tools-depends/iperf/package.mk, packages/addons/addon-depends/network-tools-depends/rar2fs/package.mk, packages/addons/addon-depends/network-tools-depends/tcpdump/package.mk, packages/addons/tools/network-tools/changelog.txt, packages/addons/tools/network-tools/package.mk
=> [le11] network-tools: update to addon (1)

packages/debug/libva-utils/package.mk, packages/multimedia/libva/package.mk, packages/multimedia/media-driver/package.mk
- libva: update to 2.18.0
- libva-utils: update to 2.18.1
- media-driver: update to 23.1.5
=> Intel updates

packages/web/curl/package.mk
ann:
- https://daniel.haxx.se/blog/2023/03/20/curl-8-0-0-is-here/
- https://daniel.haxx.se/blog/2023/03/20/curl-8-0-1-because-i-jinxed-it/
=> curl: update to 8.0.1

packages/addons/service/mariadb/changelog.txt, packages/addons/service/mariadb/package.mk, packages/addons/service/mariadb/source/bin/mariadb.start
fixes https://github.com/LibreELEC/LibreELEC.tv/issues/7701
=> mariadb: include mariadb-upgrade and mariadb-check and update addon (1)

packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v253.1...v253.2
=> systemd: update to 253.2

packages/addons/tools/btrfs-progs/package.mk
changes:
- https://btrfs.readthedocs.io/en/latest/CHANGES.html
=> [le12] btrfs-progs: update to 6.2.2 and addon (1)

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.246
- vulkan-loader: update to 1.3.246
- vulkan-tools: update to 1.3.246
=> Vulkan update to 1.3.246

packages/sysutils/systemd/package.mk
log:
- https://github.com/systemd/systemd-stable/compare/v253.2...v253.3
=> systemd: update to 253.3

scripts/build
=> [le11] scripts/build: properly honor strip build flag

packages/graphics/mesa/package.mk
Release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/afd0f404807fb6461ce7b1e37259a96f99291aa9/docs/relnotes/23.0.2.rst
=> mesa: update to 23.0.2

packages/audio/pipewire/package.mk
=> pipewire: update to 0.3.68

packages/linux-firmware/kernel-firmware/package.mk
=> kernel-firmware: update to 20230404

packages/lang/Python3/package.mk, packages/python/graphics/Pillow/package.mk
- Python3: update to 3.11.3
- Pillow: update to 9.5.0
=> Python3: update to 3.11.3

packages/addons/service/syncthing/package.mk
release notes:
- https://github.com/syncthing/syncthing/releases/tag/v1.23.3
- https://github.com/syncthing/syncthing/releases/tag/v1.23.4
log:
- https://github.com/syncthing/syncthing/compare/v1.23.2...v1.23.4
=> [le12] syncthing: update to 1.23.4 and addon (2)

packages/linux/package.mk, packages/linux/patches/default/linux-122-rtw88-USB-fixes2.patch
=> [le11] linux: update to 6.1.y

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.2
- gst-plugins-base: update to 1.22.2
- gstreamer: update to 1.22.2
=> gstreamer: update to 1.22.2

packages/addons/addon-depends/icu/package.mk
ann:
- https://icu.unicode.org/download/73
- https://sourceforge.net/p/icu/mailman/message/37803609/
=> icu: update to 73.1

packages/audio/pipewire/package.mk
=> pipewire: update to 0.3.69

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/package.mk
- https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.16/6.0.16.md?WT.mc_id=dotnet-35129-website
- https://dotnet.microsoft.com/en-us/download/dotnet/6.0
=> [le12] dotnet-runtime: update aspnet6-runtime to 6.0.16

packages/graphics/mesa/package.mk
release notes:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/23.0/docs/relnotes/23.0.3.rst
=> mesa: update to 23.0.3

packages/mediacenter/kodi-binary-addons/inputstream.rtmp/package.mk
Please merge to get pvr iptvsimple installed.
=> inputstream.rtmp: update to 21.0.1-Omega

packages/debug/libva-utils/package.mk, packages/multimedia/media-driver/package.mk
- libva-utils: update to 2.18.2
- media-driver: update to 23.2.0
=> Intel updates 

packages/audio/pipewire/package.mk
Log:
- https://github.com/PipeWire/pipewire/compare/0.3.69...0.3.70
News:
- https://github.com/PipeWire/pipewire/blob/master/NEWS
=> pipewire: update to 0.3.70

packages/addons/addon-depends/rsyslog-depends/libfastjson/package.mk, packages/addons/service/rsyslog/package.mk
- libfastjson: update to 1.2304.0
- rsyslog: update to 8.2304.0
=> rsyslog: update to 8.2304.0 and addon (1)

packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk, packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk, packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk, packages/addons/tools/multimedia-tools/package.mk
- libmediainfo: update to 23.04
- libzen: update to 0.4.41
- mediainfo: update to 23.04
=> [le12] multimedia-tools: update addon (2)

packages/compress/xz/package.mk
News:
- https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;hb=HEAD
Log:
- https://git.tukaani.org/?p=xz.git;a=shortlog;h=refs/heads/v5.4
=> xz: update to 5.4.3

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.250
- vulkan-loader: update to 1.3.250
- vulkan-tools: update to 1.3.250
=> Vulkan update to 1.3.250

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/package.mk
- cli: update to 23.0.5
- docker: update to 23.0.5 and addon (4)
- moby: update to 23.0.5
- runc: update to 1.1.7
=> [le12] docker: update to 23.0.5 and addon (4)

packages/lang/llvm/package.mk
Release notes:
- https://discourse.llvm.org/t/16-0-3-release/70341
=> llvm: update to 16.0.3

packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk, packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
- pvr.iptvsimple: update 21.3.0-Omega to 21.3.1-Omega
- pvr.waipu: update 21.1.0-Omega to 21.2.1-Omega
=> [le12] kodi-binary-addons: update to latest versions

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/changelog.txt, packages/addons/tools/dotnet-runtime/package.mk
- backport of #7616
- backport of #7770
- dotnet-runtime: update aspnet6-runtime to 6.0.16
=> [le11] dotnet-runtime: update aspnet6-runtime to 6.0.16

packages/addons/addon-depends/system-tools-depends/bottom/package.mk, packages/addons/addon-depends/system-tools-depends/diffutils/package.mk, packages/addons/addon-depends/system-tools-depends/htop/package.mk, packages/addons/addon-depends/system-tools-depends/lshw/package.mk, packages/addons/addon-depends/system-tools-depends/mc/package.mk, packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/addon-depends/system-tools-depends/vim/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
=> [le11] system-tools: update to addon (1)

packages/addons/tools/btrfs-progs/changelog.txt, packages/addons/tools/btrfs-progs/package.mk
changes:
- https://btrfs.readthedocs.io/en/latest/CHANGES.html
- Backport of #7711
=> [le11] btrfs-progs: update to 6.2.2 and addon (1)

packages/network/samba/package.mk
ann:
- https://lists.samba.org/archive/samba-announce/2023/000635.html
=> samba: update to 4.17.8

packages/linux-firmware/kernel-firmware/package.mk
=> kernel-firmware: update to 20230515

packages/audio/alsa-lib/package.mk, packages/audio/alsa-ucm-conf/package.mk, packages/audio/alsa-utils/package.mk, packages/audio/alsa-utils/patches/alsa-utils-PR213.patch
Changelog:
- https://www.alsa-project.org/wiki/Changes_v1.2.8_v1.2.9
=> alsa: update to 1.2.9

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/containerd/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
- containerd: update to 1.7.1
- cli: update to 23.0.6
- moby: update to 23.0.6
- docker: update to 23.0.6 and addon (5)
=> [le12] docker: update to 23.0.6 and addon (5)

packages/graphics/vulkan/glslang/package.mk, packages/graphics/vulkan/spirv-headers/package.mk, packages/graphics/vulkan/spirv-tools/package.mk
- glslang: update to 12.2.0
- spirv-headers: update to 268a061
- spirv-tools: update to e7c6084
=> glslang: update to 12.2.0

packages/linux-firmware/intel-ucode/package.mk
Backport of
- #7835
20230516 is a document update from 20230512
=> [le11] intel-ucode: update to 20230516

packages/addons/addon-depends/snapcast-depends/asio/package.mk, packages/addons/addon-depends/snapcast-depends/nqptp/package.mk, packages/addons/addon-depends/snapcast-depends/shairport-sync/package.mk, packages/addons/service/snapclient/package.mk, packages/addons/service/snapserver/package.mk
- asio: update to 1.28.0
- nqptp: update to 1.2.1
- shairport-sync: update to 4.2
- snapclient: update shairport-sync to 4.2 and addon (1)
- snapserver: update shairport-sync to 4.2 and addon (1)
=> [le12] snapclient and snapserver: update shairport-sync to 4.2 and addon (1) 

packages/web/curl/package.mk
changes:
- https://curl.se/changes.html#8_1_2
- https://daniel.haxx.se/blog/2023/05/30/8-1-2-ate-one-too/
- Further update to #7866 and #7860
=> curl: update to 8.1.2

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk, packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.04-fix-glslangValidator-logik.patch
- vulkan-headers: update to 1.3.251
- vulkan-loader: update to 1.3.251
- vulkan-tools: update to 1.3.251
=> vulkan: update to 1.3.251

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk
=> linux (RPi): update to 6.1.31

packages/addons/service/librespot/package.mk
=> [le12] librespot: update to githash c964102 (2023-05-14) and addon (1)

projects/Allwinner/patches/linux/0036-wip-h3-h5-cvbs.patch
close https://github.com/LibreELEC/LibreELEC.tv/issues/7868
=> update allwinner h3 h5 cvbs patch

packages/addons/service/mariadb/package.mk
release notes:
- https://mariadb.com/kb/en/mariadb-10-11-4-release-notes/
=> [le12] mariadb: update to 10.11.4 and addon (1)

packages/linux/package.mk
=> [le11] linux (RPi): update to 6.1.34

packages/addons/service/librespot/changelog.txt, packages/addons/service/librespot/package.mk
=> [le11] librespot: update to githash c964102 (2023-05-14) and addon (2)

packages/devel/ccache/package.mk, packages/lang/llvm/package.mk
- ccache: update to 4.8.2
- llvm: update to 16.0.6
=> Toolchain packages

packages/linux-firmware/intel-ucode/package.mk
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases
=> [le12] intel-ucode: update to 20230613

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.254
- vulkan-loader: update to 1.3.254
- vulkan-tools: update to 1.3.254
=> Vulkan update to 1.3.254

packages/linux-firmware/intel-ucode/package.mk
=> [le11] intel-ucode: update to 20230613

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/package.mk
- dotnet-runtime: update aspnet6-runtime to 6.0.18 and addon (1)
- aspnet6-runtime: update to 6.0.18
=> dotnet-runtime: update aspnet6-runtime to 6.0.18 and addon (1)

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-010.01-pr23411-backport-eac3-fixes.patch
This updates kodi to current Nexus HEAD and adds the E-AC3 fix PR https://github.com/xbmc/xbmc/pull/23411
Runtime tested on RPi4, E-AC3 passthrough finally works fine
=> [le11] kodi: update to latest Nexus version and add E-AC3 fix backport PR

packages/graphics/mesa/package.mk
Ann:
- https://lists.freedesktop.org/archives/mesa-announce/2023-June/000723.html
=> mesa: update to 23.1.3

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.255
- vulkan-loader: update to 1.3.255
- vulkan-tools: update to 1.3.255
=> vulkan: update to 1.3.255

packages/network/connman/package.mk, packages/network/iwd/package.mk
- iwd: update to 2.6
- connman: update to 24180d1 (1.41+/2023-04-11)
=> [le11] update iwd and connman

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/changelog.txt, packages/addons/tools/dotnet-runtime/package.mk
=> dotnet-runtime: update to aspnet6-runtime 6.0.19 and addon (4)

packages/linux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
=> linux (RPi): update to 6.1.38

packages/linux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
=> [le11] linux (RPi): update to 6.1.38

packages/multimedia/libva/package.mk, packages/multimedia/media-driver/package.mk
- media-driver: update to 23.3.0
- libva: update to 2.19.0
=> Intel package updates

packages/graphics/libprojectM/package.mk, packages/graphics/libprojectM/patches/0001-add-enable-gl-switch.patch, packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
See title.
Not runtime tested yet.
=> visualization.projectm: allow building for arm and OpenGLES 

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.5
- gst-plugins-base: update to 1.22.5
- gstreamer: update to 1.22.5
=> gstreamer: update to 1.22.5

packages/audio/pipewire/package.mk, packages/compress/libarchive/package.mk, packages/devel/libbpf/package.mk, packages/devel/libpthread-stubs/package.mk, packages/multimedia/gmmlib/package.mk, packages/network/libnftnl/package.mk, packages/sysutils/systemd/package.mk, packages/web/nghttp2/package.mk
- libpthread-stubs: update to 0.5
- libarchive: update to 3.7.0
- systemd: update to 253.7
- nghttp2: update to 1.55.1
- gmmlib: update to 22.3.9
- pipewire: update to 0.3.74
- libbpf: update to 1.2.2
- libnftnl: update to 1.2.6
=> package updates 

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/changelog.txt, packages/addons/tools/dotnet-runtime/package.mk
=> [le11] dotnet-runtime: update to aspnet6-runtime 6.0.20 and addon (5)

packages/linux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf
=> [le11] linux (RPi): update to 6.1.42

packages/rust/cargo-snapshot/package.mk, packages/rust/rust-std-snapshot/package.mk, packages/rust/rust/package.mk, packages/rust/rustc-snapshot/package.mk
Release notes:
- https://blog.rust-lang.org/2023/08/03/Rust-1.71.1.html
=> rust: update to 1.71.1

packages/addons/addon-depends/system-tools-depends/depends/libssh2/package.mk, packages/addons/addon-depends/system-tools-depends/file/package.mk, packages/addons/addon-depends/system-tools-depends/pv/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/tools/system-tools/package.mk
system-tools: update addon (1)
- file: update to 5.45
- libssh2: dont build shared library
- fix build of mc
- pv: update to 1.7.24
- unrar: update to 6.2.10
=> [le12] system-tools: update addon (1)

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.260
- vulkan-loader: update to 1.3.260
- vulkan-tools: update to 1.3.260
=> Vulkan update to 1.3.260

packages/addons/addon-depends/system-tools-depends/depends/libssh2/package.mk, packages/addons/addon-depends/system-tools-depends/file/package.mk, packages/addons/addon-depends/system-tools-depends/pv/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
=> [le11] system-tools: update addon (3)

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.261
- vulkan-loader: update to 1.3.261
- vulkan-tools: update to 1.3.261
=> Vulkan update to 1.3.261

packages/linux/package.mk
=> linux: update to 6.1.45

packages/tools/bcm2835-utils/package.mk, packages/tools/bcmstat/package.mk, projects/RPi/options
=> update RPi tools packages

packages/compress/pigz/package.mk
ann:
- https://zlib.net/pipermail/pigz-announce_zlib.net/2023-August/000018.html
=> pigz: update to 2.8

packages/network/connman/package.mk, packages/network/iwd/package.mk
- connman: update to githash ff10176
- iwd: update to 2.8
=> iwd and connman updates

packages/multimedia/media-driver/package.mk
Log:
- https://github.com/intel/media-driver/compare/intel-media-23.3.1...intel-media-23.3.2
=> media-driver: update to 23.3.2

packages/mediacenter/kodi/package.mk
=> [le11] kodi: update to current Nexus version

projects/Allwinner/patches/linux/0014-drm_call_drm_atomic_helper_shutdown_at_shutdown.patch
=> [LE11] Allwinner: linux: properly shutdown display at shutdown

projects/Allwinner/bootloader/canupdate.sh
Allow updates between arm and aarch64, same as RK and AML.
=> [LE12] Allwinner: Add canupdate.sh script

packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
Fix memory leak during device enumeration. Thanks to @cgutman.
Closes #8025
=> ffmpeg: update v4l2-request patch

projects/Allwinner/firmwares/brcmfmac_sdio-firmware.dat
=> [LE11] Allwinner: brcmfmac_sdio-firmware: update filter

packages/mediacenter/kodi/package.mk
=> kodi: update to 21.0a3-Omega

packages/graphics/mesa/package.mk
Release notes:
- https://docs.mesa3d.org/relnotes/23.1.7.html 
- https://docs.mesa3d.org/relnotes/23.1.8.html
=> mesa: update to 23.1.8

packages/sysutils/systemd/package.mk
Release notes:
- https://github.com/systemd/systemd-stable/compare/v254.3...v254.4
=> systemd: update to 254.4

packages/linux-firmware/kernel-firmware/package.mk
=> kernel-firmware: update to 20230919

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
=> inputstream.adaptive: update to 21.3.0-Omega

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.6
- gst-plugins-base: update to 1.22.6
- gstreamer: update to 1.22.6
=> gstreamer: update to 1.22.6

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/service/inadyn/package.mk, packages/addons/service/jellyfin/package.mk, packages/addons/tools/btrfs-progs/package.mk, packages/addons/tools/dotnet-runtime/package.mk
- btrfs-progs: update to 6.5.1 and addon (1)
- dotnet-runtime: update to aspnet6-runtime 6.0.22 and addon (1)
- aspnet6-runtime: update to 6.0.22
- inadyn: update to 2.12.0 and addon (1)
- jellyfin: update to 10.8.11 and addon (1)
=> [le12] Addon updates

packages/tools/bcm2835-bootloader/package.mk, projects/RPi/bootloader/canupdate.sh
Shamelessly stolen from Allwinner project :-)
=> RPi: add canupdate.sh script

packages/graphics/mesa/package.mk
ref:
- https://gitlab.freedesktop.org/mesa/mesa/-/commits/23.2/
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/ddc41d4652c61e1815f772ea02dd9a8e798a4943/docs/relnotes/23.2.1.rst
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/0af5a5e428309b5ddd35b516a421482ffa5e8239/docs/release-calendar.csv
=> mesa: update to 23.2.1

packages/mediacenter/kodi/config/70-libinput-ignore-power-button.rules, packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-995.21-keymaps-change-remote-poweroff-action-to-show-shutdo.patch, packages/sysutils/systemd/package.mk
This is a backport of #8161, #8165 and #8178
=> [le11] backport kodi power button / shutdown improvements

packages/x11/lib/libX11/package.mk
ann:
- https://lists.x.org/archives/xorg/2023-October/061506.html
=> libX11: update to 1.8.7

packages/lang/Python3/package.mk
ann:
- https://pythoninsider.blogspot.com/2023/10/python-3116-is-now-available.html
=> Python3: update to 3.11.6

packages/tools/amlogic-boot-fip/package.mk
- https://github.com/LibreELEC/amlogic-boot-fip/commits/master
- Includes https://github.com/LibreELEC/amlogic-boot-fip/pull/21
=> amlogic-boot-fip: update to githash c4bf0e3

projects/Samsung/patches/kodi/kodi-0002-LOCAL-changes-for-Odroid-XU3-XU4.patch
kodi: update patch for Odroid XU3/XU4
ref:
- https://github.com/xbmc/xbmc/commit/8ba612c86bdf090e8b7a960daf02a4908e12b078
- Fixes Samsung build since #8206
=> Fix Odroid XU3/XU4 build

packages/network/samba/package.mk
ref:
- https://www.samba.org/samba/history/samba-4.17.12.html
=> [le11] samba: update to 4.17.12

packages/web/curl/package.mk
Release notes:
- https://curl.se/changes.html
- https://curl.se/docs/security.html
=> curl: update to 8.4.0

projects/Allwinner/patches/linux/0073-wip-media-sunxi-sun8i-di-fix-race-condition.patch
=> [LE12] Allwinner: linux: fix deinterlacer driver

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.269
- vulkan-loader: update to 1.3.269
- vulkan-tools: update to 1.3.269
=> Vulkan update to 1.3.269

packages/addons/addon-depends/rpi-tools-depends/lg-gpio/package.mk
Note to myself: don't rebase/squash late at night...
=> lg-gpio: fix PKG_SHA256

packages/python/devel/meson/package.mk, packages/tools/qemu/package.mk
- meson: update to 1.2.3
- qemu: update to 8.0.5
=> Development package updates

packages/sysutils/usbutils/package.mk
announcement:
- https://lwn.net/Articles/948463/
=> usbutils: update to 016

packages/x11/xserver/xorg-server/package.mk
Ann:
- https://lists.x.org/archives/xorg-announce/2023-October/003430.html
- https://lists.x.org/archives/xorg-announce/2023-October/003431.html
=> xorg-server: update to 21.1.9

packages/addons/addon-depends/go/package.mk
fix build when compiling on arm/aarch64
=> go: add support for /usr/local host installations

packages/addons/service/tvheadend42/source/resources/settings.xml, packages/addons/service/tvheadend43/source/resources/settings.xml
Fix condition that shows the file location field when type == "File"
=> [tvheadend 4.2/4.3] Display file location field when "File" is chosen in type field.

packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk, packages/addons/tools/dotnet-runtime/package.mk
aspnet6-runtime: update to 6.0.24
=> [le12] dotnet-runtime: update to aspnet6-runtime 6.0.24 and addon (2)

packages/linux-firmware/kernel-firmware/package.mk, packages/sysutils/usbutils/package.mk
- kernel-firmware: update to 20231030
- usbutils: update to 017
=> Kernel-firmware and usbutils 

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch, packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch, packages/mediacenter/kodi/patches/kodi-999.20-headers-only.patch
=> kodi: update to fdb4025

packages/addons/service/jellyfin/package.mk, packages/addons/tools/btrfs-progs/package.mk
- btrfs-progs: update to 6.6.1 and addon (3)
- jellyfin: update to 10.8.12 and addon (2)
=> Addon updates

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk, packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.01-cmakelists-opts.patch
- vulkan-headers: update to 1.3.270
- vulkan-loader: update to 1.3.270
- vulkan-tools: update to 1.3.270
=> Vulkan update to 1.3.270

packages/graphics/nvidia/package.mk
Update to latest nvidia for GBM/Wayland graphic driver for NVIDIA GPUs supporting the GeForce 700 Series & above
- https://www.nvidia.com/en-us/drivers/unix/
- https://www.nvidia.com/download/driverResults.aspx/214100/en-us/
=> nvidia: update to 545.29.02

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/options
=> linux (RPi): update to 6.1.62

packages/rust/cargo-snapshot/package.mk, packages/rust/rust-std-snapshot/package.mk, packages/rust/rust/package.mk, packages/rust/rustc-snapshot/package.mk
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
=> Rust update to 1.74.0

packages/network/connman/package.mk, packages/network/iwd/package.mk
- connman: update to githash 1cde7a6 (2023-11-19)
- iwd: update to 2.9
=> [le12] iwd and connman

packages/devel/libbpf/package.mk
release notes:
- https://github.com/libbpf/libbpf/releases/tag/v1.3.0
=> libbpf: update to 1.3.0

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch, packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch, packages/mediacenter/kodi/patches/kodi-995.21-keymaps-change-remote-poweroff-action-to-show-shutdo.patch
just unpack tested, minor bump to current head of k20
=> kodi: update to 0f4ed67

packages/sysutils/v4l-utils/package.mk, packages/sysutils/v4l-utils/patches/v4l-utils-003-enable-bpf-without-clang.patch
Clean build tested and patch updated.
=> v4l-utils: fix 1.26.0 cross compiled builds

packages/audio/pipewire/package.mk
News:
Changelog:
- https://github.com/PipeWire/pipewire/compare/0.3.85...1.0.0
=> pipewire: update to 1.0.0

packages/network/avahi/package.mk, packages/sysutils/systemd/package.mk
- avahi: sanitize uidgid
- systemd: sanitize /etc/group and gids
=> Fix uidgid journalctl errors at boot and sanitize uidgid

packages/sysutils/systemd/package.mk
Release notes:
Log:
- https://github.com/systemd/systemd-stable/compare/v254.6...v254.7
=> systemd: update to 254.7

packages/graphics/vulkan/volk/package.mk, packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.272
- vulkan-loader: update to 1.3.272
- vulkan-tools: update to 1.3.272
- volk: add PKG_DEPENDS_TARGET=vulkan-headers
=> vulkan update to 1.3.272

packages/debug/gdb/package.mk, packages/devel/mpfr/package.mk
- gdb: update to 14.1
- mpfr: allow TARGET builds
=> gdb: update to 14.1

packages/lang/Python3/package.mk
- https://peps.python.org/pep-0664/
=> Python3: update to 3.11.7

packages/sysutils/busybox/package.mk, packages/sysutils/busybox/scripts/pastebinit
switch to our own paste service
=> pastebinit: use le paste service

packages/linux-firmware/kernel-firmware/package.mk
=> kernel-firmware: update to 20231211

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.273
- vulkan-loader: update to 1.3.273
- vulkan-tools: update to 1.3.273
=> Vulkan update to 1.3.273

packages/sysutils/udevil/package.mk
=> [le11] udevil: support custom udevil.conf in /storage/.config

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
Runtime tested on RPi 3B+, RPi4 and RPi5
=> linux (RPi): update to 6.6.7

packages/devel/cmake/package.mk
Release notes:
- https://cmake.org/cmake/help/latest/release/index.html
=> cmake: update to 3.28.1

packages/sysutils/systemd/package.mk
Release notes:
- https://github.com/systemd/systemd-stable/compare/v255...v255.1
=> systemd: update to 255.1

packages/mediacenter/kodi/package.mk
=> kodi: update to 1497cc8

packages/sysutils/systemd/package.mk
=> systemd: update to 255.2

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.8
- gst-plugins-base: update to 1.22.8
- gstreamer: update to 1.22.8
=> Gstreamer: update to 1.22.8

scripts/image
=> [le11] scripts/image: Fix RPi4 and RPi5 noobs build

packages/linux-firmware/dvb-firmware/package.mk
Ref:
- https://github.com/LibreELEC/dvb-firmware/compare/1.4.2...1.5.0
=> dvb-firmware: update to 1.5.0

packages/python/devel/meson/package.mk
Log: 
- https://github.com/mesonbuild/meson/compare/1.3.0...1.3.1
- https://mesonbuild.com/Release-notes-for-1-3-0.html
=> meson: update to 1.3.1

packages/x11/lib/pixman/package.mk
ann:
- https://lists.freedesktop.org/archives/pixman/2024-January/005008.html
=> pixman: update to 0.43.0 and meson

packages/sysutils/tz/package.mk
=> [le11] tz: update to 2023d

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch, packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch, packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch, packages/mediacenter/kodi/patches/kodi-999.20-headers-only.patch
=> kodi: update to f6e78bf

packages/graphics/mesa/package.mk
ann:
- https://lists.freedesktop.org/archives/mesa-announce/2024-January/000742.html
=> mesa: update to 23.3.3

packages/audio/espeak-ng/package.mk, packages/audio/espeak-ng/patches/PR1858-fix-compiling-in-build-directory.patch
=> espeak-ng: update to 1.51.1 and set PKG_TOOLCHAIN=autotools and fix build

packages/x11/xserver/xorg-server/package.mk
ann:
- https://lists.x.org/archives/xorg/2024-January/061525.html
=> xorg-server: update to 21.1.11

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/containerd/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/addon-depends/docker/moby/patches/moby-001-user-addon-storage-location.patch, packages/addons/addon-depends/docker/moby/patches/moby-002-use-unconfined-seccomp-profile-as-default.patch, packages/addons/service/docker/package.mk
- containerd: update to 1.7.12
- cli: update to 25.0.0
- moby: update to 25.0.0
=> docker: update to 25.0.0 and addon (2)

packages/python/graphics/Pillow/patches/Pillow-0001-crosscompiling.patch, packages/python/graphics/Pillow/patches/Pillow-0002-Revert-Move-build-config-from-setup.cfg-to-pyproject.patch
Fixes: 
- #8534 
Raised at Pillow
- https://github.com/python-pillow/Pillow/issues/7734
=> Pillow: update patches for 10.2.0 and fix upstream regression with setup.py

packages/devel/pax-utils/package.mk
=> pax-utils: fix host build on gentoo

packages/linux-drivers/RTL8192DU/package.mk
=> RTL8192DU: update to githash a82c83e

packages/graphics/mesa/package.mk
Ann:
- https://lists.freedesktop.org/archives/mesa-dev/2024-January/226125.html
=> mesa: update to 23.3.4

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.22.9
- gst-plugins-base: update to 1.22.9
- gstreamer: update to 1.22.9
=> gstreamer: update to 1.22.9

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.276
- vulkan-loader: update to 1.3.276
- vulkan-tools: update to 1.3.276
=> Vulkan update to 1.3.276

packages/audio/alsa-lib/package.mk, packages/audio/alsa-lib/patches/alsa-0001-topology--correct-version-script-path.patch, packages/audio/alsa-ucm-conf/package.mk, packages/audio/alsa-utils/package.mk
- alsa-lib: update to 1.2.11
- alsa-utils: update to 1.2.11
- alsa-ucm-conf: update to 1.2.11
=> Alsa update to 1.2.11

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.277
- vulkan-loader: update to 1.3.277
- vulkan-tools: update to 1.3.277
=> Vulkan 1.3.277

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.23.1
- gst-plugins-base: update to 1.23.1
- gstreamer: update to 1.23.1
=> gstreamer: update to 1.23.1

packages/lang/Python3/package.mk
Ref:
- https://peps.python.org/pep-0664/#schedule
=> Python3: update to 3.11.8

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
- cli: update to 25.0.3
- moby: update to 25.0.3
=> docker: update to 25.0.3 and addon (5)

packages/mediacenter/kodi/patches/kodi-995.30-no-efivars-no-autofs.patch
upstream pull request
https://github.com/xbmc/xbmc/pull/24642
=> kodi: storage info no efivars, autofs

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-995.21-keymaps-change-remote-poweroff-action-to-show-shutdo.patch
log:
- https://github.com/xbmc/xbmc/compare/0a52609c11800e5ba71e7ec81dd5131123223968...89288b972ea04b1196c6998f2a2a48456fbdcf60
=> kodi: update to githash 89288b9

packages/mediacenter/kodi/package.mk
- https://github.com/xbmc/xbmc/releases/tag/21.0b3-Omega
- https://github.com/xbmc/xbmc/pull/24690#event-11812888910
=> kodi: update to 21.0b3-Omega

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.23.2
- gst-plugins-base: update to 1.23.2
- gstreamer: update to 1.23.2
=> gstreamer: update to 1.23.2

packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.6.17

packages/network/iwd/package.mk
+ver 2.15:
+	Fix issue with notice events for connection timeouts.
+	Fix issue with reason code and deauthenticate event.
+	Fix issue with handling basename() functionality.
=> iwd: update to 2.15

packages/sysutils/systemd/package.mk
Release notes:
- https://github.com/systemd/systemd-stable/compare/v255.3...v255.4
=> systemd: update to 255.4

packages/mediacenter/kodi/package.mk
Mar 3,2024
Includes:
- https://github.com/xbmc/xbmc/pull/24785
- https://github.com/xbmc/xbmc/pull/24789
- [Fix regression for play actions](https://github.com/xbmc/xbmc/commit/f315d244ef71eac3d10bc9134027f9dd7c0513cf)
- [[VideoPlayer] Fix initial interlaced stream refresh rate switch](https://github.com/xbmc/xbmc/commit/24aea0bc5d7c973cbb3c36ea5c7bb568050adb76)
=> kodi: update to githash 7075efe 

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.279
- vulkan-loader: update to 1.3.279
- vulkan-tools: update to 1.3.279
=> Vulkan: update to 1.3.279

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.0
- gst-plugins-base: update to 1.24.0
- gstreamer: update to 1.24.0
=> gstreamer: update to 1.24.0

packages/mediacenter/LibreELEC-settings/package.mk
Includes
- https://github.com/LibreELEC/service.libreelec.settings/pull/317
- https://github.com/LibreELEC/service.libreelec.settings/pull/318
=> LibreELEC-settings: update to githash 3d37732

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk
=> linux (RPi): update to 6.6.20

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
- docker: update to 25.0.4 and addon (6)
- cli: update to 25.0.4
- moby: update to 25.0.4
=> docker: update to 25.0.4 and addon (6)

packages/compress/xz/package.mk
release notes and change logs:
- https://github.com/tukaani-project/xz/releases/tag/v5.6.1
- https://github.com/tukaani-project/xz/compare/v5.6.0...v5.6.1
=> xz: update to 5.6.1

packages/linux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.6.21

packages/audio/pipewire/package.mk, packages/devel/mold/package.mk, packages/wayland/util/bemenu/package.mk
- bemenu: update to 0.6.21
- pipewire: update to 1.0.4
- mold: update to 2.30.0
=> Extras - Package updates

packages/linux-firmware/kernel-firmware/package.mk
Kernel Firmware:
- kernel-firmware: update to 20240312
=> kernel-firmware: update to 20240312

packages/multimedia/gmmlib/package.mk, packages/multimedia/media-driver/package.mk
- gmmlib: update to 22.3.18
- media-driver: update to 24.1.5
(not including libva at this time)
=> Intel Media-driver

packages/tools/bcm2835-bootloader/package.mk
=> RPi: update to firmware 45319db

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.1
- gst-plugins-base: update to 1.24.1
- gstreamer: update to 1.24.1
=> gstreamer: update to 1.24.1

packages/sysutils/open-vm-tools/package.mk
release notes:
- https://github.com/vmware/open-vm-tools/releases/tag/stable-12.4.0
=> open-vm-tools: update to 12.4.0

packages/linux/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.6.23

packages/network/iwd/package.mk
ver 2.17:
+	Fix issue with handling deauthenticate on disconnect.
+	Fix issue with handling of rate estimation errors.
+	Fix issue with handling EAPOL frame listeners.
=> iwd: update to 2.17

packages/mediacenter/kodi/package.mk, packages/mediacenter/kodi/patches/kodi-100.02-add-libreelec.tv-RSS-news.patch, packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch, packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch, packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
#8786 accidentally switched kodi to the master branch, switch back to current HEAD of the Omega branch
=> kodi: switch back to Omega branch

packages/tools/bcm2835-utils/package.mk
=> bcm2835-utils: update to 6dc6f5f

packages/linux/package.mk
=> linux (RPi): update to 6.6.26

packages/addons/service/tvheadend42/package.mk, packages/addons/service/tvheadend43/package.mk, packages/addons/tools/ffmpeg-tools/package.mk
- ffmpeg-tools: update x265 shared library directory
- tvheadend42: update x265 shared library directory
- tvheadend43: update x265 shared library directory
=> update x265 shared library directory

packages/databases/sqlite/package.mk
- https://sqlite.org/src/timeline?from=version-3.45.2&to=version-3.45.3&to2=branch-3.45
- https://www.sqlite.org/releaselog/3_45_3.html
=> sqlite: update to 3.45.3

packages/web/curl/package.mk
Release notes:
- https://curl.se/changes.html
=> curl: update to 8.7.1

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.283
- vulkan-loader: update to 1.3.283
- vulkan-tools: update to 1.3.283
=> vulkan: update to 1.3.283

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.3
- gst-plugins-base: update to 1.24.3
- gstreamer: update to 1.24.3
=> gstreamer: update to 1.24.3

packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
=> [le12] peripheral.joystick: update 21.1.11-Omega to 21.1.14-Omega

packages/devel/arm-mem/package.mk
Minor
- https://github.com/bavison/arm-mem/pull/12
- https://github.com/bavison/arm-mem/pull/12/commits/116d2e4599697738b94cffebfbe5de3864d611a7
- https://github.com/bavison/arm-mem/issues/11
=> arm-mem: update to githash ee8ac1d

packages/addons/addon-depends/snapcast-depends/snapcast/package.mk
=> [LE12] snapcast: fix hash (again)

packages/addons/tools/system-tools/package.mk
=> system-tools: move smbus.so to lib and addon (1)

packages/addons/tools/system-tools/changelog.txt, packages/addons/tools/system-tools/package.mk
=> [le12] system-tools: move smbus.so to lib and addon (1)

packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.6.30

packages/addons/addon-depends/system-tools-depends/fdupes/package.mk
Fixes system-tools clean build.
=> fdupes: add missing sqlite DEPEND

packages/addons/addon-depends/system-tools-depends/fdupes/package.mk
=> [le12] fdupes: add missing sqlite DEPEND

packages/linux/package.mk, packages/tools/bcm2835-bootloader/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> [le12] linux (RPi): update to 6.6.30

projects/Allwinner/patches/linux/0041-OrangePi-3-LTS-support.patch
=> [LE12] Allwinner: linux: Fix OrangePi 3 LTS ethernet

packages/mediacenter/kodi-binary-addons/game.libretro.a5200/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
Backport of https://github.com/LibreELEC/LibreELEC.tv/pull/8847
=> [LE12] Update Atari emulators for authetic buttonmaps

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.285
- vulkan-loader: update to 1.3.285
- vulkan-tools: update to 1.3.285
=> vulkan: update to 1.3.285

packages/network/wireless-regdb/package.mk
ref: https://git.kernel.org/pub/scm/linux/kernel/git/wens/wireless-regdb.git
=> wireless-regdb: update to 2024.05.08

packages/linux-firmware/intel-ucode/package.mk
release notes:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20240514
=> intel-ucode: update to 20240514

tools/docker/noble/Dockerfile
=> [le12] tools/docker: add cpp-13 to noble Dockerfile

packages/graphics/mesa/package.mk
=> [le12] mesa: update to 24.0.8

packages/web/curl/package.mk
Release notes:
- https://curl.se/changes.html
=> curl: update to 8.8.0

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.4
- gst-plugins-base: update to 1.24.4
- gstreamer: update to 1.24.4
=> gstreamer: update to 1.24.4

packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk, packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
- pvr.vuplus: update 21.1.2-Omega to 21.2.0
- pvr.waipu: update 21.6.4-Omega to 21.6.6-Omega
=> [le13] kodi-binary-addons: update to latest versions

packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
Fixes https://forum.libreelec.tv/thread/28650-docker-addon-server-incorrectly-versioned/
=> docker: server: fix version display

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.287
- vulkan-loader: update to 1.3.287
- vulkan-tools: update to 1.3.287
=> vulkan: update to 1.3.287

packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
=> [le12] docker: server: fix version display

packages/addons/addon-depends/system-tools-depends/tree/package.mk, packages/addons/tools/system-tools/package.mk
Add the `tree` binary to system tools.
=> tree: add tree binary to system-tools

packages/mediacenter/kodi/package.mk
=> [le12] kodi: update to latest Omega version

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.288
- vulkan-loader: update to 1.3.288
- vulkan-tools: update to 1.3.288
=> vulkan: update to 1.3.288

packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk, packages/multimedia/zvbi/package.mk, packages/multimedia/zvbi/patches/zvbi-0010-fix-static-linking.patch, packages/multimedia/zvbi/patches/zvbi-0050-prevent-test.patch, packages/multimedia/zvbi/patches/zvbi-0060-configure-ac--Move-sincos-function-check-to-AC_CHECK_FUNCS.patch
- [zvbi: update to 0.2.42 and update PKG_ SITE and URL](https://github.com/LibreELEC/LibreELEC.tv/commit/44c465e6df4eb54dabfc71454c0ce1aca998ee7f)
=> inputstream.ffmpegdirect: update zvbi to 0.2.42 and addon (3)

packages/sysutils/busybox/scripts/fs-resize
=> [le12] busybox: use mke2fs instead of resize2fs

packages/devel/libcec/patches/0001-WIP-support-multiple-dev-cecX-devices.patch
=> [le12] cec: Allow cec driver to handle multiple instances

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.5
- gst-plugins-base: update to 1.24.5
- gstreamer: update to 1.24.5
=> gstreamer: update to 1.24.5

packages/audio/pipewire/package.mk
=> pipewire: update to 1.2.0

packages/linux/patches/default/linux-999.90-media-anysee-accept-read-buffers-of-length-1-in-anys.patch, packages/linux/patches/raspberrypi/linux-999.90-media-anysee-accept-read-buffers-of-length-1-in-anys.patch
backport of https://github.com/LibreELEC/LibreELEC.tv/pull/9044
=> linux: backport anysee usb patch from Linux 6.10

projects/Amlogic/patches/u-boot/u-boot-0001-LOCAL-configs-meson64-prevent-stdout-stderr-on-video.patch, projects/Amlogic/patches/u-boot/u-boot-0002-LOCAL-board-amlogic-odroid-n2-remove-amlogic-prefix-.patch, projects/Amlogic/patches/u-boot/u-boot-0003-FROMGIT-net-Add-Amlogic-GXL-MDIO-Mux-driver.patch, projects/Amlogic/patches/u-boot/u-boot-0004-FROMGIT-ARM-dts-sync-Amlogic-GX-DT-to-Linux-v6.4.patch, projects/Amlogic/patches/u-boot/u-boot-0005-FROMGIT-board-amlogic-fix-buffler-overflow-in-serial.patch, projects/Amlogic/patches/u-boot/u-boot-0006-FROMGIT-ARM-dts-fix-Ethernet-on-WeTek-Hub-Play2.patch, projects/Amlogic/patches/u-boot/u-boot-0007-FROMGIT-board-amlogic-add-meson_generate_serial_etha.patch
=> u-boot: update Amlogic patches to fix Odroid N2 boot

packages/network/iwd/package.mk
+ Fix issue with handling flush flag for external scans.
+ Fix issue with handling SNR calculation in ranking.
=> [le12] iwd: update to 2.19

packages/emulation/libretro-pcsx-rearmed/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk
This PR updates the PCSX ReARMed core to the latest master, and pulls in the latest strings.
I'm currently hunting down bugs in PCSX ReARMed, including a leading culprit fixed in https://github.com/kodi-game/game.libretro/pull/126. I'm getting everything synced with master to isolate any problems.
=> Update PCSX ReARMed

packages/tools/amlogic-boot-fip/package.mk
Ref:
- https://github.com/LibreELEC/LibreELEC.tv/pull/9084
- https://github.com/LibreELEC/LibreELEC.tv/issues/9056
- https://github.com/LibreELEC/amlogic-boot-fip/pull/24
=> amlogic-boot-fip: update to githash 1d9dc4e

packages/compress/lz4/package.mk, packages/compress/lzo/package.mk
- follow up to #9040 
- lzo: update target toolchain depend
- lz4: update target toolchain depend
=> Fix dependencies 

packages/emulation/libretro-atari800/package.mk, packages/emulation/libretro-bk/package.mk, packages/emulation/libretro-bluemsx/package.mk, packages/emulation/libretro-mame2000/package.mk, packages/emulation/libretro-mame2003_plus/package.mk, packages/emulation/libretro-mrboom/package.mk, packages/emulation/libretro-pcsx-rearmed/package.mk, packages/emulation/libretro-snes9x/package.mk, packages/emulation/libretro-uae/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.bk/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.bluemsx/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mame2000/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mame2003_plus/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.mrboom/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.snes9x/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro.uae/package.mk, packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
This PR backports the recent updates to game add-ons. It includes the following:
* https://github.com/LibreELEC/LibreELEC.tv/pull/9079
* https://github.com/LibreELEC/LibreELEC.tv/pull/9080
* https://github.com/LibreELEC/LibreELEC.tv/pull/9081
* https://github.com/LibreELEC/LibreELEC.tv/pull/9082
=> [le12] Backport game add-on updates

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.290
- vulkan-loader: update to 1.3.290
- vulkan-tools: update to 1.3.290
=> Vulkan: update to 1.3.290

packages/compress/libarchive/package.mk, packages/compress/lz4/package.mk, packages/compress/xz/package.mk
- xz: only build libraries
- libarchive: only build libraries
- lz4: only build libraries
=> Compress packages - only build libraries 

packages/addons/addon-depends/cxxtools/patches/cxxtools-crosscompile.patch, packages/addons/addon-depends/network-tools-depends/nmap/patches/nmap-0001-allow-build-with-automake-1-17.patch
- nmap: allow build with automake 1.17
- cxxtools: allow build with automake 1.17
=> fix addon builds - compatibility with automake-1.17

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.6
- gst-plugins-base: update to 1.24.6
- gstreamer: update to 1.24.6
=> gstreamer: update to 1.24.6

packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch, tools/ffmpeg/gen-patches.sh
Update to latest version of jc's test/6.0.1/main branch
=> RPi: update ffmpeg patch

packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch, tools/ffmpeg/gen-patches.sh
=> [le12] RPi: update ffmpeg patch

packages/mediacenter/kodi/package.mk
- Includes pvr updates. Merge along with #9146
=> kodi: update to githash f6265c8

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/patches/001-backport-build-fix.patch
=> [le12] inputstream.adaptive: backport upstream fix for build error

packages/graphics/mesa/package.mk, packages/python/devel/pyyaml/package.mk, projects/RPi/patches/mesa/0001-gallium-Add-kmsro-drivers-for-RP1-DSI-DPI-and-VEC-de.patch
- mesa: update to 24.2.0
- PyYAML: initial package
- mesa: RPi: rebase patches for 24.2.0-rc1
=> mesa: update to 24.2.0

packages/web/curl/patches/curl-0001-fix-webdav-issue.patch
- Potential fix for WebDAV reported in #9175 
- https://github.com/curl/curl/commit/b8c003832d730bb2f4b9de4204675ca5d9f7a903
- https://github.com/curl/curl/issues/13170
=> [le12] curl: fix webdav issue

packages/mediacenter/kodi/package.mk
=> kodi: update to 21.1-Omega

packages/mediacenter/kodi/package.mk
=> kodi: update to cdfc755

packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
fix Piers addon build (no tag yet)
- https://github.com/janbar/pvr.mythtv/pull/246
=> pvr.mythtv: update to githash 34e52b0

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.7
- gst-plugins-base: update to 1.24.7
- gstreamer: update to 1.24.7
=> gstreamer: update to 1.24.7

packages/tools/dtc/package.mk
=> dtc: include library file as well as symbolic links in makeinstall

packages/devel/glib/package.mk
=> glib: update to 2.81.2

packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
This adds language fixes for new remotes consistent with what we were doing with existing remotes
=> Add support for OSMC RF 3.0

packages/addons/addon-depends/system-tools-depends/bottom/package.mk, packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk, packages/addons/addon-depends/system-tools-depends/mc/package.mk, packages/addons/addon-depends/system-tools-depends/mmc-utils/package.mk, packages/addons/addon-depends/system-tools-depends/pv/package.mk, packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk, packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk, packages/addons/addon-depends/vdr/package.mk, packages/addons/service/rsyslog/package.mk, packages/addons/service/vdr-addon/package.mk, packages/addons/tools/system-tools/package.mk, packages/audio/fluidsynth/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.fluidsynth/package.mk
=> [le12] addon updates 

packages/tools/qemu/package.mk
Changelog:
- https://wiki.qemu.org/ChangeLog
- depends on #9218
=> qemu: update to 9.0.2

projects/Allwinner/patches/kodi/000-temp-revert-fences.patch, projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
Fix suggested by @knaerzche
Backport of #9269
=> [le12] Fix flickering with graphic overlays for Rockchip/Allwinner

packages/mediacenter/kodi/package.mk
- Required to support #9287
- https://github.com/xbmc/xbmc/pull/25706
Build tested on Generic along with create_addon pvr.*
=> kodi: update to githash db813bf

packages/network/iwd/package.mk
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/
=> iwd: update to 2.22

packages/addons/addon-depends/podman/conmon/package.mk, packages/addons/addon-depends/podman/libassuan/package.mk, packages/addons/addon-depends/podman/netavark/package.mk, packages/addons/addon-depends/podman/netavark/patches/netavark-0001-no-docs.patch, packages/addons/addon-depends/podman/podman-bin/package.mk, packages/addons/addon-depends/podman/podman-bin/patches/podman-0002-path-changes.patch, packages/addons/service/podman/package.mk
- conmon: update to 2.1.12
- libassuan: update to 3.0.1
- netavark: update to 1.12.2 and fix cross-compile build
- podman-bin: update to 5.2.2
- Fixes #9296
=> podman: update to 5.2.2 and addon (1)

projects/Allwinner/patches/kodi/000-temp-revert-fences.patch, projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
Fix suggested by [@knaerzche](https://github.com/LibreELEC/LibreELEC.tv/issues/9065#issuecomment-2321517730)
=> Fix flickering with graphic overlays for Rockchip/Allwinner

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.8
- gst-plugins-base: update to 1.24.8
- gstreamer: update to 1.24.8
=> gstreamer: update to 1.24.8

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.296
- vulkan-loader: update to 1.3.296
- vulkan-tools: update to 1.3.296
=> Vulkan update to 1.3.296

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- https://www.nvidia.com/en-us/drivers/details/232672/
- nvidia: update to 550.120
- xf86-video-nvidia: update to 550.120
=> Nvidia: update to 550.120

packages/network/connman/package.mk, packages/network/connman/patches/connman-07-connman_gateway_add-fix-calculation-of-is_vpn6.patch
Backport of #9258
May fix issue #9354 and/or issue #9364.
=> connman: update to 1.43

packages/linux/package.mk
Backport of #9283
Build tested on Generic
=> linux: fix iSCSI support (lost in configs)

projects/Allwinner/patches/kodi/000-temp-revert-fences.patch, projects/Amlogic/patches/kodi/000-temp-revert-fences.patch, projects/RPi/patches/kodi/000-temp-revert-fences.patch, projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
Fix builds due to:
- https://github.com/xbmc/xbmc/pull/24431
- #9380
=> kodi: rebase temp revert fences patch for kodi ed8f18b

packages/compress/xz/package.mk
- https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS
- https://tukaani.org/xz/
=> xz: update to 5.6.3

scripts/get_archive, tools/distro-tool
=> scripts and tools: only use --passive-ftp for ftp: urls

packages/addons/driver/sundtek-mediatv/package.mk
=> sundtek-mediatv: change wget to curl

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.299
- vulkan-loader: update to 1.3.299
- vulkan-tools: update to 1.3.299
=> vulkan: update to 1.3.299

packages/x11/lib/xtrans/patches/0001-Revert-is_numeric-Add-TRANS_SERVER-to-required-ifdef.patch
- https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/issues/6
- https://gitlab.freedesktop.org/xorg/lib/libxfont/-/issues/15
=> xtrans: fixes builds with 1.5.1

packages/network/iwd/package.mk
=> [le12] iwd: update to 3.0

packages/mediacenter/LibreELEC-settings/package.mk
Adds LibreELEC/service.libreelec.settings#327
=> LibreELEC-settings: update to 6ff1cf2

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.300
- vulkan-loader: update to 1.3.300
- vulkan-tools: update to 1.3.300
=> Vulkan update to 1.3.300

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- https://www.nvidia.com/en-us/drivers/details/233004/
=> nvidia updates to 550.127.05

packages/mediacenter/kodi/package.mk, projects/Allwinner/patches/kodi/000-temp-revert-fences.patch, projects/Amlogic/patches/kodi/000-temp-revert-fences.patch, projects/RPi/patches/kodi/000-temp-revert-fences.patch, projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
- update to latest Kodi with https://github.com/xbmc/xbmc/pull/25867 to support pvr build changes in #9434
=> kodi: update to githash 68effd5

packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
Update to compile with latest Kodi
- https://github.com/janbar/pvr.mythtv/commit/67196eb8baaa35adeeccf9ea0a2c605fddc25f68
=> pvr.mythtv: update to githash 67196eb

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.9
- gst-plugins-base: update to 1.24.9
- gstreamer: update to 1.24.9
=> gstreamer: update to 1.24.9

packages/audio/fluidsynth/package.mk, packages/mediacenter/kodi-binary-addons/audiodecoder.fluidsynth/package.mk
- audiodecoder.fluidsynth: update addon (12)
- fluidsynth: update to 2.4.0
=> audiodecoder.fluidsynth: update addon (12)

packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- inputstream.adaptive: update 21.5.5-Omega to 21.5.6-Omega
=> inputstream.adaptive: update 21.5.5-Omega to 21.5.6-Omega

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.301
- vulkan-loader: update to 1.3.301
- vulkan-tools: update to 1.3.301
=> Vulkan update to 1.3.301

packages/addons/addon-depends/docker/containerd/package.mk, packages/addons/addon-depends/go/package.mk, packages/addons/addon-depends/runc/package.mk, packages/addons/service/docker/package.mk
- containerd: update to 2.0.0
- runc: update to 1.2.1
- go: update to 1.23.3
=> docker: update to containerd 2.0.0 and addon (3)

packages/debug/edid-decode/package.mk
=> edid-decode: update to 5332a3b (2024-11-19)

packages/devel/talloc/config/talloc-cache.txt, packages/devel/talloc/package.mk, packages/network/cifs-utils/package.mk, packages/network/samba/package.mk
- samba: add talloc dependency
- talloc: initial package
- cifs-utils: update to 7.1
=> cifs-utils: update to 7.1 and dependencies

packages/addons/service/mpd/patches/0001-support-build-with-libfmt-11.0.0.patch, packages/devel/libfmt/package.mk
- mpd: fix build with libfmt-11.0.0
=> libfmt: update to 11.0.2

packages/network/iwd/package.mk
=> iwd: update to 3.2

projects/NXP/devices/iMX8/patches/linux/0001-Initial-support-Cadence-MHDP8501-HDMI-DP-for-i-MX8MQ.patch, projects/NXP/devices/iMX8/patches/linux/0002-arm64-dts-fsl-imx8mq-evk-enable-DCSS-and-HDMI.patch, projects/NXP/devices/iMX8/patches/linux/0003-arm64-dts-fsl-imx8mq-pico-pi-enable-DCSS-and-HDMI.patch, projects/NXP/devices/iMX8/patches/linux/0004-arm64-dts-fsl-imx8mq-phanbell.dts-enable-DCSS-and-HD.patch
ref:
- https://patchwork.kernel.org/project/linux-phy/list/?series=912540
- https://patchwork.freedesktop.org/series/120825/
- Tested with Google Coral
=> linux (NXP iMX8): Update to V19 - Cadence MHDP8501(HDMI/DP) for i.MX8MQ

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.10
- gst-plugins-base: update to 1.24.10
- gstreamer: update to 1.24.10
=> gstreamer: update to 1.24.10

packages/sysutils/systemd/package.mk
Release notes:
- https://github.com/systemd/systemd/releases/tag/v257-rc1
- https://github.com/systemd/systemd/releases/tag/v257-rc2
- https://github.com/systemd/systemd/releases/tag/v257-rc3
- https://github.com/systemd/systemd/releases/tag/v257
=> systemd: update to 257

packages/lang/Python3/package.mk, packages/lang/Python3/patches/0008-Add-an-option-to-disable-the-tk-module.patch, packages/lang/Python3/patches/py312-cpython118618-1.patch, packages/lang/Python3/patches/py312-cpython118618-2.patch
- https://docs.python.org/release/3.12.8/whatsnew/changelog.html#python-3-12-8
=> Python3: update to 3.12.8

packages/graphics/mesa/package.mk
- https://gitlab.freedesktop.org/mesa/mesa/-/commit/aaf540f49e48afc833dcc247af7ff3344c0e2aed
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/aaf540f49e48afc833dcc247af7ff3344c0e2aed/docs/relnotes/24.3.2.rst
=> mesa: update to 24.3.2

packages/network/iwd/package.mk
- Fix issue with handling External Authentication.
=> iwd: update to 3.3

packages/network/iwd/package.mk
- Fix issue with handling External Authentication.
- Backport of #9595
=> [le12] iwd: update to 3.3

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.304
- vulkan-loader: update to 1.4.304
- vulkan-tools: update to 1.4.304
=> Vulkan: update to 1.4.304

projects/NXP/devices/iMX8/patches/linux/0001-Initial-support-Cadence-MHDP8501-HDMI-DP-for-i-MX8MQ.patch
ref:
- https://patchwork.kernel.org/project/linux-phy/list/?series=918529
- https://patchwork.freedesktop.org/series/120825/
=> linux (NXP iMX8): Update to V20 - Cadence MHDP8501(HDMI/DP) for i.MX8MQ

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.6.67

packages/addons/service/minidlna/package.mk, packages/addons/service/minidlna/patches/minidlna-02-ffmpeg7.patch
- require #9569 
- minidlna: fix ffmpeg-7.1 build
- https://sourceforge.net/p/minidlna/discussion/879956/thread/81e45c3d64/
- minidlna: rebuild with ffmpeg-7.1 and addon (2)
=> minidlna: rebuild with ffmpeg-7.1 and addon (2)

packages/addons/addon-depends/docker/cli/package.mk, packages/addons/addon-depends/docker/moby/package.mk, packages/addons/service/docker/package.mk
- cli: update to 27.4.1
- moby: update to 27.4.1
=> docker: update to 27.4.1 and addon (5) 

packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
- fix CI/CD build
@garbear please review
=> game.libretro: update to 22.1.0-Piers and addon (0)

packages/addons/addon-depends/system-tools-depends/depends/oniguruma/package.mk, packages/addons/addon-depends/system-tools-depends/pv/package.mk, packages/addons/tools/system-tools/package.mk
- system-tools: update addon (3)
- oniguruma: update to 6.9.10
- pv: update to 1.9.25
=> system-tools: update addon (3)

packages/addons/tools/flirc_util/package.mk
commit:
- https://github.com/flirc/sdk/commit/280cccbb333f5be30fc48ea958ca103d2fce6fec
=> flirc_util: update to githash 280cccb and addon (1)

packages/addons/tools/flirc_util/package.mk
commit:
- https://github.com/flirc/sdk/commit/280cccbb333f5be30fc48ea958ca103d2fce6fec
- Backport of #9648
=> [le12] flirc_util: update to githash 280cccb and addon (1)

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.24.11
- gst-plugins-base: update to 1.24.11
- gstreamer: update to 1.24.11
=> gstreamer: update to 1.24.11

packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
=> systemd: add foxtel remote to 70-local-keyboard.hwdb

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk
=> linux (RPi): update to 6.12.9

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.25.1
- gst-plugins-base: update to 1.25.1
- gstreamer: update to 1.25.1
=>  gstreamer: update to 1.25.1

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.305
- vulkan-loader: update to 1.4.305
- vulkan-tools: update to 1.4.305
=> Vulkan update to 1.4.305

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- nvidia: update to 550.144.03
- xf86-video-nvidia: update to 550.144.03
=> nvidia: update to 550.144.03

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk
=> [le12] linux (RPi): update to 6.6.74

packages/mediacenter/LibreELEC-settings/package.mk
Includes https://github.com/LibreELEC/service.libreelec.settings/pull/329
Cc @antonlacon
=> LibreELEC-settings: update to githash 1eaa10a

packages/devel/gmp/patches/0001-acinclude.m4-fix-std-c23-build-failure.patch
Fix prototype to be backward compatible with gcc-10
=> gmp: update patch to support gcc-10

packages/addons/addon-depends/polkit/package.mk, packages/addons/service/mpd/package.mk
- mpd: add missing nfs include path
- polkit: fix build dependency
=> Addon build fixes

packages/lang/Python3/package.mk
release notes: https://peps.python.org/pep-0693/
=> Python3: update to 3.12.9

packages/linux-firmware/intel-ucode/package.mk, packages/linux-firmware/iwlwifi-firmware/package.mk, packages/linux-firmware/kernel-firmware/package.mk
- iwlwifi-firmware: update to githash fb888a7
- intel-ucode: update to 20250211
- kernel-firmware: update to 20250211
=> Firmware and Microcode updates

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/87917079958ad5609be9f8fe3379823fa364205d...bd12fabeba025e500e5e99a1d4b09c081d0907fb
=> kodi: update to githash bd12fab

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk
=> linux (RPi): update to 6.12.13

packages/security/openssl/package.mk
=> openssl: copy CA certs to toolchain

packages/devel/json-c/package.mk
ref:
- https://github.com/json-c/json-c/wiki
- https://s3.amazonaws.com/json-c_releases/releases/index.html
=> json-c: update download link and sha256

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.25.90
- gst-plugins-base: update to 1.25.90
- gstreamer: update to 1.25.90
=> gstreamer: update to 1.25.90

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/bd12fabeba025e500e5e99a1d4b09c081d0907fb...e47d2936ceb4a3a16733c4481882cacb0e51b4c3
=> kodi: update to githash e47d293

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/e47d2936ceb4a3a16733c4481882cacb0e51b4c3...8260af82ffa21e99c84e258a4e7b231a08bcf37b
=> kodi: update to githash 8260af8

packages/addons/service/hyperhdr/package.mk
=> [le12] hyperhdr: update to 21.0.0.0

projects/RPi/patches/kodi/0001-gbm-Set-max-bpc-for-high-bit-depth-videos.patch, projects/RPi/patches/kodi/0002-CDVDVideoCodecDRMPRIME-Also-support-YUV420-buffers.patch, projects/RPi/patches/kodi/0003-CDVDVideoCodecDRMPRIME-Adjust-av-formats-to-match-re.patch, projects/RPi/patches/kodi/0004-DVDVideoCodecDRMPRIME-Add-support-for-arbitrary-outp.patch, projects/RPi/patches/kodi/0005-DVDVideoCodecDRMPRIME-Remove-obsolete-thread_safe_ca.patch, projects/RPi/patches/kodi/0006-DVDVideoCodecDRMPRIME-Clear-m_pFilterGraph.patch, projects/RPi/patches/kodi/0007-DVDVideoCodecDRMPRIME-Move-FilterTest-from-open-to-f.patch, projects/RPi/patches/kodi/0008-DVDVideoCodecDRMPRIME-Rework-filtering-code-to-handl.patch, projects/RPi/patches/kodi/0009-CDVDVideoCodecDRMPRIME-Support-decoding-to-DRMPRIME-.patch, projects/RPi/patches/kodi/0010-DVDVideoCodecDRMPRIME-Request-v4l2-buffers-be-alloca.patch, projects/RPi/patches/kodi/0011-DVDVideoCodecDRMPRIME-Add-setting-to-enable-hw-deint.patch, projects/RPi/patches/kodi/0012-fixup-DVDVideoCodecDRMPRIME-add-support-for-filters.patch, projects/RPi/patches/kodi/0013-DVDVideoCodecDRMPRIME-Set-hwctx-for-v4l2-deinterlace.patch
This fixes HW deinterlace with SW decoded videos.
=> RPi: update kodi patches

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.310
- vulkan-loader: update to 1.4.310
- vulkan-tools: update to 1.4.310
=> Vulkan update to 1.4.310

packages/addons/service/proftpd/package.mk
- http://www.proftpd.org/
- http://www.proftpd.org/docs/RELEASE_NOTES-1.3.9
- http://www.proftpd.org/docs/NEWS-1.3.9
=> proftpd: update to 1.3.9 and addon (1)

packages/tools/crust/patches/0001-configs-Make-all-H6-devices-use-I2C-PMIC.patch, projects/Allwinner/patches/linux/0000-Revert-arm64-dts-allwinner-h6-Use-RSB-for-AXP805-PMI.patch, projects/Allwinner/patches/linux/0035-WIP-OPi3-DT-fixes.patch, projects/Allwinner/patches/u-boot/0001-Revert-arm64-dts-allwinner-h6-Use-RSB-for-AXP805-PMI.patch
This PR fixes https://github.com/LibreELEC/LibreELEC.tv/issues/7731 and possibly others boards too.
=> Allwinner: H6: Fix OrangePi One Plus boot

packages/graphics/mesa/package.mk
- https://lists.freedesktop.org/archives/mesa-dev/2025-March/226474.html
=> mesa: update to 25.0.2

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.311
- vulkan-loader: update to 1.4.311
- vulkan-tools: update to 1.4.311
=> Vulkan update to 1.4.311

packages/sysutils/tz/package.mk
https://github.com/eggert/tz/compare/2025a...2025b
=> tz: update to 2025b

packages/graphics/mesa/package.mk
https://lists.freedesktop.org/archives/mesa-dev/2025-April/226480.html
=> mesa: update to 25.0.3

packages/network/iwd/package.mk
https://web.git.kernel.org/pub/scm/network/wireless/iwd.git/log/
- Fix issue with handling blacklisting and roaming requests. 
- Fix issue with handling CQM thresholds for FullMAC devices. 
- Add support for PMKSA when using FullMAC devices.
=> iwd: update to 3.6

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/c45a28aef18e30c9e289b378ed9ece6b692b97a7...b01f67dbe312f7f0b06d29addce2b296d12c880f
=> kodi: update to githash b01f67d

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.312
- vulkan-loader: update to 1.4.312
- vulkan-tools: update to 1.4.312
=> Vulkan update to 1.4.312

packages/lang/Python3/package.mk, packages/lang/Python3/patches/0008-Add-an-option-to-disable-the-tk-module.patch
release notes: https://peps.python.org/pep-0693/
=> Python3: update to 3.12.10

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.313
- vulkan-loader: update to 1.4.313
- vulkan-tools: update to 1.4.313
=> Vulkan update to 1.4.313

packages/linux-firmware/iwlwifi-firmware/package.mk
- https://github.com/LibreELEC/iwlwifi-firmware/pull/59
=> iwlwifi-firmware: update to githash 472d887

packages/linux-firmware/firmware-imx/package.mk
=> firmware-imx: update to 8.27-5af0ceb

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- https://www.nvidia.com/en-us/drivers/details/243330/
=> Nvidia update to 570.144

packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
Getting incorrect checksum errors for vulkan-tools and vulkan-loader. Update said checksums.
=> Update vulkan-tools and vulkan-loader checksums

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.314
- vulkan-loader: update to 1.4.314
- vulkan-tools: update to 1.4.314
=> Vulkan update to 1.4.314

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.315
- vulkan-loader: update to 1.4.315
- vulkan-tools: update to 1.4.315
=> Vulkan update to 1.4.315

CONTRIBUTING.md, packages/readme.md, scripts/pkgbuilder.py, tools/update-scan
=> treewide: fix typos

tools/mkpkg/update_common_functions
- Fixes https://github.com/LibreELEC/LibreELEC.tv/pull/10057#discussion_r2090915718
=> tools/mkpkg/update_common_functions: replace wget with curl for fetching archives

tools/mkpkg/update_common_functions
=> tools/mkpkg/update_common_functions: replace wget with curl for fetching archive

packages/tools/amlogic-boot-fip/package.mk
- https://github.com/LibreELEC/amlogic-boot-fip/pull/23
=> amlogic-boot-fip: update to githash 16d007f

packages/addons/addon-depends/chrome-depends/unclutter/patches/unclutter-0002-fix-gcc-15-1-build.patch
Complete function template. Upstream is not maintained.
=> unclutter: fix gcc-15 build

packages/mediacenter/LibreELEC-settings/package.mk
User visible changes involve timezone selection and correcting typos in the country listing for wireless networks.
Behind the scene changes are helper functions that affect hostname and timezone selection.
=> LibreELEC-settings: update package

packages/sysutils/busybox/scripts/init
```
Updating Kernel    ... 100%
Updating Kernel md5... 100%
Updating System    ... 100%
Updating System md5... 100%
```
=> init: update md5 files on /flash

packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch
ref:
- https://github.com/libretro/scummvm/commit/e566a6432fd1951417bf78280cc7c741957fc419
- https://github.com/libretro/scummvm/issues/81
=> libretro-scummvm: fix armv7 GCC 15.1 internal compiler error

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- nvidia: update to 575.57.08
- xf86-video-nvidia: update to 575.57.08
- https://www.nvidia.com/en-us/drivers/details/245537/
=> Nvidia update to 575.57.08

packages/network/bluez/package.mk, packages/network/bluez/patches/bluez-12-fix-obexd-after-5_73.patch
release notes:
- https://github.com/bluez/bluez/releases/tag/5.83
- https://github.com/bluez/bluez/pulls?q=is%3Apr+closed%3A%3E2025-04-02+PW_SID
- https://github.com/bluez/bluez/compare/5.82...5.83
=> bluez: update to 5.83

.github/ISSUE_TEMPLATE/bug-report.md
Add some guidance on validating the bug report on the forum first.
=> bug-report.md: update instructions

projects/Samsung/patches/kodi/kodi-0002-LOCAL-changes-for-Odroid-XU3-XU4.patch
Since:
- https://github.com/xbmc/xbmc/pull/26838
- #10126
=> kodi (Samsung): update patch since ce89e7d

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.317
- vulkan-loader: update to 1.4.317
- vulkan-tools: update to 1.4.317
=> Vulkan update to 1.4.317

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.26.2
- gst-plugins-base: update to 1.26.2
- gstreamer: update to 1.26.2
=> gstreamer: update to 1.26.2

packages/addons/addon-depends/dotnet-runtime-depends/aspnet8-runtime/package.mk, packages/addons/addon-depends/system-tools-depends/tmux/package.mk, packages/addons/addon-depends/system-tools-depends/unrar/package.mk, packages/addons/service/rsyslog/package.mk, packages/addons/tools/dotnet-runtime/package.mk, packages/addons/tools/system-tools/package.mk
- system-tools: update addon (5)
- system-tools: include tmux as alternative to screen
- tmux: initial package
- https://github.com/tmux/tmux/wiki
- unrar: update to 7.1.7
- rsyslog: update to 8.2506.0 and addon (2)
- dotnet-runtime: update to 8.0.17 and addon (2)
- aspnet8-runtime: update to 8.0.17
=> Addon updates and addition of tmux

packages/x11/xserver/xorg-server/package.mk
log: https://gitlab.freedesktop.org/xorg/xserver/-/compare/xorg-server-21.1.17...xorg-server-21.1.18?from_project_id=371
=> xorg-server: update to 21.1.18

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.319
- vulkan-loader: update to 1.4.319
- vulkan-tools: update to 1.4.319
=> Vulkan update to 1.4.319

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.320
- vulkan-loader: update to 1.4.320
- vulkan-tools: update to 1.4.320
=> Vulkan update to 1.4.320

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.26.3
- gst-plugins-base: update to 1.26.3
- gstreamer: update to 1.26.3
=> gstreamer: update to 1.26.3

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/cb75fb5fc36078ea1c86e5596e2298f2b5e4721e...fc1ba2754b6201f6d532651917a446b5612ab430
=> kodi: update to githash fc1ba27

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.321
- vulkan-loader: update to 1.4.321
- vulkan-tools: update to 1.4.321
=> Vulkan update to 1.4.321

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/943fffad41d63431bcfbddc5270a7deb0a82a259...28fb9320ade537d241c81fad3fd65be95c798ffd
=> kodi: update to githash 28fb932

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/28fb9320ade537d241c81fad3fd65be95c798ffd...c0ad652ccc8c684a5689ba058dbc29dfca8c397a
=> kodi: update to githash c0ad652

packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
This adds support for kernel 6.12 and is also safe to use with kernel 6.6
=> [le12.2] ffmpeg: update rpi patch

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- xf86-video-nvidia: update to 575.64.05
- nvidia: update to 575.64.05
=> Nvidia update to 575.64.05

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/3ca92809f8b91de1da6b37c02cdf8df5641a3f3c...20732e8604d8c20181914deca8346376d67439e9
=> kodi: update to githash 20732e8

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/20732e8604d8c20181914deca8346376d67439e9...805b5f0e28f46199f77b49ca428ace8f1143c680
=> kodi: update to githash 805b5f0

packages/devel/readline/patches/0001-display-null-prompt.patch
see https://lists.gnu.org/archive/html/bug-readline/2025-07/msg00007.html
=> readline: add patch to fix crash in connmanctl and iwctl

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/805b5f0e28f46199f77b49ca428ace8f1143c680...67aa43ec040d8ceb060e8b3a976a0f5bf86eede6
=> kodi: update to githash 67aa43e

packages/mediacenter/LibreELEC-settings/package.mk
https://github.com/LibreELEC/service.libreelec.settings/compare/12b47f4...85f820e
=> LibreELEC-settings: update to 85f820e

packages/linux-firmware/firmware-imx/package.mk
release notes:
- https://docs.nxp.com/bundle/RN00210/page/topics/overview.html
- https://www.nxp.com/docs/en/user-guide/UG10163.pdf
=> firmware-imx: update to 8.28-994fa14

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.325
- vulkan-loader: update to 1.4.325
- vulkan-tools: update to 1.4.325
=> Vulkan update to 1.4.325

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/870ba8b8066a9f4c5a2cff083515aad6bd35b47e...ecef8959506b8fb3efeb80d2063016242d303e4b
=> kodi: update to githash ecef895

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/b65e2abbf093bfb04e7233e51acc6e42c6745f8f...27b156a54a8222aaa957b6d96e993706140729fb
=> kodi: update to githash 27b156a

packages/addons/service/syncthing/package.mk, tools/docker/jammy/Dockerfile
- syncthing: update to 2.0.2 and addon (4)
- tools/docker/jammy: update to building with go-1.23
=> syncthing: update to 2.0.2 and addon (4) and update go build to 1.23 in jammy

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> linux (RPi): update to 6.12.42

packages/graphics/mesa/package.mk
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/relnotes/25.2.1.rst?ref_type=heads
=> mesa: update to 25.2.1

packages/linux/package.mk, packages/tools/rpi-eeprom/package.mk, projects/RPi/devices/RPi/linux/linux.arm.conf, projects/RPi/devices/RPi2/linux/linux.arm.conf, projects/RPi/devices/RPi4/linux/linux.aarch64.conf, projects/RPi/devices/RPi5/linux/linux.aarch64.conf
=> [le12.2] linux (RPi): update to 6.12.42

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/22.0a1-Piers...66218443726d2839365d55e3b2ac20877ff270ed
=> kodi: update to githash 6621844

packages/graphics/mesa/patches/001-backport-mr36870-gallium-extra-samplers.patch
=> [le12.2] mesa: add patch with backport of mesa MR 36870

packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
log:
- https://github.com/janbar/pvr.mythtv/compare/67196eb8baaa35adeeccf9ea0a2c605fddc25f68...373c821d01d1cd2fd7be77123fd7fe2adab4c389
=> pvr.mythtv: update to 22.2.2 githash 373c821 and addon (5)

tools/docker/jammy/Dockerfile, tools/docker/noble/Dockerfile
- Backport of #10407 for LE12.0
- https://github.com/LibreELEC/actions/actions/runs/17199404079/job/48787162850
=> [le12.0] Docker fix caching of apt update

packages/addons/service/librespot/package.mk, packages/addons/service/minisatip/package.mk, packages/addons/service/syncthing/package.mk
- syncthing: update to 2.0.3 and addon (3)
- minisatip: update to 2.0.26 and addon (1)
- librespot: update to 0.7.0 and addon (1)
- backport of #10418
=> [le12.2] Addon updates

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/66218443726d2839365d55e3b2ac20877ff270ed...e49295490c2e46b9d0aff28bc9f8dbe0c7e347aa
=> kodi: update to githash e492954

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/e49295490c2e46b9d0aff28bc9f8dbe0c7e347aa...b9544fde80809913b8423b8d2dc3a1f39ff17e03
=> kodi: update to githash b9544fd

packages/graphics/vulkan/vulkan-headers/package.mk, packages/graphics/vulkan/vulkan-loader/package.mk, packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.326
- vulkan-loader: update to 1.4.326
- vulkan-tools: update to 1.4.326
=> Vulkan update to 1.4.326

packages/graphics/nvidia/package.mk, packages/x11/driver/xf86-video-nvidia/package.mk
- xf86-video-nvidia: update to 580.82.07
- nvidia: update to 580.82.07
- https://www.nvidia.com/en-us/drivers/details/253003/
=> Nvidia update to 580.82.07

packages/addons/addon-depends/jre-depends/jdk-aarch64-zulu/package.mk, packages/addons/addon-depends/jre-depends/jdk-arm-zulu/package.mk, packages/addons/addon-depends/jre-depends/jdk-x86_64-zulu/package.mk, packages/addons/tools/jre.zulu/package.mk
- jre.zulu: update to 8.88.0.19-8.0.462 and addon (2)
- jdk-x86_64-zulu: update to 8.88.0.19-8.0.462
- jdk-aarch64-zulu: update to 8.88.0.19-8.0.462
- jdk-arm-zulu: update to 8.88.0.19-8.0.462
=> jre.zulu: update to 8.88.0.19-8.0.462 and addon (2)

packages/addons/addon-depends/jre-depends/jdk-aarch64-zulu/package.mk, packages/addons/addon-depends/jre-depends/jdk-arm-zulu/package.mk, packages/addons/addon-depends/jre-depends/jdk-x86_64-zulu/package.mk, packages/addons/tools/jre.zulu/package.mk
- backport of #10463
- jre.zulu: update to 8.88.0.19-8.0.462 and addon (1)
- jdk-x86_64-zulu: update to 8.88.0.19-8.0.462
- jdk-aarch64-zulu: update to 8.88.0.19-8.0.462
- jdk-arm-zulu: update to 8.88.0.19-8.0.462
=> [le12.2] jre.zulu: update to 8.88.0.19-8.0.462 and addon (1)

packages/multimedia/gstreamer/gst-plugins-bad/package.mk, packages/multimedia/gstreamer/gst-plugins-base/package.mk, packages/multimedia/gstreamer/gstreamer/package.mk
- gst-plugins-bad: update to 1.27.2
- gst-plugins-base: update to 1.27.2
- gstreamer: update to 1.27.2
=> gstreamer: update to 1.27.2

packages/addons/addon-depends/comskip/patches/comskip-0001-drop-deprecated-ffmpeg8-ticks_per_frame.patch
- Fixes https://github.com/LibreELEC/LibreELEC.tv/pull/10402#issuecomment-3219459712
=> comskip: allow compile with ffmpeg8

packages/graphics/mesa/package.mk
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/docs/relnotes/25.2.3.rst?ref_type=heads
=> mesa: update to 25.2.3

packages/sysutils/systemd/package.mk
Release notes:
- https://github.com/systemd/systemd/releases/tag/v258
=> systemd: update to 258

scripts/pkgbuilder.py
This converts `scripts/pkgbuilder` to use fstrings.
=> pkgbuilder: convert to fstrings

packages/network/iwd/package.mk
=> iwd: update to 3.10

packages/sysutils/systemd/package.mk
=> [le12.2] systemd: remove provision.conf from tmpfiles.d

packages/network/bluez/system.d/bluetooth.service
=> [le12.2] bluez: fix bluetooth.service unit

packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/578817896cf13632b2ba770433d3fbec07cbc8eb...94baedc0678e92a83abd5a3fe5cedabb07758be0
=> kodi: update to githash 94baedc
