- packages/network/bluez/package.mk
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=fc6f5856d1775b39712b35049307afdd65df3d27
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=8b6432a8728f87aa328bd67f07a35a1e755d75e6
- https://github.com/bluez/bluez/pull/565
@smp79 / @chewitt / @lrusak - as reported / the suggested links. Indeed the make was generating the bluetooth.conf in the correct location, but we were safe_removing it.
built and run. Bluetooth again running as expected.
> bluez: fix relocation of dbus-1/bluetooth.conf

- projects/Amlogic/bootloader/canupdate.sh
Copied from Rockchip `$PROJECT` as the current script errors and displays the nocompat message.
> amlogic: fix canupdate.sh script

- projects/Allwinner/patches/linux/0014-drm_call_drm_atomic_helper_shutdown_at_shutdown.patch
One of the longstanding annoying issues for AW is that screen just goes blank at shutdown but it's not actually turned off. Patch in this PR fixes this. This is just a small, rebased portion of much larger patch, which is currently going through review process and will be included in mainline Linux.
> [LE12] Allwinner: linux: properly shutdown display at shutdown

- packages/tools/atf/package.mk
fix for: --no-warn-rwx-segments included
- https://developer.trustedfirmware.org/T996
- https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/19401
- Follow-up for #8117 including #7867
> atf: fix for --no-warn-rwx-segments

- packages/linux/patches/default/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
- packages/linux/patches/raspberrypi/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
See also https://forum.libreelec.tv/thread/27499-incorrect-audio-channel-configuration-mapping-on-multichannel-audio-to-hdmi-with/
ping @chewitt
> linux: add patch to fix broken channel map reporting in hdmi-codec

- packages/linux/patches/default/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
- packages/linux/patches/raspberrypi/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
> [le11] linux: add patch to fix broken channel map reporting in hdmi-codec

- packages/audio/alsa-lib/package.mk
alsa-lib 1.2.10 enabled large file support by default on 32bit platforms which leads to a crash when kodi, speaker-test etc try to access the dmix PCM.
Disable large file support in configure to fix this.
See also: https://forum.libreelec.tv/thread/27500-libreelec-nightly-rpi2-latest-builds-fail-to-boot/
ping @heitbaum
> alsa-lib: don't build with largefile support

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
- inputstream.adaptive: update 21.2.0-Omega to 21.2.1-Omega
- peripheral.joystick: update 21.1.6-Omega to 21.1.7-Omega
> [le12] kodi-binary-addons: update to latest versions

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.263
- vulkan-loader: update to 1.3.263
- vulkan-tools: update to 1.3.263
> Vulkan update to 1.3.263

- packages/devel/boost/package.mk
- fixes #6405
outcome is the same, as HOST_CXX is a wrapper for cache with g++. But ensures HOST_CXX as configured in config/functions is used.
```
LibreELEC.tv$ s/build boost:host
UNPACK      boost
BUILD      boost (host)
TOOLCHAIN      manual
###
###
###
###
g++ (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
###
###
> /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/host-g++ -x c++ -std=c++11 -march=native -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp …
```
> boost: use HOST_CXX compiler not g++

- projects/Allwinner/firmwares/brcmfmac_sdio-firmware.dat
It turns out that one FW is missing, which is used on OrangePi 3.
> [LE12] Allwinner: brcmfmac_sdio-firmware: update filter

- packages/tools/atf/package.mk
- projects/NXP/devices/iMX8/patches/atf/imx8mq-remove-ram-retention.patch
It seems that official ATF doesn't support iMX8mq anymore:
https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=e3c07d2f5a082d8bb1684ca026d1789a77b3c870
However, with two tricks (log removal, reverting feature that uses most RAM) it's possible to make it build again. Maybe we should look into NXP fork for the future.
> NXP: iMX8: atf: Fix building v2.9

- packages/debug/xorg-intel-gpu-tools/package.mk
- packages/tools/procps-ng/package.mk
Update of procps was blocked due to the dependency on xorg-intel-gpu-tools.
xorg-intel-gpu-tools 1.28 has now been release which supports procps-ng.
- https://gitlab.com/procps-ng/procps/-/blob/master/NEWS
- https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/commit/?id=31ec677ca24e7ed86e35f367f40a29d3d9f51c06
- https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/tree/NEWS
> procps update to 4.x and dependency of xorg-intel-gpu-tools

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.264
- vulkan-loader: update to 1.3.264
- vulkan-tools: update to 1.3.264
> Vulkan update to 1.3.264

- packages/mediacenter/kodi/config/advancedsettings.xml
This is no longer neccessary since kodi already supports reading the CPU temperature from the various hwmon sysfs entries.
Our downstream "cputemp" scripts are still included for now as the downstream "gputemp" scripts (which are still needed) symlink to them. This should be cleaned up at a later point.
> kodi: remove cputempcommand from advancedsettings.xml

- packages/security/openssl/package.mk
> openssl: update to 3.1.3

- packages/databases/mariadb-connector-c/patches/fix-build-error-on-32-bit-systems.patch
mariadb-connector-c: fix build error on 32-bit systems
-  3.3.7 fails compile with 32bit.
- https://jira.mariadb.org/browse/CONC-668?jql=project%20%3D%20CONC%20AND%20fixVersion%20%3D%203.3.8
- https://github.com/mariadb-corporation/mariadb-connector-c/commit/9f37c27bc8921ddc7e65ba8fc75cb4993380228a
> mariadb-connector-c: fix build error on 32-bit systems

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.17.11.html
```
Release Announcements
---------------------
This is the latest stable release of the Samba 4.17 release series.
Changes since 4.17.10
---------------------
o  Jeremy Allison <[jra@samba.org](mailto:jra@samba.org)>
* BUG 15419: Weird filename can cause assert to fail in
openat_pathref_fsp_nosymlink().
* BUG 15420: reply_sesssetup_and_X() can dereference uninitialized tmp
pointer.
* BUG 15430: Missing return in reply_exit_done().
* BUG 15432: TREE_CONNECT without SETUP causes smbd to use uninitialized
pointer.
o  Andrew Bartlett <[abartlet@samba.org](mailto:abartlet@samba.org)>
* BUG 15401: Improve GetNChanges to address some (but not all "Azure AD
Connect") syncronisation tool looping during the initial user sync …
```
> [le11] samba: update to 4.17.11

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
> [le11] inputstream.adaptive: update to 20.3.13-Nexus

- packages/mediacenter/kodi/patches/kodi-995.21-keymaps-change-remote-poweroff-action-to-show-shutdo.patch
Kodi's default power button handling is OK for typical HTPCs with window systems but it's the exact opposite of what users (and I) expect from a mediacenter appliance:
When pressing the power button on the (PC, RPi, ...) case users expect that LE/kodi shuts down - but instead kodi shows the shutdown menu and there's no way to shut down LE/kodi except grabbing a keyboard or remote and pressing enter or OK to perform the shutdown (pressing the power button again would just make the menu disappear).
OTOH When (accidentally) pressing the power button on an (IR) remote LE/kodi immediately shuts down - which is pretty bad as most devices (like eg RPi and others as well without special configuration) can't be powered up again by the IR remote and pressing the OK button to confirm that the …
> kodi: change remote power button behaviour to show the shutdown menu

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Release notes:
- https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html
Packages
- cargo-snapshot: update to 1.72.1
- rustc-snapshot: update to 1.72.1
- rust-std-snapshot: update to 1.72.1
- rust: update to 1.72.1
> rust: update to 1.72.1

- packages/mediacenter/kodi/config/70-libinput-ignore-power-button.rules
- packages/mediacenter/kodi/package.mk
- packages/sysutils/systemd/package.mk
This is a follow-up to #8161 fixing the "kodi shows shutdown menu instead of powering down" issue on GBM.
Note: as I'm not familiar with X11 or wayland in LE I won't tackle that in this PR and leave that to others to fix in a separate PR.
On GBM the issue is quite easy to fix as kodi will grab the input devices. So all we need to do is prevent libinput (and thus kodi) from handling the system / case / ACPI power button input devices and then leave it to logind to shut down the system when the power button is pressed.
All other input devices, like USB/RF/BT remotes or keyboards which have a power button will be handled by kodi and pressing the power button on those devices will show the shutdown menu.
logind won't "see" events from those devices as kodi has grabbed them.
But logind will …
> kodi GBM: shut down kodi when case power button is pressed

- licenses/fdk-aac.txt
- packages/audio/fdk-aac/package.mk
- packages/audio/pipewire/package.mk
Add fdk-aac to support pipewire aac.
adds functionality as raised in https://forum.libreelec.tv/thread/27349-possible-to-change-force-bluetooth-codec-sbc-to-aac/ 
setting as merge blocked until confirmation of testing.
> add aac support to pipewire

- packages/addons/addon-depends/system-tools-depends/mc/package.mk
Since pcre2 was introduced in mc, it doesn't build on host systems where libpcre2-dev is installed locally.
Add a configure option to point to the sysroot, where mc should search for pcre2.
> mc: fix build with local libpcre2-dev package

- packages/security/openssl/package.mk
> [le11] openssl: update to 3.0.11

- packages/addons/service/docker/source/system.d/service.system.docker.service
- Remove `kodi.service`'s indirect dependency on `docker.service` by changing `docker.service`'s install target from `multi-user.target` to `kodi.target`, which is after `kodi.service` is started so kodi start is not delayed due to docker service and containers.
- Change `docker.service`'s type back to `notify` so that other services that need to depend on `docker.service` do not prematurely start (currently `type=idle` results in other services starting as soon as docker service is started but before it's fully up)
`kodi.service` indirectly depends on `docker.service` through `multi-user.target`. This dependency causes `kodi.service` to be delayed due to `docker.service`, which can take a long time with many containers.
In a prior PR, we attempted to fix the delay by changing …
> docker: streamline systemd config

- packages/mediacenter/kodi/config/70-libinput-ignore-power-button.rules
This is a follow-up bugfix to #8165, the bitmap reporting in udev differs on 32bit and 64bit systems...
> kodi: extend power button udev rule to match on 32bit systems as well

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/graphics/vulkan/vulkan-tools/patches/vulkan-tools-995.01-cmakelists-opts.patch
- vulkan-headers: update to 1.3.266
- vulkan-loader: update to 1.3.266
- vulkan-tools: update to 1.3.266
> Vulkan update to 1.3.266

- packages/linux/patches/default/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
v2 of the patch, with a minor change (report "unknown" channel mappings in case of non-pcm audio) has been accepted for 6.7:
https://lore.kernel.org/alsa-devel/169625985045.65718.7789607105387288563.b4-ty@kernel.org/
RPi already got the patch update via the RPi kernel tree so only the default kernel patch needs updating
> linux (default): Replace hdmi-codec channel mapping patch with upstreamed version

- packages/linux/patches/default/linux-022-ASoC-hdmi-codec-Fix-broken-channel-map-reporting.patch
Backport of #8195 
RPi will get the patch via RPi kernel update in #8192
> [le11] linux (default): Replace hdmi-codec channel mapping patch with upstreamed version

- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- llvm: update to 17.0.2
- https://discourse.llvm.org/t/llvm-17-0-1-released/73549
- https://discourse.llvm.org/t/llvm-17-0-2-released/73840
- rust: update to 1.73.0
- https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html 
- cargo-snapshot: update to 1.73.0
- rustc-snapshot: update to 1.73.0
- rust-std-snapshot: update to 1.73.0
> Rust update to 1.73.0 and llvm to 17.0.2

- packages/mediacenter/kodi/package.mk
This should fix the "intermittent spinner" issue reported on the forum https://forum.libreelec.tv/thread/27169-intermittently-spinner-in-video-and-live-tv-stays-visible-channel-list-empty-aft
> [le11] kodi: update to current Nexus version

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.268
- vulkan-loader: update to 1.3.268
- vulkan-tools: update to 1.3.268
> Vulkan update to 1.3.268

- projects/Amlogic/config/kernel-firmware.dat
From https://forum.libreelec.tv/thread/27616-cannot-use-netgear-a6210-rt76x2u-linux-driver/
> amlogic: pick mt7662 firmware to AMLGX image

- packages/mediacenter/kodi/package.mk
After latest bump PVR radio stations do not work any more.
See https://forum.libreelec.tv/thread/27629-no-tvh-radio-playback-since-rpi4-test-build-13th-october/
Can confirm the issue with VNSI. Updating to current HEAD let radio play again
Tested on Generic-legacy.
> kodi: update to 8fd6170

- projects/Allwinner/patches/linux/0041-OrangePi-3-LTS-support.patch
This fix is included on other OrangePi boards with same Ethernet PHY, so it probably helps. It certainly doesn't hurt. I didn't have any issue with ethernet during my testing, so let's see if it solves the issue for others too.
> [LE12] Allwinner: linux: Attempt at fixing OPi3 LTS net stability issue

- packages/mediacenter/kodi/package.mk
Runtime tested on RPi5, pulseaudio is listed again in audio devices
> kodi: update to 21.0b1-Omega

- packages/databases/mariadb-connector-c/patches/fix-build-error-on-32-bit-systems.patch
This is updating the 32-bit build patch, to address a regression brought in by upstream patch.
> mariadb-connector-c: Resolve bad handshake on 32-bit platforms

- packages/linux-firmware/firmware-imx/package.mk
release notes:
Binary files updated in this release:
- firmware/hdmi/cadence/dpfw.bin
- firmware/hdmi/cadence/hdmitxfw.bin
- firmware/hdmi/cadence/signed_hdmi_imx8m.bin
- firmware/vpu/vpu_fw_imx8_dec.bin
- firmware/vpu/vpu_fw_imx8_enc.bin
> firmware-imx: update to 8.21

- packages/addons/tools/dvb-tools/package.mk
The current add-on description doesn't list things like `dvbscan` though it's included with dvb-apps, so expand the text to mention all binaries we include. No need to bump the rev or backport the change as it's purely cosmetic.
> dvb-tools: list dvb-apps binaries in the add-on description

- packages/security/openssl/package.mk
> [le11] openssl: update to 3.0.12

- packages/addons/addon-depends/rpi-tools-depends/lg-gpio/package.mk
This fixes ARMv8.arm build
build tested for ARMv8.arm, RPi2 and RPi5
> lg-gpio: fix wrong CROSS_PREFIX

- packages/security/openssl/package.mk
> [le12] openssl: update to 3.1.4

- packages/sysutils/dbus/package.mk
news:
- https://gitlab.freedesktop.org/dbus/dbus/-/blob/master/NEWS
dbus 1.15.8 (2023-08-21)
========================
Build-time configuration changes:
- For this version of dbus, Meson is the recommended build system for all Unix platforms. CMake continues to be recommended for Windows, but this recommendation might change to Meson in a future release, so please test the Meson build. See INSTALL for details.
- Autotools-generated files are no longer included in the tarball release. The Autotools build system is likely to be removed in a future dbus release, so Autotools users should migrate to Meson as soon as possible. It is still possible to build using Autotools, by following the same procedure as for a git clone (starting with the `./autogen.sh` script).
> dbus: update to 1.15.8 and meson

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/service/docker/package.mk
docker: update to 24.0.7 and addon (1)
- cli: update to 24.0.7
- containerd: update to 1.7.8
- moby: update to 24.0.7
```
nuc12:~ # docker version
Client:
Version:           24.0.7
API version:       1.43
Go version:        go1.21.3
Git commit:        afdd53b4e341be38d2056a42113b938559bb1d94
Built:             Sun Oct 29 10:13:49 UTC 2023
OS/Arch:           linux/amd64
Context:           default
Server:
Engine:
Version:          library-import
API version:      1.43 (minimum version 1.12)
Go version:       go1.21.3
Git commit:       library-import
Built:            library-import
OS/Arch:          linux/amd64
Experimental:     true
containerd:
Version:          1.7.8
GitCommit:        8e4b0bde866788eec76735cc77c4720144248fb7
runc:
Version:          1.1.9
GitCommit: …
```
> docker: update to 24.0.7 and addon (1)

- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/atk/package.mk
- packages/audio/pipewire/package.mk
- packages/audio/pulseaudio/package.mk
- packages/audio/wireplumber/package.mk
- packages/devel/glib/package.mk
- packages/devel/json-glib/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
- packages/sysutils/open-vm-tools/package.mk
- add glib as dependency for pipewire
- at-spi2-core: update dependencies
- glib: binaries must be executed from toolchain
- change require due to https://github.com/mesonbuild/meson/commit/f0b2ab8bb02f282499c6d0e5b9f6e5d55bb1419c in meson 1.2.2
- update glib:(target) to be dependent on glib:host
> update dependancies and fix glib pkgconfig

- packages/network/avahi/patches/avahi-0001-dbus--Use-non-deprecated-installation-path.patch
- packages/network/connman/package.mk
- with the recent #8098 fix for bluez relocating its dbus-1 config to /usr/share as documented in the dbus 1.14.0 Deprecations. This PR completes the move. It includes avahi’s upstream patch and the configure change for connman.
- Pulseaudio 16.99.1 (17.x) has incorporated this change, and once released will finalise this cleanup.
Ref: https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.14.0/NEWS#L45-51
once this PR is added the below will be the directory layout. Presently avahi, connman and pulseaudio are in /etc/dbus-1/system.d
```
nuc12:~ # ls /etc/dbus-1
session.conf  system.conf
nuc12:~ # ls /usr/share/dbus-1/system.d/
avahi-dbus.conf                 org.freedesktop.login1.conf
bluetooth.conf                  org.freedesktop.oom1.conf
connman-vpn-dbus.conf …
```
> install default dbus policies for the system bus into /usr/share/dbus-1/system.d

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mesa-demos/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/addon-depends/network-tools-depends/iperf/package.mk
- packages/addons/addon-depends/network-tools-depends/irssi/package.mk
- packages/addons/addon-depends/system-tools-depends/depends/oniguruma/package.mk
- packages/addons/addon-depends/system-tools-depends/libgpiod/package.mk
- packages/addons/addon-depends/system-tools-depends/pv/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/tools/multimedia-tools/package.mk
- packages/addons/tools/network-tools/package.mk
- packages/addons/tools/system-tools/package.mk
- system-tools: update addon (2)
- libgpiod: update to 2.1
- stress-ng: update to 0.17.00
- pv: update to 1.8.0
- oniguruma: update to 6.9.9
- network-tools: update addon (1)
- irssi: update to 1.4.5
- iperf: update to 3.15
- multimedia-tools: update addon (1)
- squeezelite: update to githash 8581aba (1.9.9.1449)
- mpg123: update to 1.32.3
- libmediainfo: update to 23.10
- mediainfo: update to 23.10
- multimedia-tools: add back mesa-demos for X11 builds
- mesa-demos: update to 9.0.0 and PKG_URL and meson
> [le12] tools addon updates 

- packages/devel/slang/package.mk
Drop the `slang` dependency: `pcre`.
`slang` is used only by `newt` which is used only by `installer`
installer > newt > slang > ~~pcre~~
- continuing cleanup of #6798
> slang: dont build with pcre

- packages/python/system/simplejson/package.mk
Compiling the c-extention currently fails, making simplejson fallback to the pure pyton implementation.
Adding the export makes sure the correct compiler is called.
These two package do the same:
`packages/python/graphics/Pillow/package.mk` and `packages/python/security/pycryptodome/package.mk`
Looks like the missing export was lost here: `simplejson: convert to new package format `
https://github.com/LibreELEC/LibreELEC.tv/commit/7cc5c21dd0264610e219569c4d96697711357055
> fix cross-compile simplejson

- packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/sources/Makefile
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscancontrol/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
- packages/addons/service/vdr-addon/package.mk
Since #8310 vdr-addon is not starting any more:
```
vdr[10336]: [10336] ERROR: /storage/.kodi/addons/service.multimedia.vdr-addon/plugin/libvdr-wirbelscancontrol.so.2.6.3: cannot open shared object file: No such file or directory
```
Only libvdr-wirbelscancontrol.so is available.Similar issue for vdr-plugin-xmltv2vdr.
With #8320 vdr-plugin-wirbelscan is failing because of missing object file:
```
vdr[3586]: [3586] ERROR: /storage/.kodi/addons/service.multimedia.vdr-addon/plugin/libvdr-wirbelscan.so.2.6.3: undefined symbol: _ZTVN8SI_EACEM14LogicalChannelE
```
Runtime tested by starting vdr-addon with all plugins enabled and DVB-T scan via script.config.vdr
> vdr-addon: update addon to (4) 

- packages/linux-firmware/intel-ucode/package.mk
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20231114
tested on ADL
before:
- [    0.000000] microcode: updated early: 0x42a -> 0x42c, date = 2023-04-18
after:
- [    0.000000] microcode: updated early: 0x42a -> 0x430, date = 2023-06-07
> intel-ucode: update to 20231114

- packages/linux-firmware/kernel-firmware/package.mk
- scripts/checkdeps
- tools/docker/jammy/Dockerfile
- tools/docker/kinetic/Dockerfile
- tools/docker/lunar/Dockerfile
- tools/docker/sid/Dockerfile
Since https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=cf8315ded9b422d2e8b620ffe8bb661221639c8f kernel-firmware requires rdfind. 
It is not possible to set a PKG_DEPENDS…=“rdfind:host” in kernel-firmware as `scripts/build linux` initiates an unpack which does not have a DEPENDS.
```
$ scripts/build linux
UNPACK      intel-ucode
UNPACK      kernel-firmware
ERROR: rdfind is not installed
FAILURE: scripts/unpack kernel-firmware during post_patch (package.mk)
${PKG_CURRENT_CALL} "${@}"
${SCRIPTS}/unpack "${p}" "${PARENT_PKG}"
${SCRIPTS}/unpack "${PKG_NAME}" …
```
> Kernel firmware update and rdfind

- tools/docker/jammy/Dockerfile
GHA Runner CI erroring as without apt-get update it can’t find the now updated OpenSSL and libc
> tools/docker/jammy: rerun apt-get update

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi5/options
> [le11] linux (RPi): update to 6.1.62

- packages/linux/package.mk
- projects/Rockchip/patches/linux/default/linux-1000-drm-rockchip.patch
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.1
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.2
6.6.1 - 30 patches
6.6.2 - 603 patches
- todo
- tab
- done
- RK upstreamed patches
``` …
```
> [LE12] linux: update to 6.6.x

- packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Sync with RPiOS 1.2-9+rpt2 bluez / 1:20230210-5+rpt2 brcmfmac versions
- Add Bluetooth coexistence settings on 43436/43436s
- Updated SYN43436S firmware for Zero 2 W
- 43455/43456 Fix BLE advertising on new phones
- Add more model-specific symlinks
> brcmfmac_sdio-firmware-rpi: update to 26ff205

- packages/linux/patches/default/linux-111-rtw88-from-next.patch
- packages/linux/patches/raspberrypi/linux-111-rtw88-from-next.patch
This patch is from wireless-next, it should be merged in 6.8.  It should resolve issues with frequent disconnects from beacon loss as reported by:
`iw wlan0 station dump`
This is caused by a bug in the driver that is filtering broadcast packets when FIF_ALLMULTI is disabled, when it should only filter multicast packets.  I would assume this would resolve the issue on all rtw88-based devices including SDIO devices.  I'm mainly using a USB dongle.
I have been running this for about two weeks on [RPi4 w/ 6.1 kernel](https://github.com/wagnerch/LibreELEC.tv/tree/rtw88-6.1.62) and it has resolved disconnect issues with the rtl8822bu dongle device.   I figured since all devices have moved to 6.6 (and since it is LTS then they are likely to stay on for the release of LE12) that this one patch …
> linux: rtw88: patch to reduce disconnects

- packages/network/connman/patches/connman-06-Revert-Don-t-add-route-for-invalid-dst-and-gateway-a.patch
Commit https://git.kernel.org/pub/scm/network/connman/connman.git/commit/?id=9eb1772d31b6fcf78e8711976696491aec9ff5df prevents the default route from being assigned to a WireGuard NIC interface; thus breaking the WireGuard "route all traffic down tunnel" configuration. It's possible to change the ConnMan service order to place WireGuard first using `connmanctl` but that's fiddly and will challenge most users so it's best to revert that commit until upstream figures out what's needed. 
I've reported the regression it to the ConnMan mailing list: https://lore.kernel.org/connman/A9CCB4B1-2A45-4C97-95E4-FBEDFAA8CD13@gmail.com/T/#u.
> connman: add revert patch to avoid wireguard route regressions

- packages/x11/driver/xf86-video-nvidia/package.mk
release notes:
- https://www.nvidia.com/download/driverResults.aspx/216530/en-us/
- Fixed a regression that prevented setting backlight brightness levels.
- Fixed a bug that could lead to UI corruption in nvidia-installer on systems with more than one initramfs file per kernel.
- Fixed a bug that caused games built on the Source 2 engine to hang when running under Xwayland.
> xf86-video-nvidia: update to 545.29.06

- packages/security/openssl/package.mk
Release notes:
- https://www.openssl.org/blog/blog/2023/11/23/OpenSSL32/
Release notes:
> openssl: update to 3.2.0

- packages/addons/addon-depends/multimedia-tools-depends/libplacebo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/patches/mpv-drmprime-0001-meson-also-expose-present_sync-for-VT-only-after.patch
- packages/python/graphics/glad/package.mk
- mpv has been migrated to meson from waf
- requires glad:host and libplacebo:target
- release notes:
- https://github.com/mpv-player/mpv/releases/tag/v0.37.0
> mpv-drmprime: update to 0.37.0

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.19.3.html
> samba: update to 4.19.3

- packages/network/iwd/package.mk
- Fix issue with buffer overflow for 32 byte SSIDs.
- Fix issue with deauthentication before FT work completes.
- Fix issue with power save disabling procedure.
> iwd: update to 2.10

- packages/tools/atf/package.mk
This document contains a summary of the new features, changes, fixes and known issues in each release of Trusted Firmware-A.
- **Architecture**
- **Performance Monitors Extension (FEAT_PMUv3)**
- This patch explicitly breaks the EL2 entry path. It is currently unsupported.
**See:** convert FEAT_MTPMU to C and move to persistent register init ([83a4dae](https://review.trustedfirmware.org/plugins/gitiles/TF-A/trusted-firmware-a/+/83a4dae1af916b938659b39b7d0884359c638185))
- **Libraries**
- **EL3 Runtime**
- **Context Management**
- Initialisation code for handoff from EL3 to NS-EL1 disabled by default. Platforms which do that need to enable this macro going forward
**See:** introduce INIT_UNUSED_NS_EL2 macro ([183329a](https://review.trustedfirmware.org/plugins/gitiles/TF-A/trusted-firmware- …
> atf: update to 2.10.0

- packages/graphics/vulkan/volk/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.271
- vulkan-loader: update to 1.3.271
- vulkan-tools: update to 1.3.271
- volk: initial package
> Vulkan update to 1.3.271

- packages/security/nss/package.mk
- packages/security/nss/patches/0001-Revert-Bug-1827303-Softoken-C_-calls-should-use-syst.patch
- includes a revert of 1827303 which was introduced in 3.94 (not yet fixed in 3.95)
- potential workaround was to compile with FIPS which was discounted, upstream have acknowledged that it should compile with the options being used
- upstream bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1856668
> nss: update to 3.95

- packages/textproc/libxml2/package.mk
- packages/textproc/xmlstarlet/patches/xmlstarlet-0246-fix-compile-with-libxml-2-12-0.patch
- libxml2: update to 2.12.1
- xmlstarlet: fix compile with libxml2 2.12.0
- https://github.com/dimitern/xmlstarlet/pull/246
- https://github.com/dimitern/xmlstarlet/issues/245
> libxml2: update to 2.12.1

- packages/sysutils/udevil/package.mk
This allows user to eg change ntfs (or all) mounts to read-only to prevent filesystem corruption in case of power loss
> udevil: support custom udevil.conf in /storage/.config

- packages/devel/glibc/package.mk
- https://man7.org/tlpi/api_changes/
> glibc: all kernels now 6.6

- packages/sysutils/v4l-utils/patches/v4l-utils-001-fix-meson-rc-keymaps.patch
logic for keytablesystemdir changed between configure and meson
was
AC_SUBST([keytablesystemdir], [$with_udevdir/rc_keymaps]) AC_SUBST([keytableuserdir], [$sysconfdir/rc_keymaps]) AC_SUBST([udevrulesdir], [$with_udevdir/rules.d])
is now the following and the -D is missing the rc_keymaps, where as previously udevrulesdir was defined seperately
- https://git.linuxtv.org/v4l-utils.git/tree/utils/keytable/meson.build?h=v4l-utils-1.26.0#n16 lines 16-22 and 62-70
> v4l-utils: fix meson.build for rc_keymaps

- packages/mediacenter/kodi/package.mk
> kodi: update to 21.0b2-Omega

- packages/linux/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
Kernel 6.1.64 introduced an ext4 regression which has been fixed in 6.1.66. See eg
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057843
https://lore.kernel.org/stable/20231205122122.dfhhoaswsfscuhc3@quack3/
> linux (RPi): update to 6.1.66

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- cargo-snapshot: update to 1.74.1
- rustc-snapshot: update to 1.74.1
- rust-std-snapshot: update to 1.74.1
- rust: update to 1.74.1
> Rust update to 1.74.1

- packages/devel/commons-lang3/package.mk
- packages/devel/commons-text/package.mk
- packages/devel/groovy/package.mk
- packages/mediacenter/kodi/package.mk
Support change introduced in Kodi 
- https://github.com/xbmc/xbmc/pull/24199
Includes
- commons-lang3: initial package
- commons-text: initial package
- groovy: initial package
- kodi: support change to Groovy/Apache commons binaries
```
Generic.x86_64-devel-20231213130757-6bd6735
Linux nuc12 6.6.7-rc1 #1 SMP Tue Dec 12 12:47:59 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:87d2d6f84799224f5fe63a6bba3e973e84e18fef). Platform: Linux x86 64-bit
Kodi compiled 2023-12-13 by GCC 13.2.0 for Linux x86 64-bit version 6.6.7 (394759)
Running on LibreELEC (heitbaum): devel-20231213130757-6bd6735 12.0, kernel: Linux x86 64-bit version 6.6.7-rc1 …
```
> kodi: support change to Groovy/Apache commons binaries

- packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
* Added support for OEM 102 key
* Added support for analog sticks in Vice cores
* Fixed Appveyor CI
* Fixed broken left shoulder in fallback buttonmap
* Fixed add-on using console to log instead of Kodi API
> game.libretro: Update to v20.2.6

- packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
* Added support for OEM 102 key (https://github.com/kodi-game/game.libretro/pull/115)
* Added support for analog sticks in Vice cores (https://github.com/kodi-game/game.libretro/pull/116)
* Fixed Appveyor CI (https://github.com/kodi-game/game.libretro/pull/119)
* Fixed broken left should button in fallback buttonmap (https://github.com/kodi-game/game.libretro/pull/113)
* Allow topology to specify type and subclass (https://github.com/kodi-game/game.libretro/pull/105)
> game.libretro: Update to v21.0.5

- packages/addons/addon-depends/system-tools-depends/inotify-tools/package.mk
- packages/addons/service/boblightd/package.mk
- packages/addons/service/proftpd/package.mk
- packages/addons/service/usbmuxd/package.mk
- packages/audio/alsa-utils/package.mk
- Follow up for #6094 - there has been 1 regression and 4 missed since the previous batch.
- alsa-utils: remove RPATH
- boblightd: remove RPATH
- inotify-tools: remove RPATH
- proftpd: remove RPATH
- usbmuxd: remove RPATH
> Remove libtool preserved temporary RPATH/RUNPATH from "shared object" ELF binaries (libraries/executables)

- packages/graphics/mesa/package.mk
```
Generic.x86_64-devel-20231214101154-d6d7c91
Linux nuc12 6.6.7 #1 SMP Thu Dec 14 10:29:50 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:87d2d6f84799224f5fe63a6bba3e973e84e18fef). Platform: Linux x86 64-bit
Kodi compiled 2023-12-14 by GCC 13.2.0 for Linux x86 64-bit version 6.6.7 (394759)
Running on LibreELEC (heitbaum): devel-20231214101154-d6d7c91 12.0, kernel: Linux x86 64-bit version 6.6.7
EGL_VENDOR …
```
> mesa: update to 23.3.1

- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/network/connman/package.mk
- packages/network/iwd/package.mk
- connman: update to githash f785c75
- https://git.kernel.org/pub/scm/network/connman/connman.git
- iwd: update to 2.11
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=e8e5d91e5a6be397bc6e56fe1bc2c71061eb2615
- iwlwifi-firmware: update to githash af0a298
- https://github.com/LibreELEC/iwlwifi-firmware/pull/47
> iwd, connman and iwlwifi-firmware package updates

- packages/network/connman/package.mk
The bump to connman HEAD imports refactoring changes that break the connman-vpn plugin resulting in no working vpn or internet access on hosts where the vpn is configured to start automatically on boot. 
I've reported the regression to the upstream maintainers and contributor whose refactoring caused the breakage. We need to avoid further bumps until this is resolved.
> connman: revert update to githash f785c75

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
Runtime tested on RPi 3B+, RPi 4 and RPi 5
> linux (RPi): update to 6.1.68

- packages/network/bluez/package.mk
log:
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/log/
fixes:
- Fix issue with not registering CSIS service.
- Fix issue with registering pairing callbacks.
- Fix issue with corruption during discovery filter parsing.
> bluez: update to 5.71

- projects/RPi/devices/RPi2/patches/kodi/000-temp-revert-fences.patch
The kodi fences changes cause a GUI lockup when playing a video without adjust refreshrate on.
Currently it's unclear whether it's a fault in kodi, mesa or the kernel.
Temporarily revert the kodi changes while this is being investigated.
See also forum report here: https://forum.libreelec.tv/thread/27876-nightly-video-playback-broken-on-rpi/
> kodi (RPi2): temporarily revert fences commits

- packages/sysutils/v4l-utils/patches/v4l-utils-001-fix-keytable-crash.patch
Recent keytable changes missed to properly initialize a buffer pointer so it used random memory when reading keymaps in legacy format and crashed:
```
LibreELEC:~ # ir-keytable -w .config/rc_keymaps/hauppauge
Segmentation fault (core dumped)
```
Patch also sent upstream: https://lore.kernel.org/linux-media/20231220160003.84042-1-hias@horus.com/T/#u
> v4l-utils: add patch to fix crash in ir-keytable

- projects/Allwinner/patches/linux/0026-phy-handle-optional-regulator-for-PHY.patch
Update patch for enabling Ethernet PHYs with multiple power regulators. This should fix issue reported in https://github.com/LibreELEC/LibreELEC.tv/pull/8200#issuecomment-1764501378
@dhewg can you confirm that this fixes issue for you? New patch should align behaviour with older approach.
> Allwinner: linux: Fix patch for ethernet PHY regulators

- packages/addons/browser/chrome/package.mk
- packages/addons/browser/chrome/source/bin/chrome-start
- packages/addons/service/librespot/package.mk
- packages/addons/service/mpd/package.mk
- packages/addons/service/snapclient/package.mk
- packages/addons/service/ttyd/package.mk
- packages/addons/service/ttyd/source/bin/ttyd.start
- packages/addons/service/tvheadend43/package.mk
- packages/addons/tools/dotnet-runtime/package.mk
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/addons/tools/network-tools/package.mk
- packages/addons/tools/system-tools/package.mk
- packages/mediacenter/kodi/profile.d/99-kodi.conf
- Following on from #6094 which removed incorrect stored RPATH/RUNPATH directories in the binaries, this new PR addresses #7602 in which private share libraries are made available system wide.
This PR addresses 3 specific areas:
- reduce the number of paths being added to LD_LIBRARY_PATH - a6cd2720475ac71f1ce6a475d3ad7c54a6e40ecb
- use lib.private for private shared libraries and update calling binaries with `'$ORIGIN/../lib.private'`. This keeps the shared libraries from polluting the LD_LIBRARY_PATH.
- in the case of addons like chrome, which set an LD_LIBRARY_PATH in there startup script, continue to use this method - but - target the lib.private
- for addons like dotnet that have internal dlopen approch available - use them - ref: …
> Keep addon introduced private shared libraries private to the addon

- packages/addons/service/boblightd/package.mk
- packages/addons/service/lcdd/package.mk
- packages/addons/service/minidlna/package.mk
- packages/addons/service/tigervnc/package.mk
- packages/addons/service/tigervnc/source/bin/tigervnc.start
- packages/addons/service/tvheadend42/package.mk
- packages/addons/service/vdr-addon/package.mk
- packages/addons/tools/flirc_util/package.mk
second batch of migrate to lib.private
- follow on from #8342
- part of #7602
packages updated
- boblightd: enable lib.private via RPATH
- flirc_util: enable lib.private via RPATH
- lcdproc: enable lib.private via RPATH
- minidlna: enable lib.private via RPATH
- tigervnc: enable lib.private via start script LD_LIBRARY_PATH
- tvheadend42: enable lib.private via RPATH
- vdr-addon: enable lib.private via RPATH
- only `libvdr-live` needed updating
remaining lib/*.so* in `addons` are only:
```
./jre.zulu:target/tools.jre.zulu/lib/libX11.so.6
./jre.zulu:target/tools.jre.zulu/lib/libXrender.so.1
./jre.zulu:target/tools.jre.zulu/lib/libxcb.so.1
./jre.zulu:target/tools.jre.zulu/lib/libXi.so.6
./jre.zulu:target/tools.jre.zulu/lib/libXtst.so.6
./jre.zulu:target/tools.jre.zulu/lib/libXinerama.so.1 …
```
> Part 2 - Keep addon introduced private shared libraries private to the addon

- packages/sysutils/tz/package.mk
This reverts commit 5360a1d7fde5985bc9e5e2983875a283e386881a.
tz is not compiling correctly on all architectures. Upstream change
> Revert "tz: update to 2023d"

- packages/sysutils/tz/package.mk
CFLAGS is no longer set as blank in the tz Makefile. Add the blank CFLAGS to our package.mk file https://github.com/eggert/tz/commit/c3ebd8e988462f248ff4dc576f669ef73448eaf5
> tz: update to 2023d

- packages/network/openssh/package.mk
Change log:
- https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog
Release notes:
- https://www.openssh.com/releasenotes.html#9.6p1
Release notes:
- https://www.openssh.com/txt/release-9.6p1
> openssh: update to 9.6p1

- packages/network/iwd/package.mk
log:
ver 2.12:
- Fix issue with DPP extra settings not being used.
- Fix issue with DPP and PRF+ handling on AARCH64.
- Add support for SAE password identifiers.
> iwd: update to 2.12

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
rust: update to 1.75.0
- cargo-snapshot: update to 1.75.0
- rustc-snapshot: update to 1.75.0
- rust-std-snapshot: update to 1.75.0
> rust: update to 1.75.0

- packages/graphics/libheif/package.mk
- packages/mediacenter/kodi-binary-addons/imagedecoder.heif/package.mk
When using imagedecoder.heif kodi is crashing with
```
kodi.sh[944]: /usr/lib/kodi/kodi.bin: symbol lookup error: /storage/.kodi/addons/imagedecoder.heif/imagedecoder.heif.so.20.1.0: undefined symbol: aom_codec_version
```
Reported in the [forum](https://forum.libreelec.tv/thread/27931-heif-add-on-does-not-work-for-libreelect-kodi-on-pi-v5/)
libheif can be build with different decoders and encoders. libaom (package aom) is detected and used after being installed to sysroot for ffmpegex. But imagedecoder.heif is only linking with libde265.
With this fix usage of libaom is explicit disabled.
Tested on Generic.
> imagedecoder.heif: fix crashing kodi

- scripts/image
When making the boodloader files optional I forgot to remove the code that unconditionally copies the bootloader files which broke noobs build for RPi4 and RPi5. Drop the code, the files are already copied by the for loop above.
> scripts/image: Fix RPi4 and RPi5 noobs build

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
```
Generic.x86_64-devel-20240105085514-3145359
Linux nuc12 6.6.9 #1 SMP Fri Jan  5 08:14:40 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:a808b5564c8416e2d84ca75b05e5bfd0fd4451c3). Platform: Linux x86 64-bit
Kodi compiled 2024-01-05 by GCC 13.2.0 for Linux x86 64-bit version 6.6.9 (394761)
Running on LibreELEC (heitbaum): devel-20240105085514-3145359 12.0, kernel: Linux x86 64-bit version 6.6.9
EGL_VENDOR …
```
> kodi: update to githash a808b55

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.8
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.9
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.10
6.6.8 - 166 patches
6.6.9 - 156 patches
6.6.10 - 49 patches
- todo
- tba
- done
- tba
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 …
```
> linux: update to 6.6.10

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.275
- vulkan-loader: update to 1.3.275
- vulkan-tools: update to 1.3.275
> Vulkan update to 1.3.275

- packages/mediacenter/kodi/package.mk
may resolve #8365
```
Generic.x86_64-devel-20240107083254-5cf49e4
Linux nuc12 6.6.10 #1 SMP Sat Jan  6 04:32:31 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:bdc4ab89ae787d359f47a0148ef95d512e0be4a9). Platform: Linux x86 64-bit
Kodi compiled 2024-01-07 by GCC 13.2.0 for Linux x86 64-bit version 6.6.10 (394762)
Running on LibreELEC (heitbaum): devel-20240107083254-5cf49e4 12.0, kernel: Linux x86 64-bit version 6.6.10
CApplication::CreateGUI - using the gbm …
```
> kodi: update to githash bdc4ab8

- packages/mediacenter/kodi/profile.d/99-kodi.conf
After  [065d3f5], LD_LIBRARY_PATH is not updated, even when there are *.so inside $addon/lib dirs.
Changing LD_LIBRARY_PATH in a set of code between parenthesis will keep the change only inside that scope.
I propose replacing the parenthesis as follows.
> Fix LD_LIBRARY_PATH update

- packages/sysutils/systemd/config/hosts.conf
- packages/sysutils/systemd/scripts/network-base-setup
Backport of #7696. This is the other half of https://github.com/LibreELEC/service.libreelec.settings/pull/292 which is in LE11. 
The two together move adding hostname and localhost to /etc/hosts from the addon to the image.
WIP as I haven't tested on LE11. I'm not expecting any actual further work to be needed. Opening because I expect the bugfix to be needed.
> systemd: network-base: add hostname and localhost to hosts.conf if not present [LE11]

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.19.4.html
> samba: update to 4.19.4

- packages/mediacenter/kodi/package.mk
> [le11] kodi: update to 20.3-Nexus

- packages/addons/addon-depends/vdr-plugins/vdr-plugin-robotv/package.mk
- packages/addons/service/mariadb/package.mk
Cleanup TOOLCHAIN
- more #5970
- mariadb: drop PKG_TOOLCHAIN hardcoding - already defaults to cmake
- vdr-plugin-robotv: drop PKG_TOOLCHAIN hardcoding - already defaults to cmake
> drop PKG_TOOLCHAIN hardcoding - already defaults to cmake

- packages/audio/pulseaudio/package.mk
Notes:
- /etc/dbus-1 is relocated to /usr/share/dbus-1
news:
- https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/1f020889c9aa44ea0f63d7222e8c2b62c3f45f68/NEWS
Changes at a glance:
* Notes for end users
*  Updates to ALSA UCM-based setups
*  Battery level indication to Bluetooth devices
*  Support for the Bluetooth FastStream codec
*  webrtc-audio-processing dependency updated
*  Trigger role groups added to module-role-cork
*  XDG base directory spec for profile-set loading
* Notes for application developers
* PA_RATE_MAX increased
* Notes for packagers
* webrtc-audio-processing dependency updated
> pulseaudio: update to 17.0

- packages/network/iwd/package.mk
Log: https://git.kernel.org/pub/scm/network/wireless/iwd.git/
ver 2.13:
+	Fix issue with handling netconfig and roaming conditions.
+	Fix issue with logging requirement for CMD_EXTERNAL_AUTH.
+	Fix issue with using OpenSSL 3.2 installations.
> iwd: update to 2.13

- packages/multimedia/media-driver/package.mk
Log:
- https://github.com/intel/media-driver/compare/intel-media-24.1.0...intel-media-24.1.1 
```
Generic.x86_64-devel-20240110113615-9110fee
Linux nuc12 6.6.10 #1 SMP Tue Jan  9 20:18:34 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:f6e78bff33d97e0de5ae5894d80d7f72b9b72f7d). Platform: Linux x86 64-bit
Kodi compiled 2024-01-09 by GCC 13.2.0 for Linux x86 64-bit version 6.6.10 (394762)
Running on LibreELEC (heitbaum): devel-20240110113615-9110fee 12.0, kernel: Linux x86 64-bit version 6.6.10
CApplication::CreateGUI - trying …
```
> media-driver: update to 24.1.1

- packages/devel/glibc/package.mk
ref:
- https://github.com/bminor/glibc/commits/release/2.38/master
- https://github.com/bminor/glibc/blob/release/2.38/master/NEWS
Security related changes:
CVE-2023-4527: If the system is configured in no-aaaa mode via /etc/resolv.conf, getaddrinfo is called for the AF_UNSPEC address family, and a DNS response is received over TCP that is larger than 2048 bytes, getaddrinfo may potentially disclose stack contents via the returned address data, or crash.
CVE-2023-4806: When an NSS plugin only implements the _gethostbyname2_r and _getcanonname_r callbacks, getaddrinfo could use memory that was freed during buffer resizing, potentially causing a crash or read or write to arbitrary memory.
CVE-2023-5156: The fix for CVE-2023-4806 introduced a memory leak when an application calls getaddrinfo …
> glibc: update to 2.38.1 (githash 44f757a)

- packages/network/bluez/package.mk
This solves a connection issue with Bluez reported in the forums: https://forum.libreelec.tv/thread/27897-12-0-nightly-can-t-connect-sony-ps3-bluetooth-remote/ and sourced from https://github.com/bluez/bluez/issues/696 and https://github.com/bluez/bluez/issues/673. AFAICT there's no impact on other input devices; a new config setting was added and this disables the new setting effectively restoring the original behaviour.
> bluez: support input.conf to handle PS3 controllers

- packages/network/bluez/package.mk
ver 5.72:
+	Fix issue with BAP and handling stream IO linking.
+	Fix issue with BAP and setup of multiple streams per endpoint.
+	Fix issue with AVDTP and potential incorrect transaction label.
+	Fix issue with A2DP and handling crash on suspend.
+	Fix issue with GATT database and an invalid pointer.
+	Add support for AICS service.
> bluez: update to 5.72

- packages/mediacenter/kodi/package.mk
Update to 15th Jan 2024
```
Generic.x86_64-devel-20240115113419-0115762
Linux nuc12 6.6.11 #1 SMP Mon Jan 15 11:38:27 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:f3f1df1eab2a38b7039e57635a6597b37510481a). Platform: Linux x86 64-bit
Kodi compiled 2024-01-15 by GCC 13.2.0 for Linux x86 64-bit version 6.6.11 (394763)
Running on LibreELEC (heitbaum): devel-20240115113419-0115762 12.0, kernel: Linux x86 64-bit version 6.6.11
CApplication::CreateGUI - using the gbm …
```
> kodi: update to githash f3f1df1

- packages/textproc/libxml2/patches/libxml2-0001-Revert-cmake-Fix-Python-installation.patch
This fixes the build of itstools:host
Upstream:
- https://gitlab.gnome.org/GNOME/libxml2/-/issues/662
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/02e12371964ed10c2c84ebb49760bc11b34913e1
> libxml2: install python host libraries into site-packages

- packages/linux/package.mk
This is to fix [REGRESSION 6.1.70] system calls with CIFS mounts failing with "Resource temporarily unavailable".
Build and runtime tested Generic and RPi5
> [LE11] kernel update to fix 6.1.70 cifs regression

- packages/devel/libevent/package.mk
- packages/network/cifs-utils/package.mk
- packages/network/nfs-utils/package.mk
- packages/sysutils/busybox/package.mk
- packages/virtual/network/package.mk
This fixes nfs and cifs mount issues since switching to util-linux's mount in #8497
Building nfs-utils is a bit of a beast, neither libevent nor sqlite are needed for mount.nfs but they are hard dependencies in configure.ac and it's not easy to only build mount.nfs. At least libevent is quite small and as I only build it as a static lib it doesn't impact image size. Any suggestions for build improvements are welcome, though.
Tested on RPi5 mounting cifs and nfs4 shares from my Debian Bookworm box using mount on the command line
> Add mount.nfs and mount.cifs helpers

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.11
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.12
6.6.11 - 124 patches
6.6.12 - 1 patch
- todo
- tba
- done
- tba
```
PROJECT=Allwinner …
```
> linux: update to 6.6.12

- scripts/mkimage
resize2fs creates a filesystem with unclean orphan file when resizing to more than 32GB if the orphan_file option is enabled, resulting in an unmountable storage partition after initial resize.
Explicitly disable the option until the issue is resolved.
Fixes: #8099
> scripts/mkimage: create storage filesystem without orphan_file option

- packages/devel/pcre/package.mk
- Since https://github.com/xbmc/xbmc/pull/24128
- pcrecpp is no longer used.
- Ref: #6798
> pcre: do not build pcrecpp

- packages/mediacenter/kodi/package.mk
Update to Jan 25, 2024 release
```
Generic.x86_64-devel-20240125103536-a036c73
Linux nuc12 6.6.13 #1 SMP Mon Jan 22 12:01:33 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.821) Git:06e228046c9f1316c7585bd61bfa1e28e22382da). Platform: Linux x86 64-bit
Kodi compiled 2024-01-25 by GCC 13.2.0 for Linux x86 64-bit version 6.6.13 (394765)
Running on LibreELEC (heitbaum): devel-20240125103536-a036c73 12.0, kernel: Linux x86 64-bit version 6.6.13
CApplication::CreateGUI - using …
```
> kodi: update to githash 06e2280

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Add firmware symlinks for Wandboard.
> brcmfmac_sdio-firmware: update to 3aecdd0

- packages/addons/addon-depends/ccid/package.mk
- packages/addons/addon-depends/chrome-depends/at-spi2-core/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/dotnet-runtime-depends/aspnet6-runtime/package.mk
- packages/addons/addon-depends/libvpx/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/libplacebo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/addon-depends/polkit/package.mk
- packages/addons/addon-depends/system-tools-depends/htop/package.mk
- packages/addons/addon-depends/system-tools-depends/lshw/package.mk
- packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
- packages/addons/browser/chrome/package.mk
- packages/addons/service/pcscd/package.mk
- packages/addons/tools/dotnet-runtime/package.mk
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/addons/tools/multimedia-tools/package.mk
- packages/addons/tools/system-tools/package.mk
- packages/multimedia/aom/package.mk
- ffmpeg-tools: update addon (1)
- aom: update to 3.8.1
- libvpx: update to 1.14.0
- dotnet-runtime: update aspnet6-runtime to 6.0.26 and addon (1)
- aspnet6-runtime: update to 6.0.26
- chrome: update to 121.0.6167.85 and addon (1)
- at-spi2-core: update to 2.51.0
- gtk3: update to 3.24.41
- pcscd: update addon (1)
- polkit: update to 124
- ccid: update to 1.5.5
- system-tools: update addon (2)
- htop: update to 3.3.0
- stress-ng: update to 0.17.04
- lshw: update to 02.20
- multimedia-tools: update addon (1)
- mpg123: update to 1.32.4
- squeezelite: update to githash 6de9e22 (2.0.0.1465)
- libplacebo: update to 6.338.2
> Addon updates

- packages/audio/taglib/package.mk
- packages/devel/utfcpp/package.mk
Release notes: https://taglib.org/
Kodi updated:
- https://github.com/xbmc/xbmc/pull/24339
- https://github.com/xbmc/xbmc/pull/24577
- https://github.com/LibreELEC/LibreELEC.tv/pull/8561/commits/d108bf373030a16361045b8ab74b9e722b51b9b0
depends on
- #8561 
new dependancy:
- utfcpp: initial package
> taglib: update to 2.0

- config/arch.x86_64
The idea is to provide flexible way to specify a custom CPU feature list, the same way is it's done in `arch.arm` and `arch.aarch64`
> Custom cpu features support for x86_64

- packages/audio/taglib/package.mk
This reverts commit 580a168e889cfa7b301a8fa3f9ae26274578d1c8.
further work is required to fully support taglib-2.0 in Kodi. The 64 bit compiles are fine, but 32 bit compiles fail. A further WIP patch to Kodi as below aligns all of the Kodi taglib overrides with the taglib.h (long was changed to off_t in taglib 2.0.)
```
From 57e7f16d7c172f92278c1df70c6b22764768f4b4 Mon Sep 17 00:00:00 2001
From: Rudi Heitbaum <rudi@heitbaum.com>
Date: Wed, 31 Jan 2024 07:06:50 +0000
Subject: [PATCH] update remaining custom taglib definitions for compile on 32bit
---
xbmc/music/tags/TagLibVFSStream.cpp | 18 +++++++++++++++++-
xbmc/music/tags/TagLibVFSStream.h   | 18 +++++++++++++++++-
2 files changed, 34 insertions(+), 2 deletions(-)
diff --git a/xbmc/music/tags/TagLibVFSStream.cpp …
```
> Revert "taglib: update to 2.0"

- packages/graphics/mesa/package.mk
```
Generic.x86_64-devel-20240201053824-b7f7563
Linux nuc12 6.6.14 #1 SMP Tue Jan 30 20:11:32 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0-BETA2 (20.90.822) Git:cabba8df735f50a317a229be4f5d6a3b7ad2fbc3). Platform: Linux x86 64-bit
Kodi compiled 2024-02-01 by GCC 13.2.0 for Linux x86 64-bit version 6.6.14 (394766)
Running on LibreELEC (heitbaum): devel-20240201053824-b7f7563 12.0, kernel: Linux x86 64-bit version 6.6.14 …
```
> mesa: update to 24.0.0

- packages/mediacenter/kodi/package.mk
log:
- https://github.com/xbmc/xbmc/compare/cabba8df735f50a317a229be4f5d6a3b7ad2fbc3...827936d3f0cc2fc39499b3019586d4e7a10ef743
> kodi: update to githash 8020920 (2023-02-03)

- packages/mediacenter/kodi/package.mk
log:
- https://github.com/xbmc/xbmc/compare/80209208f0aed03fc13abb56afceccd3328accfe...8c25e11a024d48e7505188a8b45695eadf6c79b4
> kodi: update to githash 8c25e11 (Feb 7 2024)

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
Release notes:
- https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html
> rust: update to 1.76.0

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.278
- vulkan-loader: update to 1.3.278
- vulkan-tools: update to 1.3.278
> Vulkan update to 1.3.278

- packages/security/openssl/cert/cacert.pem
Sha was updated on the source.
This commit updates cacert.pem certificate bundle with mk-ca-bundle.pl script using the content of [certdata][1] associated with mozilla/gecko-dev@66afa4a9c748ec7186a90adc735ec0fa278cee4e,
[1]: https://github.com/mozilla/gecko-dev/blob/66afa4a9c748ec7186a90adc735ec0fa278cee4e/security/nss/lib/ckfw/builtins/certdata.txt?raw=true
> cacert.pem: update to 2024-02-14

- packages/mediacenter/kodi/package.mk
Log
- https://github.com/xbmc/xbmc/compare/21.0b3-Omega...e085b62f103a3714a0efcc8ead1bd498bb92fcdd
should fix
- https://forum.libreelec.tv/thread/28095-pvr-vuplus-webinterface-cannot-be-reached-since/?postID=188292&highlight=pvr.vuplus#post188292
- https://github.com/xbmc/xbmc/issues/24629
- https://github.com/xbmc/xbmc/pull/24733
> kodi: update to githash e085b62

- tools/docker/jammy/Dockerfile
> jammy/Dockerfile needs to include the symbolic links for go-1.21

- packages/linux/package.mk
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.17
6.6.17 - 124 patches
- todo
- tba
- done
- tba
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build …
```
> linux: update to 6.6.17

- packages/mediacenter/LibreELEC-settings/package.mk
Add support for RPi5 firmware updating
> LibreELEC-settings: update to 64b036e

- packages/linux-drivers/RTL8812AU/patches/RTL8812AU-PR1134.patch
Required patch for RTL8812AU to compile with kernel 6.7
- https://github.com/aircrack-ng/rtl8812au/pull/1134
> RTL8812AU: Fix change_beacon for kernel 6.7

- packages/sysutils/systemd/config/system.d/openvpn.service.sample
The `Requires=` and `After=` dependencies, belong to the `Unit` section.
> sysutils: fix openvpn.service.sample

- packages/mediacenter/kodi/package.mk
Feb 28, 2024
- https://github.com/xbmc/xbmc/compare/480476cb59264f54d0c85da2529d2bd64a4874ad...e625f24a0b207741d1d45d6c78c45afe7901a84b
> kodi: update to githash e625f24

- packages/graphics/mesa/package.mk
The bugfix release 24.0.2 is now available.
The next bugfix release is due in two weeks, on March 13th.
Cheers,
Eric
---
Boyuan Zhang (1):
radeonsi/vcn: only use multi slices reflist when available
Chia-I Wu (1):
radv: fix pipeline stats mask
Chris Rankin (2):
vdpau: Declare texture object as immutable using helper function.
vdpau: Refactor query for video surface formats.
Connor Abbott (1):
tu: Follow pipeline compatibility rules for dynamic descriptors
Daniel Schürmann (1):
spirv: Fix SpvOpExpectKHR
Daniel Stone (2):
egl/wayland: Add opaque-equivalent FourCCs
egl/wayland: Fix EGL_EXT_present_opaque
Dave Airlie (2):
nouveau/winsys: fix bda heap leak.
nvk: fix dri options …
> mesa: update to 24.0.2

- packages/mediacenter/kodi/package.mk
Mar 1, 2024
- https://github.com/xbmc/xbmc/compare/e625f24a0b207741d1d45d6c78c45afe7901a84b...36c6d1449858c4d5fa3299af82ae3cf2341b3db3
> kodi: update to githash 36c6d14

- packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
- includes https://github.com/LibreELEC/brcmfmac_sdio-firmware/pull/36
> brcmfmac_sdio-firmware: update to githash d4382f9

- packages/devel/groovy/package.mk
This reverts commit 6ea9e1e58d0f95c4504b30d821b97a09962ca8f8.
builds with 4.0.19 are not consistently building.
```
[1566/1695] Generating AddonModuleXbmcaddon.i.cpp
FAILED: build/swig/AddonModuleXbmcaddon.i.cpp /build/build.LibreELEC-Dragonboard.aarch64-12.0-devel/build/kodi-7075efedfbf13f4f5bfa28e2fa57d7421ff5ab92/.aarch64-libreelec-linux-gnu/build/swig/AddonModuleXbmcaddon.i.cpp cd /build/build.LibreELEC-Dragonboard.aarch64-12.0-devel/build/kodi-7075efedfbf13f4f5bfa28e2fa57d7421ff5ab92/.aarch64-libreelec-linux-gnu/build/swig && /build/build.LibreELEC-Dragonboard.aarch64-12.0-devel/toolchain/bin/swig -w401 -c++ -o AddonModuleXbmcaddon.i.xml -xml -I/build/build.LibreELEC-Dragonboard.aarch64-12.0-devel/build/kodi-7075efedfbf13f4f5bfa28e2fa57d7421ff5ab92/xbmc -xmllang python …
```
> Revert "groovy: update to 4.0.19"

- packages/emulation/libretro-scummvm/package.mk
- packages/emulation/libretro-scummvm/patches/0001-libretro-Fix-missing-library-version.patch
- packages/emulation/libretro-scummvm/patches/0002-libretro-Move-scummvm.ini-to-writable-save-directory.patch
- packages/mediacenter/kodi-binary-addons/game.libretro.scummvm/package.mk
no more repository `https://github.com/libretro/scummvm-wrapper`
> libretro-scummvm: fix build after repository change

- packages/network/iwd/package.mk
ver 2.16:
+	Fix issue with uninitialized variable and DPP encrypt.
+	Fix issue with Access Point mode and ATTR_MAC validation.
+	Fix issue with Access Point mode and frequency attributes.
+	Fix issue with P2P and handling client info description.
+	Fix issue with P2P and handling parsing of service info.
+	Fix issue with netconfig and handling domain list.
+	Add support for forcing a default ECC group.
> iwd: update to 2.16

- packages/mediacenter/kodi/package.mk
March 3 2024
https://github.com/xbmc/xbmc/compare/7075efedfbf13f4f5bfa28e2fa57d7421ff5ab92...8404b9f510f84b7416f5ff3f2bc7567a93d3dbb6
> kodi: update to githash 8404b9f

- packages/mediacenter/kodi/package.mk
March 6 2024
https://github.com/xbmc/xbmc/compare/8404b9f510f84b7416f5ff3f2bc7567a93d3dbb6...495a07ad6805ffc17475d6b7181a92ce16d1c01e
> kodi: update to githash 495a07a

- packages/graphics/vulkan/glslang/package.mk
- packages/graphics/vulkan/spirv-headers/package.mk
- packages/graphics/vulkan/spirv-tools/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.280
- vulkan-loader: update to 1.3.280
- vulkan-tools: update to 1.3.280
- glslang: update to 14.1.0
- spirv-tools: update to githash 04896c4
- spirv-headers: update to githash 8b246ff
> Vulkan update to 1.3.280 and glslang update to 14.1.0

- packages/linux/package.mk
build tested for
- A64.arm
- Generic-legacy.x86_64
- Generic.x86_64
- H3.arm
- H5.arm
- H6.arm
- R40.arm
- RK3288.arm
- RK3328.arm
- RK3399.arm
runtime tested on my N100
- Generic.x86_64
> [LE11] linux: default kernel update 6.1.80

- packages/linux/package.mk
build tested for
- RPi2.arm
- RPi4.arm
- RPi5.arm
runtime tested for
- RPi4.arm
- RPi5.arm
> [LE11] linux (RPi): kernel update 6.1.77-14c373b

- projects/RPi/devices/RPi4/config/config.txt
Align RPi4 with RPi5 which supports 4kp60 output OOTB.
Note that this will only affect new installations, config.txt on existing installations won't be altered by this change.
> RPi4: enable 4kp60 output by default

- packages/graphics/mesa/package.mk
The bugfix release 24.0.3 is now available.
The next bugfix release is due in two weeks, on March 27th.
Cheers,
Eric
---
Boyuan Zhang (1):
meson: bump the minimal required vdpau version to 1.4
intel/compiler: Fix SIMD lowering when instruction needs a larger SIMD
Chia-I Wu (1):
aco: fix nir_op_pack_32_4x8 handling
Christian Gmeiner (1):
etnaviv: Fix how we determine the max supported number of varyings
Corentin Noël (1):
zink: Return early if the file descriptor could not have been duplicated/acquired
Daniel Schürmann (1):
radv: fix initialization of radv_shader_layout->use_dynamic_descriptors
Danylo Piliaiev (1):
tu: Fix dynamic state not always being …
> mesa: update to 24.0.3

- packages/linux-firmware/intel-ucode/package.mk
- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- projects/Generic/linux/linux.x86_64.conf
- Fix: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/admin-guide/hw-vuln/reg-file-data-sampling.rst?h=linux-6.6.y
- iwlwifi-firmware: update to githash a1577a4
- intel-ucode: update to 20240312
- linux (Generic): update .config for 6.6.22
- linux: update to 6.6.22
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.22
6.6.22 - 60 patches
- fixes
- intel ucode updates
- Intel iwlwifi 9000 firmware
- Generic config
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.gi …
> Linux 6.6.22

- packages/linux/package.mk
> linux (RPi): update to 6.6.22

- packages/linux/package.mk
This adds command queuing support for class A2 SD cards on RPi5 which can improve performance a lot (factor 2-4 on random 4k reads/writes).
This new feature is disabled by default and needs to be enabled manually with `dtparam=sd_cqe` in config.txt - do that at your own risk though.
See also the forum thread here: https://forums.raspberrypi.com/viewtopic.php?t=367459
> linux (RPi): update to 6.6.22-4a3a03d

- packages/devel/yajl/package.mk
- use upstream package instead of self hosted
- disable compile warnings
> cleanup: yajl

- packages/linux-drivers/RTL8812AU/package.mk
- error reimplemented
- https://github.com/aircrack-ng/rtl8812au/commit/123e373f884af3dbaca594a73463f744bac59d60
> RTL8812AU: update to githash 4f645ee

- packages/addons/service/mariadb/patches/1063738-revert-c432c9ef.patch
- https://jira.mariadb.org/browse/MDEV-33429
- https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/cad4f02094460d54b84de68f61ae1d879ab97222
- https://salsa.debian.org/mariadb-team/mariadb-server/-/raw/cad4f02094460d54b84de68f61ae1d879ab97222/debian/patches/1063738-revert-c432c9ef.patch
> mariadb: workaround fix for arm32 compiles of 10.11.7

- packages/linux-drivers/RTL8192DU/package.mk
- includes upstreamed fix 6bce4b0c747e81ed0dbeeb4b86d4f90ab65c44a7 from #8759
- log:
- https://github.com/lwfinger/rtl8192du/compare/a82c83ec8d1363a8bd1e312378c1ba47971d0012...b65f87820526cd8835c5cac19fd7e659c84e8215
> RTL8192DU: update to githash b65f878

- projects/Generic/patches/kodi/000-temp-revert-fences.patch
The change causes kodi to disbale the last image or a black screen when coming out of sleep.
- fixes #8488
- https://github.com/xbmc/xbmc/issues/24760
- https://github.com/xbmc/xbmc/pull/23921
- https://forum.libreelec.tv/thread/28349-kodi-black-screen-after-waking-from-sleep/?postID=190197#post190202
> kodi (Generic): add temp patch to revert xbmc/23921 commit

- packages/sysutils/busybox/scripts/init
For the SYSTEM copy to /dev always use /dev/SYSTEM as target name to not deal with fancy path or filenames.  
Thanks @HiassofT for clearing it up for me why it is best using /dev/SYSTEM.  
As far as i can tell all the rest of init is fine with BOOT_IMAGE and SYSTEM_IMAGE having slashes in there.  
Just toram was broken.
> busybox: init: fix toram when SYSTEM_IMAGE is with path

- packages/multimedia/bento4/package.mk
log:
- https://github.com/xbmc/Bento4/compare/1.6.0-639-8-Omega...1.6.0-641-Omega
1.6.0-641-Omega Latest
- Updated to upstream release v1.6.0-641
- Cleanup to remove unused code (from revert commit 1b208a7)
> bento4: update to 1.6.0-641-Omega

- packages/graphics/mesa/package.mk
panvk: Disable global offset on varying and non-VS attribute descriptors
Caio Oliveira (2):
intel/brw: Use helper to create accumulator register
intel/brw: Fix validation of accumulator register
Charlie Turner (1):
{vulkan,radv,anv}/video: fix issue in H264 scaling lists derivation
Corentin Noël (2):
st_pbo/compute: Use the correct structure type when allocating a specialized key
zink: Make sure to initialize all the fields of VkMemoryBarrier
radv/video: fix h265 decode with unaligned w/h
radv/video: Set maxActiveReferencePictures to 16 for H264/5
Eric Engestrom (7):
docs: add sha256sum for 24.0.3
.pick_status.json: Update to 9b6d6c1d2d0c8a517e974abbf7b75a47a607f6ec
.pick_status.json: Update to eac703f69128d5aa6879c9becbad627ce08a7920 …
> mesa: update to 24.0.4

- packages/compress/xz/package.mk
xz release tarballs 5.6.0 and 5.6.1 have been compromised with malicious code
https://www.openwall.com/lists/oss-security/2024/03/29/4
https://github.com/tukaani-project/xz/issues/92
Fixes: #8772
> xz: revert to 5.4.6

- packages/compress/libarchive/patches/libarchive-upstreamed-more-robust-error-PR2101.patch
This adds an upstreamed patch for libarchive that revises a change made by the xz-utils maintainer. Upstream PR here: https://github.com/libarchive/libarchive/pull/2101
Tested by installed and running several addons. Not sure what else uses libarchive.
> libarchive: add upstream patch around error handling

- packages/lang/Python3/package.mk
schedule:
- https://peps.python.org/pep-0664/#bugfix-releases
log:
- https://www.python.org/downloads/release/python-3119/
- https://docs.python.org/release/3.11.9/whatsnew/changelog.html#python-3-11-9
> Python3: update to 3.11.9

- packages/linux/package.mk
- linux: update to 6.6.25
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.24
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.25
6.6.24 - 396 patches
6.6.25 - 11 patches
- fixes
- tba
``` …
```
> linux: update to 6.6.25

- packages/graphics/mesa/package.mk
Release notes:
- https://lists.freedesktop.org/archives/mesa-announce/2024-April/000754.html
build option change:
- https://gitlab.freedesktop.org/mesa/mesa/-/commit/066c61c7485e24394fe76d17d201bc479f7cbd16
```
Generic.x86_64-devel-20240411135107-065d63b
Linux nuc12 6.6.26 #1 SMP Thu Apr 11 13:35:43 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0 (21.0.0) Git:21.0-Omega). Platform: Linux x86 64-bit
Kodi compiled 2024-04-09 by GCC 13.2.0 for Linux x86 64-bit version 6.6.25 (394777)
Running on LibreELEC (heitbaum): devel-20240411135107-065d63b 12.0, kernel: Linux x86 64-bit version 6.6.26
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS …
```
> mesa: update to 24.0.5

- packages/linux/package.mk
- projects/Generic/linux/linux.x86_64.conf
- linux: update to 6.6.26
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.26
6.6.26 - 255 patches
- fixes
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2bb69f5fc72183e1c62547d900f560d0e9334925
```
PROJECT=Allwinner ARCH=arm …
```
> linux: update to 6.6.26

- packages/linux-drivers/RTL8812AU/package.mk
includes:
- https://github.com/aircrack-ng/rtl8812au/commit/63cf0b4584aa8878b0fe8ab38017f31c319bde3d
- Update ioctl_cfg80211.c - support for kernel 6.9
> RTL8812AU: update to githash 63cf0b4

- packages/addons/addon-depends/libimobiledevice-glue/package.mk
- missed this package in the #8804
> libimobiledevice-glue: update to 1.2.0

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.19.6.html
> samba: update to 4.19.6

- packages/linux/package.mk
- projects/Generic/linux/linux.x86_64.conf
- projects/Rockchip/patches/linux/default/linux-1000-drm-rockchip.patch
- linux: update to 6.6.26
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.27
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.28
6.6.27 - 114 patches
6.6.28 - 122 patches
- fixes
- Spectre BHI
```
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build …
```
> linux: update to 6.6.28

- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
This should fix the Hifiberry DAC+ Pro and video decode issues reported on the forum
https://forum.libreelec.tv/thread/28386-rpi-4-choppy-audio-with-hifiberry-dac2-pro/
https://forum.libreelec.tv/thread/28391-cvideoplayeraudio-process-stream-stalled/
> linux (RPi): update to 6.6.28

- packages/linux/package.mk
Another fix for a couple of soundcards was just added https://github.com/raspberrypi/linux/commit/fe027c6c6cb299f17db69d04087b2ca973f78510
> linux (RPi): update to 6.6.28-fe027c6

- packages/network/bluez/package.mk
- packages/network/bluez/patches/bluez-50-shared-uhid--Fix-crash-if-bt_uhid_destroy-free-replay.patch
Attempt to address issue reported at https://forum.libreelec.tv/thread/28431-libreelec-omega-12-beta2/?postID=191001#post191001
seems to be addressed in 5.75 (with the post patch) read https://github.com/bluez/bluez/issues/777#issuecomment-2058613174 and the following 2 comments.
post ver 5.75:
- shared/uhid: Fix crash if bt_uhid_destroy free replay structure
ver 5.75:
- Fix issue with build system and header inclusion.
ver 5.74:
- Fix issue with not enabling Wideband Speech when available.
- Fix issue with UserspaceHID and Bluetooth Classic devices.
- Fix issue with checking for services being connected.
- Fix issue with GATT client connection creation.
- Fix issue with OBEX and small file transfers.
- Fix issue with handling pairing with Apple AirPods.
log:
- …
> bluez: update to 5.75

- packages/tools/rpi-eeprom/package.mk
This fixes a possible performance regression on RPi5
See https://github.com/raspberrypi/rpi-eeprom/commit/9a5a522ee8a17d4d445b4bb108c4da75bed829fe
> rpi-eeprom: update RPi5 bootloader to 2024-04-20

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
- packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
- packages/addons/addon-depends/podman/podman-bin/package.mk
- packages/addons/service/docker/package.mk
- packages/addons/service/minisatip/package.mk
- packages/addons/service/podman/package.mk
- packages/addons/tools/multimedia-tools/package.mk
- multimedia-tools: update addon (2)
- mpv-drmprime: update to 0.38.0
- libmediainfo: update to 24.04
- mediainfo: update to 24.04
- podman: update to 5.0.2 and addon (3)
N- podman-bin: update to 5.0.2
- docker: update to 26.0.2 and addon (3)
- moby: update to 26.0.2
- cli: update to 26.0.2
- minisatip: update to 1.3.6 and addon (1)
> Addon updates for LE12

- packages/addons/service/tvheadend43/package.mk
Tvheadend 4.3 is the recommended version for users to install (4.2 is effectively EOL) so remove the "Alpha" label.
> tvheadend43: remove alpha label

- packages/linux/package.mk
This fixes vc4.force_hotplug not ignoring all hotplug events https://github.com/raspberrypi/linux/pull/6123
and should fix DVB-T TV HAT issues on RPi5 https://github.com/raspberrypi/linux/pull/6118
> linux (RPi): update to 6.6.28-8d40b03

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.20.0rc1.html
- https://www.samba.org/samba/history/samba-4.20.0rc2.html
- https://www.samba.org/samba/history/samba-4.20.0rc3.html
- https://www.samba.org/samba/history/samba-4.20.0rc4.html
- https://www.samba.org/samba/history/samba-4.20.0.html
> samba: update to 4.20.0

- packages/sysutils/busybox/scripts/fs-resize
This ensures the /storage filesystem will have the correct options (block size, inode_ratio etc) for the target partition size.
> busybox: use mke2fs instead of resize2fs

- packages/devel/elfutils/package.mk
remove unknown options from build.
- fixes build warning:
- `configure: WARNING: unrecognized options: --disable-static, --enable-shared`
> elfutils: cleanup _CONFIGURE_OPTS

- packages/devel/libcec/patches/0001-WIP-support-multiple-dev-cecX-devices.patch
Currently on a Pi4/5, LibreELEC is largely usable when connected to second hdmi port, except CEC doesn't work as it's hard-coded to /dev/cec0.
This generates extra support issues. With this patch it does use the correct cec interface when booting connected to second hdmi port.
> cec: Allow cec driver to handle multiple instances

- packages/graphics/mesa/package.mk
Bas Nieuwenhuizen (1):
radv: Fix differing aspect masks for multiplane image copies.
nir/lower_blend: Fix nir_blend_logicop() for 8/16-bit integer formats
egl/dri2: don't bind dri2 for zink
Eric Engestrom (7):
docs: add sha256sum for 24.0.5
.pick_status.json: Update to 2bb102f020b3a5834d219ab474c6bcdd02f88d09
.pick_status.json: Update to 7a1779edc7fb82c891e584074b95d1a4801c1782
.pick_status.json: Mark 3c673919c348b0611595b32fcc8a3d376868c830 as denominated
.pick_status.json: Update to cd5c9870ea1d7e73d05f125b229f34e5749c8345
docs: add release notes for 24.0.6
VERSION: bump for 24.0.6
Eric R. Smith (3):
panfrost: fix a GPU/CPU synchronization problem
panfrost: mark separate_stencil as valid when surface is valid
panfrost: fix an incorrect stencil clear …
> [le13] mesa: update to 24.0.6

- packages/graphics/mesa/package.mk
- backport of #8840 
Bas Nieuwenhuizen (1):
radv: Fix differing aspect masks for multiplane image copies.
nir/lower_blend: Fix nir_blend_logicop() for 8/16-bit integer formats
egl/dri2: don't bind dri2 for zink
Eric Engestrom (7):
docs: add sha256sum for 24.0.5
.pick_status.json: Update to 2bb102f020b3a5834d219ab474c6bcdd02f88d09
.pick_status.json: Update to 7a1779edc7fb82c891e584074b95d1a4801c1782
.pick_status.json: Mark 3c673919c348b0611595b32fcc8a3d376868c830 as denominated
.pick_status.json: Update to cd5c9870ea1d7e73d05f125b229f34e5749c8345
docs: add release notes for 24.0.6
VERSION: bump for 24.0.6
Eric R. Smith (3):
panfrost: fix a GPU/CPU synchronization problem
panfrost: mark separate_stencil as valid when surface is valid
panfrost: fix an …
> [le12] mesa: update to 24.0.6

- packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
> [le12] pvr.hts: update 21.2.2-Omega to 21.2.3-Omega

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
- inputstream.adaptive: update 21.4.5-Omega to 21.4.6-Omega
- peripheral.joystick: update 21.1.14-Omega to 21.1.15-Omega
- pvr.nextpvr: update 21.0.3-Omega to 21.1.0-Omega
> [le13] kodi-binary-addons: update to latest versions

- packages/audio/wireplumber/package.mk
includes the migration of the lua config to json as:
- https://www.collabora.com/news-and-blog/blog/2022/10/27/from-lua-to-json-refactoring-wireplumber-configuration-system/
- https://github.com/PipeWire/wireplumber/blob/master/docs/rst/daemon/configuration/migration.rst
+ https://github.com/PipeWire/wireplumber/blob/master/docs/rst/daemon/configuration/features.rst
this version checks the following directories for configurations.
```
strace /usr/bin/wireplumber  2>&1 | grep conf | grep wireplumber
newfstatat(AT_FDCWD, "/storage/.config/wireplumber/wireplumber.conf", 0x7ffc0b543c10, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/wireplumber/wireplumber.conf", 0x7ffc0b543c10, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, …
```
> wireplumber: update to 0.5.2

- projects/Rockchip/devices/RK3328/README.md
- projects/Rockchip/devices/RK3399/README.md
Fixed build commands in the README.md file to comply with the move to 64-bit architecture.
Cheers
Michele
> Rockchip: rk3328 and rk339 builds are 64bit, fix build instructions in README.md

- packages/devel/ncurses/package.mk
when building htop with ncurses it was identified that KEY_RESIZE was not available due to NCURSES_SIGWINCH not being set. Add the option to ncurses to allow correct build of htop.
ref:
- https://github.com/htop-dev/htop/issues/1474
- This is since the ncurses-6.5 6fe28ff9b9554450764ed7aa21fd553a39379344
> ncurses: compile with --enable-sigwinch

- packages/mediacenter/kodi-binary-addons/game.libretro.a5200/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
This PR updates the two Atari emulators for the recent buttonmap changes that make controllers act closer to the original hardware.
For more info, see the tracking issue: https://github.com/kodi-game/controller-topology-project/issues/303
Includes the following changes:
* atari800 - https://github.com/kodi-game/game.libretro.atari800/pull/7
* a5200 - https://github.com/kodi-game/game.libretro.a5200/pull/1
I verified that the latest versions were on the Kodi mirrors:
> Update Atari emulators for authetic buttonmaps

- packages/addons/addon-depends/libusbmuxd/package.mk
- packages/addons/service/usbmuxd/package.mk
NEWS file is not present yet.
```
sed: can't read /data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/usbmuxd-360619c5f721f93f0b9d8af1a2df0b926fbcf281/NEWS: No such file or directory
sed: can't read /data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/usbmuxd-360619c5f721f93f0b9d8af1a2df0b926fbcf281/NEWS: No such file or directory
sed: can't read /data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/usbmuxd-360619c5f721f93f0b9d8af1a2df0b926fbcf281/NEWS: No such file or directory
UNPACK      usbmuxd
sed: can't read /data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/usbmuxd-360619c5f721f93f0b9d8af1a2df0b926fbcf281/NEWS: No such file or directory
UNPACK      libimobiledevice-glue
FIXCONFIG …
```
> usbmuxd: remove sed errors

- projects/Rockchip/patches/u-boot/0001-rockchip-rk3328-BACKPORT-Set-efuse-auto-mode-and-timing-control.patch
- projects/Rockchip/patches/u-boot/0004-rockchip-rk3328-Set-VOP-QoS-to-high-priority.patch
Backport commit https://github.com/u-boot/u-boot/commit/5708e8eeae53ad8ce605afdf61e5a83162dc5131 that enables efuse and fixes a bug related to video resolutions <=720p (as discussed here https://github.com/LibreELEC/LibreELEC.tv/pull/8868)
> [le12] u-boot (RK3328): BACKPORT: Set efuse auto mode and timing control

- projects/Allwinner/patches/linux/0041-OrangePi-3-LTS-support.patch
Ethernet timings are off, adjust them to match BSP kernel version. Tested by forum user.
> Allwinner: linux: Fix OrangePi 3 LTS ethernet

- packages/graphics/mesa/package.mk
Boris Brezillon (3):
panfrost: do not write outside num_wg_sysval
panfrost: Add the BO containing fragment program descriptor to the batch
pan/kmod: Make default allocator thread-safe
Constantine Shablia (2):
pan/bi: fix 1D array tex coord lowering
panfrost: report correct MAX_VARYINGS
Daniel Schürmann (1):
aco/ra: fix kill flags after renaming fixed Operands
David Rosca (5):
radeonsi/vcn: Allocate session buffer in VRAM
radeonsi/vcn: Fix 10bit HEVC VPS general_profile_compatibility_flags
radeonsi/vcn: Only enable VBAQ with rate control mode
frontends/va: Fix AV1 slice_data_offset with multiple slice data buffers
Revert "radeonsi/vcn: AV1 skip the redundant bs resize"
Eric Engestrom (8):
docs: add sha256sum for 24.0.6
.pick_status.json: Update to 86281ef15fca378ef48bcb072a762168e537820d …
> mesa: update to 24.0.7

- packages/graphics/mesa/package.mk
> [le12] mesa: update to 24.0.7

- packages/addons/service/boblightd/package.mk
script.xbmc.boblight require libboblight.so in lib path to be found from Python.
See https://forum.libreelec.tv/thread/28505-boblight-not-working-on-12-0-anymore/?postID=191714#post191714
Only build tested because using boblight myself
> boblight: libboblight.so has to be in lib not lib.private

- packages/network/wireless-regdb/package.mk
> [le12] wireless-regdb: update to 2024.05.08

- packages/addons/addon-depends/argtable2/patches/argtable2-01_fix_gcc-14_build.patch
- packages/addons/addon-depends/dvb-tools-depends/t2scan/patches/t2scan-15-fix-building-with-gcc-14.1.0.patch
- packages/addons/addon-depends/multimedia-tools-depends/opencaster/patches/opencaster-04_fix-gcc-14-build.patch
- packages/addons/addon-depends/multimedia-tools-depends/tsdecrypt/patches/tsdecrypt-01_fix_gcc-14_build.patch
- packages/addons/addon-depends/network-tools-depends/ncftp/package.mk
- packages/addons/addon-depends/system-tools-depends/hid_mapper/patches/hid_mapper-02_include-sys-time.patch
- packages/addons/addon-depends/system-tools-depends/screen/patches/screen-01_fix_gcc-14_build.patch
- packages/addons/service/mariadb/patches/mariadb-0002--fix-gcc14-build.patch
- packages/audio/libcdio/package.mk
- packages/compress/zip/patches/fix-compile-with-gcc14.patch
- packages/devel/ncurses/package.mk
- packages/devel/rapidjson/patches/rapidjson-0002-Removed-non-compiling-assignment-operator.-Fixed-718.patch
- packages/devel/rapidjson/patches/rapidjson-0003-Explicitly-disable-copy-assignment-operator.patch
- packages/emulation/libretro-atari800/package.mk
- packages/emulation/libretro-bk/patches/libretro-bk-0001-recast-assignment.patch
- packages/emulation/libretro-bluemsx/package.mk
- packages/emulation/libretro-mame2000/package.mk
- packages/emulation/libretro-mame2003_plus/package.mk
- packages/emulation/libretro-prboom/package.mk
- packages/emulation/libretro-snes9x/package.mk
- packages/emulation/libretro-uae/package.mk
- packages/lang/gcc/package.mk
- packages/lang/gcc/patches/gcc-0001-Revert-Arm-Block-predication-on-atomics-PR111235.patch
- packages/mediacenter/kodi-binary-addons/audiodecoder.usf/patches/audiodecoder.usf-51-fix-gcc-14-build.patch
- packages/mediacenter/kodi-binary-addons/pvr.stalker/patches/pvr.stalker-223-fix-gcc-14-build.patch
- packages/mediacenter/kodi/patches/kodi-999.30-fix-gcc-14-compile.patch
- packages/multimedia/media-driver/package.mk
- packages/network/bluez/patches/bluez-21-hciattach-add-QCA9377-Tuffello-support.patch
- packages/sysutils/lirc/package.mk
Fixes:
- ~~game.libretro.mame2003_plus~~
- ~~https://github.com/libretro/mame2003-plus-libretro/issues/1721~~
- ~~game.libretro.atari800~~
- ~~https://github.com/libretro/libretro-atari800/issues/94~~
- ~~Upstream patch (to be merged) included https://github.com/libretro/libretro-atari800/pull/92~~
- ~~game.libretro.bluemsx~~
- ~~https://github.com/libretro/blueMSX-libretro/issues/169~~
- ~~https://github.com/libretro/blueMSX-libretro/pull/170~~
- ~~https://github.com/libretro/blueMSX-libretro/pull/167~~
- game.libretro.bk
- https://github.com/xttx/bk-emulator/issues/1
- https://github.com/libretro/bk-emulator/pull/24
- Workaround applied
- #libretro-bk: fix gcc-14 build
- ~~game.libretro.uae~~
- ~~https://github.com/libretro/libretro-uae/issues/656~~
- ~~Upstream patch included …
> gcc: update to 14.1

- packages/tools/bcm2835-utils/patches/bcm2835-utils-86.patch
- packages/tools/bcm2835-utils/patches/bcm2835-utils-88.patch
- packages/x11/xserver/xorg-server/patches/xorg-server-1560-fix-cast-for-gcc14-1.patch
- bcm2835-utils: fix gcc-14 build
- https://github.com/raspberrypi/utils/pull/86
- https://github.com/raspberrypi/utils/pull/88
- xorg-server: fix gcc-14 build
> Minor compat fixes for gcc-14.1

- packages/addons/addon-depends/chrome-depends/unclutter/patches/unclutter-0001-fix-gcc-14-1-build.patch
- packages/addons/addon-depends/tslib/patches/tslib-40-fix-gcc-14-1.patch
- packages/addons/service/lcdd/patches/lcdd-0.5.6-dm140_henlar_v0.2.patch
- packages/emulation/libretro-picodrive/patches/picodrive-02-fix-build-gcc-14-1.patch
- packages/multimedia/aom/package.mk
- lcdd: fix gcc-14 build
- fixes local dm140 patch
- aom: workaround gcc-14 error on 32-bit targets
- https://bugs.chromium.org/p/aomedia/issues/detail?id=3576
- unclutter: fix gcc-14 build
- fixes unmaintained upstream
- libretro-picodrive: fix gcc-14 build on arm32
- https://github.com/libretro/picodrive/issues/227
- https://github.com/LibreELEC/LibreELEC.tv/issues/8917
- tslib: fix gcc-14 build
- https://github.com/LibreELEC/LibreELEC.tv/issues/8916
> Addon fixes for gcc-14.1

- packages/graphics/mesa/package.mk
The bugfix release 24.0.8 is now available.
The next bugfix release is due in two weeks, on June 5th.
Cheers,
Eric
---
Antoine Coutant (1):
drisw: fix build without dri3
Bas Nieuwenhuizen (1):
radv: Use zerovram for Enshrouded.
David Heidelberg (2):
freedreno/ci: move the disabled jobs from include to the main file
winsys/i915: depends on intel_wa.h
David Rosca (6):
frontends/va: Only increment slice offset after first slice parameters
radeonsi: Update buffer for other planes in si_alloc_resource
frontends/va: Store slice types for H264 decode
radeonsi/vcn: Ensure DPB has as many buffers as references
radeonsi/vcn: Allow duplicate buffers in DPB
radeonsi/vcn: Ensure at least one …
> mesa: update to 24.0.8

- packages/x11/driver/xf86-video-nvidia-legacy/patches/xf86-video-nvidia-legacy-100.15-kernel-6.8.patch
- packages/x11/driver/xf86-video-nvidia-legacy/patches/xf86-video-nvidia-legacy-100.16-gcc-14.patch
source:
- https://aur.archlinux.org/packages/nvidia-340xx
- Bring forward patch from #8890 to allow gcc-14.1 compile
> xf86-video-nvidia-legacy: patches for linux-6.8 and gcc-14.1

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
> [le12] linux (RPi): update to 6.6.31

- projects/Amlogic/config/kernel-firmware.dat
Pick the rtl8176bu firmware for future AMLGX LE12 images. Fixes #8853. I'll submit the same change to master along with a kernel bump in the near future.
> amlogic: include rtl8761bu firmware

- packages/linux/patches/raspberrypi/linux-999.99-reorder-channel-allocation.patch
This resolves an issue flagged in the forums where alsa incorrectly matches speaker layout because the list of supported layouts is not ordered correctly. The patch has been included with Amlogic images since 2019 so I'm reasonably confident it doesn't cause problems, but RPi has a much larger user audience so I'd like to prove the theory by including it in LE12 and LE13 nightlies. If no issues are seen I will send the patch upstream on @Kwiboo behalf. I have been nagging him to send it himself for several years already, but, well, it never seems to reach the top of his to-do list :)
> linux: raspberrypi: add reorder channel allocation patch

- packages/addons/addon-depends/system-tools-depends/tree/package.mk
- packages/addons/tools/system-tools/package.mk
This adds the `tree` binary to system-tools.
> system-tools: add tree to add-on

- packages/devel/heimdal/package.mk
On distros, which already use gcc 14, e.g. Arch, heimdal fails to build due to a misconfiguration. Heimdal autotools scripts heavily depend on implicit function declarations. This approach was elevated to an error with gcc14. Explicitly downgrade it to a warning until heimdal configuration is not fixed.
> heimdal: fix configuration with gcc 14

- packages/multimedia/media-driver/package.mk
```
Generic.x86_64-devel-20240529125629-b849cfc
Linux nuc12 6.10.0-rc1 #1 SMP Tue May 28 13:24:17 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0 (21.0.0) Git:21.0-Omega). Platform: Linux x86 64-bit
Kodi compiled 2024-05-29 by GCC 14.1.0 for Linux x86 64-bit version 6.10.0 (395776)
Running on LibreELEC (heitbaum): devel-20240529125629-b849cfc 13.0, kernel: Linux x86 64-bit version 6.10.0-rc1
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0092.2024.0202.1711 02/02/2024
[    0.000000] DMI: Memory slots populated: 1/2
CApplication::CreateGUI - using the gbm …
```
> media-driver: update to 24.2.4

- packages/devel/ccache/package.mk
- packages/devel/libfmt/package.mk
- packages/devel/xxHash/package.mk
- ccache: update to 4.10
- Release notes:
- https://ccache.dev/releasenotes.html#_ccache_4_10
- libfmt: add host build
- xxHash: initial package
> ccache: update to 4.10

- packages/security/openssl/cert/cacert.pem
This commit updates cacert.pem certificate bundle with mk-ca-bundle.pl script using the content of [certdata][1] associated with mozilla/gecko-dev@4d4015d3c2de8c8a64590cf87e1f2e76546da9a8,
[1]: https://github.com/mozilla/gecko-dev/blob/4d4015d3c2de8c8a64590cf87e1f2e76546da9a8/security/nss/lib/ckfw/builtins/certdata.txt?raw=true
> cacert.pem: update to 2024-05-30

- packages/security/openssl/cert/cacert.pem
This commit updates cacert.pem certificate bundle with mk-ca-bundle.pl script using the content of [certdata][1] associated with mozilla/gecko-dev@4d4015d3c2de8c8a64590cf87e1f2e76546da9a8,
[1]: https://github.com/mozilla/gecko-dev/blob/4d4015d3c2de8c8a64590cf87e1f2e76546da9a8/security/nss/lib/ckfw/builtins/certdata.txt?raw=true
> [le12] cacert.pem: update to 2024-05-30

- packages/web/libmicrohttpd/package.mk
libmicrohttpd: swap to shared library
- confirmed that this works with both Omega and P
- slight reduction of file size
- https://github.com/xbmc/xbmc/pull/25228#issuecomment-2137087948
the kodi.bin + the .so is actually smaller than that of the kodi.bin compiled against .a
```
232680 May 29 09:44 build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/libmicrohttpd-1.0.1/usr/lib/libmicrohttpd.so.12.62.1
359688 May 25 09:19 build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/libmicrohttpd-1.0.1/usr/lib/libmicrohttpd.a
26878992 May 29 10:24 build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/kodi-42120bb9047912b9379dadffdbdef9968062cf70/usr/lib/kodi/kodi.bin
26635528 May 29 10:02 build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/kodi-42120bb9047912b9379dadffdbdef9968062cf70/usr/lib/ko …
```
> libmicrohttpd: swap to shared library

- packages/devel/xxHash/package.mk
ref:
https://github.com/LibreELEC/LibreELEC.tv/pull/8945#discussion_r1623416529 
Thanks for spotting my error and fixing @mglae - yes ubuntu had the .so in `/lib/x86_64-linux-gnu/libxxhash.so.0` and I didnt notice as it picked up the headers fine.
> xxHash: fix toolchain target directory

- packages/network/iwd/package.mk
ver 2.18:
+	Fix issue with handling BSS with invalid HE capabilities.
+	Fix issue with neighbor reports with invalid country codes.
+	Fix issue with EAP-TTLS Start packets with L flag set.
+	Add support for enabling SAE for AP mode operation.
> iwd: update to 2.18

- packages/network/iwd/package.mk
- back port of #8961 
ver 2.18:
+	Fix issue with handling BSS with invalid HE capabilities.
+	Fix issue with neighbor reports with invalid country codes.
+	Fix issue with EAP-TTLS Start packets with L flag set.
+	Add support for enabling SAE for AP mode operation.
> [le12] iwd: update to 2.18

- packages/security/openssl/package.mk
> [le12] openssl: update to 3.2.2

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/service/docker/package.mk
- packages/addons/service/mariadb/package.mk
- docker: update to 26.1.4 and addon (2)
- containerd: update to 1.7.18
- cli: update to 26.1.4
- moby: update to 26.1.4
- go: update to 1.22.4
- mariadb: update to 11.4.2 and addon (2)
> Addon updates 

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/service/docker/changelog.txt
- packages/addons/service/docker/package.mk
- packages/addons/service/mariadb/changelog.txt
- packages/addons/service/mariadb/package.mk
- backport of #8966
- docker: update to 26.1.4 and addon (2)
- containerd: update to 1.7.18
- cli: update to 26.1.4
- moby: update to 26.1.4
- go: update to 1.22.4
- mariadb: update to 11.4.2 and addon (2)
> [le12] addon updates

- packages/graphics/mesa/package.mk
The bugfix release 24.1.1 is now available.
The next bugfix release is due in two weeks, on June 19th.
Cheers,
Eric
---
Amit Pundir (1):
android: Fix zink build failure
Revert "zink: use a slab allocator for zink_kopper_present_info"
David Heidelberg (1):
ci/nouveau: move disabled jobs back from include into main gitlab-ci.yml
frontends/va: Fix leak when destroying VAEncCodedBufferType
Eric Engestrom (10):
docs: add sha256sum for 24.1.0
.pick_status.json: Mark 410ca6a3e99c5c1c9c91f0f79bf43a35103cbd98 as denominated
freedreno/a6xx: fix kernel -> compute handling
panfrost: mark tests as fixed
panfrost/ci: add missing genxml trigger path
.pick_status.json: …
> mesa: update to 24.1.1

- packages/graphics/mesa/package.mk
**This is the last update for mesa as used by LE12**
[ANNOUNCE] mesa 24.0.9
The bugfix release 24.0.9 is now available.
This is the last release of the 24.0 series. Users are encouraged to
switch to the 24.1 series to continue receiving bugfixes.
Cheers,
Eric
---
Alexandre Marquet (1):
pan/mdg: quirk to disable auto32
David Heidelberg (2):
subprojects: uprev perfetto to v45.0
ci/nouveau: move disabled jobs back from include into main gitlab-ci.yml
frontends/va: Fix leak when destroying VAEncCodedBufferType
Eric Engestrom (13):
docs: add sha256sum for 24.0.8
.pick_status.json: Update to 18c736bcfc55b8fa309ede02332b9c7a2ca22e78
.pick_status.json: Mark 01bac643f6c088f7537edf18f2d4094881c1ecda as denominated
.pick_status.json: Update to …
> [le12] mesa: update to 24.0.9

- packages/databases/mariadb-connector-c/package.mk
ref:
- https://forum.libreelec.tv/thread/28644-mariadb-connector-update-forces-ssl/
> mariadb-connector-c: set DEFAULT_SSL_VERIFY_SERVER_CERT to off

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.19.7.html
> samba: update to 4.19.7

- packages/linux/patches/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
This backports a kernel patch from Linux 6.10 to LE12 to resolve an issue with Anysee USB DVB sticks reported in the forum: https://forum.libreelec.tv/thread/28025-tv-adapter-drivers-missing-from-11-0-4/?postID=192938#post192938
> linux: backport anysee usb patch from Linux 6.10

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rust: update to 1.79.0
- https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html 
- cargo-snapshot: update to 1.79.0
- rust-std-snapshot: update to 1.79.0
- rustc-snapshot: update to 1.79.0
> rust: update to 1.79.0

- packages/sysutils/eventlircd/package.mk
This resolves forum reports of non working IR since the most revent systemd bump.
> eventlircd: bump to fix assert issue with systemd udev

- packages/addons/addon-depends/ffmpegx/package.mk
- packages/addons/tools/ffmpeg-tools/package.mk
- packages/multimedia/ffmpeg/package.mk
As reported in the [forum](https://forum.libreelec.tv/thread/28654-ffmpeg-cannot-stream-and-decode-with-mpeg-dash/) MPEG-DASH demuxer is missing in LE ffmpeg.
DASH demuxer is only build with libxml2 enabled. Do this on both ffmpeg and ffmpegx.
Copying libxcb* libs is not required when building ffmpeg-tools for
Generic-legacy (X11), they are part of the image.
> ffmpeg, ffmpegx: allow dash demuxer by enabling libxml2

- packages/devel/heimdal/package.mk
Build system CFLAGS should only be expanded, not replaced. 
See discussion in #8935
> heimdal: fix CFLAGS override after ebff2c7ca0

- packages/audio/libcdio/package.mk
- packages/audio/libcdio/patches/0002-remove-lfs-shms.patch
Upstream fix that removes the need for the 32 bit workaround
fixes:
- libcdio: gcc-14 error on 32-bit targets
- https://savannah.gnu.org/bugs/?65751
> libcdio: add patch to remove lfs shms

- packages/devel/shared-mime-info/patches/shared-mime-info-219-fix-build-with-libxml2-2-12-0.patch
With the updated libxml2 shared-mime-info does not compile without this upstream patch.
- https://gitlab.freedesktop.org/xdg/shared-mime-info/-/commit/c918fe77e255150938e83a6aec259f153d303573
- https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/219
> shared-mime-info: Fix build with libxml2-2.12.0

- packages/devel/autoconf/package.mk
- packages/devel/heimdal/patches/1229.patch
[autoconf: update to 2.72](https://github.com/LibreELEC/LibreELEC.tv/commit/8f716d55bb8358db685dd56e198e6a33c05585fa)
- [heimdal: Fix build with autoconf-2.72](https://github.com/LibreELEC/LibreELEC.tv/commit/9613191541e5306f2a189b967a6f6b1333f59332)
- https://github.com/heimdal/heimdal/issues/1201
- https://github.com/heimdal/heimdal/pull/1229
> autoconf: update to 2.72

- packages/network/libdnet/package.mk
libdnet 1.14 fails to compile with autoconf-2.72 . Libdnet has been in the backlog for a long time, as it had required libcheck (it no longer requires libcheck) - so upgrading. Only used by open-vm-tools.
- #8999
release notes:
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.16.1
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.16.2
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.16.3
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.16.4
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.17.0
- https://github.com/ofalk/libdnet/releases/tag/libdnet-1.18.0
log:
- https://github.com/ofalk/libdnet/compare/libdnet-1.16.1...libdnet-1.18.0
> libdnet: update to 1.18.0

- packages/graphics/mesa/package.mk
```
Generic.x86_64-devel-20240620102701-37a7a5a
Linux nuc12 6.10.0-rc4 #1 SMP Thu Jun 20 06:33:16 UTC 2024 x86_64 GNU/Linux
Starting Kodi (21.0 (21.0.0) Git:21.0-Omega). Platform: Linux x86 64-bit
Kodi compiled 2024-06-17 by GCC 14.1.0 for Linux x86 64-bit version 6.10.0 (395776)
Running on LibreELEC (heitbaum): devel-20240620102701-37a7a5a 13.0, kernel: Linux x86 64-bit version 6.10.0-rc4
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0092.2024.0202.1711 02/02/2024
[    0.000000] DMI: Memory slots populated: 1/2
CApplication::CreateGUI - using the gbm …
```
> mesa: update to 24.1.2

- packages/linux/patches/raspberrypi/linux-999.99-reorder-channel-allocation.patch
> [LE12] linux: raspberrypi: add reorder channel allocation patch

- packages/linux/patches/raspberrypi/linux-999.99-fix-ntfs3-corruption.patch
Resolves an issue with the NTFS driver and 16K pages on RPi4/5 kernels as reported in the forum: https://forum.libreelec.tv/thread/28620-libreelec-12-0-rpi5-and-ntfs-hdd-problem. Patch is merged in the RPi kernel so can be dropped at some point soon: https://github.com/raspberrypi/linux/pull/6218 and has also been submitted to the upstream kernel.
> linux: rpi: add ntfs3 corruption fix patch

- packages/mediacenter/kodi/package.mk
Build with my 240621 release and run tested on my Alder Lake N100, RPi4, RPi5
Picked up a TrueHD and PVR fix
> [le12] kodi: update to 01bd800

- projects/Amlogic/patches/u-boot/u-boot-0001-LOCAL-configs-meson64-prevent-stdout-stderr-on-video.patch
- projects/Amlogic/patches/u-boot/u-boot-0002-LOCAL-board-amlogic-odroid-n2-remove-amlogic-prefix-.patch
This resolves an issue with FDTDIR boot on Odroid N2/N2+ devices reported in the forums.
> u-boot: update Amlogic patches to fix Odroid N2 boot

- packages/addons/browser/chrome/package.mk
- packages/addons/browser/chrome/source/bin/deb_extract_data
This change's the chrome addon's deb_extract_data from unconditionally trying to extract a file to confirming that file exists first, and adds an error if it fails to open it.
This hopefully makes the error messages from https://github.com/LibreELEC/LibreELEC.tv/pull/8783#issuecomment-2029819224 less ??? to a user.
This is untested, but pylint didn't overly complain; someone on generic needs to confirm it functions.
> chrome: conditionally extract deb file

- packages/network/openssh/package.mk
Backport of OpenSSH to LE12 - This release contains fixes for two security problems, one critical
and one minor.
Change log:
- https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog
Release notes:
- https://www.openssh.com/releasenotes.html#9.8p1
Release notes:
- https://www.openssh.com/txt/release-9.8p1
> [le12] openssh: update to 9.8p1

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.289
- vulkan-loader: update to 1.3.289
- vulkan-tools: update to 1.3.289
> Vulkan update to 1.3.289

- packages/graphics/mesa/package.mk
The bugfix release 24.1.3 is now available.
The next bugfix release is due in two weeks, on July 17th.
Cheers,
Eric
---
Alyssa Rosenzweig (1):
nir: fix miscompiles with rules with INT32_MIN
Bas Nieuwenhuizen (1):
util/disk_cache: Fix cache marker refresh.
Connor Abbott (1):
ir3: Make sure constlen includes stc/ldc.k/ldg.k instructions
Daniel Schürmann (1):
aco/spill: Unconditionally add 2 SGPRs to live-in demand
Dylan Baker (2):
clc: remove check for null pointer that cannot be true in llvm_mod_to_spirv
anv/grl: add some validation that we're not going to overflow
Eric Engestrom (16):
docs: add sha256sum for 24.1.2
ci/shader-db: drop extra nesting section …
> mesa: update to 24.1.3

- packages/network/wireless-regdb/package.mk
> wireless-regdb: update to 2024.07.04

- packages/devel/pcre2/package.mk
- packages/graphics/exiv2/package.mk
Package dependencies and changes to support Kodi “Piers”
- meson build of exiv2 is not compatible at this time https://github.com/Exiv2/exiv2/issues/3015
- pcre2: build 8BIT target
- exiv2: initial package
> Package to support Kodi “Piers”

- packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
This PR updates game.libretro with an input fix and a video buffer overflow fix.
Contains the following two PRs:
* https://github.com/kodi-game/game.libretro/pull/124 - It was causing input to fail for NDS cores
* https://github.com/kodi-game/game.libretro/pull/126 - affects cores that request a second software buffer of different size within the same run, such as PCSX-ReARMed
> game.libretro: Update for buffer overflow fix

- packages/emulation/libretro-mrboom/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.mrboom/package.mk
This PR updates the Mr.Boom core from v5.3 to v5.5.
This is not part of a normal update cycle, but a forum user noticed the Mr.Boom crashed when opening on FlatPak ([report](https://forum.kodi.tv/showthread.php?tid=173361&pid=3192377#pid3192377)).
As we debug the issue, I'm getting Mr.Boom on master everywhere to help debug the issue.
> Update Mr.Boom game add-on

- packages/addons/addon-depends/chrome-depends/harfbuzz-icu/patches/harfbuzz-icu-4734-fix-build-with-icu-75.patch
upstream fix included in harrbuzz-9.0.0
- harfbuzz/harfbuzz#4734
- harfbuzz/harfbuzz#4671
- meson: set -std=c++17 when building with icu >= 75
- Required for chrome in LE12 (Upstream harfbuzz-9.0.0 used in LE13)
> [le12] harfbuzz-icu: fix build with icu 75

- tools/docker/jammy/Dockerfile
- tools/docker/noble/Dockerfile
Untested. This should resolve #9056. If it doesn't, changes in scripts/checkdeps for aarch64 hosts need to be revisited.
@heitbaum
> dockerfiles: update packages for aarch64 to amd64 crosscompiles

- packages/python/devel/meson/package.mk
release notes:
- https://github.com/mesonbuild/meson/blob/master/docs/markdown/Release-notes-for-1.5.0.md
> meson: update to 1.5.0

- config/options
- config/show_config
- packages/addons/addon-depends/argtable2/package.mk
- packages/devel/libdaemon/package.mk
By default autotools configure scripts and libtool use bash as the config shell which is quite slow.
Using dash instead results in about 4-10% faster builds.
A clean RPi5 image builds in a Debian Bullseye chroot on my Ryzen 7950X box takes about 22 minutes instead of 23 and a RPi5 image rebuild from ccache takes about 8.5 instead of 9.5 minutes.
dash is the default system shell on Debian and Ubuntu systems so our CI builds should benefit from the improvement. On other distros dash is usually available as an optional package.
This PR doesn't suffer from the issues of the previous approach to use dash some 6 years ago (see #2785)  which we had to revert (see #2808)
By using /bin/dash from the build host (if available) instead of a self-built one fron our toolchain we avoid the long-path …
> Use /bin/dash as CONFIG_SHELL if it's installed on the build host

- projects/Rockchip/bootloader/install
For Rockchip builds
Ref:
- https://github.com/LibreELEC/LibreELEC.tv/pull/9084
- https://github.com/LibreELEC/LibreELEC.tv/issues/9056
- https://github.com/LibreELEC/amlogic-boot-fip/pull/24
tested as:
- https://github.com/heitbaum/actions/actions/runs/9919910673 RK3288
- https://github.com/heitbaum/actions/actions/runs/9923836857 RK3399
- https://github.com/heitbaum/actions/actions/runs/9923853624 RK3328
> bootloader/install: Rockchip: use qemu when not building on x86_64

- packages/addons/addon-depends/ffmpegx-depends/x265/package.mk
use ${CMAKE} not cmake to build so as to use CMAKE_TOOLCHAIN_FILE and target the correct TARGET architecture.
> x265: fix cross compiled builds

- packages/graphics/mesa/package.mk
The bugfix release 24.1.4 is now available.
The next bugfix release is due in two weeks, on July 31st.
Cheers,
Eric
PS: for those waiting for 24.2.0-rc1, it will be a bit late, although
hopefully less than 48h from now.
---
Aleksi Sapon (1):
lavapipe: build "Windows" check should use the host machine, not the `platforms` option.
Connor Abbott (3):
tu: Make cs writeable for GMEM loads when FDM is enabled
tu: Fix fdm_apply_load_coords patchpoint size
ir3: Fix stg/ldg immediate offset on a7xx
Dave Airlie (2):
anv/video: use correct offset for MPR row store scratch buffer.
radv/video: advertise mutable/extended for dst video images.
Reapply "radeonsi/vcn: AV1 skip the …
> mesa: update to 24.1.4

- packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
This adds support for the OK key on the "UR02" BlueTooth remote, as documented in the forum: https://forum.libreelec.tv/thread/28787-rpi5-trying-to-get-bluetooth-remote-ok-button-to-send-an-enter-code/
> systemd: add UR02 BT remote device to 70-local-keyboard.hwdb

- packages/multimedia/media-driver/package.mk
- packages/multimedia/media-driver/patches/media-driver-999.02-Refactor-for-build-issue.patch
include upstream fix
- https://github.com/intel/media-driver/commit/47bae3c809c9f5b11793b76b5edfd7704adb4080
- https://github.com/intel/media-driver/issues/1834
change log:
- https://github.com/intel/media-driver/compare/intel-media-24.2.5...intel-media-24.3.0
```
Generic.x86_64-devel-20240722094119-5a65c42
Linux nuc12 6.10.0 #1 SMP Fri Jul 19 10:48:33 UTC 2024 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:9052d5b00e48855654a8bf8f5d38dc789f2a0e11). Platform: Linux x86 64-bit
Kodi compiled 2024-07-19 by GCC 14.1.0 for Linux x86 64-bit version 6.10.0 (395776)
Running on LibreELEC (heitbaum): devel-20240722094119-5a65c42 13.0, kernel: Linux x86 64-bit version 6.10.0
Host CPU: 12th Gen Intel(R) Core(TM) …
```
> media-driver: update to 24.3.0

- packages/mediacenter/kodi/package.mk
Pickup fixes for Python, Bookmarks, PVR
Build for all official supported platforms and run tested on RPi4, RPi5, Generis with my community release 240710
> [le12] kodi: update to 7e5bb32

- packages/mediacenter/kodi/package.mk
- Jul 26, 2024
log:
- https://github.com/xbmc/xbmc/compare/060417ccfa5b21939669d404b9a223c3004ba132...ebf95c50e9ca5060e4d256b41e81c0f94757d122
> kodi: update to githash ebf95c5

- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
This should fix the RPi TV HAT not working on RPi5.
> linux (RPi): update to 6.6.42

- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
> [le12] linux (RPi): update to 6.6.42

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/multimedia/bento4/package.mk
- includes [bento4: update to 1.6.0-641-3-Omega](https://github.com/LibreELEC/LibreELEC.tv/pull/9149/commits/6aa61c24de6140d04b9fd6d85652b70b683942d1)
> inputstream.adaptive: update 22.1.0-Piers to 22.1.1-Piers

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/multimedia/bento4/package.mk
- includes [bento4: update to 1.6.0-641-3-Omega](https://github.com/LibreELEC/LibreELEC.tv/pull/9149/commits/6aa61c24de6140d04b9fd6d85652b70b683942d1)
> inputstream.adaptive: update 21.5.0-Omega to 21.5.1-Omega

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/patches/001-backport-build-fix.patch
see https://github.com/xbmc/inputstream.adaptive/pull/1625
build-tested for RPi5
> inputstream.adaptive: backport upstream fix for build error

- packages/mediacenter/kodi/package.mk
- Aug 7, 2024
log:
- https://github.com/xbmc/xbmc/compare/f6265c87f09132c51943ec3e259b0c98a530bae0...f02afef0f39f8a3770d0e9fd5483e8a53a1814d7
> kodi: update to githash f02afef

- packages/network/samba/package.mk
- packages/network/samba/patches/samba-200-4.11-fix-ASN1-bso14164.patch
Release notes:
- https://www.samba.org/samba/history/samba-4.20.3.html
- https://www.samba.org/samba/history/samba-4.20.4.html
> samba: update to 4.20.4

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.292
- vulkan-loader: update to 1.3.292
- vulkan-tools: update to 1.3.292
> Vulkan update to 1.3.292

- packages/graphics/mesa/package.mk
The bugfix release 24.1.5 is now available.
The next bugfix release is due in two weeks, on August 14th.
Cheers,
Eric
---
Alessandro Astone (1):
egl/gbm: Walk device list to initialize DRM platform
gallivm/sample: fix sampling indirect from vertex shaders
Revert "frontends/va: Fix AV1 slice_data_offset with multiple slice data buffers"
Deborah Brouwer (1):
ci/lava: Detect a6xx gpu recovery failures
Dylan Baker (5):
compilers/clc: Add missing break statements.
mesa: fix memory leak when using shader cache
tgsi_to_nir: free disk cache value if the size is wrong
crocus: properly free resources on BO allocation failure
crocus: check for …
> mesa: update to 24.1.5

- packages/x11/lib/pixman/patches/pixman-0001-adjust-arm-assembly-for-binutils-change.patch
Fixes arm 32 bit CI builds
- patch is from upstream
- https://gitlab.freedesktop.org/pixman/pixman/-/commit/865e6ce00bb79a6b925ed4c2c436e1533e4472aa
==
A change in the latest version of binutils broke building pixman for arm.
The binutils change:
https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=226749d5a6ff0d5c607d6428d6c81e1e7e7a994b
Closes: https://gitlab.freedesktop.org/pixman/pixman/-/issues/96
> pixman: Adjust arm assembly for binutils-2.43

- packages/devel/fakeroot/patches/gcc14-build.patch
On Arch, fakeroot build fails due to new GCC14 policy that implicit pointer conversion between incompatible types will not be allowed anymore.
Fix issue by adding explicit pointer cast until upstream is fixed.
Upstream bug reports:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074945
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074365
> fakeroot: Fix GCC14 build

- packages/multimedia/ffmpeg/patches/libreelec/ffmpeg-002-libavcodec-arm-mlpdsp_armv5te-fix-label-format-to-wo.patch
ref:
- https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2024-August/332149.html
included patch
- libavcodec/arm/mlpdsp_armv5te: fix label format to work with binutils 2.43
> ffmpeg: arm: allow 32-bit arm compile with binutils 2.43

- packages/python/devel/Jinja2/package.mk
- packages/python/devel/Jinja2/patches/0001-revert-setuptools-removal.patch
the filename has been changed to lowercase in the 3.1.4 download
revert drop of setuptools:
- https://github.com/pallets/jinja/commit/20477c63575175196bfc8103f223cc9f5642595d
> Jinja2: update to 3.1.4

- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- projects/Rockchip/patches/linux/default/linux-1000-drm-rockchip.patch
- iwlwifi-firmware: update to githash 267545f
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.1
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.2
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.3
6.10.1 - 11 patches
6.10.2 - 29 patches
6.10.3 - 809 patches
fixes 6.10.1
- thermal: core: Allow thermal zones to tell the core to ignore them (iwlwifi)
- ext4: use memtostr_pad() for s_volume_name 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.10.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.10.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.10
- …
> linux: update to 6.10.x

- packages/mediacenter/kodi/patches/kodi-995.20-python-lib-dir.patch
Recent Kodi switch from distutils to sysconfig to find python installation folder breaks cross-compilation (python lib is installed in wrong folder.) Fix it with suggestion from https://github.com/xbmc/xbmc/issues/25275 until issue is not resolved upstream.
This fixes kodi-remote util, which very useful during testing and debugging.
> kodi: Fix python installation dir

- packages/mediacenter/LibreELEC-settings/package.mk
bump LE settings to include timezone/backup changes
> LibreELEC-settings: bump to include timezone/backup changes

- packages/devel/heimdal/package.mk
allow heimdal:host to be built using build hosts with gcc-14 does not adjust :target builds. LE12 builds are only supported using the gcc-13.x
- backport of #8935 and #8994
> [le12] heimdal: fix configuration with gcc 14

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.19.8.html
> [le12] samba: update to 4.19.8

- tools/mkpkg/update_binary-addons
- backport of #9195 
without using the -x option, all binary addons are updated to the latest hash is the branch if there are no tags set.
using the -x option, the binary addons are only updated to a newer tag. when only a hash is present do not update the PKG_VERSION.
existing default behaviour of the script has not changed.
> [le12] update_binary-addons: add -x option to skip no tag updates

- tools/mkpkg/update_binary-addons
without using the -x option, all binary addons are updated to the latest hash is the branch if there are no tags set.
using the -x option, the binary addons are only updated to a newer tag. when only a hash is present do not update the PKG_VERSION.
existing default behaviour of the script has not changed.
> update_binary-addons: add -x option to skip no tag updates

- packages/linux/package.mk
- packages/linux/patches/raspberrypi/linux-010-pr6309-fix-no-signal-after-modeswitch.patch
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
Also include https://github.com/raspberrypi/linux/pull/6309 to fix an occasional "no signal" issue after switching modes with some devices (HDFury VRROOM and chewitt's LG B7V and likely some other devices, too).
Runtime tested on RPi3B+, RPi4 and RPi5
> linux (RPi): update to 6.6.45

- packages/linux/package.mk
- packages/linux/patches/raspberrypi/linux-010-pr6309-fix-no-signal-after-modeswitch.patch
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
Backport of #9198 
Runtime tested on RPi3B+, RPi4 and RPi5
> [le12] linux (RPi): update to 6.6.45

- packages/lang/gcc/patches/gcc-14.2.0-fix-building-libaom-on-arm64.patch
- Fixes #9180 
ref:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115464
- https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=32b21292adb6ad6b5e1d60d923a773e4d0daca7b
- https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=86dacfb06b90371458d58872f461d358a0834305
- https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/heads/releases/gcc-14
> gcc: 14.2 upstream fix for building libaom on arm64

- packages/addons/addon-depends/ffmpegx/patches/ffmpeg-002-libavcodec-arm-mlpdsp_armv5te-fix-label-format-to-wo.patch
- Copy of #9166 (but for ffmpegx)
ref:
- https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2024-August/332149.html
included patch
- libavcodec/arm/mlpdsp_armv5te: fix label format to work with binutils 2.43
- copy of ffmpeg patch
- commit cf501cb3e3ebef62712dec00109df50532c6f29e (origin/ffmpeg)
> ffmpegx: arm: allow 32-bit arm compile with binutils 2.43

- packages/devel/pkg-config/package.mk
It's not needed since 0.27.1, which was released 12 years ago... This also relaxes dependencies and fixes contention point of build schedule.
> [LE13] pkg-config: remove gettext dependency

- packages/mediacenter/LibreELEC-settings/package.mk
- Required for support of #9218 - https://github.com/LibreELEC/service.libreelec.settings/pull/325
> LibreELEC-settings: use importlib instead of imp Python module

- packages/addons/addon-depends/system-tools-depends/i2c-tools/package.mk
commit 472dda0a4d0f90240f6645e0e8a743f184233937 ("i2c-tools: Don't use distutilscross") accidentally dropped the binaries installation so building the system-tools addon failed as it could not find the i2cdetect etc binaries.
Add the install back (minus python installation)
> i2c-tools: add back binaries installation

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.293
- vulkan-loader: update to 1.3.293
- vulkan-tools: update to 1.3.293
> Vulkan update to 1.3.293

- packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Sync with RPiOS 1.2-9+rpt3 bluez / 1:20230625-2+rpt3 brcm80211 versions
- Add CYW43439 firmware
- Update 43455 firmware for WPA3 offload with wpa_supplicant
> brcmfmac_sdio-firmware-rpi: update to 4c1789e

- tools/mkpkg/update_binary-addons
I am not 100% sure why it happens (bash corner case?) but without that change the script exit with error code 1 even at a successful run.
> update_binary-addons: fix error at exit

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.294
- vulkan-loader: update to 1.3.294
- vulkan-tools: update to 1.3.294
> Vulkan update to 1.3.294

- packages/graphics/mesa/package.mk
The bugfix release 24.2.1 is now available.
The next bugfix release is due in three weeks, on September 18th.
(The extra week is because I'll be on holiday; normal 2-week schedule
will resume for the following releases.)
Cheers,
Eric
---
panvk: Adjust RGB component order for fixed-function blending
Connor Abbott (5):
tu: Fix off-by-one in UBO CP_LOAD_STATE size
ir3, tu: Use a UBO for VS primitive params on a750+
Revert "tu/a750: Disable HW binning when there is GS"
tu: Fix passthrough D24S8 attachments
tu: Treat partially-bound depth/stencil attachments as passthrough
Dave Airlie (3):
radv/video: fix reporting video format props for encode.
llvmpipe: …
> mesa: update to 24.2.1

- projects/RPi/patches/mesa/0002-backport-2712D0-support.patch
This fixes mesa not working on the new RPi5 2GB
> [le12] mesa (RPi): add support for new 2712D0 stepping

- packages/graphics/mesa/package.mk
Shortlog
========
vulkan/video: fix vui encoding
David Heidelberg (1):
panfrost: drop leftover definition after pan_nir_lower_64bit_intrin removal
David Rosca (2):
frontends/va: Fix locking in vlVaDeriveImage
frontends/va: Fix locking in vlVaQueryVideoProcPipelineCaps
Dylan Baker (3):
.pick_status.json: Update to 4aa1259eb4a86a94596dd31d6b80a99ce6d91299
docs: add release notes for 24.2.2
VERSION: bump for 24.2.2
Eric Engestrom (7):
docs: add sha sum for 24.2.1
.pick_status.json: Update to 51e05c284465786bf125d9d36081e9152c80619b
v3dv/ci: fix test timeout for v3dv-rpi5-vk-full:arm64
etnaviv/ci: fix gc2000_piglit test timeout
.pick_status.json: Mark 4888d39f29ae84dd279f2bd4714eb0f6e8ba5d20 as denominated
.pick_status.json: Mark 033818fdd99a543fd1cb17cc8e4be07f831a9003 as …
> mesa: update to 24.2.2

- packages/network/iwd/package.mk
- backport of #9251 
- ver 2.20:
+	Fix issue with PKEX timeout and number of frequencies used.
+	Fix issue with handling logic for handshake failures.
+	Fix issue with handling ConnectedAccessPoint signal.
> [le12] iwd: update to 2.20

- projects/Rockchip/patches/linux/default/linux-0003-pinctrl--rockchip--correct-RK3328-iomux-width-flag-for-GPIO2-B-pins.patch
> linux (Rockchip RK3328): pinctrl fix

- packages/security/openssl/package.mk
Release notes:
- https://openssl-library.org/news/openssl-3.3-notes/
Release notes:
- https://openssl-library.org/news/vulnerabilities/index.html
Jul 5, 2024
The master sources are maintained in our git repository, which is accessible over the network and cloned on GitHub, at https://github.com/openssl/openssl. Bugs and pull patches (issues and pull requests) should be filed on the GitHub repo. Please familiarize yourself with the license.
> openssl: update to 3.3.2

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.295
- vulkan-loader: update to 1.3.295
- vulkan-tools: update to 1.3.295
> Vulkan update to 1.3.295

- packages/mediacenter/kodi/patches/kodi-999.30-PR25679-backport-LFE-mixing.patch
kodi master finally gained the possibility to include the LFE channel in stereo downmix, Omega PR is here https://github.com/xbmc/xbmc/pull/25679
This patch can be dropped when the kodi Omega PR has been merged and kodi is bumped in LE.
> kodi: add backport patch to enable LFE mixing possibility

- packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
> [le12] brcmfmac_sdio-firmware-rpi: update to 4c1789e

- packages/sysutils/tz/package.mk
Log:
- https://github.com/eggert/tz/compare/2024a...2024b
> tz: update to 2024b

- packages/sysutils/tz/package.mk
- backport of #9272 
log:
- https://github.com/eggert/tz/compare/2024a...2024b
> [le12] tz: update to 2024b

- packages/sysutils/open-iscsi/patches/open-iscsi-08-rename-local-strings--ch--to-local_strings--ch-.patch
- packages/sysutils/open-iscsi/patches/open-iscsi-09-Fix-undefined-call-to-writev----include--sys-uio.h.patch
patches are from upstream
[https://github.com/open-iscsi/open-iscsi 69](https://github.com/open-iscsi/open-iscsi/pull/69)
> open-iscsi: fix build with gcc-14

- packages/linux/package.mk
As noticed in the [forum](https://forum.libreelec.tv/thread/28874-x86-64-open-iscsi-support/) the optional iSCSI-Support is broken .
In addition to  #9163 the required kernel config options got lost over the time.
Don't rely on exiting config files but enable/disable the required iSCSI settings on the fly according to the ISCSI_SUPPORT option.
Runtime tested on Generic.
> linux: fix iSCSI support (lost in configs)

- packages/network/iwd/package.mk
- Fix issue with pending scan requests after regdom update.
- Fix issue with handling the rearming of the roaming timeout.
- Fix issue with survey request and externally triggered scans.
- Fix issue with RSSI fallback when setting CQM threshold fails.
- _**Fix issue with FT-over-Air without offchannel support.**_
- Add support for per station Affinities property.
> iwd: update to 2.21

- packages/linux-firmware/kernel-firmware/package.mk
drop now upstreamed change
- https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/rtl_bt/rtl8723bs_config.bin?id=2bb8fb26599302c9cbc69a5aff329a8559c91e48
```
rename rtl8723bs_config-OBDA8723.bin -> rtl_bt/rtl8723bs_config.bin
The setting works for numerous rtl8723 series of devices so let's use
the default naming so it works by default everywhere and link the
device specific names to the generic config.
```
> kernel-firmware: update to 20240909

- packages/network/iwd/package.mk
- backport of #9284 
- Backport of #9289
- Fix issue with pending scan requests after regdom update.
- Fix issue with handling the rearming of the roaming timeout.
- Fix issue with survey request and externally triggered scans.
- Fix issue with RSSI fallback when setting CQM threshold fails.
- Fix issue with FT-over-Air without offchannel support.
- Add support for per station Affinities property.
> [le12] iwd: update to 2.22

- scripts/get_archive
- tools/distro-tool
All ftp:// urls have been migrated to http/https.
This change maintains the capability to retrieve ftp urls but only adds the —passive-ftp argument to wget if it is a ftp: url.
- fixes #9119
> scripts and tools: only use --passive-ftp for ftp: urls

- packages/addons/addon-depends/podman/conmon/package.mk
- packages/addons/addon-depends/podman/libassuan/package.mk
- packages/addons/addon-depends/podman/netavark/package.mk
- packages/addons/addon-depends/podman/netavark/patches/netavark-0001-no-docs.patch
- packages/addons/addon-depends/podman/podman-bin/package.mk
- packages/addons/addon-depends/podman/podman-bin/patches/podman-0002-path-changes.patch
- packages/addons/service/podman/package.mk
- conmon: update to 2.1.12
- libassuan: update to 3.0.1
- netavark: update to 1.12.2 and fix cross-compile build
- podman-bin: update to 5.2.2
- Fixes #9296 
- backport of #9297
> [le12] podman: update to 5.2.2 and addon (1)

- packages/sysutils/v4l-utils/package.mk
While testing `scripts/create_addon` then `make image` it was found that v4l-utils picked up the Qt libraries and wanted to build the qt binaries. This PR disables these binaries from being built. Additional raising an issue to fix Qt to honour not installing in sysroot.
> v4l-utils: do not build with Qt even if Qt is found

- packages/graphics/mesa/package.mk
The bugfix release 24.2.3 is now available.
The next bugfix release is due in two weeks, on October 2nd.
Cheers,
Eric
---
pan/kmod: Don't cap VM bind operations to one
Daniel Stone (1):
ci/alpine: Fix shellcheck errors
Dave Airlie (5):
vl/bitstream: use an int32_t for se encoding.
radv/video: handling encoding both sps and pps in same buffer
radv: Fix radeon_enc_code_ue with values over 2^16
radv/video: fix encode reference slot counting
radv/video/enc: report pps overrides in feedback for h265
David Heidelberg (3):
nir_lower_mem_access_bit_sizes: Assert when 0 components or bits are requested
freedreno/ir3: Use nir_lower_mem_access_bit_sizes instead …
> mesa: update to 24.2.3

- packages/network/connman/package.mk
- packages/network/connman/patches/connman-07-connman_gateway_add-fix-calculation-of-is_vpn6.patch
Set as **merge block** till positive test results of the testing against vpn are confirmed, so as not to have to revert as previously in these 2 PRs.
- #8427 and #8355
ver 1.43:
+	Fix issue with device creation when using LTE.
+	Fix issue with regulatory domain when powering up.
+	Fix issue with resolving ISO3166 code from timezone data.
+	Fix issue with handling DNS proxy zero termination of buffers.
+	Fix issue with handling DHCP packet length in L3 mode.
+	Fix issue with handling DHCP upper length checks.
+	Fix issue with handling IPv6 and URL parsing.
+	Fix issue with handling online check updates.
+	Fix issue with handling proxy method and WISPr.
+	Fix issue with handling default gateway setup.
+	Add support for low-priority default routes.
> connman: update to 1.43

- packages/lang/Python3/package.mk
follow of #9218
fixes
```
configure: WARNING: unrecognized options: --disable-static, --enable-openssl, --enable-readline, --enable-bzip2, --enable-zlib, --enable-xz, --without-cxx-main, --with-libmpdec, --with-system-ffi
``` 
options dropped in:
- https://git.busybox.net/buildroot/commit/package/python3?id=76cd14167f5eb3ffe22e131ddbbecf9bc61f2ef1
- https://git.busybox.net/buildroot/log/package/python3
cxx-main dropped in:
- https://github.com/python/cpython/commit/398ed84dc40abc58e16f5014d44c08f20cb4b5f6
ffi dropped in:
- https://github.com/python/cpython/commit/f40d4ddff3c800b3c956a5e8820aabe3aa87cddd
> Python3: cleanup configure options

- packages/addons/addon-depends/vdr-plugins/vdr-plugin-eepg/patches/vdr-plugin-eepg-PR2-fix-build-with-vdr-2-7-1.patch
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-epgsearch/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-live/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-restfulapi/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/patches/vdr-plugin-xmltv2vdr-04-fixed-import-for-vdr-2-7-1.patch
- packages/addons/addon-depends/vdr/package.mk
- packages/addons/service/vdr-addon/package.mk
- vdr: update to 2.7.1
- vdr-plugin-eepg: fix build with vdr 2.7.1
- vdr-plugin-epgsearch: update to 2.4.3
- vdr-plugin-live: update to 3.3.6
- vdr-plugin-restfulapi: update to githash be8a3a6
- vdr-plugin-wirbelscan: update to 2024.09.15
- vdr-plugin-xmltv2vdr: Fixed import for vdr 2.7.1
> vdr-addon: update to 2.7.1 and addon (1)

- packages/addons/addon-depends/vdr-plugins/vdr-plugin-eepg/patches/vdr-plugin-eepg-PR2-fix-build-with-vdr-2-7-1.patch
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-epgsearch/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-live/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-restfulapi/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/package.mk
- packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/patches/vdr-plugin-xmltv2vdr-04-fixed-import-for-vdr-2-7-1.patch
- packages/addons/addon-depends/vdr/package.mk
- packages/addons/service/vdr-addon/package.mk
- backport of #9317 
- vdr: update to 2.7.1
- vdr-plugin-eepg: fix build with vdr 2.7.1
- vdr-plugin-epgsearch: update to 2.4.3
- vdr-plugin-live: update to 3.3.6
- vdr-plugin-restfulapi: update to githash be8a3a6
- vdr-plugin-wirbelscan: update to 2024.09.15
- vdr-plugin-xmltv2vdr: Fixed import for vdr 2.7.1
> [le12] vdr-addon: update to 2.7.1 and addon (2)

- packages/databases/mariadb-connector-c/package.mk
- version 3.4.2 has been pulled - reverting to 3.4.1
> mariadb-connector-c: update to 3.4.1

- packages/sysutils/usbutils/patches/usbutils-0001-allow-run-with-busybox.patch
- Fixes #9327 error when using USB-devices
```
nuc12:~ # usb-devices 
find: unrecognized: -printf
BusyBox v1.36.1 (2024-09-26 02:50:44 UTC) multi-call binary.
Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
Search for files and perform actions on them.
```
> usbutils: allow usb-devices to run using busybox find

- packages/tools/atf/package.mk
Changelog and release notes:
- https://trustedfirmware-a.readthedocs.io/en/latest/change-log.html
build error with iMX8 (all other builds are successful)
```
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-iMX8.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-iMX8.aarch64-13.0-devel/build/atf-2.11.0/build/imx8mq/release/bl31/bl31.elf section `.coherent_ram' will not fit in region `RAM'
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-iMX8.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: BL31 image has exceeded its limit.
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-iMX8.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: region `RAM' overflowed …
```
> atf: update to 2.11.0

- packages/graphics/mesa/package.mk
The bugfix release 24.2.4 is now available.
The next bugfix release is due in two weeks, on October 16th.
Cheers,
Eric
---
Aleksi Sapon (2):
llvmpipe: fix quad group helper invocation masking
llvmpipe: correctly implement output variables loads
Benjamin Otte (1):
nvk: Don't emit critical messages during init
pan/va: Fix nir_op_pack_uvec4_to_uint
intel/brw: Skip per-primitive inputs when computing flat input mask
Colin Marc (2):
vulkan/video: set HEVC nuh_temporal_id_plus1 and nal_unit_type correctly
radv/video: set TemporalId correctly
Corentin Noël (1):
virgl: Avoid a race condition on handle removal
Daniel Svensson (1):
zink: add spirv_info_h dep …
> mesa: update to 24.2.4

- packages/python/devel/pyproject-hooks/package.mk
Testing with 1.1.0 was not successful and was not put forward.
Testing with 1.2.0 was successful with Generic build, further testing requested
https://github.com/pypa/pyproject-hooks/blob/main/docs/changelog.rst
https://github.com/pypa/pyproject-hooks/compare/v1.0.0...v1.1.0
https://github.com/pypa/pyproject-hooks/compare/v1.1.0...v1.2.0
> pyproject-hooks: update to 1.2.0

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-999.20-headers-only.patch
Refresh Kodi headers only patch to fix #8271 and promote libxkbcommon to common kodi target dependency so it can be build separately.
> Kodi wayland build fixes

- packages/network/wireless-regdb/package.mk
> wireless-regdb: update to 2024.10.07

- packages/network/wireless-regdb/package.mk
Release notes:
- Backport of #9369
> [le12] wireless-regdb: update to 2024.10.07

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.297
- vulkan-loader: update to 1.3.297
- vulkan-tools: update to 1.3.297
> Vulkan update to 1.3.297

- projects/Samsung/patches/kodi/kodi-0002-LOCAL-changes-for-Odroid-XU3-XU4.patch
ref:
- video plane code reworked in upstream
- https://github.com/xbmc/xbmc/commit/cfb130d42a8fce7fc6a12015e34a9df8388e47de
- fixes build since Kodi bump in #9380
> kodi (Exynos): drop video plane patch

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.21.1.html
> samba: update to 4.21.1

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- fixed by https://github.com/xbmc/inputstream.adaptive/pull/1701
- fixes #9391
> inputstream.adaptive: update 22.1.6-Piers to 22.1.7-Piers

- tools/docker/noble/Dockerfile
Noble has now been updated with gcc-14.2.0 (was 14.0.1) 
Testing with 14.0.1 has been successful and now with a release gcc version 14.2.0 that aligns with our target compiler.
> tools/docker/noble: update to gcc-14

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.298
- vulkan-loader: update to 1.3.298
- vulkan-tools: update to 1.3.298
> Vulkan update to 1.3.298

- packages/graphics/spirv-llvm-translator/package.mk
- packages/lang/llvm/package.mk
- packages/lang/llvm/patches/llvm-14.0.0-force-disable-cmakelist-options.patch
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
LLVM-19 update was on hold until rust-1.82.0 was released (rust 1.81.0 was dependent on LLVM-18.)
- https://releases.llvm.org/19.1.0/docs/ReleaseNotes.html
- https://discourse.llvm.org/t/llvm-19-1-0-released/81285
- https://discourse.llvm.org/t/llvm-19-1-1-released/82321
- https://discourse.llvm.org/t/llvm-19-1-2-released/82550
- https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v19.1.0
- https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html
> update to llvm-19.1.2 and rust-1.82.0

- packages/linux-firmware/kernel-firmware/package.mk
Do not run check_whence.py against the copied firmware. `check_whence.py` has been enforced since https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/copy-firmware.sh?id=6edd0fd36acb93c8075bbd700ad91f53fc810c0e 
Update `check_whence.py` to always return 0.
- `echo '#!/usr/bin/python3' > check_whence.py`
> kernel-firmware: update to 20241017

- packages/linux/package.mk
- scripts/checkdeps
- tools/docker/bookworm/Dockerfile
- tools/docker/focal/Dockerfile
- tools/docker/jammy/Dockerfile
- tools/docker/noble/Dockerfile
rsync:host is used solely by the linux kernel build as a fancy file copy. We're not doing something special with our rsync:host build, so switch to a system provided rsync. My belief is that most dev systems already have rsync installed.
> build: use system rsync

- scripts/get_archive
- tools/distro-tool
See https://github.com/LibreELEC/LibreELEC.tv/pull/9347#issuecomment-2423525708
Default downloads the error page instead of giving an error.
> build/curl: error when 400 series status code received on download

- packages/devel/elfutils/package.mk
- packages/devel/elfutils/patches/elfutils-002-libdw--Don-t-use-INTUSE-in-libdwP-h-str_offsets_base_off.patch
This reverts commit d393833d053c9bc4775765b22c2220977e26ae30.
Builds failing across arch - (eu code)
```
/build/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libelf.a(elf_begin.o):elf_begin.c:function file_read_elf:(.text+0x38b): error: undefined reference to 'eu_search_tree_init'
/build/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libelf.a(elf_begin.o):elf_begin.c:function file_read_elf:(.text+0x4cb): error: undefined reference to 'eu_search_tree_init'
/build/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libelf.a(elf_end.o):elf_end.c:function elf_end:(.text+0xb0): error: undefined reference to 'eu_search_tree_fini'
```
> Revert "elfutils: update to 0.192"

- packages/network/iwd/package.mk
Log
- https://git.kernel.org/pub/scm/network/wireless/iwd.git/
- ver 3.0:
+	Fix issue with handling alpha2 code for United Kingdom.
+	Fix issue with handling empty TX/RX bitrate attributes.
+	Fix issue with handling RSSI polling fallback workaround.
+	Fix issue with handling harmless cloned information elements.
+	Add experimental support for External Authentication feature.
> iwd: update to 3.0

- packages/tools/u-boot/patches/0001-libfdt-Fix-build-with-swig-4-3.0.patch
ref:
- https://github.com/swig/swig/commit/cd39cf132c96a0887be07c826b80804d7677a701
during dtc build for img.gz u-boot fails. Patch sent upstream 
- https://lists.denx.de/pipermail/u-boot/2024-October/thread.html
- https://lists.denx.de/pipermail/u-boot/2024-October/569585.html
Fixes:
```
HOSTLD  scripts/dtc/dtc
LDS     u-boot.lds
LDS     u-boot-elf.lds
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_next_node’:
scripts/dtc/pylibfdt/libfdt_wrap.c:5581:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’
5581 |     resultobj = SWIG_Python_AppendOutput(resultobj, val);
|                 ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
| …
```
> u-boot: allow u-boot to build with swig-4.3.0

- packages/multimedia/media-driver/package.mk
```
Generic.x86_64-devel-20241026093451-55aea88
Linux nuc12 6.12.0-rc4 #1 SMP Sat Oct 26 09:51:06 UTC 2024 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:32b04718c65a90f87e409674c4ef984b087b8657). Platform: Linux x86 64-bit
Kodi compiled 2024-10-26 by GCC 14.2.0 for Linux x86 64-bit version 6.12.0 (396288)
Running on LibreELEC (heitbaum): devel-20241026093451-55aea88 13.0, kernel: Linux x86 64-bit version 6.12.0-rc4
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0093.2024.0508.2037 05/08/2024
[    0.000000] DMI: Memory slots populated: 1/2 …
```
> media-driver: update to 24.4.1

- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- projects/Allwinner/linux/linux.aarch64.conf
- projects/Allwinner/linux/linux.arm.conf
- projects/Generic/linux/linux.x86_64.conf
- projects/NXP/devices/iMX6/linux/linux.arm.conf
- projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf
- projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf
- projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
- projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
- projects/Rockchip/patches/linux/default/linux-1000-drm-rockchip.patch
- projects/Samsung/linux/linux.arm.conf
- linux: update to 6.11.x
- iwlwifi-firmware: update to githash f87fe97
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.1
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.2
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.3
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.4
6.11.1 - 12 patches
6.11.2 - 695 patches
6.11.3 - 558 patches
6.11.4 - 212 patches
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.11.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.11.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.11
- …
> linux: update to 6.11.4

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/package.mk
- cli: update to 27.3.1
- moby: update to 27.3.1
- containerd: update to 1.7.23
- runc: update to 1.2.0
- go: update to 1.23.2
> docker: update to 27.3.1 and addon (2)

- tools/change_addon_version
Could anyone with linux test this ? I get some error that is likely due slow git at WSL.
```
cvh@CvH:/mnt/d/LE$ ./tools/change_addon_version
git commit "distro: bump ADDON_VERSION to 12.80.1"
git commit "addons: reset version"
fatal: Unable to create '/mnt/d/LE/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git commit "addons: bump kodi-binary-addons"
```
> change_addon_version: add binary-addons

- packages/graphics/mesa/package.mk
The bugfix release 24.2.6 is now available.
The next bugfix release is due in two weeks, on November 13th.
Cheers,
Eric
---
Adam Jackson (1):
glx: Fix the GLX_EXT_swap_control_tear drawable attributes
Alyssa Rosenzweig (1):
asahi: fix no16 flag
Anil Hiranniah (1):
panfrost: Fix a memory leak in the CSF backend
Chia-I Wu (1):
panvk: fix descriptor set layout hash
Christian Gmeiner (1):
etnaviv: nir: Enforce stricter swizzle for virtual scalar x register
Connor Abbott (3):
ir3: Increase compute const size on a7xx
freedreno: Add compute constlen quirk for X1-85
tu: Don't invalidate CS state for 3D blits
Daniel Schürmann (2):
aco/spill: fix faulty assertions
aco: Respect …
> mesa: update to 24.2.6

- packages/linux/package.mk
- packages/linux/patches/rtlwifi/6.11.2/0001-6.11.2-wifi-rtw88-8703b-Fix-reported-RX-band-width.patch
Fix RPi and Amlogic builds due to rtw patch that was backported (and then dropped from the 6.12 directory) from 6.12 to 6.11.2
> Fix linux builds due to rtw backported patch

- packages/mediacenter/kodi/package.mk
- MediaSession: Properly update when pressing stop
- [BP] Restore Library Scan Performance
- [backport][subtitles][libass] Fallback value for no PlayResY
- [BP][Libcdio-gplv3] Fix crash on macOS (upstream patch)
- [Omega][Android] Fix resuming paused media playback not working via play/pau…
- [backport][CharArrayParser] Skip malformed EOL
- [partial backport][GUI][GUIDialogSubtitleSettings] Add missing original flag support
- [addons] add missing flag to filesystem translation from binary add-ons - Backport
- [BP][UPnP] Do not scan for external subs for UPnP renderer
- [Omega][PVR] [PVR] Async EPG update: Fix removal of EPG events notified as ' deleted', take 2
- [Omega][PVR] Context menu item 'Start recording': Fix to respect other runni…
- [Omega][PVR] Context …
> [le12] kodi: update to 2b2d09e

- packages/mediacenter/kodi/package.mk
log:
- https://github.com/xbmc/xbmc/compare/32b04718c65a90f87e409674c4ef984b087b8657...3f6829c18a74f3ca68d4644cec33aa2294f443ea
```
Generic.x86_64-devel-20241102113922-dd90bad
Linux nuc12 6.12.0-rc5 #1 SMP Sat Nov  2 11:40:10 UTC 2024 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:3f6829c18a74f3ca68d4644cec33aa2294f443ea). Platform: Linux x86 64-bit
Kodi compiled 2024-11-02 by GCC 14.2.0 for Linux x86 64-bit version 6.12.0 (396288)
Running on LibreELEC (heitbaum): devel-20241102113922-dd90bad 13.0, kernel: Linux x86 64-bit version 6.12.0-rc5
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0093.2024.0508.2037 …
```
> kodi: update to githash 3f6829c

- packages/addons/service/librespot/package.mk
- packages/rust/bindgen-cli/package.mk
release notes:
- https://github.com/librespot-org/librespot/releases/tag/v0.6.0
- dependency
- bindgen-cli: update to 0.69.5
- https://github.com/librespot-org/librespot/issues/1392
> librespot: update to 0.6.0 and addon (1)

- packages/network/iwd/package.mk
+	Fix issue with handling OWE transition BSS selection.
+	Fix issue with handling oper class 136 starting frequency.
> iwd: update to 3.1

- packages/network/iwd/package.mk
+	Fix issue with handling OWE transition BSS selection.
+	Fix issue with handling oper class 136 starting frequency.
- backport #9475
> [le12] iwd: update to 3.1

- packages/graphics/libheif/package.mk
- packages/graphics/tiff/patches/tiff-0001-cmake--Replace-CMath--CMath-with-direct-link-to-avoid-export-of-target.patch
- libheif: update to 1.19.2
- tiff: fix static linkage
- https://github.com/strukturag/libheif/issues/1375
- https://gitlab.com/libtiff/libtiff/-/commit/67f73084ca824e6c2465c47a5b67b16b5beca569.patch
- https://gitlab.com/libtiff/libtiff/-/issues/625
> libheif: update to 1.19.2

- packages/x11/lib/pixman/package.mk
ref: https://gitlab.freedesktop.org/pixman/pixman/-/commit/2e29b7c43d5a3be7b70d4326f975ad1cdf18ac81
- fixes arm/aarch64 build issue introduced with #9471
> pixman: drop support for iwmmxt

- projects/RPi/packages/linux/modprobe.d/brcmfmac.conf
iwd is unable to connect with WPA3 networks with current firmware/driver combo, disable offload until it is fixed.
https://forum.libreelec.tv/thread/29155-rpi5-network-disappeared/
> RPi: brcmfmac: disable SAE authentication offload

- projects/RPi/packages/linux/modprobe.d/brcmfmac.conf
> [le12] RPi: brcmfmac: disable SAE authentication offload

- packages/addons/service/ntfs3g/package.mk
Cosmetic only change to make the add-on more visible in the repo and add a proper description. AFAIK there's no need to bump the add-on version?
> ntfs-3g: capitalise NTFS-3G and provide a longer add-on description

- packages/graphics/mesa/package.mk
The bugfix release 24.2.7 is now available.
The next bugfix release is due in two weeks, on November 27th.
Cheers,
Eric
---
Benjamin Herrenschmidt (1):
dril: Fixup order of pixel formats in drilConfigs
Christian Gmeiner (1):
etnaviv: Fix incorrect pipe_nn creation
Connor Abbott (1):
ir3: Fix detection of nontrivial continues
radeonsi/vcn: Enable VCN4 AV1 encode WA
Eric Engestrom (11):
docs: add sha sum for 24.2.6
.pick_status.json: Update to ab1479ae6a845d2c7beeb0fed6e2153cc2b16c5e
.pick_status.json: Update to fe50011ddb35077c0d4cc2b31d56f8dd1376d5a2
meson: add dependencies needed by wsi_common_x11.c even on non-drm platforms
.pick_status.json: Update to …
> mesa: update to 24.2.7

- packages/linux/package.mk
- packages/linux/patches/raspberrypi/linux-001-Revert-DTS-bcm2712-re-enable-SD-slot-CQE-by-default-.patch
- packages/linux/patches/raspberrypi/linux-002-dts-bcm2711-drop-numa_policy-from-bootargs.patch
- packages/linux/patches/raspberrypi/linux-003-dts-bcm2712-drop-numa_policy-from-bootargs.patch
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
Partial backport of #9492
The experimental NUMA emulation options on RPi4/5 are not enabled for LE12 and SD command queueing on RPi5 has been disabled by default as it still seems to cause some issues.
> [le12] linux (RPi): update to 6.6.60

- packages/addons/service/jellyfin/package.mk
release notes:
- https://github.com/jellyfin/jellyfin/releases/tag/v10.10.0
- https://github.com/jellyfin/jellyfin/releases/tag/v10.10.1
> jellyfin: update to 10.10.1 and addon (2)

- packages/addons/service/jellyfin/package.mk
release notes:
- https://github.com/jellyfin/jellyfin/releases/tag/v10.10.0
- https://github.com/jellyfin/jellyfin/releases/tag/v10.10.1
- Backport of #9501
> jellyfin: update to 10.10.1 and addon (5)

- packages/mediacenter/kodi/package.mk
log:
- https://github.com/xbmc/xbmc/compare/3f6829c18a74f3ca68d4644cec33aa2294f443ea...65703fe91c077d8cc11be4ba10221b56cd38d30b
```
Generic.x86_64-devel-20241116021420-660ae2e
Linux nuc12 6.12.0-rc7 #1 SMP Thu Nov 14 05:59:14 UTC 2024 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:65703fe91c077d8cc11be4ba10221b56cd38d30b). Platform: Linux x86 64-bit
Kodi compiled 2024-11-16 by GCC 14.2.0 for Linux x86 64-bit version 6.12.0 (396288)
Running on LibreELEC (heitbaum): devel-20241116021420-660ae2e 13.0, kernel: Linux x86 64-bit version 6.12.0-rc7 …
```
> kodi: update to githash 65703fe

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/patches/fix-aarch64-widevine.patch
This fixes the `undefined symbol: __aarch64_ldadd4_acq_rel` isses as reported on our forums:
https://forum.libreelec.tv/thread/28572-official-le13-test-images-for-amlogic-kodi-22/?postID=196568#post196568
I also PR'ed the fix upstream so we should be able to drop it at the next i.a bump
https://github.com/xbmc/inputstream.adaptive/pull/1729
> inputstream.adaptive: add patch to fix widevine on aarch64

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.3.302
- vulkan-loader: update to 1.3.302
- vulkan-tools: update to 1.3.302
> Vulkan update to 1.3.302

- packages/devel/talloc/package.mk
currently clean builds fail because talloc is looking for python but package.mk doesn't have a dependency on Python3.
eg scripts/build_mt talloc
```
Checking for python version >= 3.6.0                                                            : 3.12.7
python-config                                                                                   : /home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-13.0-devel/toolchain/aarch64-libreelec-linux-gnu/sysroot/usr/bin/python3-config
Checking for library python3.12 in LIBPATH_PYEMBED                                              : not found 
Checking for library python3.12 in LIBDIR                                                       : not found
Checking for library python3.12 in python_LIBPL …
```
> talloc: don't build python modules

- packages/sysutils/lirc/package.mk
- packages/sysutils/lirc/patches/lirc-0100-disable-python.patch
[This forum post](https://forum.libreelec.tv/thread/24372-how-to-configure-atric-ir-wakeupusb-with-rpi4/?postID=196616#post196616) reports use of not existent /var/lock/lockdev directory of lirc.
configure does detect /var/lock correctly but there is a left over lib/lirc/config.h in lirc release archive 0.10.2 overwriting the path. Delete the file.
Furthermore define lock directory using `--with-lockdir=/var/lock` because lirc's configure does check the host file system and set /var/lock/lockdev if existing.
Removing the config.h file let VERSION_NODOTS work around fail. Change the disable python patch to use shell script instead of python code to compute the value.
> lirc: fix lock directory / rework VERSION_NODOTS computation

- packages/devel/glibc/package.mk
Now all kernels are 6.12, update the api to 6.12.
> glibc: update enable-kernel=6.12.0

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.21.2.html
> samba: update to 4.21.2

- packages/mediacenter/kodi/patches/kodi-999.99-PR25981-EGL_KHR_partial_update.patch
It might not be the final iteration of the patch, but it works well enough for now and restores the Kodi UI on lima/panfrost devices. Only tested on Amlogic but I presume Allwinner and Rockchip are currently borked too.
- See https://github.com/xbmc/xbmc/pull/25981
- https://github.com/xbmc/xbmc/pull/26007
Fixes https://github.com/LibreELEC/LibreELEC.tv/issues/9529
> kodi: backport PR25981 to temp-fix GUI with lima/panfrost devices

- packages/network/iwd/package.mk
> [le12] iwd: update to 3.2

- packages/linux/package.mk
run tested on Generic  
build tested on my 241122 community release Generic, Allwinner, Rockchip
> [le12] linux: update to 6.6.63

- packages/graphics/mesa/package.mk
Hi list,
Today we have Mesa 24.3.1, the first point release of the 24.3 series.
We have lots of ixies here, including several fixes for reported issues.
We've got fixes across the board, but noe one component to heavily
touched.
I wanted to extend a thank you to all of the developers who helped
backport patches for this release.
See you again in two weeks.
Cheers,
Dylan
shortlog
========
Alyssa Rosenzweig (1):
zink: fix gl_PrimitiveID reads with quads
Antonino Maniscalco (1):
nir,zink,asahi: support passing through gl_PrimitiveID
Boris Brezillon (2):
panfrost: Increase AFBC body alignment requirement on v6+
panvk/csf: Fix register overlap in issue_fragment_jobs()
intel/brw: Fix decoding of cond_modifier and saturate in EU validation
Chia-I Wu (3):
panvk: clang-format …
> mesa: update to 24.3.1

- packages/addons/service/ntfs3g/package.mk
- packages/addons/service/ntfs3g/source/system.d/service.ntfs3g.service
Suppress error on shutdown.:
```
Dec 05 19:29:44 lepxe12 systemd[1]: Unmounting usr-sbin-mount.ntfs.mount...
Dec 05 19:29:44 lepxe12 systemd[1]: usr-sbin-mount.ntfs.mount: Deactivated successfully.
Dec 05 19:29:44 lepxe12 systemd[1]: Unmounted usr-sbin-mount.ntfs.mount.
Dec 05 19:29:50 lepxe12 systemd[1]: Stopping service.ntfsfix-mount.service...
Dec 05 19:29:50 lepxe12 umount[1068]: umount: /usr/sbin/mount.ntfs: not mounted.
Dec 05 19:29:50 lepxe12 systemd[1]: service.ntfsfix-mount.service: Control process exited, code=exited, status=32/n/a
Dec 05 19:29:50 lepxe12 systemd[1]: service.ntfsfix-mount.service: Failed with result 'exit-code'.
Dec 05 19:29:50 lepxe12 systemd[1]: Stopped service.ntfsfix-mount.service.
```
Bind mount /usr/sbin/mount/ntfs.mount may already be unmounted due to …
> ntfs3g: service: avoid error on shutdown / update addon (1)

- packages/devel/ncurses/package.mk
NCURSES_ENABLE_STDBOOL_H was not being set correctly, causing bool to be misdefined. Testing with gcc-15 showed up this issue with the cross compile.
> ncurses: fix crosscompile target ncurses.h

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rustc-snapshot: update to 1.83.0
- rust-std-snapshot: update to 1.83.0
- cargo-snapshot: update to 1.83.0
- rust: update to 1.83.0
- [INFO] The `build.profiler` option now tries to use source code from `download-ci-llvm` if possible, instead of checking out the `src/llvm-project` submodule.
- PR Link https://github.com/rust-lang/rust/pull/129295
> rust: update to 1.83.0

- projects/Rockchip/patches/linux/default/linux-1000-drm-rockchip.patch
With the kernel update to version 6.12 and this commit https://github.com/LibreELEC/LibreELEC.tv/commit/9c7e6e06d97300356a29f87c3c56288c77d19c7d the test builds stopped working on my roc-3328-cc board (no hdmi signal) and probably on others soc too. 
To resolve this I backported these two patches from @Kwiboo which are included in the upcoming kernel 6.13 (so I think they are safe).
Unfortunately I don't have any board with rk3399 to do some tests
> Rockchip backport drm patch 6 13

- packages/network/nss-mdns/config/nsswitch.conf
- packages/sysutils/systemd/package.mk
- packages/sysutils/util-linux/package.mk
- https://www.freedesktop.org/software/systemd/man/latest/nss-systemd.html#
Updated addon component `nqptp` which previously dropped root privileges has been changed to use CAP_NET_BIND_SERVICE functionality in systemd. Instead of creating a user/group in `/etc/passwd` use the `DynamicUser` systemd functionality. This functionality is independent of the `nss-systemd` service - but to allow user/group resolution - the `nss-systemd` service is required.
```
nuc12:~ # systemctl status service.nqptp
● nqptp.service - NQPTP -- Not Quite PTP
Loaded: loaded (/storage/.config/system.d/nqptp.service; linked; preset: disabled)
Active: active (running) since Tue 2024-03-05 09:30:38 UTC; 2 days ago
Main PID: 3698 (nqptp)
Tasks: 1 (limit: 37511)
Memory: 236.0K (peak: 340.0K)
CPU: 16min 49.603s
CGroup: …
```
> Enable the nss-systemd service

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/drmprime-filter/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0002-WIP-DRMPRIME-deinterlace-filter.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0003-DVDVideoCodecDRMPRIME-Avoid-exception-with-AV_PIX_FM.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0004-DVDVideoCodecDRMPRIME-Leave-deinterlace-filter-activ.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0005-SetVideoInterlaced-Set-and-unset-deinterlace-method-.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0006-DVDVideoCodecDRMPRIME-Close-deinterlace-filter-on-er.patch
- packages/mediacenter/kodi/patches/drmprime-filter/0007-DVDVideoCodecDRMPRIME-Fix-missing-flush-after-eof.patch
- projects/RPi/patches/kodi/0001-gbm-Set-max-bpc-for-high-bit-depth-videos.patch
- projects/RPi/patches/kodi/0002-CDVDVideoCodecDRMPRIME-Also-support-YUV420-buffers.patch
- projects/RPi/patches/kodi/0003-CDVDVideoCodecDRMPRIME-Adjust-av-formats-to-match-re.patch
- projects/RPi/patches/kodi/0004-DVDVideoCodecDRMPRIME-Add-support-for-arbitrary-outp.patch
- projects/RPi/patches/kodi/0005-DVDVideoCodecDRMPRIME-Remove-obsolete-thread_safe_ca.patch
- projects/RPi/patches/kodi/0006-DVDVideoCodecDRMPRIME-Clear-m_pFilterGraph.patch
- projects/RPi/patches/kodi/0007-DVDVideoCodecDRMPRIME-Move-FilterTest-from-open-to-f.patch
- projects/RPi/patches/kodi/0008-DVDVideoCodecDRMPRIME-Rework-filtering-code-to-handl.patch
- projects/RPi/patches/kodi/0009-CDVDVideoCodecDRMPRIME-Support-decoding-to-DRMPRIME-.patch
- projects/RPi/patches/kodi/0010-DVDVideoCodecDRMPRIME-Request-v4l2-buffers-be-alloca.patch
- projects/RPi/patches/kodi/0011-DVDVideoCodecDRMPRIME-Add-setting-to-enable-hw-deint.patch
- projects/RPi/patches/kodi/0012-fixup-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
Initial testing on RPi4 and RPi5 looks fine.
Depends on #9569
> kodi: update to current master with ffmpeg 7.1

- packages/emulation/libretro-hatari/package.mk
Discovered when doing `scripts/create_addon game.retro.*` from clean
> [le12] libretro-hatari: add missing zlib DEPENDS

- packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
- packages/addons/addon-depends/snapcast-depends/snapcast/package.mk
- packages/addons/service/snapclient/package.mk
- packages/addons/service/snapserver/package.mk
- packages/addons/tools/multimedia-tools/package.mk
- packages/devel/boost/package.mk
- snapclient: update addon (2)
- snapserver: update addon (2)
- snapcast: update to githash 6190041
- boost: update to 1.87.0
- multimedia-tools: update addon (2)
- squeezelite: update to githash 279ac08 (2.0.0.1507)
other fixes required:
- shairport-sync (due to ffmpeg - upstream is fixed, but nqptp needs to be reworked)
- game.libretro
- inputstream.ffmpegdirect - reliant on https://github.com/xbmc/inputstream.ffmpegdirect/pull/304 and release
> Addon build fixes

- packages/sysutils/systemd/patches/systemd-0400-use-RET_GATHER-more.patch
- packages/sysutils/systemd/patches/systemd-0500-install-alias-for-units-outside.patch
This PR fixes issue #9618.
```
RPi4:~ # systemctl status service.system.docker | cat
● service.system.docker.service - Docker Application Container Engine
Loaded: loaded (/storage/.config/system.d/service.system.docker.service; enabled; preset: disabled)
Active: active (running) since Fri 2024-12-27 17:40:34 CET; 13s ago
Docs: https://docs.docker.com
Process: 1799 ExecStartPre=/storage/.kodi/addons/service.system.docker/bin/docker-config (code=exited, status=0/SUCCESS)
Main PID: 1802 (dockerd)
Tasks: 20 (limit: 8192)
CPU: 910ms
CGroup: /system.slice/service.system.docker.service
├─1802 /storage/.kodi/addons/service.system.docker/bin/dockerd --exec-opt native.cgroupdriver=systemd --log-driver=journald --group=root --data-root=/storage/.kodi/userdata/addon_data/service.system.docker/docker …
```
> [le12] systemd: fix non-working service aliases

- packages/compress/libarchive/package.mk
- packages/devel/elfutils/package.mk
- packages/mediacenter/kodi-binary-addons/vfs.libarchive/package.mk
- libarchive: fix target DEPENDS
- libarchive: force use of pcre2
- libarchive: include LZMA (.xz)
- libarchive: update to 3.7.7
- [elfutils: build with libarchive](https://github.com/LibreELEC/LibreELEC.tv/pull/9621/commits/18125dcb28047a37b0197755ea08054d925ddef8) 
[18125dc](https://github.com/LibreELEC/LibreELEC.tv/pull/9621/commits/18125dcb28047a37b0197755ea08054d925ddef8)
- building without libarchive can not be done if libarchive is detected. update the dependancies and allow correct linking with pkg-config --static
> vfs.libarchive: libarchive to 3.7.7 and update addon (9)

- packages/linux/package.mk
- projects/NXP/devices/iMX6/linux/linux.arm.conf
- projects/NXP/devices/iMX8/linux/linux.aarch64.conf
- linux: update to 6.12.7
- linux (NXP iMX6): update .config for 6.12.7
- linux (NXP iMX8): update .config for 6.12.7
- linux: update to 6.12.x
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.6
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.7
6.12.6 - 172 patches
6.12.7 - 160 patches
``` …
```
> linux: update to 6.12.7

- packages/linux/patches/rtlwifi/after-6.12/0029-wifi-rtw88-add-__packed-attribute-to-efuse-layout-st.patch
- packages/linux/patches/rtlwifi/after-6.12/0030-wifi-rtlwifi-rtl8821ae-Fix-media-status-report.patch
- packages/linux/patches/rtlwifi/after-6.12/0031-wifi-rtw88-8812a-Support-RFE-type-2.patch
- packages/linux/patches/rtlwifi/after-6.12/0032-wifi-rtw88-8821a-8812a-Set-ptct_efuse_size-to-0.patch
- packages/linux/patches/rtlwifi/after-6.12/0033-wifi-rtw88-usb-Copy-instead-of-cloning-the-RX-skb.patch
- packages/linux/patches/rtlwifi/after-6.12/0034-wifi-rtw88-Handle-C2H_ADAPTIVITY-in-rtw_fw_c2h_cmd_h.patch
- packages/linux/patches/rtlwifi/after-6.12/0035-wifi-rtw88-usb-Preallocate-and-reuse-the-RX-skbs.patch
As the patches have now been added to rtw-next
- update the LE patches from upstream at https://github.com/pkshih/rtw
https://patchwork.kernel.org/project/linux-wireless/list/?series=&submitter=206810&state=*&q=&archive=both&delegate= https://github.com/pkshih/rtw/commit/0daa521a1c8c29ffbefe6530f0d276e74e2749d0 https://patchwork.kernel.org/project/linux-wireless/list/?series=918859&state=* https://patchwork.kernel.org/project/linux-wireless/list/?series=918880&state=* https://patchwork.kernel.org/project/linux-wireless/list/?series=919279&state=*
> linux: wifi: rtw88: update patches as they have now been accepted into rtw-next

- distributions/LibreELEC/options
- packages/sysutils/systemd/package.mk
- packages/sysutils/systemd/system.d/getty@tty0.service
- packages/sysutils/util-linux/package.mk
This PR adds buildsystem support for configuring a local console login prompt. This is useful for images that do not auto-boot into a full-screen app like Kodi, e.g. a minimal appliance-like image for Docker containers. The default is "no" so no functional change to existing LibreELEC images.
Tested with a Docker appliance OVA running under ESXi - it would be be good to validate the changes with other build projects and some real hardware.
> buildsystem: support optional configuration of local console login

- packages/mediacenter/kodi/package.mk
- projects/Allwinner/patches/kodi/000-temp-revert-fences.patch
- projects/Amlogic/patches/kodi/000-temp-revert-fences.patch
- projects/Generic/patches/kodi/000-temp-revert-fences.patch
- projects/RPi/patches/kodi/000-temp-revert-fences.patch
- projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
Runtime tested on RPi5.
The fences-revert patch now also reverts the async rendering fixes backport PR, like we do in LE master - see https://github.com/LibreELEC/LibreELEC.tv/pull/9436#issuecomment-2438028362 and https://github.com/xbmc/xbmc/pull/25588#issuecomment-2381332226
> [le12] kodi: update to current Omega HEAD

- packages/mediacenter/kodi/patches/kodi-995.20-python-lib-dir.patch
Backport of #9171
Since the switch from distutils to sysconfig landed in kodi Omega this is also needed in LE12 to fix the kodi-send and kodi-remote issues.
> [le12] kodi: Fix python installation dir

- packages/linux/package.mk
> [le12] linux (RPi): update to 6.6.69-de92e4b

- packages/addons/addon-depends/rpi-tools-depends/gpiod/package.mk
- packages/addons/addon-depends/rpi-tools-depends/gpiod/patches/gpiod-2.2.2-setuptools.patch
- packages/addons/tools/rpi-tools/package.mk
EDIT: This is the backport of #9592 for LibreELEC 12
gpiod are the official Python bindings for libgpiod. libgpiod is already part of the system tools add-on, only these Python bindings are currently missing to be able to use it in Python scripts.
lgpio and gpiozero are easier to use, but currently have some insurmountable problems, as I have tried to explain here:
[Feature request: RPi-Tools with official Python bindings for libgpiod](https://forum.libreelec.tv/thread/29292-feature-request-rpi-tools-with-official-python-bindings-for-libgpiod/)
> [le12] rpi-tools: backport of PR9592 - add gpiod support

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.21.3.html
> samba: update to 4.21.3

- packages/linux-firmware/firmware-imx/package.mk
release notes:
- Rev. LF6.6.52_2.2.0 — 16 December 2024
- Note: Support for i.MX 6 and i.MX 6 7 is deprecated in this release and will be removed in the next release.
> firmware-imx: update to 8.26-d4c33ab

- packages/addons/addon-depends/libgpiod/package.mk
- packages/addons/tools/system-tools/package.mk
gpiod are the official Python bindings for libgpiod. libgpiod is already part of the system tools add-on, only these Python bindings are currently missing to be able to use it in Python scripts.
lgpio and gpiozero are easier to use, but currently have some insurmountable problems, as I have tried to explain here:
[Feature request: RPi-Tools with official Python bindings for libgpiod](https://forum.libreelec.tv/thread/29292-feature-request-rpi-tools-with-official-python-bindings-for-libgpiod/)
> system-tools: add gpiod (official Python bindings for libgpiod)

- projects/Allwinner/devices/H2-plus/patches/u-boot/0001-DO-NOT-MERGE-sunxi-psci-Delegate-PSCI-to-SCPI.patch
- projects/Allwinner/devices/H2-plus/patches/u-boot/0007-sunxi-psci-Add-support-for-H3-CPU-0-hotplug.patch
- projects/Allwinner/devices/H2-plus/patches/u-boot/0010-sunxi-Enable-support-for-SCP-firmware-on-H3.patch
- projects/Allwinner/devices/H3/patches/u-boot/0012-DO-NOT-MERGE-sunxi-psci-Delegate-PSCI-to-SCPI.patch
- projects/Allwinner/devices/H3/patches/u-boot/0013-DO-NOT-MERGE-sunxi-Enable-SCP-SCPI-on-A33-as-well.patch
- u-boot (Allwinner H2-plus): rebase patch for 2025.01
- u-boot (Allwinner H3): rebase patch for 2025.01
- ~u-boot (Amlogic): drop upstreamed patches for 2025.01~
- ~u-boot: update to 2025.01~
Notes:
- Qualcomm still does not build `No valid dtbs found`
All builds successful apart from afore mentioned Qualcomm
```
target/LibreELEC-A64.aarch64-13.0-devel-20250107140450-f88789f-orangepi-win.img.gz
target/LibreELEC-A64.aarch64-13.0-devel-20250107140450-f88789f-pine64.img.gz
target/LibreELEC-A64.aarch64-13.0-devel-20250107140450-f88789f-pine64-lts.img.gz
target/LibreELEC-A64.aarch64-13.0-devel-20250107140450-f88789f-pine64-plus.img.gz
target/LibreELEC-AMLGX.aarch64-13.0-devel-20250107130851-f88789f-alta.img.gz
target/LibreELEC-AMLGX.aarch64-13.0-devel-20250107130851-f88789f-bananapi-m2-pro.img …
```
> u-boot: update Allwinner patches for 2025.01

- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rust: update to 1.84.0
- cargo-snapshot: update to 1.84.0
- rust-std-snapshot: update to 1.84.0
- rustc-snapshot: update to 1.84.0
- llvm: build llvm-objcopy required for rust 1.84.0
> rust: update to 1.84.0

- packages/network/libnfs/package.mk
Build tested
- https://github.com/sahlberg/libnfs/commit/5e8f7ce273308eb77f94248f4501e574a703c1a5
- https://github.com/MusicPlayerDaemon/MPD/issues/2165
Will probably wait for 6.0.x and upstream of Kodi patch before taking this out of draft. There is also the compatibility with MPD to consider.
> libnfs: update to 6.0.x and api v2

- packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Fix for [issue 9586](https://github.com/LibreELEC/LibreELEC.tv/issues/9586)
Removes check for `SUBSYSTEMS=="bluetooth"` since it is not used for bluetooth HID remotes. They use the input subsystem instead.
> eventlircd: fix subsystem rules for bluetooth HID remotes

- packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Backport of #9587 
Fix for https://github.com/LibreELEC/LibreELEC.tv/issues/9586
Removes check for SUBSYSTEMS=="bluetooth" since it is not used for bluetooth HID remotes. They use the input subsystem instead.
> [le12] eventlircd: fix subsystem rules for bluetooth HID remotes (backport of PR9587)

- packages/mediacenter/LibreELEC-settings/package.mk
bump after https://github.com/LibreELEC/service.libreelec.settings/pull/328
> LibreELEC-settings: bump to a0c61d0

- packages/network/samba/package.mk
Add samba vfs modules : catia, fruit, streams_xattr
Change sample config with Time Machine backup share - commented by default
See : https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
Tested on Generic-legacy.x86_64
> samba: Added Apple TimeMachine backup share feature

- packages/multimedia/media-driver/package.mk
ref: https://github.com/intel/media-driver/releases/tag/intel-media-25.1.0
```
Generic.x86_64-devel-20250114003445-a0d41fd
Linux nuc12 6.12.9 #1 SMP Mon Jan 13 10:15:57 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:8a0d510be81c055b29b7006d7e123270e4a0a534). Platform: Linux x86 64-bit
Kodi compiled 2025-01-13 by GCC 15.0.0 for Linux x86 64-bit version 6.12.9 (396297)
Running on LibreELEC (heitbaum): devel-20250114003445-a0d41fd 13.0, kernel: Linux x86 64-bit version 6.12.9
FFmpeg version/source: 7.1
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0094.2024.0806.1458 08/06/2024
CApplication::CreateGUI - trying to init gbm …
```
> media-driver: update to 25.1.0

- packages/network/libnfs/patches/libnfs-514-socket-use-void-cast-to-allow-compile-for-arm32.patch
- Fixes #9678
- Ref https://github.com/sahlberg/libnfs/issues/513
- Ref https://github.com/sahlberg/libnfs/pull/514
> libnfs: socket: use void cast to allow compile for arm32

- packages/mediacenter/kodi/package.mk
The version tag was updated upstream. No change to the githash.
> kodi: update version to use v21.2-Omega

- packages/sysutils/tz/package.mk
log: https://github.com/eggert/tz/compare/2024b...2025a
> tz: update to 2025a

- packages/linux/package.mk
- linux: update to 6.12.9
- linux: update to 6.12.x
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.8
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.9
6.12.8 - 114 patches
6.12.9 - 156 patches
- fixes #9624 
```
PROJECT=Allwinner ARCH=arm …
```
> linux: update to 6.12.9

- scripts/install_addon
Use the built `TARGET_ADDONS`  path defined by distribution `ADDON_PATH` .
> buildsystem: use distribution defined addon install path

- packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
- revert change introduced with 282b913aefed4599ada598991eae323412373b66 (#9470)
- go with upstream eb952e7746ad13f1eacc2d4367d9d9709af3e16e
> [le12] libmediainfo: fix build

- packages/mediacenter/kodi/package.mk
Upstream tidied up the tags (removing the v) so we should revert back
> kodi: revert to 21.2-Omega tag

- packages/linux/package.mk
- projects/Allwinner/linux/linux.aarch64.conf
- projects/Allwinner/linux/linux.arm.conf
- projects/Generic/linux/linux.x86_64.conf
- projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf
- projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf
- projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
- projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
- projects/Samsung/linux/linux.arm.conf
- linux: update to 6.12.10
- linux: update to 6.12.x
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.10
6.12.10 - 189 patches
- 
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux …
```
> linux: update to 6.12.y

- packages/addons/addon-depends/dvb-tools-depends/t2scan/patches/t2scan-17-fix-building-with-gcc-15.patch
- Minor fix required on #9566
- https://github.com/mighty-p/t2scan/pull/17
- https://github.com/LibreELEC/LibreELEC.tv/pull/9566/commits/f39ebc67aa2b7b2d1918881ea1e29794301b96ca
> t2scan: fix upstreamed -std=c23 patch

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.306
- vulkan-loader: update to 1.4.306
- vulkan-tools: update to 1.4.306
> Vulkan update to 1.4.306

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rust: update to 1.84.1
- rustc-snapshot: update to 1.84.1
- rust-std-snapshot: update to 1.84.1
- cargo-snapshot: update to 1.84.1
> Rust update to 1.84.1

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.307
- vulkan-loader: update to 1.4.307
- vulkan-tools: update to 1.4.307
> Vulkan update to 1.4.307

- packages/devel/gmp/patches/0001-acinclude.m4-fix-std-c23-build-failure.patch
Upstreamed:
Add prototype to configure test function as c23 removes unprototyped functions.
gcc-15 switched to -std=c23 by default:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
As a result `configure` fails with:
conftest.c: In function 'f':
conftest.c:12:48: error: too many arguments to function 'g'; expected 0, have 6
12 | for(i=0;i<1;i++){if(e(got,got,9,d[i].n)==0)h();g(i,d[i].src,d[i].n,got,d[i].want,9);if(d[i].n)h();}}
|                                                ^ ~
conftest.c:7:6: note: declared here
7 | void g(){}
|      ^
Upstream: hg log --patch --rev 18477:8e7bb4ae7a18
Link: https://gmplib.org/list-archives/gmp-bugs/2024-November/005550.html
Link: https://gmplib.org/list-archives/gmp-devel/2025-January/006281.html
> gmp: configure and acinclude.m4: fix -std=c23 build failure

- packages/devel/glibc/package.mk
Release Notes:
- https://sourceware.org/glibc/wiki/Release/2.41
Log:
- https://sourceware.org/git/?p=glibc.git;a=shortlog;h=refs/heads/release/2.41/master
> glibc: update to 2.41

- packages/linux/package.mk
- linux: update to 6.12.x
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.11
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.12
6.12.11 - 121 patches
6.12.12 - 41 patches
- 
``` …
```
> linux: update to 6.12.12

- projects/Allwinner/patches/linux/0071-HACK-SW-CEC-implementation-for-H3.patch
CEC stopped working on my 3 OrangePi PC's after updating from LE10 to LE11 as the former enabled the SW CEC hack for all H3 boards and the latter only for specific boards. Add OrangePi PC to that list of specific boards.
> allwinner: OrangePi PC also needs SW CEC hack

- distributions/LibreELEC/options
- packages/addons/service/boblightd/config/boblight.X11.sample
- packages/addons/service/mpd/source/config/mpd.conf
- packages/sysutils/eventlircd/evmap/03_0755_2626.evmap
- packages/sysutils/eventlircd/evmap/03_13ec_0006.evmap
- packages/tools/installer/system.d/installer.service
- projects/ARM/options
Given that I was asked to alter xbmc to kodi in a previous PR[^1], I went hunting to see if there were any other remaining instances. This is what I found that were minimally invasive. I also did a minor whitespace lint. Hopefully this isn't too annoying and you could forgive this whimsical way for me to contribute to the project.
[^1]: https://github.com/LibreELEC/LibreELEC.tv/pull/9715/files#diff-eb53bd9f4cb2c48c40ff014a0039b6c3fc5b0b1cdb484b873abdd2adf4774b48
> treewide: rename xbmc to kodi

- packages/graphics/mesa/package.mk
- packages/python/devel/ply/package.mk
ply is required by mesa package when building vulkan drivers, otherwise following error is thrown:
```
Problem encountered: Python (3.x) ply module required to build GRL kernels.
```
> ply: add python-ply package

- tools/docker/focal/Dockerfile
Update focal Dockerfile inline with jammy/noble to allow golang in LE13 to be compiled. Golang-1.18 is too old to bootstrap. Include rdfind. 
Note: focal will go EOL April 2025 - so the Dockerfile is planned to dropped at this time.
> tools/docker/focal: update Dockerfile to use golang-1.20

- packages/devel/binutils/package.mk
- packages/devel/binutils/patches/binutils-01-warn-for-uses-of-system-directories-when-link.patch
release notes:
- https://sourceware.org/pipermail/binutils/2025-February/139195.html
In a change to our previous practice, in this release the binutils-2.44.tar tarball does not contain the sources for the gold linker.  This is because the gold linker is now deprecated and will eventually be removed unless volunteers step forward and offer to continue development and maintenance.
The gold sources can be found in the binutils-with-gold-2.44.tar tarballs.  Going forward, odd numbered releases of the binutils (2.45, 2.47, etc) will just have the binutils.2.xx.tar tarballs, whilst even numbered releases will have both the binutils-2.xx.tar and the binutils-with-gold-2.xx.tar tarballs.  Eventually this will stop and gold will be dropped altogether.
> binutils: update to 2.44

- packages/graphics/vulkan/vulkan-tools/package.mk
- packages/wayland/wayland/package.mk
vulkan-tools requires wayland.xml when building wayland target with vulkan support. when wayland.xml is missing, build of vulkan-tools fails with following error:
CMake Error in cube/CMakeLists.txt:
Cannot find source file:
[...]/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/wayland/wayland.xml
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
.ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
.f95 .f03 .hip .ispc
> wayland: copy wayland.xml to SYSROOT

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/fb44880453243477a1ef1857d5555d71b00433cb...87917079958ad5609be9f8fe3379823fa364205d
```
Generic.x86_64-devel-20250206110622-9759729
Linux nuc12 6.14.0-rc1 #1 SMP Thu Feb  6 10:24:47 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:87917079958ad5609be9f8fe3379823fa364205d). Platform: Linux x86 64-bit
Kodi compiled 2025-02-06 by GCC 15.0.1 for Linux x86 64-bit version 6.14.0 (396800)
Running on LibreELEC (heitbaum): devel-20250206110622-9759729 13.0, kernel: Linux x86 64-bit version 6.14.0-rc1
FFmpeg version/source: 7.1 …
```
> kodi: update to githash 8791707

- packages/emulation/libretro-pcsx-rearmed/package.mk
ref: https://github.com/LibreELEC/LibreELEC.tv/pull/9715#discussion_r1927643465
> libretro-pcsx-rearmed: fix build for OdroidGoAdvance

- packages/web/curl/package.mk
- packages/web/curl/patches/curl-01-allow_building_debug.patch
The new curl version causes crashes eg when downloading addons from the kodi repo.
Revert the bump until the issue is resolved
> Revert "curl: update to 8.12.0"

- scripts/install_addon
This change caused addons explicitly built for a specific project/device to end up in the general ADDON_PROJECT folder (eg ARMv8) instead of the project/device specific folder.
This results in binaries compiled for different target architectures (eg cortex-a76 with AES extensions on RPi5 instead of cortex-a53 without AES extensions on our ARMv8 baseline device)  to end up in the wrong directory and  made it impossible to compile for both addon baseline options and device specific options, eg to do performance comparisons of different target architecture/options.
Our install script was fine before, so let's keep it this way
> Revert "buildsystem: use distribution defined addon install path"

- packages/addons/addon-depends/ffmpegx-depends/x265/package.mk
Cross compiling x265 for x86_64 on an arm64 host fails as cmake auto-detects the host CPU. This fixes the issue.
Ping @ksooo
> x265: fix x86_64 target compile on arm64 hosts

- packages/addons/service/mariadb/package.mk
This reverts commit 0e8535cc3e69302584a3e72f84a2e0e67ad30d81. mariadb is failing with thread_stack size in 11.4.4 and 11.4.5
https://forum.libreelec.tv/thread/29487-mariadb-addon-not-starting/
> [le12] mariadb: revert to 11.4.3 and addon (5)

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/libseccomp/package.mk
- packages/addons/addon-depends/podman/gpgme/package.mk
- packages/addons/addon-depends/podman/netavark/package.mk
- packages/addons/addon-depends/podman/podman-bin/package.mk
- packages/addons/service/docker/package.mk
- packages/addons/service/podman/package.mk
- tools/docker/jammy/Dockerfile
- tools/docker/noble/Dockerfile
- tools/docker/jammy: update to building with go-1.22
- tools/docker/noble: update to building with go-1.23
- go: update to 1.24.0
- docker: update to 27.5.1 and addon (7)
- cli: update to 27.5.1
- moby: update to 27.5.1
- podman: update to 5.4.0 and addon (3)
- podman-bin: update to 5.4.0
- containerd: update to 2.0.2
- netavark: update to 1.14.0
- libseccomp: update to 2.6.0
- gpgme: update to 1.24.2
> Addon updates for docker and podman

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/go/package.mk
- packages/addons/addon-depends/libseccomp/package.mk
- packages/addons/addon-depends/podman/gpgme/package.mk
- packages/addons/addon-depends/podman/netavark/package.mk
- packages/addons/addon-depends/podman/podman-bin/package.mk
- packages/addons/addon-depends/podman/podman-bin/patches/podman-0002-path-changes.patch
- packages/addons/service/docker/package.mk
- packages/addons/service/podman/package.mk
- tools/docker/bookworm/Dockerfile
- tools/docker/focal/Dockerfile
- tools/docker/jammy/Dockerfile
- tools/docker/noble/Dockerfile
- Backport #9784
- docker: update to 27.5.1 and addon (8)
- podman: update to 5.4.0 and addon (2)
- go: update to 1.23.6
- tools/docker/jammy: update to building with go-1.22
- tools/docker/noble: update to building with go-1.23
- tools/docker/focal: update Dockerfile to use golang-1.20
- dockerfiles: add rsync to docker build environments
- podman-bin: update to 5.4.0
- libseccomp: update to 2.6.0
- cli: update to 27.5.1
- moby: update to 27.5.1
- gpgme: update to 1.24.2
- netavark: update to 1.14.0
> [le12] Addon updates for docker and podman

- packages/tools/rpi-eeprom/package.mk
The "latest" version now got promoted to "default"
> rpi-eeprom: update to 50d7bfc

- packages/linux/package.mk
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
> [le12] linux (RPi): update to 6.6.78

- packages/graphics/mesa/package.mk
- change from intel_clc to mesa_clc https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/33014/commits
- clover: drop support for nir drivers - was not used https://gitlab.freedesktop.org/mesa/mesa/-/commit/80c4ffb61a91ed252d45e38a96e893cec0771940
> mesa: update to 25.0.0

- packages/network/openssh/package.mk
Change log:
- https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog
Release notes:
- https://www.openssh.com/releasenotes.html#9.9p2
Release notes:
- https://www.openssh.com/txt/release-9.9p2
> openssh: update to 9.9p2

- packages/network/wireless-regdb/package.mk
Release notes:
- Backport of #9810
> [le12] wireless-regdb: update to 2025.02.20

- packages/devel/json-c/package.mk
ref:
- https://github.com/json-c/json-c/wiki
- https://github.com/json-c/json-c/wiki/Old-Releases
- https://s3.amazonaws.com/json-c_releases/releases/index.html
> [le12] json-c: update download link and sha256

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.309
- vulkan-loader: update to 1.4.309
- vulkan-tools: update to 1.4.309
> Vulkan update to 1.4.309

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.21.4.html
> samba: update to 4.21.4

- packages/network/openssh/package.mk
- backport of #9802
Change log:
- https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog
Release notes:
- https://www.openssh.com/releasenotes.html#9.9p1
- https://www.openssh.com/releasenotes.html#9.9p2
Release notes:
- https://www.openssh.com/txt/release-9.9p1
- https://www.openssh.com/txt/release-9.9p2
> [le12] openssh: update to 9.9p2

- packages/security/openssl/package.mk
Release notes:
- https://openssl-library.org/news/openssl-3.2-notes/
Release notes:
- https://openssl-library.org/news/vulnerabilities/index.html
Changelog:
- https://github.com/openssl/openssl/blob/openssl-3.2/CHANGES.md
> [le12] openssl: update to 3.2.4

- packages/sysutils/kmod/patches/kmod-01-fix-build-with-glibc-2.31.patch
This patch fixes the kmod:host link error when building LE master on Debian Bullseye.
See https://github.com/kmod-project/kmod/pull/299
> kmod: add upstream fix for link errors with glibc 2.31

- packages/audio/alsa-utils/patches/alsa-utils-0001-gettext-fix.patch
Intermittent build issue in GHA, fixed by updating GETTEXT AC to matching gettext version.
- https://github.com/alsa-project/alsa-utils/issues/294
> alsa-utils: fix build with gettext-0.24

- packages/addons/addon-depends/jre-depends/jdk-aarch64-zulu/package.mk
- packages/addons/addon-depends/jre-depends/jdk-arm-zulu/package.mk
- packages/addons/addon-depends/jre-depends/jdk-x86_64-zulu/package.mk
- packages/addons/tools/jre.zulu/package.mk
- packages/addons/tools/jre.zulu/profile.d/jre.profile
- packages/multimedia/libbluray/patches/libbluray-03-set-headless-false.patch
temporary folder for libbluray-bdj-cache is set to /storage/libbluray-bdj-cache
> jre.zulu: bump jdk packages to 8.84.0.15-8.0.442 and addon (1)

- packages/emulation/libretro-swanstation/package.mk
- packages/mediacenter/kodi-binary-addons/game.libretro.swanstation/package.mk
Add the game add-on for SwanStation.
@garbear I've seen that the game add-ons are being updated by a script. I'm not sure if this is the correct way to add the add-on.
> Add SwanStation game add-on

- packages/graphics/mesa/package.mk
The bugfix release 25.0.1 is now available.
The next bugfix release is due in two weeks, on March 19th.
Cheers,
Eric
---
Benjamin Lee (4):
panfrost: remove NIR_PASS_V usage for noperspective lowering
panfrost: fix large int32->float16 conversions
panfrost: fix condition in bi_nir_is_replicated
panfrost/va: remove swizzle mod from LDEXP
brw: Fix size in assembler when compacting
Daniel Schürmann (5):
aco/scheduler: always respect min_waves on GFX10+
aco/insert_exec_mask: Don't immediately set exec to zero in break/continue blocks
aco/insert_exec_mask: don't restore exec in continue_or_break blocks
aco/ssa_elimination: insert parallelcopies for p_phi …
> mesa: update to 25.0.1

- packages/devel/binutils-aarch64/package.mk
- packages/devel/binutils-arm-none-eabi/package.mk
- packages/devel/binutils-bpf/package.mk
- packages/devel/binutils-or1k/package.mk
- packages/lang/gcc-aarch64/package.mk
- packages/lang/gcc-arm-none-eabi/package.mk
- packages/lang/gcc-bpf/package.mk
- packages/lang/gcc-or1k/package.mk
- packages/tools/atf/package.mk
Here's a funky one.
- I build ~once a month and it failed 100% for me for at least 6 months
- Looking at the patches this is in "how did this ever work for anyone?" territory 
- My build uses aarch64, armv8 and or1k, and while I fixed arm-none-eabi and bpf too, those changes are untested
> fix usage of multiple toolchains

- config/functions
meson requires setting the linker via c_ld/cpp_ld.
This now links meson based package builds with the chosen DEFAULT_LINKER.
> meson: use chosen linker

- packages/linux/package.mk
- linux: update to 6.12.17
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.16
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.17
6.12.16 - 225 patches
6.12.17 - 153 patches
-
``` …
```
> linux: update to 6.12.17

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/8260af82ffa21e99c84e258a4e7b231a08bcf37b...24fb7e8829ec2939ccde113a709548c057b6d386
```
Generic.x86_64-devel-20250307091526-2090d87
Linux nuc12 6.14.0-rc5 #1 SMP Thu Mar  6 21:57:26 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:24fb7e8829ec2939ccde113a709548c057b6d386). Platform: Linux x86 64-bit
Kodi compiled 2025-03-07 by GCC 15.0.1 for Linux x86 64-bit version 6.14.0 (396800)
Running on LibreELEC (heitbaum): devel-20250307091526-2090d87 13.0, kernel: Linux x86 64-bit version 6.14.0-rc5
FFmpeg version/source: 7.1 …
```
> kodi: update to githash 24fb7e8

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
- projects/RPi/devices/RPi/linux/linux.arm.conf
- projects/RPi/devices/RPi2/linux/linux.arm.conf
- projects/RPi/devices/RPi4/linux/linux.aarch64.conf
- projects/RPi/devices/RPi5/linux/linux.aarch64.conf
This depends on #9845 as the RPi kernel switched to the latest HEVC decoder which is currently being upstreamed.
> linux (RPi): update to 6.12.17

- packages/mediacenter/kodi/patches/drmprime-filter/0002-WIP-DRMPRIME-deinterlace-filter.patch
Upstream added ``#include "utils/StringUtils.h"`` since Omega in commit:  
8939580d9d50 ("DVDVideoCodecDRMPRIME: Support YUV422 and YUV444 formats")
So drop the hunk which adds it a second time.
Link: https://github.com/xbmc/xbmc/commit/8939580d9d501ebd8adbca793f53349253678550
> kodi: drmprime-filter: Update deinterlace filter patch

- packages/graphics/nvidia/package.mk
- packages/x11/driver/xf86-video-nvidia/package.mk
This fixes the "no display" issue after the update to the 570 driver series.
see also https://forum.libreelec.tv/thread/28426-nightly-builds/?postID=198917#post198917
Runtime tested with Generic Legacy and a RTX4060 card
> nvidia: install missing drm module and GSP firmware files

- projects/Generic/devices/x11/filesystem/etc/X11/xorg-i915.conf
Default dri2 was removed fro…m mesa
Fix Kodi failing to initialize on intel HW using Generic-legacy.
If there are still issues mesa has to be build with "legacy-x11=dri2"
> xorg-i915.conf: set "option DRI 3"

- projects/Generic/options
The nvidia driver and it's firmware files need a lot of space, 512MB is soon going to be too small:
```
443M	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.img.gz
4.0K	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.img.gz.sha256
40M	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.kernel
446M	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.ova
4.0K	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.ova.sha256
404M	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.system
444M	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.tar
4.0K	LibreELEC-Generic-legacy.x86_64-13.0-devel-20250309141523-a80dd47.tar.sha256
```
> Generic: use a minimum SYSTEM_SIZE of 1GB

- packages/mediacenter/kodi-binary-addons/audiodecoder.sidplay/package.mk
There was a crash reported in the [forum](https://forum.libreelec.tv/thread/29563-rpi-sidplay-decoder-simply-refuses-to-work) and @chewitt's log shows a link error.
Fix the link error by using default cmake module search.
Updating to hash because there is no Piers tag.
PS: Looks like a long standing error: https://github.com/xbmc/audiodecoder.sidplay/issues/15#issuecomment-503340003
> audiodecoder.sidplay: fix linking / update addon (22.0.0.1)

- packages/mediacenter/kodi-binary-addons/audiodecoder.sidplay/package.mk
Backport of #9855
There was a crash reported in the [forum](https://forum.libreelec.tv/thread/29563-rpi-sidplay-decoder-simply-refuses-to-work) and @chewitt's log shows a link error.
Fix the link error by using default cmake module search.
PS: Looks like a long standing error: https://github.com/xbmc/audiodecoder.sidplay/issues/15#issuecomment-503340003
> audiodecoder.sidplay: fix linking / update addon (2)

- packages/lang/gcc/patches/gcc-14.2.0-arm--fix-signedness-of-vld1q-intrinsic-parms.patch
- required by: aom-3.12.0
- https://aomedia.issues.chromium.org/issues/397711740
> gcc: 14.2.0: arm: Fix signedness of vld1q intrinsic parms

- packages/textproc/libxslt/package.mk
https://github.com/GNOME/libxslt/blob/master/NEWS
The non-standard EXSLT crypto extensions and support for dynamically loaded plugins are now disabled by default. These features can be enabled by passing --with-crypto or --with-plugins to configure. In a future release, these features will be removed.
Debug output and the debugger are disabled by default and can be enabled by passing --with-debug or --with-debugger.
was identified as unnecessary upon review of incorrect pkgconfig file generation https://gitlab.gnome.org/GNOME/libxslt/-/issues/136
> libxslt: update build options aligning with upstream

- packages/mediacenter/kodi/package.mk
- packages/multimedia/ffmpeg/package.mk
- packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
- tools/ffmpeg/gen-patches.sh
- [ffmpeg: update to 7.1.](https://github.com/LibreELEC/LibreELEC.tv/commit/533c84ea28ade4bd7147168efae1fc149ad5ceee)
- [kodi: update to githash 5a5daca](https://github.com/LibreELEC/LibreELEC.tv/commit/9731689f286f8675ca37529850d65122d9891166)
Kicked off build testing on other platforms.
Unsure if ffmpeg patches need to be updated.
```
Generic.x86_64-devel-20250316121316-8687ed7
Linux nuc12 6.14.0-rc6 #1 SMP Sun Mar 16 04:26:15 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:5a5daca6f60e1de5929e8635a6766c91ff4c418e). Platform: Linux x86 64-bit
Kodi compiled 2025-03-16 by GCC 15.0.1 for Linux x86 64-bit version 6.14.0 (396800)
Running on LibreELEC (heitbaum): devel-20250316121316-8687ed7 13.0, kernel: Linux x86 64-bit version …
```
> Update Kodi and ffmpeg to 7.1.1

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/docker/moby/patches/moby-001-user-addon-storage-location.patch
- packages/addons/addon-depends/podman/conmon/package.mk
- packages/addons/addon-depends/podman/libassuan/package.mk
- packages/addons/addon-depends/podman/netavark/package.mk
- packages/addons/addon-depends/podman/podman-bin/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/package.mk
- packages/addons/service/podman/package.mk
- podman: update to 5.4.1 and addon (4)
- conmon: update to 2.1.13
- libassuan: update to 3.0.2
- podman-bin: update to 5.4.1
- netavark: update to 1.14.1
- docker: update to 28.0.2 and addon (8)
- runc: update to 1.2.6
- containerd: update to 2.0.4
- moby: update to 28.0.2
- cli: update to 28.0.2
> Docker update to 28.0.2 and podman update to 5.4.1

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/5a5daca6f60e1de5929e8635a6766c91ff4c418e...32993285404dd1dcb69e2655b7ceb8cc5f323c22
```
Generic.x86_64-devel-20250322114817-f7500e0
Linux nuc12 6.14.0-rc7 #1 SMP Sat Mar 22 08:50:20 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:32993285404dd1dcb69e2655b7ceb8cc5f323c22). Platform: Linux x86 64-bit
Kodi compiled 2025-03-22 by GCC 15.0.1 for Linux x86 64-bit version 6.14.0 (396800)
Running on LibreELEC (heitbaum): devel-20250322114817-f7500e0 13.0, kernel: Linux x86 64-bit version 6.14.0-rc7 …
```
> kodi: update to githash 3299328

- packages/linux/package.mk
- linux: update to 6.12.20
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.18
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.19
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.20
6.12.18 - 148 patches
6.12.19 - 269 patches
6.12.20 - 231 patches
-
```
PROJECT=Allwinner …
```
> linux: update to 6.12.20

- packages/sysutils/tz/package.mk
log: https://github.com/eggert/tz/compare/2024b...2025b
> [le12] tz: update to 2025b

- packages/addons/service/argononecontrol/package.mk
During the continuous development of the ArgonForty Device Configuration add-on I was asked several times, like: “Why is the addon not installable out-of-the-box”. I think now it is in a state where that is possible...
The addon is required for the RPi4/5 Argon ONE cases. It provides the fan control and ensures that the shutdown works properly and power button events working as well. Additional it enables the IR receiver and provides support for the Argon Remote.
https://github.com/HungerHa/libreelec_package_argonforty-device
It would be nice, if it could be part of the LibreELEC addon repo.
> argononecontrol: add package (support for the Argon ONE cases)

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/32993285404dd1dcb69e2655b7ceb8cc5f323c22...c45a28aef18e30c9e289b378ed9ece6b692b97a7
```
Generic.x86_64-devel-20250329124642-bf12261
Linux nuc12 6.14.0 #1 SMP Sat Mar 29 12:55:10 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:c45a28aef18e30c9e289b378ed9ece6b692b97a7). Platform: Linux x86 64-bit
Kodi compiled 2025-03-29 by GCC 15.0.1 for Linux x86 64-bit version 6.14.0 (396800)
Running on LibreELEC (heitbaum): devel-20250329124642-bf12261 13.0, kernel: Linux x86 64-bit version 6.14.0 …
```
> kodi: update to githash c45a28a

- packages/network/bluez/package.mk
Bluez 5.81 accidentally reverted an earlier change causing some dbus issues. The upstream 5.81 release has been retagged to include a fix but 5.82 is now available with more fixes, so let's use that instead.
> bluez: update to 5.82

- packages/linux/package.mk
- packages/linux/patches/raspberrypi/linux-001-backport-pr6741-rpi5-sand-fixes.patch
- packages/tools/bcm2835-bootloader/package.mk
- packages/tools/rpi-eeprom/package.mk
Runtime tested on RPi5, zooming HEVC videos works fine now.
> [le12] linux (RPi): backport RPI5 HEVC zoom fix

- packages/multimedia/media-driver/package.mk
```
Generic.x86_64-devel-20250407115000-04f3f9f
Linux nuc12 6.14.0 #1 SMP Mon Apr  7 01:14:59 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:b01f67dbe312f7f0b06d29addce2b296d12c880f). Platform: Linux x86 64-bit
Kodi compiled 2025-04-06 by GCC 15.0.1 for Linux x86 64-bit version 6.15.0 (397056)
Running on LibreELEC (heitbaum): devel-20250407115000-04f3f9f 13.0, kernel: Linux x86 64-bit version 6.14.0
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0094.2024.0806.1458 08/06/2024 …
```
> media-driver: update to 25.2.0

- packages/graphics/mesa/package.mk
- fixes #9945
```
…
Video
Codecs                       : vc1dec h264dec h264enc h265dec h265enc av1dec av1enc vp9dec
APIs                         : va xa
…
User defined options
Cross files                  : /build/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/mesa-25.0.3/.x86_64-libreelec-linux-gnu/meson.conf
bindir                       : /usr/bin
build-tests                  : false
buildtype                    : plain
draw-use-llvm                : false
egl                          : enabled
gallium-drivers              : crocus,i915,iris,r300,r600,radeonsi,svga,virgl
gallium-extra-hud            : false
gallium-nine                 : false
gallium-opencl               : disabled
gallium-rusticl              : false
gallium-va                   : enabled
gallium-vdpau …
```
> mesa: add av1dec,av1enc,vp9dec for r600 and radeonsi

- packages/tools/u-boot/package.mk
- u-boot: update to 2025.04
Notes:
- Qualcomm still does not build No valid dtbs found
All builds 2025.04 successful apart from afore mentioned Qualcomm
```
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-orangepi-win.img.gz
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-orangepi-win.img.gz.sha256
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64.img.gz
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64.img.gz.sha256
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64-lts.img.gz
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64-lts.img.gz.sha256
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64-plus.img.gz
LibreELEC-A64.aarch64-13.0-devel-20250408180000-c603035-pine64-plus.img.gz.sha256 …
```
> u-boot: update to 2025.04

- packages/addons/service/argononecontrol/package.mk
The upgrade to current version. Please do not overlook the waiting backport for LE12 in the queue. #9663
> argononecontrol: update to 1.1.9 and addon (0)

- packages/addons/service/argononecontrol/package.mk
Backport of #9662
During the continuous development of the Argon ONE Control (formerly known as: ArgonForty Device Configuration) add-on I was asked several times, like: “Why is the addon not installable out-of-the-box”. I think now it is in a state where that is possible...
The addon is required for the RPi4/5 Argon ONE cases. It provides the fan control and ensures that the shutdown works properly and power button events working as well. Additional it enables the IR receiver and provides support for the Argon Remote.
https://github.com/HungerHa/libreelec_addon_argononecontrol
It would be nice, if it could be part of the LibreELEC addon repo.
> [le12] argononecontrol: add package (backport of PR9662)

- packages/addons/service/hyperion/patches/hyperion-0002-build-with-cmake-4.0.0.patch
- packages/audio/soxr/patches/soxr-0001-build-with-cmake-4.0.0.patch
- packages/emulation/rcheevos/source/CMakeLists.txt
- packages/mediacenter/p8-platform/patches/p8-platform-03-build-with-cmake-4.0.0.patch
Patches and fix for downstream unmaintained packages. These have no upstream.
- p8-platform: allow build with cmake-4.0.0
- soxr: allow build with cmake-4.0.0
- hyperion: allow build with cmake-4.0.0
- rcheevos: fix build with cmake-4.0.0
future PRs will complete the build fixes for #9916 
- upstreamed patches accepted but not in the current release
- hopefully package update containing the submitted upstream pacthes
- and lastly patches yet to be accepted
> CMake patches and fix for unmaintained packages to build with cmake 4.0.0

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/b01f67dbe312f7f0b06d29addce2b296d12c880f...6ba797d60160797af61d5a8a9314a96c21943484
Includes fix for:
- https://github.com/xbmc/xbmc/issues/26621
```
Generic.x86_64-devel-20250412155650-1351f16
Linux nuc12 6.14.1 #1 SMP Sat Apr 12 16:03:30 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:6ba797d60160797af61d5a8a9314a96c21943484). Platform: Linux x86 64-bit
Kodi compiled 2025-04-12 by GCC 15.0.1 for Linux x86 64-bit version 6.14.1 (396801)
Running on LibreELEC (heitbaum): devel-20250412155650-1351f16 13.0, kernel: Linux x86 64-bit version 6.14.1
[    0.000000] DMI: Intel(R) Client Systems …
```
> kodi: update to githash 6ba797d

- packages/graphics/glu/package.mk
- packages/graphics/mesa/package.mk
- packages/mediacenter/kodi/package.mk
- projects/Generic/devices/Generic-gl/options
- projects/Generic/filesystem/usr/share/bootloader/canupdate.sh
OpenGL has several advantages over current OpenGL ES Generic images:
1. HQ upscaler improvements
2. Dithering support
3. Future Retroplayer OpenGL shader support
4. Colour management support
HDR passthrough would be functional after https://github.com/xbmc/xbmc/pull/26406 is merged.
> Generic: switch to OpenGL

- packages/python/graphics/Pillow/package.mk
Pillow 11.2.0 was pulled upstream due to a packaging issue and has been replaced by 11.2.1.
> Pillow: bump to 11.2.1

- packages/emulation/libretro-vecx/package.mk
This fixes compile error with Generic-gl.
> libretro-vecx: update to githash 841229 and add an option USE_GLVND

- packages/addons/addon-depends/docker/tini/patches/tini-233-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/hidapi/patches/hidapi-663-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/libid3tag/patches/libid3tag-15-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/snapcast-depends/aixlog/patches/aixlog-19-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/system-tools-depends/encfs/package.mk
- packages/addons/addon-depends/system-tools-depends/encfs/patches/encfs-677-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/system-tools-depends/encfs/patches/encfs-863-build-with-cmake-4.0.0.patch
- packages/addons/addon-depends/ttyd-depends/libwebsockets/patches/libwebsockets-0001-build-with-cmake-4.0.0.patch
- packages/addons/service/oscam/patches/oscam-0900-build-with-cmake-4.0.0.patch
- packages/addons/service/tigervnc/patches/tigervnc-1366-build-with-cmake-4.0.0.patch
- packages/audio/ldacBT/patches/ldacBT-1-build-with-cmake-4.0.0.patch
- packages/audio/libogg/patches/libogg-0001-build-with-cmake-4.0.0.patch
- packages/audio/libsndfile/patches/libsndfile-1073-build-with-cmake-4.0.0.patch
- packages/compress/lzo/patches/lzo-0001-build-with-cmake-4.0.0.patch
- packages/devel/json-c/patches/json-c-888-build-with-cmake-4.0.0.patch
- packages/devel/libevent/patches/libevent-0001-build-with-cmake-4.0.0.patch
- packages/devel/libevent/patches/libevent-0002-build-with-cmake-4.0.0.patch
- packages/devel/libevent/patches/libevent-0003-build-with-cmake-4.0.0.patch
- packages/devel/libevent/patches/libevent-0004-build-with-cmake-4.0.0.patch
- packages/devel/libftdi1/patches/libftdi-0001-build-with-cmake-4.0.0.patch
- packages/devel/rapidjson/patches/rapidjson-0004-build-with-cmake-4.0.0.patch
- packages/graphics/libde265/patches/libde265-471-build-with-cmake-4.0.0.patch
- packages/multimedia/gmmlib/patches/gmmlib-130-build-with-cmake-4.0.0.patch
- packages/multimedia/media-driver/patches/media-driver-1919-build-with-cmake-4.0.0.patch
Patches and fix for packages.
This PR completes the majority of the fixes for #9916 
- upstreamed patches accepted but not in the current release
- libftdi1: patches since 1.5 allowing build with cmake-4.0.0
- libwebsockets: allow build with cmake-4.0.0
- tigervnc: allow build with cmake-4.0.0
- libsndfile: allow build with cmake-4.0.0
- hidapi: allow build with cmake-4.0.0
- submitted upstream patches
- oscam: allow build with cmake-4.0.0
- json-c: allow build with cmake-4.0.0
- aixlog: allow build with cmake-4.0.0
- libde265: allow build with cmake-4.0.0
- libid3tag: allow build with cmake-4.0.0
- tini: allow build with cmake-4.0.0
- media-driver: allow build with cmake-4.0.0
- gmmlib: allow build with cmake-4.0.0
- libogg: allow build with cmake-4.0.0
- rapidjson: allow build with …
> CMake patches and fix for packages (group 2 ) to build with cmake 4.0.0

- packages/mediacenter/kodi/package.mk
- Log:
- https://github.com/xbmc/xbmc/compare/6ba797d60160797af61d5a8a9314a96c21943484...230e3b401749690aeedfe2471bbbe876cc53fff2
- fixes #9965 
```
Generic.x86_64-devel-20250417132648-16b36c7
Linux nuc12 6.14.2 #1 SMP Thu Apr 17 13:11:05 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:230e3b401749690aeedfe2471bbbe876cc53fff2). Platform: Linux x86 64-bit
Kodi compiled 2025-04-17 by GCC 15.0.1 for Linux x86 64-bit version 6.14.2 (396802)
Running on LibreELEC (heitbaum): devel-20250417132648-16b36c7 13.0, kernel: Linux x86 64-bit version 6.14.2
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS …
```
> kodi: update to githash 230e3b4

- packages/addons/service/mariadb/patches/mariadb-246-build-with-cmake-4.0.0.patch
- packages/devel/cmake/package.mk
~This is a draft tracking pr with all the required patches/changes (except hyperhdr) to build LE and addons with cmake-4.0.0 on x86_64. Some of these patches will be separated out to be merged directly (especially the local patches for the unmaintained / local fixes.)~
~The build is wip to test build on other targets.~
~It is expected that some of these patches will be incorporated in package updates, depending on upstream release schedules.~
- Fixes #9916
- first group of changes #9937
- Second group of change #9964
> CMake update to 4.x

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/230e3b401749690aeedfe2471bbbe876cc53fff2...13574dbbc2a902f1308abe83f27587274fc351c1
```
Generic.x86_64-devel-20250420132323-006b71c
Linux nuc12 6.14.2 #1 SMP Sun Apr 20 12:16:14 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:13574dbbc2a902f1308abe83f27587274fc351c1). Platform: Linux x86 64-bit
Kodi compiled 2025-04-20 by GCC 15.0.1 for Linux x86 64-bit version 6.14.2 (396802)
Running on LibreELEC (heitbaum): devel-20250420132323-006b71c 13.0, kernel: Linux x86 64-bit version 6.14.2 …
```
> kodi: update to githash 13574db

- packages/addons/addon-depends/chrome-depends/chrome-libxkbcommon/package.mk
- packages/addons/addon-depends/chrome-depends/cups/package.mk
- packages/addons/addon-depends/chrome-depends/gtk3/package.mk
- packages/addons/addon-depends/chrome-depends/libXft/package.mk
- packages/addons/browser/chrome/package.mk
Fix build issue
```
<<< chrome-libxkbcommon:target seq 205 <<<
UNPACK      libxkbcommon
UNPACK      chrome-libxkbcommon
tar: /build/sources/libxkbcommon/libxkbcommon-1.8.1.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
FAILURE: scripts/unpack chrome-libxkbcommon during unpack (package.mk)
```
- chrome: update to 135.0.7049.95 and addon (1)
- chrome-libxkbcommon: fix source tar file reference
- libXft: update to 2.3.9 and meson
- gtk3: update to 3.24.49 and PKG_URL
- cups: update to 2.4.12
> chrome: update to 135.0.7049.95 and addon (1) And fix buid

- packages/multimedia/media-driver/package.mk
```
Generic.x86_64-devel-20250422114319-4b49e30
Linux nuc12 6.14.2 #1 SMP Mon Apr 21 07:04:50 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:13574dbbc2a902f1308abe83f27587274fc351c1). Platform: Linux x86 64-bit
Kodi compiled 2025-04-21 by GCC 15.0.1 for Linux x86 64-bit version 6.14.2 (396802)
Running on LibreELEC (heitbaum): devel-20250422114319-4b49e30 13.0, kernel: Linux x86 64-bit version 6.14.2
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0094.2024.0806.1458 08/06/2024 …
```
> media-driver: update to 25.2.1

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/13574dbbc2a902f1308abe83f27587274fc351c1...e30d10f4204d8301d8d9d62730edfe6f51344e4d
```
Generic.x86_64-devel-20250423133349-a58ca62
Linux nuc12 6.14.2 #1 SMP Mon Apr 21 07:04:50 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:e30d10f4204d8301d8d9d62730edfe6f51344e4d). Platform: Linux x86 64-bit
Kodi compiled 2025-04-23 by GCC 15.0.1 for Linux x86 64-bit version 6.14.2 (396802)
Running on LibreELEC (heitbaum): devel-20250423133349-a58ca62 13.0, kernel: Linux x86 64-bit version 6.14.2 …
```
> kodi: update to githash e30d10f

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/e30d10f4204d8301d8d9d62730edfe6f51344e4d...49b8882536fe1909c86a1cd8d67b19e32cddfdc3
- includes migration of rapidjson to nlohmann-json
- [CVariant] Replace rapidjson with nlohmann-json
- https://github.com/xbmc/xbmc/pull/26612
Places when rapidjson is still used in LE:
- https://github.com/rbuehlma/pvr.zattoo/issues/224
- https://github.com/flubshi/pvr.waipu/issues/418
- https://github.com/rbuehlma/pvr.teleboy/issues/99
- https://github.com/kodi-pvr/pvr.plutotv/issues/99
- https://github.com/xbmc/inputstream.adaptive/issues/1835
> kodi: update to githash 49b8882

- packages/linux/package.mk
- linux: update to 6.12.25
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.24
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.12.25
6.12.24 - 392 patches
6.12.25 - 223 patches
-
``` …
```
> linux: update to 6.12.25

- packages/addons/addon-depends/docker/cli/package.mk
- packages/addons/addon-depends/docker/containerd/package.mk
- packages/addons/addon-depends/docker/moby/package.mk
- packages/addons/addon-depends/runc/package.mk
- packages/addons/service/docker/package.mk
- docker: update to 28.1.1 and addon (1)
- cli: update to 28.1.1
- moby: update to 28.1.1
- containerd: update to 2.0.5
- runc: update to 1.3.0
> docker: update to 28.1.1 and addon (1)

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/49b8882536fe1909c86a1cd8d67b19e32cddfdc3...c55eee6017203fdcedfa8411b5b40ae0b0c7e3e4
- remove RapidJSON remanents
- Includes fix - https://github.com/xbmc/xbmc/pull/26705
```
Generic.x86_64-devel-20250430234304-750969d
Linux nuc12 6.14.2 #1 SMP Wed Apr 30 09:53:25 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:c55eee6017203fdcedfa8411b5b40ae0b0c7e3e4). Platform: Linux x86 64-bit
Kodi compiled 2025-04-30 by GCC 15.1.0 for Linux x86 64-bit version 6.14.2 (396802)
Running on LibreELEC (heitbaum): devel-20250430234304-750969d 13.0, kernel: Linux x86 64-bit version 6.14.2
[    0.000000] DMI: …
```
> kodi: update to githash c55eee6

- packages/graphics/mesa/package.mk
The bugfix release 25.0.5 is now available.
The next bugfix release is due in two weeks, on May 14th.
Cheers,
Eric
---
Connor Abbott (1):
tu: Fix flushing when using a staging buffer for copies
Danylo Piliaiev (1):
tu,freedreno: Don't fallback to LINEAR with DRM_FORMAT_MOD_QCOM_COMPRESSED
radv: Use radv_format_to_pipe_format instead of vk_format_to_pipe_format
Dmitry Baryshkov (1):
meson: disable SIMD blake optimisations on x32 host
Ella Stanforth (1):
v3d/compiler: Fixup output types for all 8 outputs
Eric Engestrom (10):
docs: add sha sum for 25.0.4
.pick_status.json: Update to 5f3a3740dcc6d243f2ef14138fb1c09bcbb9b5fd
pick-ui: make `Backport-to: 25.0` …
> mesa: update to 25.0.5

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
includes:
- https://github.com/xbmc/inputstream.adaptive/pull/1844
- https://github.com/xbmc/inputstream.adaptive/issues/1846
- https://github.com/xbmc/inputstream.adaptive/tree/Nexus
> [le11] inputstream.adaptive: update to githash dc604ff and addon (2)

- packages/x11/other/fluxbox/patches/fluxbox-80-fix-gettext-build.patch
- https://github.com/fluxbox/fluxbox/pull/80
fixes
```
BUILD      fluxbox (target)
TOOLCHAIN      autotools
AUTORECONF      fluxbox
autoreconf: export WARNINGS=
autoreconf: Entering directory '/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/fluxbox-1.3.7'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/aclocal -I /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/aclocal -I /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/aclocal --force -I m4
configure.ac:188: warning: …
```
> fluxbox: allow build with gettext-0.24.1

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/c55eee6017203fdcedfa8411b5b40ae0b0c7e3e4...264adc1
24d4770ffef0e3de5b11478077cfd4152
- ~https://github.com/xbmc/xbmc/compare/c55eee6017203fdcedfa8411b5b40ae0b0c7e3e4...cfbd42ac9513c54d10cc4e24bccac487e248b57c~
- ~revert of~
- ~https://github.com/xbmc/xbmc/pull/26738/commits/b1fe4d815a8d2d1fb743a69576919bff737a433f~
- ~https://github.com/xbmc/xbmc/pull/26738/commits/f902ec5c5956fcc293aea7492ed1c30b6164d7ec~
- ~See https://github.com/xbmc/xbmc/pull/26738#issue comment-2850946071~
- ~https://github.com/xbmc/xbmc/pull/26738~~
```
Generic.x86_64-devel-20250505131610-4e7fc89
Linux nuc12 6.14.5 #1 SMP Mon May  5 04:55:47 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:cfbd42ac9513c54d10cc4e24bccac487e248b57c). …
```
> kodi: update to githash 264adc1

- packages/graphics/mesa/package.mk
- https://docs.mesa3d.org/relnotes/25.1.0.html
```
Generic.x86_64-devel-20250508005225-fba6825
Linux nuc12 6.14.5 #1 SMP Thu May  8 00:57:55 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:264adc124d4770ffef0e3de5b11478077cfd4152). Platform: Linux x86 64-bit
Kodi compiled 2025-05-08 by GCC 15.1.0 for Linux x86 64-bit version 6.14.5 (396805)
Running on LibreELEC (heitbaum): devel-20250508005225-fba6825 13.0, kernel: Linux x86 64-bit version 6.14.5
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0094.2024.0806.1458 08/06/2024 …
```
> mesa: update to 25.1.0

- packages/graphics/mesa/package.mk
- packages/lang/llvm/package.mk
- llvm: panfrost requires libclc since 25.1.0
> mesa: panfrost requires libclc since 25.1.0

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- https://blog.rust-lang.org/2025/05/15/Rust-1.87.0/
- rust: update to 1.87.0
- rustc-snapshot: update to 1.87.0
- rust-std-snapshot: update to 1.87.0
- cargo-snapshot: update to 1.87.0
> rust: update to 1.87.0

- packages/graphics/spirv-llvm-translator/package.mk
- packages/lang/llvm/package.mk
Blocked until https://releases.rs/docs/1.87.0/ which supports llvm 20.1
- #10062
> llvm update to 20.1.y

- packages/databases/mariadb-connector-c/patches/mariadb-connector-c-0001-fix-build-with-gcc-15.patch
- packages/network/libtirpc/patches/libtirpc-0001-fix-build-with-gcc-15.patch
- packages/network/libtirpc/patches/libtirpc-0002-fix-build-with-gcc-15.patch
- packages/sysutils/parted/patches/parted-0001-fix-do_version-declaration.patch
- packages/tools/grub/patches/grub-0001-fix-build-with-gcc-15.patch
- packages/x11/driver/xf86-video-nvidia/patches/nvidia-kernel-ccflags-y-fix-linux-6.14.patch
Group of patches required for gcc-15 build of LE
- xf86-video-nvidia: allow build with 6.14.1 as well as gcc-15
- https://github.com/NVIDIA/open-gpu-kernel-modules/pull/841
- https://github.com/NVIDIA/open-gpu-kernel-modules/issues/814
- grub: patch grub gnulib to allow build with gcc-15
- mariadb-connector-c: fix build with gcc-15
- parted: gcc-15 upstream fix
- libtirpc: gcc-15 upstream fixes
- part of #9981 (#9705)
- ~update or patch is required~
- gcc update to 15.1 itself
> Patches required for LE to compile with gcc-15

- packages/graphics/mesa/package.mk
- tools/docker/noble/Dockerfile
This PR prepares for reusable mesa-host tools
- #10049 
- tools/docker/noble/Dockerfile: add upx-ucl to allow binary compression of mesa:host tools
- mesa: for host builds always build panfrost_compile
- mesa: host builds with shared-llvm=disabled
> mesa: simplify host build logic

- packages/mediacenter/LibreELEC-settings/package.mk
Bump to include a fix for `/etc/os-release` unbranded variable names after the LEIoT changes were merged.
> LibreELEC-settings: bump to fix unbranded variable names

- packages/addons/addon-depends/rpi-tools-depends/lg-gpio/patches/lg-gpio-36-define-and-use-type-safe-callbacks.patch
define callback argument lists and use type-safe callbacks
- https://github.com/joan2937/lg/pull/39
- https://github.com/joan2937/lg/issues/36
> lg-gpio: fix gcc-15 build

- packages/rust/rust/targets/aarch64-libreelec-linux-gnu.json
ref:
- https://github.com/llvm/llvm-project/commit/c9f27275c1330a325661bdf14fb3bc444a5e3648
> rust: fix aarch64 build against llvm-20.1

- packages/network/wireguard-tools/package.mk
log: https://github.com/WireGuard/wireguard-tools/compare/v1.0.20210914...v1.0.20250521
> wireguard-tools: update to 1.0.20250521

- packages/graphics/mesa/package.mk
Commit 9d2001f14ec7 ("Add Generic-gl device") introduced a subtle error in the glvnd enablement logic that lead to the Generic-Legacy image being built without glvnd which breaks nvidia support.
Unlike most programming languages "||" and "&&" have the same precedence in shell and "A || B && C" get evaluated as "(A || B) && C" instead of the intended "A || (B && C)".
Fix this by moving the "AND not-X11" check into the "GL" test and adjust formatting to make the intention clear.
ping @smp79
> mesa: fix logic error in glvnd selection

- packages/addons/service/argononecontrol/package.mk
Bump to current version: translations for Korean, Chinese (Simplified Han script) have been added.
> [LE12] argononecontrol: update to 1.1.12 and addon (0)

- packages/devel/flex/package.mk
- fixes https://github.com/LibreELEC/LibreELEC.tv/pull/10083#issuecomment-2907804315
- Need to revisit the flex:target build and best use the stage1flex binary from host, instead to building it in target.
- #10083
> flex: revert chnage to use TARGET_CC

- packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch
- ref: https://github.com/libretro/scummvm/issues/81#issuecomment-2910940105
> fixed by [e566a64](https://github.com/libretro/scummvm/commit/e566a6432fd1951417bf78280cc7c741957fc419)
I got round to checking CI/CD and it was still failing. I have had to reverse the lookup as findstring was not finding platform in armv7.
```
Executing (target): make all platform=armv7a-libreelec-linux-gnueabihf
Platform is armv7a-libreelec-linux-gnueabihf 32bit
```
fix should be
```diff
diff --git a/packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch b/packages/emulation/libretro-scummvm/patches/0003-libretr
o-fix-armv7-GCC-15.1-internal-compiler-error.patch
index 29728dfcb3..360ca9d8d6 100644
--- …
```
> libretro-scummvm: fix findstring armv7 check

- packages/sysutils/busybox/scripts/sudo
This unbrands the sudo warning and greatly simplifies the current warning text.
> busybox: unbrand and simplify the sudo warning

- packages/devel/flex/package.mk
- packages/devel/flex/patches/flex-0001-use-flex-host-for-target-cross-compile.patch
The compile logic whilst building a CROSS compiled flex could be improved. Given that we have already built flex:host and the necessary stage1flex, just use it. Using the --disable-bootstrap logic in the make file which would normally call sed, replace the sed call with the call to be previously built stage1flex. Both the patch and the update to package.mk are required.
- #10083
- #10091 
- https://github.com/westes/flex/pull/674
> flex: use flex:host stage1flex when building scan.c from scan.l

- packages/mediacenter/kodi/package.mk
- packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
Log:
- https://github.com/xbmc/xbmc/compare/264adc124d4770ffef0e3de5b11478077cfd4152...de5db9200b6e42972db6ebdd4b4c908f23179cac
- I got around to testing why Kodi was crashing on launch when bumping it. If I revert https://github.com/xbmc/xbmc/pull/26744 I was able to run a Kodi with 26746 and 26751. So pretty sure it is isolated to that PR. When going forward, I have had to revert the 4 PRs so as to revert 26744.
With this PR as-is with the reverts, My Kodi is running fine.
im getting the crash here
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/kodi/kodi.bin --standalone -fs --audio-backend=alsa+pulseaudio'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f060c542019 in ?? () from /usr/lib/libc.so.6
[Current …
```
> kodi: update to githash de5db92

- packages/graphics/mesa/package.mk
Ann: https://lists.freedesktop.org/archives/mesa-dev/2025-June/226512.html
```
Generic.x86_64-devel-20250604225053-f3b048c
Linux nuc12 6.15.0 #1 SMP Wed Jun  4 06:18:28 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:de5db9200b6e42972db6ebdd4b4c908f23179cac). Platform: Linux x86 64-bit
Kodi compiled 2025-06-04 by GCC 15.1.0 for Linux x86 64-bit version 6.15.0 (397056)
Running on LibreELEC (heitbaum): devel-20250604225053-f3b048c 13.0, kernel: Linux x86 64-bit version 6.15.0
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0096.2025.0115.1051 01/15/2025
CApplication::CreateGUI - trying to init gbm …
```
> mesa: update to 25.1.2

- packages/compress/xz/package.mk
- packages/lang/Python3/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
- packages/mediacenter/kodi-binary-addons/vfs.libarchive/package.mk
The follow changes allow the xz package to be moved out of sysroot
- The pre_configure_target for vfs.libarchive and pvr.iptvsimple allow xz to be linked in from outside the sysroot
xz:host is actually not used. 
These are the changes to the packages:
- squashfs-tools: drop xz support
- all images are currently zstd
- toolchain: drop xz:host DEPEND
- linux: drop xz:host DEPEND
- Python3: drop xz:host DEPEND
xz target changes:
- vfs.libarchive: use non sysroot xz
- pvr.iptvsimple: use non sysroot xz
- inputstream.ffmpegdirect: does not use xz
xz: drop host build
This PR maintains xz in the LE image: that being:
- `image/system/usr/lib/python3.11/lib-dynload/_lzma.so`
> move xz (lzma) support out of sysroot

- packages/mediacenter/kodi-binary-addons/game.shader.presets/package.mk
Add shader presets add-on needed by recently merged https://github.com/xbmc/xbmc/pull/26435.
> kodi-binary-addons: add game.shader.presets add-on

- packages/mediacenter/kodi/package.mk
- projects/Allwinner/patches/kodi/000-temp-revert-fences.patch
- projects/Amlogic/patches/kodi/000-temp-revert-fences.patch
- projects/RPi/patches/kodi/000-temp-revert-fences.patch
- projects/Rockchip/patches/kodi/000-temp-revert-fences.patch
The revert-fences patch needed a rebase after the recently merged code reformatting PR https://github.com/xbmc/xbmc/pull/26838
> kodi: update to ce89e7d

- packages/graphics/mesa/package.mk
The following options are now deprecated:
- DEPRECATION: Option 'gallium-nine' is deprecated
- was false and defaults to false
- DEPRECATION: Option 'gallium-opencl' is deprecated
- was false and defaults to false
- DEPRECATION: Option 'shared-glapi' is deprecated
- option now does nothing
- DEPRECATION: Option 'osmesa' is deprecated
- option now does nothing
- no change at this time:
- DEPRECATION: Option 'gallium-xa' is deprecated
- this deprecated option has been left as-is until it is removed by upstream. this is expected in mesa 25.2 is set to true for vmware otherwise was false and defaults to false
> mesa: drop deprecated options

- distributions/LibreELEC/options
- packages/audio/espeak-ng/package.mk
- packages/audio/espeak-ng/patches/espeak-ng-0001-allow-build-of-intonations.patch
- packages/audio/espeak-ng/patches/espeak-ng-0002-find-and-link-pthread.patch
- needed fix: https://github.com/espeak-ng/espeak-ng/issues/2048, so patch the PATH_MAX to 256
- Now included https://github.com/espeak-ng/espeak-ng/pull/2220
cross_compiling check fails because we use a different host name from host so patch out the check and manually set build of intonations and tests
```
$ du -sk build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/espeak-ng-9fb8ed27d5748cbaac336e525d3bcba21ec06d5c/
20620   build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/espeak-ng-9fb8ed27d5748cbaac336e525d3bcba21ec06d5c/
```
https://forum.libreelec.tv/thread/24881-libreelec-10-0-accessibility/?postID=200604#post200604
> espeak-ng: update to githash a06074c and use cmake

- packages/sysutils/e2fsprogs/package.mk
> e2fsprogs: remove e2mmpstatus as it is a link to dumpe2fs

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/ce89e7d9c62e800d5914d719ce5e22804d37c3b3...93eeae9b860a6f0dff4942be0e714f5d10ce2fa4
```
Generic.x86_64-devel-20250611103351-e9f28f6
Linux nuc12 6.16.0-rc1 #1 SMP Wed Jun 11 08:45:41 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:93eeae9b860a6f0dff4942be0e714f5d10ce2fa4). Platform: Linux x86 64-bit
Kodi compiled 2025-06-11 by GCC 15.1.0 for Linux x86 64-bit version 6.16.0 (397312)
Running on LibreELEC (heitbaum): devel-20250611103351-e9f28f6 13.0, kernel: Linux x86 64-bit version 6.16.0-rc1
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0096.2025.0115.1051 …
```
> kodi: update to githash 93eeae9

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.318
- vulkan-loader: update to 1.4.318
- vulkan-tools: update to 1.4.318
> Vulkan update to 1.4.318

- packages/security/openssl/cert/cacert.pem
This commit updates cacert.pem certificate bundle with mk-ca-bundle.pl script using the content of [certdata][1] associated with mozilla/gecko-dev@b8c633ab11af738f8944a5685e5c3f6c5a0a1eef,
[1]: https://github.com/mozilla/gecko-dev/blob/b8c633ab11af738f8944a5685e5c3f6c5a0a1eef/security/nss/lib/ckfw/builtins/certdata.txt?raw=true
> cacert.pem: update to 2025-06-13

- packages/web/curl/package.mk
addresses build error by not building the documents
```
ninja: error: '/build/build.LibreELEC-AMLGX.aarch64-12.80.md/build/curl-8.14.1/.aarch64-libreelec-linux-gnu/docs/libcurl/libcurl-symbols.md', needed by 'docs/libcurl/curl_easy_cleanup.3', missing and no known rule to make it
```
> curl: do not build docs

- packages/linux/package.mk
- projects/Allwinner/linux/linux.aarch64.conf
- projects/NXP/devices/iMX8/linux/linux.aarch64.conf
- projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf
- projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
- projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
- linux: update to 6.15.y
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.15.2
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.15.3
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.15.4
6.15.2 - 34 patches
6.15.3 - 780 patches
6.15.4 - 589 patches
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.15.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.15.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.15
```
PROJECT=Allwinner ARCH=aarch64 …
```
> Linux update to 6.15.4

- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rustc-snapshot: update to 1.88.0
- rust-std-snapshot: update to 1.88.0
- cargo-snapshot: update to 1.88.0
- rust: update to 1.88.0
- https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/
> rust: update to 1.88.0

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/fc1ba2754b6201f6d532651917a446b5612ab430...943fffad41d63431bcfbddc5270a7deb0a82a259
```
Generic.x86_64-devel-20250703122715-f2a3346
Linux nuc12 6.16.0-rc4 #1 SMP Thu Jul  3 08:58:44 UTC 2025 x86_64 GNU/Linux
Starting Kodi (22.0-ALPHA1 (21.90.700) Git:943fffad41d63431bcfbddc5270a7deb0a82a259). Platform: Linux x86 64-bit
Kodi compiled 2025-07-03 by GCC 15.1.0 for Linux x86 64-bit version 6.16.0 (397312)
Running on LibreELEC (heitbaum): devel-20250703122715-f2a3346 13.0, kernel: Linux x86 64-bit version 6.16.0-rc4
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0096.2025.0115.1051 …
```
> kodi: update to githash 943fffa

- packages/network/wireless-regdb/package.mk
> wireless-regdb: update to 2025.07.10

- packages/network/wireless-regdb/package.mk
Release notes:
- Backport of #10219
> [le12] wireless-regdb: update to 2025.07.10

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/c0ad652ccc8c684a5689ba058dbc29dfca8c397a...7d349752a3d518bf7442075222d7bf0127d690f3
fixes VFS addon crash
- https://github.com/xbmc/xbmc/pull/26973
> kodi: update to githash 7d34975

- packages/emulation/libretro-common/package.mk
Log:
- https://github.com/libretro/libretro-common/compare/50c15a88eb741cbe675743a282d8cc4c89421e3f...5b5a830baa6c72452c1f1d4ac3e2fdd04bfbd267
- Fixes game.libretro build since #10223
> libretro-common: update to githash 5b5a830

- packages/graphics/mesa/package.mk
The bugfix release 25.1.6 is now available.
The next bugfix release is due in two weeks, on July 30th.
Cheers,
Eric
---
Autumn Ashton (1):
radv: Fix handling of NULL pColorAttachmentLocations in vkCmdSetRenderingAttachmentLocations
panvk: Lower maxImageDimension{2D,3D,Cube} to match the HW caps
brw: Use the right width in brw_nir_apply_key for BS shaders
Calder Young (3):
iris: Fix issue with conditional dispatching
anv: Fix tiling for H.265 and VP9 video surfaces on GFX 12.5+
isl: Set tiling requirements for video surfaces
Caleb Callaway (3):
iris: re-emit push constants at compute batch start
iris: ISP invalidate at end of compute …
> mesa: update to 25.1.6

- packages/tools/bcm2835-utils/package.mk
Log:
- https://github.com/raspberrypi/utils/compare/02e3ffeee7dc8f954271fd42a3ed983567c55eb4...b7651d86d71a172b2208c67b2e360cbcb4f9d98f
> bcm2835-utils: update to githash b7651d8

- scripts/uboot_helper
Add Radxa ROCK 4SE which is officially supported by u-boot and mainline kernel.
> uboot_helper: RK3399: Add Radxa ROCK 4SE

- packages/devel/talloc/config/talloc-cache.txt
- packages/devel/talloc/package.mk
- packages/network/openssh/package.mk
- packages/network/openssh/patches/openssh-8.9p1-keydir.patch
- packages/network/samba/package.mk
- packages/network/samba/patches/samba-200-4.11-fix-ASN1-bso14164.patch
- packages/security/openssl/package.mk
Update the security components of LE12.2
- samba
- talloc (new dependency of samba)
- openssh
- openssl 
A further PR will be created potentially for other packages
> [le12.2] update security components

- distributions/LibreELEC/options
- packages/graphics/mesa-reusable/package.mk
- packages/graphics/mesa/package.mk
- packages/graphics/spirv-llvm-translator/package.mk
- packages/lang/llvm/package.mk
- packages/python/devel/ply/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rust/targets/x86_64-libreelec-linux-gnu.json
- packages/rust/rustc-snapshot/package.mk
Draft. 
- So far tested on Generic build. 
- Will need some commits squashed.
- Includes the minimal bumps to llvm, rust subsequently needs to be bumped to a minimum 1.78 to be compiled with llvm18.
- Will need to test Mesa-reusable (but expect it to work correctly) as it can/should be used by GHA actions CU/CD
> [le12.2] update mesa to 25.1

- tools/docker/jammy/Dockerfile
- tools/docker/noble/Dockerfile
- tools/docker/jammy/Dockerfile: add upx-ucl to allow binary compression
of mesa:host tools
- tools/docker/noble/Dockerfile: add upx-ucl to allow binary compression of mesa:host tools
- tools/docker/noble: update to gcc-14
- dockerfiles: update packages for aarch64 to amd64 crosscompiles
- also needed is https://github.com/LibreELEC/mesa-reusable/pull/2
> [le12.2] backport docker changes from master

- packages/lang/llvm/package.mk
These configurations (from master) allow for the panfrost host builds with llvm and rust.
- fixes https://github.com/LibreELEC/mesa-reusable/actions/runs/16512848666/job/46697942512
- llvm: build llvm-objcopy required for rust 1.84.0
- llvm: inlcude spirv for mesa panfrost builds
- llvm: panfrost requires libclc since 25.1.0
> [le12.2] include upstream updates for llvm

- tools/docker/jammy/Dockerfile
- Forward port of #10269 7f837287d77f79ff0edd676dbe05e2478ebb125d
> tools/docker/jammy/Dockerfile: add upx-ucl to allow binary compression of mesa:host tools

- packages/linux/package.mk
> [le12.2] linux: explicitly configure optional perf features

- packages/devel/glibc/package.mk
- packages/lang/gcc/patches/gcc-libsanitizer--Fix-build-with-glibc-2-42.patch
Includes the following gcc patch:
The termio structure will be removed from glibc 2.42.  It has
been deprecated since the late 80s/early 90s.
Cherry-picked from LLVM commit 59978b21ad9c65276ee8e14f26759691b8a65763
("[sanitizer_common] Remove interceptors for deprecated struct termio
(#137403)").
> glibc: update to 2.42

- packages/compress/7-zip/package.mk
- packages/debug/strace/package.mk
- packages/devel/hwdata/package.mk
- packages/security/libgcrypt/package.mk
- packages/security/openssl/package.mk
- libgcrypt: update to 1.11.2
- hwdata: update to 0.398
- 7-zip: update to 25.01
- openssl: update to 3.5.2
- strace: update to 6.16
> Package updates (for backport)

- packages/devel/readline/package.mk
This reduces image size by almost 500k (300k compressed)
```
$ ./squashfscmp.sh static shared
NEW FILE       Delta: 15           shared: 15            static: n/a          /usr/lib/libhistory.so -> libhistory.so.8
NEW FILE       Delta: 16           shared: 16            static: n/a          /usr/lib/libreadline.so -> libreadline.so.8
NEW FILE       Delta: 17           shared: 17            static: n/a          /usr/lib/libhistory.so.8 -> libhistory.so.8.3
NEW FILE       Delta: 18           shared: 18            static: n/a          /usr/lib/libreadline.so.8 -> libreadline.so.8.3
NEW FILE       Delta: 68,216       shared: 68,216        static: n/a          /usr/lib/libhistory.so.8.3
NEW FILE       Delta: 421,240      shared: 421,240       static: n/a …
```
> readline: build as a shared library instead of static

- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rustc-snapshot/package.mk
- rustc-snapshot: update to 1.89.0
- rust-std-snapshot: update to 1.89.0
- cargo-snapshot: update to 1.89.0
- rust: update to 1.89.0
- llvm: add llc and llvm-... as required by rust-1.89.0
> rust: update to 1.89.0

- licenses/PSF-2.0.txt
- packages/python/devel/distlib/package.mk
- packages/tools/qemu/package.mk
- since #10327
- Errors on Generic build
- qemu: require distlib:host
- distlib: initial package
> Python Distlib for qemu

- packages/lang/llvm/package.mk
- fixes aarch64 and arm rust target builds
> llvm: include llvm- and obj on all target llvm builds to support rust

- packages/wayland/libxkbcommon/package.mk
This finally adds a lot of missing keysyms like the long awaited XKB_KEY_XF86OK for the OK button on remotes.
This is in preparation for the Kodi PR https://github.com/xbmc/xbmc/pull/26039
> libxkbcommon: update to 1.11.0

- packages/graphics/libprojectM/package.mk
- packages/graphics/libprojectM/patches/0002-Allow-to-build-without-X11-on-Linux-and-BSD.patch
- packages/mediacenter/kodi-binary-addons/visualization.projectm/package.mk
- fixes #10306
- Attached patch enabled the EGL in SOIL2
- ref https://github.com/SpartanJ/SOIL2/commit/8eba88632323f6d65e5e68a2830a9ef60dd09d91 
- ref https://github.com/SpartanJ/SOIL2/issues/74
Includes the following commits:
- visualization.projectm: update to githash 22f1ff1 and addon (5)
- libprojectM: allow build with EGL on gbm
~~there is an additional build issue - as below - with pthread to be fixed.~~
~~[build.LibreELEC-Generic.x86_64-13.0-devel-libprojectM_target-678.log](https://github.com/user-attachments/files/21737495/build.LibreELEC-Generic.x86_64-13.0-devel-libprojectM_target-678.log)~~
> libprojectM: allow build with EGL on gbm

- packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.matrixtrails/package.mk
- needs https://github.com/xbmc/screensaver.matrixtrails/pull/87
- needs https://github.com/xbmc/screensaver.asterwave/pull/78
- ref https://github.com/SpartanJ/SOIL2/commit/8eba88632323f6d65e5e68a2830a9ef60dd09d91 
- ref https://github.com/SpartanJ/SOIL2/issues/74 
- fixes #10306
- Required changes for addons included in #10349
> screensaver: allow build with EGL on gbm

- packages/mediacenter/kodi-binary-addons/game.shader.presets/package.mk
This fixes the build error with current kodi master:
```
/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-13.0-devel/build/game.shader.presets-22.0.1-Piers/src/addon.h:44:8: error: conflicting return type specified for 'virtual void CShaderPreset::ShaderPresetWrite(preset_file, const video_shader&)'
44 |   void ShaderPresetWrite(preset_file file, const video_shader &shader) override;
|        ^~~~~~~~~~~~~~~~~
In file included from /home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-13.0-devel/build/game.shader.presets-22.0.1-Piers/src/addon.h:23: 
/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-13.0-devel/toolchain/aarch64-libreelec-linux-gnu/sysroot/usr/include/kodi/addon-instance/ShaderPreset.h:164:16: note: overridden function is …
```
> game.shader.presets: update to 22.1.0-Piers

- packages/lang/Python3/package.mk
release notes:
- https://www.python.org/downloads/release/python-3137/
> Python3: update to 3.13.7

- packages/graphics/mesa/package.mk
The bugfix release 25.1.8 is now available.
The next bugfix release is due in two weeks, on August 27th.
Cheers,
Eric
---
Alyssa Rosenzweig (2):
asahi: enable virtgpu support
agx: gate scratch opt on internal shaders
brw: Remove extra iteration on instructions from brw_opt_address_reg_load
Christian Gmeiner (2):
etnaviv: blt: Clear only requested color buffers
etnaviv: rs: Clear only requested color buffers
spirv: move cmat store barrier after the store.
David Rosca (3):
vulkan/video: Fix h265 level values
radv: Add timeout to video encode query
rusticl/ptr: Fix hidden lifetime warning
Emma Anholt (1):
i915: Avoid calling …
> mesa: update to 25.1.8

- scripts/get_archive
le13 has migrated to using curl instead of wget. this change allows for curl to be used when preparing package get on dev host, but still defaults to wget as is the standard in le12.x
> [le12.2] scripts/get_archive: allow fallback to curl if wget is missing

- packages/linux-firmware/iwlwifi-firmware/package.mk
- supports Linux 6.16
- Backport of #10386
> [le12.2] iwlwifi-firmware: update to githash 042ba27

- packages/graphics/mesa/patches/001-mr36870-gallium-extra-samplers.patch
This fixes a huge memory leak when using EGL rendering
See https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36870
Issue was initially reported on forums: https://forum.libreelec.tv/thread/29918-rpi4-prime-breaks-system-on-12-2/?postID=201675#post201675
> mesa: add patch with mesa MR 36870

- packages/network/samba/package.mk
Release notes:
- https://www.samba.org/samba/history/samba-4.22.4.html
> samba: update to 4.22.4

- packages/sysutils/systemd/hwdb.d/70-local-keyboard.hwdb
Fix the indentation problem. Also lowercase names and append some `remote`(s) for content ~ocd~ alignment.
> systemd: fix 70-local-keyboard.hwdb indentation

- packages/linux/package.mk
- projects/Rockchip/patches/linux/default/linux-1001-v4l2-rockchip.patch
- linux: update to 6.16.4
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.4
6.16.4 - 457 patches
- done
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.16
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 …
```
> linux: update to 6.16.4

- packages/compress/zstd/package.mk
This configures the zstd:target build. Disables the CLI utilities. Disables the ability to read zstd compressed files that used a version older than 0.8 to compress. Skips building the static library.
> zstd: configure target build

- packages/graphics/spirv-llvm-translator/package.mk
- packages/lang/llvm/package.mk
- packages/lang/llvm/patches/llvm-14.0.0-force-disable-cmakelist-options.patch
This fixes issue identified by rust build https://github.com/librespot-org/librespot/issues/1553. Would normally not be included in stable release, but as it is only supporting rust and mesa, may be appropriate for LE12.2.
- llvm: update to 19.1.7
- spirv-llvm-translator: update to 19.1.10
> [le12.2] llvm: update to 19.1.7

- packages/addons/service/oscam/package.mk
- packages/addons/service/pcscd/package.mk
- packages/addons/service/pcscd/source/bin/pcscd.start
- backport of #10467 
- oscam: update to 11886, include missing shared library and addon (1)
- pcscd: do not use polkit and addon (1)
> [le12.2] oscam: update to 11886, include missing shared library and addon (1)

- packages/mediacenter/kodi/package.mk
Log:
- https://github.com/xbmc/xbmc/compare/b9544fde80809913b8423b8d2dc3a1f39ff17e03...98c138dd91da0d9a0e7a111acf3add4d43cd94e6
> kodi: update to githash 98c138d

- packages/addons/service/oscam/package.mk
- backport of #10471 
- fixes https://github.com/LibreELEC/LibreELEC.tv/commit/38c127fb384598872837b07c26064200b3064a05#commitcomment-165428638
> [le12.2] oscam: fix RPATH on libpcsclite and addon (2)

- packages/linux/package.mk
- backport #10482 
- linux: update to 6.16.7
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.5
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.6
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.7
6.16.5 - 142 patches
6.16.6 - 183 patches
6.16.7 - x86/vmscape patches
- done
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.16
``` …
```
> [le12.2] linux: update to 6.16.7

- packages/audio/ldacBT/patches/ldacBT-1-build-with-cmake-4.0.0.patch
fix ldacBT patch
fixes build failure when compiling with pipewire
> fix ldacBT patch

- packages/addons/addon-depends/rsyslog-depends/librelp/package.mk
- packages/addons/addon-depends/snapcast-depends/asio/package.mk
- packages/addons/addon-depends/snapcast-depends/snapcast/package.mk
- packages/addons/service/filebrowser/package.mk
- packages/addons/service/minisatip/package.mk
- packages/addons/service/rsyslog/package.mk
- packages/addons/service/snapclient/package.mk
- packages/addons/service/snapserver/package.mk
- packages/addons/service/syncthing/package.mk
- backport of #10517 
- minisatip: update to 2.0.34 and addon (5)
- snapserver: update to 0.33.0 and addon (1)
- snapclient: update to 0.33.0 and addon (1)
- snapcast: update to 0.33.0
- asio: update to 1.36.0
- syncthing: update to 2.0.9 and addon (7)
- filebrowser: update to 2.43.0 and addon (2)
- rsyslog: update addon (2)
- librelp: update to 1.12.0
> [le12.2] Addon updates 

- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
- vulkan-headers: update to 1.4.328
- vulkan-loader: update to 1.4.328
- vulkan-tools: update to 1.4.328
> Vulkan update to 1.4.328

- packages/graphics/spirv-llvm-translator/package.mk
- packages/lang/llvm/package.mk
- packages/rust/cargo-snapshot/package.mk
- packages/rust/rust-std-snapshot/package.mk
- packages/rust/rust/package.mk
- packages/rust/rust/targets/aarch64-libreelec-linux-gnu.json
- packages/rust/rust/targets/arm-libreelec-linux-gnueabihf.json
- packages/rust/rust/targets/x86_64-libreelec-linux-gnu.json
- packages/rust/rustc-snapshot/package.mk
~~Required rust-1.90.0 (18th September 2025) before this can be merged.~~
- llvm: update to 21.1.1
- spirv-llvm-translator: update to 21.1.0
- spirv-tools: update to githash 925b0bd
- spirv-headers: update to githash 1de2e41
- rust: update to 1.90.0
- rustc-snapshot: update to 1.90.0
- rust-std-snapshot: update to 1.90.0
- cargo-snapshot: update to 1.90.0
> llvm: update to 21.1.y

- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- linux: update to 6.16.9
- iwlwifi-firmware: update to githash 8f70df6
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.8
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.9
6.16.8 - 189 patches
6.16.9 - 149 patches
- done
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.16
``` …
```
> linux: update to 6.16.9

- packages/linux-firmware/iwlwifi-firmware/package.mk
- packages/linux/package.mk
- backport of #10525
-  linux: update to 6.16.9
- iwlwifi-firmware: update to githash 8f70df6
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.8
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.16.9
6.16.8 - 189 patches
6.16.9 - 149 patches
- done
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.16.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.16
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 …
```
> [le12.2] linux: update to 6.16.9

- packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
> [le12.0] inputstream.adaptive: update to 21.5.16-Omega

- packages/audio/alsa-utils/udev.d/90-alsa-restore.rules
- packages/audio/rpi-cirrus-config/udev.d/90-alsa-restore.rules
Our downstream udev rule has been carrying a meaningless `NAME="snd/%k"` action since forever that just results in an error message being logged to the journal - see also #10532
```
/usr/lib/udev/rules.d/90-alsa-restore.rules:5 NAME="snd/%k": Only network interfaces can be renamed, ignoring.
```
Drop that and also add the `SUBSYSTEM=="sound"` check like in the upstream alsa-tools udev rule
> fix error in 90-alsa-restore.rules udev rule

- packages/network/bluez/system.d/bluetooth.service
Align our bluetooth.service unit with upstream:
Specify the correct dbus service type, add bus name and add the alias so pulseaudio stops complaining about the missing dbus-org.bluez.service
See #10532
> bluez: fix bluetooth.service unit

- packages/security/openssl/package.mk
- backport #10541 
- Release notes:
Release notes:
> [le12.2] openssl: update to 3.5.4

- packages/linux/package.mk
- packages/tools/rpi-eeprom/package.mk
> [le12.2] linux (RPi): update to 6.12.51

- config/functions
Meson reverses meaning of environment variables for host and target tools. This also causes that STRIP variable points to different binary that every script expects. In general that's not an issue unless host distro has a buggy binutils version.
With this fix there is one less dependency on host distro.
Ref: https://forum.libreelec.tv/thread/29840-buildsystem-cant-create-working-upgrade-tar-file-for-rpi4-with-gentoo-linux/
Ref: https://github.com/LibreELEC/LibreELEC.tv/pull/3776
NOTE: I'm open to suggestions for better solution. I was thinking to basically revert #3776 and just unset env variables that are accepted by meson. Since they were set to host instead of target tools, they were most likely unused. Otherwise at least linker or compiler would complain about unknown flags or …
> functions: Fix strip cmd for meson
